export const ACTION_TYPES = [
  "book_completed",
  "bible_in_one_year_day_viewed",
  "chapter_completed",
  "devotional_day_completed",
  "devotional_day_started",
  "devotional_day_viewed",
  "keyword_mastered",
  "keyword_viewed",
  "note_started",
  "note_created",
  "person_viewed",
  "person_learned",
  "place_discovered",
  "place_viewed",
  "reading_plan_chapter_completed",
  "trivia_question_answered",
  "trivia_started",
  "user_login",
  "user_signup",
  "user_upgraded",
  "chapter_notes_viewed",
  "verse_highlighted",
  "understand_verse_of_the_day",
  "feed_post_thought",
  "feed_post_prayer",
  "feed_post_prayer_request",
  "feed_post_photo",
  "feed_post_video",
  "feed_post_liked",
  "feed_post_commented",
  "feed_post_replied",
  "buddy_added",
  "group_message_sent",
  "series_week_started",
  "study_group_feed_viewed",
  "study_group_article_opened",
  "study_group_bible_study_card_opened",
] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE = {
  book_completed: "book_completed",
  bible_in_one_year_day_viewed: "bible_in_one_year_day_viewed",
  chapter_completed: "chapter_completed",
  devotional_day_completed: "devotional_day_completed",
  devotional_day_started: "devotional_day_started",
  devotional_day_viewed: "devotional_day_viewed",
  keyword_mastered: "keyword_mastered",
  keyword_viewed: "keyword_viewed",
  note_started: "note_started",
  note_created: "note_created",
  person_viewed: "person_viewed",
  person_learned: "person_learned",
  place_discovered: "place_discovered",
  place_viewed: "place_viewed",
  reading_plan_chapter_completed: "reading_plan_chapter_completed",
  trivia_question_answered: "trivia_question_answered",
  trivia_started: "trivia_started",
  user_login: "user_login",
  user_signup: "user_signup",
  user_upgraded: "user_upgraded",
  chapter_notes_viewed: "chapter_notes_viewed",
  verse_highlighted: "verse_highlighted",
  understand_verse_of_the_day: "understand_verse_of_the_day",
  feed_post_thought: "feed_post_thought",
  feed_post_prayer: "feed_post_prayer",
  feed_post_prayer_request: "feed_post_prayer_request",
  feed_post_photo: "feed_post_photo",
  feed_post_video: "feed_post_video",
  feed_post_liked: "feed_post_liked",
  feed_post_commented: "feed_post_commented",
  feed_post_replied: "feed_post_replied",
  buddy_added: "buddy_added",
  group_message_sent: "group_message_sent",
  series_week_started: "series_week_started",
  study_group_feed_viewed: "study_group_feed_viewed",
  study_group_article_opened: "study_group_article_opened",
  study_group_bible_study_card_opened: "study_group_bible_study_card_opened",
} as const satisfies Record<ActionType, ActionType>;

export function isActionType(value: string): value is ActionType {
  return (ACTION_TYPES as readonly string[]).includes(value);
}
