export const ACTION_TYPES = [
  "guided_studies_viewed",
  "guided_study_tool_opened",
  "devotionals_viewed",
  "devotional_opened",
  "devotional_day_opened",
  "devotional_bible_reading_opened",
  "devotional_reflection_saved",
  "reading_plans_viewed",
  "reading_plan_opened",
  "reading_plan_day_opened",
  "reading_plan_chapter_opened",
  "bible_study_games_viewed",
  "bible_game_opened",
  "trivia_hub_viewed",
  "trivia_category_opened",
  "trivia_pack_opened",
  "scrambled_hub_viewed",
  "scrambled_category_opened",
  "scrambled_books_viewed",
  "scrambled_book_opened",
  "scrambled_book_viewed",
  "scrambled_chapter_opened",
  "scrambled_chapter_completed",
  "dashboard_viewed",
  "dashboard_card_opened",
  "invite_buddy_opened",
  "landing_page_visited",
  "landing_cta_clicked",
  "onboarding_intro_viewed",
  "onboarding_intro_started",
  "onboarding_intro_skipped",
  "onboarding_question_completed",
  "onboarding_results_viewed",
  "onboarding_journey_started",
  "dashboard_tour_started",
  "dashboard_tour_completed",
  "dashboard_tour_skipped",
  "bible_year_day_start_popup_viewed",
  "bible_year_day_start_popup_clicked",
  "bible_year_task_started",
  "bible_year_task_completed",
  "follow_along_scripture_opened",
  "free_account_popup_viewed",
  "free_account_popup_skipped",
  "profile_creation_popup_completed",
  "profile_creation_popup_skipped",
  "upgrade_popup_viewed",
  "upgrade_popup_cta_clicked",
  "upgrade_popup_dismissed",
  "trial_popup_viewed",
  "trial_started",
  "trial_canceled",
  "trial_converted",
  "book_completed",
  "bible_in_one_year_started",
  "bible_in_one_year_day_viewed",
  "bible_in_one_year_reading_completed",
  "bible_in_one_year_trivia_completed",
  "bible_in_one_year_reflection_completed",
  "bible_reader_viewed",
  "bible_book_opened",
  "bible_book_viewed",
  "bible_chapter_opened",
  "bible_chapter_viewed",
  "chapter_completed",
  "devotional_day_completed",
  "devotional_day_started",
  "devotional_day_viewed",
  "keyword_mastered",
  "keyword_viewed",
  "note_started",
  "note_created",
  "person_viewed",
  "person_learned",
  "place_discovered",
  "place_viewed",
  "reading_plan_chapter_completed",
  "scrambled_word_answered",
  "trivia_question_answered",
  "trivia_question_correct",
  "trivia_chapter_completed",
  "trivia_started",
  "user_login",
  "user_signup",
  "user_upgraded",
  "chapter_notes_viewed",
  "chapter_notes_reviewed",
  "deep_study_interest_clicked",
  "study_notes_viewed",
  "study_notes_section_opened",
  "verse_highlighted",
  "understand_verse_of_the_day",
  "feed_post_thought",
  "feed_post_prayer",
  "feed_post_prayer_request",
  "feed_post_photo",
  "feed_post_video",
  "feed_post_liked",
  "feed_post_commented",
  "feed_post_replied",
  "buddy_added",
  "group_message_sent",
  "series_week_started",
  "series_week_notes_opened",
  "study_group_feed_viewed",
  "study_group_article_opened",
  "study_group_bible_study_card_opened",
  "bible_buddy_tv_viewed",
  "bible_buddy_tv_title_opened",
  "bible_buddy_tv_video_started",
  "bible_topic_lesson_completed",
  "louis_opened",
  "louis_user_message_sent",
  "louis_ai_message_sent",
  "louis_daily_message_shown",
  "louis_route_handoff_shown",
  "louis_daily_task_bonus",
  "referral_signup_reward",
  "badge_earned",
] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE = {
  guided_studies_viewed: "guided_studies_viewed",
  guided_study_tool_opened: "guided_study_tool_opened",
  devotionals_viewed: "devotionals_viewed",
  devotional_opened: "devotional_opened",
  devotional_day_opened: "devotional_day_opened",
  devotional_bible_reading_opened: "devotional_bible_reading_opened",
  devotional_reflection_saved: "devotional_reflection_saved",
  reading_plans_viewed: "reading_plans_viewed",
  reading_plan_opened: "reading_plan_opened",
  reading_plan_day_opened: "reading_plan_day_opened",
  reading_plan_chapter_opened: "reading_plan_chapter_opened",
  bible_study_games_viewed: "bible_study_games_viewed",
  bible_game_opened: "bible_game_opened",
  trivia_hub_viewed: "trivia_hub_viewed",
  trivia_category_opened: "trivia_category_opened",
  trivia_pack_opened: "trivia_pack_opened",
  scrambled_hub_viewed: "scrambled_hub_viewed",
  scrambled_category_opened: "scrambled_category_opened",
  scrambled_books_viewed: "scrambled_books_viewed",
  scrambled_book_opened: "scrambled_book_opened",
  scrambled_book_viewed: "scrambled_book_viewed",
  scrambled_chapter_opened: "scrambled_chapter_opened",
  scrambled_chapter_completed: "scrambled_chapter_completed",
  dashboard_viewed: "dashboard_viewed",
  dashboard_card_opened: "dashboard_card_opened",
  invite_buddy_opened: "invite_buddy_opened",
  landing_page_visited: "landing_page_visited",
  landing_cta_clicked: "landing_cta_clicked",
  onboarding_intro_viewed: "onboarding_intro_viewed",
  onboarding_intro_started: "onboarding_intro_started",
  onboarding_intro_skipped: "onboarding_intro_skipped",
  onboarding_question_completed: "onboarding_question_completed",
  onboarding_results_viewed: "onboarding_results_viewed",
  onboarding_journey_started: "onboarding_journey_started",
  dashboard_tour_started: "dashboard_tour_started",
  dashboard_tour_completed: "dashboard_tour_completed",
  dashboard_tour_skipped: "dashboard_tour_skipped",
  bible_year_day_start_popup_viewed: "bible_year_day_start_popup_viewed",
  bible_year_day_start_popup_clicked: "bible_year_day_start_popup_clicked",
  bible_year_task_started: "bible_year_task_started",
  bible_year_task_completed: "bible_year_task_completed",
  follow_along_scripture_opened: "follow_along_scripture_opened",
  free_account_popup_viewed: "free_account_popup_viewed",
  free_account_popup_skipped: "free_account_popup_skipped",
  profile_creation_popup_completed: "profile_creation_popup_completed",
  profile_creation_popup_skipped: "profile_creation_popup_skipped",
  upgrade_popup_viewed: "upgrade_popup_viewed",
  upgrade_popup_cta_clicked: "upgrade_popup_cta_clicked",
  upgrade_popup_dismissed: "upgrade_popup_dismissed",
  trial_popup_viewed: "trial_popup_viewed",
  trial_started: "trial_started",
  trial_canceled: "trial_canceled",
  trial_converted: "trial_converted",
  book_completed: "book_completed",
  bible_in_one_year_started: "bible_in_one_year_started",
  bible_in_one_year_day_viewed: "bible_in_one_year_day_viewed",
  bible_in_one_year_reading_completed: "bible_in_one_year_reading_completed",
  bible_in_one_year_trivia_completed: "bible_in_one_year_trivia_completed",
  bible_in_one_year_reflection_completed: "bible_in_one_year_reflection_completed",
  bible_reader_viewed: "bible_reader_viewed",
  bible_book_opened: "bible_book_opened",
  bible_book_viewed: "bible_book_viewed",
  bible_chapter_opened: "bible_chapter_opened",
  bible_chapter_viewed: "bible_chapter_viewed",
  chapter_completed: "chapter_completed",
  devotional_day_completed: "devotional_day_completed",
  devotional_day_started: "devotional_day_started",
  devotional_day_viewed: "devotional_day_viewed",
  keyword_mastered: "keyword_mastered",
  keyword_viewed: "keyword_viewed",
  note_started: "note_started",
  note_created: "note_created",
  person_viewed: "person_viewed",
  person_learned: "person_learned",
  place_discovered: "place_discovered",
  place_viewed: "place_viewed",
  reading_plan_chapter_completed: "reading_plan_chapter_completed",
  scrambled_word_answered: "scrambled_word_answered",
  trivia_question_answered: "trivia_question_answered",
  trivia_question_correct: "trivia_question_correct",
  trivia_chapter_completed: "trivia_chapter_completed",
  trivia_started: "trivia_started",
  user_login: "user_login",
  user_signup: "user_signup",
  user_upgraded: "user_upgraded",
  chapter_notes_viewed: "chapter_notes_viewed",
  chapter_notes_reviewed: "chapter_notes_reviewed",
  deep_study_interest_clicked: "deep_study_interest_clicked",
  study_notes_viewed: "study_notes_viewed",
  study_notes_section_opened: "study_notes_section_opened",
  verse_highlighted: "verse_highlighted",
  understand_verse_of_the_day: "understand_verse_of_the_day",
  feed_post_thought: "feed_post_thought",
  feed_post_prayer: "feed_post_prayer",
  feed_post_prayer_request: "feed_post_prayer_request",
  feed_post_photo: "feed_post_photo",
  feed_post_video: "feed_post_video",
  feed_post_liked: "feed_post_liked",
  feed_post_commented: "feed_post_commented",
  feed_post_replied: "feed_post_replied",
  buddy_added: "buddy_added",
  group_message_sent: "group_message_sent",
  series_week_started: "series_week_started",
  series_week_notes_opened: "series_week_notes_opened",
  study_group_feed_viewed: "study_group_feed_viewed",
  study_group_article_opened: "study_group_article_opened",
  study_group_bible_study_card_opened: "study_group_bible_study_card_opened",
  bible_buddy_tv_viewed: "bible_buddy_tv_viewed",
  bible_buddy_tv_title_opened: "bible_buddy_tv_title_opened",
  bible_buddy_tv_video_started: "bible_buddy_tv_video_started",
  bible_topic_lesson_completed: "bible_topic_lesson_completed",
  louis_opened: "louis_opened",
  louis_user_message_sent: "louis_user_message_sent",
  louis_ai_message_sent: "louis_ai_message_sent",
  louis_daily_message_shown: "louis_daily_message_shown",
  louis_route_handoff_shown: "louis_route_handoff_shown",
  louis_daily_task_bonus: "louis_daily_task_bonus",
  referral_signup_reward: "referral_signup_reward",
  badge_earned: "badge_earned",
} as const satisfies Record<ActionType, ActionType>;

export function isActionType(value: string): value is ActionType {
  return (ACTION_TYPES as readonly string[]).includes(value);
}
