export const ACTION_TYPES = [
  "guided_studies_viewed",
  "guided_study_tool_opened",
  "devotionals_viewed",
  "devotional_opened",
  "devotional_day_opened",
  "devotional_bible_reading_opened",
  "devotional_reflection_saved",
  "reading_plans_viewed",
  "reading_plan_opened",
  "reading_plan_day_opened",
  "reading_plan_chapter_opened",
  "bible_study_games_viewed",
  "bible_game_opened",
  "trivia_hub_viewed",
  "trivia_category_opened",
  "trivia_pack_opened",
  "scrambled_hub_viewed",
  "scrambled_category_opened",
  "scrambled_books_viewed",
  "scrambled_book_opened",
  "scrambled_book_viewed",
  "scrambled_chapter_opened",
  "scrambled_chapter_completed",
  "dashboard_viewed",
  "dashboard_card_opened",
  "invite_buddy_opened",
  "book_completed",
  "bible_in_one_year_day_viewed",
  "bible_reader_viewed",
  "bible_book_opened",
  "bible_book_viewed",
  "bible_chapter_opened",
  "bible_chapter_viewed",
  "chapter_completed",
  "devotional_day_completed",
  "devotional_day_started",
  "devotional_day_viewed",
  "keyword_mastered",
  "keyword_viewed",
  "note_started",
  "note_created",
  "person_viewed",
  "person_learned",
  "place_discovered",
  "place_viewed",
  "reading_plan_chapter_completed",
  "scrambled_word_answered",
  "trivia_question_answered",
  "trivia_question_correct",
  "trivia_chapter_completed",
  "trivia_started",
  "user_login",
  "user_signup",
  "user_upgraded",
  "chapter_notes_viewed",
  "chapter_notes_reviewed",
  "verse_highlighted",
  "understand_verse_of_the_day",
  "feed_post_thought",
  "feed_post_prayer",
  "feed_post_prayer_request",
  "feed_post_photo",
  "feed_post_video",
  "feed_post_liked",
  "feed_post_commented",
  "feed_post_replied",
  "buddy_added",
  "group_message_sent",
  "series_week_started",
  "study_group_feed_viewed",
  "study_group_article_opened",
  "study_group_bible_study_card_opened",
  "bible_buddy_tv_viewed",
  "bible_buddy_tv_title_opened",
  "bible_buddy_tv_video_started",
  "louis_opened",
  "louis_user_message_sent",
  "louis_ai_message_sent",
  "louis_daily_message_shown",
  "louis_route_handoff_shown",
] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE = {
  guided_studies_viewed: "guided_studies_viewed",
  guided_study_tool_opened: "guided_study_tool_opened",
  devotionals_viewed: "devotionals_viewed",
  devotional_opened: "devotional_opened",
  devotional_day_opened: "devotional_day_opened",
  devotional_bible_reading_opened: "devotional_bible_reading_opened",
  devotional_reflection_saved: "devotional_reflection_saved",
  reading_plans_viewed: "reading_plans_viewed",
  reading_plan_opened: "reading_plan_opened",
  reading_plan_day_opened: "reading_plan_day_opened",
  reading_plan_chapter_opened: "reading_plan_chapter_opened",
  bible_study_games_viewed: "bible_study_games_viewed",
  bible_game_opened: "bible_game_opened",
  trivia_hub_viewed: "trivia_hub_viewed",
  trivia_category_opened: "trivia_category_opened",
  trivia_pack_opened: "trivia_pack_opened",
  scrambled_hub_viewed: "scrambled_hub_viewed",
  scrambled_category_opened: "scrambled_category_opened",
  scrambled_books_viewed: "scrambled_books_viewed",
  scrambled_book_opened: "scrambled_book_opened",
  scrambled_book_viewed: "scrambled_book_viewed",
  scrambled_chapter_opened: "scrambled_chapter_opened",
  scrambled_chapter_completed: "scrambled_chapter_completed",
  dashboard_viewed: "dashboard_viewed",
  dashboard_card_opened: "dashboard_card_opened",
  invite_buddy_opened: "invite_buddy_opened",
  book_completed: "book_completed",
  bible_in_one_year_day_viewed: "bible_in_one_year_day_viewed",
  bible_reader_viewed: "bible_reader_viewed",
  bible_book_opened: "bible_book_opened",
  bible_book_viewed: "bible_book_viewed",
  bible_chapter_opened: "bible_chapter_opened",
  bible_chapter_viewed: "bible_chapter_viewed",
  chapter_completed: "chapter_completed",
  devotional_day_completed: "devotional_day_completed",
  devotional_day_started: "devotional_day_started",
  devotional_day_viewed: "devotional_day_viewed",
  keyword_mastered: "keyword_mastered",
  keyword_viewed: "keyword_viewed",
  note_started: "note_started",
  note_created: "note_created",
  person_viewed: "person_viewed",
  person_learned: "person_learned",
  place_discovered: "place_discovered",
  place_viewed: "place_viewed",
  reading_plan_chapter_completed: "reading_plan_chapter_completed",
  scrambled_word_answered: "scrambled_word_answered",
  trivia_question_answered: "trivia_question_answered",
  trivia_question_correct: "trivia_question_correct",
  trivia_chapter_completed: "trivia_chapter_completed",
  trivia_started: "trivia_started",
  user_login: "user_login",
  user_signup: "user_signup",
  user_upgraded: "user_upgraded",
  chapter_notes_viewed: "chapter_notes_viewed",
  chapter_notes_reviewed: "chapter_notes_reviewed",
  verse_highlighted: "verse_highlighted",
  understand_verse_of_the_day: "understand_verse_of_the_day",
  feed_post_thought: "feed_post_thought",
  feed_post_prayer: "feed_post_prayer",
  feed_post_prayer_request: "feed_post_prayer_request",
  feed_post_photo: "feed_post_photo",
  feed_post_video: "feed_post_video",
  feed_post_liked: "feed_post_liked",
  feed_post_commented: "feed_post_commented",
  feed_post_replied: "feed_post_replied",
  buddy_added: "buddy_added",
  group_message_sent: "group_message_sent",
  series_week_started: "series_week_started",
  study_group_feed_viewed: "study_group_feed_viewed",
  study_group_article_opened: "study_group_article_opened",
  study_group_bible_study_card_opened: "study_group_bible_study_card_opened",
  bible_buddy_tv_viewed: "bible_buddy_tv_viewed",
  bible_buddy_tv_title_opened: "bible_buddy_tv_title_opened",
  bible_buddy_tv_video_started: "bible_buddy_tv_video_started",
  louis_opened: "louis_opened",
  louis_user_message_sent: "louis_user_message_sent",
  louis_ai_message_sent: "louis_ai_message_sent",
  louis_daily_message_shown: "louis_daily_message_shown",
  louis_route_handoff_shown: "louis_route_handoff_shown",
} as const satisfies Record<ActionType, ActionType>;

export function isActionType(value: string): value is ActionType {
  return (ACTION_TYPES as readonly string[]).includes(value);
}
