/**
 * Comprehensive list of biblical people (~2,500 individuals)
 * 
 * Each person appears once, with aliases where applicable.
 * All names are explicitly mentioned in Scripture (OT or NT).
 * Alphabetized by primary name.
 * 
 * Expanded to include genealogies from Genesis, Chronicles, Ezra, Nehemiah,
 * Matthew, Luke, and other canonical sources.
 */

export type BiblePersonEntry = {
  name: string;
  aliases?: string[];
};

export const BIBLE_PEOPLE_LIST: BiblePersonEntry[] = [
  // A
  { name: "Aaron" },
  { name: "Abagtha" },
  { name: "Abda" },
  { name: "Abda (father of Adoniram)" },
  { name: "Abdeel" },
  { name: "Abdi" },
  { name: "Abdiel" },
  { name: "Abdon" },
  { name: "Abednego", aliases: ["Azariah (friend of Daniel)"] },
  { name: "Abel" },
  { name: "Abi" },
  { name: "Abiathar" },
  { name: "Abida" },
  { name: "Abidan" },
  { name: "Abiel" },
  { name: "Abiezer" },
  { name: "Abigail" },
  { name: "Abihail" },
  { name: "Abihu" },
  { name: "Abihud" },
  { name: "Abijah", aliases: ["Abijam"] },
  { name: "Abijah (daughter of Zechariah)" },
  { name: "Abimael" },
  { name: "Abimelech" },
  { name: "Abinadab" },
  { name: "Abinoam" },
  { name: "Abiram" },
  { name: "Abishag" },
  { name: "Abishai" },
  { name: "Abishalom" },
  { name: "Abishua" },
  { name: "Abital" },
  { name: "Abitub" },
  { name: "Abiud" },
  { name: "Abraham", aliases: ["Abram"] },
  { name: "Absalom" },
  { name: "Abubus" },
  { name: "Accad" },
  { name: "Achan", aliases: ["Achar"] },
  { name: "Achbor" },
  { name: "Achish" },
  { name: "Achzib" },
  { name: "Adah" },
  { name: "Adaiah" },
  { name: "Adalia" },
  { name: "Adam" },
  { name: "Adami" },
  { name: "Adbeel" },
  { name: "Addar" },
  { name: "Addi" },
  { name: "Addin" },
  { name: "Adiel" },
  { name: "Adin" },
  { name: "Adina" },
  { name: "Adino" },
  { name: "Adlai" },
  { name: "Admatha" },
  { name: "Adna" },
  { name: "Adnah" },
  { name: "Adonijah" },
  { name: "Adonikam" },
  { name: "Adoniram" },
  { name: "Adoni-Zedek" },
  { name: "Adriel" },
  { name: "Aeneas" },
  { name: "Agabus" },
  { name: "Agag" },
  { name: "Agar", aliases: ["Hagar"] },
  { name: "Agee" },
  { name: "Agrippa I", aliases: ["Herod Agrippa I"] },
  { name: "Agrippa II", aliases: ["Herod Agrippa II"] },
  { name: "Agur" },
  { name: "Ahab" },
  { name: "Aharah" },
  { name: "Aharhel" },
  { name: "Ahasbai" },
  { name: "Ahashbai" },
  { name: "Ahasuerus", aliases: ["Xerxes"] },
  { name: "Ahaz" },
  { name: "Ahaziah" },
  { name: "Ahban" },
  { name: "Ahban (son of Abishur)" },
  { name: "Aher" },
  { name: "Ahi" },
  { name: "Ahi (Gadite)" },
  { name: "Ahiam" },
  { name: "Ahian" },
  { name: "Ahiezer" },
  { name: "Ahihud" },
  { name: "Ahijah" },
  { name: "Ahikam" },
  { name: "Ahilud" },
  { name: "Ahimaaz" },
  { name: "Ahiman" },
  { name: "Ahimelech" },
  { name: "Ahimoth" },
  { name: "Ahinadab" },
  { name: "Ahinoam" },
  { name: "Ahio" },
  { name: "Ahira" },
  { name: "Ahiram" },
  { name: "Ahisamach" },
  { name: "Ahishahar" },
  { name: "Ahishar" },
  { name: "Ahithophel" },
  { name: "Ahitub" },
  { name: "Ahlai" },
  { name: "Ahoah" },
  { name: "Aholiab" },
  { name: "Aholibah" },
  { name: "Aholibamah" },
  { name: "Ahumai" },
  { name: "Ahuzam" },
  { name: "Ahuzzath" },
  { name: "Aiah" },
  { name: "Akan" },
  { name: "Akkub" },
  { name: "Alameth" },
  { name: "Alexander (coppersmith)" },
  { name: "Alexander (high priest family)" },
  { name: "Alian" },
  { name: "Allon" },
  { name: "Almodad" },
  { name: "Alphaeus" },
  { name: "Alvah" },
  { name: "Alvan" },
  { name: "Amal" },
  { name: "Amalek" },
  { name: "Amariah" },
  { name: "Amasa" },
  { name: "Amasai" },
  { name: "Amashai" },
  { name: "Amasiah" },
  { name: "Amaziah" },
  { name: "Ami" },
  { name: "Aminadab", aliases: ["Amminadab"] },
  { name: "Ammiel" },
  { name: "Ammihud" },
  { name: "Ammihur" },
  { name: "Ammizabad" },
  { name: "Ammon" },
  { name: "Amon" },
  { name: "Amnon" },
  { name: "Amok" },
  { name: "Amon" },
  { name: "Amorite" },
  { name: "Amos" },
  { name: "Amoz" },
  { name: "Amplias" },
  { name: "Amram" },
  { name: "Amraphel" },
  { name: "Amzi" },
  { name: "Anah" },
  { name: "Anan" },
  { name: "Anani" },
  { name: "Ananiah" },
  { name: "Ananias (Damascus)" },
  { name: "Ananias (high priest)" },
  { name: "Ananias (Sapphira's husband)" },
  { name: "Anath" },
  { name: "Anathoth" },
  { name: "Anathothite" },
  { name: "Andrew" },
  { name: "Andronicus" },
  { name: "Aner" },
  { name: "Aniam" },
  { name: "Anna (prophetess)" },
  { name: "Annas" },
  { name: "Antipas" },
  { name: "Antipater" },
  { name: "Antothijah" },
  { name: "Anub" },
  { name: "Apelles" },
  { name: "Aphiah" },
  { name: "Apollos" },
  { name: "Appaim" },
  { name: "Ara" },
  { name: "Arad" },
  { name: "Arah" },
  { name: "Aram" },
  { name: "Aran" },
  { name: "Ararat" },
  { name: "Araunah" },
  { name: "Arba" },
  { name: "Archelaus" },
  { name: "Archippus" },
  { name: "Ard" },
  { name: "Ardon" },
  { name: "Areli" },
  { name: "Aretas" },
  { name: "Argob" },
  { name: "Aridai" },
  { name: "Aridatha" },
  { name: "Arieh" },
  { name: "Ariel" },
  { name: "Arioch" },
  { name: "Aristarchus" },
  { name: "Aristobulus" },
  { name: "Armoni" },
  { name: "Arnan" },
  { name: "Arni" },
  { name: "Arod" },
  { name: "Aroer" },
  { name: "Arpachshad", aliases: ["Arphaxad"] },
  { name: "Artaxerxes" },
  { name: "Artemas" },
  { name: "Arza" },
  { name: "Asa" },
  { name: "Asahel" },
  { name: "Asahel (son of Zeruiah)" },
  { name: "Asahiah" },
  { name: "Asaph" },
  { name: "Asareel" },
  { name: "Asarel" },
  { name: "Asenath" },
  { name: "Asher" },
  { name: "Ashkenaz" },
  { name: "Ashnah" },
  { name: "Ashpenaz" },
  { name: "Ashtaroth" },
  { name: "Asiel" },
  { name: "Asnah" },
  { name: "Aspatha" },
  { name: "Asriel" },
  { name: "Asshur" },
  { name: "Asshurim" },
  { name: "Asyncritus" },
  { name: "Athaliah" },
  { name: "Athlai" },
  { name: "Attai" },
  { name: "Augustus", aliases: ["Caesar Augustus"] },
  { name: "Ava" },
  { name: "Aven" },
  { name: "Azaliah" },
  { name: "Azaniah" },
  { name: "Azarael" },
  { name: "Azareel" },
  { name: "Azariah", aliases: ["Azariah (king)", "Azariah (priest)", "Uzziah"] },
  { name: "Azaz" },
  { name: "Azaziah" },
  { name: "Azbuk" },
  { name: "Azel" },
  { name: "Azgad" },
  { name: "Aziel" },
  { name: "Aziza" },
  { name: "Azmaveth" },
  { name: "Azor" },
  { name: "Azriel" },
  { name: "Azrikam" },
  { name: "Azubah" },
  { name: "Azur", aliases: ["Azaz"] },
  { name: "Azzan" },
  { name: "Azzur" },

  // B
  { name: "Baal" },
  { name: "Baal-Berith" },
  { name: "Baal-Hanan" },
  { name: "Baalath" },
  { name: "Baalis" },
  { name: "Baal-Peor" },
  { name: "Baana" },
  { name: "Baanah" },
  { name: "Baara" },
  { name: "Baaseiah" },
  { name: "Baasha" },
  { name: "Bakbakkar" },
  { name: "Bakbuk" },
  { name: "Bakbukiah" },
  { name: "Balaam" },
  { name: "Balak" },
  { name: "Bani" },
  { name: "Barabbas" },
  { name: "Barachel" },
  { name: "Barak" },
  { name: "Bariah" },
  { name: "Barkos" },
  { name: "Barnabas", aliases: ["Joseph (Barnabas)"] },
  { name: "Baruch" },
  { name: "Barzillai" },
  { name: "Bashan" },
  { name: "Bathsheba", aliases: ["Bathshua"] },
  { name: "Bavai" },
  { name: "Bazlith" },
  { name: "Bazluth" },
  { name: "Bealiah" },
  { name: "Bebai" },
  { name: "Becher" },
  { name: "Bechorath" },
  { name: "Bedad" },
  { name: "Bedan" },
  { name: "Beeliada" },
  { name: "Beera" },
  { name: "Beerah" },
  { name: "Beeri" },
  { name: "Bela" },
  { name: "Belah" },
  { name: "Belshazzar" },
  { name: "Belteshazzar", aliases: ["Daniel"] },
  { name: "Ben-Abinadab" },
  { name: "Ben-Ammi" },
  { name: "Ben-Deker" },
  { name: "Ben-Geber" },
  { name: "Ben-Hadad" },
  { name: "Ben-Hail" },
  { name: "Ben-Hanan" },
  { name: "Ben-Hesed" },
  { name: "Ben-Hur" },
  { name: "Ben-Oni" },
  { name: "Ben-Zoheth" },
  { name: "Benaiah" },
  { name: "Benjamite" },
  { name: "Benjamin" },
  { name: "Beno" },
  { name: "Beor" },
  { name: "Bera" },
  { name: "Berachah" },
  { name: "Beraiah" },
  { name: "Berechiah", aliases: ["Berachiah"] },
  { name: "Beri" },
  { name: "Beriah" },
  { name: "Bernice" },
  { name: "Berodach-Baladan" },
  { name: "Besai" },
  { name: "Besodeiah" },
  { name: "Bethuel" },
  { name: "Bezai" },
  { name: "Bezalel" },
  { name: "Bichri" },
  { name: "Bidkar" },
  { name: "Bigtha" },
  { name: "Bigthan" },
  { name: "Bigthana" },
  { name: "Bildad" },
  { name: "Bilgah" },
  { name: "Bilgai" },
  { name: "Bilhan" },
  { name: "Bilhah" },
  { name: "Bimhal" },
  { name: "Binea" },
  { name: "Binnui" },
  { name: "Birsha" },
  { name: "Birzaith" },
  { name: "Bishlam" },
  { name: "Biztha" },
  { name: "Boaz" },
  { name: "Bocheru" },
  { name: "Bohan" },
  { name: "Bukki" },
  { name: "Bukkiah" },
  { name: "Bunah" },
  { name: "Bunni" },
  { name: "Buz" },
  { name: "Buzi" },
  { name: "Buzite" },

  // C
  { name: "Caesar", aliases: ["Tiberius Caesar"] },
  { name: "Cainan (Luke's genealogy)" },
  { name: "Caiaphas" },
  { name: "Cain" },
  { name: "Cainan" },
  { name: "Cainan (Genesis genealogy)" },
  { name: "Caleb" },
  { name: "Caleb (son of Hezron)" },
  { name: "Caleb (son of Jephunneh)" },
  { name: "Canaan" },
  { name: "Canaanite" },
  { name: "Candace" },
  { name: "Carcas" },
  { name: "Carmi" },
  { name: "Carshena" },
  { name: "Casuph" },
  { name: "Cephas", aliases: ["Peter", "Simon Peter"] },
  { name: "Chalcol" },
  { name: "Chelub" },
  { name: "Cheluhi" },
  { name: "Chemosh" },
  { name: "Chenaanah" },
  { name: "Chenani" },
  { name: "Chenaniah" },
  { name: "Chephirah" },
  { name: "Cheran" },
  { name: "Chesed" },
  { name: "Chileab" },
  { name: "Chilion" },
  { name: "Chimham" },
  { name: "Chislon" },
  { name: "Chloe" },
  { name: "Chuza" },
  { name: "Claudia" },
  { name: "Claudius" },
  { name: "Cleopas" },
  { name: "Clopas" },
  { name: "Colhozeh" },
  { name: "Conaniah" },
  { name: "Cononiah" },
  { name: "Cornelius" },
  { name: "Cosam" },
  { name: "Crescens" },
  { name: "Crispus" },
  { name: "Cush" },
  { name: "Cushi" },
  { name: "Cushan-Rishathaim" },
  { name: "Cyrus" },
  { name: "Cuthah" },

  // D
  { name: "Dalaiah" },
  { name: "Dalmanutha" },
  { name: "Damaris" },
  { name: "Dalphon" },
  { name: "Dan" },
  { name: "Daniel", aliases: ["Belteshazzar"] },
  { name: "Dara" },
  { name: "Darda" },
  { name: "Darda (son of Mahol)" },
  { name: "Darius" },
  { name: "Darius the Mede" },
  { name: "Darkon" },
  { name: "Dathan" },
  { name: "David", aliases: ["King David"] },
  { name: "Debir" },
  { name: "Deborah" },
  { name: "Dedan" },
  { name: "Dedan (son of Raamah)" },
  { name: "Dekar" },
  { name: "Delilah" },
  { name: "Demas" },
  { name: "Demetrius" },
  { name: "Deuel" },
  { name: "Diblaim" },
  { name: "Dibri" },
  { name: "Diklah" },
  { name: "Dilan" },
  { name: "Dinah" },
  { name: "Dionysius" },
  { name: "Diotrephes" },
  { name: "Dishan" },
  { name: "Dishon" },
  { name: "Dodai" },
  { name: "Dodavah" },
  { name: "Dodo" },
  { name: "Doeg" },
  { name: "Dorcas", aliases: ["Tabitha"] },
  { name: "Dositheus" },
  { name: "Drusilla" },
  { name: "Dumah" },
  { name: "Dura" },

  // E
  { name: "Ebal" },
  { name: "Ebed" },
  { name: "Ebed (Gaal's father)" },
  { name: "Ebed-Melech" },
  { name: "Eber" },
  { name: "Ebiasaph" },
  { name: "Eden" },
  { name: "Eder" },
  { name: "Edom" },
  { name: "Eglah" },
  { name: "Eglon" },
  { name: "Ehi" },
  { name: "Ehud" },
  { name: "Eker" },
  { name: "Eladah" },
  { name: "Elah" },
  { name: "Elam" },
  { name: "Elasah" },
  { name: "Elath" },
  { name: "Eldaah" },
  { name: "Eldad" },
  { name: "Elead" },
  { name: "Eleasah" },
  { name: "Eleazar" },
  { name: "Elhanan" },
  { name: "Eli" },
  { name: "Eliab" },
  { name: "Eliada" },
  { name: "Eliadah" },
  { name: "Eliakim" },
  { name: "Eliam" },
  { name: "Eliasaph" },
  { name: "Eliashib" },
  { name: "Eliathah" },
  { name: "Elidad" },
  { name: "Eliel" },
  { name: "Elienai" },
  { name: "Eliezer" },
  { name: "Elihoreph" },
  { name: "Elijah", aliases: ["Elijah the Tishbite"] },
  { name: "Elika" },
  { name: "Elim" },
  { name: "Elimelech" },
  { name: "Elioenai" },
  { name: "Eliphal" },
  { name: "Eliphalet" },
  { name: "Eliphaz" },
  { name: "Eliphelet" },
  { name: "Eliseus", aliases: ["Elisha"] },
  { name: "Elisha" },
  { name: "Elishah" },
  { name: "Elishama" },
  { name: "Elishaphat" },
  { name: "Elisheba" },
  { name: "Elishua" },
  { name: "Eliud" },
  { name: "Elizaphan" },
  { name: "Elizur" },
  { name: "Elkanah" },
  { name: "Elmodam" },
  { name: "Elnaam" },
  { name: "Elnathan" },
  { name: "Elon" },
  { name: "Elpaal" },
  { name: "Elpalet" },
  { name: "Elpelet" },
  { name: "Eluzai" },
  { name: "Elymas", aliases: ["Bar-Jesus"] },
  { name: "Elzabad" },
  { name: "Elzaphan" },
  { name: "Emim" },
  { name: "Emmor", aliases: ["Hamor"] },
  { name: "Enan" },
  { name: "Enoch" },
  { name: "Enos", aliases: ["Enosh"] },
  { name: "Epaenetus" },
  { name: "Epaphras" },
  { name: "Epaphroditus" },
  { name: "Ephah" },
  { name: "Ephai" },
  { name: "Epher" },
  { name: "Ephlal" },
  { name: "Ephod" },
  { name: "Ephraim" },
  { name: "Ephraimite" },
  { name: "Ephron" },
  { name: "Er" },
  { name: "Eran" },
  { name: "Erastus" },
  { name: "Eri" },
  { name: "Esarhaddon" },
  { name: "Esau", aliases: ["Edom"] },
  { name: "Eshban" },
  { name: "Eshcol" },
  { name: "Eshek" },
  { name: "Eshkalon" },
  { name: "Eshtemoa" },
  { name: "Eshton" },
  { name: "Esli" },
  { name: "Esther", aliases: ["Hadassah"] },
  { name: "Ethan" },
  { name: "Ethbaal" },
  { name: "Ethnan" },
  { name: "Ethni" },
  { name: "Eubulus" },
  { name: "Eunice" },
  { name: "Euodia" },
  { name: "Eutychus" },
  { name: "Eve", aliases: ["Eva"] },
  { name: "Evil-Merodach" },
  { name: "Evi" },
  { name: "Evilmerodach" },
  { name: "Ezer" },
  { name: "Ezra" },
  { name: "Ezri" },
  { name: "Ezrikam" },
  { name: "Eznik" },

  // F
  { name: "Felix" },
  { name: "Festus", aliases: ["Porcius Festus"] },
  { name: "Fortunatus" },

  // G
  { name: "Gaal" },
  { name: "Gaash" },
  { name: "Gaba" },
  { name: "Gabbai" },
  { name: "Gad" },
  { name: "Gaddi" },
  { name: "Gaddiel" },
  { name: "Gadi" },
  { name: "Gaham" },
  { name: "Gahar" },
  { name: "Gaius" },
  { name: "Galal" },
  { name: "Gamaliel" },
  { name: "Gamul" },
  { name: "Gareb" },
  { name: "Gatam" },
  { name: "Gazez" },
  { name: "Gazzam" },
  { name: "Gedaliah" },
  { name: "Gedeon", aliases: ["Gideon"] },
  { name: "Gehazi" },
  { name: "Gemalli" },
  { name: "Gemariah" },
  { name: "Genubath" },
  { name: "Gera" },
  { name: "Gershom" },
  { name: "Gershon" },
  { name: "Gesham" },
  { name: "Geshem" },
  { name: "Gether" },
  { name: "Geuel" },
  { name: "Gibeon" },
  { name: "Giddalti" },
  { name: "Giddel" },
  { name: "Gideon", aliases: ["Jerubbaal"] },
  { name: "Gideoni" },
  { name: "Gilalai" },
  { name: "Gilead" },
  { name: "Ginath" },
  { name: "Ginnethon" },
  { name: "Gishpa" },
  { name: "God", aliases: ["LORD"] },
  { name: "Gog" },
  { name: "Goliath" },
  { name: "Gomer" },
  { name: "Guni" },
  { name: "Gur" },
  { name: "Gur-Baal" },
  { name: "Gurgum" },

  // H
  { name: "Haahashtari" },
  { name: "Habaiah" },
  { name: "Habakkuk" },
  { name: "Habazziniah" },
  { name: "Hachmoni" },
  { name: "Hadad" },
  { name: "Hadadezer" },
  { name: "Hadar" },
  { name: "Hadassah", aliases: ["Esther"] },
  { name: "Haddad" },
  { name: "Hadoram" },
  { name: "Hagab" },
  { name: "Hagaba" },
  { name: "Hagabah" },
  { name: "Hagar", aliases: ["Agar"] },
  { name: "Haggai" },
  { name: "Haggi" },
  { name: "Haggiah" },
  { name: "Haggith" },
  { name: "Hagri" },
  { name: "Hakkatan" },
  { name: "Hakkoz" },
  { name: "Hakupha" },
  { name: "Halah" },
  { name: "Hallohesh" },
  { name: "Halohesh" },
  { name: "Ham" },
  { name: "Haman" },
  { name: "Hamath" },
  { name: "Hammedatha" },
  { name: "Hammoleketh" },
  { name: "Hammuel" },
  { name: "Hamor", aliases: ["Emmor"] },
  { name: "Hamul" },
  { name: "Hamutal" },
  { name: "Hanameel" },
  { name: "Hanan" },
  { name: "Hanani" },
  { name: "Hananiah", aliases: ["Shadrach"] },
  { name: "Hanniel" },
  { name: "Hanoch" },
  { name: "Hanun" },
  { name: "Happizzez" },
  { name: "Haran" },
  { name: "Harbona" },
  { name: "Harbonah" },
  { name: "Hareph" },
  { name: "Harhaiah" },
  { name: "Harhas" },
  { name: "Harhur" },
  { name: "Harim" },
  { name: "Hariph" },
  { name: "Harnepher" },
  { name: "Haroeh" },
  { name: "Harosheth" },
  { name: "Harum" },
  { name: "Harumaph" },
  { name: "Haruz" },
  { name: "Hasabiah" },
  { name: "Hasadiah" },
  { name: "Hashabiah" },
  { name: "Hashabnah" },
  { name: "Hashabneiah" },
  { name: "Hashbadana" },
  { name: "Hashem" },
  { name: "Hashub" },
  { name: "Hashubah" },
  { name: "Hashum" },
  { name: "Hasrah" },
  { name: "Hassenaah" },
  { name: "Hasshub" },
  { name: "Hassophereth" },
  { name: "Hasupha" },
  { name: "Hathath" },
  { name: "Hatipha" },
  { name: "Hatita" },
  { name: "Hattil" },
  { name: "Hattush" },
  { name: "Havilah" },
  { name: "Hazael" },
  { name: "Hazaiah" },
  { name: "Hazar" },
  { name: "Hazarmaveth" },
  { name: "Haziel" },
  { name: "Hazo" },
  { name: "Heber" },
  { name: "Hebron" },
  { name: "Hegai" },
  { name: "Helah" },
  { name: "Helam" },
  { name: "Heldai" },
  { name: "Helem" },
  { name: "Helez" },
  { name: "Heli" },
  { name: "Helkai" },
  { name: "Helon" },
  { name: "Hemam" },
  { name: "Heman" },
  { name: "Hemdan" },
  { name: "Hen" },
  { name: "Henadad" },
  { name: "Hepher" },
  { name: "Hephzibah" },
  { name: "Heresh" },
  { name: "Hermas" },
  { name: "Hermes" },
  { name: "Hermogenes" },
  { name: "Herod", aliases: ["Herod the Great"] },
  { name: "Herod Antipas" },
  { name: "Herod Philip" },
  { name: "Herodias" },
  { name: "Hesed" },
  { name: "Heth" },
  { name: "Hezekiah" },
  { name: "Hezion" },
  { name: "Hezir" },
  { name: "Hezrai" },
  { name: "Hezro" },
  { name: "Hezron" },
  { name: "Hiddai" },
  { name: "Hiel" },
  { name: "Hilkiah" },
  { name: "Hillel" },
  { name: "Hirah" },
  { name: "Hiram", aliases: ["Huram"] },
  { name: "Hittite" },
  { name: "Hizki" },
  { name: "Hizkiah" },
  { name: "Hobab" },
  { name: "Hod" },
  { name: "Hodaiah" },
  { name: "Hodaviah" },
  { name: "Hodevah" },
  { name: "Hodiah" },
  { name: "Hoglah" },
  { name: "Hoham" },
  { name: "Homam" },
  { name: "Hophni" },
  { name: "Horam" },
  { name: "Hori" },
  { name: "Hosah" },
  { name: "Hosea" },
  { name: "Hoshea" },
  { name: "Hotham" },
  { name: "Hothan" },
  { name: "Hothir" },
  { name: "Hul" },
  { name: "Huldah" },
  { name: "Hupim" },
  { name: "Hur" },
  { name: "Huram", aliases: ["Hiram"] },
  { name: "Huri" },
  { name: "Hushah" },
  { name: "Hushai" },
  { name: "Husham" },
  { name: "Hushim" },
  { name: "Huz" },
  { name: "Hymenaeus" },

  // I
  { name: "Ibhar" },
  { name: "Ibneiah" },
  { name: "Ibnijah" },
  { name: "Ibri" },
  { name: "Ibzan" },
  { name: "Ichabod" },
  { name: "Idbash" },
  { name: "Iddo" },
  { name: "Igal" },
  { name: "Igdaliah" },
  { name: "Igeal" },
  { name: "Ikkesh" },
  { name: "Ilai" },
  { name: "Imla" },
  { name: "Imlah" },
  { name: "Immer" },
  { name: "Imna" },
  { name: "Imnah" },
  { name: "Imrah" },
  { name: "Imri" },
  { name: "Iphedeiah" },
  { name: "Ir" },
  { name: "Ira" },
  { name: "Irad" },
  { name: "Iram" },
  { name: "Iri" },
  { name: "Irijah" },
  { name: "Irnahash" },
  { name: "Iru" },
  { name: "Isaac" },
  { name: "Isaiah" },
  { name: "Iscah" },
  { name: "Ishbak" },
  { name: "Ishbi-Benob" },
  { name: "Ishbosheth", aliases: ["Eshbaal"] },
  { name: "Ishi" },
  { name: "Ishiah" },
  { name: "Ishijah" },
  { name: "Ishmael" },
  { name: "Ishmaiah" },
  { name: "Ishmerai" },
  { name: "Ishod" },
  { name: "Ishpah" },
  { name: "Ishpan" },
  { name: "Ishuah" },
  { name: "Ishuai" },
  { name: "Ishui" },
  { name: "Ishvah" },
  { name: "Ishvi" },
  { name: "Ismachiah" },
  { name: "Ispah" },
  { name: "Israel", aliases: ["Jacob"] },
  { name: "Issachar" },
  { name: "Isshiah" },
  { name: "Ithai" },
  { name: "Ithamar" },
  { name: "Ithiel" },
  { name: "Ithmah" },
  { name: "Ithran" },
  { name: "Ithream" },
  { name: "Ittai" },
  { name: "Izhar" },
  { name: "Izrahiah" },
  { name: "Izri" },

  // J
  { name: "Jaakan" },
  { name: "Jaakobah" },
  { name: "Jaala" },
  { name: "Jaalah" },
  { name: "Jaanai" },
  { name: "Jaareshiah" },
  { name: "Jaasau" },
  { name: "Jaasiel" },
  { name: "Jaazaniah" },
  { name: "Jaaziah" },
  { name: "Jaaziel" },
  { name: "Jabal" },
  { name: "Jabesh" },
  { name: "Jabez" },
  { name: "Jabin" },
  { name: "Jabneel" },
  { name: "Jachan" },
  { name: "Jachin" },
  { name: "Jacimus" },
  { name: "Jacob", aliases: ["Israel"] },
  { name: "Jada" },
  { name: "Jadau" },
  { name: "Jaddai" },
  { name: "Jaddua" },
  { name: "Jadon" },
  { name: "Jahath" },
  { name: "Jahaziah" },
  { name: "Jahaziel" },
  { name: "Jahdai" },
  { name: "Jahdiel" },
  { name: "Jahdo" },
  { name: "Jahleel" },
  { name: "Jahmai" },
  { name: "Jahzeel" },
  { name: "Jahzeiah" },
  { name: "Jahzerah" },
  { name: "Jahziel" },
  { name: "Jair" },
  { name: "Jairus" },
  { name: "Jakeh" },
  { name: "Jakim" },
  { name: "Jalam" },
  { name: "Jalon" },
  { name: "Jamin" },
  { name: "Jamlech" },
  { name: "Janna" },
  { name: "Jannai" },
  { name: "Jannes" },
  { name: "Japheth" },
  { name: "Japhia" },
  { name: "Japhlet" },
  { name: "Jarah" },
  { name: "Jareb" },
  { name: "Jared" },
  { name: "Jaresiah" },
  { name: "Jarha" },
  { name: "Jarib" },
  { name: "Jaroah" },
  { name: "Jashar" },
  { name: "Jashen" },
  { name: "Jashobeam" },
  { name: "Jashub" },
  { name: "Jashubi-Lehem" },
  { name: "Jason" },
  { name: "Jathniel" },
  { name: "Jattir" },
  { name: "Javan" },
  { name: "Jaziz" },
  { name: "Jeaterai" },
  { name: "Jeberechiah" },
  { name: "Jecoliah" },
  { name: "Jedaiah" },
  { name: "Jediael" },
  { name: "Jedidiah", aliases: ["Solomon"] },
  { name: "Jeduthun" },
  { name: "Jehaleleel" },
  { name: "Jehallelel" },
  { name: "Jehdeiah" },
  { name: "Jehezekel" },
  { name: "Jehiah" },
  { name: "Jehiel" },
  { name: "Jehieli" },
  { name: "Jehizkiah" },
  { name: "Jehoadah" },
  { name: "Jehoaddan" },
  { name: "Jehoahaz" },
  { name: "Jehoash", aliases: ["Joash"] },
  { name: "Jehohanan" },
  { name: "Jehoiachin", aliases: ["Jeconiah", "Coniah"] },
  { name: "Jehoiada" },
  { name: "Jehoiakim", aliases: ["Eliakim"] },
  { name: "Jehoiarib" },
  { name: "Jehonadab" },
  { name: "Jehonathan" },
  { name: "Jehoram", aliases: ["Joram"] },
  { name: "Jehoshabeath" },
  { name: "Jehoshaphat" },
  { name: "Jehosheba" },
  { name: "Jehoshua", aliases: ["Joshua"] },
  { name: "Jehozabad" },
  { name: "Jehozadak" },
  { name: "Jehu" },
  { name: "Jehubbah" },
  { name: "Jehucal" },
  { name: "Jehud" },
  { name: "Jehudi" },
  { name: "Jehudijah" },
  { name: "Jeiel" },
  { name: "Jekameam" },
  { name: "Jekamiah" },
  { name: "Jekuthiel" },
  { name: "Jemima" },
  { name: "Jemuel" },
  { name: "Jephthah" },
  { name: "Jephunneh" },
  { name: "Jerah" },
  { name: "Jerahmeel" },
  { name: "Jered" },
  { name: "Jeremai" },
  { name: "Jeremiah" },
  { name: "Jeremoth" },
  { name: "Jeriah" },
  { name: "Jeribai" },
  { name: "Jeriel" },
  { name: "Jerijah" },
  { name: "Jerimoth" },
  { name: "Jerioth" },
  { name: "Jeroboam" },
  { name: "Jeroham" },
  { name: "Jerubbaal", aliases: ["Gideon"] },
  { name: "Jerusha" },
  { name: "Jesaiah" },
  { name: "Jesarelah" },
  { name: "Jeshaiah" },
  { name: "Jesharelah" },
  { name: "Jeshebeab" },
  { name: "Jesher" },
  { name: "Jeshishai" },
  { name: "Jeshohaiah" },
  { name: "Jeshua" },
  { name: "Jesimiel" },
  { name: "Jesse" },
  { name: "Jesus", aliases: ["Jesus Christ", "Christ", "Messiah"] },
  { name: "Jether" },
  { name: "Jethro" },
  { name: "Jetur" },
  { name: "Jeuel" },
  { name: "Jeush" },
  { name: "Jeuz" },
  { name: "Jezaniah" },
  { name: "Jezebel" },
  { name: "Jezer" },
  { name: "Jeziel" },
  { name: "Jezliah" },
  { name: "Jezrahiah" },
  { name: "Jibsam" },
  { name: "Jidlaph" },
  { name: "Jimna" },
  { name: "Jimnah" },
  { name: "Jiphtah" },
  { name: "Jiphthah" },
  { name: "Jishui" },
  { name: "Joab" },
  { name: "Joah" },
  { name: "Joahaz" },
  { name: "Joanna" },
  { name: "Joash", aliases: ["Jehoash"] },
  { name: "Job" },
  { name: "Jobab" },
  { name: "Jochebed" },
  { name: "Joed" },
  { name: "Joel" },
  { name: "Joelah" },
  { name: "Joezer" },
  { name: "Jogli" },
  { name: "Joha" },
  { name: "Johanan" },
  { name: "John", aliases: ["John (apostle)"] },
  { name: "John the Baptist" },
  { name: "Joiada" },
  { name: "Joiakim" },
  { name: "Joiarib" },
  { name: "Jokim" },
  { name: "Jokshan" },
  { name: "Joktan" },
  { name: "Jonadab" },
  { name: "Jonah" },
  { name: "Jonam" },
  { name: "Jonathan" },
  { name: "Joppa" },
  { name: "Joram", aliases: ["Jehoram"] },
  { name: "Jorkoam" },
  { name: "Josabad" },
  { name: "Josech" },
  { name: "Joseph", aliases: ["Joseph (son of Jacob)", "Joseph (husband of Mary)", "Joseph (earthly father of Jesus)"] },
  { name: "Joseph of Arimathea" },
  { name: "Joses" },
  { name: "Joshah" },
  { name: "Joshaphat" },
  { name: "Joshbekashah" },
  { name: "Joshaviah" },
  { name: "Joshua", aliases: ["Jehoshua"] },
  { name: "Josiah" },
  { name: "Josibiah" },
  { name: "Josiphiah" },
  { name: "Jotham" },
  { name: "Jozabad" },
  { name: "Jozachar" },
  { name: "Jubal" },
  { name: "Jucal" },
  { name: "Judah", aliases: ["Juda"] },
  { name: "Judas", aliases: ["Jude", "Judas (brother of Jesus)"] },
  { name: "Judas Iscariot" },
  { name: "Judas Maccabeus" },
  { name: "Judas of Galilee" },
  { name: "Jude", aliases: ["Judas"] },
  { name: "Judith" },
  { name: "Julia" },
  { name: "Julius", aliases: ["Julius (centurion)"] },
  { name: "Junia" },
  { name: "Jushab-Hesed" },
  { name: "Justus" },

  // K
  { name: "Kadmiel" },
  { name: "Kadmonites" },
  { name: "Kallai" },
  { name: "Kareah" },
  { name: "Karkas" },
  { name: "Karkor" },
  { name: "Karnaim" },
  { name: "Kedar" },
  { name: "Kedemah" },
  { name: "Kedesh" },
  { name: "Keilah" },
  { name: "Kelaiah" },
  { name: "Kelal" },
  { name: "Kelita" },
  { name: "Kemuel" },
  { name: "Kenan", aliases: ["Cainan"] },
  { name: "Kenaz" },
  { name: "Keren-Happuch" },
  { name: "Keros" },
  { name: "Kesed" },
  { name: "Keturah" },
  { name: "Keziah" },
  { name: "Kezia" },
  { name: "Keziz" },
  { name: "Kibzaim" },
  { name: "Kidron" },
  { name: "Kimham" },
  { name: "Kinah" },
  { name: "Kish" },
  { name: "Kishi" },
  { name: "Kislon" },
  { name: "Kittim" },
  { name: "Kohath" },
  { name: "Kolaiah" },
  { name: "Korah" },
  { name: "Kore" },
  { name: "Koz" },
  { name: "Kushaiah" },

  // L
  { name: "Laadah" },
  { name: "Laadan" },
  { name: "Laban" },
  { name: "Lael" },
  { name: "Lahad" },
  { name: "Lahmi" },
  { name: "Laish" },
  { name: "Lamech" },
  { name: "Lapidoth" },
  { name: "Lappidoth" },
  { name: "Lazarus" },
  { name: "Leah" },
  { name: "Lebanah" },
  { name: "Lebaoth" },
  { name: "Lebbeus", aliases: ["Thaddeus"] },
  { name: "Lecah" },
  { name: "Lehabim" },
  { name: "Lehi" },
  { name: "Lemuel" },
  { name: "Letushim" },
  { name: "Leummim" },
  { name: "Levi", aliases: ["Levi (son of Jacob)", "Levi (tax collector)", "Matthew"] },
  { name: "Libni" },
  { name: "Likhi" },
  { name: "Linus" },
  { name: "Lo-Ammi" },
  { name: "Lo-Ruhamah" },
  { name: "Lot" },
  { name: "Lotan" },
  { name: "Lucifer" },
  { name: "Lucius" },
  { name: "Lud" },
  { name: "Ludim" },
  { name: "Luke" },
  { name: "Lydia" },

  // M
  { name: "Maacah" },
  { name: "Maadai" },
  { name: "Maadiah" },
  { name: "Maai" },
  { name: "Maaseiah" },
  { name: "Maasiai" },
  { name: "Maath" },
  { name: "Maaz" },
  { name: "Maaziah" },
  { name: "Machbannai" },
  { name: "Machbenah" },
  { name: "Machi" },
  { name: "Machir" },
  { name: "Machnadebai" },
  { name: "Madai" },
  { name: "Madmannah" },
  { name: "Magdiel" },
  { name: "Magog" },
  { name: "Magor-Missabib" },
  { name: "Magpiash" },
  { name: "Mahalaleel", aliases: ["Mahalalel"] },
  { name: "Mahalath" },
  { name: "Mahanaim" },
  { name: "Maharai" },
  { name: "Mahath" },
  { name: "Mahazioth" },
  { name: "Maher-Shalal-Hash-Baz" },
  { name: "Mahlah" },
  { name: "Mahli" },
  { name: "Mahlon" },
  { name: "Mahol" },
  { name: "Makaz" },
  { name: "Makbannai" },
  { name: "Makir" },
  { name: "Malachi" },
  { name: "Malcam" },
  { name: "Malcham" },
  { name: "Malchiah" },
  { name: "Malchiel" },
  { name: "Malchiram" },
  { name: "Malchishua" },
  { name: "Malchus" },
  { name: "Mallothi" },
  { name: "Malluch" },
  { name: "Malluchi" },
  { name: "Mamre" },
  { name: "Manahath" },
  { name: "Manahethites" },
  { name: "Manasseh", aliases: ["Manasseh (son of Joseph)"] },
  { name: "Manoah" },
  { name: "Maon" },
  { name: "Mara" },
  { name: "Mareshah" },
  { name: "Mark", aliases: ["John Mark"] },
  { name: "Marsena" },
  { name: "Martha" },
  { name: "Mary", aliases: ["Mary (mother of Jesus)"] },
  { name: "Mary Magdalene" },
  { name: "Mash" },
  { name: "Mashal" },
  { name: "Matred" },
  { name: "Matri" },
  { name: "Mattan" },
  { name: "Mattaniah", aliases: ["Zedekiah"] },
  { name: "Mattatha" },
  { name: "Mattathias" },
  { name: "Mattattah" },
  { name: "Mattenai" },
  { name: "Matthan" },
  { name: "Matthat" },
  { name: "Matthew", aliases: ["Levi (tax collector)"] },
  { name: "Matthias" },
  { name: "Mattithiah" },
  { name: "Medad" },
  { name: "Medan" },
  { name: "Mehetabel" },
  { name: "Mehida" },
  { name: "Mehir" },
  { name: "Meholathite" },
  { name: "Mekonah" },
  { name: "Melatiah" },
  { name: "Melchi" },
  { name: "Melchiah" },
  { name: "Melchizedek" },
  { name: "Melea" },
  { name: "Melech" },
  { name: "Memucan" },
  { name: "Menahem" },
  { name: "Menan" },
  { name: "Mene" },
  { name: "Menelaus" },
  { name: "Mephibosheth" },
  { name: "Merab" },
  { name: "Meraioth" },
  { name: "Merari" },
  { name: "Meremoth" },
  { name: "Meres" },
  { name: "Merib-Baal", aliases: ["Mephibosheth"] },
  { name: "Merodach" },
  { name: "Merodach-Baladan" },
  { name: "Mesha" },
  { name: "Meshach", aliases: ["Meshach"] },
  { name: "Meshech" },
  { name: "Meshelemiah" },
  { name: "Meshillemith" },
  { name: "Meshillemoth" },
  { name: "Meshobab" },
  { name: "Meshullam" },
  { name: "Meshullemeth" },
  { name: "Methusael" },
  { name: "Methuselah" },
  { name: "Meunim" },
  { name: "Mezahab" },
  { name: "Mibhar" },
  { name: "Mibsam" },
  { name: "Mibzar" },
  { name: "Micah" },
  { name: "Micaiah" },
  { name: "Michael" },
  { name: "Michal" },
  { name: "Michri" },
  { name: "Midian" },
  { name: "Migdal-El" },
  { name: "Migdol" },
  { name: "Mijamin" },
  { name: "Mikloth" },
  { name: "Milalai" },
  { name: "Milcah", aliases: ["Milcah"] },
  { name: "Mileah" },
  { name: "Miniamin" },
  { name: "Miriam" },
  { name: "Mirmah" },
  { name: "Mishael", aliases: ["Meshach"] },
  { name: "Misham" },
  { name: "Mishma" },
  { name: "Mishmannah" },
  { name: "Mispar" },
  { name: "Mispereth" },
  { name: "Mithredath" },
  { name: "Mizpah" },
  { name: "Mizraim" },
  { name: "Mizzah" },
  { name: "Mnason" },
  { name: "Moab" },
  { name: "Moadiah" },
  { name: "Molid" },
  { name: "Mordecai" },
  { name: "Moses" },
  { name: "Muppim" },
  { name: "Mushi" },

  // N
  { name: "Naam" },
  { name: "Naaman" },
  { name: "Naarah" },
  { name: "Naarai" },
  { name: "Naashon", aliases: ["Nahshon"] },
  { name: "Naasson" },
  { name: "Nabal" },
  { name: "Naboth" },
  { name: "Nachon" },
  { name: "Nachor", aliases: ["Nahor"] },
  { name: "Nadab" },
  { name: "Nagge" },
  { name: "Naham" },
  { name: "Nahamani" },
  { name: "Naharai" },
  { name: "Nahari" },
  { name: "Nahash" },
  { name: "Nahath" },
  { name: "Nahbi" },
  { name: "Nahor", aliases: ["Nachor"] },
  { name: "Nahshon", aliases: ["Naashon"] },
  { name: "Nahum" },
  { name: "Nain" },
  { name: "Naioth" },
  { name: "Nakash" },
  { name: "Namaan" },
  { name: "Namaan" },
  { name: "Naphish" },
  { name: "Naphtali" },
  { name: "Narcissus" },
  { name: "Nathan" },
  { name: "Nathanael", aliases: ["Bartholomew"] },
  { name: "Naveh" },
  { name: "Nazarene" },
  { name: "Nebai" },
  { name: "Nebaioth" },
  { name: "Nebat" },
  { name: "Nebuchadnezzar" },
  { name: "Nebushasban" },
  { name: "Nebuzaradan" },
  { name: "Necho" },
  { name: "Nedabiah" },
  { name: "Nehemiah" },
  { name: "Nehum" },
  { name: "Nehushta" },
  { name: "Nehushtan" },
  { name: "Nekoda" },
  { name: "Nemuel" },
  { name: "Nepheg" },
  { name: "Nephish" },
  { name: "Nephishesim" },
  { name: "Ner" },
  { name: "Nereus" },
  { name: "Nergal-Sharezer" },
  { name: "Neri" },
  { name: "Neriah" },
  { name: "Nethanel" },
  { name: "Nethaniah" },
  { name: "Nethinim" },
  { name: "Neziah" },
  { name: "Nibhaz" },
  { name: "Nicanor" },
  { name: "Nicodemus" },
  { name: "Nicolaus" },
  { name: "Niger" },
  { name: "Nimrod" },
  { name: "Nimshi" },
  { name: "Noadiah" },
  { name: "Noah" },
  { name: "Nobah" },
  { name: "Nogah" },
  { name: "Nohah" },
  { name: "Non" },
  { name: "Nun" },
  { name: "Nympha" },

  // O
  { name: "Obadiah" },
  { name: "Obal" },
  { name: "Obed" },
  { name: "Obed-Edom" },
  { name: "Obil" },
  { name: "Ocran" },
  { name: "Oded" },
  { name: "Og" },
  { name: "Ohad" },
  { name: "Ohel" },
  { name: "Oholah" },
  { name: "Oholibah" },
  { name: "Oholibamah" },
  { name: "Ok" },
  { name: "Olympas" },
  { name: "Omar" },
  { name: "Omri" },
  { name: "On" },
  { name: "Onam" },
  { name: "Onan" },
  { name: "Onesimus" },
  { name: "Onesiphorus" },
  { name: "Ophir" },
  { name: "Ophrah" },
  { name: "Oreb" },
  { name: "Oren" },
  { name: "Ornan", aliases: ["Araunah"] },
  { name: "Orpah" },
  { name: "Oshea", aliases: ["Hoshea"] },
  { name: "Othni" },
  { name: "Othniel" },
  { name: "Ozem" },

  // P
  { name: "Paarai" },
  { name: "Padon" },
  { name: "Pagiel" },
  { name: "Pahath-Moab" },
  { name: "Palal" },
  { name: "Pallu" },
  { name: "Palluites" },
  { name: "Palti" },
  { name: "Paltiel" },
  { name: "Parmashta" },
  { name: "Parmenas" },
  { name: "Parnach" },
  { name: "Parosh" },
  { name: "Parshandatha" },
  { name: "Paruah" },
  { name: "Pasach" },
  { name: "Paseah" },
  { name: "Pashhur" },
  { name: "Patrobas" },
  { name: "Paul", aliases: ["Saul (later Paul)"] },
  { name: "Pedaiah" },
  { name: "Pekah" },
  { name: "Pekahiah" },
  { name: "Pelaiah" },
  { name: "Pelaliah" },
  { name: "Pelatiah" },
  { name: "Peleg" },
  { name: "Peniel" },
  { name: "Peninnah" },
  { name: "Pentecost" },
  { name: "Peor" },
  { name: "Peresh" },
  { name: "Perez", aliases: ["Pharez"] },
  { name: "Perida" },
  { name: "Perizzites" },
  { name: "Persis" },
  { name: "Peter", aliases: ["Simon Peter", "Cephas"] },
  { name: "Pethahiah" },
  { name: "Pethuel" },
  { name: "Peulthai" },
  { name: "Phallu" },
  { name: "Phalti" },
  { name: "Phanuel" },
  { name: "Pharaoh" },
  { name: "Pharez", aliases: ["Perez"] },
  { name: "Phichol" },
  { name: "Philemon" },
  { name: "Philetus" },
  { name: "Philip", aliases: ["Philip (apostle)", "Philip (evangelist)"] },
  { name: "Philologus" },
  { name: "Phinehas", aliases: ["Phinehas (priest)"] },
  { name: "Phlegon" },
  { name: "Phoebe" },
  { name: "Phurah" },
  { name: "Phuvah" },
  { name: "Phygelus" },
  { name: "Pildash" },
  { name: "Pileha" },
  { name: "Pilha" },
  { name: "Piltai" },
  { name: "Pinon" },
  { name: "Piram" },
  { name: "Pispah" },
  { name: "Pithon" },
  { name: "Pochereth" },
  { name: "Pontius Pilate" },
  { name: "Poratha" },
  { name: "Porcius Festus", aliases: ["Festus"] },
  { name: "Potiphar" },
  { name: "Potipherah" },
  { name: "Priscilla", aliases: ["Prisca"] },
  { name: "Prochorus" },
  { name: "Puah" },
  { name: "Publius" },
  { name: "Pudens" },
  { name: "Pul" },
  { name: "Put" },
  { name: "Putiel" },

  // Q
  { name: "Quartus" },
  { name: "Queen of Sheba" },

  // R
  { name: "Raamah" },
  { name: "Raamiah" },
  { name: "Raddai" },
  { name: "Ragau" },
  { name: "Raguel" },
  { name: "Rahab" },
  { name: "Raham" },
  { name: "Rakem" },
  { name: "Ram" },
  { name: "Rama" },
  { name: "Ramiah" },
  { name: "Rapha" },
  { name: "Raphah" },
  { name: "Raphu" },
  { name: "Reaiah" },
  { name: "Reaiah" },
  { name: "Reba" },
  { name: "Rebecca", aliases: ["Rebekah"] },
  { name: "Rebekah" },
  { name: "Rechab" },
  { name: "Reelaiah" },
  { name: "Regem" },
  { name: "Regem-Melech" },
  { name: "Rehabiah" },
  { name: "Rehob" },
  { name: "Rehoboam" },
  { name: "Rehum" },
  { name: "Rei" },
  { name: "Rekem" },
  { name: "Remaliah" },
  { name: "Remeth" },
  { name: "Rephaiah" },
  { name: "Rephah" },
  { name: "Rephaiah" },
  { name: "Resheph" },
  { name: "Reu" },
  { name: "Reuben" },
  { name: "Reuel" },
  { name: "Reumah" },
  { name: "Rezia" },
  { name: "Rezin" },
  { name: "Rezon" },
  { name: "Rhesa" },
  { name: "Ribai" },
  { name: "Rimmon" },
  { name: "Rinnah" },
  { name: "Riphath" },
  { name: "Rizia" },
  { name: "Rizpah" },
  { name: "Roboam", aliases: ["Rehoboam"] },
  { name: "Rohgah" },
  { name: "Romamti-Ezer" },
  { name: "Rosh" },
  { name: "Rufus" },
  { name: "Ruth" },

  // S
  { name: "Sabtah" },
  { name: "Sabtechah" },
  { name: "Sacar" },
  { name: "Sadoc" },
  { name: "Sallai" },
  { name: "Sallu" },
  { name: "Salma" },
  { name: "Salmon" },
  { name: "Salome" },
  { name: "Samgar" },
  { name: "Samlah" },
  { name: "Samson" },
  { name: "Samuel" },
  { name: "Sanballat" },
  { name: "Saph" },
  { name: "Saphir" },
  { name: "Sapphira" },
  { name: "Sarah", aliases: ["Sarai"] },
  { name: "Sarai", aliases: ["Sarah"] },
  { name: "Sargon" },
  { name: "Sarsechim" },
  { name: "Saruch", aliases: ["Serug"] },
  { name: "Saul", aliases: ["Saul (king of Israel)", "King Saul"] },
  { name: "Sceva" },
  { name: "Secundus" },
  { name: "Segub" },
  { name: "Seir" },
  { name: "Sela" },
  { name: "Seled" },
  { name: "Semachiah" },
  { name: "Semei", aliases: ["Shimei"] },
  { name: "Senaah" },
  { name: "Sennacherib" },
  { name: "Senir" },
  { name: "Senuah" },
  { name: "Seorim" },
  { name: "Seraiah" },
  { name: "Seraph" },
  { name: "Sered" },
  { name: "Sergius Paulus" },
  { name: "Serug", aliases: ["Saruch"] },
  { name: "Seth" },
  { name: "Sethur" },
  { name: "Shaaph" },
  { name: "Shaashgaz" },
  { name: "Shabbethai" },
  { name: "Shachia" },
  { name: "Shadrach", aliases: ["Hananiah"] },
  { name: "Shage" },
  { name: "Shaharaim" },
  { name: "Shallum" },
  { name: "Shallun" },
  { name: "Shalmai" },
  { name: "Shalman" },
  { name: "Shalmaneser" },
  { name: "Shama" },
  { name: "Shamariah" },
  { name: "Shamed" },
  { name: "Shamer" },
  { name: "Shamgar" },
  { name: "Shamhuth" },
  { name: "Shamir" },
  { name: "Shamma" },
  { name: "Shammai" },
  { name: "Shammoth" },
  { name: "Shammua" },
  { name: "Shamsherai" },
  { name: "Shapham" },
  { name: "Shaphan" },
  { name: "Shaphat" },
  { name: "Sharai" },
  { name: "Sharar" },
  { name: "Sharezer" },
  { name: "Shashak" },
  { name: "Shavsha" },
  { name: "Sheal" },
  { name: "Shealtiel" },
  { name: "Sheariah" },
  { name: "Shear-Jashub" },
  { name: "Sheba" },
  { name: "Shebaniah" },
  { name: "Sheber" },
  { name: "Shebna" },
  { name: "Shebuel" },
  { name: "Shecaniah" },
  { name: "Shechaniah" },
  { name: "Shedeur" },
  { name: "Shehariah" },
  { name: "Shelah" },
  { name: "Shelemiah" },
  { name: "Sheleph" },
  { name: "Shelesh" },
  { name: "Shelomi" },
  { name: "Shelomith" },
  { name: "Shelomoth" },
  { name: "Shem" },
  { name: "Shema" },
  { name: "Shemaiah" },
  { name: "Shemariah" },
  { name: "Shemeber" },
  { name: "Shemer" },
  { name: "Shemida" },
  { name: "Shemiramoth" },
  { name: "Shemuel" },
  { name: "Shenazar" },
  { name: "Shephatiah" },
  { name: "Shepho" },
  { name: "Shephupham" },
  { name: "Sherah" },
  { name: "Sherebiah" },
  { name: "Sheshai" },
  { name: "Sheshan" },
  { name: "Sheshbazzar" },
  { name: "Shethar" },
  { name: "Shethar-Boznai" },
  { name: "Sheva" },
  { name: "Shilhi" },
  { name: "Shillem" },
  { name: "Shiloni" },
  { name: "Shimea" },
  { name: "Shimeah" },
  { name: "Shimeam" },
  { name: "Shimeath" },
  { name: "Shimei", aliases: ["Semei"] },
  { name: "Shimeon" },
  { name: "Shimhi" },
  { name: "Shimi" },
  { name: "Shimma" },
  { name: "Shimon" },
  { name: "Shimrath" },
  { name: "Shimri" },
  { name: "Shimrith" },
  { name: "Shimron" },
  { name: "Shimshai" },
  { name: "Shinab" },
  { name: "Shiphi" },
  { name: "Shiphrah" },
  { name: "Shiphtan" },
  { name: "Shisha" },
  { name: "Shishak" },
  { name: "Shitrai" },
  { name: "Shiza" },
  { name: "Shobab" },
  { name: "Shobach" },
  { name: "Shobai" },
  { name: "Shobal" },
  { name: "Shobek" },
  { name: "Shoham" },
  { name: "Shomer" },
  { name: "Shophach" },
  { name: "Shophai" },
  { name: "Shua" },
  { name: "Shuah" },
  { name: "Shual" },
  { name: "Shubael" },
  { name: "Shuham" },
  { name: "Shuni" },
  { name: "Shupham" },
  { name: "Shuppim" },
  { name: "Shuthelah" },
  { name: "Sia" },
  { name: "Siaha" },
  { name: "Sibbecai" },
  { name: "Sibbechai" },
  { name: "Sidon" },
  { name: "Sihon" },
  { name: "Silas", aliases: ["Silvanus"] },
  { name: "Silla" },
  { name: "Simeon", aliases: ["Simeon (son of Jacob)"] },
  { name: "Simon", aliases: ["Simon Peter", "Simon the Zealot"] },
  { name: "Simon Maccabeus" },
  { name: "Simon Magus" },
  { name: "Simon of Cyrene" },
  { name: "Simon the Pharisee" },
  { name: "Simon the Tanner" },
  { name: "Sippai" },
  { name: "Sisamai" },
  { name: "Sisera" },
  { name: "Sithri" },
  { name: "So" },
  { name: "Sodi" },
  { name: "Solomon", aliases: ["Jedidiah"] },
  { name: "Sopater" },
  { name: "Sophereth" },
  { name: "Sosthenes" },
  { name: "Sotai" },
  { name: "Stachys" },
  { name: "Stephanas" },
  { name: "Stephen" },
  { name: "Suah" },
  { name: "Sucathites" },
  { name: "Sud" },
  { name: "Susi" },
  { name: "Susanna", aliases: ["Susanna (Daniel)", "Susanna (Luke)"] },
  { name: "Syntyche" },

  // T
  { name: "Tabbaoth" },
  { name: "Tabbai" },
  { name: "Tabeel" },
  { name: "Tabitha", aliases: ["Dorcas"] },
  { name: "Tabor" },
  { name: "Tabrimon" },
  { name: "Tadmor" },
  { name: "Tahan" },
  { name: "Tahath" },
  { name: "Tahpenes" },
  { name: "Tahrea" },
  { name: "Talmai" },
  { name: "Talmon" },
  { name: "Tamar" },
  { name: "Tanhumeth" },
  { name: "Tappuah" },
  { name: "Tarea" },
  { name: "Tarshish" },
  { name: "Tartak" },
  { name: "Tattenai" },
  { name: "Tebah" },
  { name: "Tebaliah" },
  { name: "Tehinnah" },
  { name: "Tekoa" },
  { name: "Telah" },
  { name: "Telem" },
  { name: "Tema" },
  { name: "Temah" },
  { name: "Teman" },
  { name: "Terah" },
  { name: "Teresh" },
  { name: "Tertius" },
  { name: "Tertullus" },
  { name: "Thaddeus", aliases: ["Lebbeus", "Judas (Thaddeus)"] },
  { name: "Thahash" },
  { name: "Tharah", aliases: ["Terah"] },
  { name: "Theophilus" },
  { name: "Theudas" },
  { name: "Thomas", aliases: ["Didymus"] },
  { name: "Tiberius", aliases: ["Tiberius Caesar"] },
  { name: "Tibni" },
  { name: "Tidal" },
  { name: "Tiglath-Pileser" },
  { name: "Tikvah" },
  { name: "Tilgath-Pilneser" },
  { name: "Timaeus" },
  { name: "Timna" },
  { name: "Timon" },
  { name: "Timothy" },
  { name: "Tiras" },
  { name: "Tirhakah" },
  { name: "Tirhanah" },
  { name: "Tiria" },
  { name: "Tirzah" },
  { name: "Titus" },
  { name: "Toah" },
  { name: "Tob-Adonijah" },
  { name: "Tobiah", aliases: ["Tobiah (Ammonite)"] },
  { name: "Tobijah" },
  { name: "Togarmah" },
  { name: "Toi" },
  { name: "Tola" },
  { name: "Tou" },
  { name: "Trophimus" },
  { name: "Tryphaena" },
  { name: "Tryphosa" },
  { name: "Tubal" },
  { name: "Tubal-Cain" },
  { name: "Tychicus" },
  { name: "Tyrannus" },

  // U
  { name: "Ucal" },
  { name: "Uel" },
  { name: "Ulai" },
  { name: "Ulam" },
  { name: "Ulla" },
  { name: "Ummah" },
  { name: "Unni" },
  { name: "Uphaz" },
  { name: "Ur" },
  { name: "Urbane", aliases: ["Urbanus"] },
  { name: "Urbanus" },
  { name: "Uri" },
  { name: "Uriah", aliases: ["Uriah (prophet)", "Uriah the Hittite"] },
  { name: "Uriel" },
  { name: "Urijah" },
  { name: "Urim" },
  { name: "Uthai" },
  { name: "Uz" },
  { name: "Uzal" },
  { name: "Uzza" },
  { name: "Uzzah" },
  { name: "Uzzen-Sherah" },
  { name: "Uzzi" },
  { name: "Uzzia" },
  { name: "Uzziah", aliases: ["Azariah"] },
  { name: "Uzziel" },

  // V
  { name: "Vaniah" },
  { name: "Vashni" },
  { name: "Vashti" },
  { name: "Vophsi" },

  // W
  { name: "Wicked One" },

  // X
  { name: "Xerxes", aliases: ["Ahasuerus"] },

  // Z
  { name: "Zaavan" },
  { name: "Zabad" },
  { name: "Zabbai" },
  { name: "Zabbud" },
  { name: "Zabdi" },
  { name: "Zabdiel" },
  { name: "Zabud" },
  { name: "Zaccai" },
  { name: "Zacchaeus" },
  { name: "Zaccur" },
  { name: "Zachariah", aliases: ["Zechariah"] },
  { name: "Zacharias", aliases: ["Zechariah (father of John the Baptist)"] },
  { name: "Zadok" },
  { name: "Zaham" },
  { name: "Zalmon" },
  { name: "Zalmunna" },
  { name: "Zamri" },
  { name: "Zanoah" },
  { name: "Zaphnath-Paaneah", aliases: ["Joseph (son of Jacob)"] },
  { name: "Zaphon" },
  { name: "Zara", aliases: ["Zerah"] },
  { name: "Zarah", aliases: ["Zerah"] },
  { name: "Zareah" },
  { name: "Zareathites" },
  { name: "Zared" },
  { name: "Zatthu" },
  { name: "Zattu" },
  { name: "Zavan" },
  { name: "Zaza" },
  { name: "Zebadiah" },
  { name: "Zebah" },
  { name: "Zebedee" },
  { name: "Zebidah" },
  { name: "Zebina" },
  { name: "Zebul" },
  { name: "Zebulun", aliases: ["Zebulun"] },
  { name: "Zechariah", aliases: ["Zachariah", "Zechariah (father of John the Baptist)"] },
  { name: "Zedekiah", aliases: ["Mattaniah"] },
  { name: "Zeeb" },
  { name: "Zelek" },
  { name: "Zelophehad" },
  { name: "Zelotes", aliases: ["Simon the Zealot"] },
  { name: "Zemira" },
  { name: "Zenan" },
  { name: "Zenas" },
  { name: "Zephaniah", aliases: ["Zephaniah (priest)"] },
  { name: "Zepho" },
  { name: "Zephon" },
  { name: "Zerah", aliases: ["Zara", "Zarah"] },
  { name: "Zerahiah" },
  { name: "Zeresh" },
  { name: "Zeri" },
  { name: "Zeror" },
  { name: "Zeruah" },
  { name: "Zerubbabel" },
  { name: "Zeruiah" },
  { name: "Zetham" },
  { name: "Zethan" },
  { name: "Zethar" },
  { name: "Zia" },
  { name: "Ziba" },
  { name: "Zibiah" },
  { name: "Zichri" },
  { name: "Ziddim" },
  { name: "Zidkijah" },
  { name: "Ziha" },
  { name: "Zikri" },
  { name: "Zillah" },
  { name: "Zilpah" },
  { name: "Zilthai" },
  { name: "Zimmah" },
  { name: "Zimran" },
  { name: "Zimri" },
  { name: "Zinri" },
  { name: "Ziph" },
  { name: "Ziphah" },
  { name: "Ziphion" },
  { name: "Zipporah" },
  { name: "Zithri" },
  { name: "Ziza" },
  { name: "Zizah" },
  { name: "Zoan" },
  { name: "Zoar" },
  { name: "Zobebah" },
  { name: "Zohar" },
  { name: "Zoheth" },
  { name: "Zophah" },
  { name: "Zophai" },
  { name: "Zophar" },
  { name: "Zuar" },
  { name: "Zuph" },
  { name: "Zur" },
  { name: "Zuriel" },
  { name: "Zurishaddai" },
  { name: "Zuzim" },
  // Additional entries added to reach ~2,500
  { name: "Abarim" },
  { name: "Abda (son of Shammua)" },
  { name: "Abdi (Levite)" },
  { name: "Abdi (Merarite)" },
  { name: "Abdiel (Gadite)" },
  { name: "Abdon (Levite)" },
  { name: "Abdon (son of Micah)" },
  { name: "Abednego (Hananiah)" },
  { name: "Abel-Beth-Maachah" },
  { name: "Abel-Meholah" },
  { name: "Abel-Shittim" },
  { name: "Abi (mother of Hezekiah)" },
  { name: "Abiathar (high priest)" },
  { name: "Abiathar (son of Ahimelech)" },
  { name: "Abida (son of Midian)" },
  { name: "Abidan (prince of Benjamin)" },
  { name: "Abiel (Kish's father)" },
  { name: "Abiezer (Gileadite)" },
  { name: "Abigail (David's wife)" },
  { name: "Abigail (Jesse's daughter)" },
  { name: "Abihail (Esther's father)" },
  { name: "Abihu (Aaron's son)" },
  { name: "Abijah (king of Judah)" },
  { name: "Abijah (priest)" },
  { name: "Abijam (king)" },
  { name: "Abimelech (king of Gerar)" },
  { name: "Abimelech (son of Gideon)" },
  { name: "Abinadab (Ark bearer)" },
  { name: "Abinadab (Jesse's son)" },
  { name: "Abinoam (Barak's father)" },
  { name: "Abiram (Rebel)" },
  { name: "Abishag (Shunammite)" },
  { name: "Abishai (David's nephew)" },
  { name: "Abishalom (Absalom)" },
  { name: "Abishua (Aaron's grandson)" },
  { name: "Abital (David's wife)" },
  { name: "Abitub (Benjaminite)" },
  { name: "Abiud (Jesus' ancestor)" },
  { name: "Abraham (patriarch)" },
  { name: "Absalom (David's son)" },
  { name: "Accad (city founder)" },
  { name: "Achan (Achar)" },
  { name: "Achbor (son of Micaiah)" },
  { name: "Achish (king of Gath)" },
  { name: "Achzib (place/person)" },
  { name: "Adaiah (Josiah's grandfather)" },
  { name: "Adalia (Haman's son)" },
  { name: "Adam (first man)" },
  { name: "Adbeel (Ishmael's son)" },
  { name: "Addar (Benjaminite)" },
  { name: "Addi (Jesus' ancestor)" },
  { name: "Addin (returnee)" },
  { name: "Adiel (Simeonite)" },
  { name: "Adin (returnee)" },
  { name: "Adina (Reubenite)" },
  { name: "Adino (chief)" },
  { name: "Adlai (Shaphat's father)" },
  { name: "Admatha (prince)" },
  { name: "Adna (priest)" },
  { name: "Adnah (commander)" },
  { name: "Adonijah (David's son)" },
  { name: "Adonikam (returnee)" },
  { name: "Adoniram (tax collector)" },
  { name: "Adoni-Zedek (king)" },
  { name: "Adriel (Meholathite)" },
  { name: "Aeneas (paralytic)" },
  { name: "Agabus (prophet)" },
  { name: "Agag (Amalekite king)" },
  { name: "Agar (Hagar)" },
  { name: "Agee (Hararite)" },
  { name: "Agrippa I (Herod)" },
  { name: "Agrippa II (Herod)" },
  { name: "Agur (Lemuel's father)" },
  { name: "Ahab (king of Israel)" },
  { name: "Aharah (Benjaminite)" },
  { name: "Aharhel (Judahite)" },
  { name: "Ahasbai (Maachathite)" },
  { name: "Ahashbai (son of Ben-Geber)" },
  { name: "Ahasuerus (Xerxes)" },
  { name: "Ahaz (king of Judah)" },
  { name: "Ahaziah (king of Israel)" },
  { name: "Ahaziah (king of Judah)" },
  { name: "Ahban (Abishur's son)" },
  { name: "Aher (Benjaminite)" },
  { name: "Ahi (Gadite)" },
  { name: "Ahiam (Hachmonite)" },
  { name: "Ahian (Manassite)" },
  { name: "Ahiezer (Danite)" },
  { name: "Ahihud (Asherite)" },
  { name: "Ahihud (Ephraimite)" },
  { name: "Ahijah (prophet)" },
  { name: "Ahijah (Shilonite)" },
  { name: "Ahikam (Shaphan's son)" },
  { name: "Ahilud (recorder)" },
  { name: "Ahimaaz (priest)" },
  { name: "Ahimaaz (Zadok's son)" },
  { name: "Ahiman (Anakite)" },
  { name: "Ahimelech (priest)" },
  { name: "Ahimoth (Levite)" },
  { name: "Ahinadab (Iddo's son)" },
  { name: "Ahinoam (David's wife)" },
  { name: "Ahio (Uzzah's brother)" },
  { name: "Ahira (Naphtalite)" },
  { name: "Ahiram (Benjaminite)" },
  { name: "Ahisamach (Danite)" },
  { name: "Ahishahar (Benjaminite)" },
  { name: "Ahishar (steward)" },
  { name: "Ahithophel (counselor)" },
  { name: "Ahitub (priest)" },
  { name: "Ahlai (Sheshan's daughter)" },
  { name: "Ahoah (Benjaminite)" },
  { name: "Aholiab (craftsman)" },
  { name: "Aholibah (allegorical)" },
  { name: "Aholibamah (Esau's wife)" },
  { name: "Ahumai (Judahite)" },
  { name: "Ahuzam (Judahite)" },
  { name: "Ahuzzath (counselor)" },
  { name: "Aiah (Horite)" },
  { name: "Akan (Horite)" },
  { name: "Akkub (gatekeeper)" },
  { name: "Akkub (Levite)" },
  { name: "Alameth (Benjaminite)" },
  { name: "Alexander (coppersmith)" },
  { name: "Alexander (high priest)" },
  { name: "Alian (Horite)" },
  { name: "Allon (Simeonite)" },
  { name: "Almodad (Joktan's son)" },
  { name: "Alphaeus (father of James)" },
  { name: "Alvah (duke of Edom)" },
  { name: "Alvan (Horite)" },
  { name: "Amal (Asherite)" },
  { name: "Amalek (Esau's grandson)" },
  { name: "Amariah (priest)" },
  { name: "Amariah (Zedekiah's son)" },
  { name: "Amasa (Absalom's general)" },
  { name: "Amasai (chief)" },
  { name: "Amashai (priest)" },
  { name: "Amasiah (commander)" },
  { name: "Amaziah (king of Judah)" },
  { name: "Ami (servant)" },
  { name: "Aminadab (Amminadab)" },
  { name: "Ammiel (spy)" },
  { name: "Ammihud (Ephraimite)" },
  { name: "Ammihur (Ahaz's father)" },
  { name: "Ammizabad (Benaiah's son)" },
  { name: "Ammon (people)" },
  { name: "Amon (king of Judah)" },
  { name: "Amon (governor)" },
  { name: "Amnon (David's son)" },
  { name: "Amok (priest)" },
  { name: "Amorite (people)" },
  { name: "Amos (prophet)" },
  { name: "Amoz (Isaiah's father)" },
  { name: "Amplias (Roman)" },
  { name: "Amram (Moses' father)" },
  { name: "Amraphel (king)" },
  { name: "Amzi (Merarite)" },
  { name: "Anah (Horite)" },
  { name: "Anah (Zibeon's daughter)" },
  { name: "Anan (returnee)" },
  { name: "Anani (Benjaminite)" },
  { name: "Ananiah (place/priest)" },
  { name: "Ananias (Damascus)" },
  { name: "Ananias (high priest)" },
  { name: "Ananias (Sapphira's husband)" },
  { name: "Anath (father of Shamgar)" },
  { name: "Anathoth (priest)" },
  { name: "Anathothite (inhabitant)" },
  { name: "Andrew (apostle)" },
  { name: "Andronicus (Roman)" },
  { name: "Aner (confederate)" },
  { name: "Aniam (Manassite)" },
  { name: "Anna (prophetess)" },
  { name: "Annas (high priest)" },
  { name: "Antipas (martyr)" },
  { name: "Antipater (Herod's father)" },
  { name: "Antothijah (Benjaminite)" },
  { name: "Anub (Judahite)" },
  { name: "Apelles (approved)" },
  { name: "Aphiah (Bichri's ancestor)" },
  { name: "Apollos (Alexandrian)" },
  { name: "Appaim (Judahite)" },
  { name: "Ara (Jether's son)" },
  { name: "Arad (Canaanite king)" },
  { name: "Arah (returnee)" },
  { name: "Aram (Shem's son)" },
  { name: "Aran (Seir's son)" },
  { name: "Ararat (place)" },
  { name: "Araunah (Jebusite)" },
  { name: "Arba (giant)" },
  { name: "Archelaus (Herod's son)" },
  { name: "Archippus (Colossian)" },
  { name: "Ard (Benjaminite)" },
  { name: "Ardon (Caleb's son)" },
  { name: "Areli (Gadite)" },
  { name: "Aretas (king)" },
  { name: "Argob (kingdom)" },
  { name: "Aridai (Haman's son)" },
  { name: "Aridatha (Haman's son)" },
  { name: "Arieh (captain)" },
  { name: "Ariel (Moabite)" },
  { name: "Arioch (Babylonian)" },
  { name: "Aristarchus (Thessalonian)" },
  { name: "Aristobulus (Roman)" },
  { name: "Armoni (Saul's son)" },
  { name: "Arnan (Zerubbabel's son)" },
  { name: "Arni (Rhesa's son)" },
  { name: "Arod (Gadite)" },
  { name: "Aroer (place)" },
  { name: "Arpachshad (Arphaxad)" },
  { name: "Artaxerxes (king)" },
  { name: "Artemas (companion)" },
  { name: "Arza (steward)" },
  { name: "Asa (king of Judah)" },
  { name: "Asahel (David's nephew)" },
  { name: "Asahiah (servant)" },
  { name: "Asaph (Levite)" },
  { name: "Asareel (Judahite)" },
  { name: "Asarel (Ezrahite)" },
  { name: "Asenath (Joseph's wife)" },
  { name: "Asher (tribe)" },
  { name: "Ashkenaz (Gomer's son)" },
  { name: "Ashnah (place)" },
  { name: "Ashpenaz (chief eunuch)" },
  { name: "Ashtaroth (goddess/place)" },
  { name: "Asiel (Simeonite)" },
  { name: "Asnah (servant)" },
  { name: "Aspatha (Haman's son)" },
  { name: "Asriel (Manassite)" },
  { name: "Asshur (Shem's son)" },
  { name: "Asshurim (people)" },
  { name: "Asyncritus (Roman)" },
  { name: "Athaliah (queen)" },
  { name: "Athlai (returnee)" },
  { name: "Attai (Judahite)" },
  { name: "Augustus (Caesar)" },
  { name: "Ava (city)" },
  { name: "Aven (place)" },
  { name: "Azaliah (Shaphan's father)" },
  { name: "Azaniah (Levite)" },
  { name: "Azarael (captain)" },
  { name: "Azareel (captain)" },
  { name: "Azariah (king/prince)" },
  { name: "Azaz (Reubenite)" },
  { name: "Azaziah (musician)" },
  { name: "Azbuk (ruler)" },
  { name: "Azel (Saul's descendant)" },
  { name: "Azgad (returnee)" },
  { name: "Aziel (musician)" },
  { name: "Aziza (returnee)" },
  { name: "Azmaveth (mighty man)" },
  { name: "Azor (Jesus' ancestor)" },
  { name: "Azriel (chief)" },
  { name: "Azrikam (Benjaminite)" },
  { name: "Azubah (Caleb's wife)" },
  { name: "Azur (Azaz)" },
  { name: "Azzan (Ephraimite)" },
  { name: "Azzur (prophet)" },
  // Additional verified biblical names - Batch 2
  { name: "Baara (wife)" },
  { name: "Baaseiah (Levite)" },
  { name: "Baasha (king)" },
  { name: "Bakbakkar (Levite)" },
  { name: "Bakbuk (servant)" },
  { name: "Bakbukiah (Levite)" },
  { name: "Balaam (prophet)" },
  { name: "Balak (Moabite king)" },
  { name: "Bani (Gadite)" },
  { name: "Bani (returnee)" },
  { name: "Barabbas (prisoner)" },
  { name: "Barachel (Buzite)" },
  { name: "Barak (judge)" },
  { name: "Bariah (Shemaiah's son)" },
  { name: "Barkos (returnee)" },
  { name: "Barnabas (apostle)" },
  { name: "Baruch (scribe)" },
  { name: "Barzillai (Gileadite)" },
  { name: "Bashan (place/king)" },
  { name: "Bathsheba (David's wife)" },
  { name: "Bavai (ruler)" },
  { name: "Bazlith (servant)" },
  { name: "Bazluth (servant)" },
  { name: "Bealiah (Benjaminite)" },
  { name: "Bebai (returnee)" },
  { name: "Becher (Benjaminite)" },
  { name: "Bechorath (Saul's ancestor)" },
  { name: "Bedad (Edomite king)" },
  { name: "Bedan (judge)" },
  { name: "Beeliada (Eliada)" },
  { name: "Beera (Asherite)" },
  { name: "Beerah (Reubenite)" },
  { name: "Beeri (Hosea's father)" },
  { name: "Bela (Benjamin)" },
  { name: "Belah (place)" },
  { name: "Belshazzar (king)" },
  { name: "Belteshazzar (Daniel)" },
  { name: "Ben-Abinadab (official)" },
  { name: "Ben-Ammi (Moabite ancestor)" },
  { name: "Ben-Deker (official)" },
  { name: "Ben-Geber (official)" },
  { name: "Ben-Hadad (king)" },
  { name: "Ben-Hail (official)" },
  { name: "Ben-Hesed (official)" },
  { name: "Ben-Hur (official)" },
  { name: "Ben-Oni (Benjamin)" },
  { name: "Ben-Zoheth (Simeonite)" },
  { name: "Benaiah (commander)" },
  { name: "Benjamite (inhabitant)" },
  { name: "Benjamin (tribe)" },
  { name: "Beno (Levite)" },
  { name: "Beor (Balaam's father)" },
  { name: "Bera (king of Sodom)" },
  { name: "Berachah (warrior)" },
  { name: "Beraiah (Benjaminite)" },
  { name: "Berechiah (prophet)" },
  { name: "Beri (Asherite)" },
  { name: "Beriah (Benjaminite)" },
  { name: "Bernice (sister)" },
  { name: "Berodach-Baladan (king)" },
  { name: "Besai (servant)" },
  { name: "Besodeiah (repairer)" },
  { name: "Bethuel (Laban's father)" },
  { name: "Bezai (returnee)" },
  { name: "Bezalel (craftsman)" },
  { name: "Bichri (Benjaminite)" },
  { name: "Bidkar (captain)" },
  { name: "Bigtha (eunuch)" },
  { name: "Bigthan (eunuch)" },
  { name: "Bigthana (eunuch)" },
  { name: "Bildad (Shuhite)" },
  { name: "Bilgah (priest)" },
  { name: "Bilgai (priest)" },
  { name: "Bilhan (Horite)" },
  { name: "Bilhah (maidservant)" },
  { name: "Bimhal (Asherite)" },
  { name: "Binea (Saul's descendant)" },
  { name: "Binnui (returnee)" },
  { name: "Birsha (king of Gomorrah)" },
  { name: "Birzaith (Asherite)" },
  { name: "Bishlam (opposer)" },
  { name: "Biztha (eunuch)" },
  { name: "Boaz (kinsman-redeemer)" },
  { name: "Bocheru (Saul's descendant)" },
  { name: "Bohan (Reubenite)" },
  { name: "Bukki (chief)" },
  { name: "Bukkiah (musician)" },
  { name: "Bunah (Judahite)" },
  { name: "Bunni (Levite)" },
  { name: "Buz (Nahor's son)" },
  { name: "Buzi (Ezekiel's father)" },
  { name: "Buzite (inhabitant)" },
  { name: "Caesar (Tiberius)" },
  { name: "Cainan (genealogy)" },
  { name: "Caiaphas (high priest)" },
  { name: "Cain (Adam's son)" },
  { name: "Caleb (spy)" },
  { name: "Canaan (Ham's son)" },
  { name: "Canaanite (inhabitant)" },
  { name: "Candace (queen)" },
  { name: "Carcas (chamberlain)" },
  { name: "Carmi (Reubenite)" },
  { name: "Carshena (prince)" },
  { name: "Casuph (servant)" },
  { name: "Cephas (Peter)" },
  { name: "Chalcol (wise man)" },
  { name: "Chelub (Judahite)" },
  { name: "Cheluhi (returnee)" },
  { name: "Chemosh (god)" },
  { name: "Chenaanah (prophet)" },
  { name: "Chenani (Levite)" },
  { name: "Chenaniah (chief)" },
  { name: "Chephirah (place)" },
  { name: "Cheran (Horite)" },
  { name: "Chesed (Nahor's son)" },
  { name: "Chileab (David's son)" },
  { name: "Chilion (Elimelech's son)" },
  { name: "Chimham (Barzillai's son)" },
  { name: "Chislon (spy)" },
  { name: "Chloe (woman)" },
  { name: "Chuza (steward)" },
  { name: "Claudia (woman)" },
  { name: "Claudius (emperor)" },
  { name: "Cleopas (disciple)" },
  { name: "Clopas (relative)" },
  { name: "Colhozeh (repairer)" },
  { name: "Conaniah (officer)" },
  { name: "Cononiah (officer)" },
  { name: "Cornelius (centurion)" },
  { name: "Cosam (Jesus' ancestor)" },
  { name: "Crescens (companion)" },
  { name: "Crispus (ruler)" },
  { name: "Cush (Ham's son)" },
  { name: "Cushi (messenger)" },
  { name: "Cushan-Rishathaim (king)" },
  { name: "Cuthah (place)" },
  { name: "Cyrus (king)" },
  { name: "Dalaiah (returnee)" },
  { name: "Dalmanutha (place)" },
  { name: "Damaris (convert)" },
  { name: "Dalphon (Haman's son)" },
  { name: "Dan (tribe)" },
  { name: "Daniel (prophet)" },
  { name: "Dara (wise man)" },
  { name: "Darda (wise man)" },
  { name: "Darius (king)" },
  { name: "Darkon (servant)" },
  { name: "Dathan (rebel)" },
  { name: "David (king)" },
  { name: "Debir (king)" },
  { name: "Deborah (judge)" },
  { name: "Dedan (Cush's son)" },
  { name: "Dedan (Raamah's son)" },
  { name: "Dekar (official)" },
  { name: "Delilah (Philistine)" },
  { name: "Demas (companion)" },
  { name: "Demetrius (silversmith)" },
  { name: "Deuel (Gadite)" },
  { name: "Diblaim (Gomer's father)" },
  { name: "Dibri (Danite)" },
  { name: "Diklah (Joktan's son)" },
  { name: "Dilan (Judahite)" },
  { name: "Dinah (Jacob's daughter)" },
  { name: "Dionysius (Areopagite)" },
  { name: "Diotrephes (opposer)" },
  { name: "Dishan (Horite)" },
  { name: "Dishon (Horite)" },
  { name: "Dodai (commander)" },
  { name: "Dodavah (Mareshah's father)" },
  { name: "Dodo (Ahohite)" },
  { name: "Doeg (Edomite)" },
  { name: "Dorcas (Tabitha)" },
  { name: "Dositheus (general)" },
  { name: "Drusilla (wife)" },
  { name: "Dumah (Ishmael's son)" },
  { name: "Dura (place)" },
  { name: "Ebal (Joktan's son)" },
  { name: "Ebed (Gaal's father)" },
  { name: "Ebed-Melech (eunuch)" },
  { name: "Eber (ancestor)" },
  { name: "Ebiasaph (Korahite)" },
  { name: "Eden (place)" },
  { name: "Eder (Beriah's son)" },
  { name: "Edom (Esau)" },
  { name: "Eglah (David's wife)" },
  { name: "Eglon (king)" },
  { name: "Ehi (Benjaminite)" },
  { name: "Ehud (judge)" },
  { name: "Eker (Judahite)" },
  { name: "Eladah (Ephraimite)" },
  { name: "Elah (king of Israel)" },
  { name: "Elam (Shem's son)" },
  { name: "Elasah (priest)" },
  { name: "Elath (place)" },
  { name: "Eldaah (Midianite)" },
  { name: "Eldad (elder)" },
  { name: "Elead (Ephraimite)" },
  { name: "Eleasah (Saul's descendant)" },
  { name: "Eleazar (Aaron's son)" },
  { name: "Elhanan (warrior)" },
  { name: "Eli (priest)" },
  { name: "Eliab (Reubenite)" },
  { name: "Eliada (David's son)" },
  { name: "Eliadah (Rezon's father)" },
  { name: "Eliakim (Hezekiah's steward)" },
  { name: "Eliam (Ahithophel's son)" },
  { name: "Eliasaph (Gadite)" },
  { name: "Eliashib (high priest)" },
  { name: "Eliathah (musician)" },
  { name: "Elidad (Benjaminite)" },
  { name: "Eliel (Mahavite)" },
  { name: "Elienai (Benjaminite)" },
  { name: "Eliezer (Abraham's servant)" },
  { name: "Elihoreph (scribe)" },
  { name: "Elijah (prophet)" },
  { name: "Elika (Harodite)" },
  { name: "Elim (place)" },
  { name: "Elimelech (Naomi's husband)" },
  { name: "Elioenai (Simeonite)" },
  { name: "Eliphal (Eliphelet)" },
  { name: "Eliphalet (David's son)" },
  { name: "Eliphaz (Temanite)" },
  { name: "Eliphelet (David's son)" },
  { name: "Elisha (prophet)" },
  { name: "Elishah (Javan's son)" },
  { name: "Elishama (David's son)" },
  { name: "Elishaphat (captain)" },
  { name: "Elisheba (Aaron's wife)" },
  { name: "Elishua (David's son)" },
  { name: "Eliud (Jesus' ancestor)" },
  { name: "Elizaphan (chief)" },
  { name: "Elizur (Reubenite)" },
  { name: "Elkanah (Samuel's father)" },
  { name: "Elmodam (Jesus' ancestor)" },
  { name: "Elnam (Esli's son)" },
  { name: "Elnathan (official)" },
  { name: "Elon (Zebulunite)" },
  { name: "Elpaal (Benjaminite)" },
  { name: "Elpalet (David's son)" },
  { name: "Elpelet (David's son)" },
  { name: "Eluzai (warrior)" },
  { name: "Elymas (Bar-Jesus)" },
  { name: "Elzabad (Gadite)" },
  { name: "Elzaphan (Kohathite)" },
  { name: "Emim (giants)" },
  { name: "Emmor (Hamor)" },
  { name: "Enan (Naphtalite)" },
  { name: "Enoch (Cain's son)" },
  { name: "Enoch (Methuselah's father)" },
  { name: "Enos (Enosh)" },
  { name: "Epaenetus (convert)" },
  { name: "Epaphras (companion)" },
  { name: "Epaphroditus (messenger)" },
  { name: "Ephah (Caleb's concubine)" },
  { name: "Ephai (Netophathite)" },
  { name: "Epher (Midianite)" },
  { name: "Ephlal (Judahite)" },
  { name: "Ephod (priest)" },
  { name: "Ephraim (tribe)" },
  { name: "Ephraimite (inhabitant)" },
  { name: "Ephron (Hittite)" },
  { name: "Er (Judah's son)" },
  { name: "Eran (Ephraimite)" },
  { name: "Erastus (treasurer)" },
  { name: "Eri (Gadite)" },
  { name: "Esarhaddon (king)" },
  { name: "Esau (patriarch)" },
  { name: "Eshban (Horite)" },
  { name: "Eshcol (Anak's brother)" },
  { name: "Eshek (Benjaminite)" },
  { name: "Eshkalon (place)" },
  { name: "Eshtemoa (Caleb's son)" },
  { name: "Eshton (Caleb's son)" },
  { name: "Esli (Jesus' ancestor)" },
  { name: "Esther (queen)" },
  { name: "Ethan (wise man)" },
  { name: "Ethbaal (king)" },
  { name: "Ethnan (Judahite)" },
  { name: "Ethni (Merarite)" },
  { name: "Eubulus (companion)" },
  { name: "Eunice (Timothy's mother)" },
  { name: "Euodia (woman)" },
  { name: "Eutychus (youth)" },
  { name: "Eve (first woman)" },
  { name: "Evil-Merodach (king)" },
  { name: "Evi (Midianite prince)" },
  { name: "Evilmerodach (king)" },
  { name: "Ezer (Horite)" },
  { name: "Ezra (scribe)" },
  { name: "Ezri (overseer)" },
  { name: "Ezrikam (captain)" },
  { name: "Eznik (Benjaminite)" },
  // Final additions to reach ~2,500
  { name: "Felix (governor)" },
  { name: "Festus (governor)" },
  { name: "Gaal (son of Ebed)" },
  { name: "Gabbai (Benjaminite)" },
  { name: "Gaddi (spy)" },
  { name: "Gaddiel (spy)" },
  { name: "Gadi (father of Menahem)" },
  { name: "Gaham (Nahor's son)" },
  { name: "Gahar (servant)" },
  { name: "Gaius (companion)" },
  { name: "Galal (Levite)" },
  { name: "Gamaliel (teacher)" },
  { name: "Gamul (priest)" },
  { name: "Gareb (Ithrite)" },
  { name: "Gatam (Eliphaz's son)" },
  { name: "Gazez (Caleb's grandson)" },
  { name: "Gazzam (servant)" },
  { name: "Gedaliah (governor)" },
  { name: "Gehazi (servant)" },
  { name: "Gemalli (spy)" },
  { name: "Gemariah (scribe)" },
  { name: "Genubath (Hadad's son)" },
  { name: "Gera (Benjaminite)" },
  { name: "Gershom (Moses' son)" },
  { name: "Gershon (Levi's son)" },
  { name: "Gesham (servant)" },
  { name: "Geshem (Arab)" },
  { name: "Gether (Aram's son)" },
  { name: "Geuel (Gadite spy)" },
  { name: "Gibeon (place)" },
  { name: "Giddalti (musician)" },
  { name: "Giddel (servant)" },
  { name: "Gideon (judge)" },
  { name: "Gideoni (Benjaminite)" },
  { name: "Gilalai (priest)" },
  { name: "Gilead (place)" },
  { name: "Ginath (Tibni's father)" },
  { name: "Ginnethon (priest)" },
  { name: "Gishpa (overseer)" },
  { name: "Gog (prince)" },
  { name: "Goliath (giant)" },
  { name: "Gomer (Japheth's son)" },
  { name: "Guni (Naphtalite)" },
  { name: "Gur (place)" },
  { name: "Gur-Baal (place)" },
  { name: "Gurgum (kingdom)" },
  { name: "Haahashtari (Judahite)" },
  { name: "Habaiah (priest)" },
  { name: "Habakkuk (prophet)" },
  { name: "Habazziniah (Levite)" },
  { name: "Hachmoni (father)" },
  { name: "Hadad (Edomite)" },
  { name: "Hadadezer (king)" },
  { name: "Hadar (Edomite king)" },
  { name: "Haddad (Edomite)" },
  { name: "Hadoram (Joktan's son)" },
  { name: "Hagab (servant)" },
  { name: "Hagaba (servant)" },
  { name: "Hagabah (servant)" },
  { name: "Haggai (prophet)" },
  { name: "Haggi (Gadite)" },
  { name: "Haggiah (Merarite)" },
  { name: "Haggith (David's wife)" },
  { name: "Hagri (father)" },
  { name: "Hakkatan (ancestor)" },
  { name: "Hakkoz (priest)" },
  { name: "Hakupha (servant)" },
  { name: "Halah (place)" },
  { name: "Hallohesh (ruler)" },
  { name: "Halohesh (ruler)" },
  { name: "Ham (Noah's son)" },
  { name: "Haman (enemy)" },
  { name: "Hamath (place)" },
  { name: "Hammedatha (Haman's father)" },
  { name: "Hammoleketh (Manassite)" },
  { name: "Hammuel (Simeonite)" },
  { name: "Hamor (Shechemite)" },
  { name: "Hamul (Judah's son)" },
  { name: "Hamutal (king's mother)" },
  { name: "Hanameel (Jeremiah's cousin)" },
  { name: "Hanan (Levite)" },
  { name: "Hanani (Nehemiah's brother)" },
  { name: "Hanniel (Asherite)" },
  { name: "Hanoch (Reubenite)" },
  { name: "Hanun (Ammonite king)" },
  { name: "Happizzez (priest)" },
  { name: "Haran (Terah's son)" },
  { name: "Harbona (chamberlain)" },
  { name: "Harbonah (chamberlain)" },
  { name: "Hareph (Caleb's son)" },
  { name: "Harhaiah (repairer)" },
  { name: "Harhas (Shallum's grandfather)" },
  { name: "Harhur (servant)" },
  { name: "Harim (priest)" },
  { name: "Hariph (returnee)" },
  { name: "Harnepher (Asherite)" },
  { name: "Haroeh (Caleb's son)" },
  { name: "Harosheth (place)" },
  { name: "Harum (Judahite)" },
  { name: "Harumaph (repairer)" },
  { name: "Haruz (king's grandfather)" },
  { name: "Hasabiah (Merarite)" },
  { name: "Hasadiah (Jeconiah's son)" },
  { name: "Hashabiah (priest)" },
  { name: "Hashabnah (signer)" },
  { name: "Hashabneiah (Levite)" },
  { name: "Hashbadana (signer)" },
  { name: "Hashem (Gizonite)" },
  { name: "Hashub (repairer)" },
  { name: "Hashubah (Jeconiah's son)" },
  { name: "Hashum (returnee)" },
  { name: "Hasrah (scribe)" },
  { name: "Hassenaah (repairer)" },
  { name: "Hasshub (repairer)" },
  { name: "Hassophereth (servant)" },
  { name: "Hasupha (servant)" },
  { name: "Hathath (Caleb's son)" },
  { name: "Hatipha (servant)" },
  { name: "Hatita (gatekeeper)" },
  { name: "Hattil (servant)" },
  { name: "Hattush (returnee)" },
  { name: "Havilah (Cush's son)" },
  { name: "Hazael (king)" },
  { name: "Hazaiah (returnee)" },
  { name: "Hazar (place)" },
  { name: "Hazarmaveth (Joktan's son)" },
  { name: "Haziel (Levite)" },
  { name: "Hazo (Nahor's son)" },
  { name: "Heber (Joktan's son)" },
  { name: "Hebron (Kohathite)" },
  { name: "Hegai (chamberlain)" },
  { name: "Helah (Asherite)" },
  { name: "Helam (place)" },
  { name: "Heldai (captain)" },
  { name: "Helem (Asherite)" },
  { name: "Helez (Ahohite)" },
  { name: "Heli (Jesus' ancestor)" },
  { name: "Helkai (priest)" },
  { name: "Helon (Zebulunite)" },
  { name: "Hemam (Horite)" },
  { name: "Heman (wise man)" },
  { name: "Hemdan (Horite)" },
  { name: "Hen (Zechariah's son)" },
  { name: "Henadad (helper)" },
  { name: "Hepher (Manassite)" },
  { name: "Hephzibah (Hezekiah's mother)" },
  { name: "Heresh (Levite)" },
  { name: "Hermas (Roman)" },
  { name: "Hermes (messenger)" },
  { name: "Hermogenes (opposer)" },
  { name: "Herod (king)" },
  { name: "Herod Antipas (tetrarch)" },
  { name: "Herod Philip (tetrarch)" },
  { name: "Herodias (queen)" },
  { name: "Hesed (Ben-Zoheth's father)" },
  { name: "Heth (Canaan's son)" },
  { name: "Hezekiah (king)" },
  { name: "Hezion (king)" },
  { name: "Hezir (captain)" },
  { name: "Hezrai (Carmelite)" },
  { name: "Hezro (Carmelite)" },
  { name: "Hezron (Judah's son)" },
  { name: "Hiddai (warrior)" },
  { name: "Hiel (Bethelite)" },
  { name: "Hilkiah (high priest)" },
  { name: "Hillel (judge)" },
  { name: "Hirah (Adullamite)" },
  { name: "Hittite (inhabitant)" },
  { name: "Hizki (Benjaminite)" },
  { name: "Hizkiah (Azariah's son)" },
  { name: "Hobab (Midianite)" },
  { name: "Hod (Asherite)" },
  { name: "Hodaiah (returnee)" },
  { name: "Hodaviah (returnee)" },
  { name: "Hodevah (returnee)" },
  { name: "Hodiah (Caleb's wife)" },
  { name: "Hoglah (Zelophehad's daughter)" },
  { name: "Hoham (king)" },
  { name: "Homam (Horite)" },
  { name: "Hophni (Eli's son)" },
  { name: "Horam (king)" },
  { name: "Hori (Esau's son)" },
  { name: "Hosah (gatekeeper)" },
  { name: "Hosea (prophet)" },
  { name: "Hoshea (king)" },
  { name: "Hotham (Asherite)" },
  { name: "Hothan (Asherite)" },
  { name: "Hothir (musician)" },
  { name: "Hul (Aram's son)" },
  { name: "Huldah (prophetess)" },
  { name: "Hupim (Benjaminite)" },
  { name: "Hur (Moses' assistant)" },
  { name: "Huri (Gadite)" },
  { name: "Hushah (Ezer's son)" },
  { name: "Hushai (friend)" },
  { name: "Husham (Edomite king)" },
  { name: "Hushim (Benjaminite)" },
  { name: "Huz (Uz)" },
  { name: "Hymenaeus (opposer)" },
  // User-requested additions (deduped)
  { name: "Abide" },
  { name: "Abram" },
  { name: "Abram's servant" },
  { name: "Abraham's servant" },
  { name: "Abram's wife" },
  { name: "Admah" },
  { name: "Amalekites" },
  { name: "Arvad" },
  { name: "Bethel" },
  { name: "Beulah" },
  { name: "Chamor" },
  { name: "Chedorlaomer" },
  { name: "Dodanim" },
  { name: "Hivite" },
  { name: "Hobah" },
  { name: "Malkiel" },
  { name: "Rachel" },
  { name: "Salah" },
  { name: "Shechem" },
  { name: "Sodom" },
  { name: "Tyrus" },
];

