import { GENESIS_CREATION_WEB_VERSES, type GenesisVerse } from "./creationOfWorldDeepNotes";

export const BIBLE_YEAR_GENESIS_WEB_VERSES: Record<number, GenesisVerse[]> = {
  ...GENESIS_CREATION_WEB_VERSES,
  5: [
    { verse: 1, text: "This is the book of the generations of Adam. In the day that God created man, he made him in God's likeness." },
    { verse: 2, text: "He created them male and female, and blessed them, and called their name Man, in the day when they were created." },
    { verse: 3, text: "Adam lived one hundred thirty years, and became the father of a son in his own likeness, after his image, and named him Seth." },
    { verse: 4, text: "The days of Adam after he became the father of Seth were eight hundred years, and he became the father of sons and daughters." },
    { verse: 5, text: "All the days that Adam lived were nine hundred thirty years, then he died." },
    { verse: 6, text: "Seth lived one hundred five years, and became the father of Enosh." },
    { verse: 7, text: "Seth lived after he became the father of Enosh eight hundred seven years, and became the father of sons and daughters." },
    { verse: 8, text: "All the days of Seth were nine hundred twelve years, then he died." },
    { verse: 9, text: "Enosh lived ninety years, and became the father of Kenan." },
    { verse: 10, text: "Enosh lived after he became the father of Kenan, eight hundred fifteen years, and became the father of sons and daughters." },
    { verse: 11, text: "All the days of Enosh were nine hundred five years, then he died." },
    { verse: 12, text: "Kenan lived seventy years, and became the father of Mahalalel." },
    { verse: 13, text: "Kenan lived after he became the father of Mahalalel eight hundred forty years, and became the father of sons and daughters." },
    { verse: 14, text: "All the days of Kenan were nine hundred ten years, then he died." },
    { verse: 15, text: "Mahalalel lived sixty-five years, and became the father of Jared." },
    { verse: 16, text: "Mahalalel lived after he became the father of Jared eight hundred thirty years, and became the father of sons and daughters." },
    { verse: 17, text: "All the days of Mahalalel were eight hundred ninety-five years, then he died." },
    { verse: 18, text: "Jared lived one hundred sixty-two years, and became the father of Enoch." },
    { verse: 19, text: "Jared lived after he became the father of Enoch eight hundred years, and became the father of sons and daughters." },
    { verse: 20, text: "All the days of Jared were nine hundred sixty-two years, then he died." },
    { verse: 21, text: "Enoch lived sixty-five years, and became the father of Methuselah." },
    { verse: 22, text: "Enoch walked with God after he became the father of Methuselah three hundred years, and became the father of sons and daughters." },
    { verse: 23, text: "All the days of Enoch were three hundred sixty-five years." },
    { verse: 24, text: "Enoch walked with God, and he was not, for God took him." },
    { verse: 25, text: "Methuselah lived one hundred eighty-seven years, and became the father of Lamech." },
    { verse: 26, text: "Methuselah lived after he became the father of Lamech seven hundred eighty-two years, and became the father of sons and daughters." },
    { verse: 27, text: "All the days of Methuselah were nine hundred sixty-nine years, then he died." },
    { verse: 28, text: "Lamech lived one hundred eighty-two years, and became the father of a son," },
    { verse: 29, text: "and he named him Noah, saying, \"This same will comfort us in our work and in the toil of our hands, because of the ground which Yahweh has cursed.\"" },
    { verse: 30, text: "Lamech lived after he became the father of Noah five hundred ninety-five years, and became the father of sons and daughters." },
    { verse: 31, text: "All the days of Lamech were seven hundred seventy-seven years, then he died." },
    { verse: 32, text: "Noah was five hundred years old, and Noah became the father of Shem, Ham, and Japheth." },
  ],
  6: [
    { verse: 1, text: "It happened, when men began to multiply on the surface of the ground, and daughters were born to them," },
    { verse: 2, text: "that God's sons saw that men's daughters were beautiful, and they took for themselves wives of all that they chose." },
    { verse: 3, text: "Yahweh said, \"My Spirit will not strive with man forever, because he also is flesh; yet will his days be one hundred twenty years.\"" },
    { verse: 4, text: "The Nephilim were in the earth in those days, and also after that, when God's sons came in to men's daughters. They bore children to them. Those were the mighty men who were of old, men of renown." },
    { verse: 5, text: "Yahweh saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually." },
    { verse: 6, text: "Yahweh was sorry that he had made man on the earth, and it grieved him in his heart." },
    { verse: 7, text: "Yahweh said, \"I will destroy man whom I have created from the surface of the ground; man, along with animals, creeping things, and birds of the sky; for I am sorry that I have made them.\"" },
    { verse: 8, text: "But Noah found favor in Yahweh's eyes." },
    { verse: 9, text: "This is the history of the generations of Noah. Noah was a righteous man, blameless among the people of his time. Noah walked with God." },
    { verse: 10, text: "Noah became the father of three sons: Shem, Ham, and Japheth." },
    { verse: 11, text: "The earth was corrupt before God, and the earth was filled with violence." },
    { verse: 12, text: "God saw the earth, and saw that it was corrupt, for all flesh had corrupted their way on the earth." },
    { verse: 13, text: "God said to Noah, \"The end of all flesh has come before me, for the earth is filled with violence through them. Behold, I will destroy them with the earth." },
    { verse: 14, text: "Make a ship of gopher wood. You shall make rooms in the ship, and shall seal it inside and outside with pitch." },
    { verse: 15, text: "This is how you shall make it. The length of the ship will be three hundred cubits, the breadth of it fifty cubits, and the height of it thirty cubits." },
    { verse: 16, text: "You shall make a roof in the ship, and to a cubit shall you finish it upward. You shall set the door of the ship in its side. You shall make it with lower, second, and third levels." },
    { verse: 17, text: "I, even I, do bring the flood of waters on this earth, to destroy all flesh having the breath of life from under the sky. Everything that is in the earth will die." },
    { verse: 18, text: "But I will establish my covenant with you. You shall come into the ship, you, your sons, your wife, and your sons' wives with you." },
    { verse: 19, text: "Of every living thing of all flesh, you shall bring two of every sort into the ship, to keep them alive with you. They shall be male and female." },
    { verse: 20, text: "Of the birds after their kind, of the livestock after their kind, of every creeping thing of the ground after its kind, two of every sort shall come to you, to keep them alive." },
    { verse: 21, text: "Take with you of all food that is eaten, and gather it to you; and it will be for food for you, and for them.\"" },
    { verse: 22, text: "Thus Noah did. According to all that God commanded him, so he did." },
  ],
  7: [
    { verse: 1, text: "Yahweh said to Noah, \"Come with all of your household into the ship, for I have seen your righteousness before me in this generation." },
    { verse: 2, text: "You shall take seven pairs of every clean animal with you, the male and his female. Of the animals that are not clean, take two, the male and his female." },
    { verse: 3, text: "Also of the birds of the sky, seven and seven, male and female, to keep seed alive on the surface of all the earth." },
    { verse: 4, text: "In seven days, I will cause it to rain on the earth for forty days and forty nights. Every living thing that I have made, I will destroy from the surface of the ground.\"" },
    { verse: 5, text: "Noah did everything that Yahweh commanded him." },
    { verse: 6, text: "Noah was six hundred years old when the flood of waters came on the earth." },
    { verse: 7, text: "Noah went into the ship with his sons, his wife, and his sons' wives, because of the waters of the flood." },
    { verse: 8, text: "Clean animals, animals that are not clean, birds, and everything that creeps on the ground" },
    { verse: 9, text: "went by pairs to Noah into the ship, male and female, as God commanded Noah." },
    { verse: 10, text: "It happened after the seven days, that the waters of the flood came on the earth." },
    { verse: 11, text: "In the six hundredth year of Noah's life, in the second month, on the seventeenth day of the month, on the same day all the fountains of the great deep were burst open, and the sky's windows were opened." },
    { verse: 12, text: "The rain was on the earth forty days and forty nights." },
    { verse: 13, text: "In the same day Noah, and Shem, Ham, and Japheth, the sons of Noah, and Noah's wife, and the three wives of his sons with them, entered into the ship;" },
    { verse: 14, text: "they, and every animal after its kind, all the livestock after their kind, every creeping thing that creeps on the earth after its kind, and every bird after its kind, every bird of every sort." },
    { verse: 15, text: "They went to Noah into the ship, by pairs of all flesh with the breath of life in them." },
    { verse: 16, text: "Those who went in, went in male and female of all flesh, as God commanded him; and Yahweh shut him in." },
    { verse: 17, text: "The flood was forty days on the earth. The waters increased, and lifted up the ship, and it was lifted up above the earth." },
    { verse: 18, text: "The waters prevailed, and increased greatly on the earth; and the ship floated on the surface of the waters." },
    { verse: 19, text: "The waters prevailed exceedingly on the earth. All the high mountains that were under the whole sky were covered." },
    { verse: 20, text: "The waters prevailed fifteen cubits upward, and the mountains were covered." },
    { verse: 21, text: "All flesh died that moved on the earth, including birds, livestock, animals, every creeping thing that creeps on the earth, and every man." },
    { verse: 22, text: "All in whose nostrils was the breath of the spirit of life, of all that was on the dry land, died." },
    { verse: 23, text: "Every living thing was destroyed that was on the surface of the ground, including man, livestock, creeping things, and birds of the sky. They were destroyed from the earth. Only Noah was left, and those who were with him in the ship." },
    { verse: 24, text: "The waters prevailed on the earth one hundred fifty days." },
  ],
  8: [
    { verse: 1, text: "And God remembered Noah, and every living thing, and all the cattle that was with him in the ark: and God made a wind to pass over the earth, and the waters asswaged;" },
    { verse: 2, text: "The fountains also of the deep and the windows of heaven were stopped, and the rain from heaven was restrained;" },
    { verse: 3, text: "And the waters returned from off the earth continually: and after the end of the hundred and fifty days the waters were abated." },
    { verse: 4, text: "And the ark rested in the seventh month, on the seventeenth day of the month, upon the mountains of Ararat." },
    { verse: 5, text: "And the waters decreased continually until the tenth month: in the tenth month, on the first day of the month, were the tops of the mountains seen." },
    { verse: 6, text: "And it came to pass at the end of forty days, that Noah opened the window of the ark which he had made:" },
    { verse: 7, text: "And he sent forth a raven, which went forth to and fro, until the waters were dried up from off the earth." },
    { verse: 8, text: "Also he sent forth a dove from him, to see if the waters were abated from off the face of the ground;" },
    { verse: 9, text: "But the dove found no rest for the sole of her foot, and she returned unto him into the ark, for the waters were on the face of the whole earth: then he put forth his hand, and took her, and pulled her in unto him into the ark." },
    { verse: 10, text: "And he stayed yet other seven days; and again he sent forth the dove out of the ark;" },
    { verse: 11, text: "And the dove came in to him in the evening; and, lo, in her mouth was an olive leaf pluckt off: so Noah knew that the waters were abated from off the earth." },
    { verse: 12, text: "And he stayed yet other seven days; and sent forth the dove; which returned not again unto him any more." },
    { verse: 13, text: "And it came to pass in the six hundredth and first year, in the first month, the first day of the month, the waters were dried up from off the earth: and Noah removed the covering of the ark, and looked, and, behold, the face of the ground was dry." },
    { verse: 14, text: "And in the second month, on the seven and twentieth day of the month, was the earth dried." },
    { verse: 15, text: "And God spake unto Noah, saying," },
    { verse: 16, text: "Go forth of the ark, thou, and thy wife, and thy sons, and thy sons' wives with thee." },
    { verse: 17, text: "Bring forth with thee every living thing that is with thee, of all flesh, both of fowl, and of cattle, and of every creeping thing that creepeth upon the earth; that they may breed abundantly in the earth, and be fruitful, and multiply upon the earth." },
    { verse: 18, text: "And Noah went forth, and his sons, and his wife, and his sons' wives with him:" },
    { verse: 19, text: "Every beast, every creeping thing, and every fowl, and whatsoever creepeth upon the earth, after their kinds, went forth out of the ark." },
    { verse: 20, text: "And Noah builded an altar unto the LORD; and took of every clean beast, and of every clean fowl, and offered burnt offerings on the altar." },
    { verse: 21, text: "And the LORD smelled a sweet savour; and the LORD said in his heart, I will not again curse the ground any more for man's sake; for the imagination of man's heart is evil from his youth; neither will I again smite any more every thing living, as I have done." },
    { verse: 22, text: "While the earth remaineth, seedtime and harvest, and cold and heat, and summer and winter, and day and night shall not cease." },
  ],
  9: [
    { verse: 1, text: "And God blessed Noah and his sons, and said unto them, Be fruitful, and multiply, and replenish the earth." },
    { verse: 2, text: "And the fear of you and the dread of you shall be upon every beast of the earth, and upon every fowl of the air, upon all that moveth upon the earth, and upon all the fishes of the sea; into your hand are they delivered." },
    { verse: 3, text: "Every moving thing that liveth shall be meat for you; even as the green herb have I given you all things." },
    { verse: 4, text: "But flesh with the life thereof, which is the blood thereof, shall ye not eat." },
    { verse: 5, text: "And surely your blood of your lives will I require; at the hand of every beast will I require it, and at the hand of man; at the hand of every man's brother will I require the life of man." },
    { verse: 6, text: "Whoso sheddeth man's blood, by man shall his blood be shed: for in the image of God made he man." },
    { verse: 7, text: "And you, be ye fruitful, and multiply; bring forth abundantly in the earth, and multiply therein." },
    { verse: 8, text: "And God spake unto Noah, and to his sons with him, saying," },
    { verse: 9, text: "And I, behold, I establish my covenant with you, and with your seed after you;" },
    { verse: 10, text: "And with every living creature that is with you, of the fowl, of the cattle, and of every beast of the earth with you; from all that go out of the ark, to every beast of the earth." },
    { verse: 11, text: "And I will establish my covenant with you; neither shall all flesh be cut off any more by the waters of a flood; neither shall there any more be a flood to destroy the earth." },
    { verse: 12, text: "And God said, This is the token of the covenant which I make between me and you and every living creature that is with you, for perpetual generations:" },
    { verse: 13, text: "I do set my bow in the cloud, and it shall be for a token of a covenant between me and the earth." },
    { verse: 14, text: "And it shall come to pass, when I bring a cloud over the earth, that the bow shall be seen in the cloud:" },
    { verse: 15, text: "And I will remember my covenant, which is between me and you and every living creature of all flesh; and the waters shall no more become a flood to destroy all flesh." },
    { verse: 16, text: "And the bow shall be in the cloud; and I will look upon it, that I may remember the everlasting covenant between God and every living creature of all flesh that is upon the earth." },
    { verse: 17, text: "And God said unto Noah, This is the token of the covenant, which I have established between me and all flesh that is upon the earth." },
    { verse: 18, text: "And the sons of Noah, that went forth of the ark, were Shem, and Ham, and Japheth: and Ham is the father of Canaan." },
    { verse: 19, text: "These are the three sons of Noah: and of them was the whole earth overspread." },
    { verse: 20, text: "And Noah began to be an husbandman, and he planted a vineyard:" },
    { verse: 21, text: "And he drank of the wine, and was drunken; and he was uncovered within his tent." },
    { verse: 22, text: "And Ham, the father of Canaan, saw the nakedness of his father, and told his two brethren without." },
    { verse: 23, text: "And Shem and Japheth took a garment, and laid it upon both their shoulders, and went backward, and covered the nakedness of their father; and their faces were backward, and they saw not their father's nakedness." },
    { verse: 24, text: "And Noah awoke from his wine, and knew what his younger son had done unto him." },
    { verse: 25, text: "And he said, Cursed be Canaan; a servant of servants shall he be unto his brethren." },
    { verse: 26, text: "And he said, Blessed be the LORD God of Shem; and Canaan shall be his servant." },
    { verse: 27, text: "God shall enlarge Japheth, and he shall dwell in the tents of Shem; and Canaan shall be his servant." },
    { verse: 28, text: "And Noah lived after the flood three hundred and fifty years." },
    { verse: 29, text: "And all the days of Noah were nine hundred and fifty years: and he died." },
  ],
  10: [
    { verse: 1, text: "Now these are the generations of the sons of Noah, Shem, Ham, and Japheth: and unto them were sons born after the flood." },
    { verse: 2, text: "The sons of Japheth; Gomer, and Magog, and Madai, and Javan, and Tubal, and Meshech, and Tiras." },
    { verse: 3, text: "And the sons of Gomer; Ashkenaz, and Riphath, and Togarmah." },
    { verse: 4, text: "And the sons of Javan; Elishah, and Tarshish, Kittim, and Dodanim." },
    { verse: 5, text: "By these were the isles of the Gentiles divided in their lands; every one after his tongue, after their families, in their nations." },
    { verse: 6, text: "And the sons of Ham; Cush, and Mizraim, and Phut, and Canaan." },
    { verse: 7, text: "And the sons of Cush; Seba, and Havilah, and Sabtah, and Raamah, and Sabtechah: and the sons of Raamah; Sheba, and Dedan." },
    { verse: 8, text: "And Cush begat Nimrod: he began to be a mighty one in the earth." },
    { verse: 9, text: "He was a mighty hunter before the LORD: wherefore it is said, Even as Nimrod the mighty hunter before the LORD." },
    { verse: 10, text: "And the beginning of his kingdom was Babel, and Erech, and Accad, and Calneh, in the land of Shinar." },
    { verse: 11, text: "Out of that land went forth Asshur, and builded Nineveh, and the city Rehoboth, and Calah," },
    { verse: 12, text: "And Resen between Nineveh and Calah: the same is a great city." },
    { verse: 13, text: "And Mizraim begat Ludim, and Anamim, and Lehabim, and Naphtuhim," },
    { verse: 14, text: "And Pathrusim, and Casluhim, (out of whom came Philistim,) and Caphtorim." },
    { verse: 15, text: "And Canaan begat Sidon his firstborn, and Heth," },
    { verse: 16, text: "And the Jebusite, and the Amorite, and the Girgasite," },
    { verse: 17, text: "And the Hivite, and the Arkite, and the Sinite," },
    { verse: 18, text: "And the Arvadite, and the Zemarite, and the Hamathite: and afterward were the families of the Canaanites spread abroad." },
    { verse: 19, text: "And the border of the Canaanites was from Sidon, as thou comest to Gerar, unto Gaza; as thou goest, unto Sodom, and Gomorrah, and Admah, and Zeboim, even unto Lasha." },
    { verse: 20, text: "These are the sons of Ham, after their families, after their tongues, in their countries, and in their nations." },
    { verse: 21, text: "Unto Shem also, the father of all the children of Eber, the brother of Japheth the elder, even to him were children born." },
    { verse: 22, text: "The children of Shem; Elam, and Asshur, and Arphaxad, and Lud, and Aram." },
    { verse: 23, text: "And the children of Aram; Uz, and Hul, and Gether, and Mash." },
    { verse: 24, text: "And Arphaxad begat Salah; and Salah begat Eber." },
    { verse: 25, text: "And unto Eber were born two sons: the name of one was Peleg; for in his days was the earth divided; and his brother's name was Joktan." },
    { verse: 26, text: "And Joktan begat Almodad, and Sheleph, and Hazar-maveth, and Jerah," },
    { verse: 27, text: "And Hadoram, and Uzal, and Diklah," },
    { verse: 28, text: "And Obal, and Abimael, and Sheba," },
    { verse: 29, text: "And Ophir, and Havilah, and Jobab: all these were the sons of Joktan." },
    { verse: 30, text: "And their dwelling was from Mesha, as thou goest unto Sephar a mount of the east." },
    { verse: 31, text: "These are the sons of Shem, after their families, after their tongues, in their lands, after their nations." },
    { verse: 32, text: "These are the families of the sons of Noah, after their generations, in their nations: and by these were the nations divided in the earth after the flood." },
  ],
  11: [
    { verse: 1, text: "And the whole earth was of one language, and of one speech." },
    { verse: 2, text: "And it came to pass, as they journeyed from the east, that they found a plain in the land of Shinar; and they dwelt there." },
    { verse: 3, text: "And they said one to another, Go to, let us make brick, and burn them throughly. And they had brick for stone, and slime had they for morter." },
    { verse: 4, text: "And they said, Go to, let us build us a city and a tower, whose top may reach unto heaven; and let us make us a name, lest we be scattered abroad upon the face of the whole earth." },
    { verse: 5, text: "And the LORD came down to see the city and the tower, which the children of men builded." },
    { verse: 6, text: "And the LORD said, Behold, the people is one, and they have all one language; and this they begin to do: and now nothing will be restrained from them, which they have imagined to do." },
    { verse: 7, text: "Go to, let us go down, and there confound their language, that they may not understand one another's speech." },
    { verse: 8, text: "So the LORD scattered them abroad from thence upon the face of all the earth: and they left off to build the city." },
    { verse: 9, text: "Therefore is the name of it called Babel; because the LORD did there confound the language of all the earth: and from thence did the LORD scatter them abroad upon the face of all the earth." },
    { verse: 10, text: "These are the generations of Shem: Shem was an hundred years old, and begat Arphaxad two years after the flood:" },
    { verse: 11, text: "And Shem lived after he begat Arphaxad five hundred years, and begat sons and daughters." },
    { verse: 12, text: "And Arphaxad lived five and thirty years, and begat Salah:" },
    { verse: 13, text: "And Arphaxad lived after he begat Salah four hundred and three years, and begat sons and daughters." },
    { verse: 14, text: "And Salah lived thirty years, and begat Eber:" },
    { verse: 15, text: "And Salah lived after he begat Eber four hundred and three years, and begat sons and daughters." },
    { verse: 16, text: "And Eber lived four and thirty years, and begat Peleg:" },
    { verse: 17, text: "And Eber lived after he begat Peleg four hundred and thirty years, and begat sons and daughters." },
    { verse: 18, text: "And Peleg lived thirty years, and begat Reu:" },
    { verse: 19, text: "And Peleg lived after he begat Reu two hundred and nine years, and begat sons and daughters." },
    { verse: 20, text: "And Reu lived two and thirty years, and begat Serug:" },
    { verse: 21, text: "And Reu lived after he begat Serug two hundred and seven years, and begat sons and daughters." },
    { verse: 22, text: "And Serug lived thirty years, and begat Nahor:" },
    { verse: 23, text: "And Serug lived after he begat Nahor two hundred years, and begat sons and daughters." },
    { verse: 24, text: "And Nahor lived nine and twenty years, and begat Terah:" },
    { verse: 25, text: "And Nahor lived after he begat Terah an hundred and nineteen years, and begat sons and daughters." },
    { verse: 26, text: "And Terah lived seventy years, and begat Abram, Nahor, and Haran." },
    { verse: 27, text: "Now these are the generations of Terah: Terah begat Abram, Nahor, and Haran; and Haran begat Lot." },
    { verse: 28, text: "And Haran died before his father Terah in the land of his nativity, in Ur of the Chaldees." },
    { verse: 29, text: "And Abram and Nahor took them wives: the name of Abram's wife was Sarai; and the name of Nahor's wife, Milcah, the daughter of Haran, the father of Milcah, and the father of Iscah." },
    { verse: 30, text: "But Sarai was barren; she had no child." },
    { verse: 31, text: "And Terah took Abram his son, and Lot the son of Haran his son's son, and Sarai his daughter in law, his son Abram's wife; and they went forth with them from Ur of the Chaldees, to go into the land of Canaan; and they came unto Haran, and dwelt there." },
    { verse: 32, text: "And the days of Terah were two hundred and five years: and Terah died in Haran." },
  ],
  12: [
    { verse: 1, text: "Now the LORD had said unto Abram, Get thee out of thy country, and from thy kindred, and from thy father's house, unto a land that I will shew thee:" },
    { verse: 2, text: "And I will make of thee a great nation, and I will bless thee, and make thy name great; and thou shalt be a blessing:" },
    { verse: 3, text: "And I will bless them that bless thee, and curse him that curseth thee: and in thee shall all families of the earth be blessed." },
    { verse: 4, text: "So Abram departed, as the LORD had spoken unto him; and Lot went with him: and Abram was seventy and five years old when he departed out of Haran." },
    { verse: 5, text: "And Abram took Sarai his wife, and Lot his brother's son, and all their substance that they had gathered, and the souls that they had gotten in Haran; and they went forth to go into the land of Canaan; and into the land of Canaan they came." },
    { verse: 6, text: "And Abram passed through the land unto the place of Sichem, unto the plain of Moreh. And the Canaanite was then in the land." },
    { verse: 7, text: "And the LORD appeared unto Abram, and said, Unto thy seed will I give this land: and there builded he an altar unto the LORD, who appeared unto him." },
    { verse: 8, text: "And he removed from thence unto a mountain on the east of Bethel, and pitched his tent, having Bethel on the west, and Hai on the east: and there he builded an altar unto the LORD, and called upon the name of the LORD." },
    { verse: 9, text: "And Abram journeyed, going on still toward the south." },
    { verse: 10, text: "And there was a famine in the land: and Abram went down into Egypt to sojourn there; for the famine was grievous in the land." },
    { verse: 11, text: "And it came to pass, when he was come near to enter into Egypt, that he said unto Sarai his wife, Behold now, I know that thou art a fair woman to look upon:" },
    { verse: 12, text: "Therefore it shall come to pass, when the Egyptians shall see thee, that they shall say, This is his wife: and they will kill me, but they will save thee alive." },
    { verse: 13, text: "Say, I pray thee, thou art my sister: that it may be well with me for thy sake; and my soul shall live because of thee." },
    { verse: 14, text: "And it came to pass, that, when Abram was come into Egypt, the Egyptians beheld the woman that she was very fair." },
    { verse: 15, text: "The princes also of Pharaoh saw her, and commended her before Pharaoh: and the woman was taken into Pharaoh's house." },
    { verse: 16, text: "And he entreated Abram well for her sake: and he had sheep, and oxen, and he asses, and menservants, and maidservants, and she asses, and camels." },
    { verse: 17, text: "And the LORD plagued Pharaoh and his house with great plagues because of Sarai Abram's wife." },
    { verse: 18, text: "And Pharaoh called Abram, and said, What is this that thou hast done unto me? why didst thou not tell me that she was thy wife?" },
    { verse: 19, text: "Why saidst thou, She is my sister? so I might have taken her to me to wife: now therefore behold thy wife, take her, and go thy way." },
    { verse: 20, text: "And Pharaoh commanded his men concerning him: and they sent him away, and his wife, and all that he had." },
  ],
  13: [
    { verse: 1, text: "And Abram went up out of Egypt, he, and his wife, and all that he had, and Lot with him, into the south." },
    { verse: 2, text: "And Abram was very rich in cattle, in silver, and in gold." },
    { verse: 3, text: "And he went on his journeys from the south even to Bethel, unto the place where his tent had been at the beginning, between Bethel and Hai;" },
    { verse: 4, text: "Unto the place of the altar, which he had made there at the first: and there Abram called on the name of the LORD." },
    { verse: 5, text: "And Lot also, which went with Abram, had flocks, and herds, and tents." },
    { verse: 6, text: "And the land was not able to bear them, that they might dwell together: for their substance was great, so that they could not dwell together." },
    { verse: 7, text: "And there was a strife between the herdmen of Abram's cattle and the herdmen of Lot's cattle: and the Canaanite and the Perizzite dwelled then in the land." },
    { verse: 8, text: "And Abram said unto Lot, Let there be no strife, I pray thee, between me and thee, and between my herdmen and thy herdmen; for we be brethren." },
    { verse: 9, text: "Is not the whole land before thee? separate thyself, I pray thee, from me: if thou wilt take the left hand, then I will go to the right; or if thou depart to the right hand, then I will go to the left." },
    { verse: 10, text: "And Lot lifted up his eyes, and beheld all the plain of Jordan, that it was well watered every where, before the LORD destroyed Sodom and Gomorrah, even as the garden of the LORD, like the land of Egypt, as thou comest unto Zoar." },
    { verse: 11, text: "Then Lot chose him all the plain of Jordan; and Lot journeyed east: and they separated themselves the one from the other." },
    { verse: 12, text: "Abram dwelled in the land of Canaan, and Lot dwelled in the cities of the plain, and pitched his tent toward Sodom." },
    { verse: 13, text: "But the men of Sodom were wicked and sinners before the LORD exceedingly." },
    { verse: 14, text: "And the LORD said unto Abram, after that Lot was separated from him, Lift up now thine eyes, and look from the place where thou art northward, and southward, and eastward, and westward:" },
    { verse: 15, text: "For all the land which thou seest, to thee will I give it, and to thy seed for ever." },
    { verse: 16, text: "And I will make thy seed as the dust of the earth: so that if a man can number the dust of the earth, then shall thy seed also be numbered." },
    { verse: 17, text: "Arise, walk through the land in the length of it and in the breadth of it; for I will give it unto thee." },
    { verse: 18, text: "Then Abram removed his tent, and came and dwelt in the plain of Mamre, which is in Hebron, and built there an altar unto the LORD." },
  ],
  14: [
    { verse: 1, text: "And it came to pass in the days of Amraphel king of Shinar, Arioch king of Ellasar, Chedorlaomer king of Elam, and Tidal king of nations;" },
    { verse: 2, text: "That these made war with Bera king of Sodom, and with Birsha king of Gomorrah, Shinab king of Admah, and Shemeber king of Zeboiim, and the king of Bela, which is Zoar." },
    { verse: 3, text: "All these were joined together in the vale of Siddim, which is the salt sea." },
    { verse: 4, text: "Twelve years they served Chedorlaomer, and in the thirteenth year they rebelled." },
    { verse: 5, text: "And in the fourteenth year came Chedorlaomer, and the kings that were with him, and smote the Rephaims in Ashteroth Karnaim, and the Zuzims in Ham, and the Emims in Shaveh Kiriathaim," },
    { verse: 6, text: "And the Horites in their mount Seir, unto Elparan, which is by the wilderness." },
    { verse: 7, text: "And they returned, and came to Enmishpat, which is Kadesh, and smote all the country of the Amalekites, and also the Amorites, that dwelt in Hazezontamar." },
    { verse: 8, text: "And there went out the king of Sodom, and the king of Gomorrah, and the king of Admah, and the king of Zeboiim, and the king of Bela (the same is Zoar;) and they joined battle with them in the vale of Siddim;" },
    { verse: 9, text: "With Chedorlaomer the king of Elam, and with Tidal king of nations, and Amraphel king of Shinar, and Arioch king of Ellasar; four kings with five." },
    { verse: 10, text: "And the vale of Siddim was full of slimepits; and the kings of Sodom and Gomorrah fled, and fell there; and they that remained fled to the mountain." },
    { verse: 11, text: "And they took all the goods of Sodom and Gomorrah, and all their victuals, and went their way." },
    { verse: 12, text: "And they took Lot, Abram's brother's son, who dwelt in Sodom, and his goods, and departed." },
    { verse: 13, text: "And there came one that had escaped, and told Abram the Hebrew; for he dwelt in the plain of Mamre the Amorite, brother of Eshcol, and brother of Aner: and these were confederate with Abram." },
    { verse: 14, text: "And when Abram heard that his brother was taken captive, he armed his trained servants, born in his own house, three hundred and eighteen, and pursued them unto Dan." },
    { verse: 15, text: "And he divided himself against them, he and his servants, by night, and smote them, and pursued them unto Hobah, which is on the left hand of Damascus." },
    { verse: 16, text: "And he brought back all the goods, and also brought again his brother Lot, and his goods, and the women also, and the people." },
    { verse: 17, text: "And the king of Sodom went out to meet him after his return from the slaughter of Chedorlaomer, and of the kings that were with him, at the valley of Shaveh, which is the king's dale." },
    { verse: 18, text: "And Melchizedek king of Salem brought forth bread and wine: and he was the priest of the most high God." },
    { verse: 19, text: "And he blessed him, and said, Blessed be Abram of the most high God, possessor of heaven and earth:" },
    { verse: 20, text: "And blessed be the most high God, which hath delivered thine enemies into thy hand. And he gave him tithes of all." },
    { verse: 21, text: "And the king of Sodom said unto Abram, Give me the persons, and take the goods to thyself." },
    { verse: 22, text: "And Abram said to the king of Sodom, I have lift up mine hand unto the LORD, the most high God, the possessor of heaven and earth," },
    { verse: 23, text: "That I will not take from a thread even to a shoelatchet, and that I will not take any thing that is thine, lest thou shouldest say, I have made Abram rich:" },
    { verse: 24, text: "Save only that which the young men have eaten, and the portion of the men which went with me, Aner, Eshcol, and Mamre; let them take their portion." },
  ],
  15: [
    { verse: 1, text: "After these things the word of the LORD came unto Abram in a vision, saying, Fear not, Abram: I am thy shield, and thy exceeding great reward." },
    { verse: 2, text: "And Abram said, Lord GOD, what wilt thou give me, seeing I go childless, and the steward of my house is this Eliezer of Damascus?" },
    { verse: 3, text: "And Abram said, Behold, to me thou hast given no seed: and, lo, one born in my house is mine heir." },
    { verse: 4, text: "And, behold, the word of the LORD came unto him, saying, This shall not be thine heir; but he that shall come forth out of thine own bowels shall be thine heir." },
    { verse: 5, text: "And he brought him forth abroad, and said, Look now toward heaven, and tell the stars, if thou be able to number them: and he said unto him, So shall thy seed be." },
    { verse: 6, text: "And he believed in the LORD; and he counted it to him for righteousness." },
    { verse: 7, text: "And he said unto him, I am the LORD that brought thee out of Ur of the Chaldees, to give thee this land to inherit it." },
    { verse: 8, text: "And he said, Lord GOD, whereby shall I know that I shall inherit it?" },
    { verse: 9, text: "And he said unto him, Take me an heifer of three years old, and a she goat of three years old, and a ram of three years old, and a turtledove, and a young pigeon." },
    { verse: 10, text: "And he took unto him all these, and divided them in the midst, and laid each piece one against another: but the birds divided he not." },
    { verse: 11, text: "And when the fowls came down upon the carcases, Abram drove them away." },
    { verse: 12, text: "And when the sun was going down, a deep sleep fell upon Abram; and, lo, an horror of great darkness fell upon him." },
    { verse: 13, text: "And he said unto Abram, Know of a surety that thy seed shall be a stranger in a land that is not theirs, and shall serve them; and they shall afflict them four hundred years;" },
    { verse: 14, text: "And also that nation, whom they shall serve, will I judge: and afterward shall they come out with great substance." },
    { verse: 15, text: "And thou shalt go to thy fathers in peace; thou shalt be buried in a good old age." },
    { verse: 16, text: "But in the fourth generation they shall come hither again: for the iniquity of the Amorites is not yet full." },
    { verse: 17, text: "And it came to pass, that, when the sun went down, and it was dark, behold a smoking furnace, and a burning lamp that passed between those pieces." },
    { verse: 18, text: "In the same day the LORD made a covenant with Abram, saying, Unto thy seed have I given this land, from the river of Egypt unto the great river, the river Euphrates:" },
    { verse: 19, text: "The Kenites, and the Kenizzites, and the Kadmonites," },
    { verse: 20, text: "And the Hittites, and the Perizzites, and the Rephaims," },
    { verse: 21, text: "And the Amorites, and the Canaanites, and the Girgashites, and the Jebusites." },
  ],
};
