export const EXPANDED_BIBLE_STUDY_KEYWORDS: string[] = [
  "abomination of desolation",
  "altar of incense",
  "ark of the covenant",
  "atoning sacrifice",
  "baptism of repentance",
  "beatitudes",
  "book of the law",
  "book of life",
  "bread of life",
  "bronze altar",
  "bronze serpent",
  "burning bush",
  "captivity",
  "chief cornerstone",
  "cloud by day",
  "cornerstone",
  "courtyard",
  "covenant faithfulness",
  "day of atonement",
  "day of the Lord",
  "days of unleavened bread",
  "double minded",
  "everlasting covenant",
  "fear of the Lord",
  "fellowship offering",
  "firstfruits",
  "fruit of the Spirit",
  "glory of God",
  "golden calf",
  "good shepherd",
  "great commission",
  "great high priest",
  "holies of holies",
  "holy of holies",
  "holy spirit",
  "house of prayer",
  "image of God",
  "indwelling",
  "kingdom of God",
  "kingdom of heaven",
  "lake of fire",
  "lamb of God",
  "law of Moses",
  "living hope",
  "living water",
  "longsuffering",
  "lord of hosts",
  "lord of lords",
  "man of lawlessness",
  "marvel",
  "mercy seat",
  "ministry of reconciliation",
  "most holy place",
  "new birth",
  "new covenant",
  "new creation",
  "passion week",
  "peace offering",
  "pillar of cloud",
  "pillar of fire",
  "prince of peace",
  "promised land",
  "prophet like Moses",
  "pure in heart",
  "red sea",
  "refiner",
  "remnant",
  "resurrection of the dead",
  "river of life",
  "root of Jesse",
  "sabbath rest",
  "scapegoat",
  "scroll of the prophet Isaiah",
  "second death",
  "seed of Abraham",
  "seed of the woman",
  "sermon on the mount",
  "shofar",
  "sin offering",
  "son of David",
  "son of God",
  "son of man",
  "spiritual gifts",
  "stiff necked",
  "tabernacle of meeting",
  "table of showbread",
  "temple curtain",
  "tent of meeting",
  "throne of grace",
  "tree of life",
  "tribulation",
  "trumpet",
  "unleavened bread",
  "veil",
  "voice crying in the wilderness",
  "washing of regeneration",
  "white robe",
  "word became flesh",
  "word of God",
  "wrath of God",
  "yoke of slavery",
  "zeal",
  "abide in me",
  "abraham's bosom",
  "advocate",
  "alpha and omega",
  "ancient of days",
  "armor of God",
  "author and finisher of our faith",
  "book of remembrance",
  "captain of the Lord's host",
  "carnal mind",
  "chief priests",
  "communion",
  "crown of life",
  "daily bread",
  "denarius",
  "doers of the word",
  "double portion",
  "faith comes by hearing",
  "faith without works",
  "former rain",
  "frankincense",
  "full armor of God",
  "gehenna",
  "gift of God",
  "gospel of peace",
  "gospel of the kingdom",
  "great white throne",
  "helmet of salvation",
  "high places",
  "high priest",
  "hyssop",
  "image of the invisible God",
  "indescribable gift",
  "iniquity",
  "jot and tittle",
  "joy of the Lord",
  "justification",
  "king of kings",
  "laborers are few",
  "latter rain",
  "law and the prophets",
  "leaven of the pharisees",
  "light of the world",
  "lion of the tribe of Judah",
  "man shall not live by bread alone",
  "mammon",
  "meekness",
  "ministry of death",
  "myrrh",
  "oil of gladness",
  "peace that passes understanding",
  "pearl of great price",
  "physician heal yourself",
  "potsherd",
  "power of darkness",
  "propitiation",
  "pure religion",
  "refuge city",
  "refuge cities",
  "renewing of your mind",
  "robe of righteousness",
  "rod and staff",
  "schoolmaster",
  "scribe",
  "shekel",
  "sheol",
  "shield of faith",
  "signet ring",
  "still small voice",
  "sword of the Spirit",
  "tetrarch",
  "time of the gentiles",
  "treasure in heaven",
  "tribulation saints",
  "true vine",
  "washing of water by the word",
  "wheat and tares",
  "white stone",
  "whole armor of God",
  "wise as serpents",
  "yoke is easy",
  "zeal of the Lord",
];
