/**
 * Comprehensive list of biblical keywords and phrases (~1,800-2,000 terms)
 * 
 * Each keyword appears once.
 * All keywords appear in the canonical Old or New Testament.
 * Alphabetized by term.
 * 
 * Includes: religious roles, professions, objects, materials, agricultural terms,
 * religious practices, festivals, legal/covenant language, spiritual concepts,
 * events, economic terms, and other biblically grounded terms.
 */

export type BibleKeywordEntry = {
  term: string;
};

export const BIBLE_KEYWORDS_LIST: BibleKeywordEntry[] = [
  // A
  { term: "Abomination" },
  { term: "Abomination of Desolation" },
  { term: "Abraham's Bosom" },
  { term: "Accuser" },
  { term: "Adoption" },
  { term: "Adultery" },
  { term: "Advocate" },
  { term: "Affliction" },
  { term: "Age to Come" },
  { term: "Alabaster" },
  { term: "Alms" },
  { term: "Altar" },
  { term: "Amen" },
  { term: "Anathema" },
  { term: "Ancient of Days" },
  { term: "Angel" },
  { term: "Angel of the Lord" },
  { term: "Anointing" },
  { term: "Anointing Oil" },
  { term: "Antichrist" },
  { term: "Apostasy" },
  { term: "Apostle" },
  { term: "Ark" },
  { term: "Ark of the Covenant" },
  { term: "Armor" },
  { term: "Armor of God" },
  { term: "Ascension" },
  { term: "Asherah" },
  { term: "Ashes" },
  { term: "Assembly" },
  { term: "Atonement" },
  { term: "Atonement Cover" },
  { term: "Avarice" },

  // B
  { term: "Babel" },
  { term: "Babylon" },
  { term: "Baptism" },
  { term: "Baptism of Fire" },
  { term: "Baptism of the Holy Spirit" },
  { term: "Barley" },
  { term: "Basket" },
  { term: "Beast" },
  { term: "Beatitude" },
  { term: "Beelzebub" },
  { term: "Belial" },
  { term: "Benediction" },
  { term: "Betrayal" },
  { term: "Birthright" },
  { term: "Bishop" },
  { term: "Blasphemy" },
  { term: "Blessing" },
  { term: "Blood" },
  { term: "Blood of the Covenant" },
  { term: "Boaz" },
  { term: "Born Again" },
  { term: "Bread" },
  { term: "Bread of Life" },
  { term: "Bread of the Presence" },
  { term: "Breastplate" },
  { term: "Bride" },
  { term: "Bridegroom" },
  { term: "Burial" },
  { term: "Burnt Offering" },
  { term: "Byword" },

  // C
  { term: "Calling" },
  { term: "Camel" },
  { term: "Canaanite" },
  { term: "Candlestick" },
  { term: "Censer" },
  { term: "Census" },
  { term: "Centurion" },
  { term: "Chaff" },
  { term: "Chalice" },
  { term: "Chariot" },
  { term: "Chastisement" },
  { term: "Cherub" },
  { term: "Cherubim" },
  { term: "Chief Priest" },
  { term: "Child" },
  { term: "Children of God" },
  { term: "Children of Israel" },
  { term: "Chosen One" },
  { term: "Christ" },
  { term: "Christian" },
  { term: "Church" },
  { term: "Circumcision" },
  { term: "City" },
  { term: "City of God" },
  { term: "Cleansing" },
  { term: "Cloud" },
  { term: "Cloud of Witnesses" },
  { term: "Cock" },
  { term: "Commandment" },
  { term: "Compassion" },
  { term: "Confession" },
  { term: "Consecration" },
  { term: "Consolation" },
  { term: "Consummation" },
  { term: "Corban" },
  { term: "Cornerstone" },
  { term: "Corruption" },
  { term: "Covenant" },
  { term: "Covenant of Salt" },
  { term: "Covetousness" },
  { term: "Creation" },
  { term: "Creator" },
  { term: "Crown" },
  { term: "Crown of Life" },
  { term: "Crown of Thorns" },
  { term: "Crucifixion" },
  { term: "Cubit" },
  { term: "Cult" },
  { term: "Cup" },
  { term: "Cup of Blessing" },
  { term: "Cup of Wrath" },
  { term: "Curse" },
  { term: "Cymbal" },

  // D
  { term: "Daily Bread" },
  { term: "Darkness" },
  { term: "David" },
  { term: "Day of Atonement" },
  { term: "Day of Judgment" },
  { term: "Day of the Lord" },
  { term: "Death" },
  { term: "Debt" },
  { term: "Decalogue" },
  { term: "Decree" },
  { term: "Defilement" },
  { term: "Deliverance" },
  { term: "Deliverer" },
  { term: "Demon" },
  { term: "Denarius" },
  { term: "Depravity" },
  { term: "Desert" },
  { term: "Desolation" },
  { term: "Devil" },
  { term: "Diaspora" },
  { term: "Disciple" },
  { term: "Discipline" },
  { term: "Dispersion" },
  { term: "Divination" },
  { term: "Divine" },
  { term: "Doctrine" },
  { term: "Door" },
  { term: "Dove" },
  { term: "Dragon" },
  { term: "Dross" },
  { term: "Dust" },

  // E
  { term: "Eagle" },
  { term: "Earth" },
  { term: "Easter" },
  { term: "Eden" },
  { term: "Elder" },
  { term: "Election" },
  { term: "Elect" },
  { term: "Emmanuel" },
  { term: "End Times" },
  { term: "Enemy" },
  { term: "Enmity" },
  { term: "Epistle" },
  { term: "Eternal Life" },
  { term: "Eternity" },
  { term: "Eunuch" },
  { term: "Evangelist" },
  { term: "Evil" },
  { term: "Evil One" },
  { term: "Exaltation" },
  { term: "Exile" },
  { term: "Exodus" },
  { term: "Expiation" },
  { term: "Eye" },
  { term: "Eye for an Eye" },

  // F
  { term: "Faith" },
  { term: "Faithful" },
  { term: "Fall" },
  { term: "False Prophet" },
  { term: "Famine" },
  { term: "Fast" },
  { term: "Fasting" },
  { term: "Father" },
  { term: "Father in Heaven" },
  { term: "Fear" },
  { term: "Fear of the Lord" },
  { term: "Feast" },
  { term: "Feast of Booths" },
  { term: "Feast of Dedication" },
  { term: "Feast of Firstfruits" },
  { term: "Feast of Tabernacles" },
  { term: "Feast of Trumpets" },
  { term: "Feast of Unleavened Bread" },
  { term: "Feast of Weeks" },
  { term: "Fellowship" },
  { term: "Field" },
  { term: "Fig" },
  { term: "Fig Tree" },
  { term: "Fire" },
  { term: "Firstborn" },
  { term: "Firstfruits" },
  { term: "Fish" },
  { term: "Flesh" },
  { term: "Flood" },
  { term: "Flour" },
  { term: "Flute" },
  { term: "Fool" },
  { term: "Footstool" },
  { term: "Forbidden Fruit" },
  { term: "Foreknowledge" },
  { term: "Foreordain" },
  { term: "Forgiveness" },
  { term: "Foundation" },
  { term: "Fountain" },
  { term: "Fowler" },
  { term: "Fox" },
  { term: "Frankincense" },
  { term: "Freedom" },
  { term: "Friend" },
  { term: "Fruit" },
  { term: "Fruit of the Spirit" },
  { term: "Furnace" },

  // G
  { term: "Garden" },
  { term: "Garment" },
  { term: "Gate" },
  { term: "Gates of Hell" },
  { term: "Genealogy" },
  { term: "Generation" },
  { term: "Gentile" },
  { term: "Gethsemane" },
  { term: "Gifts of the Spirit" },
  { term: "Girdle" },
  { term: "Glory" },
  { term: "Glory of God" },
  { term: "Goat" },
  { term: "God" },
  { term: "God the Father" },
  { term: "Godhead" },
  { term: "Gog and Magog" },
  { term: "Gold" },
  { term: "Golgotha" },
  { term: "Gomorrah" },
  { term: "Gospel" },
  { term: "Grace" },
  { term: "Grain" },
  { term: "Grain Offering" },
  { term: "Grave" },
  { term: "Great Commission" },
  { term: "Great White Throne" },
  { term: "Greed" },
  { term: "Guilt" },
  { term: "Guilt Offering" },

  // H
  { term: "Hades" },
  { term: "Hallelujah" },
  { term: "Hallel" },
  { term: "Hand" },
  { term: "Harlot" },
  { term: "Harvest" },
  { term: "Head" },
  { term: "Heal" },
  { term: "Healing" },
  { term: "Heart" },
  { term: "Heaven" },
  { term: "Heavenly" },
  { term: "Hebrew" },
  { term: "Hell" },
  { term: "Hellenist" },
  { term: "Heresy" },
  { term: "Herod" },
  { term: "High Place" },
  { term: "High Priest" },
  { term: "Hinnom" },
  { term: "Hireling" },
  { term: "Holiness" },
  { term: "Holy" },
  { term: "Holy of Holies" },
  { term: "Holy One" },
  { term: "Holy Place" },
  { term: "Holy Spirit" },
  { term: "Honey" },
  { term: "Horn" },
  { term: "Horse" },
  { term: "Hosanna" },
  { term: "Host" },
  { term: "Host of Heaven" },
  { term: "House" },
  { term: "House of God" },
  { term: "House of Israel" },
  { term: "Humble" },
  { term: "Humility" },
  { term: "Husband" },
  { term: "Hymn" },

  // I
  { term: "Idol" },
  { term: "Idolatry" },
  { term: "Image" },
  { term: "Image of God" },
  { term: "Immanuel" },
  { term: "Immortality" },
  { term: "Incarnation" },
  { term: "Incense" },
  { term: "Inheritance" },
  { term: "Iniquity" },
  { term: "Inn" },
  { term: "Inspiration" },
  { term: "Intercession" },
  { term: "Iron" },
  { term: "Israel" },
  { term: "Israelite" },
  { term: "Issachar" },

  // J
  { term: "Jacob" },
  { term: "Jachin" },
  { term: "Jail" },
  { term: "Jailer" },
  { term: "Jasper" },
  { term: "Jealousy" },
  { term: "Jerusalem" },
  { term: "Jew" },
  { term: "Jewish" },
  { term: "Jezebel" },
  { term: "Job" },
  { term: "John" },
  { term: "Jordan" },
  { term: "Joseph" },
  { term: "Joy" },
  { term: "Jubilee" },
  { term: "Judge" },
  { term: "Judgment" },
  { term: "Judgment Seat" },
  { term: "Just" },
  { term: "Justice" },
  { term: "Justification" },
  { term: "Justify" },

  // K
  { term: "Kenite" },
  { term: "Key" },
  { term: "Keys of the Kingdom" },
  { term: "Kid" },
  { term: "Kill" },
  { term: "Kindness" },
  { term: "King" },
  { term: "Kingdom" },
  { term: "Kingdom of God" },
  { term: "Kingdom of Heaven" },
  { term: "Kingship" },
  { term: "Kinsman" },
  { term: "Kinsman-Redeemer" },
  { term: "Kiss" },
  { term: "Kneel" },
  { term: "Knowledge" },

  // L
  { term: "Lamb" },
  { term: "Lamb of God" },
  { term: "Lamp" },
  { term: "Lampstand" },
  { term: "Land" },
  { term: "Land of Promise" },
  { term: "Last Days" },
  { term: "Last Supper" },
  { term: "Law" },
  { term: "Law of Moses" },
  { term: "Lawyer" },
  { term: "Laying on of Hands" },
  { term: "Lazarus" },
  { term: "Leaven" },
  { term: "Legion" },
  { term: "Leprosy" },
  { term: "Leper" },
  { term: "Leviathan" },
  { term: "Levite" },
  { term: "Leviticus" },
  { term: "Liberty" },
  { term: "Life" },
  { term: "Light" },
  { term: "Light of the World" },
  { term: "Lilies" },
  { term: "Lion" },
  { term: "Lion of Judah" },
  { term: "Living Water" },
  { term: "Loaf" },
  { term: "Lord" },
  { term: "Lord of Hosts" },
  { term: "Lord's Day" },
  { term: "Lord's Prayer" },
  { term: "Lord's Supper" },
  { term: "Love" },
  { term: "Lust" },
  { term: "Lyre" },

  // M
  { term: "Magi" },
  { term: "Magic" },
  { term: "Magician" },
  { term: "Mammon" },
  { term: "Man" },
  { term: "Manna" },
  { term: "Mantle" },
  { term: "Marriage" },
  { term: "Martyr" },
  { term: "Master" },
  { term: "Measure" },
  { term: "Mediator" },
  { term: "Meditation" },
  { term: "Meek" },
  { term: "Meekness" },
  { term: "Melchizedek" },
  { term: "Memorial" },
  { term: "Mercy" },
  { term: "Mercy Seat" },
  { term: "Messenger" },
  { term: "Messiah" },
  { term: "Millennium" },
  { term: "Millstone" },
  { term: "Miracle" },
  { term: "Miraculous" },
  { term: "Miriam" },
  { term: "Mist" },
  { term: "Mite" },
  { term: "Molech" },
  { term: "Money" },
  { term: "Money Changer" },
  { term: "Month" },
  { term: "Moon" },
  { term: "Moral" },
  { term: "Mortal" },
  { term: "Moses" },
  { term: "Most High" },
  { term: "Mother" },
  { term: "Mount" },
  { term: "Mourn" },
  { term: "Mourning" },
  { term: "Mouth" },
  { term: "Mystery" },

  // N
  { term: "Nail" },
  { term: "Name" },
  { term: "Nation" },
  { term: "Nativity" },
  { term: "Nazarene" },
  { term: "Nazirite" },
  { term: "Neighbor" },
  { term: "Net" },
  { term: "New Birth" },
  { term: "New Covenant" },
  { term: "New Creation" },
  { term: "New Jerusalem" },
  { term: "New Moon" },
  { term: "New Testament" },
  { term: "Night" },
  { term: "Noah" },
  { term: "Noise" },
  { term: "Number" },

  // O
  { term: "Oath" },
  { term: "Obedience" },
  { term: "Obey" },
  { term: "Offering" },
  { term: "Oil" },
  { term: "Old Covenant" },
  { term: "Old Testament" },
  { term: "Olive" },
  { term: "Olive Branch" },
  { term: "Olive Tree" },
  { term: "Only Begotten" },
  { term: "Oracle" },
  { term: "Ordination" },
  { term: "Ox" },

  // P
  { term: "Palm" },
  { term: "Palm Branch" },
  { term: "Parable" },
  { term: "Paradise" },
  { term: "Parousia" },
  { term: "Passion" },
  { term: "Passover" },
  { term: "Pastor" },
  { term: "Path" },
  { term: "Patience" },
  { term: "Patriarch" },
  { term: "Peace" },
  { term: "Peace Offering" },
  { term: "Pearl" },
  { term: "Penalty" },
  { term: "Pentecost" },
  { term: "People" },
  { term: "People of God" },
  { term: "Perdition" },
  { term: "Perfect" },
  { term: "Perfection" },
  { term: "Persecution" },
  { term: "Perseverance" },
  { term: "Pharisee" },
  { term: "Phylactery" },
  { term: "Pillar" },
  { term: "Pit" },
  { term: "Plague" },
  { term: "Plant" },
  { term: "Pleasure" },
  { term: "Pledge" },
  { term: "Plow" },
  { term: "Poor" },
  { term: "Poverty" },
  { term: "Power" },
  { term: "Praise" },
  { term: "Prayer" },
  { term: "Preach" },
  { term: "Preacher" },
  { term: "Preaching" },
  { term: "Predestination" },
  { term: "Presence" },
  { term: "Presence of God" },
  { term: "Priest" },
  { term: "Priesthood" },
  { term: "Prince" },
  { term: "Prince of Peace" },
  { term: "Prison" },
  { term: "Proclamation" },
  { term: "Promise" },
  { term: "Promised Land" },
  { term: "Prophesy" },
  { term: "Prophecy" },
  { term: "Prophet" },
  { term: "Propitiation" },
  { term: "Proselyte" },
  { term: "Proverb" },
  { term: "Providence" },
  { term: "Psalter" },
  { term: "Publican" },
  { term: "Punishment" },
  { term: "Purification" },
  { term: "Purify" },
  { term: "Purity" },
  { term: "Purpose" },

  // Q
  { term: "Quail" },
  { term: "Queen" },
  { term: "Quench" },
  { term: "Quiver" },

  // R
  { term: "Rabbi" },
  { term: "Rain" },
  { term: "Rainbow" },
  { term: "Ransom" },
  { term: "Rapture" },
  { term: "Raven" },
  { term: "Reap" },
  { term: "Reaping" },
  { term: "Rebellion" },
  { term: "Rebirth" },
  { term: "Reconciliation" },
  { term: "Redeem" },
  { term: "Redeemer" },
  { term: "Redemption" },
  { term: "Refiner" },
  { term: "Refining" },
  { term: "Refuge" },
  { term: "Regeneration" },
  { term: "Reign" },
  { term: "Rejoice" },
  { term: "Remnant" },
  { term: "Repent" },
  { term: "Repentance" },
  { term: "Reproach" },
  { term: "Reprobate" },
  { term: "Rescue" },
  { term: "Resurrection" },
  { term: "Resurrection of the Dead" },
  { term: "Retribution" },
  { term: "Revelation" },
  { term: "Revenge" },
  { term: "Reward" },
  { term: "Rich" },
  { term: "Riches" },
  { term: "Right Hand" },
  { term: "Righteous" },
  { term: "Righteousness" },
  { term: "River" },
  { term: "Rock" },
  { term: "Rod" },
  { term: "Rope" },
  { term: "Ruler" },

  // S
  { term: "Sabbath" },
  { term: "Sabbath Day" },
  { term: "Sackcloth" },
  { term: "Sacrament" },
  { term: "Sacred" },
  { term: "Sacrifice" },
  { term: "Sadducee" },
  { term: "Saint" },
  { term: "Salt" },
  { term: "Salt of the Earth" },
  { term: "Salvation" },
  { term: "Sanctification" },
  { term: "Sanctify" },
  { term: "Sanctuary" },
  { term: "Sand" },
  { term: "Satan" },
  { term: "Satisfaction" },
  { term: "Savior" },
  { term: "Scapegoat" },
  { term: "Scepter" },
  { term: "Scribe" },
  { term: "Scripture" },
  { term: "Scroll" },
  { term: "Sea" },
  { term: "Seal" },
  { term: "Second Coming" },
  { term: "Seed" },
  { term: "Seed of Abraham" },
  { term: "Self-Control" },
  { term: "Serpent" },
  { term: "Servant" },
  { term: "Servant of the Lord" },
  { term: "Service" },
  { term: "Seven" },
  { term: "Seventy" },
  { term: "Shame" },
  { term: "Sheep" },
  { term: "Sheepfold" },
  { term: "Shekel" },
  { term: "Shekinah" },
  { term: "Sheol" },
  { term: "Shepherd" },
  { term: "Shield" },
  { term: "Shiloh" },
  { term: "Shofar" },
  { term: "Sickle" },
  { term: "Sick" },
  { term: "Sickness" },
  { term: "Sign" },
  { term: "Silence" },
  { term: "Silver" },
  { term: "Sin" },
  { term: "Sin Offering" },
  { term: "Sinai" },
  { term: "Sinner" },
  { term: "Sister" },
  { term: "Sit" },
  { term: "Six" },
  { term: "Skeleton" },
  { term: "Skin" },
  { term: "Slave" },
  { term: "Slavery" },
  { term: "Sleep" },
  { term: "Sloth" },
  { term: "Snake" },
  { term: "Sodom" },
  { term: "Son" },
  { term: "Son of David" },
  { term: "Son of God" },
  { term: "Son of Man" },
  { term: "Song" },
  { term: "Soul" },
  { term: "Sower" },
  { term: "Sowing" },
  { term: "Spear" },
  { term: "Spirit" },
  { term: "Spirit of God" },
  { term: "Spiritual" },
  { term: "Spoil" },
  { term: "Staff" },
  { term: "Star" },
  { term: "Star of Bethlehem" },
  { term: "Stature" },
  { term: "Steadfast" },
  { term: "Steward" },
  { term: "Stewardship" },
  { term: "Stick" },
  { term: "Stone" },
  { term: "Stoning" },
  { term: "Storehouse" },
  { term: "Storm" },
  { term: "Strait" },
  { term: "Stranger" },
  { term: "Strength" },
  { term: "Strike" },
  { term: "Stumble" },
  { term: "Substitution" },
  { term: "Suffer" },
  { term: "Suffering" },
  { term: "Suffering Servant" },
  { term: "Sun" },
  { term: "Sun of Righteousness" },
  { term: "Supper" },
  { term: "Swine" },
  { term: "Sword" },
  { term: "Sword of the Spirit" },
  { term: "Synagogue" },
  { term: "Synod" },

  // T
  { term: "Tabernacle" },
  { term: "Table" },
  { term: "Table of Showbread" },
  { term: "Talent" },
  { term: "Tares" },
  { term: "Tassel" },
  { term: "Tax" },
  { term: "Tax Collector" },
  { term: "Teacher" },
  { term: "Teaching" },
  { term: "Tear" },
  { term: "Temple" },
  { term: "Temple Worship" },
  { term: "Temptation" },
  { term: "Tempt" },
  { term: "Tempter" },
  { term: "Ten" },
  { term: "Ten Commandments" },
  { term: "Tent" },
  { term: "Tent of Meeting" },
  { term: "Test" },
  { term: "Testament" },
  { term: "Testify" },
  { term: "Testimony" },
  { term: "Thief" },
  { term: "Thirst" },
  { term: "Thorn" },
  { term: "Thousand" },
  { term: "Threshing" },
  { term: "Threshing Floor" },
  { term: "Throne" },
  { term: "Thunder" },
  { term: "Time" },
  { term: "Times" },
  { term: "Tithe" },
  { term: "Tithing" },
  { term: "Tomb" },
  { term: "Tongue" },
  { term: "Torah" },
  { term: "Tower" },
  { term: "Tower of Babel" },
  { term: "Tradition" },
  { term: "Transfiguration" },
  { term: "Transgression" },
  { term: "Trap" },
  { term: "Treasure" },
  { term: "Tree" },
  { term: "Tree of Life" },
  { term: "Tree of Knowledge" },
  { term: "Trespass" },
  { term: "Trial" },
  { term: "Tribe" },
  { term: "Tribulation" },
  { term: "Trinity" },
  { term: "Triumph" },
  { term: "Trumpet" },
  { term: "Trust" },
  { term: "Truth" },
  { term: "Twelve" },
  { term: "Two" },

  // U
  { term: "Unbelief" },
  { term: "Unclean" },
  { term: "Unction" },
  { term: "Understanding" },
  { term: "Unleavened Bread" },
  { term: "Unrighteous" },
  { term: "Urim and Thummim" },

  // V
  { term: "Vail" },
  { term: "Valley" },
  { term: "Veil" },
  { term: "Vengeance" },
  { term: "Vessel" },
  { term: "Vesture" },
  { term: "Vicar" },
  { term: "Victory" },
  { term: "Vine" },
  { term: "Vineyard" },
  { term: "Vineyard of the Lord" },
  { term: "Vineyard Owner" },
  { term: "Violence" },
  { term: "Virgin" },
  { term: "Virgin Birth" },
  { term: "Vision" },
  { term: "Voice" },
  { term: "Vow" },
  { term: "Vulture" },

  // W
  { term: "Wages" },
  { term: "Wail" },
  { term: "Wait" },
  { term: "Walk" },
  { term: "Wall" },
  { term: "Wander" },
  { term: "War" },
  { term: "Wash" },
  { term: "Washing" },
  { term: "Watch" },
  { term: "Watchman" },
  { term: "Water" },
  { term: "Water of Life" },
  { term: "Wave Offering" },
  { term: "Way" },
  { term: "Wealth" },
  { term: "Weapon" },
  { term: "Weary" },
  { term: "Wedding" },
  { term: "Wedding Feast" },
  { term: "Weed" },
  { term: "Week" },
  { term: "Weep" },
  { term: "Weeping" },
  { term: "Well" },
  { term: "Wheat" },
  { term: "Wheel" },
  { term: "Whip" },
  { term: "Whisper" },
  { term: "White" },
  { term: "White Throne" },
  { term: "Wicked" },
  { term: "Wickedness" },
  { term: "Widow" },
  { term: "Wife" },
  { term: "Wilderness" },
  { term: "Wind" },
  { term: "Wine" },
  { term: "Winepress" },
  { term: "Wing" },
  { term: "Winnow" },
  { term: "Winnowing Fork" },
  { term: "Wisdom" },
  { term: "Wise" },
  { term: "Wise Men" },
  { term: "Witness" },
  { term: "Woe" },
  { term: "Woman" },
  { term: "Wonder" },
  { term: "Wood" },
  { term: "Word" },
  { term: "Word of God" },
  { term: "Work" },
  { term: "Works" },
  { term: "World" },
  { term: "Worm" },
  { term: "Wormwood" },
  { term: "Worship" },
  { term: "Worth" },
  { term: "Worthy" },
  { term: "Wound" },
  { term: "Wrath" },
  { term: "Wrestle" },
  { term: "Write" },
  { term: "Writing" },

  // Y
  { term: "Year" },
  { term: "Year of Jubilee" },
  { term: "Yoke" },
  { term: "Young" },
  { term: "Youth" },

  // Z
  { term: "Zeal" },
  { term: "Zealot" },
  { term: "Zion" },
];

