/**
 * Comprehensive list of biblical keywords and phrases
 * 
 * Each keyword appears once.
 * All keywords appear in the canonical Old or New Testament or are historically/culturally necessary to understand Scripture.
 * Alphabetized by term.
 * Merged from current list and new unified 3-layer list.
 */

export type BibleKeywordEntry = {
  term: string;
};

export const BIBLE_KEYWORDS_LIST: BibleKeywordEntry[] = [
  { term: "Abomination" },
  { term: "Abomination of Desolation" },
  { term: "Abraham's Bosom" },
  { term: "Accuser" },
  { term: "Adoption" },
  { term: "Adoption Language" },
  { term: "Adultery" },
  { term: "Advocate" },
  { term: "Affliction" },
  { term: "Age to Come" },
  { term: "Alabaster" },
  { term: "Alms" },
  { term: "Altar" },
  { term: "Amen" },
  { term: "Anathema" },
  { term: "Ancient of Days" },
  { term: "Angel" },
  { term: "Angel of the Lord" },
  { term: "Anointed King" },
  { term: "Anointing" },
  { term: "Anointing Oil" },
  { term: "Antichrist" },
  { term: "Apocalyptic Language" },
  { term: "Apostasy" },
  { term: "Apostle" },
  { term: "Ark" },
  { term: "Ark of the Covenant" },
  { term: "Armor" },
  { term: "Armor Bearer" },
  { term: "Armor of God" },
  { term: "Ascension" },
  { term: "Asherah" },
  { term: "Ashes" },
  { term: "Assembly" },
  { term: "Astrologer" },
  { term: "Atonement" },
  { term: "Atonement Cover" },
  { term: "Avenger of Blood" },
  { term: "Babel" },
  { term: "Babylon" },
  { term: "Balm" },
  { term: "Baptism" },
  { term: "Baptism of Fire" },
  { term: "Baptism of the Holy Spirit" },
  { term: "Barley" },
  { term: "Battle Line" },
  { term: "Battering Ram" },
  { term: "Beast" },
  { term: "Beatitude" },
  { term: "Beelzebub" },
  { term: "Behemoth" },
  { term: "Belial" },
  { term: "Benediction" },
  { term: "Betrayal" },
  { term: "Bill of Divorce" },
  { term: "Birthright" },
  { term: "Bishop" },
  { term: "Bird of Prey" },
  { term: "Blasphemy" },
  { term: "Blessing" },
  { term: "Blood" },
  { term: "Blood Avenger" },
  { term: "Blood of the Covenant" },
  { term: "Blood Ritual" },
  { term: "Bondservant" },
  { term: "Born Again" },
  { term: "Boundary Stone" },
  { term: "Bow Down" },
  { term: "Bread Breaking" },
  { term: "Bread of Life" },
  { term: "Bread of the Presence" },
  { term: "Breastplate" },
  { term: "Bride" },
  { term: "Bridegroom" },
  { term: "Bronze Altar" },
  { term: "Bronze Serpent" },
  { term: "Burden Bearer" },
  { term: "Burdens" },
  { term: "Burnt Offering" },
  { term: "Calling" },
  { term: "Camel Driver" },
  { term: "Canaanite" },
  { term: "Candlestick" },
  { term: "Casting Lots" },
  { term: "Censer" },
  { term: "Census" },
  { term: "Centurion" },
  { term: "Chaff" },
  { term: "Chalice" },
  { term: "Charms" },
  { term: "Chariot" },
  { term: "Chariot Corps" },
  { term: "Chasten" },
  { term: "Chastisement" },
  { term: "Cherub" },
  { term: "Cherubim" },
  { term: "Chief Baker" },
  { term: "Chief Cupbearer" },
  { term: "Chief Priest" },
  { term: "Children of God" },
  { term: "Children of Israel" },
  { term: "Chosen One" },
  { term: "Christ" },
  { term: "Church" },
  { term: "Circumcision" },
  { term: "Citadel" },
  { term: "City Fortifications" },
  { term: "City of God" },
  { term: "Cleansing" },
  { term: "Cloud" },
  { term: "Cloud of Witnesses" },
  { term: "Clothing as Status" },
  { term: "Commandment" },
  { term: "Commander of Fifties" },
  { term: "Commander of Thousands" },
  { term: "Confession" },
  { term: "Consecration" },
  { term: "Contend" },
  { term: "Cornerstone" },
  { term: "Corvée Labor" },
  { term: "Cosmic Imagery" },
  { term: "Cosmic Rebellion" },
  { term: "Covenant" },
  { term: "Covenant Blessing" },
  { term: "Covenant Curse" },
  { term: "Covenant Renewal" },
  { term: "Cover Shame" },
  { term: "Creation" },
  { term: "Creator" },
  { term: "Crown" },
  { term: "Crown of Life" },
  { term: "Crown of Thorns" },
  { term: "Crucifixion" },
  { term: "Cubit" },
  { term: "Daily Bread" },
  { term: "Daily Wage" },
  { term: "Day of Atonement" },
  { term: "Day of Judgment" },
  { term: "Day of the Lord" },
  { term: "Day of the Lord Pattern" },
  { term: "Debt" },
  { term: "Debt Forgiveness" },
  { term: "Debtor Prison" },
  { term: "Decalogue" },
  { term: "Decree" },
  { term: "Deed of Purchase" },
  { term: "Defilement" },
  { term: "Deliver" },
  { term: "Deliverance" },
  { term: "Deliverer" },
  { term: "Demon" },
  { term: "Denarius" },
  { term: "Denarius Wage" },
  { term: "Desolation" },
  { term: "Despise" },
  { term: "Detestable" },
  { term: "Devil" },
  { term: "Diaspora" },
  { term: "Disciple" },
  { term: "Divination" },
  { term: "Divination Practices" },
  { term: "Doctrine" },
  { term: "Double Portion" },
  { term: "Dream Interpreter" },
  { term: "Dry Cistern" },
  { term: "Dust on Head" },
  { term: "Economic Oppression" },
  { term: "Eden" },
  { term: "Elder" },
  { term: "Elders at the Gate" },
  { term: "Elect" },
  { term: "Election" },
  { term: "Emmanuel" },
  { term: "Enchantments" },
  { term: "End Times" },
  { term: "Ephod" },
  { term: "Epistle" },
  { term: "Eternal Life" },
  { term: "Eunuch" },
  { term: "Evangelist" },
  { term: "Evil One" },
  { term: "Exile" },
  { term: "Exile Motif" },
  { term: "Exodus" },
  { term: "Expiation" },
  { term: "Eye for an Eye" },
  { term: "Faith" },
  { term: "Faithfulness vs Faith" },
  { term: "Fall on One's Face" },
  { term: "False Prophet" },
  { term: "Famine" },
  { term: "Fasting" },
  { term: "Fear of the Lord" },
  { term: "Feast of Booths" },
  { term: "Feast of Dedication" },
  { term: "Feast of Firstfruits" },
  { term: "Feast of Tabernacles" },
  { term: "Feast of Trumpets" },
  { term: "Feast of Unleavened Bread" },
  { term: "Feast of Weeks" },
  { term: "Firstborn" },
  { term: "Firstborn Portion" },
  { term: "Firstfruits" },
  { term: "Flock Ownership" },
  { term: "Foot Washing" },
  { term: "Forbidden Fruit" },
  { term: "Forced Labor" },
  { term: "Foreknowledge" },
  { term: "Forgiveness" },
  { term: "Foundation" },
  { term: "Frankincense" },
  { term: "Fruit of the Spirit" },
  { term: "Gate Judgment" },
  { term: "Gatekeeper" },
  { term: "Genealogy" },
  { term: "Gentile" },
  { term: "Gethsemane" },
  { term: "Gifts of the Spirit" },
  { term: "Glorification" },
  { term: "Glory" },
  { term: "Glory of God" },
  { term: "Gog and Magog" },
  { term: "Gold" },
  { term: "Golgotha" },
  { term: "Gospel" },
  { term: "Grace" },
  { term: "Grain Offering" },
  { term: "Granary" },
  { term: "Great Commission" },
  { term: "Great White Throne" },
  { term: "Guest Right" },
  { term: "Hades" },
  { term: "Hallelujah" },
  { term: "Handmaid" },
  { term: "Harlot" },
  { term: "Harvest" },
  { term: "Harvest Share" },
  { term: "Hardhearted" },
  { term: "Heart Circumcision" },
  { term: "Heaven" },
  { term: "Hell" },
  { term: "Heresy" },
  { term: "Hide the Face" },
  { term: "High Priest" },
  { term: "Holy of Holies" },
  { term: "Holy Spirit" },
  { term: "Honor and Shame Culture" },
  { term: "Hosanna" },
  { term: "Host of Heaven" },
  { term: "Hospitality Code" },
  { term: "House of God" },
  { term: "Household Manager" },
  { term: "Household Servant" },
  { term: "Idol" },
  { term: "Idolatry" },
  { term: "Image of God" },
  { term: "Incarnation" },
  { term: "Incense" },
  { term: "Inheritance" },
  { term: "Inheritance Allotment" },
  { term: "Inheritance Promise" },
  { term: "Inheritance Rights" },
  { term: "Iniquity" },
  { term: "Intercession" },
  { term: "Interest Usury" },
  { term: "Iron Rod" },
  { term: "Israelite" },
  { term: "Justification" },
  { term: "Justification Language" },
  { term: "Jubilee" },
  { term: "Jubilee Release" },
  { term: "Judge" },
  { term: "Judgment" },
  { term: "Judgment Seat" },
  { term: "Key" },
  { term: "Keys of the Kingdom" },
  { term: "Kingdom" },
  { term: "Kingdom Authority" },
  { term: "Kingdom of God" },
  { term: "Kingdom of Heaven" },
  { term: "Kinsman" },
  { term: "Kinsman-Redeemer" },
  { term: "Lamb" },
  { term: "Lamb of God" },
  { term: "Lampstand" },
  { term: "Land Allotment" },
  { term: "Last Days" },
  { term: "Last Supper" },
  { term: "Laid Waste" },
  { term: "Lambing" },
  { term: "Law of Moses" },
  { term: "Leaven" },
  { term: "Legion" },
  { term: "Leper" },
  { term: "Leprosy" },
  { term: "Leviathan" },
  { term: "Levite" },
  { term: "Legal Scroll" },
  { term: "Light of the World" },
  { term: "Lift the Horn" },
  { term: "Lion of Judah" },
  { term: "Lion's Den" },
  { term: "Living Water" },
  { term: "Livestock" },
  { term: "Locust Swarm" },
  { term: "Loathe" },
  { term: "Lord of Hosts" },
  { term: "Magi" },
  { term: "Magicians of Egypt" },
  { term: "Mammon" },
  { term: "Manna" },
  { term: "Measuring Rod" },
  { term: "Mediator" },
  { term: "Medium" },
  { term: "Melchizedek" },
  { term: "Mercy Seat" },
  { term: "Messenger Herald" },
  { term: "Messiah" },
  { term: "Messianic Age" },
  { term: "Messianic Expectation" },
  { term: "Millennium" },
  { term: "Millstone" },
  { term: "Miracle" },
  { term: "Money Changer" },
  { term: "Most Holy Place" },
  { term: "Myrrh" },
  { term: "Nazirite" },
  { term: "Necromancer" },
  { term: "New Birth" },
  { term: "New Covenant" },
  { term: "New Creation" },
  { term: "New Exodus Pattern" },
  { term: "New Jerusalem" },
  { term: "New Obedience" },
  { term: "Nurse" },
  { term: "Oath" },
  { term: "Oath Ceremony" },
  { term: "Oath Token" },
  { term: "Offering" },
  { term: "Old Covenant" },
  { term: "Olive Branch" },
  { term: "Omens" },
  { term: "Only Begotten" },
  { term: "Oppress" },
  { term: "Ordination" },
  { term: "Outer Court" },
  { term: "Overseer" },
  { term: "Parable" },
  { term: "Paradise" },
  { term: "Parousia" },
  { term: "Passover" },
  { term: "Pentecost" },
  { term: "Perseverance of the Saints" },
  { term: "Pharisee" },
  { term: "Phylacteries" },
  { term: "Pillar" },
  { term: "Pit" },
  { term: "Plague" },
  { term: "Pledge Cloak" },
  { term: "Plowshare" },
  { term: "Plunder" },
  { term: "Pour Out Wrath" },
  { term: "Power" },
  { term: "Predestination" },
  { term: "Presence of God" },
  { term: "Price of a Slave" },
  { term: "Priesthood" },
  { term: "Priestly Garments" },
  { term: "Prince of Peace" },
  { term: "Prophecy" },
  { term: "Prophet" },
  { term: "Prophetic Hyperbole" },
  { term: "Prophetic Sign Act" },
  { term: "Propitiation" },
  { term: "Public Rebuke" },
  { term: "Ransom" },
  { term: "Ransom Payment" },
  { term: "Ravaged" },
  { term: "Rebellious" },
  { term: "Rebuke" },
  { term: "Redeem" },
  { term: "Redemption" },
  { term: "Redemption Clause" },
  { term: "Redemption Document" },
  { term: "Redemption Price" },
  { term: "Regathering" },
  { term: "Regeneration" },
  { term: "Remember Covenant" },
  { term: "Remnant" },
  { term: "Remnant Theology" },
  { term: "Repentance" },
  { term: "Resurrection" },
  { term: "Return from Exile" },
  { term: "Righteous Status" },
  { term: "Righteousness" },
  { term: "Rod" },
  { term: "Royal Advisor" },
  { term: "Royal Garments" },
  { term: "Royal Messiah" },
  { term: "Rulers of This Age" },
  { term: "Sabbath" },
  { term: "Sacred Lot" },
  { term: "Sacrifice" },
  { term: "Sadducee" },
  { term: "Sackcloth and Ashes" },
  { term: "Salvation" },
  { term: "Sanctification" },
  { term: "Scapegoat" },
  { term: "Scattering" },
  { term: "Scepter" },
  { term: "Scepter Rod" },
  { term: "Scourge" },
  { term: "Scripture" },
  { term: "Seal" },
  { term: "Seal Impression" },
  { term: "Sealing of the Spirit" },
  { term: "Second Coming" },
  { term: "Serpent" },
  { term: "Shed Blood" },
  { term: "Sheepfold Gate" },
  { term: "Shekinah" },
  { term: "Sheol" },
  { term: "Shepherd" },
  { term: "Shepherd King" },
  { term: "Shepherd's Rod" },
  { term: "Shield Wall" },
  { term: "Signet Ring" },
  { term: "Silver" },
  { term: "Sin Offering" },
  { term: "Smite" },
  { term: "Smote" },
  { term: "Son of David" },
  { term: "Son of God" },
  { term: "Son of Man" },
  { term: "Sorcery" },
  { term: "Spells" },
  { term: "Spirit of God" },
  { term: "Spiritist" },
  { term: "Spoil of War" },
  { term: "Staff" },
  { term: "Staff of Authority" },
  { term: "Standard Bearer" },
  { term: "Steward" },
  { term: "Stiff-Necked" },
  { term: "Store City" },
  { term: "Striking" },
  { term: "Stronghold" },
  { term: "Strive" },
  { term: "Substitution" },
  { term: "Suffering Servant" },
  { term: "Sword of the Spirit" },
  { term: "Symbolic Action" },
  { term: "Symbolic Numbers" },
  { term: "Synagogue" },
  { term: "Tabernacle" },
  { term: "Table Fellowship" },
  { term: "Table of Showbread" },
  { term: "Talent" },
  { term: "Taskmaster" },
  { term: "Tax Collector" },
  { term: "Temple" },
  { term: "Temple Treasury" },
  { term: "Tent of Meeting" },
  { term: "Threshing Floor" },
  { term: "Threshing Ox" },
  { term: "Threshing Sledge" },
  { term: "Throne" },
  { term: "Tithe" },
  { term: "Tithe Storehouse" },
  { term: "Torah" },
  { term: "Torn Garments" },
  { term: "Tower of Babel" },
  { term: "Trade Goods" },
  { term: "Transfiguration" },
  { term: "Transgression" },
  { term: "Tribe" },
  { term: "Tribulation" },
  { term: "Trinity" },
  { term: "Trumpet" },
  { term: "Trumpet Signal" },
  { term: "Unclean" },
  { term: "Unleavened Bread" },
  { term: "Urim and Thummim" },
  { term: "Usury" },
  { term: "Veil" },
  { term: "Vineyard" },
  { term: "Virgin Birth" },
  { term: "Visit Iniquity" },
  { term: "Watchers" },
  { term: "Watchman" },
  { term: "Waterless Pit" },
  { term: "Wet Nurse" },
  { term: "Wilderness" },
  { term: "Wine" },
  { term: "Winepress" },
  { term: "Winepress Pit" },
  { term: "Winnowing Fork" },
  { term: "Wisdom" },
  { term: "Wise Men of the East" },
  { term: "Word of God" },
  { term: "Works of the Law" },
  { term: "Wrath" },
  { term: "Yahweh" },
  { term: "Year of Jubilee" },
  { term: "Yoke" },
  { term: "Yoke Bearer" },
  { term: "Zeal" },
  { term: "Zealot" },
  { term: "Zion" },
  // --- Additional WEB glossary and expanded keyword terms ---
  // WEB glossary
  { term: "Abaddon" },
  { term: "Abba" },
  { term: "Alpha" },
  { term: "Apollyon" },
  { term: "Armageddon" },
  { term: "Har mגדּdon" },
  { term: "Assarion" },
  { term: "Aureus" },
  { term: "Baptize" },
  { term: "Bath" },
  { term: "Batos" },
  { term: "Beelzebul" },
  { term: "Choenix" },
  { term: "Concubine" },
  { term: "Cor" },
  { term: "Corban" },
  { term: "Crucify" },
  { term: "Cummin" },
  { term: "Darnel" },
  { term: "Denarii" },
  { term: "Didrachma" },
  { term: "Distaff" },
  { term: "Drachma" },
  { term: "Ephah" },
  { term: "Gittith" },
  { term: "Goad" },
  { term: "Hin" },
  { term: "Homer" },
  { term: "Jehovah" },
  { term: "Kodrantes" },
  { term: "Lepta" },
  { term: "Mahalath" },
  { term: "Maschil" },
  { term: "Michtam" },
  { term: "Mina" },
  { term: "Praetorium" },
  { term: "Quadrans" },
  { term: "Rabbi" },
  { term: "Rhabboni" },
  { term: "Sata" },
  { term: "Shigionoth" },
  { term: "Stadion" },
  { term: "Stadia" },
  { term: "Stater" },
  { term: "Tartarus" },
  { term: "Teraphim" },
  { term: "Yah" },
  // Expanded keyword candidates (selection; many already present but deduped at runtime)
  { term: "Abstain" },
  { term: "Accountability" },
  { term: "Accursed" },
  { term: "Acquit" },
  { term: "Adversary" },
  { term: "Awe" },
  { term: "Baldness" },
  { term: "Basket" },
  { term: "Begotten" },
  { term: "Blameless" },
  { term: "Borne" },
  { term: "Calamity" },
  { term: "Calloused" },
  { term: "Captivity" },
  { term: "Carnal" },
  { term: "Chastening" },
  { term: "Chastity" },
  { term: "Cherished" },
  { term: "Clean Days" },
  { term: "Clean Thing" },
  { term: "Coals" },
  { term: "Consolation" },
  { term: "Contempt" },
  { term: "Contrite" },
  { term: "Convict" },
  { term: "Conviction" },
  { term: "Corruption" },
  { term: "Counsel" },
  { term: "Counselor" },
  { term: "Crimson" },
  { term: "Crossbeam" },
  { term: "Daemon" },
  { term: "Damnation" },
  { term: "Devotion" },
  { term: "Devout" },
  { term: "Discipline" },
  { term: "Disperse" },
  { term: "Doxology" },
  { term: "Dread" },
  { term: "Dust" },
  { term: "Earnest" },
  { term: "Endurance" },
  { term: "Enmity" },
  { term: "Envy" },
  { term: "Equity" },
  { term: "Error" },
  { term: "Eternal" },
  { term: "Exalt" },
  { term: "Exhort" },
  { term: "Goaded" },
  { term: "Grant" },
  { term: "Grieve" },
  { term: "Guilt" },
  { term: "Guilt Offering" },
  { term: "Hard Heart" },
  { term: "Headship" },
  { term: "Heathen" },
  { term: "Heavenly" },
  { term: "Heritage" },
  { term: "Hewn" },
  { term: "Holy Place" },
  { term: "Household" },
  { term: "Impart" },
  { term: "Impute" },
  { term: "Imputation" },
  { term: "Instruction" },
  { term: "Intercede" },
  { term: "Interpretation" },
  { term: "Jealousy" },
  { term: "Koinonia" },
  { term: "Lament" },
  { term: "Lawful" },
  { term: "Lawlessness" },
  { term: "Libation" },
  { term: "Living Waters" },
  { term: "Loins" },
  { term: "Lordship" },
  { term: "Lots" },
  { term: "Lowliness" },
  { term: "Lust" },
  { term: "Manifest" },
  { term: "Manifestation" },
  { term: "Martyr" },
  { term: "Merciful" },
  { term: "Ministry" },
  { term: "Mock" },
  { term: "Molten" },
  { term: "Mourn" },
  { term: "Mystery" },
  { term: "Nations" },
  { term: "Ordinance" },
  { term: "Orphan" },
  { term: "Perfect" },
  { term: "Perfection" },
  { term: "Perish" },
  { term: "Persecuted" },
  { term: "Persecution" },
  { term: "Pestilence" },
  { term: "Petition" },
  { term: "Piety" },
  { term: "Pollution" },
  { term: "Portion" },
  { term: "Profane" },
  { term: "Prosper" },
  { term: "Prostitute" },
  { term: "Prostitution" },
  { term: "Proverb" },
  { term: "Providence" },
  { term: "Purify" },
  { term: "Purity" },
  { term: "Put Away" },
  { term: "Quench" },
  { term: "Quickened" },
  { term: "Reconcile" },
  { term: "Reconciliation" },
  { term: "Refuge" },
  { term: "Rejoicing" },
  { term: "Reproof" },
  { term: "Revile" },
  { term: "Reward" },
  { term: "Robes" },
  { term: "Sacrificial System" },
  { term: "Sacrificial" },
  { term: "Sacred" },
  { term: "Scorn" },
  { term: "Sealed" },
  { term: "Seared" },
  { term: "Seed" },
  { term: "Seeking" },
  { term: "Shepherding" },
  { term: "Sincerity" },
  { term: "Slander" },
  { term: "Sloth" },
  { term: "Sober" },
  { term: "Sobriety" },
  { term: "Sojourner" },
  { term: "Spare" },
  { term: "Stumble" },
  { term: "Steadfast" },
  { term: "Stiff Necked" },
  { term: "Strife" },
  { term: "Submission" },
  { term: "Subdue" },
  { term: "Suffering" },
  { term: "Supplication" },
  { term: "Sustain" },
  { term: "Testimony" },
  { term: "Thanksgiving" },
  { term: "Thresh" },
  { term: "Trial" },
  { term: "Understanding" },
  { term: "Ungodly" },
  { term: "Unholy" },
  { term: "Unleavened" },
  { term: "Upright" },
  { term: "Vengeance" },
  { term: "Vow" },
  { term: "Warning" },
  { term: "Watch" },
  { term: "Watchful" },
  { term: "Widow" },
  { term: "Witness" },
  { term: "Woe" },
  { term: "Worship" },
  { term: "Prophet" },
  { term: "Priesthood" },
  { term: "Works" },
  { term: "Obedience" },
  { term: "Holiness" },
  // Temple, worship, sacrifice, purity, feasts (subset; many already present)
  { term: "Altar of Incense" },
  { term: "Bloodguilt" },
  { term: "Burning Coals" },
  { term: "Clean Days" },
  { term: "Clean Thing" },
  { term: "Congregation" },
  { term: "Covering of the Ark" },
  { term: "Daily Offering" },
  { term: "Festival" },
  { term: "Holy Convocation" },
  { term: "Lampstand" },
  { term: "Laver" },
  { term: "Meal Offering" },
  { term: "New Moon" },
  { term: "Purification" },
  { term: "Purity Laws" },
  { term: "Tabernacle Furnishings" },
  { term: "Temple Tax" },
  { term: "Votive Offering" },
  // Jewish groups, roles, offices, social terms (many already present)
  { term: "Chief Priest" },
  { term: "Lawyer" },
  { term: "Teacher of the Law" },
  { term: "Ruler" },
  { term: "Sanhedrin" },
  { term: "Proselyte" },
  { term: "Stranger" },
  { term: "Foreigner" },
  { term: "Redeemer" },
  // Roman government, military, punishment, law
  { term: "Cohort" },
  { term: "Tribune" },
  { term: "Governor" },
  { term: "Proconsul" },
  { term: "Praetor" },
  { term: "Edict" },
  { term: "Tribute" },
  { term: "Sentence" },
  { term: "Prisoner" },
  { term: "Chains" },
  { term: "Bondage" },
  // Money, weights, measures, time, materials (many already present, deduped at runtime)
  { term: "Beka" },
  { term: "Gerah" },
  { term: "Measure" },
  { term: "Weigh" },
  { term: "Scales" },
  { term: "Fine Linen" },
  { term: "Purple" },
  { term: "Scarlet" },
  { term: "Brass" },
  { term: "Onyx" },
  { term: "Bdellium" },
  { term: "Ointment" },
  { term: "Spice" },
  // War, weapons, armor, strategy (many already present)
  { term: "Buckler" },
  { term: "Helmet" },
  { term: "Javelin" },
  { term: "Quiver" },
  { term: "Rampart" },
  { term: "Fortress" },
  { term: "Banner" },
  { term: "Ambush" },
  { term: "Spoils" },
  // Agriculture, animals, daily life, crafts
  { term: "Olivepress" },
  { term: "Shearing" },
  { term: "Oxgoad" },
  { term: "Herdsman" },
  { term: "Stall" },
  { term: "Fodder" },
  { term: "Manger" },
  { term: "Loom" },
  { term: "Spinning" },
  { term: "Weaving" },
  { term: "Potter" },
  { term: "Clay" },
  { term: "Kiln" },
  { term: "Mortar" },
  { term: "Pitch" },
  { term: "Tar" },
  { term: "Balmer" },
  // Prophecy, visions, end times language (many already present)
  { term: "Seer" },
  { term: "Oracle" },
  { term: "Portent" },
  { term: "Mark" },
  { term: "Image of the Beast" },
  { term: "Lake of Fire" },
  // Bible study concept words (many already present; deduped at runtime)
  { term: "Fornication" },
  { term: "Heretic" },
  { term: "Testimony" },
  // User-requested keyword additions
  { term: "Abundance" },
  { term: "Acknowledge" },
  { term: "Adulteress" },
  { term: "Anger" },
  { term: "Anxiety" },
  { term: "Arrogant" },
  { term: "Balance" },
  { term: "Bed" },
  { term: "Bitter" },
  { term: "Bitterness" },
  { term: "Bribe" },
  { term: "Children" },
  { term: "Cistern" },
  { term: "Collateral" },
  { term: "Command" },
  { term: "Companion" },
  { term: "Confidence" },
  { term: "Contention" },
  { term: "Contentment" },
  { term: "Correction" },
  { term: "Corrupt" },
  { term: "Covetous" },
  { term: "Curse" },
  { term: "Darkness" },
  { term: "Daughter" },
  { term: "Deceit" },
  { term: "Deceitful" },
  { term: "Death" },
  { term: "Desire" },
  { term: "Destruction" },
  { term: "Diligence" },
  { term: "Discernment" },
  { term: "Distress" },
  { term: "Drunkard" },
  { term: "Equitable" },
  { term: "Evil" },
  { term: "Exaltation" },
  { term: "Faithful" },
  { term: "Faithfulness" },
  { term: "Father" },
  { term: "Fear" },
  { term: "Field" },
  { term: "Folly" },
  { term: "Fool" },
  { term: "Foolish" },
  { term: "Fountain" },
  { term: "Friend" },
  { term: "Fruit" },
  { term: "Gain" },
  { term: "Garland" },
  { term: "Generations" },
  { term: "Generous" },
  { term: "Glutton" },
  { term: "Gossip" },
  { term: "Gracious" },
  { term: "Greedy" },
  { term: "Grief" },
  { term: "Guidance" },
  { term: "Guile" },
  { term: "Harsh" },
  { term: "Heart" },
  { term: "Highway" },
  { term: "Holy" },
  { term: "Honor" },
  { term: "Hope" },
  { term: "House" },
  { term: "Humble" },
  { term: "Humiliation" },
  { term: "Increase" },
  { term: "Indolence" },
  { term: "Insight" },
  { term: "Integrity" },
  { term: "Joy" },
  { term: "Justice" },
  { term: "Kind" },
  { term: "Kindness" },
  { term: "Knowledge" },
  { term: "Lack" },
  { term: "Lamp" },
  { term: "Law" },
  { term: "Learning" },
  { term: "Life" },
  { term: "Light" },
  { term: "Lips" },
  { term: "Longing" },
  { term: "Loss" },
  { term: "Lot" },
  { term: "Lovingkindness" },
  { term: "Lying" },
  { term: "Meek" },
  { term: "Mind" },
  { term: "Mockery" },
  { term: "Mother" },
  { term: "Mouth" },
  { term: "Naive" },
  { term: "Neighbor" },
  { term: "Net" },
  { term: "Offspring" },
  { term: "Oil" },
  { term: "Oppression" },
  { term: "Partiality" },
  { term: "Path" },
  { term: "Patience" },
  { term: "Peace" },
  { term: "Perverse" },
  { term: "Perversity" },
  { term: "Pledge" },
  { term: "Planning" },
  { term: "Poor" },
  { term: "Poverty" },
  { term: "Precept" },
  { term: "Preparation" },
  { term: "Profit" },
  { term: "Promise" },
  { term: "Prosperity" },
  { term: "Prudence" },
  { term: "Punishment" },
  { term: "Quarrel" },
  { term: "Recompense" },
  { term: "Rich" },
  { term: "Riches" },
  { term: "Righteous" },
  { term: "Road" },
  { term: "Ruin" },
  { term: "Scoffer" },
  { term: "Scorner" },
  { term: "Seduction" },
  { term: "Self-Control" },
  { term: "Sensual" },
  { term: "Shield" },
  { term: "Shame" },
  { term: "Simple" },
  { term: "Sin" },
  { term: "Sluggard" },
  { term: "Smooth" },
  { term: "Snare" },
  { term: "Sorrow" },
  { term: "Soul" },
  { term: "Speech" },
  { term: "Spirit" },
  { term: "Steps" },
  { term: "Storehouse" },
  { term: "Strong Tower" },
  { term: "Stubborn" },
  { term: "Surety" },
  { term: "Talebearer" },
  { term: "Teaching" },
  { term: "Temperate" },
  { term: "Toil" },
  { term: "Tongue" },
  { term: "Trap" },
  { term: "Treacherous" },
  { term: "Treasure" },
  { term: "Truth" },
  { term: "Uprightness" },
  { term: "Vain" },
  { term: "Verdict" },
  { term: "Violence" },
  { term: "Vine" },
  { term: "Walk" },
  { term: "Way" },
  { term: "Wealth" },
  { term: "Weights" },
  { term: "Wicked" },
  { term: "Wickedness" },
  { term: "Wife" },
  { term: "Word" },
  { term: "Forsake" },
];
