/**
 * Comprehensive list of biblical keywords and phrases
 * 
 * Each keyword appears once.
 * All keywords appear in the canonical Old or New Testament or are historically/culturally necessary to understand Scripture.
 * Alphabetized by term.
 * Merged from current list and new unified 3-layer list.
 */

export type BibleKeywordEntry = {
  term: string;
};

function normalizeTerm(term: string): string {
  return term.trim().toLowerCase();
}

function dedupeKeywordEntries(entries: BibleKeywordEntry[]): BibleKeywordEntry[] {
  const seen = new Set<string>();
  const deduped: BibleKeywordEntry[] = [];

  entries.forEach((entry) => {
    const normalized = normalizeTerm(entry.term);
    if (!normalized || seen.has(normalized)) {
      return;
    }
    seen.add(normalized);
    deduped.push({ term: entry.term.trim() });
  });

  return deduped;
}

const USER_REQUESTED_KEYWORDS: string[] = [
  "Abandon",
  "Abase",
  "Abhor",
  "Abide",
  "Abomination",
  "Abound",
  "Abundance",
  "Accuse",
  "Adhere",
  "Adversary",
  "Afflict",
  "Affliction",
  "Afterward",
  "Age",
  "Agreement",
  "Allegiance",
  "Almighty",
  "Altar",
  "Amazement",
  "Ambition",
  "Anoint",
  "Anointing",
  "Apparel",
  "Appeal",
  "Appoint",
  "Appointed",
  "Ark",
  "Ashes",
  "Assembly",
  "Authority",
  "Avenge",
  "Awake",
  "Awaken",
  "Barren",
  "Beast",
  "Beasts of the field",
  "Beget",
  "Beginning",
  "Behold",
  "Believe",
  "Betray",
  "Birth",
  "Birthright",
  "Blameless",
  "Blaspheme",
  "Bless",
  "Blessed",
  "Blessing",
  "Blood",
  "Bondage",
  "Bondservant",
  "Boundary",
  "Bow",
  "Bread",
  "Breath",
  "Bride",
  "Bridegroom",
  "Brotherhood",
  "Build",
  "Burn",
  "Burning",
  "Burnt offering",
  "Calamity",
  "Calling",
  "Captive",
  "Captivity",
  "Carcass",
  "Care",
  "Cattle",
  "Cave",
  "Ceremony",
  "Charge",
  "Chastise",
  "Childbearing",
  "Chosen",
  "Clean",
  "Cling",
  "Clothe",
  "Clothing",
  "Command",
  "Commandment",
  "Commit",
  "Companion",
  "Compassion",
  "Conceal",
  "Conceive",
  "Condemn",
  "Confess",
  "Confusion",
  "Consecrate",
  "Consume",
  "Contention",
  "Contend",
  "Contract",
  "Corrupt",
  "Corruption",
  "Counsel",
  "Covenant",
  "Cover",
  "Crafty",
  "Create",
  "Creation",
  "Creator",
  "Creature",
  "Cry",
  "Cultivate",
  "Curse",
  "Cut off",
  "Darkness",
  "Daughter",
  "Dawn",
  "Day",
  "Death",
  "Deceive",
  "Deception",
  "Decree",
  "Deep",
  "Defile",
  "Delight",
  "Deliver",
  "Deliverance",
  "Depart",
  "Desert",
  "Desire",
  "Despise",
  "Destroy",
  "Destruction",
  "Devour",
  "Discern",
  "Discernment",
  "Discipline",
  "Dishonor",
  "Disperse",
  "Division",
  "Dominion",
  "Dread",
  "Dream",
  "Dwell",
  "Dwelling",
  "Earth",
  "Elder",
  "Embrace",
  "Endure",
  "Enmity",
  "Envy",
  "Establish",
  "Eternal",
  "Everlasting",
  "Evil",
  "Exalt",
  "Exceed",
  "Exile",
  "Exist",
  "Expanse",
  "Face",
  "Faith",
  "Faithful",
  "Fall",
  "Falsehood",
  "Famine",
  "Favor",
  "Fear",
  "Fertile",
  "Fertility",
  "Field",
  "Flesh",
  "Flock",
  "Flourish",
  "Flood",
  "Forbear",
  "Forget",
  "Forgive",
  "Forgiveness",
  "Foundation",
  "Fruit",
  "Fruitful",
  "Fulfill",
  "Gather",
  "Garment",
  "Generations",
  "Gift",
  "Give",
  "Glory",
  "Good",
  "Govern",
  "Grace",
  "Grave",
  "Greed",
  "Grieve",
  "Ground",
  "Guard",
  "Guilt",
  "Handmaid",
  "Harden",
  "Harvest",
  "Hate",
  "Heaven",
  "Heir",
  "Heritage",
  "Holy",
  "Honor",
  "Hope",
  "Household",
  "Humble",
  "Hunger",
  "Husband",
  "Idolatry",
  "Image",
  "Immortality",
  "Increase",
  "Inheritance",
  "Iniquity",
  "Innocent",
  "Integrity",
  "Judge",
  "Judgment",
  "Justice",
  "Keep",
  "Kindness",
  "Knowledge",
  "Labor",
  "Land",
  "Law",
  "Legacy",
  "Lend",
  "Life",
  "Light",
  "Live",
  "Livestock",
  "Longevity",
  "Lordship",
  "Love",
  "Male",
  "Marriage",
  "Meek",
  "Mercy",
  "Might",
  "Mighty",
  "Multiply",
  "Murder",
  "Naked",
  "Nation",
  "Neighbor",
  "Obedience",
  "Offering",
  "Offspring",
  "Oppress",
  "Oppression",
  "Ordain",
  "Oath",
  "Pain",
  "Pardon",
  "Pasture",
  "Peace",
  "Perish",
  "Perverse",
  "Pervert",
  "Pit",
  "Plant",
  "Plunder",
  "Possession",
  "Power",
  "Praise",
  "Preserve",
  "Pride",
  "Promise",
  "Prosper",
  "Provision",
  "Punish",
  "Purify",
  "Pursue",
  "Rage",
  "Ransom",
  "Reap",
  "Rebellion",
  "Rebuke",
  "Redeem",
  "Redemption",
  "Refuge",
  "Reign",
  "Reject",
  "Remember",
  "Repent",
  "Reproach",
  "Restore",
  "Restrain",
  "Return",
  "Reward",
  "Righteous",
  "Righteousness",
  "Rise",
  "Rule",
  "Sacrifice",
  "Sanctify",
  "Seed",
  "Separate",
  "Separation",
  "Servant",
  "Service",
  "Shame",
  "Shepherd",
  "Sin",
  "Sisterhood",
  "Slave",
  "Sleep",
  "Sojourn",
  "Soul",
  "Sow",
  "Spirit",
  "Steward",
  "Strength",
  "Strive",
  "Subdue",
  "Suffer",
  "Sweat",
  "Tempt",
  "Test",
  "Transgression",
  "Tremble",
  "Trouble",
  "Truth",
  "Unclean",
  "Upright",
  "Vain",
  "Vengeance",
  "Vow",
  "Walk",
  "Wander",
  "Waters",
  "Wealth",
  "Weep",
  "Wicked",
  "Wickedness",
  "Wife",
  "Wild",
  "Wine",
  "Wisdom",
  "Witness",
  "Woman",
  "Womb",
  "Work",
  "Worship",
  "Wrath",
  "Yearn",
  "Yield",
];

const BASE_BIBLE_KEYWORDS_LIST: BibleKeywordEntry[] = [
  { term: "Abomination" },
  { term: "Abomination of Desolation" },
  { term: "Abraham's Bosom" },
  { term: "Accuser" },
  { term: "Adoption" },
  { term: "Adoption Language" },
  { term: "Adultery" },
  { term: "Advocate" },
  { term: "Affliction" },
  { term: "Age to Come" },
  { term: "Alabaster" },
  { term: "Alms" },
  { term: "Altar" },
  { term: "Amen" },
  { term: "Anathema" },
  { term: "Ancient of Days" },
  { term: "Angel" },
  { term: "Angel of the Lord" },
  { term: "Anointed King" },
  { term: "Anointing" },
  { term: "Anointing Oil" },
  { term: "Antichrist" },
  { term: "Apocalyptic Language" },
  { term: "Apostasy" },
  { term: "Apostle" },
  { term: "Ark" },
  { term: "Ark of the Covenant" },
  { term: "Armor" },
  { term: "Armor Bearer" },
  { term: "Armor of God" },
  { term: "Ascension" },
  { term: "Asherah" },
  { term: "Ashes" },
  { term: "Assembly" },
  { term: "Astrologer" },
  { term: "Atonement" },
  { term: "Atonement Cover" },
  { term: "Avenger of Blood" },
  { term: "Babel" },
  { term: "Babylon" },
  { term: "Balm" },
  { term: "Baptism" },
  { term: "Baptism of Fire" },
  { term: "Baptism of the Holy Spirit" },
  { term: "Barley" },
  { term: "Battle Line" },
  { term: "Battering Ram" },
  { term: "Beast" },
  { term: "Beatitude" },
  { term: "Beelzebub" },
  { term: "Behemoth" },
  { term: "Belial" },
  { term: "Benediction" },
  { term: "Betrayal" },
  { term: "Bill of Divorce" },
  { term: "Birthright" },
  { term: "Bishop" },
  { term: "Bird of Prey" },
  { term: "Blasphemy" },
  { term: "Blessing" },
  { term: "Blood" },
  { term: "Blood Avenger" },
  { term: "Blood of the Covenant" },
  { term: "Blood Ritual" },
  { term: "Bondservant" },
  { term: "Born Again" },
  { term: "Boundary Stone" },
  { term: "Bow Down" },
  { term: "Bread Breaking" },
  { term: "Bread of Life" },
  { term: "Bread of the Presence" },
  { term: "Breastplate" },
  { term: "Bride" },
  { term: "Bridegroom" },
  { term: "Bronze Altar" },
  { term: "Bronze Serpent" },
  { term: "Burden Bearer" },
  { term: "Burdens" },
  { term: "Burnt Offering" },
  { term: "Calling" },
  { term: "Camel Driver" },
  { term: "Canaanite" },
  { term: "Candlestick" },
  { term: "Casting Lots" },
  { term: "Censer" },
  { term: "Census" },
  { term: "Centurion" },
  { term: "Chaff" },
  { term: "Chalice" },
  { term: "Charms" },
  { term: "Chariot" },
  { term: "Chariot Corps" },
  { term: "Chasten" },
  { term: "Chastisement" },
  { term: "Cherub" },
  { term: "Cherubim" },
  { term: "Chief Baker" },
  { term: "Chief Cupbearer" },
  { term: "Chief Priest" },
  { term: "Children of God" },
  { term: "Children of Israel" },
  { term: "Chosen One" },
  { term: "Christ" },
  { term: "Church" },
  { term: "Circumcision" },
  { term: "Citadel" },
  { term: "City Fortifications" },
  { term: "City of God" },
  { term: "Cleansing" },
  { term: "Cloud" },
  { term: "Cloud of Witnesses" },
  { term: "Clothing as Status" },
  { term: "Commandment" },
  { term: "Commander of Fifties" },
  { term: "Commander of Thousands" },
  { term: "Confession" },
  { term: "Consecration" },
  { term: "Contend" },
  { term: "Cornerstone" },
  { term: "Corvée Labor" },
  { term: "Cosmic Imagery" },
  { term: "Cosmic Rebellion" },
  { term: "Covenant" },
  { term: "Covenant Blessing" },
  { term: "Covenant Curse" },
  { term: "Covenant Renewal" },
  { term: "Cover Shame" },
  { term: "Creation" },
  { term: "Creator" },
  { term: "Crown" },
  { term: "Crown of Life" },
  { term: "Crown of Thorns" },
  { term: "Crucifixion" },
  { term: "Cubit" },
  { term: "Daily Bread" },
  { term: "Daily Wage" },
  { term: "Day of Atonement" },
  { term: "Day of Judgment" },
  { term: "Day of the Lord" },
  { term: "Day of the Lord Pattern" },
  { term: "Debt" },
  { term: "Debt Forgiveness" },
  { term: "Debtor Prison" },
  { term: "Decalogue" },
  { term: "Decree" },
  { term: "Deed of Purchase" },
  { term: "Defilement" },
  { term: "Deliver" },
  { term: "Deliverance" },
  { term: "Deliverer" },
  { term: "Demon" },
  { term: "Denarius" },
  { term: "Denarius Wage" },
  { term: "Desolation" },
  { term: "Despise" },
  { term: "Detestable" },
  { term: "Devil" },
  { term: "Diaspora" },
  { term: "Disciple" },
  { term: "Divination" },
  { term: "Divination Practices" },
  { term: "Doctrine" },
  { term: "Double Portion" },
  { term: "Dream Interpreter" },
  { term: "Dry Cistern" },
  { term: "Dust on Head" },
  { term: "Economic Oppression" },
  { term: "Eden" },
  { term: "Elder" },
  { term: "Elders at the Gate" },
  { term: "Elect" },
  { term: "Election" },
  { term: "Emmanuel" },
  { term: "Enchantments" },
  { term: "End Times" },
  { term: "Ephod" },
  { term: "Epistle" },
  { term: "Eternal Life" },
  { term: "Eunuch" },
  { term: "Evangelist" },
  { term: "Evil One" },
  { term: "Exile" },
  { term: "Exile Motif" },
  { term: "Exodus" },
  { term: "Expiation" },
  { term: "Eye for an Eye" },
  { term: "Faith" },
  { term: "Faithfulness vs Faith" },
  { term: "Fall on One's Face" },
  { term: "False Prophet" },
  { term: "Famine" },
  { term: "Fasting" },
  { term: "Fear of the Lord" },
  { term: "Feast of Booths" },
  { term: "Feast of Dedication" },
  { term: "Feast of Firstfruits" },
  { term: "Feast of Tabernacles" },
  { term: "Feast of Trumpets" },
  { term: "Feast of Unleavened Bread" },
  { term: "Feast of Weeks" },
  { term: "Firstborn" },
  { term: "Firstborn Portion" },
  { term: "Firstfruits" },
  { term: "Flock Ownership" },
  { term: "Foot Washing" },
  { term: "Forbidden Fruit" },
  { term: "Forced Labor" },
  { term: "Foreknowledge" },
  { term: "Forgiveness" },
  { term: "Foundation" },
  { term: "Frankincense" },
  { term: "Fruit of the Spirit" },
  { term: "Gate Judgment" },
  { term: "Gatekeeper" },
  { term: "Genealogy" },
  { term: "Gentile" },
  { term: "Gethsemane" },
  { term: "Gifts of the Spirit" },
  { term: "Glorification" },
  { term: "Glory" },
  { term: "Glory of God" },
  { term: "Gog and Magog" },
  { term: "Gold" },
  { term: "Golgotha" },
  { term: "Gospel" },
  { term: "Grace" },
  { term: "Grain Offering" },
  { term: "Granary" },
  { term: "Great Commission" },
  { term: "Great White Throne" },
  { term: "Guest Right" },
  { term: "Hades" },
  { term: "Hallelujah" },
  { term: "Handmaid" },
  { term: "Harlot" },
  { term: "Harvest" },
  { term: "Harvest Share" },
  { term: "Hardhearted" },
  { term: "Heart Circumcision" },
  { term: "Heaven" },
  { term: "Hell" },
  { term: "Heresy" },
  { term: "Hide the Face" },
  { term: "High Priest" },
  { term: "Holy of Holies" },
  { term: "Holy Spirit" },
  { term: "Honor and Shame Culture" },
  { term: "Hosanna" },
  { term: "Host of Heaven" },
  { term: "Hospitality Code" },
  { term: "House of God" },
  { term: "Household Manager" },
  { term: "Household Servant" },
  { term: "Idol" },
  { term: "Idolatry" },
  { term: "Image of God" },
  { term: "Incarnation" },
  { term: "Incense" },
  { term: "Inheritance" },
  { term: "Inheritance Allotment" },
  { term: "Inheritance Promise" },
  { term: "Inheritance Rights" },
  { term: "Iniquity" },
  { term: "Intercession" },
  { term: "Interest Usury" },
  { term: "Iron Rod" },
  { term: "Israelite" },
  { term: "Justification" },
  { term: "Justification Language" },
  { term: "Jubilee" },
  { term: "Jubilee Release" },
  { term: "Judge" },
  { term: "Judgment" },
  { term: "Judgment Seat" },
  { term: "Key" },
  { term: "Keys of the Kingdom" },
  { term: "Kingdom" },
  { term: "Kingdom Authority" },
  { term: "Kingdom of God" },
  { term: "Kingdom of Heaven" },
  { term: "Kinsman" },
  { term: "Kinsman-Redeemer" },
  { term: "Lamb" },
  { term: "Lamb of God" },
  { term: "Lampstand" },
  { term: "Land Allotment" },
  { term: "Last Days" },
  { term: "Last Supper" },
  { term: "Laid Waste" },
  { term: "Lambing" },
  { term: "Law of Moses" },
  { term: "Leaven" },
  { term: "Legion" },
  { term: "Leper" },
  { term: "Leprosy" },
  { term: "Leviathan" },
  { term: "Levite" },
  { term: "Legal Scroll" },
  { term: "Light of the World" },
  { term: "Lift the Horn" },
  { term: "Lion of Judah" },
  { term: "Lion's Den" },
  { term: "Living Water" },
  { term: "Livestock" },
  { term: "Locust Swarm" },
  { term: "Loathe" },
  { term: "Lord of Hosts" },
  { term: "Magi" },
  { term: "Magicians of Egypt" },
  { term: "Mammon" },
  { term: "Manna" },
  { term: "Measuring Rod" },
  { term: "Mediator" },
  { term: "Medium" },
  { term: "Melchizedek" },
  { term: "Mercy Seat" },
  { term: "Messenger Herald" },
  { term: "Messiah" },
  { term: "Messianic Age" },
  { term: "Messianic Expectation" },
  { term: "Millennium" },
  { term: "Millstone" },
  { term: "Miracle" },
  { term: "Money Changer" },
  { term: "Most Holy Place" },
  { term: "Myrrh" },
  { term: "Nazirite" },
  { term: "Necromancer" },
  { term: "New Birth" },
  { term: "New Covenant" },
  { term: "New Creation" },
  { term: "New Exodus Pattern" },
  { term: "New Jerusalem" },
  { term: "New Obedience" },
  { term: "Nurse" },
  { term: "Oath" },
  { term: "Oath Ceremony" },
  { term: "Oath Token" },
  { term: "Offering" },
  { term: "Old Covenant" },
  { term: "Olive Branch" },
  { term: "Omens" },
  { term: "Only Begotten" },
  { term: "Oppress" },
  { term: "Ordination" },
  { term: "Outer Court" },
  { term: "Overseer" },
  { term: "Parable" },
  { term: "Paradise" },
  { term: "Parousia" },
  { term: "Passover" },
  { term: "Pentecost" },
  { term: "Perseverance of the Saints" },
  { term: "Pharisee" },
  { term: "Phylacteries" },
  { term: "Pillar" },
  { term: "Pit" },
  { term: "Plague" },
  { term: "Pledge Cloak" },
  { term: "Plowshare" },
  { term: "Plunder" },
  { term: "Pour Out Wrath" },
  { term: "Power" },
  { term: "Predestination" },
  { term: "Presence of God" },
  { term: "Price of a Slave" },
  { term: "Priesthood" },
  { term: "Priestly Garments" },
  { term: "Prince of Peace" },
  { term: "Prophecy" },
  { term: "Prophet" },
  { term: "Prophetic Hyperbole" },
  { term: "Prophetic Sign Act" },
  { term: "Propitiation" },
  { term: "Public Rebuke" },
  { term: "Ransom" },
  { term: "Ransom Payment" },
  { term: "Ravaged" },
  { term: "Rebellious" },
  { term: "Rebuke" },
  { term: "Redeem" },
  { term: "Redemption" },
  { term: "Redemption Clause" },
  { term: "Redemption Document" },
  { term: "Redemption Price" },
  { term: "Regathering" },
  { term: "Regeneration" },
  { term: "Remember Covenant" },
  { term: "Remnant" },
  { term: "Remnant Theology" },
  { term: "Repentance" },
  { term: "Resurrection" },
  { term: "Return from Exile" },
  { term: "Righteous Status" },
  { term: "Righteousness" },
  { term: "Rod" },
  { term: "Royal Advisor" },
  { term: "Royal Garments" },
  { term: "Royal Messiah" },
  { term: "Rulers of This Age" },
  { term: "Sabbath" },
  { term: "Sacred Lot" },
  { term: "Sacrifice" },
  { term: "Sadducee" },
  { term: "Sackcloth and Ashes" },
  { term: "Salvation" },
  { term: "Sanctification" },
  { term: "Scapegoat" },
  { term: "Scattering" },
  { term: "Scepter" },
  { term: "Scepter Rod" },
  { term: "Scourge" },
  { term: "Scripture" },
  { term: "Seal" },
  { term: "Seal Impression" },
  { term: "Sealing of the Spirit" },
  { term: "Second Coming" },
  { term: "Serpent" },
  { term: "Shed Blood" },
  { term: "Sheepfold Gate" },
  { term: "Shekinah" },
  { term: "Sheol" },
  { term: "Shepherd" },
  { term: "Shepherd King" },
  { term: "Shepherd's Rod" },
  { term: "Shield Wall" },
  { term: "Signet Ring" },
  { term: "Silver" },
  { term: "Sin Offering" },
  { term: "Smite" },
  { term: "Smote" },
  { term: "Son of David" },
  { term: "Son of God" },
  { term: "Son of Man" },
  { term: "Sorcery" },
  { term: "Spells" },
  { term: "Spirit of God" },
  { term: "Spiritist" },
  { term: "Spoil of War" },
  { term: "Staff" },
  { term: "Staff of Authority" },
  { term: "Standard Bearer" },
  { term: "Steward" },
  { term: "Stiff-Necked" },
  { term: "Store City" },
  { term: "Striking" },
  { term: "Stronghold" },
  { term: "Strive" },
  { term: "Substitution" },
  { term: "Suffering Servant" },
  { term: "Sword of the Spirit" },
  { term: "Symbolic Action" },
  { term: "Symbolic Numbers" },
  { term: "Synagogue" },
  { term: "Tabernacle" },
  { term: "Table Fellowship" },
  { term: "Table of Showbread" },
  { term: "Talent" },
  { term: "Taskmaster" },
  { term: "Tax Collector" },
  { term: "Temple" },
  { term: "Temple Treasury" },
  { term: "Tent of Meeting" },
  { term: "Threshing Floor" },
  { term: "Threshing Ox" },
  { term: "Threshing Sledge" },
  { term: "Throne" },
  { term: "Tithe" },
  { term: "Tithe Storehouse" },
  { term: "Torah" },
  { term: "Torn Garments" },
  { term: "Tower of Babel" },
  { term: "Trade Goods" },
  { term: "Transfiguration" },
  { term: "Transgression" },
  { term: "Tribe" },
  { term: "Tribulation" },
  { term: "Trinity" },
  { term: "Trumpet" },
  { term: "Trumpet Signal" },
  { term: "Unclean" },
  { term: "Unleavened Bread" },
  { term: "Urim and Thummim" },
  { term: "Usury" },
  { term: "Veil" },
  { term: "Vineyard" },
  { term: "Virgin Birth" },
  { term: "Visit Iniquity" },
  { term: "Watchers" },
  { term: "Watchman" },
  { term: "Waterless Pit" },
  { term: "Wet Nurse" },
  { term: "Wilderness" },
  { term: "Wine" },
  { term: "Winepress" },
  { term: "Winepress Pit" },
  { term: "Winnowing Fork" },
  { term: "Wisdom" },
  { term: "Wise Men of the East" },
  { term: "Word of God" },
  { term: "Works of the Law" },
  { term: "Wrath" },
  { term: "Yahweh" },
  { term: "Year of Jubilee" },
  { term: "Yoke" },
  { term: "Yoke Bearer" },
  { term: "Zeal" },
  { term: "Zealot" },
  { term: "Zion" },
  // --- Additional WEB glossary and expanded keyword terms ---
  // WEB glossary
  { term: "Abaddon" },
  { term: "Abba" },
  { term: "Alpha" },
  { term: "Apollyon" },
  { term: "Armageddon" },
  { term: "Har mגדּdon" },
  { term: "Assarion" },
  { term: "Aureus" },
  { term: "Baptize" },
  { term: "Bath" },
  { term: "Batos" },
  { term: "Beelzebul" },
  { term: "Choenix" },
  { term: "Concubine" },
  { term: "Cor" },
  { term: "Corban" },
  { term: "Crucify" },
  { term: "Cummin" },
  { term: "Darnel" },
  { term: "Denarii" },
  { term: "Didrachma" },
  { term: "Distaff" },
  { term: "Drachma" },
  { term: "Ephah" },
  { term: "Gittith" },
  { term: "Goad" },
  { term: "Hin" },
  { term: "Homer" },
  { term: "Jehovah" },
  { term: "Kodrantes" },
  { term: "Lepta" },
  { term: "Mahalath" },
  { term: "Maschil" },
  { term: "Michtam" },
  { term: "Mina" },
  { term: "Praetorium" },
  { term: "Quadrans" },
  { term: "Rabbi" },
  { term: "Rhabboni" },
  { term: "Sata" },
  { term: "Shigionoth" },
  { term: "Stadion" },
  { term: "Stadia" },
  { term: "Stater" },
  { term: "Tartarus" },
  { term: "Teraphim" },
  { term: "Yah" },
  // Expanded keyword candidates (selection; many already present but deduped at runtime)
  { term: "Abstain" },
  { term: "Accountability" },
  { term: "Accursed" },
  { term: "Acquit" },
  { term: "Adversary" },
  { term: "Awe" },
  { term: "Baldness" },
  { term: "Basket" },
  { term: "Begotten" },
  { term: "Blameless" },
  { term: "Borne" },
  { term: "Calamity" },
  { term: "Calloused" },
  { term: "Captivity" },
  { term: "Carnal" },
  { term: "Chastening" },
  { term: "Chastity" },
  { term: "Cherished" },
  { term: "Clean Days" },
  { term: "Clean Thing" },
  { term: "Coals" },
  { term: "Consolation" },
  { term: "Contempt" },
  { term: "Contrite" },
  { term: "Convict" },
  { term: "Conviction" },
  { term: "Corruption" },
  { term: "Counsel" },
  { term: "Counselor" },
  { term: "Crimson" },
  { term: "Crossbeam" },
  { term: "Daemon" },
  { term: "Damnation" },
  { term: "Devotion" },
  { term: "Devout" },
  { term: "Discipline" },
  { term: "Disperse" },
  { term: "Doxology" },
  { term: "Dread" },
  { term: "Dust" },
  { term: "Earnest" },
  { term: "Endurance" },
  { term: "Enmity" },
  { term: "Envy" },
  { term: "Equity" },
  { term: "Error" },
  { term: "Eternal" },
  { term: "Exalt" },
  { term: "Exhort" },
  { term: "Goaded" },
  { term: "Grant" },
  { term: "Grieve" },
  { term: "Guilt" },
  { term: "Guilt Offering" },
  { term: "Hard Heart" },
  { term: "Headship" },
  { term: "Heathen" },
  { term: "Heavenly" },
  { term: "Heritage" },
  { term: "Hewn" },
  { term: "Holy Place" },
  { term: "Household" },
  { term: "Impart" },
  { term: "Impute" },
  { term: "Imputation" },
  { term: "Instruction" },
  { term: "Intercede" },
  { term: "Interpretation" },
  { term: "Jealousy" },
  { term: "Koinonia" },
  { term: "Lament" },
  { term: "Lawful" },
  { term: "Lawlessness" },
  { term: "Libation" },
  { term: "Living Waters" },
  { term: "Loins" },
  { term: "Lordship" },
  { term: "Lots" },
  { term: "Lowliness" },
  { term: "Lust" },
  { term: "Manifest" },
  { term: "Manifestation" },
  { term: "Martyr" },
  { term: "Merciful" },
  { term: "Ministry" },
  { term: "Mock" },
  { term: "Molten" },
  { term: "Mourn" },
  { term: "Mystery" },
  { term: "Nations" },
  { term: "Ordinance" },
  { term: "Orphan" },
  { term: "Perfect" },
  { term: "Perfection" },
  { term: "Perish" },
  { term: "Persecuted" },
  { term: "Persecution" },
  { term: "Pestilence" },
  { term: "Petition" },
  { term: "Piety" },
  { term: "Pollution" },
  { term: "Portion" },
  { term: "Profane" },
  { term: "Prosper" },
  { term: "Prostitute" },
  { term: "Prostitution" },
  { term: "Proverb" },
  { term: "Providence" },
  { term: "Purify" },
  { term: "Purity" },
  { term: "Put Away" },
  { term: "Quench" },
  { term: "Quickened" },
  { term: "Reconcile" },
  { term: "Reconciliation" },
  { term: "Refuge" },
  { term: "Rejoicing" },
  { term: "Reproof" },
  { term: "Revile" },
  { term: "Reward" },
  { term: "Robes" },
  { term: "Sacrificial System" },
  { term: "Sacrificial" },
  { term: "Sacred" },
  { term: "Scorn" },
  { term: "Sealed" },
  { term: "Seared" },
  { term: "Seed" },
  { term: "Seeking" },
  { term: "Shepherding" },
  { term: "Sincerity" },
  { term: "Slander" },
  { term: "Sloth" },
  { term: "Sober" },
  { term: "Sobriety" },
  { term: "Sojourner" },
  { term: "Spare" },
  { term: "Stumble" },
  { term: "Steadfast" },
  { term: "Stiff Necked" },
  { term: "Strife" },
  { term: "Submission" },
  { term: "Subdue" },
  { term: "Suffering" },
  { term: "Supplication" },
  { term: "Sustain" },
  { term: "Testimony" },
  { term: "Thanksgiving" },
  { term: "Thresh" },
  { term: "Trial" },
  { term: "Understanding" },
  { term: "Ungodly" },
  { term: "Unholy" },
  { term: "Unleavened" },
  { term: "Upright" },
  { term: "Vengeance" },
  { term: "Vow" },
  { term: "Warning" },
  { term: "Watch" },
  { term: "Watchful" },
  { term: "Widow" },
  { term: "Witness" },
  { term: "Woe" },
  { term: "Worship" },
  { term: "Prophet" },
  { term: "Priesthood" },
  { term: "Works" },
  { term: "Obedience" },
  { term: "Holiness" },
  // Temple, worship, sacrifice, purity, feasts (subset; many already present)
  { term: "Altar of Incense" },
  { term: "Bloodguilt" },
  { term: "Burning Coals" },
  { term: "Clean Days" },
  { term: "Clean Thing" },
  { term: "Congregation" },
  { term: "Covering of the Ark" },
  { term: "Daily Offering" },
  { term: "Festival" },
  { term: "Holy Convocation" },
  { term: "Lampstand" },
  { term: "Laver" },
  { term: "Meal Offering" },
  { term: "New Moon" },
  { term: "Purification" },
  { term: "Purity Laws" },
  { term: "Tabernacle Furnishings" },
  { term: "Temple Tax" },
  { term: "Votive Offering" },
  // Jewish groups, roles, offices, social terms (many already present)
  { term: "Chief Priest" },
  { term: "Lawyer" },
  { term: "Teacher of the Law" },
  { term: "Ruler" },
  { term: "Sanhedrin" },
  { term: "Proselyte" },
  { term: "Stranger" },
  { term: "Foreigner" },
  { term: "Redeemer" },
  // Roman government, military, punishment, law
  { term: "Cohort" },
  { term: "Tribune" },
  { term: "Governor" },
  { term: "Proconsul" },
  { term: "Praetor" },
  { term: "Edict" },
  { term: "Tribute" },
  { term: "Sentence" },
  { term: "Prisoner" },
  { term: "Chains" },
  { term: "Bondage" },
  // Money, weights, measures, time, materials (many already present, deduped at runtime)
  { term: "Beka" },
  { term: "Gerah" },
  { term: "Measure" },
  { term: "Weigh" },
  { term: "Scales" },
  { term: "Fine Linen" },
  { term: "Purple" },
  { term: "Scarlet" },
  { term: "Brass" },
  { term: "Onyx" },
  { term: "Bdellium" },
  { term: "Ointment" },
  { term: "Spice" },
  // War, weapons, armor, strategy (many already present)
  { term: "Buckler" },
  { term: "Helmet" },
  { term: "Javelin" },
  { term: "Quiver" },
  { term: "Rampart" },
  { term: "Fortress" },
  { term: "Banner" },
  { term: "Ambush" },
  { term: "Spoils" },
  // Agriculture, animals, daily life, crafts
  { term: "Olivepress" },
  { term: "Shearing" },
  { term: "Oxgoad" },
  { term: "Herdsman" },
  { term: "Stall" },
  { term: "Fodder" },
  { term: "Manger" },
  { term: "Loom" },
  { term: "Spinning" },
  { term: "Weaving" },
  { term: "Potter" },
  { term: "Clay" },
  { term: "Kiln" },
  { term: "Mortar" },
  { term: "Pitch" },
  { term: "Tar" },
  { term: "Balmer" },
  // Prophecy, visions, end times language (many already present)
  { term: "Seer" },
  { term: "Oracle" },
  { term: "Portent" },
  { term: "Mark" },
  { term: "Image of the Beast" },
  { term: "Lake of Fire" },
  // Bible study concept words (many already present; deduped at runtime)
  { term: "Fornication" },
  { term: "Heretic" },
  { term: "Testimony" },
  // User-requested keyword additions
  { term: "Abundance" },
  { term: "Acknowledge" },
  { term: "Adulteress" },
  { term: "Anger" },
  { term: "Anxiety" },
  { term: "Arrogant" },
  { term: "Balance" },
  { term: "Bed" },
  { term: "Bitter" },
  { term: "Bitterness" },
  { term: "Bribe" },
  { term: "Children" },
  { term: "Cistern" },
  { term: "Collateral" },
  { term: "Command" },
  { term: "Companion" },
  { term: "Confidence" },
  { term: "Contention" },
  { term: "Contentment" },
  { term: "Correction" },
  { term: "Corrupt" },
  { term: "Covetous" },
  { term: "Curse" },
  { term: "Darkness" },
  { term: "Daughter" },
  { term: "Deceit" },
  { term: "Deceitful" },
  { term: "Death" },
  { term: "Desire" },
  { term: "Destruction" },
  { term: "Diligence" },
  { term: "Discernment" },
  { term: "Distress" },
  { term: "Drunkard" },
  { term: "Equitable" },
  { term: "Evil" },
  { term: "Exaltation" },
  { term: "Faithful" },
  { term: "Faithfulness" },
  { term: "Father" },
  { term: "Fear" },
  { term: "Field" },
  { term: "Folly" },
  { term: "Fool" },
  // User-requested additions (deduped) - batch 6
  { term: "Abide" },
  { term: "Accuse" },
  { term: "Admonish" },
  { term: "Afflict" },
  { term: "Altar fire" },
  { term: "Anoint" },
  { term: "Anointed" },
  { term: "Avenge" },
  { term: "Battle" },
  { term: "Bear guilt" },
  { term: "Behold" },
  { term: "Bless" },
  { term: "Blow trumpet" },
  { term: "Bond" },
  { term: "Bread" },
  { term: "Burning" },
  { term: "Camp" },
  { term: "Charge" },
  { term: "Chastise" },
  { term: "Chosen" },
  { term: "Clean" },
  { term: "Consecrate" },
  { term: "Consume" },
  { term: "Contribution" },
  { term: "Dedicate" },
  { term: "Defile" },
  { term: "Depart" },
  { term: "Desert" },
  { term: "Destroy" },
  { term: "Devote" },
  { term: "Disobedience" },
  { term: "Dwell" },
  { term: "Dwelling" },
  { term: "Encamp" },
  { term: "Encampment" },
  { term: "Forgive" },
  { term: "Freewill offering" },
  { term: "Gather" },
  { term: "Grumble" },
  { term: "Grumbling" },
  { term: "Half tribe" },
  { term: "Harden" },
  { term: "Healing" },
  { term: "Heave offering" },
  { term: "Impurity" },
  { term: "Leader" },
  { term: "Levitical service" },
  { term: "March" },
  { term: "Memorial" },
  { term: "Mercy" },
  { term: "Mighty hand" },
  { term: "Murmur" },
  { term: "Murmuring" },
  { term: "Nation" },
  { term: "Nazirite vow" },
  { term: "Overthrow" },
  { term: "Peace offering" },
  { term: "Possession" },
  { term: "Refuse" },
  { term: "Release" },
  { term: "Remembrance" },
  { term: "Repent" },
  { term: "Rest" },
  { term: "Reverence" },
  { term: "Sanctify" },
  { term: "Sanctuary" },
  { term: "Service" },
  { term: "Shekel" },
  { term: "Smoke" },
  { term: "Solemn assembly" },
  { term: "Sovereign" },
  { term: "Statute" },
  { term: "Testing" },
  { term: "Wage" },
  { term: "War" },
  { term: "Warfare" },
  { term: "Backsliding" },
  { term: "Blaspheme" },
  { term: "Captive" },
  { term: "Cloud of glory" },
  { term: "Commanding" },
  { term: "Community guilt" },
  { term: "Complaint against leadership" },
  { term: "Courage" },
  { term: "Covenant mercy" },
  { term: "Covering" },
  { term: "Cut off" },
  { term: "Day of rest" },
  { term: "Death sentence" },
  { term: "Dedication" },
  { term: "Desecrate" },
  { term: "Despair" },
  { term: "Discontent" },
  { term: "Dissension" },
  { term: "Divine presence" },
  { term: "Divine wrath" },
  { term: "Doubt" },
  { term: "Earth opening" },
  { term: "Faithlessness" },
  // User-requested additions (deduped) - batch 7
  { term: "Abhor" },
  { term: "Backslide" },
  { term: "Blot out" },
  { term: "Borrow" },
  { term: "Break covenant" },
  { term: "Burn offering" },
  { term: "Care" },
  { term: "Censure" },
  { term: "Circumcise" },
  { term: "Confess" },
  { term: "Deceive" },
  { term: "Declare" },
  { term: "Delight" },
  { term: "Elders" },
  { term: "Enemy" },
  { term: "Gates" },
  { term: "Goodness" },
  { term: "Graven image" },
  { term: "Hear" },
  { term: "Heed" },
  { term: "Keep" },
  { term: "Lend" },
  { term: "Listen" },
  { term: "Long life" },
  { term: "Might" },
  { term: "Overtake" },
  { term: "Prayer" },
  { term: "Priest" },
  { term: "Punish" },
  { term: "Repay" },
  { term: "Restore" },
  { term: "Return" },
  { term: "Rule" },
  { term: "Teach" },
  { term: "Teacher" },
  { term: "Turn" },
  { term: "Uncircumcised" },
  { term: "Allegiance" },
  { term: "Authority of law" },
  { term: "Blessing and curse" },
  { term: "Borrower" },
  { term: "Brotherhood" },
  { term: "Captive woman" },
  { term: "Ceremonial law" },
  { term: "Community" },
  { term: "Compensation" },
  { term: "Compassionate" },
  { term: "Covenant loyalty" },
  { term: "Debt release" },
  { term: "Declaration" },
  { term: "Devour" },
  { term: "Divine law" },
  { term: "Divorce" },
  { term: "Dowry" },
  { term: "False witness" },
  { term: "Flee" },
  { term: "Foreign god" },
  { term: "Foreign nation" },
  { term: "Foreign wife" },
  { term: "Free" },
  { term: "Generosity" },
  { term: "Glean" },
  { term: "Guiltless" },
  { term: "Hate" },
  { term: "Hear O Israel" },
  { term: "Help" },
  { term: "Idolater" },
  { term: "Jealous" },
  { term: "Judge rightly" },
  { term: "Justice system" },
  { term: "Kindness to stranger" },
  { term: "Kingship" },
  { term: "Land inheritance" },
  { term: "Liberation" },
  { term: "Life and death" },
  { term: "Listening" },
  { term: "Migration" },
  { term: "Pardon" },
  { term: "Preserve" },
  { term: "Pure" },
  { term: "Refusal" },
  { term: "Reign" },
  { term: "Remember" },
  { term: "Renew" },
  { term: "Repayment" },
  { term: "Responsibility" },
  { term: "Retribution" },
  { term: "Sacred assembly" },
  { term: "Sacred offering" },
  { term: "Serve" },
  { term: "Shelter" },
  { term: "Sign" },
  { term: "Stone" },
  { term: "Substitute" },
  { term: "Thankfulness" },
  { term: "Tithe year" },
  { term: "Tradition" },
  { term: "Treasure people" },
  { term: "Trustworthy" },
  { term: "Unjust" },
  { term: "Voluntary" },
  { term: "Waiting" },
  { term: "Weak" },
  { term: "Widow care" },
  { term: "Year of release" },
  { term: "Blessing of obedience" },
  { term: "Breaking covenant" },
  { term: "Covenant stipulation" },
  { term: "Covenant witness" },
  { term: "Curse of disobedience" },
  { term: "Day of assembly" },
  { term: "Devoted thing" },
  { term: "Divine justice" },
  { term: "Divine mercy" },
  { term: "Everlasting covenant" },
  { term: "Generational blessing" },
  { term: "Generational curse" },
  { term: "Holy nation" },
  { term: "Household law" },
  { term: "Inheritance right" },
  { term: "Justice for poor" },
  { term: "Law of the king" },
  { term: "Law of the priest" },
  { term: "Law of witness" },
  { term: "Life command" },
  { term: "Moral law" },
  { term: "National covenant" },
  { term: "Obedient heart" },
  { term: "Public reading" },
  { term: "Royal law" },
  { term: "Sanctuary law" },
  { term: "Shema" },
  { term: "Social justice" },
  { term: "Statutory law" },
  { term: "Stern warning" },
  { term: "Temple worship" },
  { term: "Test of loyalty" },
  { term: "The Lord your God" },
  { term: "Whole heart" },
  { term: "Whole soul" },
  { term: "False report" },
  { term: "Fellowship" },
  { term: "Fire from the Lord" },
  { term: "Flock" },
  { term: "Forgiving" },
  { term: "Gathering" },
  { term: "Glorify" },
  { term: "Gratitude" },
  { term: "Hardness of heart" },
  { term: "Healing serpent" },
  { term: "Honor leadership" },
  { term: "Humility" },
  { term: "Impatience" },
  { term: "Intercessory prayer" },
  { term: "Jealous spirit" },
  { term: "Judicial" },
  { term: "Lifting hands" },
  { term: "Long suffering" },
  { term: "Mediation" },
  { term: "Meekness" },
  { term: "Memorial offering" },
  { term: "Mighty works" },
  { term: "Murmuring spirit" },
  { term: "Obligation" },
  { term: "Obey" },
  { term: "Opposition" },
  { term: "Overcome" },
  { term: "Perpetual" },
  { term: "Pilgrimage" },
  { term: "Possess" },
  { term: "Presence" },
  { term: "Presumptuous sin" },
  { term: "Protection" },
  { term: "Provision" },
  { term: "Refinement" },
  { term: "Resistance" },
  { term: "Restoration" },
  { term: "Reverent fear" },
  { term: "Sacred duty" },
  { term: "Sacred service" },
  { term: "Sacred space" },
  { term: "Sanctified" },
  { term: "Separation" },
  { term: "Set apart" },
  { term: "Signal" },
  { term: "Solemn oath" },
  { term: "Tabernacle service" },
  { term: "Tempt" },
  { term: "Terror" },
  { term: "Thank offering" },
  { term: "Unbelief" },
  { term: "Unfaithful" },
  { term: "Unity" },
  { term: "Unlawful" },
  { term: "Unrest" },
  { term: "Victory" },
  { term: "Wandering" },
  { term: "Weakness" },
  { term: "Whispering" },
  { term: "Wonder" },
  { term: "Year of wandering" },
  { term: "Atonement money" },
  { term: "Atonement ritual" },
  { term: "Burning incense" },
  { term: "Cleansing water" },
  { term: "Communal offering" },
  { term: "Dedication offering" },
  { term: "Evening offering" },
  { term: "First generation" },
  { term: "First census" },
  { term: "Freewill vow" },
  { term: "Guilt payment" },
  { term: "Heave portion" },
  { term: "Holy incense" },
  { term: "Holy portion" },
  { term: "Holy ritual" },
  { term: "Holy trumpet" },
  { term: "Levite duty" },
  { term: "Life blood" },
  { term: "Morning offering" },
  { term: "Offerer" },
  { term: "Offering by fire" },
  { term: "Priestly blessing" },
  { term: "Purification water" },
  { term: "Red heifer" },
  { term: "Sacred inheritance" },
  { term: "Sacred tent" },
  { term: "Sanctuary veil" },
  { term: "Second generation" },
  { term: "Separation vow" },
  { term: "Silver trumpets" },
  { term: "Sin of rebellion" },
  { term: "Solemn feast" },
  { term: "Spirit of jealousy" },
  { term: "Sprinkled blood" },
  { term: "Tabernacle court" },
  { term: "Temple service" },
  { term: "Tenth portion" },
  { term: "Trumpet blast" },
  { term: "Unintentional sin" },
  { term: "Water from rock" },
  { term: "Wave offering" },
  { term: "Foolish" },
  { term: "Fountain" },
  { term: "Friend" },
  { term: "Fruit" },
  { term: "Gain" },
  { term: "Garland" },
  { term: "Generations" },
  { term: "Generous" },
  { term: "Glutton" },
  { term: "Gossip" },
  { term: "Gracious" },
  { term: "Greedy" },
  { term: "Grief" },
  { term: "Guidance" },
  { term: "Guile" },
  { term: "Harsh" },
  { term: "Heart" },
  { term: "Highway" },
  { term: "Holy" },
  { term: "Honor" },
  { term: "Hope" },
  { term: "House" },
  { term: "Humble" },
  { term: "Humiliation" },
  { term: "Increase" },
  { term: "Indolence" },
  { term: "Insight" },
  { term: "Integrity" },
  { term: "Joy" },
  { term: "Justice" },
  { term: "Kind" },
  { term: "Kindness" },
  { term: "Knowledge" },
  { term: "Lack" },
  { term: "Lamp" },
  { term: "Law" },
  { term: "Learning" },
  { term: "Life" },
  { term: "Light" },
  { term: "Lips" },
  { term: "Longing" },
  { term: "Loss" },
  { term: "Lot" },
  { term: "Lovingkindness" },
  { term: "Lying" },
  { term: "Meek" },
  { term: "Mind" },
  { term: "Mockery" },
  { term: "Mother" },
  { term: "Mouth" },
  { term: "Naive" },
  { term: "Neighbor" },
  { term: "Net" },
  { term: "Offspring" },
  { term: "Oil" },
  { term: "Oppression" },
  { term: "Partiality" },
  { term: "Path" },
  { term: "Patience" },
  { term: "Peace" },
  { term: "Perverse" },
  { term: "Perversity" },
  { term: "Pledge" },
  { term: "Planning" },
  { term: "Poor" },
  { term: "Poverty" },
  { term: "Precept" },
  { term: "Preparation" },
  { term: "Profit" },
  { term: "Promise" },
  { term: "Prosperity" },
  { term: "Prudence" },
  { term: "Punishment" },
  { term: "Quarrel" },
  { term: "Recompense" },
  { term: "Rich" },
  { term: "Riches" },
  { term: "Righteous" },
  { term: "Road" },
  { term: "Ruin" },
  { term: "Scoffer" },
  { term: "Scorner" },
  { term: "Seduction" },
  { term: "Self-Control" },
  { term: "Sensual" },
  { term: "Shield" },
  { term: "Shame" },
  { term: "Simple" },
  { term: "Sin" },
  { term: "Sluggard" },
  { term: "Smooth" },
  { term: "Snare" },
  { term: "Sorrow" },
  { term: "Soul" },
  { term: "Speech" },
  { term: "Spirit" },
  { term: "Steps" },
  { term: "Storehouse" },
  { term: "Strong Tower" },
  { term: "Stubborn" },
  { term: "Surety" },
  { term: "Talebearer" },
  { term: "Teaching" },
  { term: "Temperate" },
  { term: "Toil" },
  { term: "Tongue" },
  { term: "Trap" },
  { term: "Treacherous" },
  { term: "Treasure" },
  { term: "Truth" },
  { term: "Uprightness" },
  { term: "Vain" },
  { term: "Verdict" },
  { term: "Violence" },
  { term: "Vine" },
  { term: "Walk" },
  { term: "Way" },
  { term: "Wealth" },
  { term: "Weights" },
  { term: "Wicked" },
  { term: "Wickedness" },
  { term: "Wife" },
  { term: "Word" },
  { term: "Forsake" },
  { term: "Acceptance" },
  { term: "Admonition" },
  { term: "Adulterer" },
  { term: "Adversity" },
  { term: "Agony" },
  { term: "Arrogance" },
  { term: "Authority" },
  { term: "Banquet" },
  { term: "Better" },
  { term: "Blindness" },
  { term: "Bloodshed" },
  { term: "Boldness" },
  { term: "Boast" },
  { term: "Body" },
  { term: "Boundary" },
  { term: "Brother" },
  { term: "Burden" },
  { term: "Careless" },
  { term: "Chamber" },
  { term: "Character" },
  { term: "Choice" },
  { term: "City" },
  { term: "Clarity" },
  { term: "Clever" },
  { term: "Collapse" },
  { term: "Comfort" },
  { term: "Compassion" },
  { term: "Complaint" },
  { term: "Conflict" },
  { term: "Confusion" },
  { term: "Conscience" },
  { term: "Consequence" },
  { term: "Control" },
  { term: "Covetousness" },
  { term: "Crafty" },
  { term: "Creditor" },
  { term: "Crime" },
  { term: "Cruel" },
  { term: "Damage" },
  { term: "Danger" },
  { term: "Day" },
  { term: "Decision" },
  { term: "Defense" },
  { term: "Delay" },
  { term: "Device" },
  { term: "Discretion" },
  { term: "Disgrace" },
  { term: "Dishonor" },
  { term: "Dispute" },
  { term: "Division" },
  { term: "Door" },
  { term: "Dream" },
  { term: "Duty" },
  { term: "Earth" },
  { term: "Escape" },
  { term: "Establish" },
  { term: "Eternity" },
  { term: "Example" },
  { term: "Examination" },
  { term: "Excellence" },
  { term: "Excuse" },
  { term: "Failure" },
  { term: "Favor" },
  { term: "Flattery" },
  { term: "Flesh" },
  { term: "Food" },
  { term: "Form" },
  { term: "Future" },
  { term: "Generation" },
  { term: "Gift" },
  { term: "Gladness" },
  { term: "Good" },
  { term: "Greed" },
  { term: "Habit" },
  { term: "Hand" },
  { term: "Hardship" },
  { term: "Harm" },
  { term: "Hatred" },
  { term: "Hunger" },
  { term: "Hypocrisy" },
  { term: "Ignorance" },
  { term: "Impulse" },
  { term: "Incline" },
  { term: "Innocent" },
  { term: "Intelligence" },
  { term: "King" },
  { term: "Labor" },
  { term: "Lazy" },
  { term: "Leadership" },
  { term: "Length" },
  { term: "Limit" },
  { term: "Love" },
  { term: "Loyalty" },
  { term: "Madness" },
  { term: "Malice" },
  { term: "Master" },
  { term: "Memory" },
  { term: "Misery" },
  { term: "Money" },
  { term: "Night" },
  { term: "Nourishment" },
  { term: "Offense" },
  { term: "Opportunity" },
  { term: "Outcome" },
  { term: "Overflow" },
  { term: "Pain" },
  { term: "Penalty" },
  { term: "Peril" },
  { term: "Pleasure" },
  { term: "Plot" },
  { term: "Praise" },
  { term: "Pride" },
  { term: "Purpose" },
  { term: "Quiet" },
  { term: "Rage" },
  { term: "Rebellion" },
  { term: "Regret" },
  { term: "Rejoice" },
  { term: "Reputation" },
  { term: "Request" },
  { term: "Respect" },
  { term: "Restraint" },
  { term: "Risk" },
  { term: "Safety" },
  { term: "Scheme" },
  { term: "Secret" },
  { term: "Security" },
  { term: "Selfish" },
  { term: "Sense" },
  { term: "Servant" },
  { term: "Shadow" },
  { term: "Silence" },
  { term: "Stability" },
  { term: "Step" },
  { term: "Strength" },
  { term: "Success" },
  { term: "Support" },
  { term: "Temper" },
  { term: "Temptation" },
  { term: "Test" },
  { term: "Thought" },
  { term: "Threat" },
  { term: "Time" },
  { term: "Torment" },
  { term: "Trade" },
  { term: "Trouble" },
  { term: "Trust" },
  { term: "Vanity" },
  { term: "Vision" },
  { term: "Voice" },
  { term: "Will" },
  { term: "Work" },
  { term: "Youth" },
  // User-requested additions (deduped) - batch 8, 2026-02-17
  { term: "Appoint" },
  { term: "Armed" },
  { term: "Army" },
  { term: "Assign" },
  { term: "Bravery" },
  { term: "Brethren" },
  { term: "Captain" },
  { term: "Cast lots" },
  { term: "City gate" },
  { term: "Conquer" },
  { term: "Conquest" },
  { term: "Defeat" },
  { term: "Dispossess" },
  { term: "Exterminate" },
  { term: "Fall" },
  { term: "Fierce" },
  { term: "Fight" },
  { term: "Fortified" },
  { term: "Fury" },
  { term: "Good courage" },
  { term: "Grasp" },
  { term: "Haste" },
  { term: "Heritage portion" },
  { term: "Inherit" },
  { term: "Mighty" },
  { term: "Pursue" },
  { term: "Put to death" },
  { term: "Remain" },
  { term: "Slay" },
  { term: "Spoil" },
  { term: "Summon" },
  { term: "Swear" },
  { term: "Sword" },
  { term: "Take possession" },
  { term: "Valiant" },
  { term: "Advance" },
  { term: "Alarm" },
  { term: "Ambush strategy" },
  { term: "Annihilate" },
  { term: "Appointment" },
  { term: "Army division" },
  { term: "Assign inheritance" },
  { term: "Battle plan" },
  { term: "Blazing" },
  { term: "Blockade" },
  { term: "Bold" },
  { term: "Bravery in battle" },
  { term: "Break through" },
  { term: "Burn with fire" },
  { term: "Camp order" },
  { term: "Campaign" },
  { term: "Charge forward" },
  { term: "City wall" },
  { term: "Clash" },
  { term: "Officer" },
  { term: "Commanding officer" },
  // User-requested additions (auto-generated basics from multi-word entries) - 2026-02-17
  { term: "Bosom" },
  { term: "Language" },
  { term: "Come" },
  { term: "Days" },
  { term: "Lord" },
  { term: "Bearer" },
  { term: "God" },
  { term: "Cover" },
  { term: "Fire" },
  { term: "Line" },
  { term: "Ram" },
  { term: "Prey" },
  { term: "Avenger" },
  { term: "Ritual" },
  { term: "Again" },
  { term: "Down" },
  { term: "Breaking" },
  { term: "Driver" },
  { term: "Corps" },
  { term: "Baker" },
  { term: "Cupbearer" },
  { term: "Israel" },
  { term: "One" },
  { term: "Fortifications" },
  { term: "Witnesses" },
  { term: "Status" },
  { term: "Fifties" },
  { term: "Thousands" },
  { term: "Imagery" },
  { term: "Renewal" },
  { term: "Thorns" },
  { term: "Pattern" },
  { term: "Prison" },
  { term: "Purchase" },
  { term: "Practices" },
  { term: "Interpreter" },
  { term: "Gate" },
  { term: "Times" },
  { term: "Motif" },
  { term: "Eye" },
  { term: "Face" },
  { term: "Booths" },
  { term: "Tabernacles" },
  { term: "Trumpets" },
  { term: "Weeks" },
  { term: "Ownership" },
  { term: "Washing" },
  { term: "Magog" },
  { term: "Commission" },
  { term: "Right" },
  { term: "Share" },
  { term: "Holies" },
  { term: "Culture" },
  { term: "Code" },
  { term: "Manager" },
  { term: "Allotment" },
  { term: "Rights" },
  { term: "Seat" },
  { term: "Supper" },
  { term: "Waste" },
  { term: "Moses" },
  { term: "Scroll" },
  { term: "World" },
  { term: "Horn" },
  { term: "Judah" },
  { term: "Den" },
  { term: "Water" },
  { term: "Swarm" },
  { term: "Hosts" },
  { term: "Egypt" },
  { term: "Herald" },
  { term: "Age" },
  { term: "Expectation" },
  { term: "Changer" },
  { term: "Place" },
  { term: "Birth" },
  { term: "Token" },
  { term: "Branch" },
  { term: "Court" },
  { term: "Saints" },
  { term: "Cloak" },
  { term: "Slave" },
  { term: "Garments" },
  { term: "Hyperbole" },
  { term: "Act" },
  { term: "Payment" },
  { term: "Clause" },
  { term: "Document" },
  { term: "Price" },
  { term: "Theology" },
  { term: "Advisor" },
  { term: "Impression" },
  { term: "Coming" },
  { term: "Wall" },
  { term: "Ring" },
  { term: "David" },
  { term: "Man" },
  { term: "Action" },
  { term: "Numbers" },
  { term: "Showbread" },
  { term: "Collector" },
  { term: "Treasury" },
  { term: "Meeting" },
  { term: "Floor" },
  { term: "Ox" },
  { term: "Sledge" },
  { term: "Goods" },
  { term: "Thummim" },
  { term: "Fork" },
  { term: "East" },
  { term: "mגדּdon" },
  { term: "Thhing" },
  { term: "Waters" },
  { term: "System" },
  { term: "Necked" },
  { term: "Thing" },
  { term: "Convocation" },
  { term: "Moon" },
  { term: "Laws" },
  { term: "Furnishings" },
  { term: "Tax" },
  { term: "Linen" },
  { term: "off" },
  { term: "opening" },
  { term: "out" },
  { term: "image" },
  { term: "year" },
  { term: "apart" },
  { term: "reading" },
  { term: "report" },
  { term: "hands" },
  { term: "space" },
  { term: "ritual" },
  { term: "payment" },
  { term: "rock" },
  { term: "Tower" },
  { term: "strategy" },
  { term: "plan" },
  { term: "through" },
  { term: "order" },
  { term: "over" },
  { term: "down" },
  { term: "before" },
  { term: "men" },
  { term: "troops" },
  { term: "strengthened" },
  { term: "treaty" },
  { term: "ban" },
  { term: "stones" },
  { term: "horn" },
  { term: "firm" },
  { term: "courageous" },
  { term: "land" },
  { term: "back" },
  { term: "cry" },
  { term: "fulfilled" },
  { term: "still" },
  { term: "Complete destruction" },
  { term: "Conquest campaign" },
  { term: "Cross over" },
  { term: "Cut down" },
  { term: "Defensive" },
  { term: "Destroy utterly" },
  { term: "Devoted to destruction" },
  { term: "Distribute" },
  { term: "Drive out" },
  { term: "Encourage" },
  { term: "Encouragement" },
  { term: "Enlarge" },
  { term: "Entrust" },
  { term: "Expel" },
  { term: "Fall before" },
  { term: "Fighting men" },
  { term: "Fortify" },
  { term: "Gather troops" },
  { term: "Give over" },
  { term: "Hand over" },
  { term: "Head" },
  { term: "Heart strengthened" },
  { term: "Honor covenant" },
  { term: "Inheritance boundary" },
  { term: "Inheritance division" },
  { term: "Keep covenant" },
  { term: "Keep law" },
  { term: "Land division" },
  { term: "Land promise" },
  { term: "Lineage" },
  { term: "Loyal" },
  { term: "Military" },
  { term: "Military order" },
  { term: "Military strength" },
  { term: "Obedient" },
  { term: "Overthrow enemy" },
  { term: "Pass through" },
  { term: "Peace treaty" },
  { term: "Persist" },
  { term: "Possession right" },
  { term: "Prepare" },
  { term: "Priestly service" },
  { term: "Pursuit" },
  { term: "Put under ban" },
  { term: "Rebel" },
  { term: "Reinforce" },
  { term: "Remain faithful" },
  { term: "Renew covenant" },
  { term: "Rest from war" },
  { term: "Return to camp" },
  { term: "Rout" },
  { term: "Rule over" },
  { term: "Seize" },
  { term: "Set up stones" },
  { term: "Settlement" },
  { term: "Shout" },
  { term: "Show mercy" },
  { term: "Signal horn" },
  { term: "Stand firm" },
  { term: "Strong" },
  { term: "Strong and courageous" },
  { term: "Submit" },
  { term: "Take courage" },
  { term: "Take land" },
  { term: "Take spoil" },
  { term: "Take the city" },
  { term: "Test loyalty" },
  { term: "Territory" },
  { term: "Triumph" },
  { term: "Turn back" },
  { term: "Victory cry" },
  { term: "War cry" },
  { term: "Warrior spirit" },
  { term: "Covenant oath" },
  { term: "Covenant sign" },
  { term: "Covenant stone" },
  { term: "Divine command" },
  { term: "Divine promise" },
  { term: "Divine strength" },
  { term: "Encamp before" },
  { term: "Faith in promise" },
  { term: "Fulfill" },
  { term: "Fulfillment" },
  { term: "Generational promise" },
  { term: "Holy war" },
  { term: "Justice of God" },
  { term: "Keep charge" },
  { term: "Mighty act" },
  { term: "Overcome fear" },
  { term: "Possession of land" },
  { term: "Promise fulfilled" },
  { term: "Remembrance stones" },
  { term: "Sacred oath" },
  { term: "Serve the Lord" },
  { term: "Settlement promise" },
  { term: "Stand still" },
  { term: "Stone memorial" },
  { term: "Trust in the Lord" },
  { term: "Victory through obedience" },
  { term: "Witness stone" },
];

const ADDITIONAL_USER_REQUESTED_KEYWORDS: string[] = [
  "Abyss",
  "Adorn",
  "Altar of Burnt Offering",
  "Ambassador",
  "Backsliding",
  "Basin",
  "Book of the Covenant",
  "Breastpiece",
  "Burning Bush",
  "Calf",
  "Camp",
  "Chain",
  "Consumed",
  "Craft",
  "Craftsman",
  "Destroyer",
  "Divine",
  "Earthquake",
  // Judges nuclear-mode update (2026-02-17)
  "abandon",
  "abandoned",
  "abduction",
  "abhor",
  "abomination",
  "accuse",
  "adultery",
  "adversary",
  "afflict",
  "affliction",
  "alliance",
  "altar",
  "ambush",
  "anger",
  "anoint",
  "apostasy",
  "armor",
  "armed",
  "army",
  "assembly",
  "avenge",
  "avenger",
  "axe",
  "backsliding",
  "ban",
  "banished",
  "battle",
  "betray",
  "betrayal",
  "blessing",
  "blind",
  "blood",
  "boast",
  "bondage",
  "boundary",
  "bow",
  "bravery",
  "bribe",
  "burning",
  "burnt offering",
  "calf",
  "camp",
  "captain",
  "captivity",
  "capture",
  "carved image",
  "cast down",
  "cattle",
  "cave",
  "charge",
  "chariot",
  "child sacrifice",
  "choose",
  "city gate",
  "clan",
  "command",
  "commitment",
  "compassion",
  "conquer",
  "conquest",
  "consecrate",
  "counsel",
  "covenant",
  "cry out",
  "curse",
  "cut down",
  "dagger",
  "darkness",
  "death",
  "deceit",
  "declare",
  "deliver",
  "deliverance",
  "destroy",
  "devastation",
  "devotion",
  "disobedience",
  "disperse",
  "divide",
  "division",
  "dread",
  "drive out",
  "dwell",
  "eagle",
  "earth",
  "elders",
  "enemy",
  "enslave",
  "entice",
  "escape",
  "evil",
  "faithless",
  "fall",
  "family",
  "famine",
  "father’s house",
  "fear",
  "feast",
  "field",
  "fight",
  "fire",
  "flame",
  "flee",
  "flesh",
  "follow",
  "forgive",
  "forsake",
  "fortress",
  "freedom",
  "fruitful",
  "gather",
  "generation",
  "gift",
  "glory",
  "govern",
  "grace",
  "grind",
  "groan",
  "guilt",
  "hand",
  "hardness",
  "harvest",
  "hatred",
  "heart",
  "heritage",
  "hidden",
  "hill country",
  "holy",
  "honor",
  "household",
  "humble",
  "idol",
  "idolatry",
  "image",
  "inherit",
  "inheritance",
  "iniquity",
  "innocent",
  "insult",
  "intercede",
  "iron",
  "judge",
  "judgment",
  "justice",
  "keep",
  "kingdom",
  "kinsman",
  "knife",
  "labor",
  "lament",
  "law",
  "lead",
  "leader",
  "levy",
  "lie in wait",
  "life",
  "light",
  "loyalty",
  "lust",
  "mighty",
  "military",
  "mock",
  "mountain pass",
  "nation",
  "neighbor",
  "net",
  "night",
  "oath",
  "obedience",
  "offense",
  "offering",
  "oppress",
  "oppression",
  "order",
  "overthrow",
  "pagan",
  "peace",
  "people",
  "perish",
  "persecution",
  "pillage",
  "plunder",
  "possession",
  "power",
  "pray",
  "priesthood",
  "provoke",
  "pursue",
  "rage",
  "raise up",
  "rebellion",
  "redeem",
  "refuge",
  "reign",
  "repent",
  "rest",
  "return",
  "revenge",
  "righteous",
  "righteousness",
  "rob",
  "rule",
  "sacrifice",
  "sanctuary",
  "save",
  "secret",
  "seek",
  "seize",
  "serve",
  "servitude",
  "shame",
  "shepherd",
  "shield",
  "shout",
  "silence",
  "sin",
  "sister",
  "slay",
  "slavery",
  "sling",
  "smite",
  "snare",
  "soldier",
  "son",
  "song",
  "spear",
  "spirit",
  "spoils",
  "strength",
  "stronghold",
  "strike",
  "subdue",
  "submit",
  "suffer",
  "sword",
  "tabernacle",
  "tear down",
  "tent",
  "territory",
  "test",
  "throne",
  "tribe",
  "trouble",
  "trust",
  "tumult",
  "turn away",
  "unclean",
  "vengeance",
  "victory",
  "village",
  "violence",
  "vow",
  "war",
  "warrior",
  "weep",
  "wicked",
  "wilderness",
  "wisdom",
  "worship",
  "wrath",
  "yoke",
  "Elders",
  "Enslave",
  "Enslavement",
  "Feast",
  "Flee",
  "Freedom",
  "Fury",
  "Glorify",
  "Graven Image",
  "Grumble",
  "Grumbling",
  "Hand of God",
  "Hardness",
  "Healing",
  "Holy Ground",
  "Impurity",
  "Leader",
  "Liberate",
  "Liberation",
  "Linen",
  "Locust",
  "Mantle",
  "Marvel",
  "Memorial",
  "Midnight",
  "Mighty Hand",
  "Murmur",
  "Murmuring",
  "Overcome",
  "Overthrow",
  "Pillar of Cloud",
  "Pillar of Fire",
  "Polished",
  "Priest",
  "Rebel",
  "Refine",
  "Refiner",
  "Release",
  "Remembrance",
  "Rest",
  "Reverence",
  "Sanctuary",
  "Shekel",
  "Sign",
  "Slavery",
  "Smoke",
  "Solemn",
  "Statute",
  "Stone Tablets",
  "Testing",
  "Thunder",
  "Treasury",
  "Vestment",
  "Victory",
  "Wages",
  "Wandering",
  "Water",
  "Wave Offering",
  "Whirlwind",
  "Wonder",
  "Workmanship",
  "Zealous",
  "Ancestral",
  "Captain",
  "Cloud of Glory",
  "Completion",
  "Courage",
  "Craftsmanship",
  "Crush",
  "Despair",
  "Drought",
  "Dwelling Place",
  "Fellowship",
  "Fire",
  "Flame",
  "Glorious",
  "Hearing",
  "Helper",
  "Inheritance Right",
  "Jealous",
  "Lawsuit",
  "Majesty",
  "Obligation",
  "Obey",
  "Patriarchal",
  "Powerful",
  "Prayer",
  "Presence",
  "Protect",
  "Refusal",
  "Restoration",
  "Reveal",
  "Servitude",
  "Sovereign",
  "Splendor",
  "Substitute",
  "Tabernacle Veil",
  "Terror",
  "Unbelief",
  "Unfaithful",
  "Unity",
  "Victory Song",
  "Visitation",
  "Waiting",
  "Wash",
  "Weakness",
  "Wonderworking",
  "Year of Freedom",
];

const RITUAL_PURITY_KEYWORDS: string[] = [
  "Acceptable",
  "Atoning",
  "Atonement money",
  "Atonement ritual",
  "Body discharge",
  "Boil",
  "Bond",
  "Burning sacrifice",
  "Candle",
  "Ceremonial",
  "Ceremonial uncleanness",
  "Cloven hoof",
  "Consecrated",
  "Contamination",
  "Dedicate",
  "Discharge",
  "Disease",
  "Distinction",
  "Dove",
  "Drink offering",
  "Eighth day",
  "Fat",
  "Fellowship offering",
  "Festal",
  "Fire offering",
  "Forbidden",
  "Freewill offering",
  "Fringe",
  "Germ",
  "Glean",
  "Gleaming",
  "Heave offering",
  "Holy offering",
  "Holy portion",
  "Holy priesthood",
  "Issue",
  "Leprous",
  "Lump",
  "Meat offering",
  "Mildew",
  "Ministration",
  "Minister",
  "Midwife",
  "Mold",
  "Monthly feast",
  "Mourning",
  "New grain",
  "Peace offering",
  "Priestly",
  "Sabbath year",
  "Scroll",
  "Sermon",
  "Sheaf",
  "Solemn assembly",
  "Solemn rest",
  "Sprinkle",
  "Sprinkling",
  "Stone",
  "Tassel",
  "Tithing",
  "Trespass",
  "Trespass offering",
  "Uncleanness",
  "Anointed",
  "Ash",
  "Atonement blood",
  "Burning incense",
  "Burning of fat",
  "Burning outside the camp",
  "Cedarwood",
  "Ceremonial law",
  "Cleansed",
  "Cleansing water",
  "Communion",
  "Confess sin",
  "Contagion",
  "Cutting off",
  "Day of rest",
  "Dedicated",
  "Desecrate",
  "Divided hoof",
  "Epidemic",
  "Exclusion",
  "Excrement",
  "Fat portions",
  "Freewill",
  "Fragrance",
  "Frost",
  "Goat",
  "Harvest feast",
  "Holy fire",
  "Holy season",
  "Holy year",
  "Hyssop",
  "Incense altar",
  "Infection",
  "Infestation",
  "Injustice",
  "Inner sanctuary",
  "Judicial",
  "Justice law",
  "Male goat",
  "Measuring",
  "Memorial portion",
  "Molten image",
  "Monthly offering",
  "Mold infection",
  "Morning offering",
  "Nazirite vow",
  "Night offering",
  "Oblation",
  "Oil of anointing",
  "Perpetual",
  "Pilgrim feast",
  "Possess",
  "Presentation",
  "Priestly garment",
  "Profanation",
  "Public sin",
  "Ransom price",
  "Red heifer",
  "Reverent",
  "Sacrificial blood",
  "Sanctified",
  "Scalp infection",
  "Scaly disease",
  "Separation offering",
  "Sinful",
  "Solemn day",
  "Solemn feast",
  "Sprinkled blood",
  "Statutory",
  "Strain",
  "Tabernacle court",
  "Tabernacle service",
  "Tassels",
  "Temple service",
  "Thanksgiving offering",
  "Trespass guilt",
  "Unblemished",
  "Uncovered",
  "Votive",
  "Wash basin",
  "Yearly atonement",
  "Animal sacrifice",
  "Atonement day",
  "Atonement ritual blood",
  "Burnt sacrifice",
  "Ceremonial purity",
  "Clean animal",
  "Cleansing ritual",
  "Community guilt",
  "Defiled",
  "Divine command",
  "Evening offering",
  "Fellowship meal",
  "Guilt payment",
  "Holy altar",
  "Holy garment",
  "Holy sacrifice",
  "Holy worship",
  "Impure",
  "Impurity ritual",
  "Inner court",
  "Levitical code",
  "Life blood",
  "Living sacrifice",
  "Offer sacrifice",
  "Offerer",
  "Offering ritual",
  "Purification ritual",
  "Sacred assembly",
  "Sacred bread",
  "Sacred incense",
  "Sacred oil",
  "Sacred statute",
  "Sacrificial animal",
  "Sacrificial fire",
  "Sacrificial law",
  "Sacrificial ritual",
  "Sanctuary veil",
  "Seasonal feast",
  "Solemn convocation",
  "Temple altar",
  "Temple incense",
  "Temple ritual",
  "Temple veil",
  "Thank offering",
  "Unclean animal",
  "Unclean food",
  "Unclean person",
  "Unclean thing",
  "Uncleanliness",
  "Washing ritual",
  "Year of release",
];

export const BIBLE_KEYWORDS_LIST: BibleKeywordEntry[] = dedupeKeywordEntries([
  ...BASE_BIBLE_KEYWORDS_LIST,
  ...USER_REQUESTED_KEYWORDS.map((term) => ({ term })),
  ...ADDITIONAL_USER_REQUESTED_KEYWORDS.map((term) => ({ term })),
  ...RITUAL_PURITY_KEYWORDS.map((term) => ({ term })),
]);
