// Ruth integration (2026-02-17) -- moved to BIBLE_PLACES_LIST array below
/**
 * Comprehensive list of biblical places (~1,800-2,000 locations)
 * 
 * Each place appears once.
 * All places are explicitly named or clearly described in Scripture (OT or NT).
 * Alphabetized by name.
 * 
 * Includes: cities, towns, regions, territories, empires, nations, mountains, hills,
 * valleys, rivers, seas, wells, deserts, wilderness areas, palaces, houses, temples,
 * altars, tents, tabernacle structures, gates, roads, fields, caves, sacred locations,
 * and political/functional locations named in Scripture.
 */

export type BiblePlaceEntry = {
  name: string;
};

export const BIBLE_PLACES_LIST: BiblePlaceEntry[] = [
  // Ruth integration (2026-02-17)
  { name: "Bethlehem Ephrathah" },
  { name: "country of Moab" },
  { name: "field" },
  { name: "fields of Boaz" },
  { name: "fields of Bethlehem" },
  { name: "gate" },
  { name: "gate of Bethlehem" },
  { name: "house of Elimelech" },
  { name: "household" },
  { name: "land of Judah" },
  { name: "threshing floor" },
  { name: "town" },
  // A
  { name: "Abana" },
  { name: "Abarim" },
  { name: "Abdon" },
  { name: "Abel" },
  { name: "Abel-Beth-Maachah" },
  { name: "Abel-Carmel" },
  { name: "Abel-Keramim" },
  { name: "Abel-Meholah" },
  { name: "Abel-Mizraim" },
  { name: "Abel-Shittim" },
  { name: "Abila" },
  { name: "Abit" },
  { name: "Abronah" },
  { name: "Accad" },
  { name: "Achmetha" },
  { name: "Achor" },
  { name: "Achshaph" },
  { name: "Achzib" },
  { name: "Adadah" },
  { name: "Adam" },
  { name: "Adami" },
  { name: "Adar" },
  { name: "Adasa" },
  { name: "Addar" },
  { name: "Adithaim" },
  { name: "Admah" },
  { name: "Adoraim" },
  { name: "Adullam" },
  { name: "Aenon" },
  { name: "Ai" },
  { name: "Aijalon" },
  { name: "Ain" },
  { name: "Akkad" },
  { name: "Allammelech" },
  { name: "Allon" },
  { name: "Almon" },
  { name: "Almon-Diblathaim" },
  { name: "Aloth" },
  { name: "Altar" },
  { name: "Amad" },
  { name: "Amalek" },
  { name: "Amanah" },
  { name: "Amathus" },
  { name: "Amaziah" },
  { name: "Ammon" },
  { name: "Ammah" },
  { name: "Amphipolis" },
  { name: "Anab" },
  { name: "Anaharath" },
  { name: "Anathoth" },
  { name: "Anem" },
  { name: "Anim" },
  { name: "Antioch" },
  { name: "Antioch of Pisidia" },
  { name: "Antipatris" },
  { name: "Aphek" },
  { name: "Apollonia" },
  { name: "Arab" },
  { name: "Arabah" },
  { name: "Arad" },
  { name: "Aram" },
  { name: "Aram-Naharaim" },
  { name: "Aram-Zobah" },
  { name: "Ararat" },
  { name: "Arba" },
  { name: "Arbela" },
  { name: "Arcer" },
  { name: "Arimathea" },
  { name: "Aroer" },
  { name: "Arpad" },
  { name: "Aruboth" },
  { name: "Arumah" },
  { name: "Arvad" },
  { name: "Ashan" },
  { name: "Ashdod" },
  { name: "Asher" },
  { name: "Ashkelon" },
  { name: "Ashnah" },
  { name: "Ashtaroth" },
  { name: "Ashur" },
  { name: "Asia" },
  { name: "Askalon" },
  { name: "Asshur" },
  { name: "Assyria" },
  { name: "Ataroth" },
  { name: "Ataroth-Addar" },
  { name: "Atergatis" },
  { name: "Athens" },
  { name: "Attalia" },
  { name: "Avaris" },
  { name: "Avim" },
  { name: "Avith" },
  { name: "Azal" },
  { name: "Azekah" },
  { name: "Aznoth-Tabor" },
  { name: "Azotus" },
  { name: "Azzah" },
  { name: "Azzan" },

  // B
  { name: "Baal" },
  { name: "Baal-Gad" },
  { name: "Baal-Hamon" },
  { name: "Baal-Hazor" },
  { name: "Baal-Meon" },
  { name: "Baal-Peor" },
  { name: "Baal-Perazim" },
  { name: "Baal-Shalishah" },
  { name: "Baal-Tamar" },
  { name: "Baalath" },
  { name: "Baalath-Beer" },
  { name: "Babel" },
  { name: "Babylon" },
  { name: "Baca" },
  { name: "Bachrites" },
  { name: "Bahurim" },
  { name: "Balah" },
  { name: "Bamah" },
  { name: "Bamoth" },
  { name: "Bamoth-Baal" },
  { name: "Bashan" },
  { name: "Bath" },
  { name: "Bealoth" },
  { name: "Beer" },
  { name: "Beer-Elim" },
  { name: "Beer-Lahai-Roi" },
  { name: "Beer-Sheba" },
  { name: "Beeroth" },
  { name: "Beersheba" },
  { name: "Beeshterah" },
  { name: "Beit Jibrin" },
  { name: "Bela" },
  { name: "Belgium" },
  { name: "Bene-Berak" },
  { name: "Benjamin" },
  { name: "Berea" },
  { name: "Berothah" },
  { name: "Berothai" },
  { name: "Besor" },
  { name: "Betah" },
  { name: "Beten" },
  { name: "Beth-Anath" },
  { name: "Beth-Anoth" },
  { name: "Beth-Arabah" },
  { name: "Beth-Aven" },
  { name: "Beth-Azmaveth" },
  { name: "Beth-Baal-Meon" },
  { name: "Beth-Barah" },
  { name: "Beth-Dagon" },
  { name: "Beth-Diblathaim" },
  { name: "Beth-Eked" },
  { name: "Beth-Emek" },
  { name: "Beth-Ezel" },
  { name: "Beth-Gader" },
  { name: "Beth-Gamul" },
  { name: "Beth-Haccerem" },
  { name: "Beth-Haggan" },
  { name: "Beth-Haran" },
  { name: "Beth-Hoglah" },
  { name: "Beth-Horon" },
  { name: "Beth-Jeshimoth" },
  { name: "Beth-Le-Aphrah" },
  { name: "Beth-Lebaoth" },
  { name: "Beth-Marcaboth" },
  { name: "Beth-Meon" },
  { name: "Beth-Millo" },
  { name: "Beth-Nimrah" },
  { name: "Beth-Pazzez" },
  { name: "Beth-Pelet" },
  { name: "Beth-Peor" },
  { name: "Beth-Phage" },
  { name: "Beth-Rapha" },
  { name: "Beth-Rehob" },
  { name: "Beth-Saida" },
  { name: "Beth-San" },
  { name: "Beth-Shemesh" },
  { name: "Beth-Shittah" },
  { name: "Beth-Tappuah" },
  { name: "Beth-Zur" },
  { name: "Bethabara" },
  { name: "Bethany" },
  { name: "Bethel" },
  { name: "Bethesda" },
  { name: "Bethlehem" },
  { name: "Bethlehem of Galilee" },
  { name: "Bethlehem of Judea" },
  { name: "Bethphage" },
  { name: "Bethsaida" },
  { name: "Bethshan" },
  { name: "Bethshean" },
  { name: "Betonim" },
  { name: "Bezek" },
  { name: "Bezer" },
  { name: "Bileam" },
  { name: "Bilhah" },
  { name: "Bithynia" },
  { name: "Bocim" },
  { name: "Bohan" },
  { name: "Bozrah" },
  { name: "Bozrah of Edom" },
  { name: "Bubastis" },
  { name: "Bukki" },

  // C
  { name: "Cabul" },
  { name: "Caesarea" },
  { name: "Caesarea Philippi" },
  { name: "Cain" },
  { name: "Calah" },
  { name: "Calneh" },
  { name: "Calno" },
  { name: "Cana" },
  { name: "Canaan" },
  { name: "Capernaum" },
  { name: "Caphtor" },
  { name: "Cappadocia" },
  { name: "Carchemish" },
  { name: "Carea" },
  { name: "Carmel" },
  { name: "Carthage" },
  { name: "Casiphia" },
  { name: "Cave" },
  { name: "Cave of Adullam" },
  { name: "Cave of Machpelah" },
  { name: "Cedron" },
  { name: "Cenchrea" },
  { name: "Chaldea" },
  { name: "Charax" },
  { name: "Charchemish" },
  { name: "Chebar" },
  { name: "Chedorlaomer" },
  { name: "Chelal" },
  { name: "Chellus" },
  { name: "Chelub" },
  { name: "Chemarim" },
  { name: "Chemosh" },
  { name: "Chesalon" },
  { name: "Chesed" },
  { name: "Chesil" },
  { name: "Chesulloth" },
  { name: "Chezib" },
  { name: "Chinnereth" },
  { name: "Chinneroth" },
  { name: "Chios" },
  { name: "Chisloth-Tabor" },
  { name: "Chitlish" },
  { name: "Chorazin" },
  { name: "Chozeba" },
  { name: "Cilicia" },
  { name: "City of David" },
  { name: "City of Salt" },
  { name: "Cnidus" },
  { name: "Colosse" },
  { name: "Colossae" },
  { name: "Conaniah" },
  { name: "Coos" },
  { name: "Corinth" },
  { name: "Cos" },
  { name: "Cozeba" },
  { name: "Crete" },
  { name: "Cush" },
  { name: "Cuthah" },
  { name: "Cyprus" },
  { name: "Cyrene" },
  { name: "Cyrus" },

  // D
  { name: "Daberath" },
  { name: "Dagon" },
  { name: "Dalmanutha" },
  { name: "Damascus" },
  { name: "Dan" },
  { name: "Darkon" },
  { name: "Darum" },
  { name: "Dathema" },
  { name: "Debir" },
  { name: "Decapolis" },
  { name: "Dedan" },
  { name: "Deganiah" },
  { name: "Delaiah" },
  { name: "Derbe" },
  { name: "Dibon" },
  { name: "Dibon-Gad" },
  { name: "Dilean" },
  { name: "Dimnah" },
  { name: "Dimon" },
  { name: "Dimonah" },
  { name: "Dizahab" },
  { name: "Dophkah" },
  { name: "Dor" },
  { name: "Dothan" },
  { name: "Dura" },

  // E
  { name: "Ebal" },
  { name: "Eben-Ezer" },
  { name: "Ebron" },
  { name: "Ecbatana" },
  { name: "Eden" },
  { name: "Eder" },
  { name: "Edrei" },
  { name: "Eglaim" },
  { name: "Eglon" },
  { name: "Egypt" },
  { name: "Ekron" },
  { name: "Elam" },
  { name: "Elath" },
  { name: "Elealeh" },
  { name: "Eleph" },
  { name: "Elim" },
  { name: "Elon" },
  { name: "Elon-Beth-Hanan" },
  { name: "Eloth" },
  { name: "Eltekeh" },
  { name: "Eltekon" },
  { name: "Eltolead" },
  { name: "Eltolad" },
  { name: "Emmaus" },
  { name: "Enaim" },
  { name: "Endor" },
  { name: "Engedi" },
  { name: "Engannim" },
  { name: "En-Haddah" },
  { name: "En-Hakkore" },
  { name: "En-Hazor" },
  { name: "En-Mishpat" },
  { name: "En-Rimmon" },
  { name: "En-Rogel" },
  { name: "En-Shemesh" },
  { name: "En-Tappuah" },
  { name: "Ephah" },
  { name: "Ephes-Dammim" },
  { name: "Ephesus" },
  { name: "Ephraim" },
  { name: "Ephrath" },
  { name: "Ephron" },
  { name: "Er-Rakkath" },
  { name: "Erech" },
  { name: "Eri" },
  { name: "Eshcol" },
  { name: "Eshan" },
  { name: "Eshnaol" },
  { name: "Eshternoa" },
  { name: "Eshtemoa" },
  { name: "Etham" },
  { name: "Ethiopia" },
  { name: "Ethnan" },
  { name: "Ezion-Gaber" },
  { name: "Ezion-Geber" },
  { name: "Ezrahite" },

  // F
  { name: "Fair Havens" },
  { name: "Field" },

  // G
  { name: "Gad" },
  { name: "Gadara" },
  { name: "Gader" },
  { name: "Galatia" },
  { name: "Galilee" },
  { name: "Galilee of the Nations" },
  { name: "Gamala" },
  { name: "Gath" },
  { name: "Gath-Hepher" },
  { name: "Gath-Rimmon" },
  { name: "Gaul" },
  { name: "Gaza" },
  { name: "Geba" },
  { name: "Gebal" },
  { name: "Geder" },
  { name: "Gederah" },
  { name: "Gederoth" },
  { name: "Gederothaim" },
  { name: "Gedor" },
  { name: "Geliloth" },
  { name: "Gemalli" },
  { name: "Gennesaret" },
  { name: "Gerar" },
  { name: "Gergesa" },
  { name: "Gerizim" },
  { name: "Geshur" },
  { name: "Gethsemane" },
  { name: "Gezer" },
  { name: "Gibbethon" },
  { name: "Gibeah" },
  { name: "Gibeon" },
  { name: "Gibeah of Benjamin" },
  { name: "Gibeah of Saul" },
  { name: "Gidom" },
  { name: "Gihon" },
  { name: "Gilboa" },
  { name: "Gilead" },
  { name: "Gilgal" },
  { name: "Gimzo" },
  { name: "Ginath" },
  { name: "Gittaim" },
  { name: "Goath" },
  { name: "Gob" },
  { name: "Golan" },
  { name: "Golgotha" },
  { name: "Gomorrah" },
  { name: "Goshen" },
  { name: "Greece" },
  { name: "Gudgodah" },
  { name: "Gur" },
  { name: "Gur-Baal" },

  // H
  { name: "Habor" },
  { name: "Hachilah" },
  { name: "Hadad-Rimmon" },
  { name: "Hadashah" },
  { name: "Hades" },
  { name: "Hadid" },
  { name: "Hadrach" },
  { name: "Halah" },
  { name: "Halhul" },
  { name: "Hali" },
  { name: "Hallohesh" },
  { name: "Halon" },
  { name: "Ham" },
  { name: "Hamath" },
  { name: "Hammath" },
  { name: "Hammon" },
  { name: "Hammoth-Dor" },
  { name: "Hanan" },
  { name: "Hanes" },
  { name: "Hannah" },
  { name: "Hannathon" },
  { name: "Haphraim" },
  { name: "Hara" },
  { name: "Haradah" },
  { name: "Haran" },
  { name: "Hareth" },
  { name: "Harim" },
  { name: "Harod" },
  { name: "Harosheth" },
  { name: "Harosheth of the Gentiles" },
  { name: "Havilah" },
  { name: "Havoth-Jair" },
  { name: "Hazar-Addar" },
  { name: "Hazar-Enan" },
  { name: "Hazar-Gaddah" },
  { name: "Hazar-Shual" },
  { name: "Hazar-Susah" },
  { name: "Hazar-Susim" },
  { name: "Hazazon-Tamar" },
  { name: "Hazeroth" },
  { name: "Hazezon-Tamar" },
  { name: "Hazor" },
  { name: "Heaven" },
  { name: "Hebron" },
  { name: "Helam" },
  { name: "Helbah" },
  { name: "Helbon" },
  { name: "Helkath" },
  { name: "Helkath-Hazzurim" },
  { name: "Hell" },
  { name: "Hena" },
  { name: "Hepher" },
  { name: "Hepherites" },
  { name: "Hermon" },
  { name: "Heshbon" },
  { name: "Hethlon" },
  { name: "Hezron" },
  { name: "Hiddekel" },
  { name: "Hiel" },
  { name: "Hierapolis" },
  { name: "Hil" },
  { name: "Hilen" },
  { name: "Hinnom" },
  { name: "Hirah" },
  { name: "Hiram" },
  { name: "Hittite" },
  { name: "Hobah" },
  { name: "Hoglah" },
  { name: "Holon" },
  { name: "Hophni" },
  { name: "Horeb" },
  { name: "Horem" },
  { name: "Hormah" },
  { name: "Horonaim" },
  { name: "Hosah" },
  { name: "Hukkok" },
  { name: "Hukok" },
  { name: "Hul" },
  { name: "Huldah" },
  { name: "Humtah" },
  { name: "Hur" },

  // I
  { name: "Iconium" },
  { name: "Idumea" },
  { name: "Ijon" },
  { name: "Illyricum" },
  { name: "Immer" },
  { name: "India" },
  { name: "Iphedeiah" },
  { name: "Iron" },
  { name: "Ishmael" },
  { name: "Israel" },
  { name: "Issachar" },
  { name: "Italy" },
  { name: "Ithnan" },
  { name: "Ithrite" },
  { name: "Ittah-Kazin" },
  { name: "Iyyim" },

  // J
  { name: "Jabbok" },
  { name: "Jabesh" },
  { name: "Jabesh-Gilead" },
  { name: "Jabneel" },
  { name: "Jabneh" },
  { name: "Jachin" },
  { name: "Jagur" },
  { name: "Jahaz" },
  { name: "Jahzah" },
  { name: "Janoah" },
  { name: "Janohah" },
  { name: "Janohem" },
  { name: "Japha" },
  { name: "Japhia" },
  { name: "Jarmuth" },
  { name: "Jattir" },
  { name: "Jazer" },
  { name: "Jebus" },
  { name: "Jecoliah" },
  { name: "Jedaiah" },
  { name: "Jehoshaphat" },
  { name: "Jehovah-Jireh" },
  { name: "Jehovah-Nissi" },
  { name: "Jehovah-Shalom" },
  { name: "Jekabzeel" },
  { name: "Jekameam" },
  { name: "Jemnaan" },
  { name: "Jenoah" },
  { name: "Jerahmeel" },
  { name: "Jericho" },
  { name: "Jeruel" },
  { name: "Jerusalem" },
  { name: "Jeshimon" },
  { name: "Jeshua" },
  { name: "Jeshanah" },
  { name: "Jethlah" },
  { name: "Jezreel" },
  { name: "Jiphtah" },
  { name: "Jiphtah-El" },
  { name: "Jiri" },
  { name: "Jokdeam" },
  { name: "Jokneam" },
  { name: "Joktheel" },
  { name: "Joppa" },
  { name: "Jordan" },
  { name: "Jordan River" },
  { name: "Jotbah" },
  { name: "Jotbathah" },
  { name: "Judah" },
  { name: "Judea" },
  { name: "Juttah" },

  // K
  { name: "Kabzeel" },
  { name: "Kadesh" },
  { name: "Kadesh-Barnea" },
  { name: "Kamon" },
  { name: "Kanah" },
  { name: "Karka" },
  { name: "Karkaa" },
  { name: "Karkor" },
  { name: "Karnaim" },
  { name: "Kartah" },
  { name: "Kartan" },
  { name: "Kattath" },
  { name: "Kedemoth" },
  { name: "Kedesh" },
  { name: "Kedesh in Galilee" },
  { name: "Kedesh-Naphtali" },
  { name: "Kefar-Hammon" },
  { name: "Kehelathah" },
  { name: "Keilah" },
  { name: "Kemuel" },
  { name: "Kenath" },
  { name: "Kenaz" },
  { name: "Kerioth" },
  { name: "Kesalon" },
  { name: "Kesitah" },
  { name: "Kibroth-Hattaavah" },
  { name: "Kibzaim" },
  { name: "Kidron" },
  { name: "Kidron Valley" },
  { name: "Kinah" },
  { name: "Kir" },
  { name: "Kir-Haraseth" },
  { name: "Kir-Heres" },
  { name: "Kir-Moab" },
  { name: "Kirjath" },
  { name: "Kirjath-Arba" },
  { name: "Kirjath-Baal" },
  { name: "Kirjath-Huzoth" },
  { name: "Kirjath-Jearim" },
  { name: "Kirjath-Sannah" },
  { name: "Kirjath-Sepher" },
  { name: "Kishon" },
  { name: "Kitron" },
  { name: "Kittim" },
  { name: "Korah" },
  { name: "Koz" },

  // L
  { name: "Laadah" },
  { name: "Laish" },
  { name: "Lakkum" },
  { name: "Lasea" },
  { name: "Lasharon" },
  { name: "Lasha" },
  { name: "Lashkar" },
  { name: "Lebaoth" },
  { name: "Lebonah" },
  { name: "Lebaoth" },
  { name: "Lebo-Hamath" },
  { name: "Lebonah" },
  { name: "Lehi" },
  { name: "Leshem" },
  { name: "Libnah" },
  { name: "Libya" },
  { name: "Lod" },
  { name: "Lo-Debar" },
  { name: "Lower Beth-Horon" },
  { name: "Lud" },
  { name: "Luhith" },
  { name: "Luz" },
  { name: "Lydia" },
  { name: "Lydda" },
  { name: "Lysias" },
  { name: "Lystra" },

  // M
  { name: "Maacah" },
  { name: "Maaleh-Acrabbim" },
  { name: "Maarath" },
  { name: "Macedonia" },
  { name: "Machpelah" },
  { name: "Madai" },
  { name: "Madmannah" },
  { name: "Madon" },
  { name: "Magdala" },
  { name: "Magdiel" },
  { name: "Magog" },
  { name: "Mahalab" },
  { name: "Mahanaim" },
  { name: "Mahaneh-Dan" },
  { name: "Mahanaim" },
  { name: "Maon" },
  { name: "Makaz" },
  { name: "Makkedah" },
  { name: "Malatha" },
  { name: "Mallotha" },
  { name: "Mamre" },
  { name: "Manahath" },
  { name: "Manasseh" },
  { name: "Maon" },
  { name: "Marah" },
  { name: "Mareshah" },
  { name: "Maroth" },
  { name: "Marsena" },
  { name: "Mash" },
  { name: "Masrekah" },
  { name: "Massah" },
  { name: "Mattanah" },
  { name: "Media" },
  { name: "Megiddo" },
  { name: "Melita" },
  { name: "Memphis" },
  { name: "Mephaath" },
  { name: "Meribah" },
  { name: "Merom" },
  { name: "Meroz" },
  { name: "Mesech" },
  { name: "Meshech" },
  { name: "Meshullam" },
  { name: "Mesopotamia" },
  { name: "Methoar" },
  { name: "Mevorach" },
  { name: "Micha" },
  { name: "Michmash" },
  { name: "Middin" },
  { name: "Migdal" },
  { name: "Migdal-El" },
  { name: "Migdal-Gad" },
  { name: "Migron" },
  { name: "Miletus" },
  { name: "Minni" },
  { name: "Minnith" },
  { name: "Mishal" },
  { name: "Mishma" },
  { name: "Mishr" },
  { name: "Misrephoth-Maim" },
  { name: "Mitylene" },
  { name: "Mizpah" },
  { name: "Mizpeh" },
  { name: "Mizpeh of Gilead" },
  { name: "Moab" },
  { name: "Moffat" },
  { name: "Moladah" },
  { name: "Moreh" },
  { name: "Moresheth" },
  { name: "Moresheth-Gath" },
  { name: "Moriah" },
  { name: "Mount" },
  { name: "Mount Abarim" },
  { name: "Mount Ararat" },
  { name: "Mount Carmel" },
  { name: "Mount Ebal" },
  { name: "Mount Ephraim" },
  { name: "Mount Gerizim" },
  { name: "Mount Gilboa" },
  { name: "Mount Gilead" },
  { name: "Mount Hermon" },
  { name: "Mount Horeb" },
  { name: "Mount Hor" },
  { name: "Mount Lebanon" },
  { name: "Mount Moriah" },
  { name: "Mount Nebo" },
  { name: "Mount Olives" },
  { name: "Mount Pisgah" },
  { name: "Mount Seir" },
  { name: "Mount Sinai" },
  { name: "Mount Tabor" },
  { name: "Mount Zion" },
  { name: "Mozah" },
  { name: "Mysia" },

  // N
  { name: "Naaran" },
  { name: "Naarath" },
  { name: "Nain" },
  { name: "Naioth" },
  { name: "Naphath" },
  { name: "Naphath-Dor" },
  { name: "Naphtali" },
  { name: "Nazareth" },
  { name: "Neapolis" },
  { name: "Nebo" },
  { name: "Nebuchadnezzar" },
  { name: "Negeb" },
  { name: "Negev" },
  { name: "Nekeb" },
  { name: "Nephtoah" },
  { name: "Netaim" },
  { name: "Netophah" },
  { name: "New Heaven and New Earth" },
  { name: "Nezib" },
  { name: "Nibshan" },
  { name: "Nimrim" },
  { name: "Nimrod" },
  { name: "Nineveh" },
  { name: "Nob" },
  { name: "Nod" },
  { name: "No" },
  { name: "Noph" },
  { name: "Nophah" },

  // O
  { name: "Oboth" },
  { name: "Ono" },
  { name: "Ophel" },
  { name: "Ophir" },
  { name: "Ophni" },
  { name: "Ophrah" },
  { name: "Ophrah of the Abiezrites" },
  { name: "Orontes" },

  // P
  { name: "Paddan-Aram" },
  { name: "Padan-Aram" },
  { name: "Pai" },
  { name: "Palace" },
  { name: "Pamphylia" },
  { name: "Paphos" },
  { name: "Paran" },
  { name: "Parthia" },
  { name: "Patara" },
  { name: "Pathros" },
  { name: "Patmos" },
  { name: "Pela" },
  { name: "Peleth" },
  { name: "Pelusium" },
  { name: "Peniel" },
  { name: "Penuel" },
  { name: "Perga" },
  { name: "Pergamos" },
  { name: "Pergamum" },
  { name: "Perizzites" },
  { name: "Persia" },
  { name: "Pethor" },
  { name: "Pharpar" },
  { name: "Phenice" },
  { name: "Philadelphia" },
  { name: "Philippi" },
  { name: "Philistia" },
  { name: "Philistim" },
  { name: "Phoenicia" },
  { name: "Phrygia" },
  { name: "Pirathon" },
  { name: "Pisgah" },
  { name: "Pisidia" },
  { name: "Pithom" },
  { name: "Punon" },
  { name: "Put" },
  { name: "Puteoli" },

  // Q
  { name: "Qumran" },

  // R
  { name: "Raamah" },
  { name: "Raamses" },
  { name: "Rabbah" },
  { name: "Rabbath-Ammon" },
  { name: "Rakkath" },
  { name: "Ramah" },
  { name: "Ramah of Benjamin" },
  { name: "Rama" },
  { name: "Ramath-Lehi" },
  { name: "Ramath-Mizpeh" },
  { name: "Ramathaim-Zophim" },
  { name: "Ramathite" },
  { name: "Rameses" },
  { name: "Ramoth" },
  { name: "Ramoth-Gilead" },
  { name: "Reed Sea" },
  { name: "Red Sea" },
  { name: "Rehob" },
  { name: "Rehoboth" },
  { name: "Remeth" },
  { name: "Rephidim" },
  { name: "Rephaim" },
  { name: "Rezeph" },
  { name: "Rezin" },
  { name: "Rhegium" },
  { name: "Riblah" },
  { name: "Rimmon" },
  { name: "Rimmon-Parez" },
  { name: "Riphath" },
  { name: "Rissah" },
  { name: "Rithmah" },
  { name: "River" },
  { name: "River Chebar" },
  { name: "River Euphrates" },
  { name: "River Jordan" },
  { name: "River Kishon" },
  { name: "River Nile" },
  { name: "River of Egypt" },
  { name: "River Ulai" },
  { name: "Road" },
  { name: "Rogelim" },
  { name: "Rome" },
  { name: "Ros" },
  { name: "Rumah" },

  // S
  { name: "Salamis" },
  { name: "Salcah" },
  { name: "Salchah" },
  { name: "Salmah" },
  { name: "Salmon" },
  { name: "Salt Sea" },
  { name: "Salt Valley" },
  { name: "Samaria" },
  { name: "Samaria (city)" },
  { name: "Samaria (region)" },
  { name: "Samnium" },
  { name: "Samothrace" },
  { name: "Sansannah" },
  { name: "Saphir" },
  { name: "Sapphira" },
  { name: "Sarid" },
  { name: "Saron" },
  { name: "Seba" },
  { name: "Sebaste" },
  { name: "Secacah" },
  { name: "Sechu" },
  { name: "Secundus" },
  { name: "Sela" },
  { name: "Selah" },
  { name: "Seleucia" },
  { name: "Sem" },
  { name: "Senir" },
  { name: "Sephar" },
  { name: "Sepharad" },
  { name: "Sepharvaim" },
  { name: "Sepulchre" },
  { name: "Serug" },
  { name: "Shalisha" },
  { name: "Shalem" },
  { name: "Shamir" },
  { name: "Shaphir" },
  { name: "Sharon" },
  { name: "Sharuhen" },
  { name: "Shaveh" },
  { name: "Shaveh-Kiriathaim" },
  { name: "Shear-Jashub" },
  { name: "Sheba" },
  { name: "Shechem" },
  { name: "Sheep Gate" },
  { name: "Sheep Pool" },
  { name: "Sheol" },
  { name: "Sheshach" },
  { name: "Shihor" },
  { name: "Shihor-Libnath" },
  { name: "Shiloh" },
  { name: "Shimron" },
  { name: "Shimron-Meron" },
  { name: "Shinab" },
  { name: "Shinar" },
  { name: "Shion" },
  { name: "Shittim" },
  { name: "Shoco" },
  { name: "Shoco" },
  { name: "Shunem" },
  { name: "Shur" },
  { name: "Shushan" },
  { name: "Sibmah" },
  { name: "Sichem" },
  { name: "Siddim" },
  { name: "Sidon" },
  { name: "Siloam" },
  { name: "Siloam Pool" },
  { name: "Simeon" },
  { name: "Sin" },
  { name: "Sinai" },
  { name: "Sion" },
  { name: "Sippai" },
  { name: "Smyrna" },
  { name: "Socho" },
  { name: "Socoh" },
  { name: "Sodom" },
  { name: "Solem" },
  { name: "Spain" },
  { name: "Sparta" },
  { name: "Succoth" },
  { name: "Sukkiims" },
  { name: "Syracuse" },
  { name: "Syria" },
  { name: "Syrtis" },

  // T
  { name: "Tabernacle" },
  { name: "Tabor" },
  { name: "Tadmor" },
  { name: "Tahath" },
  { name: "Tahpanhes" },
  { name: "Tamar" },
  { name: "Tanaach" },
  { name: "Tanach" },
  { name: "Tappuah" },
  { name: "Taralah" },
  { name: "Tarshish" },
  { name: "Tarsus" },
  { name: "Tartak" },
  { name: "Taurus" },
  { name: "Tekoa" },
  { name: "Tel-Abib" },
  { name: "Tel-Abib" },
  { name: "Tel-Harsha" },
  { name: "Tel-Melah" },
  { name: "Telaim" },
  { name: "Telem" },
  { name: "Tell-Harsha" },
  { name: "Tell-Melah" },
  { name: "Teman" },
  { name: "Temple" },
  { name: "Temple Mount" },
  { name: "Temple of Solomon" },
  { name: "Tent" },
  { name: "Terah" },
  { name: "Thammuz" },
  { name: "Thebez" },
  { name: "Thessalonica" },
  { name: "Thyatira" },
  { name: "Tiberias" },
  { name: "Tiberias (Sea of)" },
  { name: "Tibni" },
  { name: "Tigris" },
  { name: "Timnah" },
  { name: "Timnath" },
  { name: "Timnath-Heres" },
  { name: "Timnath-Serah" },
  { name: "Tiphsah" },
  { name: "Tirzah" },
  { name: "Tishbe" },
  { name: "Tob" },
  { name: "Tophel" },
  { name: "Tophet" },
  { name: "Tou" },
  { name: "Trachonitis" },
  { name: "Troas" },
  { name: "Tubal" },
  { name: "Tyre" },

  // U
  { name: "Ulam" },
  { name: "Ulai" },
  { name: "Upper Beth-Horon" },
  { name: "Ur" },
  { name: "Urim" },
  { name: "Uz" },
  { name: "Uzal" },

  // V
  { name: "Valley" },
  { name: "Valley of Achor" },
  { name: "Valley of Baca" },
  { name: "Valley of Berachah" },
  { name: "Valley of Elah" },
  { name: "Valley of Hinnom" },
  { name: "Valley of Jehoshaphat" },
  { name: "Valley of Jezreel" },
  { name: "Valley of Rephaim" },
  { name: "Valley of Shaveh" },
  { name: "Valley of Siddim" },
  { name: "Valley of Slaughter" },
  { name: "Valley of Succoth" },
  { name: "Valley of the Kings" },
  { name: "Valley of the Shadow of Death" },
  { name: "Valley of the Son of Hinnom" },
  { name: "Valley of Zephathah" },

  // W
  { name: "Water Gate" },
  { name: "Well" },
  { name: "Well of Beersheba" },
  { name: "Well of Harod" },
  { name: "Well of Sirah" },
  { name: "Wilderness" },
  { name: "Wilderness of Beersheba" },
  { name: "Wilderness of Beth-Aven" },
  { name: "Wilderness of Edom" },
  { name: "Wilderness of Engedi" },
  { name: "Wilderness of Gibeon" },
  { name: "Wilderness of Judea" },
  { name: "Wilderness of Maon" },
  { name: "Wilderness of Paran" },
  { name: "Wilderness of Shur" },
  { name: "Wilderness of Sin" },
  { name: "Wilderness of Tekoa" },
  { name: "Wilderness of Zin" },
  { name: "Wilderness of Ziph" },

  // Z
  { name: "Zaanaim" },
  { name: "Zaanannim" },
  { name: "Zaavan" },
  { name: "Zadok" },
  { name: "Zair" },
  { name: "Zalmon" },
  { name: "Zanoah" },
  { name: "Zaphon" },
  { name: "Zarephath" },
  { name: "Zarethan" },
  { name: "Zarhites" },
  { name: "Zeboim" },
  { name: "Zeboiim" },
  { name: "Zebulun" },
  { name: "Zedad" },
  { name: "Zelah" },
  { name: "Zelzah" },
  { name: "Zemaraim" },
  { name: "Zenan" },
  { name: "Zephath" },
  { name: "Zephathah" },
  { name: "Zer" },
  { name: "Zered" },
  { name: "Zeredah" },
  { name: "Zereth-Shahar" },
  { name: "Ziklag" },
  { name: "Zin" },
  { name: "Zin (Wilderness of)" },
  { name: "Zion" },
  { name: "Zior" },
  { name: "Ziph" },
  { name: "Zoan" },
  { name: "Zoar" },
  { name: "Zobah" },
  { name: "Zorah" },
  { name: "Zupim" },
  { name: "Zur" },
  // Additional comprehensive places - Batch 2
  { name: "Abilene" },
  { name: "Abiram" },
  { name: "Achzib (Asher)" },
  { name: "Adada" },
  { name: "Adami-Nekeb" },
  { name: "Adar (fortress)" },
  { name: "Adithaim" },
  { name: "Adoraim" },
  { name: "Adullam (cave)" },
  { name: "Aijalon Valley" },
  { name: "Ain Karem" },
  { name: "Ajalon" },
  { name: "Akrabbim" },
  { name: "Aksah" },
  { name: "Alamoth" },
  { name: "Aleppo" },
  { name: "Allon-Bachuth" },
  { name: "Almon-Diblathaim" },
  { name: "Amalekites" },
  { name: "Ammonites" },
  { name: "Amorites" },
  { name: "Anab" },
  { name: "Anathoth (city)" },
  { name: "Anthedon" },
  { name: "Aphek (Philistine)" },
  { name: "Aphek (Asher)" },
  { name: "Appii Forum" },
  { name: "Arabah (valley)" },
  { name: "Arabs" },
  { name: "Aram-Damascus" },
  { name: "Aram-Maachah" },
  { name: "Aram-Naharaim" },
  { name: "Arbela (Galilee)" },
  { name: "Arnon" },
  { name: "Arnon River" },
  { name: "Arnon Valley" },
  { name: "Aroer (Gad)" },
  { name: "Aroer (Moab)" },
  { name: "Aroer (Negeb)" },
  { name: "Aruboth" },
  { name: "Ashdod (city)" },
  { name: "Ashdodites" },
  { name: "Asherah" },
  { name: "Ashkelon (city)" },
  { name: "Ashtaroth-Karnaim" },
  { name: "Asia Minor" },
  { name: "Assyrian Empire" },
  { name: "Atad" },
  { name: "Ataroth-Addar" },
  { name: "Athaliah" },
  { name: "Attalia" },
  { name: "Aven" },
  { name: "Avvim" },
  { name: "Azem" },
  { name: "Azekah (fortress)" },
  { name: "Azmaveth (place)" },
  { name: "Azotus" },
  { name: "Baal (town)" },
  { name: "Baal-Gad (valley)" },
  { name: "Baal-Hamon (vineyard)" },
  { name: "Baal-Hazor (mountain)" },
  { name: "Baal-Meon (city)" },
  { name: "Baal-Perazim (hill)" },
  { name: "Baal-Shalishah (place)" },
  { name: "Baal-Tamar (grove)" },
  { name: "Baalath (city)" },
  { name: "Baalath-Beer (well)" },
  { name: "Babel (tower)" },
  { name: "Babylonian Empire" },
  { name: "Baca (valley)" },
  { name: "Bahurim (village)" },
  { name: "Bamoth-Baal (high place)" },
  { name: "Bashan (region)" },
  { name: "Batanaea" },
  { name: "Bath-Rabbim" },
  { name: "Bealoth" },
  { name: "Beer (well)" },
  { name: "Beer-Elim (well)" },
  { name: "Beer-Lahai-Roi (well)" },
  { name: "Beer-Sheba (city)" },
  { name: "Beeroth (city)" },
  { name: "Beersheba (city)" },
  { name: "Beit Jibrin" },
  { name: "Bela (Zoar)" },
  { name: "Bene-Berak (city)" },
  { name: "Benjamin (territory)" },
  { name: "Berea (Macedonia)" },
  { name: "Berothah (city)" },
  { name: "Berothai (city)" },
  { name: "Besor (brook)" },
  { name: "Betah (city)" },
  { name: "Beten (city)" },
  { name: "Beth-Anath (city)" },
  { name: "Beth-Anoth (city)" },
  { name: "Beth-Arabah (city)" },
  { name: "Beth-Aven (city)" },
  { name: "Beth-Azmaveth (city)" },
  { name: "Beth-Baal-Meon (city)" },
  { name: "Beth-Barah (ford)" },
  { name: "Beth-Dagon (city)" },
  { name: "Beth-Diblathaim (city)" },
  { name: "Beth-Eked (place)" },
  { name: "Beth-Emek (city)" },
  { name: "Beth-Ezel (city)" },
  { name: "Beth-Gader (city)" },
  { name: "Beth-Gamul (city)" },
  { name: "Beth-Haccerem (place)" },
  { name: "Beth-Haggan (garden)" },
  { name: "Beth-Haran (city)" },
  { name: "Beth-Hoglah (city)" },
  { name: "Beth-Horon (city)" },
  { name: "Beth-Jeshimoth (city)" },
  { name: "Beth-Le-Aphrah (city)" },
  { name: "Beth-Lebaoth (city)" },
  { name: "Beth-Marcaboth (city)" },
  { name: "Beth-Meon (city)" },
  { name: "Beth-Millo (fortress)" },
  { name: "Beth-Nimrah (city)" },
  { name: "Beth-Pazzez (city)" },
  { name: "Beth-Pelet (city)" },
  { name: "Beth-Phage (village)" },
  { name: "Beth-Rapha (city)" },
  { name: "Beth-Rehob (city)" },
  { name: "Beth-Saida (city)" },
  { name: "Beth-San (city)" },
  { name: "Beth-Shemesh (city)" },
  { name: "Beth-Shittah (city)" },
  { name: "Beth-Tappuah (city)" },
  { name: "Beth-Zur (city)" },
  { name: "Bethabara (ford)" },
  { name: "Bethany (village)" },
  { name: "Bethel (city)" },
  { name: "Bethesda (pool)" },
  { name: "Bethlehem (city)" },
  { name: "Bethlehem Ephrathah" },
  { name: "Bethphage (village)" },
  { name: "Bethsaida (city)" },
  { name: "Bethshan (city)" },
  { name: "Bethshean (city)" },
  { name: "Betonim (city)" },
  { name: "Bezek (city)" },
  { name: "Bezer (city of refuge)" },
  { name: "Bileam (city)" },
  { name: "Bilhah (tent)" },
  { name: "Bithynia (province)" },
  { name: "Bocim (weepers)" },
  { name: "Bohan (stone)" },
  { name: "Bozrah (city)" },
  { name: "Bubastis (city)" },
  { name: "Bukki (district)" },
  { name: "Cabul (district)" },
  { name: "Caesarea (city)" },
  { name: "Caesarea Maritima" },
  { name: "Caesarea Philippi (city)" },
  { name: "Cain (land of)" },
  { name: "Calah (city)" },
  { name: "Calneh (city)" },
  { name: "Calno (city)" },
  { name: "Cana (village)" },
  { name: "Canaan (land)" },
  { name: "Canaanites" },
  { name: "Capernaum (city)" },
  { name: "Caphtor (island)" },
  { name: "Cappadocia (region)" },
  { name: "Carchemish (city)" },
  { name: "Carea (city)" },
  { name: "Carmel (mountain)" },
  { name: "Carthage (city)" },
  { name: "Casiphia (place)" },
  { name: "Cave of Adullam" },
  { name: "Cave of Machpelah" },
  { name: "Cedron (brook)" },
  { name: "Cenchrea (harbor)" },
  { name: "Chaldea (land)" },
  { name: "Chaldeans" },
  { name: "Charax (fortress)" },
  { name: "Charchemish (city)" },
  { name: "Chebar (river)" },
  { name: "Chedorlaomer (king)" },
  { name: "Chelal (city)" },
  { name: "Chellus (city)" },
  { name: "Chelub (city)" },
  { name: "Chemarim (idols)" },
  { name: "Chemosh (god)" },
  { name: "Chesalon (city)" },
  { name: "Chesed (region)" },
  { name: "Chesil (city)" },
  { name: "Chesulloth (city)" },
  { name: "Chezib (city)" },
  { name: "Chinnereth (sea)" },
  { name: "Chinneroth (region)" },
  { name: "Chios (island)" },
  { name: "Chisloth-Tabor (city)" },
  { name: "Chitlish (city)" },
  { name: "Chorazin (city)" },
  { name: "Chozeba (city)" },
  { name: "Cilicia (region)" },
  { name: "City of David (Jerusalem)" },
  { name: "City of Salt" },
  { name: "Cnidus (city)" },
  { name: "Colosse (city)" },
  { name: "Colossae (city)" },
  { name: "Conaniah (place)" },
  { name: "Coos (island)" },
  { name: "Corinth (city)" },
  { name: "Cos (island)" },
  { name: "Cozeba (city)" },
  { name: "Crete (island)" },
  { name: "Cush (land)" },
  { name: "Cushites" },
  { name: "Cuthah (city)" },
  { name: "Cyprus (island)" },
  { name: "Cyrene (city)" },
  { name: "Cyrus (river)" },
  { name: "Daberath (city)" },
  { name: "Dagon (temple)" },
  { name: "Dalmanutha (region)" },
  { name: "Damascus (city)" },
  { name: "Dan (city)" },
  { name: "Dan (tribe)" },
  { name: "Darkon (place)" },
  { name: "Darum (city)" },
  { name: "Dathema (fortress)" },
  { name: "Debir (city)" },
  { name: "Decapolis (region)" },
  { name: "Dedan (city)" },
  { name: "Deganiah (city)" },
  { name: "Delaiah (place)" },
  { name: "Derbe (city)" },
  { name: "Dibon (city)" },
  { name: "Dibon-Gad (city)" },
  { name: "Dilean (city)" },
  { name: "Dimnah (city)" },
  { name: "Dimon (city)" },
  { name: "Dimonah (city)" },
  { name: "Dizahab (place)" },
  { name: "Dophkah (place)" },
  { name: "Dor (city)" },
  { name: "Dothan (city)" },
  { name: "Dura (plain)" },
  { name: "Ebal (mountain)" },
  { name: "Eben-Ezer (stone)" },
  { name: "Ebron (city)" },
  { name: "Ecbatana (city)" },
  { name: "Eden (garden)" },
  { name: "Eder (tower)" },
  { name: "Edrei (city)" },
  { name: "Eglaim (city)" },
  { name: "Eglon (city)" },
  { name: "Egypt (country)" },
  { name: "Ekron (city)" },
  { name: "Elam (country)" },
  { name: "Elath (city)" },
  { name: "Elealeh (city)" },
  { name: "Eleph (city)" },
  { name: "Elim (oasis)" },
  { name: "Elon (city)" },
  { name: "Elon-Beth-Hanan (city)" },
  { name: "Eloth (city)" },
  { name: "Eltekeh (city)" },
  { name: "Eltekon (city)" },
  { name: "Eltolad (city)" },
  { name: "Emmaus (village)" },
  { name: "Enaim (city)" },
  { name: "Endor (city)" },
  { name: "Engedi (city)" },
  { name: "Engannim (city)" },
  { name: "En-Haddah (spring)" },
  { name: "En-Hakkore (spring)" },
  { name: "En-Hazor (spring)" },
  { name: "En-Mishpat (spring)" },
  { name: "En-Rimmon (spring)" },
  { name: "En-Rogel (spring)" },
  { name: "En-Shemesh (spring)" },
  { name: "En-Tappuah (spring)" },
  { name: "Ephah (land)" },
  { name: "Ephes-Dammim (place)" },
  { name: "Ephesus (city)" },
  { name: "Ephraim (tribe)" },
  { name: "Ephrath (city)" },
  { name: "Ephron (mountain)" },
  { name: "Er-Rakkath (city)" },
  { name: "Erech (city)" },
  { name: "Eri (city)" },
  { name: "Eshcol (valley)" },
  { name: "Eshan (city)" },
  { name: "Eshnaol (city)" },
  { name: "Eshternoa (city)" },
  { name: "Eshtemoa (city)" },
  { name: "Etham (place)" },
  { name: "Ethiopia (country)" },
  { name: "Ethnan (city)" },
  { name: "Ezion-Gaber (city)" },
  { name: "Ezion-Geber (city)" },
  { name: "Ezrahite (place)" },
  { name: "Fair Havens (harbor)" },
  { name: "Field (generic)" },
  { name: "Gad (tribe)" },
  { name: "Gadara (city)" },
  { name: "Gader (city)" },
  { name: "Galatia (region)" },
  { name: "Galilee (region)" },
  { name: "Galilee of the Nations" },
  { name: "Gamala (city)" },
  { name: "Gath (city)" },
  { name: "Gath-Hepher (city)" },
  { name: "Gath-Rimmon (city)" },
  { name: "Gaul (country)" },
  { name: "Gaza (city)" },
  { name: "Geba (city)" },
  { name: "Gebal (city)" },
  { name: "Geder (city)" },
  { name: "Gederah (city)" },
  { name: "Gederoth (city)" },
  { name: "Gederothaim (city)" },
  { name: "Gedor (city)" },
  { name: "Geliloth (city)" },
  { name: "Gemalli (place)" },
  { name: "Gennesaret (lake)" },
  { name: "Gerar (city)" },
  { name: "Gergesa (region)" },
  { name: "Gerizim (mountain)" },
  { name: "Geshur (land)" },
  { name: "Gethsemane (garden)" },
  { name: "Gezer (city)" },
  { name: "Gibbethon (city)" },
  { name: "Gibeah (city)" },
  { name: "Gibeon (city)" },
  { name: "Gibeah of Benjamin" },
  { name: "Gibeah of Saul" },
  { name: "Gidom (city)" },
  { name: "Gihon (spring)" },
  { name: "Gilboa (mountain)" },
  { name: "Gilead (region)" },
  { name: "Gilgal (city)" },
  { name: "Gimzo (city)" },
  { name: "Ginath (city)" },
  { name: "Gittaim (city)" },
  { name: "Goath (place)" },
  { name: "Gob (place)" },
  { name: "Golan (city)" },
  { name: "Golgotha (place)" },
  { name: "Gomorrah (city)" },
  { name: "Goshen (land)" },
  { name: "Greece (country)" },
  { name: "Gudgodah (place)" },
  { name: "Gur (ascent)" },
  { name: "Gur-Baal (place)" },
  { name: "Habor (river)" },
  { name: "Hachilah (hill)" },
  { name: "Hadad-Rimmon (city)" },
  { name: "Hadashah (city)" },
  { name: "Hades (underworld)" },
  { name: "Hadid (city)" },
  { name: "Hadrach (city)" },
  { name: "Halah (city)" },
  { name: "Halhul (city)" },
  { name: "Hali (city)" },
  { name: "Hallohesh (place)" },
  { name: "Halon (city)" },
  { name: "Ham (land)" },
  { name: "Hamath (city)" },
  { name: "Hammath (city)" },
  { name: "Hammon (city)" },
  { name: "Hammoth-Dor (city)" },
  { name: "Hanan (city)" },
  { name: "Hanes (city)" },
  { name: "Hannah (city)" },
  { name: "Hannathon (city)" },
  { name: "Haphraim (city)" },
  { name: "Hara (city)" },
  { name: "Haradah (place)" },
  { name: "Haran (city)" },
  { name: "Hareth (wood)" },
  { name: "Harim (city)" },
  { name: "Harod (spring)" },
  { name: "Harosheth (city)" },
  { name: "Harosheth of the Gentiles" },
  { name: "Havilah (land)" },
  { name: "Havoth-Jair (villages)" },
  { name: "Hazar-Addar (city)" },
  { name: "Hazar-Enan (city)" },
  { name: "Hazar-Gaddah (city)" },
  { name: "Hazar-Shual (city)" },
  { name: "Hazar-Susah (city)" },
  { name: "Hazar-Susim (city)" },
  { name: "Hazazon-Tamar (city)" },
  { name: "Hazeroth (place)" },
  { name: "Hazezon-Tamar (city)" },
  { name: "Hazor (city)" },
  { name: "Heaven (sky)" },
  { name: "Hebron (city)" },
  { name: "Helam (place)" },
  { name: "Helbah (city)" },
  { name: "Helbon (city)" },
  { name: "Helkath (city)" },
  { name: "Helkath-Hazzurim (field)" },
  { name: "Hell (place)" },
  { name: "Hena (city)" },
  { name: "Hepher (city)" },
  { name: "Hepherites (people)" },
  { name: "Hermon (mountain)" },
  { name: "Heshbon (city)" },
  { name: "Hethlon (place)" },
  { name: "Hezron (city)" },
  { name: "Hiddekel (river)" },
  { name: "Hiel (man)" },
  { name: "Hierapolis (city)" },
  { name: "Hil (city)" },
  { name: "Hilen (city)" },
  { name: "Hinnom (valley)" },
  { name: "Hirah (city)" },
  { name: "Hiram (city)" },
  { name: "Hittite (people)" },
  { name: "Hittites" },
  { name: "Hobah (place)" },
  { name: "Hoglah (city)" },
  { name: "Holon (city)" },
  { name: "Hophni (place)" },
  { name: "Horeb (mountain)" },
  { name: "Horem (city)" },
  { name: "Hormah (city)" },
  { name: "Horonaim (city)" },
  { name: "Hosah (city)" },
  { name: "Hukkok (city)" },
  { name: "Hukok (city)" },
  { name: "Hul (land)" },
  { name: "Huldah (prophetess)" },
  { name: "Humtah (city)" },
  { name: "Hur (mountain)" },
  { name: "Iconium (city)" },
  { name: "Idumea (region)" },
  { name: "Ijon (city)" },
  { name: "Illyricum (region)" },
  { name: "Immer (place)" },
  { name: "India (country)" },
  { name: "Iphedeiah (city)" },
  { name: "Iron (city)" },
  { name: "Ishmael (people)" },
  { name: "Ishmaelites" },
  { name: "Israel (nation)" },
  { name: "Issachar (tribe)" },
  { name: "Italy (country)" },
  { name: "Ithnan (city)" },
  { name: "Ithrite (family)" },
  { name: "Ittah-Kazin (city)" },
  { name: "Iyyim (city)" },
  { name: "Jabbok (river)" },
  { name: "Jabesh (city)" },
  { name: "Jabesh-Gilead (city)" },
  { name: "Jabneel (city)" },
  { name: "Jabneh (city)" },
  { name: "Jachin (pillar)" },
  { name: "Jagur (city)" },
  { name: "Jahaz (city)" },
  { name: "Jahzah (city)" },
  { name: "Janoah (city)" },
  { name: "Janohah (city)" },
  { name: "Janohem (city)" },
  { name: "Japha (city)" },
  { name: "Japhia (city)" },
  { name: "Jarmuth (city)" },
  { name: "Jattir (city)" },
  { name: "Jazer (city)" },
  { name: "Jebus (city)" },
  { name: "Jecoliah (city)" },
  { name: "Jedaiah (place)" },
  { name: "Jehoshaphat (valley)" },
  { name: "Jehovah-Jireh (altar)" },
  { name: "Jehovah-Nissi (altar)" },
  { name: "Jehovah-Shalom (altar)" },
  { name: "Jekabzeel (city)" },
  { name: "Jekameam (place)" },
  { name: "Jemnaan (city)" },
  { name: "Jenoah (city)" },
  { name: "Jerahmeel (land)" },
  { name: "Jericho (city)" },
  { name: "Jeruel (wilderness)" },
  { name: "Jerusalem (city)" },
  { name: "Jeshimon (wilderness)" },
  { name: "Jeshua (city)" },
  { name: "Jeshanah (city)" },
  { name: "Jethlah (city)" },
  { name: "Jezreel (city)" },
  { name: "Jezreel (valley)" },
  { name: "Jiphtah (city)" },
  { name: "Jiphtah-El (valley)" },
  { name: "Jiri (city)" },
  { name: "Jokdeam (city)" },
  { name: "Jokneam (city)" },
  { name: "Joktheel (city)" },
  { name: "Joppa (city)" },
  { name: "Jordan (river)" },
  { name: "Jotbah (city)" },
  { name: "Jotbathah (place)" },
  { name: "Judah (tribe)" },
  { name: "Judea (region)" },
  { name: "Juttah (city)" },
  { name: "Kabzeel (city)" },
  { name: "Kadesh (city)" },
  { name: "Kadesh-Barnea (oasis)" },
  { name: "Kamon (city)" },
  { name: "Kanah (city)" },
  { name: "Kanah (brook)" },
  { name: "Karka (city)" },
  { name: "Karkaa (city)" },
  { name: "Karkor (place)" },
  { name: "Karnaim (city)" },
  { name: "Kartah (city)" },
  { name: "Kartan (city)" },
  { name: "Kattath (city)" },
  { name: "Kedemoth (city)" },
  { name: "Kedesh (city)" },
  { name: "Kedesh in Galilee" },
  { name: "Kedesh-Naphtali (city)" },
  { name: "Kefar-Hammon (city)" },
  { name: "Kehelathah (place)" },
  { name: "Keilah (city)" },
  { name: "Kemuel (place)" },
  { name: "Kenath (city)" },
  { name: "Kenaz (city)" },
  { name: "Kerioth (city)" },
  { name: "Kesalon (city)" },
  { name: "Kesitah (place)" },
  { name: "Kibroth-Hattaavah (place)" },
  { name: "Kibzaim (city)" },
  { name: "Kidron (brook)" },
  { name: "Kidron Valley" },
  { name: "Kinah (city)" },
  { name: "Kir (city)" },
  { name: "Kir-Haraseth (city)" },
  { name: "Kir-Heres (city)" },
  { name: "Kir-Moab (city)" },
  { name: "Kirjath (city)" },
  { name: "Kirjath-Arba (city)" },
  { name: "Kirjath-Baal (city)" },
  { name: "Kirjath-Huzoth (city)" },
  { name: "Kirjath-Jearim (city)" },
  { name: "Kirjath-Sannah (city)" },
  { name: "Kirjath-Sepher (city)" },
  { name: "Kishon (river)" },
  { name: "Kitron (city)" },
  { name: "Kittim (island)" },
  { name: "Korah (place)" },
  { name: "Koz (city)" },
  { name: "Laadah (city)" },
  { name: "Laish (city)" },
  { name: "Lakkum (city)" },
  { name: "Lasea (city)" },
  { name: "Lasharon (city)" },
  { name: "Lasha (city)" },
  { name: "Lashkar (city)" },
  { name: "Lebaoth (city)" },
  { name: "Lebonah (city)" },
  { name: "Lebo-Hamath (city)" },
  { name: "Lehi (place)" },
  { name: "Leshem (city)" },
  { name: "Libnah (city)" },
  { name: "Libya (country)" },
  { name: "Lod (city)" },
  { name: "Lo-Debar (city)" },
  { name: "Lower Beth-Horon" },
  { name: "Lud (people)" },
  { name: "Luhith (city)" },
  { name: "Luz (city)" },
  { name: "Lydia (region)" },
  { name: "Lydda (city)" },
  { name: "Lysias (place)" },
  { name: "Lystra (city)" },
  { name: "Maacah (city)" },
  { name: "Maaleh-Acrabbim (ascent)" },
  { name: "Maarath (city)" },
  { name: "Macedonia (region)" },
  { name: "Machpelah (cave)" },
  { name: "Madai (people)" },
  { name: "Madmannah (city)" },
  { name: "Madon (city)" },
  { name: "Magdala (city)" },
  { name: "Magdiel (city)" },
  { name: "Magog (land)" },
  { name: "Mahalab (city)" },
  { name: "Mahanaim (city)" },
  { name: "Mahaneh-Dan (camp)" },
  { name: "Maon (city)" },
  { name: "Makaz (city)" },
  { name: "Makkedah (city)" },
  { name: "Malatha (city)" },
  { name: "Mallotha (city)" },
  { name: "Mamre (oak)" },
  { name: "Manahath (city)" },
  { name: "Manasseh (tribe)" },
  { name: "Marah (place)" },
  { name: "Mareshah (city)" },
  { name: "Maroth (city)" },
  { name: "Marsena (city)" },
  { name: "Mash (place)" },
  { name: "Masrekah (city)" },
  { name: "Massah (place)" },
  { name: "Mattanah (place)" },
  { name: "Media (country)" },
  { name: "Medes" },
  { name: "Megiddo (city)" },
  { name: "Melita (island)" },
  { name: "Memphis (city)" },
  { name: "Mephaath (city)" },
  { name: "Meribah (place)" },
  { name: "Merom (waters)" },
  { name: "Meroz (city)" },
  { name: "Mesech (people)" },
  { name: "Meshech (people)" },
  { name: "Meshullam (city)" },
  { name: "Mesopotamia (region)" },
  { name: "Methoar (city)" },
  { name: "Mevorach (city)" },
  { name: "Micha (city)" },
  { name: "Michmash (city)" },
  { name: "Middin (city)" },
  { name: "Migdal (city)" },
  { name: "Migdal-El (city)" },
  { name: "Migdal-Gad (city)" },
  { name: "Migron (place)" },
  { name: "Miletus (city)" },
  { name: "Minni (people)" },
  { name: "Minnith (city)" },
  { name: "Mishal (city)" },
  { name: "Mishma (city)" },
  { name: "Mishr (city)" },
  { name: "Misrephoth-Maim (place)" },
  { name: "Mitylene (city)" },
  { name: "Mizpah (city)" },
  { name: "Mizpeh (city)" },
  { name: "Mizpeh of Gilead" },
  { name: "Moab (country)" },
  { name: "Moabites" },
  { name: "Moffat (city)" },
  { name: "Moladah (city)" },
  { name: "Moreh (hill)" },
  { name: "Moresheth (city)" },
  { name: "Moresheth-Gath (city)" },
  { name: "Moriah (mountain)" },
  { name: "Mozah (city)" },
  { name: "Mysia (region)" },
  { name: "Naaran (city)" },
  { name: "Naarath (city)" },
  { name: "Nain (city)" },
  { name: "Naioth (place)" },
  { name: "Naphath (region)" },
  { name: "Naphath-Dor (region)" },
  { name: "Naphtali (tribe)" },
  { name: "Nazareth (city)" },
  { name: "Neapolis (city)" },
  { name: "Nebo (mountain)" },
  { name: "Nebuchadnezzar (city)" },
  { name: "Negeb (region)" },
  { name: "Negev (desert)" },
  { name: "Nekeb (city)" },
  { name: "Nephtoah (waters)" },
  { name: "Netaim (place)" },
  { name: "Netophah (city)" },
  { name: "New Heaven and New Earth" },
  { name: "Nezib (city)" },
  { name: "Nibshan (city)" },
  { name: "Nimrim (city)" },
  { name: "Nimrod (city)" },
  { name: "Nineveh (city)" },
  { name: "Nob (city)" },
  { name: "Nod (land)" },
  { name: "No (city)" },
  { name: "Noph (city)" },
  { name: "Nophah (city)" },
  { name: "Oboth (place)" },
  { name: "Ono (city)" },
  { name: "Ophel (hill)" },
  { name: "Ophir (land)" },
  { name: "Ophni (city)" },
  { name: "Ophrah (city)" },
  { name: "Ophrah of the Abiezrites" },
  { name: "Orontes (river)" },
  { name: "Paddan-Aram (region)" },
  { name: "Padan-Aram (region)" },
  { name: "Pai (city)" },
  { name: "Palace (building)" },
  { name: "Pamphylia (region)" },
  { name: "Paphos (city)" },
  { name: "Paran (wilderness)" },
  { name: "Parthia (country)" },
  { name: "Parthians" },
  { name: "Patara (city)" },
  { name: "Pathros (region)" },
  { name: "Patmos (island)" },
  { name: "Pela (city)" },
  { name: "Peleth (city)" },
  { name: "Pelusium (city)" },
  { name: "Peniel (place)" },
  { name: "Penuel (city)" },
  { name: "Perga (city)" },
  { name: "Pergamos (city)" },
  { name: "Pergamum (city)" },
  { name: "Perizzites (people)" },
  { name: "Persia (country)" },
  { name: "Persians" },
  { name: "Pethor (city)" },
  { name: "Pharpar (river)" },
  { name: "Phenice (harbor)" },
  { name: "Philadelphia (city)" },
  { name: "Philippi (city)" },
  { name: "Philistia (country)" },
  { name: "Philistim (people)" },
  { name: "Philistines" },
  { name: "Phoenicia (region)" },
  { name: "Phrygia (region)" },
  { name: "Pirathon (city)" },
  { name: "Pisgah (mountain)" },
  { name: "Pisidia (region)" },
  { name: "Pithom (city)" },
  { name: "Punon (place)" },
  { name: "Put (people)" },
  { name: "Puteoli (city)" },
  { name: "Qumran (community)" },
  { name: "Raamah (city)" },
  { name: "Raamses (city)" },
  { name: "Rabbah (city)" },
  { name: "Rabbath-Ammon (city)" },
  { name: "Rakkath (city)" },
  { name: "Ramah (city)" },
  { name: "Ramah of Benjamin" },
  { name: "Rama (city)" },
  { name: "Ramath-Lehi (place)" },
  { name: "Ramath-Mizpeh (city)" },
  { name: "Ramathaim-Zophim (city)" },
  { name: "Ramathite (place)" },
  { name: "Rameses (city)" },
  { name: "Ramoth (city)" },
  { name: "Ramoth-Gilead (city)" },
  { name: "Reed Sea" },
  { name: "Red Sea" },
  { name: "Rehob (city)" },
  { name: "Rehoboth (city)" },
  { name: "Rehoboth (well)" },
  { name: "Remeth (city)" },
  { name: "Rephidim (place)" },
  { name: "Rephaim (valley)" },
  { name: "Rezeph (city)" },
  { name: "Rezin (place)" },
  { name: "Rhegium (city)" },
  { name: "Riblah (city)" },
  { name: "Rimmon (city)" },
  { name: "Rimmon-Parez (place)" },
  { name: "Riphath (place)" },
  { name: "Rissah (place)" },
  { name: "Rithmah (place)" },
  { name: "River (generic)" },
  { name: "River Chebar" },
  { name: "River Euphrates" },
  { name: "River Jordan" },
  { name: "River Kishon" },
  { name: "River Nile" },
  { name: "River of Egypt" },
  { name: "River Ulai" },
  { name: "Road (generic)" },
  { name: "Rogelim (city)" },
  { name: "Rome (city)" },
  { name: "Ros (city)" },
  { name: "Rumah (city)" },
  { name: "Salamis (city)" },
  { name: "Salcah (city)" },
  { name: "Salchah (city)" },
  { name: "Salmah (city)" },
  { name: "Salmon (city)" },
  { name: "Salt Sea" },
  { name: "Salt Valley" },
  { name: "Samaria (city)" },
  { name: "Samaria (region)" },
  { name: "Samnium (region)" },
  { name: "Samothrace (island)" },
  { name: "Sansannah (city)" },
  { name: "Saphir (city)" },
  { name: "Sapphira (city)" },
  { name: "Sarid (city)" },
  { name: "Saron (region)" },
  { name: "Seba (people)" },
  { name: "Sebaste (city)" },
  { name: "Secacah (city)" },
  { name: "Sechu (place)" },
  { name: "Secundus (place)" },
  { name: "Sela (city)" },
  { name: "Selah (place)" },
  { name: "Seleucia (city)" },
  { name: "Sem (city)" },
  { name: "Senir (mountain)" },
  { name: "Sephar (city)" },
  { name: "Sepharad (place)" },
  { name: "Sepharvaim (city)" },
  { name: "Sepulchre (tomb)" },
  { name: "Serug (place)" },
  { name: "Shalisha (region)" },
  { name: "Shalem (city)" },
  { name: "Shamir (city)" },
  { name: "Shaphir (city)" },
  { name: "Sharon (plain)" },
  { name: "Sharuhen (city)" },
  { name: "Shaveh (valley)" },
  { name: "Shaveh-Kiriathaim (valley)" },
  { name: "Shear-Jashub (child)" },
  { name: "Sheba (country)" },
  { name: "Shechem (city)" },
  { name: "Sheep Gate" },
  { name: "Sheep Pool" },
  { name: "Sheol (underworld)" },
  { name: "Sheshach (city)" },
  { name: "Shihor (brook)" },
  { name: "Shihor-Libnath (brook)" },
  { name: "Shiloh (city)" },
  { name: "Shimron (city)" },
  { name: "Shimron-Meron (city)" },
  { name: "Shinab (city)" },
  { name: "Shinar (land)" },
  { name: "Shion (city)" },
  { name: "Shittim (place)" },
  { name: "Shoco (city)" },
  { name: "Shunem (city)" },
  { name: "Shur (wilderness)" },
  { name: "Shushan (city)" },
  { name: "Sibmah (city)" },
  { name: "Sichem (city)" },
  { name: "Siddim (valley)" },
  { name: "Sidon (city)" },
  { name: "Siloam (pool)" },
  { name: "Siloam Pool" },
  { name: "Simeon (tribe)" },
  { name: "Sin (wilderness)" },
  { name: "Sinai (mountain)" },
  { name: "Sion (hill)" },
  { name: "Sippai (city)" },
  { name: "Smyrna (city)" },
  { name: "Socho (city)" },
  { name: "Socoh (city)" },
  { name: "Sodom (city)" },
  { name: "Solem (city)" },
  { name: "Spain (country)" },
  { name: "Sparta (city)" },
  { name: "Succoth (city)" },
  { name: "Succoth (place)" },
  { name: "Sukkiims (people)" },
  { name: "Syracuse (city)" },
  { name: "Syria (country)" },
  { name: "Syrtis (sandbank)" },
  { name: "Tabernacle (tent)" },
  { name: "Tabor (mountain)" },
  { name: "Tadmor (city)" },
  { name: "Tahath (place)" },
  { name: "Tahpanhes (city)" },
  { name: "Tamar (city)" },
  { name: "Tanaach (city)" },
  { name: "Tanach (city)" },
  { name: "Tappuah (city)" },
  { name: "Taralah (city)" },
  { name: "Tarshish (city)" },
  { name: "Tarsus (city)" },
  { name: "Tartak (idol)" },
  { name: "Taurus (mountains)" },
  { name: "Tekoa (city)" },
  { name: "Tel-Abib (place)" },
  { name: "Tel-Harsha (place)" },
  { name: "Tel-Melah (place)" },
  { name: "Telaim (city)" },
  { name: "Telem (city)" },
  { name: "Tell-Harsha (place)" },
  { name: "Tell-Melah (place)" },
  { name: "Teman (city)" },
  { name: "Temple (building)" },
  { name: "Temple Mount" },
  { name: "Temple of Solomon" },
  { name: "Tent (dwelling)" },
  { name: "Terah (city)" },
  { name: "Thammuz (idol)" },
  { name: "Thebez (city)" },
  { name: "Thessalonica (city)" },
  { name: "Thyatira (city)" },
  { name: "Tiberias (city)" },
  { name: "Tiberias (Sea of)" },
  { name: "Tibni (city)" },
  { name: "Tigris (river)" },
  { name: "Timnah (city)" },
  { name: "Timnath (city)" },
  { name: "Timnath-Heres (city)" },
  { name: "Timnath-Serah (city)" },
  { name: "Tiphsah (city)" },
  { name: "Tirzah (city)" },
  { name: "Tishbe (city)" },
  { name: "Tob (land)" },
  { name: "Tophel (place)" },
  { name: "Tophet (place)" },
  { name: "Tou (city)" },
  { name: "Trachonitis (region)" },
  { name: "Troas (city)" },
  { name: "Tubal (people)" },
  { name: "Tyre (city)" },
  { name: "Ulam (city)" },
  { name: "Ulai (river)" },
  { name: "Upper Beth-Horon" },
  { name: "Ur (city)" },
  { name: "Urim (place)" },
  { name: "Uz (land)" },
  { name: "Uzal (city)" },
  { name: "Valley (generic)" },
  { name: "Valley of Achor" },
  { name: "Valley of Baca" },
  { name: "Valley of Berachah" },
  { name: "Valley of Elah" },
  { name: "Valley of Hinnom" },
  { name: "Valley of Jehoshaphat" },
  { name: "Valley of Jezreel" },
  { name: "Valley of Rephaim" },
  { name: "Valley of Shaveh" },
  { name: "Valley of Siddim" },
  { name: "Valley of Slaughter" },
  { name: "Valley of Succoth" },
  { name: "Valley of the Kings" },
  { name: "Valley of the Shadow of Death" },
  { name: "Valley of the Son of Hinnom" },
  { name: "Valley of Zephathah" },
  { name: "Water Gate" },
  { name: "Well (generic)" },
  { name: "Well of Beersheba" },
  { name: "Well of Harod" },
  { name: "Well of Sirah" },
  { name: "Wilderness (generic)" },
  { name: "Wilderness of Beersheba" },
  { name: "Wilderness of Beth-Aven" },
  { name: "Wilderness of Edom" },
  { name: "Wilderness of Engedi" },
  { name: "Wilderness of Gibeon" },
  { name: "Wilderness of Judea" },
  { name: "Wilderness of Maon" },
  { name: "Wilderness of Paran" },
  { name: "Wilderness of Shur" },
  { name: "Wilderness of Sin" },
  { name: "Wilderness of Tekoa" },
  { name: "Wilderness of Zin" },
  { name: "Wilderness of Ziph" },
  { name: "Zaanaim (oak)" },
  { name: "Zaanannim (oak)" },
  { name: "Zaavan (place)" },
  { name: "Zadok (place)" },
  { name: "Zair (city)" },
  { name: "Zalmon (mountain)" },
  { name: "Zanoah (city)" },
  { name: "Zaphon (city)" },
  { name: "Zarephath (city)" },
  { name: "Zarethan (city)" },
  { name: "Zarhites (place)" },
  { name: "Zeboim (city)" },
  { name: "Zeboiim (city)" },
  { name: "Zebulun (tribe)" },
  { name: "Zedad (city)" },
  { name: "Zelah (city)" },
  { name: "Zelzah (city)" },
  { name: "Zemaraim (city)" },
  { name: "Zenan (city)" },
  { name: "Zephath (city)" },
  { name: "Zephathah (valley)" },
  { name: "Zer (city)" },
  { name: "Zered (brook)" },
  { name: "Zeredah (city)" },
  { name: "Zereth-Shahar (city)" },
  { name: "Ziklag (city)" },
  { name: "Zin (wilderness)" },
  { name: "Zion (hill)" },
  { name: "Zior (city)" },
  { name: "Ziph (city)" },
  { name: "Ziph (wilderness)" },
  { name: "Zoan (city)" },
  { name: "Zoar (city)" },
  { name: "Zobah (kingdom)" },
  { name: "Zorah (city)" },
  { name: "Zupim (city)" },
  { name: "Zur (city)" },
  // User-requested additions (deduped)
  { name: "Ajalon Valley" },
  { name: "Ashteroth Karnaim" },
  { name: "Bitumen pits" },
  { name: "Brook" },
  { name: "Burning plain" },
  { name: "City" },
  { name: "City gate" },
  { name: "Country" },
  { name: "Deep" },
  { name: "Desert" },
  { name: "East" },
  { name: "East of Eden" },
  { name: "East of Jordan" },
  { name: "Ellasar" },
  { name: "Ephrathah" },
  { name: "Euphrates" },
  { name: "Field of Ephron" },
  { name: "Field of Zoar" },
  { name: "Fertile plain" },
  { name: "Fountain" },
  { name: "Garden" },
  { name: "Garden of Eden" },
  { name: "Gate" },
  { name: "Gathering of waters" },
  { name: "Goiim" },
  { name: "Great Sea" },
  { name: "Ground" },
  { name: "Hill" },
  { name: "Hill country" },
  { name: "House" },
  { name: "Jordan Valley" },
  { name: "Kedem" },
  { name: "Kiriath Arba" },
  { name: "Land" },
  { name: "Land of Canaan" },
  { name: "Land of Egypt" },
  { name: "Land of Havilah" },
  { name: "Land of Nod" },
  { name: "Land of Shinar" },
  { name: "Land of the East" },
  { name: "Lebanon" },
  { name: "Meadow" },
  { name: "Migdol" },
  { name: "Mountain" },
  { name: "Mountain east of Bethel" },
  { name: "Mountains of Ararat" },
  { name: "Mountains of the East" },
  { name: "Nahal Eshcol" },
  { name: "North" },
  { name: "Oak grove" },
  { name: "Oak of Mamre" },
  { name: "Pasture" },
  { name: "Pit" },
  { name: "Pishon" },
  { name: "Plain" },
  { name: "Plain of Jordan" },
  { name: "Plain of Mamre" },
  { name: "Rephaim Valley" },
  { name: "Resen" },
  { name: "Sea" },
  { name: "Seir" },
  { name: "South" },
  { name: "Spring" },
  { name: "Tower" },
  { name: "Ur of the Chaldeans" },
  { name: "Well of oath" },
  // User-requested additions (deduped) - batch 2
  { name: "Alush" },
  { name: "Baal Zephon" },
  { name: "Bitter waters" },
  { name: "Camp" },
  { name: "Camp by the sea" },
  { name: "City of Pithom" },
  { name: "City of Raamses" },
  { name: "Coast" },
  { name: "Desert of Shur" },
  { name: "Desert of Sin" },
  { name: "Desert of Sinai" },
  { name: "East wind" },
  { name: "Encampment" },
  { name: "Fortress" },
  { name: "Frontier" },
  { name: "Gulf" },
  { name: "Harbor" },
  { name: "House of bondage" },
  { name: "Land of Goshen" },
  { name: "Land of Midian" },
  { name: "Midian" },
  { name: "Mountain of God" },
  { name: "Oasis" },
  { name: "Pi Hahiroth" },
  { name: "Pillar of cloud" },
  { name: "Pillar of fire" },
  { name: "Ridge" },
  { name: "Royal house" },
  { name: "Sanctuary" },
  { name: "Sea shore" },
  { name: "Settlement" },
  { name: "Shore" },
  { name: "Store cities" },
  { name: "Stronghold" },
  { name: "Tent of meeting" },
  { name: "Territory" },
  { name: "Wadi" },
  { name: "Walled city" },
  { name: "Wasteland" },
  { name: "Water source" },
  { name: "Wells" },
  { name: "Wilderness of Etham" },
  { name: "Wilderness of Sinai" },
  // User-requested additions (deduped) - batch 3
  { name: "Altar of Burnt Offering" },
  { name: "Altar of Incense" },
  { name: "Assembly place" },
  { name: "Court" },
  { name: "Court of the tabernacle" },
  { name: "Entrance" },
  { name: "Entrance of the tent" },
  { name: "Entrance of the tent of meeting" },
  { name: "Inner sanctuary" },
  { name: "Outer court" },
  { name: "Outside the camp" },
  { name: "Tabernacle court" },
  { name: "Threshold" },
  // User-requested additions (deduped) - batch 4
  { name: "Abarim mountains" },
  { name: "Ar" },
  { name: "Bene Jaakan" },
  { name: "Border of Edom" },
  { name: "Border of Moab" },
  { name: "Brook Zered" },
  { name: "Camp by the Jordan" },
  { name: "City of refuge" },
  { name: "Desert of Kedemoth" },
  { name: "Desert of Moab" },
  { name: "Desert of Paran" },
  { name: "Desert of Zin" },
  { name: "Edom" },
  { name: "Hor" },
  { name: "Land of Bashan" },
  { name: "Land of Edom" },
  { name: "Land of Moab" },
  { name: "Livnah" },
  { name: "Medeba" },
  { name: "Mountains of Abarim" },
  { name: "Nahaliel" },
  { name: "Peor" },
  { name: "Plain of Moab" },
  { name: "Rimmon Perez" },
  { name: "Taberah" },
  { name: "Valley of Arnon" },
  { name: "Valley of Zered" },
  { name: "Wilderness of Moab" },
  { name: "Zalmonah" },
  { name: "Zared" },
  // User-requested additions (deduped) - batch 5
  { name: "Og’s territory" },
  { name: "Sihon’s territory" },
  // User-requested additions (deduped) - batch 6, 2026-02-17
  { name: "Achor Valley" },
  { name: "Anak" },
  { name: "Baalah" },
  { name: "Cave of Makkedah" },
  { name: "Ezion" },
  { name: "Kiriath Baal" },
  { name: "Kiriath Jearim" },
  { name: "Kiriath Sepher" },
  { name: "Lachish" },
  { name: "Land of the Hittites" },
  { name: "Mearah" },
  { name: "Mount Halak" },
  { name: "Mount Hebron" },
  { name: "Mountains of Israel" },
  { name: "Mountains of Judah" },
  { name: "Nahal" },
  { name: "Plain of Sharon" },
  { name: "Taanach" },
  { name: "Valley of Aijalon" },
  // 1 Samuel unique additions (2026-02-17, deduped)
  { name: "Baale Judah" },
  { name: "Beth-car" },
  { name: "Carmel" },
  { name: "City of David (reference stage)" },
  { name: "Country of the Philistines" },
  { name: "Dead Sea (Salt Sea reference)" },
  { name: "Eben-ezer" },
  { name: "En-dor" },
  { name: "Gebea" },
  { name: "Goshen (reference)" },
  { name: "Hill country of Ephraim" },
  { name: "Jerusalem (future reference context)" },
  { name: "Land of Israel" },
  { name: "Land of the Philistines" },
  { name: "Lebanon (reference)" },
  { name: "Mount Zion (reference trajectory)" },
  { name: "Philistia" },
  { name: "Ramah" },
  { name: "Red Sea (reference tradition)" },
  { name: "Wilderness of Maon" },
  { name: "Zoar (reference tradition)" },

// 1 Samuel integration (2026-02-17)
{ name: "Ashdod" },
{ name: "Ashkelon" },
{ name: "Ashur" },
{ name: "Azotus" },
{ name: "Baale Judah" },
{ name: "Beth-car" },
{ name: "Beth-shan" },
{ name: "Beth-shemesh" },
{ name: "Carmel" },
{ name: "City of David (reference stage)" },
{ name: "Country of the Philistines" },
{ name: "Dead Sea (Salt Sea reference)" },
{ name: "Eben-ezer" },
{ name: "En-dor" },
{ name: "Gebea" },
{ name: "Gittaim" },
{ name: "Goshen (reference)" },
{ name: "Hachilah" },
{ name: "Hill country of Ephraim" },
{ name: "Jerusalem (future reference context)" },
{ name: "Keilah" },
{ name: "Land of Israel" },
{ name: "Land of the Philistines" },
{ name: "Lebanon (reference)" },
{ name: "Maon" },
{ name: "Michmash" },
{ name: "Mount Ephraim" },
{ name: "Mount Gilboa" },
{ name: "Mount Zion (reference trajectory)" },
{ name: "Nob" },
{ name: "Philistia" },
{ name: "Ramah" },
{ name: "Red Sea (reference tradition)" },
{ name: "Salt Sea" },
{ name: "Shiloh" },
{ name: "Socoh" },
{ name: "Tabor" },
{ name: "Valley of Elah" },
{ name: "Wilderness of Maon" },
{ name: "Wilderness of Ziph" },
{ name: "Ziklag" },
{ name: "Ziph" },
{ name: "Zoar (reference tradition)" },
// End 1 Samuel integration
];

