import { GENESIS_CREATION_WEB_VERSES, type GenesisVerse } from "./creationOfWorldDeepNotes";

export const BIBLE_YEAR_GENESIS_WEB_VERSES: Record<number, GenesisVerse[]> = {
  ...GENESIS_CREATION_WEB_VERSES,
  5: [
    { verse: 1, text: "This is the book of the generations of Adam. In the day that God created man, he made him in God's likeness." },
    { verse: 2, text: "He created them male and female, and blessed them, and called their name Man, in the day when they were created." },
    { verse: 3, text: "Adam lived one hundred thirty years, and became the father of a son in his own likeness, after his image, and named him Seth." },
    { verse: 4, text: "The days of Adam after he became the father of Seth were eight hundred years, and he became the father of sons and daughters." },
    { verse: 5, text: "All the days that Adam lived were nine hundred thirty years, then he died." },
    { verse: 6, text: "Seth lived one hundred five years, and became the father of Enosh." },
    { verse: 7, text: "Seth lived after he became the father of Enosh eight hundred seven years, and became the father of sons and daughters." },
    { verse: 8, text: "All the days of Seth were nine hundred twelve years, then he died." },
    { verse: 9, text: "Enosh lived ninety years, and became the father of Kenan." },
    { verse: 10, text: "Enosh lived after he became the father of Kenan, eight hundred fifteen years, and became the father of sons and daughters." },
    { verse: 11, text: "All the days of Enosh were nine hundred five years, then he died." },
    { verse: 12, text: "Kenan lived seventy years, and became the father of Mahalalel." },
    { verse: 13, text: "Kenan lived after he became the father of Mahalalel eight hundred forty years, and became the father of sons and daughters." },
    { verse: 14, text: "All the days of Kenan were nine hundred ten years, then he died." },
    { verse: 15, text: "Mahalalel lived sixty-five years, and became the father of Jared." },
    { verse: 16, text: "Mahalalel lived after he became the father of Jared eight hundred thirty years, and became the father of sons and daughters." },
    { verse: 17, text: "All the days of Mahalalel were eight hundred ninety-five years, then he died." },
    { verse: 18, text: "Jared lived one hundred sixty-two years, and became the father of Enoch." },
    { verse: 19, text: "Jared lived after he became the father of Enoch eight hundred years, and became the father of sons and daughters." },
    { verse: 20, text: "All the days of Jared were nine hundred sixty-two years, then he died." },
    { verse: 21, text: "Enoch lived sixty-five years, and became the father of Methuselah." },
    { verse: 22, text: "Enoch walked with God after he became the father of Methuselah three hundred years, and became the father of sons and daughters." },
    { verse: 23, text: "All the days of Enoch were three hundred sixty-five years." },
    { verse: 24, text: "Enoch walked with God, and he was not, for God took him." },
    { verse: 25, text: "Methuselah lived one hundred eighty-seven years, and became the father of Lamech." },
    { verse: 26, text: "Methuselah lived after he became the father of Lamech seven hundred eighty-two years, and became the father of sons and daughters." },
    { verse: 27, text: "All the days of Methuselah were nine hundred sixty-nine years, then he died." },
    { verse: 28, text: "Lamech lived one hundred eighty-two years, and became the father of a son," },
    { verse: 29, text: "and he named him Noah, saying, \"This same will comfort us in our work and in the toil of our hands, because of the ground which Yahweh has cursed.\"" },
    { verse: 30, text: "Lamech lived after he became the father of Noah five hundred ninety-five years, and became the father of sons and daughters." },
    { verse: 31, text: "All the days of Lamech were seven hundred seventy-seven years, then he died." },
    { verse: 32, text: "Noah was five hundred years old, and Noah became the father of Shem, Ham, and Japheth." },
  ],
  6: [
    { verse: 1, text: "It happened, when men began to multiply on the surface of the ground, and daughters were born to them," },
    { verse: 2, text: "that God's sons saw that men's daughters were beautiful, and they took for themselves wives of all that they chose." },
    { verse: 3, text: "Yahweh said, \"My Spirit will not strive with man forever, because he also is flesh; yet will his days be one hundred twenty years.\"" },
    { verse: 4, text: "The Nephilim were in the earth in those days, and also after that, when God's sons came in to men's daughters. They bore children to them. Those were the mighty men who were of old, men of renown." },
    { verse: 5, text: "Yahweh saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil continually." },
    { verse: 6, text: "Yahweh was sorry that he had made man on the earth, and it grieved him in his heart." },
    { verse: 7, text: "Yahweh said, \"I will destroy man whom I have created from the surface of the ground; man, along with animals, creeping things, and birds of the sky; for I am sorry that I have made them.\"" },
    { verse: 8, text: "But Noah found favor in Yahweh's eyes." },
    { verse: 9, text: "This is the history of the generations of Noah. Noah was a righteous man, blameless among the people of his time. Noah walked with God." },
    { verse: 10, text: "Noah became the father of three sons: Shem, Ham, and Japheth." },
    { verse: 11, text: "The earth was corrupt before God, and the earth was filled with violence." },
    { verse: 12, text: "God saw the earth, and saw that it was corrupt, for all flesh had corrupted their way on the earth." },
    { verse: 13, text: "God said to Noah, \"The end of all flesh has come before me, for the earth is filled with violence through them. Behold, I will destroy them with the earth." },
    { verse: 14, text: "Make a ship of gopher wood. You shall make rooms in the ship, and shall seal it inside and outside with pitch." },
    { verse: 15, text: "This is how you shall make it. The length of the ship will be three hundred cubits, the breadth of it fifty cubits, and the height of it thirty cubits." },
    { verse: 16, text: "You shall make a roof in the ship, and to a cubit shall you finish it upward. You shall set the door of the ship in its side. You shall make it with lower, second, and third levels." },
    { verse: 17, text: "I, even I, do bring the flood of waters on this earth, to destroy all flesh having the breath of life from under the sky. Everything that is in the earth will die." },
    { verse: 18, text: "But I will establish my covenant with you. You shall come into the ship, you, your sons, your wife, and your sons' wives with you." },
    { verse: 19, text: "Of every living thing of all flesh, you shall bring two of every sort into the ship, to keep them alive with you. They shall be male and female." },
    { verse: 20, text: "Of the birds after their kind, of the livestock after their kind, of every creeping thing of the ground after its kind, two of every sort shall come to you, to keep them alive." },
    { verse: 21, text: "Take with you of all food that is eaten, and gather it to you; and it will be for food for you, and for them.\"" },
    { verse: 22, text: "Thus Noah did. According to all that God commanded him, so he did." },
  ],
  7: [
    { verse: 1, text: "Yahweh said to Noah, \"Come with all of your household into the ship, for I have seen your righteousness before me in this generation." },
    { verse: 2, text: "You shall take seven pairs of every clean animal with you, the male and his female. Of the animals that are not clean, take two, the male and his female." },
    { verse: 3, text: "Also of the birds of the sky, seven and seven, male and female, to keep seed alive on the surface of all the earth." },
    { verse: 4, text: "In seven days, I will cause it to rain on the earth for forty days and forty nights. Every living thing that I have made, I will destroy from the surface of the ground.\"" },
    { verse: 5, text: "Noah did everything that Yahweh commanded him." },
    { verse: 6, text: "Noah was six hundred years old when the flood of waters came on the earth." },
    { verse: 7, text: "Noah went into the ship with his sons, his wife, and his sons' wives, because of the waters of the flood." },
    { verse: 8, text: "Clean animals, animals that are not clean, birds, and everything that creeps on the ground" },
    { verse: 9, text: "went by pairs to Noah into the ship, male and female, as God commanded Noah." },
    { verse: 10, text: "It happened after the seven days, that the waters of the flood came on the earth." },
    { verse: 11, text: "In the six hundredth year of Noah's life, in the second month, on the seventeenth day of the month, on the same day all the fountains of the great deep were burst open, and the sky's windows were opened." },
    { verse: 12, text: "The rain was on the earth forty days and forty nights." },
    { verse: 13, text: "In the same day Noah, and Shem, Ham, and Japheth, the sons of Noah, and Noah's wife, and the three wives of his sons with them, entered into the ship;" },
    { verse: 14, text: "they, and every animal after its kind, all the livestock after their kind, every creeping thing that creeps on the earth after its kind, and every bird after its kind, every bird of every sort." },
    { verse: 15, text: "They went to Noah into the ship, by pairs of all flesh with the breath of life in them." },
    { verse: 16, text: "Those who went in, went in male and female of all flesh, as God commanded him; and Yahweh shut him in." },
    { verse: 17, text: "The flood was forty days on the earth. The waters increased, and lifted up the ship, and it was lifted up above the earth." },
    { verse: 18, text: "The waters prevailed, and increased greatly on the earth; and the ship floated on the surface of the waters." },
    { verse: 19, text: "The waters prevailed exceedingly on the earth. All the high mountains that were under the whole sky were covered." },
    { verse: 20, text: "The waters prevailed fifteen cubits upward, and the mountains were covered." },
    { verse: 21, text: "All flesh died that moved on the earth, including birds, livestock, animals, every creeping thing that creeps on the earth, and every man." },
    { verse: 22, text: "All in whose nostrils was the breath of the spirit of life, of all that was on the dry land, died." },
    { verse: 23, text: "Every living thing was destroyed that was on the surface of the ground, including man, livestock, creeping things, and birds of the sky. They were destroyed from the earth. Only Noah was left, and those who were with him in the ship." },
    { verse: 24, text: "The waters prevailed on the earth one hundred fifty days." },
  ],
};
