type CreationSection = {
  reference: string;
  title: string;
  verses: number[];
  notes: string[];
};

type CreationChapterNote = {
  chapter: number;
  title: string;
  hook: string;
  setup: string[];
  matters: string[];
  sections: CreationSection[];
  finalThought: string[];
  pause: string[];
  lesson: string;
};

type GenesisVerse = {
  verse: number;
  text: string;
};

const GENESIS_CREATION_KJV_VERSES: Record<number, GenesisVerse[]> = {
  1: [
    { verse: 1, text: "In the beginning God created the heaven and the earth." },
    { verse: 2, text: "And the earth was without form, and void; and darkness was upon the face of the deep. And the Spirit of God moved upon the face of the waters." },
    { verse: 3, text: "And God said, Let there be light: and there was light." },
    { verse: 4, text: "And God saw the light, that it was good: and God divided the light from the darkness." },
    { verse: 5, text: "And God called the light Day, and the darkness he called Night. And the evening and the morning were the first day." },
    { verse: 6, text: "And God said, Let there be a firmament in the midst of the waters, and let it divide the waters from the waters." },
    { verse: 7, text: "And God made the firmament, and divided the waters which were under the firmament from the waters which were above the firmament: and it was so." },
    { verse: 8, text: "And God called the firmament Heaven. And the evening and the morning were the second day." },
    { verse: 9, text: "And God said, Let the waters under the heaven be gathered together unto one place, and let the dry land appear: and it was so." },
    { verse: 10, text: "And God called the dry land Earth; and the gathering together of the waters called he Seas: and God saw that it was good." },
    { verse: 11, text: "And God said, Let the earth bring forth grass, the herb yielding seed, and the fruit tree yielding fruit after his kind, whose seed is in itself, upon the earth: and it was so." },
    { verse: 12, text: "And the earth brought forth grass, and herb yielding seed after his kind, and the tree yielding fruit, whose seed was in itself, after his kind: and God saw that it was good." },
    { verse: 13, text: "And the evening and the morning were the third day." },
    { verse: 14, text: "And God said, Let there be lights in the firmament of the heaven to divide the day from the night; and let them be for signs, and for seasons, and for days, and years:" },
    { verse: 15, text: "And let them be for lights in the firmament of the heaven to give light upon the earth: and it was so." },
    { verse: 16, text: "And God made two great lights; the greater light to rule the day, and the lesser light to rule the night: he made the stars also." },
    { verse: 17, text: "And God set them in the firmament of the heaven to give light upon the earth," },
    { verse: 18, text: "And to rule over the day and over the night, and to divide the light from the darkness: and God saw that it was good." },
    { verse: 19, text: "And the evening and the morning were the fourth day." },
    { verse: 20, text: "And God said, Let the waters bring forth abundantly the moving creature that hath life, and fowl that may fly above the earth in the open firmament of heaven." },
    { verse: 21, text: "And God created great whales, and every living creature that moveth, which the waters brought forth abundantly, after their kind, and every winged fowl after his kind: and God saw that it was good." },
    { verse: 22, text: "And God blessed them, saying, Be fruitful, and multiply, and fill the waters in the seas, and let fowl multiply in the earth." },
    { verse: 23, text: "And the evening and the morning were the fifth day." },
    { verse: 24, text: "And God said, Let the earth bring forth the living creature after his kind, cattle, and creeping thing, and beast of the earth after his kind: and it was so." },
    { verse: 25, text: "And God made the beast of the earth after his kind, and cattle after their kind, and every thing that creepeth upon the earth after his kind: and God saw that it was good." },
    { verse: 26, text: "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth." },
    { verse: 27, text: "So God created man in his own image, in the image of God created he him; male and female created he them." },
    { verse: 28, text: "And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth." },
    { verse: 29, text: "And God said, Behold, I have given you every herb bearing seed, which is upon the face of all the earth, and every tree, in the which is the fruit of a tree yielding seed; to you it shall be for meat." },
    { verse: 30, text: "And to every beast of the earth, and to every fowl of the air, and to every thing that creepeth upon the earth, wherein there is life, I have given every green herb for meat: and it was so." },
    { verse: 31, text: "And God saw every thing that he had made, and, behold, it was very good. And the evening and the morning were the sixth day." },
  ],
  2: [
    { verse: 1, text: "Thus the heavens and the earth were finished, and all the host of them." },
    { verse: 2, text: "And on the seventh day God ended his work which he had made; and he rested on the seventh day from all his work which he had made." },
    { verse: 3, text: "And God blessed the seventh day, and sanctified it: because that in it he had rested from all his work which God created and made." },
    { verse: 4, text: "These are the generations of the heavens and of the earth when they were created, in the day that the LORD God made the earth and the heavens," },
    { verse: 5, text: "And every plant of the field before it was in the earth, and every herb of the field before it grew: for the LORD God had not caused it to rain upon the earth, and there was not a man to till the ground." },
    { verse: 6, text: "But there went up a mist from the earth, and watered the whole face of the ground." },
    { verse: 7, text: "And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul." },
    { verse: 8, text: "And the LORD God planted a garden eastward in Eden; and there he put the man whom he had formed." },
    { verse: 9, text: "And out of the ground made the LORD God to grow every tree that is pleasant to the sight, and good for food; the tree of life also in the midst of the garden, and the tree of knowledge of good and evil." },
    { verse: 10, text: "And a river went out of Eden to water the garden; and from thence it was parted, and became into four heads." },
    { verse: 11, text: "The name of the first is Pison: that is it which compasseth the whole land of Havilah, where there is gold;" },
    { verse: 12, text: "And the gold of that land is good: there is bdellium and the onyx stone." },
    { verse: 13, text: "And the name of the second river is Gihon: the same is it that compasseth the whole land of Ethiopia." },
    { verse: 14, text: "And the name of the third river is Hiddekel: that is it which goeth toward the east of Assyria. And the fourth river is Euphrates." },
    { verse: 15, text: "And the LORD God took the man, and put him into the garden of Eden to dress it and to keep it." },
    { verse: 16, text: "And the LORD God commanded the man, saying, Of every tree of the garden thou mayest freely eat:" },
    { verse: 17, text: "But of the tree of the knowledge of good and evil, thou shalt not eat of it: for in the day that thou eatest thereof thou shalt surely die." },
    { verse: 18, text: "And the LORD God said, It is not good that the man should be alone; I will make him an help meet for him." },
    { verse: 19, text: "And out of the ground the LORD God formed every beast of the field, and every fowl of the air; and brought them unto Adam to see what he would call them: and whatsoever Adam called every living creature, that was the name thereof." },
    { verse: 20, text: "And Adam gave names to all cattle, and to the fowl of the air, and to every beast of the field; but for Adam there was not found an help meet for him." },
    { verse: 21, text: "And the LORD God caused a deep sleep to fall upon Adam and he slept: and he took one of his ribs, and closed up the flesh instead thereof;" },
    { verse: 22, text: "And the rib, which the LORD God had taken from man, made he a woman, and brought her unto the man." },
    { verse: 23, text: "And Adam said, This is now bone of my bones, and flesh of my flesh: she shall be called Woman, because she was taken out of Man." },
    { verse: 24, text: "Therefore shall a man leave his father and his mother, and shall cleave unto his wife: and they shall be one flesh." },
    { verse: 25, text: "And they were both naked, the man and his wife, and were not ashamed." },
  ],
};

function verseText(chapter: number, verse: number) {
  return GENESIS_CREATION_KJV_VERSES[chapter]?.find((item) => item.verse === verse)?.text || "";
}

function verseCallouts(chapter: number, verses: number[]) {
  return verses.map((verse) => `> **${verse}** ${verseText(chapter, verse)}`).join("\n\n");
}

function buildSection(chapter: number, section: CreationSection) {
  return `## ${section.reference}\n\n# ${section.title}\n\n${verseCallouts(chapter, section.verses)}\n\n${section.notes.join("\n\n")}`;
}

function buildCreationNotes(chapter: CreationChapterNote) {
  return `# Genesis ${chapter.chapter}\n\n# ${chapter.title}\n\n${chapter.hook}\n\n${chapter.setup.join("\n\n")}\n\n## Why Genesis ${chapter.chapter} Matters\n\n${chapter.matters.map((item) => `- ${item}`).join("\n")}\n\n## Chapter Flow\n\n${chapter.sections.map((section) => `- 📍 ${section.title}`).join("\n")}\n\n# Deep Chapter Notes\n\n${chapter.sections.map((section) => buildSection(chapter.chapter, section)).join("\n\n")}\n\n# Final Thought on Genesis ${chapter.chapter}\n\n${chapter.finalThought.map((item) => `- ${item}`).join("\n")}\n\n# Pause and Reflect\n\n${chapter.pause.map((item) => `- ${item}`).join("\n")}\n\n# The Big Lesson of Genesis ${chapter.chapter}\n\n${chapter.lesson}`;
}

const creationNotes: CreationChapterNote[] = [
  {
    chapter: 1,
    title: "The God Who Speaks Everything Into Order",
    hook: "Genesis 1 opens before there are nations, temples, kings, cities, families, or graves.",
    setup: [
      "There is no Israel yet. No Abraham. No Moses. No David. No Jerusalem. No cross on a hill.",
      "The Bible begins bigger than all of that.",
      "It begins with God, creation, light, order, life, blessing, and humanity made with purpose.",
      "Genesis 1 is not written like a science textbook. It is written like a theological doorway. It tells us who made the world, who rules it, why creation is good, and why human beings matter.",
    ],
    matters: [
      "🌌 It introduces God as Creator before anything else exists.",
      "🗣️ It shows creation responding to God's word.",
      "🌊 It moves from darkness and deep waters into order and life.",
      "👤 It explains human dignity through the image of God.",
      "🌍 It gives humanity purpose inside God's world.",
      "✨ It repeats that creation is good before sin ever enters the story.",
    ],
    sections: [
      {
        reference: "Genesis 1:1 to 2",
        title: "In the Beginning",
        verses: [1, 2],
        notes: [
          "Before Genesis tells us what people do, it tells us what God does.",
          "God creates.",
          "That means the Bible does not begin with humanity searching for God. It begins with God already there, already acting, already bringing reality into existence.",
          "### 🌌 In The Beginning",
          "The phrase `In the beginning` means the story starts at the start of creation itself.",
          "Not the beginning of God.",
          "The beginning of the heavens and the earth.",
          "That matters because God is not introduced as part of creation. He is outside it, before it, and Lord over it.",
          "### 🌍 Heaven And Earth",
          "In the KJV, `heaven and earth` means the whole created order.",
          "It is a way of saying everything above, everything below, everything visible, and everything humans will ever live inside.",
          "Modern readers sometimes hear `heaven` and think only of the place believers go after death. But here the word points to the sky, the heavens, and the upper realm of creation.",
          "Genesis is saying:",
          "🌌 God made the skies",
          "🌍 God made the earth",
          "🌊 God rules the waters",
          "✨ God owns the whole story before people ever step into it",
          "### 🌊 Without Form And Void",
          "Verse 2 says the earth was `without form, and void.`",
          "`Without form` means unshaped.",
          "`Void` means empty.",
          "So the picture is not a finished world yet. It is creation waiting to be ordered and filled.",
          "Think of a dark, watery, unfinished world.",
          "Not evil.",
          "Not outside God's control.",
          "Unformed and unfilled.",
          "That sets up the pattern of the chapter.",
          "God will form what is unformed.",
          "God will fill what is empty.",
          "### 🕊️ The Spirit Moving Over The Waters",
          "The Spirit of God moves upon the face of the waters.",
          "The Hebrew image is gentle but powerful. The word can carry the idea of hovering, like a bird over its young.",
          "Before light appears, before land appears, before animals appear, God's Spirit is already present.",
          "That means darkness is not God's absence.",
          "The deep is not outside His reach.",
          "The waters are not stronger than Him.",
          "The first scene of the Bible is dark, but it is not hopeless.",
        ],
      },
      {
        reference: "Genesis 1:3 to 5",
        title: "Light Breaks Into The Darkness",
        verses: [3, 4, 5],
        notes: [
          "The first recorded words of God in Scripture are simple and powerful.",
          "`Let there be light.`",
          "And light comes.",
          "### 🗣️ God Speaks",
          "Genesis 1 keeps repeating this pattern:",
          "🗣️ God speaks",
          "🌍 creation responds",
          "👀 God sees",
          "✨ God calls it good",
          "⏳ evening and morning mark the day",
          "That rhythm matters. Creation is not a fight between equal powers. God does not struggle to create. He speaks.",
          "### 💡 Light Before The Sun",
          "Modern readers often notice that light appears before the sun and moon are named on day four.",
          "That is not an accident.",
          "Genesis is showing that light does not depend on pagan sun gods or heavenly bodies. Light comes because God commands it.",
          "The sun will later serve God's order, but it is not the source of divine power.",
          "### ⚖️ Separation",
          "God divides light from darkness.",
          "This is one of the first acts of order in the Bible.",
          "God separates.",
          "He names.",
          "He gives boundaries.",
          "This matters because creation is not only about making things. It is about putting things in their proper place.",
          "### ⏳ Evening And Morning",
          "The day is marked as evening and morning.",
          "This gives Genesis 1 its steady pulse.",
          "There is movement.",
          "There is rhythm.",
          "There is time.",
          "The God who made light also gives creation a pattern to live inside.",
        ],
      },
      {
        reference: "Genesis 1:6 to 8",
        title: "The Firmament And The Waters",
        verses: [6, 7, 8],
        notes: [
          "Now God speaks into the waters.",
          "The deep that looked wild and overwhelming in verse 2 is now being divided and ordered.",
          "### 📖 What Is The Firmament?",
          "`Firmament` is an older KJV word.",
          "It means the expanse or sky.",
          "Ancient people looked up and saw the sky as a great spread-out space above them, the place where clouds, birds, and heavenly lights belonged.",
          "So when Genesis talks about the firmament dividing waters above and waters below, it is speaking in the language of how the ancient world pictured the sky and weather.",
          "### 🌊 Waters Above And Waters Below",
          "To ancient readers, water was powerful.",
          "Water could bring life through rain.",
          "Water could also bring danger through floods and seas.",
          "Genesis shows God placing boundaries on the waters.",
          "That is huge.",
          "The waters do not rule themselves.",
          "God rules them.",
          "### ☁️ Heaven",
          "God calls the firmament `Heaven.`",
          "Here that word points to the sky above the earth.",
          "The same chapter uses heaven language for the expanse where birds fly and lights appear.",
          "This helps modern readers slow down.",
          "In Genesis 1, heaven can mean the sky or the heavens, not only the final dwelling place of God.",
        ],
      },
      {
        reference: "Genesis 1:9 to 13",
        title: "Land Appears And Life Begins To Grow",
        verses: [9, 10, 11, 12, 13],
        notes: [
          "Now the world begins to look like a place where life can live.",
          "The waters gather.",
          "Dry land appears.",
          "Plants begin to grow.",
          "### 🌍 Dry Land Appears",
          "God calls the dry land Earth and the gathered waters Seas.",
          "Naming is authority.",
          "When God names Day, Night, Heaven, Earth, and Seas, He is not just labeling things. He is ruling them.",
          "### 🌱 After His Kind",
          "The plants produce `after his kind.`",
          "That phrase means creation has order built into it.",
          "Fruit trees produce fruit.",
          "Seeds reproduce according to their kind.",
          "The world is not random in Genesis 1. It is fruitful, structured, and dependable.",
          "### 🧬 Seed In Itself",
          "The phrase about seed matters.",
          "God creates living systems that can keep producing life.",
          "The tree is not only beautiful for one day. It carries future fruit inside it.",
          "That is part of the goodness of creation.",
          "🌱 life can multiply",
          "🍎 food can be provided",
          "🌍 the earth can sustain creatures",
          "⏳ one generation can lead to another",
          "### ✨ God Saw That It Was Good",
          "Again, God calls it good.",
          "Not sinful.",
          "Not disposable.",
          "Good.",
          "That matters for the whole Bible. Redemption is not God throwing creation away. It is God rescuing what He made good.",
        ],
      },
      {
        reference: "Genesis 1:14 to 19",
        title: "The Sun, Moon, And Stars Take Their Place",
        verses: [14, 15, 16, 17, 18, 19],
        notes: [
          "Day four fills the sky with lights.",
          "But Genesis describes them in a surprisingly quiet way.",
          "It does not even use the words sun and moon here. It says greater light and lesser light.",
          "### ☀️ Why That Matters",
          "In the ancient world, many nations worshiped the sun, moon, and stars.",
          "They treated them like gods.",
          "Genesis does the opposite.",
          "The heavenly lights are not gods.",
          "They are lamps in God's sky.",
          "They do not rule over God.",
          "They serve the order God gives them.",
          "### 📅 Signs, Seasons, Days, And Years",
          "The lights help mark time.",
          "This matters because human life needs rhythm.",
          "📅 seasons for planting and harvesting",
          "🌙 days and nights for work and rest",
          "⏳ years for memory and history",
          "🙏 appointed times for worship later in Israel's life",
          "God is not only making objects. He is making a world humans can live in and understand.",
          "### ✨ He Made The Stars Also",
          "That little line is almost shocking.",
          "The stars are enormous to us.",
          "But Genesis mentions them almost casually.",
          "`He made the stars also.`",
          "That is not because stars are small.",
          "It is because God is that great.",
        ],
      },
      {
        reference: "Genesis 1:20 to 25",
        title: "The Waters, Sky, And Land Fill With Life",
        verses: [20, 21, 22, 23, 24, 25],
        notes: [
          "The empty places are now being filled.",
          "Waters receive living creatures.",
          "The sky receives birds.",
          "The land receives animals.",
          "### 🐋 Great Whales",
          "The KJV says `great whales.`",
          "The Hebrew word can refer to large sea creatures or great creatures of the deep.",
          "This matters because ancient people often feared the sea and the huge creatures in it.",
          "Genesis says even the great creatures belong to God's creation.",
          "They are not rival gods.",
          "They are made things.",
          "### 🧬 Be Fruitful And Multiply",
          "This is the first blessing spoken over living creatures.",
          "`Be fruitful` means produce life.",
          "`Multiply` means increase and fill the place God gave you.",
          "Creation is meant to overflow with life.",
          "### 🐄 Cattle, Creeping Things, And Beasts",
          "The land animals are grouped in a way ancient readers would recognize:",
          "🐄 cattle: domesticated animals",
          "🐍 creeping things: smaller ground creatures",
          "🦁 beasts of the earth: wild animals",
          "God's world is full, layered, and alive.",
          "And before humanity appears, the world is already called good.",
        ],
      },
      {
        reference: "Genesis 1:26 to 31",
        title: "Humanity Is Made In God's Image",
        verses: [26, 27, 28, 29, 30, 31],
        notes: [
          "This is the peak of Genesis 1.",
          "Everything slows down.",
          "God does not simply say, `Let there be man.`",
          "He says, `Let us make man in our image, after our likeness.`",
          "### 👤 Image And Likeness",
          "`Image` and `likeness` mean humans are made to reflect God in the world.",
          "In the ancient Near East, kings were often called images of a god.",
          "Genesis takes that royal idea and spreads it to humanity.",
          "Not just Pharaoh.",
          "Not just kings.",
          "Not just the powerful.",
          "Male and female are created in God's image.",
          "That gives every human being dignity before anything they achieve.",
          "### 👑 Dominion",
          "`Dominion` means rule or stewardship.",
          "It does not mean abuse creation.",
          "It means humanity is given responsibility under God.",
          "Humans are royal representatives in God's world.",
          "A helpful way to say it:",
          "👑 God is the King",
          "👤 humans bear His image",
          "🌍 creation is entrusted to their care",
          "⚖️ rule must reflect God's goodness",
          "### 🌍 Subdue The Earth",
          "`Subdue` can sound harsh to modern ears.",
          "Here it means bringing the earth's potential into ordered, fruitful life under God's command.",
          "The world is good, but it still needs cultivation.",
          "Fields need tending.",
          "Animals need care.",
          "Human society needs wisdom.",
          "Genesis gives humans work before sin enters the story.",
          "Work is not a curse.",
          "It is part of human purpose.",
          "### 💍 Male And Female",
          "Verse 27 names both male and female inside the image of God.",
          "That matters deeply.",
          "Women are not an afterthought.",
          "Men are not more image-bearing than women.",
          "Together, humanity reflects God in the world.",
          "### 🍞 Food And Peace",
          "God gives plants for food.",
          "The picture is peaceful provision.",
          "There is no violence in the scene.",
          "No fear.",
          "No shame.",
          "No death clouding the chapter yet.",
          "### ✨ Very Good",
          "After humanity is created, God sees everything He made and calls it `very good.`",
          "That phrase matters.",
          "Creation is not barely acceptable.",
          "It is not an accident.",
          "It is very good because it reflects the intention of a good Creator.",
        ],
      },
    ],
    finalThought: [
      "Genesis 1 teaches that the world begins with God, not chaos.",
      "It teaches that creation is ordered, purposeful, and good.",
      "It teaches that human beings have dignity because God made them in His image.",
      "And it teaches that life is meant to be lived under God's rule, not apart from it.",
    ],
    pause: [
      "Where do you need to remember that God brings order into places that feel dark or unfinished?",
      "How does being made in God's image change the way you see yourself?",
      "How should it change the way you treat other people?",
      "What part of creation helps you notice God's wisdom and beauty?",
    ],
    lesson:
      "Genesis 1 teaches that everything begins with God. Before there is sin, pain, failure, or fear, there is a good Creator making a good world and placing humanity inside it with dignity, purpose, and blessing.",
  },
  {
    chapter: 2,
    title: "Eden, Humanity, And Life With God",
    hook: "Genesis 2 slows the camera down.",
    setup: [
      "Genesis 1 showed the whole creation week like a wide shot of the universe.",
      "Genesis 2 zooms in.",
      "Now we see the garden. The dust. The breath. The trees. The command. The animals. The first relationship.",
      "This chapter is not a second, competing creation story. It is a closer look at humanity's place inside God's good world.",
    ],
    matters: [
      "🛑 It introduces holy rest and completion.",
      "👤 It shows humanity formed from dust and filled with breath.",
      "🌱 It places Adam in Eden with work and responsibility.",
      "⚖️ It introduces the first command and the possibility of disobedience.",
      "💍 It shows companionship, marriage, and one flesh union.",
      "🙏 It shows human life beginning in intimacy, not shame.",
    ],
    sections: [
      {
        reference: "Genesis 2:1 to 3",
        title: "God Rests And Blesses The Seventh Day",
        verses: [1, 2, 3],
        notes: [
          "Genesis 2 begins with completion.",
          "The heavens and earth are finished.",
          "The world is no longer without form and void. It has been shaped and filled.",
          "### 🛑 God Rested",
          "God does not rest because He is tired.",
          "He rests because the work is complete.",
          "This is royal rest.",
          "The Creator has ordered His world.",
          "Now He delights in it.",
          "### 🙏 Sanctified",
          "`Sanctified` means set apart as holy.",
          "This is the first thing in the Bible called holy.",
          "Not a mountain.",
          "Not a temple.",
          "Not a priest.",
          "A day.",
          "That tells us something beautiful.",
          "Time itself can become sacred when it is received from God.",
          "### ⏳ Sabbath Before Sinai",
          "The formal Sabbath command comes later through Moses.",
          "But Genesis roots the pattern of rest in creation itself.",
          "Human beings were not made only to produce.",
          "We were made to live in rhythm with God.",
        ],
      },
      {
        reference: "Genesis 2:4 to 9",
        title: "Adam Formed And Eden Planted",
        verses: [4, 5, 6, 7, 8, 9],
        notes: [
          "Now Genesis turns from the wide creation account to the human story.",
          "Verse 4 says, `These are the generations.`",
          "### 📖 These Are The Generations",
          "This phrase is important in Genesis.",
          "It points to the Hebrew word `toledot`, meaning the record or story of what came from something.",
          "Here it introduces the story that comes from the heavens and the earth.",
          "The focus is about to land on humanity.",
          "### 🌧️ No Rain, No Man To Till",
          "Verse 5 says there was no man to till the ground.",
          "`Till` means work, cultivate, or serve the soil.",
          "Genesis is already showing that the ground and humanity belong together.",
          "The earth has potential, but humanity is called to cultivate it.",
          "### 👤 Formed From Dust",
          "Verse 7 says God formed man from the dust of the ground.",
          "`Formed` is a hands-on word.",
          "It can picture a potter shaping clay.",
          "Genesis 1 showed God speaking humanity into the story.",
          "Genesis 2 shows God shaping humanity personally.",
          "### 🌬️ Breath Of Life",
          "God breathes into Adam's nostrils the breath of life.",
          "This is intimate.",
          "Human beings are dust and breath.",
          "Humble and glorious.",
          "Earthy and spiritual.",
          "Dependent and dignified.",
          "### 🌱 Eden",
          "God plants a garden eastward in Eden.",
          "Eden is not pictured as a wild jungle.",
          "It is a prepared place of beauty, food, life, and fellowship.",
          "The garden is a sacred space where humanity lives near God.",
          "### 🌳 Two Trees",
          "The tree of life points to life with God.",
          "The tree of knowledge of good and evil will become the place of testing.",
          "The chapter is peaceful, but there is already a real choice in the garden.",
        ],
      },
      {
        reference: "Genesis 2:10 to 14",
        title: "The Rivers Of Eden",
        verses: [10, 11, 12, 13, 14],
        notes: [
          "These verses can feel like geography details people want to skip.",
          "But Genesis is telling us Eden was a place of abundance.",
          "### 🌊 A River Went Out",
          "The river waters the garden and then divides into four heads.",
          "Water in the ancient world meant life.",
          "No water, no crops.",
          "No crops, no people.",
          "So Eden is pictured as a source of life flowing outward.",
          "### 🗺️ Pison, Gihon, Hiddekel, Euphrates",
          "Some of these names are hard to identify with certainty today.",
          "Hiddekel is usually connected with the Tigris.",
          "Euphrates is still known.",
          "The point is not to give us a modern GPS pin.",
          "The point is to show that Eden is connected to real geography, real rivers, and real abundance.",
          "### 💰 Gold, Bdellium, And Onyx",
          "Verse 12 mentions gold, bdellium, and onyx.",
          "Bdellium was likely a precious resin or stone-like material.",
          "Onyx was a valued stone.",
          "These details make Eden feel rich and beautiful.",
          "Creation is not ugly or empty.",
          "It is full of good gifts.",
        ],
      },
      {
        reference: "Genesis 2:15 to 17",
        title: "The Garden Command",
        verses: [15, 16, 17],
        notes: [
          "God places Adam in the garden with a calling and a command.",
          "### 🌱 Dress It And Keep It",
          "`Dress` means cultivate or work.",
          "`Keep` means guard, watch, or preserve.",
          "Adam is not placed in Eden to be lazy.",
          "He is there to serve and protect what God has made.",
          "This is important.",
          "Work exists before the fall.",
          "Responsibility exists before sin.",
          "Purpose is part of paradise.",
          "### 🍎 Freely Eat",
          "God's command begins with generosity.",
          "Before God says what Adam may not eat, He says what Adam may eat.",
          "`Of every tree of the garden thou mayest freely eat.`",
          "The first command is surrounded by abundance.",
          "### ⚖️ The Forbidden Tree",
          "The tree of the knowledge of good and evil introduces obedience.",
          "Humanity is free, but not autonomous.",
          "That means humans do not get to define good and evil apart from God.",
          "Trust is built into the garden.",
          "### 💀 Thou Shalt Surely Die",
          "The warning is serious.",
          "Death has not entered the story yet, but the possibility is named.",
          "The command is not random.",
          "It teaches Adam that life depends on trusting God's word.",
        ],
      },
      {
        reference: "Genesis 2:18 to 25",
        title: "Eve Created And The First Marriage",
        verses: [18, 19, 20, 21, 22, 23, 24, 25],
        notes: [
          "For the first time in the Bible, God says something is not good.",
          "Not sin.",
          "Not rebellion.",
          "Aloneness.",
          "### 💔 Not Good To Be Alone",
          "Genesis 1 repeated `good` again and again.",
          "Now Genesis 2 says the man being alone is not good.",
          "Human beings were made for relationship.",
          "With God.",
          "With creation.",
          "With one another.",
          "### 📖 Help Meet",
          "`Help meet` is often misunderstood.",
          "It does not mean a weak assistant.",
          "`Help` in the Old Testament is often used of God helping His people.",
          "`Meet` means suitable, corresponding, fitting.",
          "So the idea is a helper who corresponds to him.",
          "Someone strong enough to stand beside him.",
          "Someone matching him in dignity.",
          "### 🦁 Naming The Animals",
          "God brings the animals to Adam.",
          "Adam names them.",
          "Naming again shows discernment and authority.",
          "But as Adam names creature after creature, the lesson becomes clear.",
          "There is no partner corresponding to him among the animals.",
          "He is part of creation, but he is not the same as the animals.",
          "### 🦴 The Rib",
          "God forms the woman from Adam's side.",
          "Not from his head to rule over him.",
          "Not from his feet to be trampled by him.",
          "From his side.",
          "The picture is closeness, equality, and shared life.",
          "### 💍 Bone Of My Bones",
          "Adam's first recorded words are poetry.",
          "He recognizes her as like him and yet distinct from him.",
          "This is joy.",
          "This is recognition.",
          "This is the first human relationship without shame.",
          "### 🧬 One Flesh",
          "Verse 24 becomes one of the Bible's foundation texts for marriage.",
          "A man leaves father and mother and cleaves to his wife.",
          "`Cleave` means cling, hold fast, or be joined closely.",
          "Marriage is pictured as covenant loyalty and shared life.",
          "### 🙏 Naked And Not Ashamed",
          "The chapter ends with total innocence.",
          "No hiding.",
          "No fear.",
          "No using each other.",
          "No shame.",
          "That is the beauty of Eden before sin enters.",
          "Humanity is fully known and not yet broken by guilt.",
        ],
      },
    ],
    finalThought: [
      "Genesis 2 teaches that human life is both humble and holy.",
      "We are dust, but God breathes life into us.",
      "We are workers, but not machines.",
      "We are made for relationship, responsibility, worship, rest, and love.",
    ],
    pause: [
      "What does it mean to you that God formed humanity personally?",
      "Where do you need a healthier rhythm of work and rest?",
      "How does Genesis 2 shape the way you think about relationships?",
      "What does Eden show you about God's original desire for human life?",
    ],
    lesson:
      "Genesis 2 teaches that God's good world was designed for life with Him. Eden shows work without frustration, command without fear, relationship without shame, and humanity living as dust filled with divine breath.",
  },
];

function buildCreationNotesWithBigLessonFirst(chapter: CreationChapterNote) {
  const chapterFlow = chapter.sections.map((section) => `- 📍 ${section.title}`).join("\n");
  const finalThought = chapter.finalThought.map((item) => `- ${item}`).join("\n");
  const pause = chapter.pause.map((item) => `- ${item}`).join("\n");

  return `# Genesis ${chapter.chapter}\n\n# ${chapter.title}\n\n${chapter.hook}\n\n${chapter.setup.join("\n\n")}\n\n## Why Genesis ${chapter.chapter} Matters\n\n${chapter.matters.map((item) => `- ${item}`).join("\n")}\n\n## Chapter Flow\n\n${chapterFlow}\n\n# Deep Chapter Notes\n\n${chapter.sections.map((section) => buildSection(chapter.chapter, section)).join("\n\n")}\n\n# The Big Lesson of Genesis ${chapter.chapter}\n\n${chapter.lesson}\n\n# Final Thought on Genesis ${chapter.chapter}\n\n${finalThought}\n\n# Pause and Reflect\n\n${pause}`;
}

export const CREATION_OF_WORLD_DEEP_NOTES = creationNotes.map(buildCreationNotesWithBigLessonFirst);
