type FallSection = {
  reference: string;
  title: string;
  verses: number[];
  notes: string[];
};

type FallChapterNote = {
  chapter: number;
  title: string;
  hook: string;
  setup: string[];
  matters: string[];
  sections: FallSection[];
  finalThought: string[];
  pause: string[];
  lesson: string;
};

type GenesisVerse = {
  verse: number;
  text: string;
};

const GENESIS_FALL_KJV_VERSES: Record<number, GenesisVerse[]> = {
  3: [
    { verse: 1, text: "Now the serpent was more subtil than any beast of the field which the LORD God had made. And he said unto the woman, Yea, hath God said, Ye shall not eat of every tree of the garden?" },
    { verse: 2, text: "And the woman said unto the serpent, We may eat of the fruit of the trees of the garden:" },
    { verse: 3, text: "But of the fruit of the tree which is in the midst of the garden, God hath said, Ye shall not eat of it, neither shall ye touch it, lest ye die." },
    { verse: 4, text: "And the serpent said unto the woman, Ye shall not surely die:" },
    { verse: 5, text: "For God doth know that in the day ye eat thereof, then your eyes shall be opened, and ye shall be as gods, knowing good and evil." },
    { verse: 6, text: "And when the woman saw that the tree was good for food, and that it was pleasant to the eyes, and a tree to be desired to make one wise, she took of the fruit thereof, and did eat, and gave also unto her husband with her; and he did eat." },
    { verse: 7, text: "And the eyes of them both were opened, and they knew that they were naked; and they sewed fig leaves together and made themselves aprons." },
    { verse: 8, text: "And they heard the voice of the LORD God walking in the garden in the cool of the day: and Adam and his wife hid themselves from the presence of the LORD God amongst the trees of the garden." },
    { verse: 9, text: "And the LORD God called unto Adam, and said unto him, Where art thou?" },
    { verse: 10, text: "And he said, I heard thy voice in the garden, and I was afraid, because I was naked; and I hid myself." },
    { verse: 11, text: "And he said, Who told thee that thou wast naked? Hast thou eaten of the tree, whereof I commanded thee that thou shouldest not eat?" },
    { verse: 12, text: "And the man said, The woman whom thou gavest to be with me, she gave me of the tree, and I did eat." },
    { verse: 13, text: "And the LORD God said unto the woman, What is this that thou hast done? And the woman said, The serpent beguiled me, and I did eat." },
    { verse: 14, text: "And the LORD God said unto the serpent, Because thou hast done this, thou art cursed above all cattle, and above every beast of the field; upon thy belly shalt thou go, and dust shalt thou eat all the days of thy life:" },
    { verse: 15, text: "And I will put enmity between thee and the woman, and between thy seed and her seed; it shall bruise thy head, and thou shalt bruise his heel." },
    { verse: 16, text: "Unto the woman he said, I will greatly multiply thy sorrow and thy conception; in sorrow thou shalt bring forth children; and thy desire shall be to thy husband, and he shall rule over thee." },
    { verse: 17, text: "And unto Adam he said, Because thou hast hearkened unto the voice of thy wife, and hast eaten of the tree, of which I commanded thee, saying, Thou shalt not eat of it: cursed is the ground for thy sake; in sorrow shalt thou eat of it all the days of thy life;" },
    { verse: 18, text: "Thorns also and thistles shall it bring forth to thee; and thou shalt eat the herb of the field;" },
    { verse: 19, text: "In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and unto dust shalt thou return." },
    { verse: 20, text: "And Adam called his wife's name Eve; because she was the mother of all living." },
    { verse: 21, text: "Unto Adam also and to his wife did the LORD God make coats of skins, and clothed them." },
    { verse: 22, text: "And the LORD God said, Behold, the man is become as one of us, to know good and evil: and now, lest he put forth his hand, and take also of the tree of life, and eat, and live for ever:" },
    { verse: 23, text: "Therefore the LORD God sent him forth from the garden of Eden, to till the ground from whence he was taken." },
    { verse: 24, text: "So he drove out the man; and he placed at the east of the garden of Eden Cherubims, and a flaming sword which turned every way, to keep the way of the tree of life." },
  ],
  4: [
    { verse: 1, text: "And Adam knew Eve his wife; and she conceived, and bare Cain, and said, I have gotten a man from the LORD." },
    { verse: 2, text: "And she again bare his brother Abel. And Abel was a keeper of sheep, but Cain was a tiller of the ground." },
    { verse: 3, text: "And in process of time it came to pass, that Cain brought of the fruit of the ground an offering unto the LORD." },
    { verse: 4, text: "And Abel, he also brought of the firstlings of his flock and of the fat thereof. And the LORD had respect unto Abel and to his offering:" },
    { verse: 5, text: "But unto Cain and to his offering he had not respect. And Cain was very wroth, and his countenance fell." },
    { verse: 6, text: "And the LORD said unto Cain, Why art thou wroth? and why is thy countenance fallen?" },
    { verse: 7, text: "If thou doest well, shalt thou not be accepted? and if thou doest not well, sin lieth at the door. And unto thee shall be his desire, and thou shalt rule over him." },
    { verse: 8, text: "And Cain talked with Abel his brother: and it came to pass, when they were in the field, that Cain rose up against Abel his brother, and slew him." },
    { verse: 9, text: "And the LORD said unto Cain, Where is Abel thy brother? And he said, I know not: Am I my brother's keeper?" },
    { verse: 10, text: "And he said, What hast thou done? the voice of thy brother's blood crieth unto me from the ground." },
    { verse: 11, text: "And now art thou cursed from the earth, which hath opened her mouth to receive thy brother's blood from thy hand;" },
    { verse: 12, text: "When thou tillest the ground, it shall not henceforth yield unto thee her strength; a fugitive and a vagabond shalt thou be in the earth." },
    { verse: 13, text: "And Cain said unto the LORD, My punishment is greater than I can bear." },
    { verse: 14, text: "Behold, thou hast driven me out this day from the face of the earth; and from thy face shall I be hid; and I shall be a fugitive and a vagabond in the earth; and it shall come to pass, that every one that findeth me shall slay me." },
    { verse: 15, text: "And the LORD said unto him, Therefore whosoever slayeth Cain, vengeance shall be taken on him sevenfold. And the LORD set a mark upon Cain, lest any finding him should kill him." },
    { verse: 16, text: "And Cain went out from the presence of the LORD, and dwelt in the land of Nod, on the east of Eden." },
    { verse: 17, text: "And Cain knew his wife; and she conceived, and bare Enoch: and he builded a city, and called the name of the city, after the name of his son, Enoch." },
    { verse: 18, text: "And unto Enoch was born Irad: and Irad begat Mehujael: and Mehujael begat Methusael: and Methusael begat Lamech." },
    { verse: 19, text: "And Lamech took unto him two wives: the name of the one was Adah, and the name of the other Zillah." },
    { verse: 20, text: "And Adah bare Jabal: he was the father of such as dwell in tents, and of such as have cattle." },
    { verse: 21, text: "And his brother's name was Jubal: he was the father of all such as handle the harp and organ." },
    { verse: 22, text: "And Zillah, she also bare Tubalcain, an instructer of every artificer in brass and iron: and the sister of Tubalcain was Naamah." },
    { verse: 23, text: "And Lamech said unto his wives, Adah and Zillah, Hear my voice; ye wives of Lamech, hearken unto my speech: for I have slain a man to my wounding, and a young man to my hurt." },
    { verse: 24, text: "If Cain shall be avenged sevenfold, truly Lamech seventy and sevenfold." },
    { verse: 25, text: "And Adam knew his wife again; and she bare a son, and called his name Seth: For God, said she, hath appointed me another seed instead of Abel, whom Cain slew." },
    { verse: 26, text: "And to Seth, to him also there was born a son; and he called his name Enos: then began men to call upon the name of the LORD." },
  ],
};

function verseText(chapter: number, verse: number) {
  return GENESIS_FALL_KJV_VERSES[chapter]?.find((item) => item.verse === verse)?.text || "";
}

function verseCallouts(chapter: number, verses: number[]) {
  return verses.map((verse) => `> **${verse}** ${verseText(chapter, verse)}`).join("\n\n");
}

function buildSection(chapter: number, section: FallSection) {
  return `## ${section.reference}\n\n# ${section.title}\n\n${verseCallouts(chapter, section.verses)}\n\n${section.notes.join("\n\n")}`;
}

const fallNotes: FallChapterNote[] = [
  {
    chapter: 3,
    title: "The Day Shame Entered the Garden",
    hook: "Genesis 3 is where the Bible turns from beauty to heartbreak.",
    setup: [
      "Genesis 1 showed a good world spoken into order by God. Genesis 2 brought us close to Eden, where humanity lived with God, with work, with food, with relationship, and without shame.",
      "Then Genesis 3 opens with a voice that questions God.",
      "This chapter is not only about one forbidden fruit. It is about the first collapse of trust. Temptation enters through a question, grows through desire, and ends with fear, shame, blame, pain, exile, and death.",
      "The tragedy is that Adam and Eve do not become more free when they disobey. They become afraid.",
    ],
    matters: [
      "🐍 It shows how temptation twists God's words before it breaks God's command.",
      "👀 It explains why shame and hiding feel so deeply human.",
      "💔 It shows relationships breaking through blame.",
      "⚖️ It introduces judgment, pain, cursed ground, and death.",
      "🌱 It gives the first promise that evil will not win forever.",
      "🚪 It explains why humanity is outside Eden and why the rest of the Bible is a rescue story.",
    ],
    sections: [
      {
        reference: "Genesis 3:1 to 5",
        title: "The Serpent and Temptation",
        verses: [1, 2, 3, 4, 5],
        notes: [
          "The first thing sin does in the Bible is talk.",
          "That matters.",
          "Sin does not begin here with violence. It begins with a conversation that makes God sound less trustworthy.",
          "### 🐍 The Serpent Is Subtil",
          "The KJV says the serpent was `subtil.` That means crafty, clever, shrewd, and dangerous in a hidden way.",
          "The Hebrew idea is not that the serpent looks scary. It is that he knows how to work through suggestion.",
          "That is how temptation often works.",
          "- 🧠 not always loud",
          "- 👀 not always obvious",
          "- 🗣️ often wrapped in a question",
          "- ⚖️ often aimed at trust before behavior",
          "- 💔 often designed to make God look like the problem",
          "The serpent does not start by saying, `Disobey God.`",
          "He starts by asking, `Yea, hath God said?`",
          "In normal language, that means, `Did God really say that?`",
          "This is the first attack. Not on the fruit. On God's word.",
          "### 🗣️ Twisting God's Words",
          "God had generously allowed Adam and Eve to eat from the trees of the garden, except one tree.",
          "But the serpent makes the command sound restrictive.",
          "He says, `Ye shall not eat of every tree of the garden?`",
          "That question pushes Eve to focus on the one limit instead of the huge gift.",
          "That is psychologically deep.",
          "Temptation often shrinks your vision until the only thing you can see is what God said no to.",
          "### 🍎 Eve's Answer",
          "Eve knows God gave permission to eat from the trees.",
          "She also knows there is a boundary.",
          "But verse 3 adds the phrase `neither shall ye touch it.` Genesis 2 did not record God saying those exact words.",
          "Bible readers debate whether Adam explained it that way, whether Eve is adding a fence around the command, or whether the wording shows the command is already becoming blurry in her mind.",
          "Either way, the moment is tense.",
          "The serpent has pulled her into a conversation where God's command is being handled by the enemy.",
          "### ⚠️ Ye Shall Not Surely Die",
          "Verse 4 is the first direct contradiction of God's word.",
          "God said death would come.",
          "The serpent says it will not.",
          "This is not just misinformation. It is rebellion dressed as confidence.",
          "Then the serpent attacks God's character.",
          "He suggests God is holding something back. He makes God sound insecure, selfish, and afraid of human growth.",
          "That is the heart of temptation in Genesis 3.",
          "It whispers:",
          "- 🙄 God is not telling you everything",
          "- 👀 God is keeping something from you",
          "- 👑 you can define good and evil yourself",
          "- 🚪 disobedience will open your life, not ruin it",
          "The serpent makes sin sound like awakening.",
          "But the chapter will show it is actually collapse.",
        ],
      },
      {
        reference: "Genesis 3:6 to 7",
        title: "The Fall",
        verses: [6, 7],
        notes: [
          "Verse 6 slows everything down.",
          "Eve looks at the tree differently now.",
          "Before, it was a boundary. Now, after the serpent's words, it becomes attractive in a new way.",
          "### 👀 Desire Grows Through Looking",
          "The tree is described in three ways.",
          "- 🍽️ good for food",
          "- 👀 pleasant to the eyes",
          "- 🧠 desired to make one wise",
          "That is not random.",
          "Temptation often speaks to real desires.",
          "Food is not evil. Beauty is not evil. Wisdom is not evil.",
          "The danger is wanting a good thing outside of trust and obedience to God.",
          "Sin does not always look ugly when it approaches us.",
          "Sometimes it looks useful.",
          "Sometimes it looks beautiful.",
          "Sometimes it looks like wisdom.",
          "### 🍎 She Took, Ate, Gave",
          "The verbs are quick and painful.",
          "She took.",
          "She ate.",
          "She gave.",
          "He ate.",
          "The first sin is both personal and shared. Eve is deceived by the serpent, and Adam eats with her.",
          "The verse says her husband was `with her.` That makes the scene heavier. Adam is not pictured as miles away. He is present, silent, and participating.",
          "### 🙈 Eyes Opened, But Not Like They Expected",
          "The serpent promised opened eyes.",
          "Their eyes are opened.",
          "But what do they see first?",
          "Not glory.",
          "Not freedom.",
          "Not godlike power.",
          "They see nakedness.",
          "They see vulnerability.",
          "They see shame.",
          "Genesis 2 ended by saying the man and woman were naked and not ashamed.",
          "Genesis 3 now says they know they are naked and try to cover themselves.",
          "That is the first emotional fruit of sin.",
          "Shame.",
          "### 🍃 Fig Leaves",
          "They sew fig leaves together and make aprons.",
          "This is human covering.",
          "It is the first attempt to manage shame without coming honestly to God.",
          "And that still feels familiar.",
          "People still try to cover what they are afraid to confess.",
          "- 😶 hiding behind image",
          "- 😤 blaming someone else",
          "- 🧱 acting like nothing happened",
          "- 🧥 making emotional fig leaves",
          "Genesis 3 is ancient, but the psychology is painfully current.",
        ],
      },
      {
        reference: "Genesis 3:8 to 13",
        title: "Hiding and Blame",
        verses: [8, 9, 10, 11, 12, 13],
        notes: [
          "After sin enters, God comes near.",
          "That detail matters.",
          "The first sinners hide, but God is the one who calls.",
          "### 🌬️ The Cool of the Day",
          "Verse 8 says they heard the voice of the LORD God walking in the garden in the cool of the day.",
          "This language is tender and terrifying at the same time.",
          "The garden was once a place of openness. Now the same presence of God feels frightening.",
          "Sin changes how people experience God's nearness.",
          "God has not changed.",
          "But Adam and Eve have.",
          "### 🙈 Hiding From Presence",
          "They hide among the trees.",
          "Think about that.",
          "The trees God made for beauty and life are now used as cover from God.",
          "That is what sin does. It takes good gifts and turns them into hiding places.",
          "### ❓ Where Art Thou?",
          "God asks, `Where art thou?`",
          "God is not asking because He lacks information.",
          "He is drawing Adam into confession.",
          "A better answer would have been, `I sinned. I was wrong. I am afraid.`",
          "Adam gets close, but not all the way.",
          "He says he was afraid because he was naked.",
          "Fear has now entered the human relationship with God.",
          "### ⚖️ Who Told Thee?",
          "God's question exposes the new voice Adam has listened to.",
          "Who told you that you were naked?",
          "Who taught you to see yourself this way?",
          "Who gave you this shame?",
          "Then God names the real issue: `Hast thou eaten of the tree?`",
          "God brings the conversation back to obedience.",
          "### 👉 Blame Starts Fast",
          "Adam blames Eve, but he also quietly blames God.",
          "`The woman whom thou gavest to be with me...`",
          "That is a loaded sentence.",
          "The gift God gave him in Genesis 2 is now being used as an excuse in Genesis 3.",
          "Eve blames the serpent.",
          "The KJV says the serpent `beguiled` her. That means deceived, tricked, or led astray.",
          "She is telling the truth about deception, but she still ate.",
          "Genesis 3 shows a human pattern that never stopped:",
          "- 😨 fear instead of honesty",
          "- 🙈 hiding instead of confession",
          "- 👉 blame instead of responsibility",
          "- 💔 distance instead of trust",
        ],
      },
      {
        reference: "Genesis 3:14 to 19",
        title: "The Curses",
        verses: [14, 15, 16, 17, 18, 19],
        notes: [
          "God now speaks judgment.",
          "This section is heavy, but it is not chaotic. God addresses the serpent, the woman, and the man.",
          "Sin has touched every direction of human life.",
          "### 🐍 The Serpent Is Cursed",
          "The serpent is cursed above the beasts of the field.",
          "The word `cursed` means placed under judgment. It is not a magical insult. It is God's verdict against evil.",
          "The serpent goes on its belly and eats dust. In the Bible, dust often pictures humiliation and defeat.",
          "### 🌱 The First Gospel Hint",
          "Verse 15 is one of the most important verses in Genesis.",
          "God says there will be `enmity` between the serpent and the woman, and between the serpent's seed and her seed.",
          "`Enmity` means hostility, conflict, or deep opposition.",
          "This verse points to a long war between evil and the line through which God will bring rescue.",
          "Christians often call this the `protoevangelium,` meaning the first announcement of the gospel.",
          "That does not mean Adam and Eve understood everything about Jesus in that moment.",
          "But the Bible is planting a seed.",
          "One from the woman will crush the serpent's head, even though His heel will be bruised.",
          "That is victory through suffering.",
          "The rest of Scripture keeps moving toward that promise.",
          "### 💔 Pain in Birth and Relationship",
          "God tells the woman that sorrow will be multiplied in conception and childbirth.",
          "`Sorrow shalt thou bring forth children` means pain, grief, hardship, and struggle will now be connected to bringing life into the world.",
          "The place where life comes will now carry pain.",
          "The relationship between husband and wife is also wounded.",
          "The line about desire and rule is not describing a healthy marriage ideal. It is describing distortion after sin.",
          "What was meant to be unity becomes tension.",
          "What was meant to be partnership becomes struggle.",
          "### 🌱 The Ground Is Cursed",
          "Adam's judgment affects the ground.",
          "That matters because Adam was formed from the ground and called to work it.",
          "Work existed before sin, but frustration enters after sin.",
          "Now the ground fights back.",
          "Thorns and thistles grow.",
          "Bread comes through sweat.",
          "Life becomes labor under resistance.",
          "### ⚰️ Dust Thou Art",
          "Verse 19 is the first clear death sentence over humanity.",
          "`Dust thou art, and unto dust shalt thou return.`",
          "This is devastating.",
          "The human formed from dust and filled with breath will return to dust.",
          "Death is not natural in the story's original goodness. It is the result of sin entering God's good world.",
        ],
      },
      {
        reference: "Genesis 3:20 to 24",
        title: "Exile From Eden",
        verses: [20, 21, 22, 23, 24],
        notes: [
          "The chapter ends with both mercy and exile.",
          "That tension matters.",
          "God judges sin, but He also covers shame.",
          "### 👩 Eve, Mother of All Living",
          "Adam names his wife Eve because she is the mother of all living.",
          "After a chapter full of death language, this name holds hope.",
          "Life will continue.",
          "The promise has not been erased.",
          "### 🧥 Coats of Skins",
          "Verse 21 says God made coats of skins and clothed them.",
          "This is different from fig leaves.",
          "Human covering was weak. God's covering is stronger.",
          "The text does not explain every detail, but skins imply the death of an animal. Something dies so shame can be covered.",
          "That does not mean Genesis 3 explains the whole sacrificial system yet.",
          "But it does introduce a deep Bible pattern:",
          "- 🙈 humans cannot cover shame well enough on their own",
          "- 🧥 God provides covering",
          "- 🩸 sin brings death",
          "- 🙏 mercy appears even after judgment",
          "### 🌳 Kept From the Tree of Life",
          "God sends them out so they do not eat from the tree of life and live forever in a fallen state.",
          "That is judgment, but also mercy.",
          "Living forever broken would not be salvation.",
          "### 🚪 East of Eden",
          "Adam and Eve are driven out.",
          "The word `drove` is strong. Eden is no longer open to them.",
          "Cherubims, or cherubim, are heavenly guardians. The flaming sword turns every way to guard the way to the tree of life.",
          "Genesis 3 ends with humanity outside the garden.",
          "That is why the rest of the Bible matters.",
          "The Bible will keep asking:",
          "How can people get back to life with God?",
          "The answer will not come through another fig leaf.",
          "It will come through God's rescue.",
        ],
      },
    ],
    finalThought: [
      "Genesis 3 is painful because it feels so honest.",
      "We know what it is like to listen to the wrong voice.",
      "We know what it is like to hide after we fail.",
      "We know what it is like to blame when we should confess.",
      "But this chapter also shows God calling, covering, judging, and promising.",
    ],
    pause: [
      "Where are you most tempted to question God's goodness?",
      "What fig leaves do people use today to cover shame?",
      "Why is blame easier than confession?",
      "How does Genesis 3 help you understand why the world needs redemption?",
    ],
    lesson:
      "Genesis 3 teaches that sin begins by breaking trust with God and ends by breaking everything else. But even in judgment, God begins the promise of rescue.",
  },
  {
    chapter: 4,
    title: "When Sin Moves From the Garden Into the Family",
    hook: "Genesis 4 shows what happens when sin leaves Eden and enters the home.",
    setup: [
      "Genesis 3 ended with Adam and Eve outside the garden. They are alive, covered by God, but separated from Eden.",
      "Genesis 4 begins with children, worship, work, offerings, anger, and murder.",
      "That is how fast the story falls.",
      "Sin does not stay private. It spreads into family, worship, speech, violence, culture, and generations.",
    ],
    matters: [
      "👥 It introduces Cain and Abel, the first brothers in Scripture.",
      "🙏 It shows worship becoming a place of comparison and anger.",
      "😡 It explains how jealousy can grow into violence.",
      "🩸 It records the first murder.",
      "🚶 It shows exile continuing east of Eden.",
      "🧬 It contrasts Cain's line with the line of Seth.",
    ],
    sections: [
      {
        reference: "Genesis 4:1 to 7",
        title: "Cain and Abel's Offerings",
        verses: [1, 2, 3, 4, 5, 6, 7],
        notes: [
          "Genesis 4 begins with birth.",
          "That feels hopeful after Genesis 3.",
          "Eve has a son, and she says, `I have gotten a man from the LORD.`",
          "Life continues outside Eden.",
          "But the brokenness of Genesis 3 is still there.",
          "### 👶 Cain and Abel",
          "Cain works the ground. Abel keeps sheep.",
          "`Keeper` means one who tends, watches, guards, or cares for something.",
          "Their work reflects the world after Eden.",
          "Cain works the ground that was cursed in Genesis 3.",
          "Abel keeps flocks in a world where death has entered.",
          "### 🙏 Offerings to the LORD",
          "Both brothers bring offerings.",
          "Cain brings fruit of the ground.",
          "Abel brings the firstlings of his flock and the fat.",
          "The text highlights Abel bringing the first and the best.",
          "That matters.",
          "The issue is not simply plants versus animals. Later in the Bible, grain offerings can be acceptable. The deeper issue is the heart, quality, and faith behind the offering.",
          "Abel's offering is received. Cain's is not.",
          "### 😡 Cain Was Very Wroth",
          "`Wroth` means angry.",
          "`Countenance` means face, expression, or appearance.",
          "Cain's countenance falls. His face changes because his heart is changing.",
          "That detail is psychologically powerful.",
          "Before Cain kills with his hands, anger shows on his face.",
          "God meets Cain before the murder.",
          "That is mercy.",
          "God asks why he is angry.",
          "God gives Cain a warning and a way forward.",
          "### 🐍 Sin Lieth at the Door",
          "Verse 7 is one of the strongest pictures of sin in Genesis.",
          "Sin is pictured like something crouching at the door.",
          "It is near.",
          "It is waiting.",
          "It desires Cain.",
          "But Cain must rule over it.",
          "This is not a vague spiritual idea. It is emotional reality.",
          "- 😡 anger is at the door",
          "- 👀 comparison is at the door",
          "- 💔 rejection is at the door",
          "- 🩸 violence is at the door",
          "- ⚖️ Cain still has a choice",
          "Genesis 4 shows that temptation did not end with the serpent.",
          "Now temptation is crouching inside human anger.",
        ],
      },
      {
        reference: "Genesis 4:8 to 16",
        title: "Cain Murders Abel",
        verses: [8, 9, 10, 11, 12, 13, 14, 15, 16],
        notes: [
          "Cain does not listen to God's warning.",
          "He talks with Abel and then kills him in the field.",
          "The field should have been a place of work.",
          "Now it becomes a place of blood.",
          "### 🩸 The First Murder",
          "Genesis does not describe the murder with dramatic detail.",
          "It says Cain rose up against Abel his brother and slew him.",
          "The repeated phrase `his brother` matters.",
          "This is not random violence. This is family violence.",
          "The first human death recorded in Scripture is not old age.",
          "It is murder.",
          "### ❓ Am I My Brother's Keeper?",
          "God asks Cain, `Where is Abel thy brother?`",
          "This sounds like Genesis 3 when God asked Adam, `Where art thou?`",
          "Again, God is not lacking information. He is drawing Cain into truth.",
          "Cain answers with a lie and a hard question.",
          "`Am I my brother's keeper?`",
          "`Keeper` is the same kind of word used for Abel's care of sheep. Cain is basically saying, `Am I responsible for him?`",
          "The answer the Bible wants us to feel is yes.",
          "Humans are responsible for one another.",
          "Sin makes people treat responsibility like an insult.",
          "### 🩸 Blood Cries From the Ground",
          "God says Abel's blood cries from the ground.",
          "This is powerful imagery.",
          "Cain may have hidden the body, but he cannot silence the blood.",
          "In the Bible, innocent blood is not ignored by God.",
          "The ground received Abel's blood, and now the ground becomes part of Cain's judgment.",
          "### 🚶 Fugitive and Vagabond",
          "Cain is cursed from the earth.",
          "`Fugitive` means someone who wanders because he is displaced.",
          "`Vagabond` means a restless wanderer without settled home.",
          "Cain worked the ground, but now the ground will not yield its strength to him.",
          "The punishment fits the sin.",
          "He spilled blood into the ground.",
          "Now the ground resists him.",
          "### 🧬 The Mark of Cain",
          "Cain fears being killed.",
          "God places a mark on Cain to protect him from revenge.",
          "The Bible does not say what the mark looked like.",
          "That matters because people have wrongly guessed and abused this text in terrible ways.",
          "The point is not race, appearance, or some curse people can identify today.",
          "The point is mercy restraining violence.",
          "Cain is guilty, but God does not allow endless revenge.",
          "Genesis 4 shows judgment and mercy together again.",
          "Cain then goes out from the presence of the LORD and lives east of Eden.",
          "The distance keeps growing.",
        ],
      },
      {
        reference: "Genesis 4:17 to 24",
        title: "Cain's Descendants",
        verses: [17, 18, 19, 20, 21, 22, 23, 24],
        notes: [
          "This section can feel like a genealogy, but it is doing more than listing names.",
          "It shows culture developing while sin also spreads.",
          "### 🏙️ The First City",
          "Cain builds a city and names it after his son Enoch.",
          "Cities are not automatically evil in the Bible.",
          "But here, it is striking that the first city is connected to Cain's line.",
          "A restless wanderer tries to build permanence.",
          "A man marked by exile tries to make a name and a place.",
          "### 🧬 Civilization Develops",
          "Cain's descendants develop parts of human culture.",
          "- 🏕️ Jabal is connected to tents and cattle",
          "- 🎶 Jubal is connected to harp and organ",
          "- ⚒️ Tubalcain is connected to bronze and iron work",
          "The KJV says Tubalcain was an `instructer of every artificer in brass and iron.`",
          "`Artificer` means craftsman or skilled worker.",
          "This means Genesis is not anti-culture.",
          "Music, tools, animals, tents, and cities all develop in the world outside Eden.",
          "But the chapter also shows that cultural progress does not automatically fix the human heart.",
          "Technology can grow while violence grows too.",
          "### 🩸 Lamech's Boast",
          "Lamech is the first man in Scripture recorded as taking two wives.",
          "Genesis 2 presented one man and one woman becoming one flesh.",
          "Genesis 4 shows relationship order bending away from that pattern.",
          "Then Lamech sings a violent boast to his wives.",
          "He says he killed a man for wounding him.",
          "This is escalation.",
          "Cain killed and tried to dodge responsibility.",
          "Lamech kills and brags.",
          "Cain feared vengeance.",
          "Lamech celebrates greater vengeance.",
          "He twists God's protection of Cain into a personal anthem of violence.",
          "That is how sin spreads.",
          "- 😡 anger becomes murder",
          "- 🩸 murder becomes boasting",
          "- ⚖️ justice becomes revenge",
          "- 👑 pride makes violence sound powerful",
        ],
      },
      {
        reference: "Genesis 4:25 to 26",
        title: "Seth's Line",
        verses: [25, 26],
        notes: [
          "The chapter does not end with Lamech's violence.",
          "That is mercy.",
          "It ends with another son.",
          "### 👶 Seth Appointed",
          "Eve names her son Seth because God appointed another seed instead of Abel.",
          "`Seed` means offspring, descendant, or family line.",
          "That word matters because Genesis 3 promised conflict between the serpent's seed and the woman's seed.",
          "Abel is dead. Cain is exiled. But the promise is not dead.",
          "God preserves a line.",
          "### 🙏 Calling on the Name of the LORD",
          "Verse 26 says that in the days of Enos, people began to call upon the name of the LORD.",
          "This is worship language.",
          "It means people are seeking, naming, and depending on the LORD.",
          "After a chapter of murder, wandering, city building, and violent boasting, this final sentence matters deeply.",
          "Humanity is broken, but worship is still possible.",
          "Sin is spreading, but the LORD is still being called upon.",
          "The story is moving toward Noah, but it is also moving toward the bigger promise of redemption.",
        ],
      },
    ],
    finalThought: [
      "Genesis 4 is not just about Cain being bad.",
      "It is about anger being warned before it becomes blood.",
      "It is about comparison turning worship into resentment.",
      "It is about violence spreading through generations.",
      "And it is about God preserving hope even when the family story is shattered.",
    ],
    pause: [
      "Where does comparison tend to affect your heart?",
      "What does Cain teach you about anger before it becomes action?",
      "Why does `Am I my brother's keeper?` still matter today?",
      "How does Seth's line give hope after such a dark chapter?",
    ],
    lesson:
      "Genesis 4 teaches that sin spreads from hidden desire into public damage when it is not confronted. But God still warns, restrains, protects, and preserves a line of hope.",
  },
];

function buildFallNotes(chapter: FallChapterNote) {
  const chapterFlow = chapter.sections.map((section) => `- 📍 ${section.title}`).join("\n");
  const finalThought = chapter.finalThought.map((item) => `- ${item}`).join("\n");
  const pause = chapter.pause.map((item) => `- ${item}`).join("\n");

  return `# Genesis ${chapter.chapter}\n\n# ${chapter.title}\n\n${chapter.hook}\n\n${chapter.setup.join("\n\n")}\n\n## Why Genesis ${chapter.chapter} Matters\n\n${chapter.matters.map((item) => `- ${item}`).join("\n")}\n\n## Chapter Flow\n\n${chapterFlow}\n\n# Deep Chapter Notes\n\n${chapter.sections.map((section) => buildSection(chapter.chapter, section)).join("\n\n")}\n\n# The Big Lesson of Genesis ${chapter.chapter}\n\n${chapter.lesson}\n\n# Final Thought on Genesis ${chapter.chapter}\n\n${finalThought}\n\n# Pause and Reflect\n\n${pause}`;
}

export const FALL_OF_MAN_DEEP_NOTES = fallNotes.map(buildFallNotes);
