import type { PersonalLeviticusPhraseSectionInput } from "./leviticusOneToTenPersonalNotes";
import { DAY_61_80_FIRST_SAMUEL_11_30_SUPPLEMENTAL_SECTIONS } from "./daySixtyOneToEightySupplementalPersonalNotes";

const e = (...codes: number[]) => String.fromCodePoint(...codes);

const I = {
  armor: e(0x1F6E1, 0xFE0F),
  arrow: e(0x1F3F9),
  battle: e(0x2694, 0xFE0F),
  bread: e(0x1F35E),
  cave: e(0x1F573, 0xFE0F),
  city: e(0x1F3D9, 0xFE0F),
  crown: e(0x1F451),
  cut: e(0x2702, 0xFE0F),
  ear: e(0x1F442),
  eye: e(0x1F441, 0xFE0F),
  field: e(0x1F33E),
  fire: e(0x1F525),
  food: e(0x1F372),
  hand: e(0x270B),
  harp: e(0x1FA95),
  heart: e(0x1F49B),
  hill: e(0x26F0, 0xFE0F),
  honey: e(0x1F36F),
  house: e(0x1F3E0),
  king: e(0x1F451),
  lamb: e(0x1F411),
  oil: e(0x1FA94),
  people: e(0x1F465),
  prayer: e(0x1F64F),
  priest: e(0x1F9D4),
  question: e(0x2753),
  robe: e(0x1F9E5),
  rock: e(0x1FAA8),
  scroll: e(0x1F4DC),
  sorrow: e(0x1F622),
  spear: e(0x1F52A),
  spirit: e(0x1F32C, 0xFE0F),
  star: e(0x2728),
  stone: e(0x1FAA8),
  tent: e(0x26FA),
  warning: e(0x26A0, 0xFE0F),
  water: e(0x1F4A7),
};

type PhraseSeed = [icon: string, title: string, meaning: string, bullets: string[], close: string];
type SectionSeed = [chapter: number, startVerse: number, endVerse: number, title: string, icon: string, phrases: PhraseSeed[]];

const note = (lines: string[]) => lines.join("\n\n");

function phrase([icon, title, meaning, bullets, close]: PhraseSeed): [string, string] {
  return [
    `${icon} ${title}`,
    note([
      `${title} means ${meaning}`,
      ...bullets,
      close,
    ]),
  ];
}

function section([chapter, startVerse, endVerse, title, icon, phrases]: SectionSeed): PersonalLeviticusPhraseSectionInput {
  return {
    chapter,
    startVerse,
    endVerse,
    reference: `1 Samuel ${chapter}:${startVerse}-${endVerse}`,
    title,
    icon,
    phrases: phrases.map(phrase),
  };
}

const p = (icon: string, title: string, meaning: string, bullets: string[], close: string): PhraseSeed => [icon, title, meaning, bullets, close];

const sections: SectionSeed[] = [
  [11, 1, 5, "Nahash Threatens Jabeshgilead", I.warning, [
    p(I.city, "Nahash The Ammonite Came Up", "an enemy king moves against Jabeshgilead with military pressure.", [`${I.city} Jabeshgilead threatened`, `${I.battle} Ammonite power`, `${I.warning} Crisis begins`], "The new king Saul will be tested by a real threat."),
    p(I.question, "Make A Covenant With Us", "the people ask for terms of surrender instead of rescue.", [`${I.question} Desperate request`, `${I.people} A fearful city`, `${I.warning} Enemy control`], "Their words show how helpless they feel."),
    p(I.eye, "Thrust Out All Your Right Eyes", "Nahash demands a cruel humiliation that would shame and weaken the men.", [`${I.eye} Right eyes`, `${I.sorrow} Public shame`, `${I.battle} Fighting ability damaged`], "The threat is meant to disgrace Israel, not merely win a city."),
    p(I.sorrow, "All The People Lifted Up Their Voices, And Wept", "Jabesh responds with grief and fear.", [`${I.sorrow} Weeping`, `${I.city} City in danger`, `${I.question} Waiting for help`], "The phrase prepares the reader for Saul's first act of deliverance."),
  ]],
  [11, 6, 11, "Saul Rescues Jabesh", I.spirit, [
    p(I.spirit, "The Spirit Of God Came Upon Saul", "God empowers Saul for leadership and rescue.", [`${I.spirit} God's Spirit`, `${I.king} Saul equipped`, `${I.battle} Rescue begins`], "Saul's courage is presented as God's work, not just personality."),
    p(I.fire, "His Anger Was Kindled Greatly", "Saul is stirred by righteous anger at Israel's humiliation.", [`${I.fire} Anger`, `${I.people} Israel threatened`, `${I.hand} Action coming`], "The phrase shows anger directed toward protecting God's people."),
    p(I.hand, "Whosoever Cometh Not Forth After Saul And After Samuel", "Saul calls Israel to gather under kingly and prophetic leadership.", [`${I.hand} Saul`, `${I.scroll} Samuel`, `${I.people} Israel summoned`], "The phrase links Saul's authority with Samuel's recognized leadership."),
    p(I.battle, "The LORD Hath Wrought Salvation In Israel", "the rescue is credited to the LORD.", [`${I.battle} Victory`, `${I.prayer} The LORD`, `${I.people} Israel saved`], "The phrase keeps the glory of deliverance in the right place."),
  ]],
  [11, 12, 15, "The Kingdom Is Renewed", I.king, [
    p(I.question, "Who Is He That Said, Shall Saul Reign Over Us", "the people remember those who doubted Saul.", [`${I.question} Earlier doubt`, `${I.king} Saul vindicated`, `${I.people} Public support`], "Victory changes how the people see Saul."),
    p(I.hand, "There Shall Not A Man Be Put To Death This Day", "Saul refuses revenge after victory.", [`${I.hand} Mercy`, `${I.king} Restraint`, `${I.battle} Day of salvation`], "The phrase shows a good early moment in Saul's leadership."),
    p(I.city, "Let Us Go To Gilgal", "Samuel calls the people to renew the kingdom in a worship setting.", [`${I.city} Gilgal`, `${I.king} Kingdom renewed`, `${I.prayer} Before the LORD`], "The phrase makes kingship public and covenant-shaped."),
    p(I.star, "They Made Saul King Before The LORD", "Saul is confirmed as king in the LORD's presence.", [`${I.king} Saul made king`, `${I.prayer} Before the LORD`, `${I.people} Israel rejoices`], "The phrase shows monarchy beginning under God's sight."),
  ]],
  [12, 1, 5, "Samuel's Integrity", I.scroll, [
    p(I.ear, "I Have Hearkened Unto Your Voice", "Samuel acknowledges that Israel's request for a king has been granted.", [`${I.ear} Israel asked`, `${I.king} King given`, `${I.scroll} Samuel speaks`], "The phrase sets up Samuel's farewell-like address."),
    p(I.question, "Whose Ox Have I Taken", "Samuel asks whether he has used leadership for personal gain.", [`${I.question} Honest examination`, `${I.hand} No stealing`, `${I.people} Public witness`], "The phrase shows what righteous leadership should be able to say."),
    p(I.hand, "Of Whose Hand Have I Received Any Bribe", "Samuel denies corrupt judgment and invites correction.", [`${I.hand} No bribe`, `${I.scroll} Clean leadership`, `${I.people} Accountability`], "The phrase contrasts Samuel's integrity with corrupt leaders."),
    p(I.star, "The LORD Is Witness Against You", "Samuel makes the people answer before God.", [`${I.star} Divine witness`, `${I.people} Public testimony`, `${I.scroll} Serious words`], "The phrase gives the moment covenant weight."),
  ]],
  [12, 6, 11, "Samuel Retells The LORD's Faithfulness", I.prayer, [
    p(I.scroll, "It Is The LORD That Advanced Moses And Aaron", "Samuel reminds Israel that the LORD raised past deliverers.", [`${I.scroll} Moses`, `${I.people} Aaron`, `${I.star} The LORD acted`], "The phrase roots Israel's story in God's saving work."),
    p(I.ear, "Stand Still, That I May Reason With You", "Samuel calls Israel to listen and think honestly before God.", [`${I.ear} Listen`, `${I.scroll} Reason together`, `${I.prayer} Before the LORD`], "The phrase shows that biblical rebuke teaches, not only scolds."),
    p(I.king, "Ye Said Unto Me, Nay; But A King Shall Reign Over Us", "Samuel names Israel's demand clearly.", [`${I.king} King demanded`, `${I.people} Israel insisted`, `${I.warning} Trust exposed`], "The phrase keeps the heart issue in view."),
    p(I.hand, "If Ye Will Fear The LORD, And Serve Him", "Samuel gives the path for faithful life under a king.", [`${I.hand} Fear the LORD`, `${I.prayer} Serve Him`, `${I.ear} Obey His voice`], "The phrase shows that monarchy does not remove the need for obedience."),
  ]],
  [12, 16, 21, "Thunder At Wheat Harvest", I.fire, [
    p(I.eye, "Stand And See This Great Thing", "Samuel tells Israel to watch the sign God will give.", [`${I.eye} Watch`, `${I.fire} Sign coming`, `${I.star} The LORD acts`], "The phrase prepares the people to learn through what they see."),
    p(I.fire, "Thunder And Rain", "God sends unusual weather during wheat harvest.", [`${I.fire} Thunder`, `${I.water} Rain`, `${I.warning} Holy warning`], "The sign makes Israel feel the seriousness of asking for a king."),
    p(I.sorrow, "Pray For Thy Servants Unto The LORD Thy God", "the people ask Samuel to intercede for them.", [`${I.prayer} Pray for us`, `${I.sorrow} Fear`, `${I.people} Servants`], "The phrase shows fear turning into a request for mercy."),
    p(I.heart, "Serve Him In Truth With All Your Heart", "Samuel calls them to sincere obedience after their sin is exposed.", [`${I.heart} Whole heart`, `${I.prayer} Serve the LORD`, `${I.scroll} Truth`], "The phrase teaches that conviction should lead to faithful service."),
  ]],
  [13, 1, 6, "Philistine Pressure Rises", I.battle, [
    p(I.king, "Saul Reigned One Year", "the story moves into Saul's early reign.", [`${I.king} Saul reigning`, `${I.scroll} Time marker`, `${I.warning} Testing ahead`], "The phrase begins the account of Saul's leadership under pressure."),
    p(I.battle, "Jonathan Smote The Garrison Of The Philistines", "Jonathan attacks a Philistine outpost.", [`${I.battle} Jonathan acts`, `${I.city} Garrison`, `${I.warning} Conflict escalates`], "The phrase shows Israel's war with Philistia intensifying."),
    p(I.ear, "Let The Hebrews Hear", "Saul announces the conflict across the land.", [`${I.ear} Trumpet message`, `${I.people} Hebrews summoned`, `${I.battle} War news`], "The phrase calls scattered people into a national crisis."),
    p(I.sorrow, "The People Did Hide Themselves", "Israel responds with fear under Philistine pressure.", [`${I.sorrow} Fear`, `${I.cave} Caves`, `${I.hill} Rocks and pits`], "The phrase shows how weak Israel feels before the enemy."),
  ]],
  [13, 8, 13, "Saul Offers Unlawfully", I.warning, [
    p(I.warning, "He Tarried Seven Days", "Saul waits the time Samuel had commanded.", [`${I.warning} Waiting`, `${I.ear} Samuel's instruction`, `${I.people} People scattering`], "The phrase sets up the pressure Saul fails under."),
    p(I.fire, "He Offered The Burnt Offering", "Saul performs a priestly act he was not authorized to do.", [`${I.fire} Burnt offering`, `${I.king} King overstepping`, `${I.warning} Disobedience`], "The phrase marks Saul's early failure."),
    p(I.question, "What Hast Thou Done", "Samuel confronts Saul with a direct question.", [`${I.question} Confrontation`, `${I.scroll} Prophet rebuke`, `${I.warning} Sin exposed`], "The phrase forces Saul to face his action."),
    p(I.heart, "The LORD Hath Sought Him A Man After His Own Heart", "God will seek a different kind of king.", [`${I.heart} God's heart`, `${I.king} Future king`, `${I.warning} Saul rejected from dynasty`], "The phrase points ahead toward David."),
  ]],
  [13, 15, 20, "Israel Has No Smith", I.armor, [
    p(I.people, "About Six Hundred Men", "Saul's force is small and fragile.", [`${I.people} Few soldiers`, `${I.battle} Weak army`, `${I.warning} Pressure remains`], "The phrase shows the human weakness around Saul."),
    p(I.hand, "There Was No Smith Found Throughout All The Land Of Israel", "Israel lacks blacksmiths because the Philistines control weapons production.", [`${I.hand} No smith`, `${I.armor} Weapon shortage`, `${I.battle} Philistine control`], "The phrase explains Israel's military disadvantage."),
    p(I.spear, "There Was Neither Sword Nor Spear Found", "most Israelites have no proper battle weapons.", [`${I.spear} No sword`, `${I.armor} No spear`, `${I.people} Unarmed people`], "The phrase makes the danger feel concrete."),
    p(I.battle, "The Garrison Of The Philistines Went Out", "the enemy keeps moving while Israel is weak.", [`${I.battle} Enemy outpost`, `${I.warning} Threat active`, `${I.hill} Michmash`], "The phrase keeps tension high for Jonathan's next act."),
  ]],
  [14, 1, 6, "Jonathan Steps Out In Faith", I.battle, [
    p(I.hand, "Come, And Let Us Go Over", "Jonathan invites his armor bearer into a risky act of faith.", [`${I.hand} Come`, `${I.battle} Go over`, `${I.heart} Courage`], "The phrase begins one of Jonathan's best moments."),
    p(I.warning, "He Told Not His Father", "Jonathan acts without Saul knowing.", [`${I.warning} Hidden movement`, `${I.king} Saul unaware`, `${I.battle} Risk`], "The detail shows the contrast between Jonathan's initiative and Saul's passivity."),
    p(I.rock, "A Sharp Rock On The One Side", "the path is physically difficult and dangerous.", [`${I.rock} Sharp rocks`, `${I.hill} Climb`, `${I.warning} Hard approach`], "The phrase makes Jonathan's faith feel rugged and real."),
    p(I.star, "There Is No Restraint To The LORD To Save By Many Or By Few", "Jonathan believes God can save without needing a large army.", [`${I.star} The LORD saves`, `${I.people} Many or few`, `${I.heart} Faith`], "The phrase is the theological center of the scene."),
  ]],
  [14, 7, 12, "Jonathan's Sign", I.eye, [
    p(I.heart, "Do All That Is In Thine Heart", "the armor bearer supports Jonathan's faithful courage.", [`${I.heart} Shared courage`, `${I.armor} Armor bearer`, `${I.hand} Loyal help`], "The phrase shows companionship in risky obedience."),
    p(I.question, "If They Say Thus Unto Us", "Jonathan sets a sign to discern the moment.", [`${I.question} Sign`, `${I.ear} Enemy words`, `${I.battle} Decision point`], "The phrase shows faith acting with thoughtfulness."),
    p(I.battle, "Come Up After Me", "Jonathan moves first and his armor bearer follows.", [`${I.battle} Jonathan leads`, `${I.armor} Armor bearer follows`, `${I.hill} Climb`], "The phrase shows courage taking the first step."),
    p(I.fire, "There Was Trembling In The Host", "panic spreads through the Philistine camp.", [`${I.fire} Trembling`, `${I.battle} Enemy shaken`, `${I.star} God at work`], "The phrase shows the battle turning beyond Jonathan's strength."),
  ]],
  [14, 16, 21, "The LORD Saves Israel", I.star, [
    p(I.eye, "The Watchmen Of Saul In Gibeah Looked", "Saul's men see confusion in the enemy camp.", [`${I.eye} Watchmen`, `${I.battle} Enemy melting`, `${I.question} What is happening`], "The phrase shows the victory becoming visible from a distance."),
    p(I.question, "Number Now, And See Who Is Gone From Us", "Saul investigates who began the action.", [`${I.question} Count the people`, `${I.people} Someone missing`, `${I.battle} Jonathan discovered`], "The phrase shows Saul trying to understand a move he did not lead."),
    p(I.battle, "Every Man's Sword Was Against His Fellow", "the Philistines fall into confusion and fight each other.", [`${I.battle} Confusion`, `${I.spear} Swords turned inward`, `${I.star} God disrupts`], "The phrase shows God saving Israel through enemy panic."),
    p(I.star, "The LORD Saved Israel That Day", "the chapter credits the victory to God.", [`${I.star} The LORD saves`, `${I.people} Israel rescued`, `${I.battle} Victory`], "Israel is not saved because the army is clever or Saul is impressive. The rescue belongs to the LORD."),
  ]],
  [14, 24, 29, "Saul's Rash Oath", I.warning, [
    p(I.warning, "Saul Had Adjured The People", "Saul binds the army with a strict oath.", [`${I.warning} Rash command`, `${I.people} Army burdened`, `${I.food} Food forbidden`], "The phrase begins the trouble caused by Saul's leadership."),
    p(I.food, "Cursed Be The Man That Eateth Any Food", "Saul forbids eating until evening.", [`${I.food} No food`, `${I.sorrow} Weak soldiers`, `${I.warning} Harmful oath`], "The phrase shows zeal without wisdom."),
    p(I.honey, "There Was Honey Upon The Ground", "food is available, but the oath keeps the soldiers from receiving strength.", [`${I.food} Honey`, `${I.hand} Strength nearby`, `${I.warning} Oath blocks help`], "The phrase makes Saul's command look even more foolish."),
    p(I.eye, "Mine Eyes Have Been Enlightened", "Jonathan feels refreshed after tasting honey.", [`${I.eye} Eyes brightened`, `${I.food} Honey strengthens`, `${I.warning} Oath exposed`], "The phrase proves the army needed nourishment."),
  ]],
  [14, 31, 35, "The People Eat With Blood", I.food, [
    p(I.sorrow, "The People Were Very Faint", "Saul's oath leaves the army exhausted.", [`${I.sorrow} Weakness`, `${I.food} Hunger`, `${I.warning} Leadership cost`], "The phrase shows the human result of Saul's foolish command."),
    p(I.warning, "The People Did Eat Them With The Blood", "hungry soldiers violate God's law about blood.", [`${I.warning} Blood eaten`, `${I.food} Hunger`, `${I.scroll} Law broken`], "The phrase shows one foolish command leading to further sin."),
    p(I.scroll, "Ye Have Transgressed", "Saul recognizes that the people have sinned.", [`${I.scroll} Transgression`, `${I.warning} Sin named`, `${I.people} Army corrected`], "The phrase names the seriousness of eating blood."),
    p(I.stone, "Saul Built An Altar Unto The LORD", "Saul builds his first altar after the crisis.", [`${I.stone} Altar`, `${I.prayer} The LORD`, `${I.warning} Troubled worship`], "The phrase puts worship beside Saul's uneven leadership."),
  ]],
  [14, 36, 41, "Jonathan Is Spared", I.hand, [
    p(I.question, "Shall I Go Down After The Philistines", "Saul seeks direction after earlier acting foolishly.", [`${I.question} Inquiry`, `${I.battle} Pursuit`, `${I.prayer} Seeking God`], "The phrase shows the need for God's guidance."),
    p(I.ear, "He Answered Him Not That Day", "God gives no answer to Saul.", [`${I.ear} Silence`, `${I.king} Saul`, `${I.warning} Something wrong`], "The phrase signals unresolved guilt in the camp."),
    p(I.question, "Tell Me What Thou Hast Done", "Saul demands Jonathan explain himself.", [`${I.question} Interrogation`, `${I.people} Jonathan`, `${I.warning} Oath problem`], "The phrase exposes how Saul's oath has trapped his own son."),
    p(I.people, "The People Rescued Jonathan", "Israel refuses to let Jonathan die.", [`${I.people} People intervene`, `${I.hand} Jonathan spared`, `${I.star} God worked through him`], "The phrase shows the people recognizing God's deliverance through Jonathan."),
  ]],
  [14, 47, 52, "Saul's Wars Continue", I.battle, [
    p(I.battle, "Saul Took The Kingdom Over Israel", "Saul's reign becomes established through conflict.", [`${I.king} Kingdom`, `${I.battle} Many enemies`, `${I.people} Israel`], "The phrase summarizes Saul's early rule."),
    p(I.spear, "Whithersoever He Turned Himself, He Vexed Them", "Saul fights Israel's surrounding enemies.", [`${I.spear} War`, `${I.battle} Enemies pressured`, `${I.king} Royal strength`], "The phrase shows Saul as an active military leader."),
    p(I.people, "The Sons Of Saul", "the narrator introduces Saul's family.", [`${I.people} Jonathan`, `${I.house} Saul's house`, `${I.scroll} Family line`], "The phrase prepares readers for later family tensions."),
    p(I.warning, "There Was Sore War Against The Philistines", "Saul's reign remains marked by continuing conflict.", [`${I.warning} Ongoing war`, `${I.battle} Philistines`, `${I.people} Israel pressured`], "The phrase reminds us that Saul's victory did not end the struggle."),
  ]],
  [15, 1, 6, "The Command Against Amalek", I.scroll, [
    p(I.ear, "Hearken Thou Unto The Voice Of The Words Of The LORD", "Samuel calls Saul to listen carefully to God's command.", [`${I.ear} Hearken`, `${I.scroll} The LORD's words`, `${I.king} Saul under command`], "The phrase makes obedience the main issue before the battle begins."),
    p(I.warning, "I Remember That Which Amalek Did To Israel", "God brings Amalek's old attack on Israel into judgment.", [`${I.warning} Amalek remembered`, `${I.people} Israel attacked`, `${I.scroll} Justice delayed but not forgotten`], "The phrase shows that God remembers violence against His people."),
    p(I.battle, "Go And Smite Amalek", "Saul is given a direct battle command.", [`${I.battle} Commanded battle`, `${I.king} Saul sent`, `${I.warning} Serious judgment`], "The phrase begins the test Saul will fail."),
    p(I.hand, "Kenites, Go, Depart", "Saul warns the Kenites to separate from Amalek.", [`${I.hand} Mercy warning`, `${I.people} Kenites spared`, `${I.scroll} Distinction made`], "The phrase shows judgment does not erase careful distinction."),
  ]],
  [15, 7, 9, "Saul Spares What God Condemned", I.warning, [
    p(I.battle, "Saul Smote The Amalekites", "Saul begins obeying by defeating Amalek.", [`${I.battle} Victory`, `${I.king} Saul acts`, `${I.warning} Obedience incomplete`], "The phrase starts with success, but the next lines reveal the problem."),
    p(I.king, "He Took Agag The King Of The Amalekites Alive", "Saul spares the enemy king God told him to destroy.", [`${I.king} Agag spared`, `${I.warning} Disobedience`, `${I.eye} Visible trophy`], "The phrase shows Saul keeping what God had judged."),
    p(I.hand, "Spared The Best Of The Sheep", "Saul keeps valuable animals instead of obeying fully.", [`${I.hand} Best animals`, `${I.lamb} Sheep and oxen`, `${I.warning} Selective obedience`], "The phrase exposes obedience mixed with self-interest."),
    p(I.warning, "Would Not Utterly Destroy Them", "Saul refuses complete obedience.", [`${I.warning} Would not`, `${I.scroll} Command resisted`, `${I.heart} Heart revealed`], "The phrase makes the failure plain."),
  ]],
  [15, 10, 15, "Samuel Confronts Saul", I.sorrow, [
    p(I.sorrow, "It Repenteth Me That I Have Set Up Saul To Be King", "God expresses grief over Saul's rebellion.", [`${I.sorrow} Divine grief`, `${I.king} Saul`, `${I.warning} Turning back`], "The phrase shows Saul's failure is deeply serious."),
    p(I.prayer, "Samuel Cried Unto The LORD All Night", "Samuel grieves and prays over Saul's failure.", [`${I.prayer} All night`, `${I.sorrow} Prophet grief`, `${I.king} Saul's collapse`], "The phrase shows correction comes from sorrow, not cold anger."),
    p(I.king, "Saul Came To Carmel, And Set Him Up A Place", "Saul creates a memorial for himself after incomplete obedience.", [`${I.king} Self-honor`, `${I.city} Carmel`, `${I.warning} Pride`], "The phrase hints that Saul is celebrating himself before facing God."),
    p(I.question, "What Meaneth Then This Bleating Of The Sheep", "Samuel exposes Saul's disobedience through the sounds of spared animals.", [`${I.question} Bleating sheep`, `${I.lamb} Evidence`, `${I.warning} Sin heard`], "The phrase shows that excuses cannot silence evidence."),
  ]],
  [15, 16, 21, "To Obey Is Better Than Sacrifice", I.scroll, [
    p(I.ear, "Stay, And I Will Tell Thee", "Samuel stops Saul's excuses and brings God's word.", [`${I.ear} Stop`, `${I.scroll} God's message`, `${I.warning} Excuses interrupted`], "The phrase prepares the rebuke."),
    p(I.heart, "When Thou Wast Little In Thine Own Sight", "Samuel reminds Saul of his earlier humility.", [`${I.heart} Humility`, `${I.king} Saul's beginning`, `${I.warning} Pride now`], "The phrase shows how Saul has changed."),
    p(I.scroll, "To Obey Is Better Than Sacrifice", "God values obedience more than religious offerings used to cover rebellion.", [`${I.scroll} Obedience`, `${I.fire} Sacrifice`, `${I.warning} Rebellion exposed`], "The phrase is the central lesson of the chapter."),
    p(I.king, "He Hath Also Rejected Thee From Being King", "Saul's rejection of God's word leads to his rejection as king.", [`${I.king} Kingship rejected`, `${I.scroll} Word rejected`, `${I.warning} Consequence`], "The phrase marks a major turning point in 1 Samuel."),
  ]],
  [15, 24, 29, "Saul Confesses With Mixed Motives", I.sorrow, [
    p(I.sorrow, "I Have Sinned", "Saul admits wrongdoing.", [`${I.sorrow} Confession`, `${I.king} Saul`, `${I.warning} Consequence remains`], "The phrase sounds right, but the story shows his heart is still tangled."),
    p(I.warning, "I Feared The People", "Saul blames pressure from the people for his disobedience.", [`${I.warning} Fear of people`, `${I.people} Public pressure`, `${I.heart} Weak leadership`], "The phrase shows fear replacing faithful obedience."),
    p(I.hand, "Honour Me Now, I Pray Thee", "Saul still wants public honor after disobeying God.", [`${I.hand} Honor requested`, `${I.king} Public image`, `${I.warning} Mixed confession`], "The phrase reveals Saul's concern for appearance."),
    p(I.robe, "The LORD Hath Rent The Kingdom Of Israel From Thee", "Samuel uses the torn robe as a sign of Saul's torn kingdom.", [`${I.robe} Torn robe`, `${I.king} Kingdom torn`, `${I.scroll} Prophetic sign`], "The phrase makes Saul's loss visible."),
  ]],
  [15, 32, 35, "Samuel Grieves For Saul", I.cut, [
    p(I.king, "Bring Ye Hither To Me Agag", "Samuel finishes the judgment Saul refused to complete.", [`${I.king} Agag`, `${I.scroll} Judgment completed`, `${I.warning} Saul's failure exposed`], "The phrase shows Samuel doing what the king failed to do."),
    p(I.spear, "Samuel Hewed Agag In Pieces", "Agag is executed under divine judgment.", [`${I.spear} Judgment`, `${I.warning} Amalek's violence answered`, `${I.scroll} Serious obedience`], "The phrase is severe because the command was severe."),
    p(I.sorrow, "Samuel Came No More To See Saul", "the prophet's relationship with Saul is broken.", [`${I.sorrow} Separation`, `${I.scroll} Prophet and king`, `${I.warning} Leadership fracture`], "The phrase shows Saul's rejection beginning to settle in."),
    p(I.heart, "Samuel Mourned For Saul", "Samuel grieves over Saul's fall.", [`${I.sorrow} Mourning`, `${I.king} Saul`, `${I.heart} Grief over failure`], "The phrase keeps the rejection from feeling casual or easy."),
  ]],
  [16, 1, 5, "Samuel Goes To Bethlehem", I.oil, [
    p(I.sorrow, "How Long Wilt Thou Mourn For Saul", "God calls Samuel to move forward from grief.", [`${I.sorrow} Mourning`, `${I.king} Saul rejected`, `${I.oil} New anointing coming`], "The phrase shows that grief is real, but God's plan continues."),
    p(I.oil, "Fill Thine Horn With Oil", "Samuel is sent to anoint the next king.", [`${I.oil} Oil`, `${I.king} New king`, `${I.hand} God sends`], "The phrase signals a new beginning in Israel's monarchy."),
    p(I.house, "I Have Provided Me A King Among His Sons", "God has already chosen a king from Jesse's family.", [`${I.house} Jesse`, `${I.king} Provided king`, `${I.star} God's choice`], "The phrase shows kingship moving by God's provision."),
    p(I.warning, "The Elders Of The Town Trembled", "Bethlehem's elders fear Samuel's arrival.", [`${I.warning} Trembling`, `${I.city} Bethlehem`, `${I.scroll} Prophet's weight`], "The phrase shows Samuel's presence is spiritually serious."),
  ]],
  [16, 6, 11, "David Is Anointed", I.eye, [
    p(I.eye, "Look Not On His Countenance", "God tells Samuel not to judge by appearance.", [`${I.eye} Appearance`, `${I.heart} Heart matters`, `${I.king} God's choice`], "The phrase corrects the same outward focus that made Saul seem impressive."),
    p(I.heart, "The LORD Looketh On The Heart", "God sees inward character, not only outward form.", [`${I.heart} Heart`, `${I.eye} God's sight`, `${I.king} True leadership`], "The phrase is one of the key lessons of David's calling."),
    p(I.question, "There Remaineth Yet The Youngest", "David is the overlooked son still keeping sheep.", [`${I.question} Youngest`, `${I.lamb} Sheep`, `${I.star} God's hidden choice`], "The phrase shows God choosing the one others did not present first."),
    p(I.spirit, "The Spirit Of The LORD Came Upon David", "God empowers David from the day of anointing.", [`${I.spirit} Spirit`, `${I.oil} Anointing`, `${I.king} Future king`], "The phrase marks David's spiritual beginning as king-elect."),
  ]],
  [16, 14, 19, "David Serves Saul", I.harp, [
    p(I.spirit, "The Spirit Of The LORD Departed From Saul", "Saul loses the empowering presence that had marked his kingship.", [`${I.spirit} Spirit departed`, `${I.king} Saul`, `${I.sorrow} Deep loss`], "The phrase shows the seriousness of Saul's rejection."),
    p(I.warning, "An Evil Spirit From The LORD Troubled Him", "Saul experiences torment under God's judgment.", [`${I.warning} Troubled spirit`, `${I.sorrow} Saul distressed`, `${I.king} Judgment on leadership`], "The phrase is difficult, but it shows Saul under God's sovereign discipline."),
    p(I.harp, "A Cunning Player On An Harp", "David is known for musical skill.", [`${I.harp} Harp`, `${I.hand} Skill`, `${I.house} Service in Saul's house`], "The phrase brings David into Saul's court through ordinary gifting."),
    p(I.hand, "David Took An Harp, And Played With His Hand", "David's music brings relief to Saul.", [`${I.harp} Music`, `${I.hand} David's hand`, `${I.sorrow} Saul refreshed`], "The phrase shows David serving the king who will later hunt him."),
  ]],
  [17, 1, 6, "Goliath Defies Israel", I.battle, [
    p(I.battle, "The Philistines Gathered Together Their Armies", "Israel faces another major Philistine threat.", [`${I.battle} Philistine army`, `${I.people} Israel`, `${I.warning} War setting`], "The phrase sets the battlefield scene."),
    p(I.people, "A Champion Out Of The Camp", "Goliath steps forward as the representative fighter.", [`${I.people} Champion`, `${I.spear} Warrior`, `${I.warning} Intimidation`], "The phrase explains why one man's challenge can terrify a whole army."),
    p(I.spear, "The Staff Of His Spear Was Like A Weaver's Beam", "Goliath's weapon is described as massive.", [`${I.spear} Huge spear`, `${I.armor} Heavy armor`, `${I.eye} Visible threat`], "The phrase helps readers feel his physical intimidation."),
    p(I.warning, "I Defy The Armies Of Israel", "Goliath mocks Israel's army and, by implication, Israel's God.", [`${I.warning} Defiance`, `${I.battle} Armies of Israel`, `${I.sorrow} Fear spreads`], "The phrase shows the battle is spiritual as well as military."),
  ]],
  [17, 12, 17, "David Is Sent To The Battle", I.hand, [
    p(I.house, "David Was The Son Of That Ephrathite", "David is reintroduced through Jesse's family line.", [`${I.house} Jesse`, `${I.city} Bethlehemjudah`, `${I.king} Future king hidden`], "The phrase keeps David grounded in an ordinary family."),
    p(I.lamb, "David Went And Returned From Saul To Feed His Father's Sheep", "David moves between service at court and shepherd work.", [`${I.lamb} Sheep`, `${I.house} Father's house`, `${I.hand} Faithful ordinary work`], "The phrase shows David's humility before public victory."),
    p(I.food, "Take Now For Thy Brethren An Ephah Of This Parched Corn", "Jesse sends David with food for his brothers.", [`${I.food} Food sent`, `${I.people} Brothers`, `${I.hand} Errand of service`], "The phrase shows the giant story begins with a simple act of obedience."),
    p(I.battle, "Saul, And They, And All The Men Of Israel", "David is sent into a national battle scene.", [`${I.king} Saul`, `${I.people} Israel`, `${I.battle} Valley of Elah`], "The phrase places David's small errand inside a huge crisis."),
  ]],
  [17, 20, 25, "David Hears The Defiance", I.ear, [
    p(I.hand, "David Rose Up Early In The Morning", "David obeys Jesse's errand promptly.", [`${I.hand} Early obedience`, `${I.food} Supplies carried`, `${I.battle} Battle line`], "The phrase shows readiness before courage becomes public."),
    p(I.ear, "David Heard Them", "David personally hears Goliath's defiant words.", [`${I.ear} Hearing`, `${I.warning} Defiance`, `${I.heart} Faith stirred`], "The phrase is the moment David enters the conflict."),
    p(I.question, "Who Is This Uncircumcised Philistine", "David sees Goliath as a covenant outsider defying God's people.", [`${I.question} Covenant perspective`, `${I.warning} Defiance named`, `${I.star} Living God`], "The phrase shows David reading the battle through faith."),
    p(I.sorrow, "His Anger Was Kindled Against David", "Eliab reacts harshly to David's questions.", [`${I.sorrow} Brother's anger`, `${I.question} Motives accused`, `${I.heart} David misunderstood`], "The phrase shows David facing criticism before he faces Goliath."),
  ]],
  [17, 31, 36, "David Refuses Saul's Armor", I.armor, [
    p(I.hand, "Let No Man's Heart Fail Because Of Him", "David tells Saul that fear should not rule Israel.", [`${I.hand} Courage`, `${I.heart} Hearts strengthened`, `${I.warning} Goliath's fear broken`], "The phrase shows David's faith strengthening others."),
    p(I.lamb, "Thy Servant Kept His Father's Sheep", "David points to shepherd experience as preparation.", [`${I.lamb} Shepherd work`, `${I.hand} Hidden training`, `${I.battle} Future battle`], "The phrase shows God preparing David in ordinary fields."),
    p(I.armor, "I Cannot Go With These", "David refuses armor he has not tested.", [`${I.armor} Saul's armor`, `${I.hand} Not proved`, `${I.heart} David's simplicity`], "The phrase shows David will fight as himself, not as a copy of Saul."),
    p(I.stone, "Five Smooth Stones", "David chooses simple shepherd weapons.", [`${I.stone} Stones`, `${I.hand} Sling`, `${I.battle} Faith not flash`], "The phrase makes the coming victory feel impossible apart from God."),
  ]],
  [17, 41, 46, "David Speaks In The LORD's Name", I.star, [
    p(I.warning, "Am I A Dog, That Thou Comest To Me With Staves", "Goliath mocks David's appearance and weapons.", [`${I.warning} Mockery`, `${I.battle} Giant confidence`, `${I.hand} David's staff`], "The phrase shows Goliath judging by sight."),
    p(I.star, "I Come To Thee In The Name Of The LORD Of Hosts", "David identifies the true power behind him.", [`${I.star} LORD of hosts`, `${I.battle} God's battle`, `${I.heart} Faith`], "The phrase is the heart of David's courage."),
    p(I.people, "That All The Earth May Know", "David wants the victory to reveal God beyond Israel.", [`${I.people} All the earth`, `${I.star} God known`, `${I.battle} Public witness`], "The phrase turns the fight into testimony."),
    p(I.battle, "The Battle Is The LORD'S", "David declares that victory belongs to God.", [`${I.battle} Battle`, `${I.star} The LORD's`, `${I.hand} God delivers`], "The phrase is the theological center of David and Goliath."),
  ]],
  [17, 48, 53, "Goliath Falls", I.stone, [
    p(I.hand, "David Hasted, And Ran Toward The Army", "David moves toward the threat instead of away from it.", [`${I.hand} Haste`, `${I.battle} Toward the army`, `${I.heart} Courage`], "The phrase shows active faith."),
    p(I.stone, "Smote The Philistine In His Forehead", "the stone strikes Goliath in the vulnerable place.", [`${I.stone} Stone`, `${I.eye} Forehead`, `${I.star} God gives victory`], "The phrase shows the giant falling through a small instrument."),
    p(I.spear, "There Was No Sword In The Hand Of David", "David wins without the weapon expected for battle.", [`${I.spear} No sword`, `${I.hand} Sling and stone`, `${I.star} God's power`], "The phrase underlines that victory did not come through normal strength."),
    p(I.battle, "The Men Of Israel And Of Judah Arose", "David's victory gives courage to the army.", [`${I.battle} Army rises`, `${I.people} Israel and Judah`, `${I.warning} Philistines flee`], "The phrase shows one faithful victory strengthening many."),
  ]],
  [17, 55, 58, "Saul Asks About David", I.question, [
    p(I.question, "Whose Son Is This Youth", "Saul asks about David's family identity.", [`${I.question} Whose son`, `${I.king} Saul`, `${I.house} Jesse's house`], "The phrase shows David becoming publicly significant."),
    p(I.hand, "Abner, Inquire Thou Whose Son The Stripling Is", "Saul orders Abner to identify David.", [`${I.hand} Inquiry`, `${I.people} Abner`, `${I.eye} David noticed`], "The phrase shows the court turning attention toward David."),
    p(I.battle, "With The Head Of The Philistine In His Hand", "David returns with proof of victory.", [`${I.hand} Goliath's head`, `${I.battle} Defeated enemy`, `${I.star} Victory visible`], "The phrase makes the victory undeniable."),
    p(I.house, "I Am The Son Of Thy Servant Jesse", "David answers by naming his father and humble household.", [`${I.house} Jesse`, `${I.city} Bethlehemite`, `${I.heart} Humble answer`], "The phrase keeps David's identity simple even after a great victory."),
  ]],
  [18, 1, 5, "Jonathan Loves David", I.heart, [
    p(I.heart, "The Soul Of Jonathan Was Knit With The Soul Of David", "Jonathan's heart becomes deeply bound to David in loyal friendship.", [`${I.heart} Souls knit`, `${I.people} Jonathan and David`, `${I.hand} Covenant friendship`], "The phrase introduces one of the Bible's strongest friendships."),
    p(I.robe, "Jonathan Stripped Himself Of The Robe", "Jonathan gives David royal clothing and weapons.", [`${I.robe} Robe`, `${I.armor} Weapons`, `${I.king} Royal honor`], "The phrase shows Jonathan honoring David instead of envying him."),
    p(I.hand, "David Went Out Whithersoever Saul Sent Him", "David serves faithfully under Saul.", [`${I.hand} Sent by Saul`, `${I.battle} Military service`, `${I.heart} Faithful conduct`], "The phrase shows David succeeding without self-promotion."),
    p(I.star, "He Was Accepted In The Sight Of All The People", "David gains public favor.", [`${I.star} Favor`, `${I.people} People`, `${I.king} Saul's servants`], "The phrase explains why Saul's jealousy will grow."),
  ]],
  [18, 6, 9, "Saul Eyes David", I.eye, [
    p(I.people, "The Women Came Out Of All Cities Of Israel", "David's victory becomes a national celebration.", [`${I.people} Women singing`, `${I.city} Cities`, `${I.star} Public praise`], "The phrase shows how widely David is honored."),
    p(I.ear, "Saul Hath Slain His Thousands, And David His Ten Thousands", "the song compares Saul and David in a way that wounds Saul's pride.", [`${I.ear} Song`, `${I.king} Saul`, `${I.people} David praised more`], "The phrase becomes the spark of jealousy."),
    p(I.fire, "Saul Was Very Wroth", "Saul becomes angry at David's praise.", [`${I.fire} Anger`, `${I.eye} Comparison`, `${I.warning} Jealousy`], "The phrase shows Saul's heart turning against David."),
    p(I.eye, "Saul Eyed David From That Day And Forward", "Saul watches David with suspicion.", [`${I.eye} Suspicion`, `${I.warning} Jealousy grows`, `${I.heart} Heart poisoned`], "The phrase begins Saul's long hostility toward David."),
  ]],
  [18, 10, 15, "Saul Fears David", I.warning, [
    p(I.spear, "Saul Cast The Javelin", "Saul tries to kill David in a sudden act of violence.", [`${I.spear} Javelin`, `${I.warning} Murderous jealousy`, `${I.harp} David serving`], "The phrase shows jealousy becoming deadly."),
    p(I.hand, "David Avoided Out Of His Presence Twice", "David escapes Saul's attacks more than once.", [`${I.hand} David escapes`, `${I.spear} Twice attacked`, `${I.star} Protected`], "The phrase shows God preserving David."),
    p(I.warning, "Saul Was Afraid Of David", "Saul fears David because the LORD is with him.", [`${I.warning} Saul afraid`, `${I.star} LORD with David`, `${I.king} Kingdom tension`], "The phrase reveals the spiritual reason for Saul's fear."),
    p(I.people, "All Israel And Judah Loved David", "David is loved by the people he leads.", [`${I.people} Israel and Judah`, `${I.heart} Loved David`, `${I.battle} He went out and came in`], "The phrase shows David's favor growing while Saul's fear grows too."),
  ]],
  [18, 17, 22, "Saul Uses Marriage As A Trap", I.heart, [
    p(I.question, "Who Am I", "David responds humbly to the offer of marriage into Saul's family.", [`${I.question} Humility`, `${I.king} King's son in law`, `${I.house} David's family`], "The phrase shows David not grasping at status."),
    p(I.warning, "Let The Hand Of The Philistines Be Against Him", "Saul plans to use danger against David.", [`${I.warning} Hidden plot`, `${I.battle} Philistines`, `${I.king} Saul's manipulation`], "The phrase shows Saul disguising murder as opportunity."),
    p(I.heart, "Michal Saul's Daughter Loved David", "Michal's love becomes part of Saul's plan.", [`${I.heart} Michal`, `${I.people} David`, `${I.warning} Saul uses love`], "The phrase shows relationships being pulled into Saul's jealousy."),
    p(I.hand, "David Behaved Himself More Wisely", "David keeps acting with wisdom under pressure.", [`${I.hand} Wisdom`, `${I.warning} Saul's plots`, `${I.star} Favor grows`], "The phrase explains why David's name becomes highly valued."),
  ]],
  [19, 1, 6, "Jonathan Warns David", I.warning, [
    p(I.warning, "Saul Spake To Jonathan His Son, And To All His Servants, That They Should Kill David", "Saul's private jealousy becomes an open death order.", [`${I.warning} Kill David`, `${I.king} Saul`, `${I.people} Servants told`], "The phrase marks a darker stage in Saul's pursuit."),
    p(I.heart, "Jonathan Saul's Son Delighted Much In David", "Jonathan's love for David resists Saul's hatred.", [`${I.heart} Jonathan's loyalty`, `${I.people} David`, `${I.warning} Family conflict`], "The phrase shows covenant friendship under pressure."),
    p(I.ear, "Take Heed To Thyself Until The Morning", "Jonathan warns David to hide and stay safe.", [`${I.ear} Warning`, `${I.hand} Hide`, `${I.heart} Friend protects friend`], "The phrase shows love acting wisely."),
    p(I.hand, "Jonathan Spake Good Of David Unto Saul", "Jonathan intercedes for David before Saul.", [`${I.hand} Speaks good`, `${I.king} Saul`, `${I.heart} Defense of David`], "The phrase shows Jonathan using his place to protect the innocent."),
  ]],
  [19, 8, 13, "Michal Helps David Escape", I.house, [
    p(I.battle, "David Slew Them With A Great Slaughter", "David keeps serving Israel successfully.", [`${I.battle} Victory`, `${I.people} Philistines`, `${I.warning} Saul's jealousy stirred`], "The phrase shows David's faithfulness becoming another trigger for Saul."),
    p(I.spear, "Saul Sought To Smite David Even To The Wall", "Saul again tries to pin David with a spear.", [`${I.spear} Spear attack`, `${I.harp} David playing`, `${I.warning} Murder attempt`], "The phrase shows Saul's violence returning."),
    p(I.hand, "Michal Let David Down Through A Window", "Michal helps David escape Saul's messengers.", [`${I.hand} Window escape`, `${I.heart} Michal helps`, `${I.warning} Night danger`], "The phrase shows David's own wife protecting his life."),
    p(I.house, "There Was An Image In The Bed", "Michal uses a household image to delay Saul's men.", [`${I.house} Bed deception`, `${I.eye} Delay`, `${I.warning} Escape plan`], "The phrase shows the desperate measures around David's flight."),
  ]],
  [19, 18, 23, "Saul Prophesies At Ramah", I.spirit, [
    p(I.hand, "David Fled, And Escaped", "David leaves Saul and goes to Samuel.", [`${I.hand} Flight`, `${I.city} Ramah`, `${I.scroll} Samuel`], "The phrase moves David from court danger to prophetic refuge."),
    p(I.spirit, "The Spirit Of God Was Upon The Messengers Of Saul", "God interrupts Saul's messengers through prophetic power.", [`${I.spirit} Spirit`, `${I.people} Messengers`, `${I.star} God stops pursuit`], "The phrase shows God protecting David in a surprising way."),
    p(I.question, "Is Saul Also Among The Prophets", "Saul himself is overcome in prophetic behavior.", [`${I.question} Old saying repeated`, `${I.king} Saul humbled`, `${I.spirit} Spirit's power`], "The phrase shows Saul unable to control the situation."),
    p(I.robe, "He Stripped Off His Clothes Also", "Saul is publicly humbled before Samuel.", [`${I.robe} Stripped`, `${I.sorrow} Humiliation`, `${I.warning} King brought low`], "The phrase shows the pursuing king reduced and exposed."),
  ]],
  [20, 1, 6, "David And Jonathan Make A Plan", I.heart, [
    p(I.question, "What Have I Done", "David asks why Saul is trying to kill him.", [`${I.question} David's confusion`, `${I.warning} Saul's hostility`, `${I.heart} Innocence`], "The phrase shows David seeking honest understanding."),
    p(I.sorrow, "There Is But A Step Between Me And Death", "David feels how close danger has come.", [`${I.sorrow} Near death`, `${I.warning} Saul's threat`, `${I.heart} David's fear`], "The phrase makes David's danger personal."),
    p(I.hand, "Whatsoever Thy Soul Desireth, I Will Even Do It For Thee", "Jonathan pledges loyal help to David.", [`${I.hand} Loyal help`, `${I.heart} Friendship`, `${I.people} Covenant trust`], "The phrase shows Jonathan's friendship becoming action."),
    p(I.question, "Who Shall Tell Me", "David asks how he will know Saul's heart.", [`${I.question} Need for a sign`, `${I.warning} Danger uncertain`, `${I.heart} Trusting Jonathan`], "The phrase sets up the arrow signal."),
  ]],
  [20, 11, 16, "The Covenant Is Renewed", I.scroll, [
    p(I.hand, "Come, And Let Us Go Out Into The Field", "Jonathan takes David away for private covenant conversation.", [`${I.hand} Come`, `${I.field} Field`, `${I.heart} Private loyalty`], "The phrase creates a safe place for truth."),
    p(I.star, "The LORD God Of Israel Be Witness", "Jonathan places their agreement before God.", [`${I.star} Divine witness`, `${I.heart} Covenant`, `${I.people} David and Jonathan`], "The phrase makes friendship covenantal, not casual."),
    p(I.hand, "I Will Shew It Thee", "Jonathan promises to reveal Saul's intentions.", [`${I.hand} Promise`, `${I.ear} News shared`, `${I.warning} Danger clarified`], "The phrase shows loyalty through truth telling."),
    p(I.heart, "Jonathan Caused David To Swear Again", "Jonathan renews the covenant because he loves David.", [`${I.heart} Love`, `${I.scroll} Oath`, `${I.house} Future families`], "The phrase binds their friendship across future danger."),
  ]],
  [20, 18, 23, "The Arrow Signal", I.arrow, [
    p(I.arrow, "Thou Shalt Be Missed", "Jonathan says David's empty seat will be noticed.", [`${I.arrow} Signal setup`, `${I.house} King's table`, `${I.warning} Saul's reaction tested`], "The phrase makes absence part of the plan."),
    p(I.stone, "By The Stone Ezel", "David is told where to hide.", [`${I.stone} Stone Ezel`, `${I.hand} Hiding place`, `${I.arrow} Signal location`], "The phrase grounds the plan in a specific place."),
    p(I.arrow, "I Will Shoot Three Arrows", "Jonathan creates a coded way to communicate danger.", [`${I.arrow} Three arrows`, `${I.eye} Watch carefully`, `${I.warning} Hidden message`], "The phrase shows wisdom protecting David without direct speech."),
    p(I.star, "The LORD Be Between Thee And Me For Ever", "Jonathan trusts the LORD to guard their covenant beyond the moment.", [`${I.star} The LORD between`, `${I.heart} Friendship`, `${I.house} Families forever`], "The phrase gives their loyalty lasting spiritual weight."),
  ]],
  [20, 24, 29, "Saul's Anger Reveals The Truth", I.fire, [
    p(I.house, "David's Place Was Empty", "David's absence tests Saul's heart.", [`${I.house} Empty seat`, `${I.warning} Hidden test`, `${I.king} Saul watched`], "The phrase begins the reveal."),
    p(I.question, "Wherefore Cometh Not The Son Of Jesse", "Saul asks why David is missing.", [`${I.question} Saul asks`, `${I.house} Feast table`, `${I.warning} Suspicion`], "The phrase shows Saul focused on David."),
    p(I.fire, "Saul's Anger Was Kindled Against Jonathan", "Saul turns his rage on his own son.", [`${I.fire} Anger`, `${I.heart} Jonathan loyal`, `${I.warning} Saul exposed`], "The phrase proves Saul's hatred has become irrational."),
    p(I.spear, "Saul Cast A Javelin At Him", "Saul tries to strike Jonathan too.", [`${I.spear} Javelin`, `${I.people} Jonathan threatened`, `${I.warning} Violent rage`], "The phrase confirms David truly is in danger."),
  ]],
  [20, 35, 40, "David And Jonathan Part", I.sorrow, [
    p(I.arrow, "Is Not The Arrow Beyond Thee", "Jonathan gives the signal that David must flee.", [`${I.arrow} Arrow beyond`, `${I.warning} Danger confirmed`, `${I.hand} Secret message`], "The phrase is the moment David receives the answer."),
    p(I.hand, "Make Speed, Haste, Stay Not", "Jonathan's words through the boy tell David to leave quickly.", [`${I.hand} Hurry`, `${I.warning} Do not stay`, `${I.sorrow} Flight begins`], "The phrase turns warning into action."),
    p(I.sorrow, "They Kissed One Another, And Wept One With Another", "David and Jonathan grieve their separation.", [`${I.sorrow} Weeping`, `${I.heart} Covenant friendship`, `${I.warning} Dangerous future`], "The phrase shows the emotional cost of Saul's sin."),
    p(I.star, "The LORD Be Between Me And Thee", "Jonathan sends David away with covenant faith before God.", [`${I.star} The LORD`, `${I.heart} Friendship`, `${I.house} Descendants`], "The phrase keeps their bond alive even as they part."),
  ]],
  [21, 1, 6, "David Receives Holy Bread", I.bread, [
    p(I.city, "David Came To Nob To Ahimelech The Priest", "David seeks help from the priest at Nob.", [`${I.city} Nob`, `${I.priest} Ahimelech`, `${I.warning} David fleeing`], "The phrase moves David into sacred territory while he is vulnerable."),
    p(I.question, "Why Art Thou Alone", "Ahimelech notices David's unusual situation.", [`${I.question} Alone`, `${I.warning} Danger hidden`, `${I.priest} Priest concerned`], "The phrase signals that David's arrival is not normal."),
    p(I.bread, "There Is No Common Bread Under Mine Hand", "Ahimelech only has holy bread available.", [`${I.bread} Holy bread`, `${I.priest} Priest's hand`, `${I.warning} Unusual need`], "The phrase explains why this moment is exceptional."),
    p(I.hand, "So The Priest Gave Him Hallowed Bread", "David receives consecrated bread because of urgent need.", [`${I.bread} Hallowed bread`, `${I.hand} Mercy`, `${I.sorrow} Fugitive need`], "The phrase shows mercy meeting David's hunger."),
  ]],
  [21, 7, 12, "David Flees To Gath", I.warning, [
    p(I.eye, "Doeg, An Edomite", "a dangerous observer is present at Nob.", [`${I.eye} Doeg sees`, `${I.warning} Future betrayal`, `${I.city} Nob at risk`], "The phrase quietly prepares the tragedy of chapter 22."),
    p(I.spear, "The Sword Of Goliath The Philistine", "David takes the weapon from his earlier victory.", [`${I.spear} Goliath's sword`, `${I.battle} Past victory`, `${I.warning} Present fear`], "The phrase connects David's courage and his current vulnerability."),
    p(I.city, "David Arose, And Fled That Day For Fear Of Saul", "David leaves Israelite territory because Saul threatens him.", [`${I.city} Gath`, `${I.sorrow} Fear`, `${I.warning} Exile begins`], "The phrase shows how far Saul's hatred drives David."),
    p(I.warning, "He Changed His Behaviour Before Them", "David pretends madness to survive in Gath.", [`${I.warning} Survival act`, `${I.city} Enemy city`, `${I.sorrow} Humiliation`], "The phrase shows David in a low and desperate place."),
  ]],
  [22, 1, 5, "David At Adullam", I.cave, [
    p(I.cave, "David Therefore Departed Thence, And Escaped To The Cave Adullam", "David finds refuge in a cave while fleeing Saul.", [`${I.cave} Adullam`, `${I.hand} Escape`, `${I.sorrow} Fugitive life`], "The phrase begins David's wilderness leadership."),
    p(I.people, "Every One That Was In Distress", "broken and burdened people gather to David.", [`${I.people} Distressed`, `${I.sorrow} In debt`, `${I.heart} Discontented`], "The phrase shows David becoming a leader of the hurting."),
    p(I.king, "He Became A Captain Over Them", "David begins leading a small band.", [`${I.king} Captain`, `${I.people} Four hundred men`, `${I.cave} Wilderness community`], "The phrase shows leadership forming before the throne."),
    p(I.ear, "Abide Not In The Hold", "the prophet Gad directs David to move.", [`${I.ear} Prophetic word`, `${I.hand} Move`, `${I.scroll} Guidance`], "The phrase shows David still needing God's direction."),
  ]],
  [22, 6, 10, "Doeg Reports David", I.warning, [
    p(I.king, "Saul Heard That David Was Discovered", "Saul learns where David has been.", [`${I.king} Saul`, `${I.warning} David discovered`, `${I.people} Servants gathered`], "The phrase resumes Saul's pursuit."),
    p(I.spear, "Having His Spear In His Hand", "Saul's spear remains a symbol of his violent paranoia.", [`${I.spear} Spear`, `${I.king} Saul seated`, `${I.warning} Threatening posture`], "The phrase shows Saul's leadership atmosphere."),
    p(I.question, "Will The Son Of Jesse Give Every One Of You Fields", "Saul manipulates his servants by appealing to reward and fear.", [`${I.question} Accusation`, `${I.king} Political pressure`, `${I.warning} Manipulation`], "The phrase shows Saul poisoning loyalty."),
    p(I.eye, "I Saw The Son Of Jesse Coming To Nob", "Doeg reports David's visit to Ahimelech.", [`${I.eye} Doeg saw`, `${I.city} Nob`, `${I.warning} Dangerous report`], "The phrase turns David's need into evidence against the priests."),
  ]],
  [22, 11, 16, "Nob Is Slaughtered", I.sorrow, [
    p(I.question, "Why Have Ye Conspired Against Me", "Saul falsely accuses Ahimelech of treason.", [`${I.question} False charge`, `${I.priest} Priest accused`, `${I.warning} Saul's paranoia`], "The phrase shows Saul interpreting mercy as conspiracy."),
    p(I.hand, "Who Is So Faithful Among All Thy Servants As David", "Ahimelech defends David's loyalty.", [`${I.hand} Faithful David`, `${I.king} King's son in law`, `${I.priest} Priest speaks truth`], "The phrase shows David's innocence in Saul's own court."),
    p(I.spear, "Slay The Priests Of The LORD", "Saul commands the murder of priests.", [`${I.spear} Horrific command`, `${I.priest} Priests of the LORD`, `${I.warning} Saul's collapse`], "The phrase shows Saul fighting against God's servants."),
    p(I.fire, "Nob, The City Of The Priests, Smote He With The Edge Of The Sword", "Doeg destroys the priestly city.", [`${I.fire} Nob destroyed`, `${I.sorrow} Innocent lives`, `${I.warning} Saul's sin spreads`], "The phrase is one of Saul's darkest acts."),
  ]],
  [22, 20, 23, "Abiathar Escapes", I.hand, [
    p(I.hand, "One Of The Sons Of Ahimelech Escaped", "Abiathar survives the slaughter at Nob.", [`${I.hand} Survivor`, `${I.priest} Abiathar`, `${I.sorrow} Tragedy behind him`], "The phrase preserves a priestly remnant."),
    p(I.ear, "Abiathar Shewed David That Saul Had Slain The LORD'S Priests", "David hears the terrible news.", [`${I.ear} Report`, `${I.sorrow} Priests slain`, `${I.warning} Saul's violence`], "The phrase brings the weight of Nob to David."),
    p(I.sorrow, "I Have Occasioned The Death Of All The Persons", "David feels responsibility because Doeg saw him at Nob.", [`${I.sorrow} David's grief`, `${I.eye} Doeg's witness`, `${I.priest} Nob's loss`], "The phrase shows David grieving consequences."),
    p(I.hand, "With Me Thou Shalt Be In Safeguard", "David promises protection to Abiathar.", [`${I.hand} Protection`, `${I.priest} Abiathar`, `${I.cave} Refuge with David`], "The phrase shows David sheltering what Saul destroyed."),
  ]],
  [23, 1, 6, "David Rescues Keilah", I.battle, [
    p(I.ear, "The Philistines Fight Against Keilah", "David hears that a city is under attack.", [`${I.ear} News`, `${I.city} Keilah`, `${I.battle} Philistines`], "The phrase shows David caring about Israel even while hunted."),
    p(I.question, "Shall I Go And Smite These Philistines", "David asks the LORD before acting.", [`${I.question} Inquiry`, `${I.prayer} Ask God`, `${I.battle} Rescue decision`], "The phrase shows David's dependence on God's direction."),
    p(I.hand, "Go, And Smite The Philistines, And Save Keilah", "the LORD sends David to rescue the city.", [`${I.hand} Go`, `${I.battle} Smite`, `${I.city} Save Keilah`], "The phrase shows David's mission comes from God."),
    p(I.priest, "Abiathar Came Down With An Ephod In His Hand", "the priestly means of inquiry is with David.", [`${I.priest} Abiathar`, `${I.hand} Ephod`, `${I.prayer} Guidance`], "The phrase shows priestly guidance staying with David."),
  ]],
  [23, 7, 12, "Saul Hunts David At Keilah", I.warning, [
    p(I.king, "God Hath Delivered Him Into Mine Hand", "Saul wrongly interprets David's location as divine opportunity.", [`${I.king} Saul`, `${I.hand} False claim`, `${I.warning} Twisted religion`], "The phrase shows Saul using God-language for a murderous pursuit."),
    p(I.question, "Will The Men Of Keilah Deliver Me Up", "David asks whether the rescued city will betray him.", [`${I.question} Betrayal question`, `${I.city} Keilah`, `${I.warning} Danger`], "The phrase shows David seeking truth before trusting circumstances."),
    p(I.hand, "They Will Deliver Thee Up", "the LORD tells David the city would surrender him.", [`${I.hand} Hard answer`, `${I.city} Keilah`, `${I.warning} David must leave`], "The phrase shows guidance can protect from betrayal."),
    p(I.hill, "David Abode In The Wilderness In Strong Holds", "David lives in rugged hiding places.", [`${I.hill} Wilderness`, `${I.cave} Strong holds`, `${I.sorrow} Fugitive life`], "The phrase describes David's life before the throne."),
  ]],
  [23, 15, 18, "Jonathan Strengthens David", I.heart, [
    p(I.warning, "David Saw That Saul Was Come Out To Seek His Life", "David knows Saul is actively hunting him.", [`${I.warning} Life threatened`, `${I.king} Saul pursues`, `${I.hill} Wilderness`], "The phrase sets the emotional weight of Jonathan's visit."),
    p(I.heart, "Jonathan Saul's Son Arose", "Jonathan takes initiative to come to David.", [`${I.heart} Loyal friend`, `${I.hand} Jonathan comes`, `${I.warning} Risk`], "The phrase shows friendship crossing danger."),
    p(I.hand, "Strengthened His Hand In God", "Jonathan encourages David's faith in the LORD.", [`${I.hand} Strengthened hand`, `${I.star} In God`, `${I.heart} Covenant encouragement`], "The phrase is one of the best pictures of spiritual friendship."),
    p(I.king, "Thou Shalt Be King Over Israel", "Jonathan affirms God's future for David.", [`${I.king} David's future`, `${I.heart} Jonathan's humility`, `${I.star} God's promise`], "The phrase shows Jonathan accepting David's calling without envy."),
  ]],
  [23, 19, 24, "David Escapes At The Rock", I.rock, [
    p(I.warning, "Came Up The Ziphites To Saul", "local people report David's location to Saul.", [`${I.warning} Betrayal`, `${I.city} Ziph`, `${I.king} Saul informed`], "The phrase shows danger coming from inside Judah."),
    p(I.eye, "See Therefore, And Take Knowledge", "Saul asks for detailed surveillance.", [`${I.eye} Watch carefully`, `${I.warning} Hunt`, `${I.hand} Bring certainty`], "The phrase shows Saul's obsession becoming organized."),
    p(I.rock, "Saul Went On This Side Of The Mountain, And David On That Side", "David and Saul are separated by the mountain at a tense moment.", [`${I.rock} Mountain`, `${I.warning} Close call`, `${I.hand} Escape forming`], "The phrase makes the rescue feel narrow."),
    p(I.hand, "There Came A Messenger Unto Saul", "a sudden Philistine threat pulls Saul away.", [`${I.hand} Messenger`, `${I.battle} Philistines invade`, `${I.star} Providence`], "The phrase shows God making a way out."),
  ]],
  [24, 1, 6, "David Cuts Saul's Robe", I.cave, [
    p(I.cave, "Saul Went In To Cover His Feet", "Saul unknowingly enters the cave where David is hiding.", [`${I.cave} Cave`, `${I.king} Saul vulnerable`, `${I.warning} Test for David`], "The phrase creates a moment where David could take revenge."),
    p(I.hand, "The LORD Hath Delivered Thine Enemy Into Thine Hand", "David's men interpret the moment as permission to kill Saul.", [`${I.hand} Enemy in hand`, `${I.question} Interpretation`, `${I.warning} Temptation`], "The phrase shows how opportunity still needs obedience."),
    p(I.cut, "Cut Off The Skirt Of Saul's Robe Privily", "David secretly cuts Saul's robe instead of killing him.", [`${I.cut} Robe cut`, `${I.hand} Restraint`, `${I.king} Saul spared`], "The phrase becomes proof of mercy."),
    p(I.heart, "David's Heart Smote Him", "David's conscience is troubled even for cutting the robe.", [`${I.heart} Conscience`, `${I.robe} Robe edge`, `${I.star} Reverence for anointing`], "The phrase shows David's sensitivity toward God's authority."),
  ]],
  [24, 8, 13, "David Appeals To The LORD", I.prayer, [
    p(I.hand, "My Hand Shall Not Be Upon Thee", "David refuses to kill Saul.", [`${I.hand} No revenge`, `${I.king} Saul spared`, `${I.star} Trusting God`], "The phrase shows David leaving judgment with the LORD."),
    p(I.eye, "Thine Eyes Have Seen", "David points to visible proof that he spared Saul.", [`${I.eye} Proof`, `${I.robe} Robe in hand`, `${I.hand} Mercy shown`], "The phrase forces Saul to see David's innocence."),
    p(I.prayer, "The LORD Judge Between Me And Thee", "David appeals to God as judge.", [`${I.prayer} God judges`, `${I.warning} Saul's wrong`, `${I.hand} David restrained`], "The phrase shows David refusing personal vengeance."),
    p(I.question, "After Whom Is The King Of Israel Come Out", "David asks why Saul hunts someone so small and harmless.", [`${I.question} Why hunt David`, `${I.king} King of Israel`, `${I.sorrow} Fugitive humility`], "The phrase exposes the absurdity of Saul's pursuit."),
  ]],
  [24, 16, 21, "Saul Weeps", I.sorrow, [
    p(I.sorrow, "Saul Lifted Up His Voice, And Wept", "Saul is emotionally overcome by David's mercy.", [`${I.sorrow} Weeping`, `${I.king} Saul`, `${I.hand} Mercy received`], "The phrase shows a temporary softening in Saul."),
    p(I.hand, "Thou Art More Righteous Than I", "Saul admits David has acted better than he has.", [`${I.hand} Righteous conduct`, `${I.warning} Saul admits wrong`, `${I.star} David vindicated`], "The phrase is a rare honest confession from Saul."),
    p(I.king, "Thou Shalt Surely Be King", "Saul acknowledges David's future kingship.", [`${I.king} Future king`, `${I.star} God's plan`, `${I.sorrow} Saul knows`], "The phrase confirms what Jonathan already knew."),
    p(I.house, "Swear Now Therefore Unto Me By The LORD", "Saul asks David to preserve his family line.", [`${I.house} Saul's seed`, `${I.prayer} Oath before LORD`, `${I.hand} Mercy for future`], "The phrase shows David's mercy extending beyond the moment."),
  ]],
  [25, 1, 6, "David Requests Food From Nabal", I.food, [
    p(I.sorrow, "Samuel Died", "Israel loses the prophet who anointed David and confronted Saul.", [`${I.sorrow} Samuel dies`, `${I.people} Israel mourns`, `${I.scroll} A major transition`], "The phrase marks the end of an era."),
    p(I.people, "The Man Was Very Great", "Nabal is wealthy and powerful in livestock.", [`${I.people} Nabal`, `${I.lamb} Sheep and goats`, `${I.warning} Wealth without wisdom`], "The phrase sets up his responsibility to act generously."),
    p(I.hand, "Let The Young Men Find Favour In Thine Eyes", "David asks Nabal for kindness during a feast time.", [`${I.hand} Request`, `${I.food} Provision`, `${I.heart} Favor`], "The phrase shows David asking, not taking."),
    p(I.star, "We Come In A Good Day", "David appeals to the celebration and abundance of sheep-shearing.", [`${I.star} Feast day`, `${I.food} Plenty`, `${I.hand} Opportunity for generosity`], "The phrase makes Nabal's refusal more shameful."),
  ]],
  [25, 9, 13, "Nabal Refuses David", I.warning, [
    p(I.warning, "Who Is David", "Nabal insults David by pretending he is unimportant.", [`${I.warning} Insult`, `${I.people} David dismissed`, `${I.heart} Pride`], "The phrase shows contempt instead of gratitude."),
    p(I.question, "Shall I Then Take My Bread", "Nabal treats his possessions as only his own.", [`${I.question} My bread`, `${I.food} My water`, `${I.lamb} My flesh`], "The phrase exposes selfishness."),
    p(I.spear, "Gird Ye On Every Man His Sword", "David reacts in anger and prepares for violence.", [`${I.spear} Swords`, `${I.fire} Anger`, `${I.warning} Dangerous reaction`], "The phrase shows David is not perfect in this scene."),
    p(I.people, "About Four Hundred Men Went Up After David", "David moves with a large armed group.", [`${I.people} Four hundred`, `${I.battle} Armed response`, `${I.warning} Bloodshed near`], "The phrase raises the stakes."),
  ]],
  [25, 14, 19, "A Servant Warns Abigail", I.ear, [
    p(I.ear, "One Of The Young Men Told Abigail", "a servant wisely informs Abigail of the danger.", [`${I.ear} Report`, `${I.people} Servant`, `${I.hand} Abigail warned`], "The phrase begins the rescue from disaster."),
    p(I.hand, "The Men Were Very Good Unto Us", "the servant testifies that David's men protected them.", [`${I.hand} Good treatment`, `${I.lamb} Shepherds protected`, `${I.star} David's restraint`], "The phrase shows Nabal's refusal was unjust."),
    p(I.warning, "He Is Such A Son Of Belial", "the servant describes Nabal as wicked and impossible to reason with.", [`${I.warning} Son of Belial`, `${I.ear} Cannot speak to him`, `${I.sorrow} Household danger`], "The phrase explains why Abigail must act."),
    p(I.fire, "Surely In Vain Have I Kept All That This Fellow Hath", "David speaks from anger and wounded justice.", [`${I.fire} Anger`, `${I.hand} Protection unrewarded`, `${I.warning} Revenge forming`], "The phrase shows David nearing sin."),
  ]],
  [25, 23, 28, "Abigail Pleads With David", I.hand, [
    p(I.hand, "Fell Before David On Her Face", "Abigail approaches David with humility.", [`${I.hand} Humility`, `${I.people} Abigail`, `${I.warning} Bloodshed prevention`], "The phrase shows wisdom entering through humility."),
    p(I.warning, "Let Not My Lord Regard This Man Of Belial", "Abigail names Nabal's folly without defending it.", [`${I.warning} Nabal's folly`, `${I.hand} Honest speech`, `${I.heart} Wise appeal`], "The phrase shows truth and peacemaking together."),
    p(I.prayer, "The LORD Hath Withholden Thee From Coming To Shed Blood", "Abigail sees God's mercy in stopping David's revenge.", [`${I.prayer} The LORD restrains`, `${I.spear} Bloodshed avoided`, `${I.heart} David spared from guilt`], "The phrase explains the spiritual importance of her intervention."),
    p(I.house, "The LORD Will Certainly Make My Lord A Sure House", "Abigail affirms David's future under God's promise.", [`${I.house} Sure house`, `${I.king} David's future`, `${I.star} God's promise`], "The phrase lifts David's eyes above revenge."),
  ]],
  [25, 32, 37, "David Is Restrained", I.heart, [
    p(I.star, "Blessed Be The LORD God Of Israel", "David recognizes God sent Abigail to stop him.", [`${I.star} Bless the LORD`, `${I.hand} Abigail sent`, `${I.warning} Sin prevented`], "The phrase shows David receiving correction well."),
    p(I.hand, "Blessed Be Thy Advice", "David blesses Abigail's wise counsel.", [`${I.hand} Wise advice`, `${I.heart} Humble correction`, `${I.spear} Bloodshed stopped`], "The phrase shows good leadership can accept rebuke."),
    p(I.warning, "The LORD Smote Nabal", "God judges Nabal without David taking revenge.", [`${I.warning} God judges`, `${I.people} Nabal dies`, `${I.hand} David restrained`], "The phrase confirms David did not need to avenge himself."),
    p(I.heart, "David Sent And Communed With Abigail", "David later takes Abigail as wife.", [`${I.heart} Abigail`, `${I.house} David's household`, `${I.star} Wisdom honored`], "The phrase closes the story with Abigail preserved and honored."),
  ]],
  [26, 1, 5, "Saul Pursues Again", I.warning, [
    p(I.warning, "The Ziphites Came Unto Saul", "the Ziphites again reveal David's location.", [`${I.warning} Betrayal`, `${I.city} Ziph`, `${I.king} Saul informed`], "The phrase repeats the pressure David faces from local informers."),
    p(I.battle, "Saul Arose, And Went Down To The Wilderness Of Ziph", "Saul resumes hunting David.", [`${I.battle} Saul moves`, `${I.hill} Wilderness`, `${I.warning} Pursuit returns`], "The phrase shows Saul's earlier tears did not produce lasting repentance."),
    p(I.eye, "David Sent Out Spies", "David watches Saul's movements carefully.", [`${I.eye} Spies`, `${I.hand} Careful knowledge`, `${I.warning} Survival wisdom`], "The phrase shows David acting wisely under threat."),
    p(I.spear, "Saul Lay In The Trench", "Saul sleeps in the camp with his spear nearby.", [`${I.spear} Spear`, `${I.king} Saul sleeping`, `${I.warning} Another test`], "The phrase sets up David's second chance to kill Saul."),
  ]],
  [26, 6, 11, "David Takes The Spear And Cruse", I.spear, [
    p(I.question, "Who Will Go Down With Me To Saul", "David asks who will join him in the dangerous descent.", [`${I.question} Who will go`, `${I.warning} Risk`, `${I.hand} Abishai volunteers`], "The phrase shows David initiating a bold but restrained act."),
    p(I.hand, "Destroy Him Not", "David refuses Abishai's offer to kill Saul.", [`${I.hand} Do not destroy`, `${I.king} Saul spared`, `${I.star} Reverence`], "The phrase shows David's consistent refusal to murder the anointed king."),
    p(I.star, "The LORD Shall Smite Him", "David trusts God to deal with Saul in God's time.", [`${I.star} The LORD judges`, `${I.hand} David restrained`, `${I.warning} Vengeance refused`], "The phrase shows faith waiting for God's justice."),
    p(I.spear, "David Took The Spear And The Cruse Of Water", "David takes proof that he could have killed Saul.", [`${I.spear} Spear`, `${I.water} Cruse of water`, `${I.eye} Evidence`], "The phrase gives David proof without bloodshed."),
  ]],
  [26, 13, 18, "David Calls Across The Hill", I.hill, [
    p(I.hill, "David Went Over To The Other Side", "David creates distance before speaking.", [`${I.hill} Other side`, `${I.warning} Safe distance`, `${I.ear} Public call`], "The phrase shows courage joined with wisdom."),
    p(I.question, "Art Not Thou A Valiant Man", "David challenges Abner's failure to guard Saul.", [`${I.question} Abner rebuked`, `${I.king} King unguarded`, `${I.spear} Spear missing`], "The phrase uses irony to expose the camp's weakness."),
    p(I.hand, "See Where The King's Spear Is", "David points to the evidence of mercy.", [`${I.hand} Look`, `${I.spear} Spear`, `${I.water} Water cruse`], "The phrase proves David spared Saul again."),
    p(I.sorrow, "They Have Driven Me Out This Day From Abiding In The Inheritance Of The LORD", "David grieves being pushed away from life in the land.", [`${I.sorrow} Driven out`, `${I.house} LORD's inheritance`, `${I.warning} Exile pain`], "The phrase shows Saul's pursuit has spiritual cost."),
  ]],
  [26, 21, 25, "Saul Admits Folly Again", I.sorrow, [
    p(I.sorrow, "I Have Sinned", "Saul admits wrong again after David spares him.", [`${I.sorrow} Confession`, `${I.king} Saul`, `${I.warning} Repeated failure`], "The phrase sounds hopeful, but Saul's pattern makes it sad."),
    p(I.warning, "I Have Played The Fool", "Saul names his own foolishness.", [`${I.warning} Foolishness`, `${I.king} Saul`, `${I.sorrow} Wasted pursuit`], "The phrase is a rare moment of clarity."),
    p(I.hand, "The LORD Render To Every Man His Righteousness", "David trusts God to repay faithfulness.", [`${I.hand} The LORD repays`, `${I.heart} Righteousness`, `${I.star} Faithfulness`], "The phrase explains why David does not seize revenge."),
    p(I.king, "Blessed Be Thou, My Son David", "Saul blesses David before they part.", [`${I.king} Saul blesses`, `${I.people} David`, `${I.sorrow} Temporary peace`], "The phrase closes another mercy scene, but the relationship remains broken."),
  ]],
  [27, 1, 6, "David Goes To Philistine Territory", I.city, [
    p(I.heart, "David Said In His Heart", "David reasons from fear inside himself.", [`${I.heart} Inner speech`, `${I.sorrow} Fear`, `${I.warning} Dangerous conclusion`], "The phrase shows even David can be pulled by fear."),
    p(I.warning, "I Shall Now Perish One Day By The Hand Of Saul", "David believes Saul will eventually kill him.", [`${I.warning} Fear of Saul`, `${I.sorrow} Weariness`, `${I.hand} Human reasoning`], "The phrase shows exhaustion pressing against faith."),
    p(I.city, "David Arose, And He Passed Over", "David moves into Philistine territory with his men.", [`${I.city} Philistine land`, `${I.people} Six hundred men`, `${I.warning} Complicated refuge`], "The phrase marks a troubling exile choice."),
    p(I.house, "Achish Gave Him Ziklag", "David receives a city from the Philistine king.", [`${I.house} Ziklag`, `${I.king} Achish`, `${I.city} Exile base`], "The phrase gives David a base outside Israel."),
  ]],
  [27, 8, 12, "David Deceives Achish", I.warning, [
    p(I.battle, "David And His Men Went Up, And Invaded", "David conducts raids while living under Achish.", [`${I.battle} Raids`, `${I.people} David's men`, `${I.warning} Hidden activity`], "The phrase shows David surviving in a morally complicated situation."),
    p(I.hand, "David Saved Neither Man Nor Woman Alive", "David leaves no witnesses from his raids.", [`${I.hand} No survivors`, `${I.warning} Severe action`, `${I.city} Report hidden`], "The phrase is dark and shows the danger of this season."),
    p(I.question, "Whither Have Ye Made A Road To Day", "Achish asks where David has raided.", [`${I.question} Achish asks`, `${I.warning} Deception`, `${I.city} False report`], "The phrase reveals David's double life."),
    p(I.heart, "Achish Believed David", "Achish trusts David's misleading reports.", [`${I.heart} Achish believes`, `${I.warning} David deceives`, `${I.king} Political protection`], "The phrase shows David gaining safety through deception."),
  ]],
  [28, 1, 6, "Saul Receives No Answer", I.sorrow, [
    p(I.battle, "The Philistines Gathered Their Armies Together", "another major battle with Philistia approaches.", [`${I.battle} Philistine army`, `${I.king} Saul threatened`, `${I.warning} Crisis`], "The phrase sets up Saul's final collapse."),
    p(I.warning, "Thou Shalt Know What Thy Servant Can Do", "David speaks ambiguously to Achish about fighting.", [`${I.warning} Ambiguous words`, `${I.king} Achish`, `${I.people} David`], "The phrase shows David trapped in a dangerous alliance."),
    p(I.sorrow, "Samuel Was Dead", "the prophet Saul once rejected is gone.", [`${I.sorrow} Samuel dead`, `${I.scroll} No prophet guide`, `${I.king} Saul alone`], "The phrase deepens Saul's isolation."),
    p(I.ear, "The LORD Answered Him Not", "Saul seeks guidance but receives no answer.", [`${I.ear} No answer`, `${I.prayer} Dreams`, `${I.scroll} Prophets`], "The phrase shows the tragedy of seeking God after resisting Him."),
  ]],
  [28, 7, 12, "Saul Seeks A Medium", I.warning, [
    p(I.warning, "Seek Me A Woman That Hath A Familiar Spirit", "Saul turns to forbidden spiritual practice.", [`${I.warning} Familiar spirit`, `${I.king} Saul desperate`, `${I.scroll} Law violated`], "The phrase shows Saul going where obedience forbids."),
    p(I.robe, "Saul Disguised Himself", "Saul hides his identity to pursue darkness.", [`${I.robe} Disguise`, `${I.warning} Secret sin`, `${I.sorrow} King in fear`], "The phrase shows shame and deception around his choice."),
    p(I.question, "Whom Shall I Bring Up Unto Thee", "the medium asks whose spirit Saul wants.", [`${I.question} Forbidden request`, `${I.sorrow} Samuel wanted`, `${I.warning} Dark scene`], "The phrase shows Saul trying to recover guidance through rebellion."),
    p(I.sorrow, "Saul Perceived That It Was Samuel", "Saul recognizes the figure as Samuel.", [`${I.sorrow} Samuel`, `${I.king} Saul afraid`, `${I.warning} Judgment coming`], "The phrase brings Saul face to face with the word he cannot escape."),
  ]],
  [28, 15, 19, "Samuel Announces Saul's End", I.sorrow, [
    p(I.sorrow, "I Am Sore Distressed", "Saul admits his desperate condition.", [`${I.sorrow} Distress`, `${I.battle} Philistines`, `${I.ear} No answer from God`], "The phrase shows the loneliness of rebellion."),
    p(I.warning, "Wherefore Then Dost Thou Ask Of Me", "Samuel asks why Saul seeks him when the LORD has departed.", [`${I.warning} Hard question`, `${I.king} Saul`, `${I.star} The LORD opposed`], "The phrase exposes Saul's impossible position."),
    p(I.king, "The LORD Hath Rent The Kingdom Out Of Thine Hand", "Samuel repeats that Saul's kingdom has been taken.", [`${I.king} Kingdom torn`, `${I.hand} Saul's hand`, `${I.people} David`], "The phrase confirms the earlier judgment."),
    p(I.sorrow, "Tomorrow Shalt Thou And Thy Sons Be With Me", "Samuel announces Saul's coming death.", [`${I.sorrow} Tomorrow`, `${I.people} Saul's sons`, `${I.battle} Death in battle`], "The phrase is devastating and final."),
  ]],
  [28, 20, 25, "Saul Is Strengthened For The Night", I.food, [
    p(I.sorrow, "Saul Fell Straightway All Along On The Earth", "Saul collapses under fear and weakness.", [`${I.sorrow} Collapse`, `${I.warning} Terrible word`, `${I.food} No strength`], "The phrase shows the king physically broken."),
    p(I.hand, "The Woman Came Unto Saul", "the medium now acts with concern toward Saul.", [`${I.hand} Woman comes`, `${I.sorrow} Saul afraid`, `${I.food} Food offered`], "The phrase is strange because care appears in a forbidden setting."),
    p(I.food, "Set A Morsel Of Bread Before Thee", "Saul is urged to eat before leaving.", [`${I.food} Bread`, `${I.hand} Strength`, `${I.sorrow} Heavy night`], "The phrase shows basic human need after spiritual disaster."),
    p(I.sorrow, "They Rose Up, And Went Away That Night", "Saul walks out into the night before his final battle.", [`${I.sorrow} Night`, `${I.battle} Battle ahead`, `${I.warning} End approaching`], "The phrase leaves the reader under the weight of Saul's doom."),
  ]],
  [29, 1, 5, "The Philistines Reject David", I.warning, [
    p(I.battle, "The Philistines Gathered Together All Their Armies", "David is caught near the Philistine war camp.", [`${I.battle} Philistine armies`, `${I.people} David with Achish`, `${I.warning} Dangerous position`], "The phrase shows David's exile choice reaching crisis."),
    p(I.question, "What Do These Hebrews Here", "the Philistine princes question David's presence.", [`${I.question} Suspicion`, `${I.people} Hebrews`, `${I.warning} David distrusted`], "The phrase shows the Philistines do not fully accept David."),
    p(I.king, "Is Not This David", "the princes recognize David's reputation.", [`${I.king} David known`, `${I.ear} Old song remembered`, `${I.warning} Trust questioned`], "The phrase shows David's past victory still shapes his present danger."),
    p(I.ear, "Saul Slew His Thousands, And David His Ten Thousands", "the old song becomes evidence against David among the Philistines.", [`${I.ear} Victory song`, `${I.people} David feared`, `${I.battle} Philistine memory`], "The phrase that angered Saul now alarms Philistine leaders."),
  ]],
  [29, 6, 11, "Achish Sends David Away", I.hand, [
    p(I.hand, "As The LORD Liveth, Thou Hast Been Upright", "Achish praises David using Israel's God-language.", [`${I.hand} Upright in Achish's eyes`, `${I.king} Philistine ruler`, `${I.warning} Complicated loyalty`], "The phrase shows how convincing David has been to Achish."),
    p(I.warning, "The Lords Favour Thee Not", "the Philistine rulers refuse to let David fight with them.", [`${I.warning} Rejected by princes`, `${I.people} David spared from battle`, `${I.battle} Conflict avoided`], "The phrase becomes a providential escape from fighting Israel."),
    p(I.question, "What Have I Done", "David protests in a way that keeps his cover.", [`${I.question} David asks`, `${I.warning} Ambiguous loyalty`, `${I.king} Achish convinced`], "The phrase shows David still navigating deception."),
    p(I.hand, "David And His Men Rose Up Early To Depart", "David leaves the Philistine army before the battle.", [`${I.hand} Departing`, `${I.people} David's men`, `${I.star} Providence`], "The phrase removes David from the fight where Saul will die."),
  ]],
  [30, 1, 6, "Ziklag Is Burned", I.fire, [
    p(I.fire, "The Amalekites Had Invaded The South, And Ziklag", "David's home base is attacked while he is away.", [`${I.fire} Ziklag burned`, `${I.warning} Amalekites`, `${I.sorrow} Families taken`], "The phrase brings David into sudden grief."),
    p(I.sorrow, "They Lifted Up Their Voice And Wept", "David and his men grieve until they have no strength.", [`${I.sorrow} Weeping`, `${I.people} David's men`, `${I.house} Families gone`], "The phrase shows real grief before rescue."),
    p(I.warning, "The People Spake Of Stoning Him", "David's men turn their grief toward him.", [`${I.warning} Stoning threat`, `${I.sorrow} Bitter souls`, `${I.people} Leadership pressure`], "The phrase shows David isolated under blame."),
    p(I.hand, "David Encouraged Himself In The LORD His God", "David strengthens himself by turning to the LORD.", [`${I.hand} Encouraged himself`, `${I.star} In the LORD`, `${I.sorrow} In deep distress`], "The phrase is one of David's clearest faith moments in crisis."),
  ]],
  [30, 7, 10, "David Pursues With God's Answer", I.prayer, [
    p(I.priest, "Bring Me Hither The Ephod", "David seeks priestly guidance before pursuing.", [`${I.priest} Ephod`, `${I.prayer} Inquiry`, `${I.warning} Crisis decision`], "The phrase shows David asking God instead of only reacting."),
    p(I.question, "Shall I Pursue After This Troop", "David asks the LORD whether to chase the raiders.", [`${I.question} Pursue?`, `${I.battle} Enemy troop`, `${I.hand} Need direction`], "The phrase models seeking God in urgent pain."),
    p(I.hand, "Pursue: For Thou Shalt Surely Overtake Them", "God gives David permission and promise.", [`${I.hand} Pursue`, `${I.battle} Overtake`, `${I.star} Recover all`], "The phrase gives hope before the rescue is visible."),
    p(I.water, "The Brook Besor", "two hundred exhausted men stop at the brook.", [`${I.water} Besor`, `${I.sorrow} Faint men`, `${I.people} Some continue`], "The phrase sets up David's later mercy toward those who stayed behind."),
  ]],
  [30, 11, 15, "The Egyptian Servant", I.hand, [
    p(I.hand, "They Found An Egyptian In The Field", "David's men find an abandoned servant.", [`${I.hand} Found servant`, `${I.field} Field`, `${I.star} Providence`], "The phrase shows God guiding David through an overlooked person."),
    p(I.food, "They Gave Him Bread, And He Did Eat", "David's men restore the servant with food and water.", [`${I.food} Bread`, `${I.water} Water`, `${I.hand} Mercy`], "The phrase shows mercy becoming the path to rescue."),
    p(I.sorrow, "My Master Left Me", "the servant was abandoned when he became sick.", [`${I.sorrow} Abandoned`, `${I.warning} Amalekite cruelty`, `${I.hand} David's mercy`], "The phrase contrasts David's care with Amalekite harshness."),
    p(I.question, "Canst Thou Bring Me Down To This Company", "David asks the servant to guide them to the raiders.", [`${I.question} Can you guide`, `${I.battle} Enemy camp`, `${I.hand} Rescue route`], "The phrase turns mercy toward one man into help for many."),
  ]],
  [30, 16, 20, "David Recovers All", I.star, [
    p(I.food, "They Were Spread Abroad Upon All The Earth, Eating And Drinking", "the raiders are careless in celebration.", [`${I.food} Feasting`, `${I.warning} Careless enemies`, `${I.battle} Attack coming`], "The phrase shows the enemy unprepared for David's arrival."),
    p(I.battle, "David Smote Them From The Twilight Even Unto The Evening", "David fights a long battle to rescue the captives.", [`${I.battle} Long fight`, `${I.hand} David acts`, `${I.sorrow} Families at stake`], "The phrase shows rescue requiring endurance."),
    p(I.star, "David Recovered All", "everything taken from David's people is restored.", [`${I.star} Recovered all`, `${I.house} Families restored`, `${I.hand} God's promise fulfilled`], "The phrase is the center of the chapter's hope."),
    p(I.people, "There Was Nothing Lacking To Them", "no person or possession is missing after the rescue.", [`${I.people} Sons and daughters`, `${I.house} Spoil restored`, `${I.star} Complete recovery`], "The phrase shows the fullness of God's mercy in the rescue."),
  ]],
  [30, 21, 26, "David Shares The Spoil", I.hand, [
    p(I.water, "The Brook Besor", "David returns to the men who were too exhausted to continue.", [`${I.water} Besor`, `${I.sorrow} Weary men`, `${I.hand} David returns`], "The phrase brings the story back to those who could not fight."),
    p(I.warning, "Men Of Belial", "some selfish men do not want to share the spoil.", [`${I.warning} Worthless men`, `${I.hand} Refusing share`, `${I.people} Division`], "The phrase exposes a hard-hearted response after mercy."),
    p(I.hand, "As His Part Is That Goeth Down To The Battle", "David rules that those who stayed with the supplies share equally.", [`${I.hand} Equal share`, `${I.battle} Fighters`, `${I.house} Supply keepers`], "The phrase shows David's generous leadership."),
    p(I.people, "He Sent Of The Spoil Unto The Elders Of Judah", "David shares blessing with Judah's towns.", [`${I.people} Elders`, `${I.house} Judah`, `${I.star} Gifts after rescue`], "The phrase shows David strengthening relationships before becoming king."),
  ]],
];

export const FIRST_SAMUEL_11_30_PERSONAL_SECTIONS: PersonalLeviticusPhraseSectionInput[] = [
  ...sections.map(section),
  ...DAY_61_80_FIRST_SAMUEL_11_30_SUPPLEMENTAL_SECTIONS,
];
