type GenesisTenPersonalSection = {
  chapter: number;
  startVerse: number;
  endVerse: number;
  reference: string;
  title: string;
  icon: string;
  phrases: Array<[string, string]>;
};

function normalizeReference(reference: string) {
  return reference.replace(/[–—]/g, "-").trim();
}

function parseReferenceParts(reference: string) {
  const normalized = normalizeReference(reference);
  const match = normalized.match(/^Genesis\s+(\d+):(\d+)-(\d+)$/i);

  if (!match) {
    throw new Error(`Could not parse Genesis 10 reference: ${reference}`);
  }

  return {
    reference: `Genesis ${match[1]}:${match[2]}-${match[3]}`,
    chapter: Number(match[1]),
    startVerse: Number(match[2]),
    endVerse: Number(match[3]),
  };
}

function stripOuterBold(line: string) {
  return line.replace(/^\*\*/, "").replace(/\*\*$/, "").trim();
}

function isSectionHeader(line: string) {
  return /^#\s*\*\*.*Genesis\s+10:\d+(?:-|–|—)\d+.*\*\*$/i.test(line.trim());
}

function isPhraseTitleLine(line: string) {
  const trimmed = line.trim();
  if (!/^\*\*.*\*\*$/.test(trimmed)) return false;
  const inner = stripOuterBold(trimmed);
  if (/^Genesis\s+10:/i.test(inner)) return false;
  const first = Array.from(inner)[0] || "";
  return !/[A-Za-z0-9]/.test(first);
}

function isInlineBoldBodyLine(line: string) {
  if (!(line.startsWith("**") && line.endsWith("**"))) return false;
  const inner = stripOuterBold(line);
  const first = inner.charAt(0);
  return /[A-Za-z]/.test(first);
}

function parseGenesisTenRawNotes(rawText: string): GenesisTenPersonalSection[] {
  const lines = rawText
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean);

  const sections: GenesisTenPersonalSection[] = [];
  let i = 0;

  while (i < lines.length) {
    const sectionLine = lines[i];
    if (!isSectionHeader(sectionLine)) {
      i += 1;
      continue;
    }

    const cleanedSectionLine = stripOuterBold(sectionLine.replace(/^#\s*/, "").trim());
    const referenceMatch = cleanedSectionLine.match(/Genesis\s+10:\d+(?:-|–|—)\d+/i);
    if (!referenceMatch) {
      i += 1;
      continue;
    }

    const displayReference = referenceMatch[0];
    const icon = cleanedSectionLine.slice(0, cleanedSectionLine.indexOf(displayReference)).trim();
    const parsed = parseReferenceParts(displayReference);

    i += 1;
    const rawTitle = lines[i] || "";
    const title = stripOuterBold(rawTitle);
    i += 1;

    const phrases: Array<[string, string]> = [];
    while (i < lines.length && !isSectionHeader(lines[i])) {
      if (!isPhraseTitleLine(lines[i])) {
        i += 1;
        continue;
      }

      const phraseTitle = stripOuterBold(lines[i]);
      i += 1;
      const body: string[] = [];

      while (i < lines.length && !isSectionHeader(lines[i]) && !isPhraseTitleLine(lines[i])) {
        if (!isInlineBoldBodyLine(lines[i])) {
          body.push(lines[i]);
        }
        i += 1;
      }

      phrases.push([phraseTitle, body.join("\n\n").trim()]);
    }

    sections.push({
      chapter: parsed.chapter,
      startVerse: parsed.startVerse,
      endVerse: parsed.endVerse,
      reference: parsed.reference,
      title,
      icon,
      phrases,
    });
  }

  return sections;
}

export const GENESIS_TEN_RAW_NOTES = [
  "# **🌍 Genesis 10:1–2**",
  "",
  "**Noah’s Descendants** ",
  "",
  "**👨‍👩‍👦 Now These Are The Generations Of The Sons Of Noah**",
  "",
  "The word **generations** means descendants or the family line that comes from someone.",
  "",
  "Genesis 9 ended with Noah’s death.",
  "",
  "Now the story shifts from Noah to his three sons and the nations that would come from them.",
  "",
  "This chapter explains how the earth was repopulated after the flood.",
  "",
  "👨‍👩‍👦 Generations means descendants",
  "",
  "📖 The focus moves from Noah to his sons",
  "",
  "🌍 The nations begin forming",
  "",
  "➡️ Humanity spreads across the earth",
  "",
  "**👶 Unto Them Were Sons Born After The Flood**",
  "",
  "After leaving the ark, Noah’s sons had children.",
  "",
  "This does **not** mean these were their only children.",
  "",
  "Moses records the family lines that became important nations, not every son and daughter that was born.",
  "",
  "👶 More children were born",
  "",
  "📖 Important family lines are recorded",
  "",
  "🌍 The earth begins filling again",
  "",
  "👨‍👩‍👧 Not every child is listed",
  "",
  "# **🌍 Genesis 10:3–5**",
  "",
  "**🌍 The Sons Of Japheth**",
  "",
  "Japheth had seven sons:",
  "",
  "**Gomer** — Connected with people who settled around the Black Sea.",
  "",
  "**Magog** — Connected with nations north of Israel and mentioned later in Ezekiel and Revelation.",
  "",
  "**Madai** — Ancestor of the Medes, who later became part of the Medo Persian Empire.",
  "",
  "**Javan** — Connected with ancient Greece.",
  "",
  "**Tubal** — Connected with people who settled in Asia Minor, modern day Turkey.",
  "",
  "**Meshech** — Connected with regions north of Israel and often mentioned together with Tubal.",
  "",
  "**Tiras** — Traditionally connected with peoples who settled around the Aegean Sea.",
  "",
  "🌍 Japheth had seven sons",
  "",
  "🗺️ Their descendants settled north and west of Israel",
  "",
  "📖 They became many ancient nations",
  "",
  "➡️ Moses traces the beginning of these nations",
  "",
  "**👨‍👦 The Sons Of Gomer**",
  "",
  "Gomer had three sons:",
  "",
  "**Ashkenaz** — Connected with peoples who settled north of Israel and around the Black Sea.",
  "",
  "**Riphath** — Little is known, but his descendants became another ancient people group.",
  "",
  "**Togarmah** — Connected with Armenia and eastern Asia Minor.",
  "",
  "👨‍👦 Gomer’s family continued growing",
  "",
  "🌍 More tribes and nations developed",
  "",
  "📖 Noah’s descendants continued spreading",
  "",
  "➡️ The family tree expands",
  "",
  "**👨‍👦 The Sons Of Javan**",
  "",
  "Javan had four sons:",
  "",
  "**Elishah** — Connected with islands in the Mediterranean.",
  "",
  "**Tarshish** — Known for ships and long distance trade. Possibly connected with Spain or other western ports.",
  "",
  "**Kittim** — Connected with Cyprus and nearby islands.",
  "",
  "**Dodanim** — Connected with people around the Aegean Sea.",
  "",
  "👨‍👦 Javan’s descendants spread along the coast",
  "",
  "🌊 Many settled around the Mediterranean Sea",
  "",
  "📖 Trade and seafaring nations developed",
  "",
  "➡️ The family tree continues",
  "",
  "**🌊 By These Were The Isles Of The Gentiles Divided**",
  "",
  "**Isles** means islands, coastlands, or lands across the sea.",
  "",
  "**Gentiles** means the nations or people who were not Israelites.",
  "",
  "Moses is explaining that many of the coastal and distant nations came from Japheth’s descendants.",
  "",
  "🌊 Isles means coastlands and islands",
  "",
  "🌍 Gentiles means the nations",
  "",
  "📖 Many distant nations came from Japheth",
  "",
  "➡️ The earth continued spreading",
  "",
  "**🗺️ Divided In Their Lands**",
  "",
  "As families grew, they settled in different places.",
  "",
  "Over time they formed their own territories and nations.",
  "",
  "🗺️ Families settled in different lands",
  "",
  "🌍 Territories were established",
  "",
  "📖 Nations began forming",
  "",
  "➡️ People spread across the earth",
  "",
  "**🗣️ Every One After His Tongue**",
  "",
  "**Tongue** means language.",
  "",
  "Each family eventually developed its own language.",
  "",
  "Genesis 11 explains how those languages came to exist at the Tower of Babel.",
  "",
  "🗣️ Tongue means language",
  "",
  "🌍 Different languages developed",
  "",
  "📖 Genesis 11 explains why",
  "",
  "➡️ Moses is summarizing what happened",
  "",
  "**👨‍👩‍👧 After Their Families, In Their Nations**",
  "",
  "As families grew larger, they became tribes.",
  "",
  "Over time those tribes became nations.",
  "",
  "Genesis 10 is often called the **Table of Nations** because it records where many of the ancient nations began.",
  "",
  "👨‍👩‍👧 Families became tribes",
  "",
  "🌍 Tribes became nations",
  "",
  "📖 The world spread from Noah’s family",
  "",
  "➡️ The nations of the earth began",
  "",
  "# **🌍 Genesis 10:6–20**",
  "",
  "**The Sons of Ham**",
  "",
  "**👨‍👩‍👦 The Sons Of Ham**",
  "",
  "Ham, one of Noah’s three sons, had four sons:",
  "",
  "**Cush** — Ancestor of peoples who settled south of Egypt, especially in the region of Ethiopia and Sudan.",
  "",
  "**Mizraim** — The Hebrew name for Egypt. His descendants became the Egyptians.",
  "",
  "**Put** — Connected with peoples living west of Egypt, likely in Libya and North Africa.",
  "",
  "**Canaan** — Ancestor of the Canaanites, who settled in the land later known as Canaan, the Promised Land. Noah had previously spoken a prophecy concerning Canaan (Genesis 9). Later, Abraham instructed his servant not to choose a Canaanite wife for Isaac because the Canaanites became known for their wickedness and idol worship.",
  "",
  "👨‍👩‍👦 Ham was one of Noah’s sons",
  "",
  "🌍 His descendants settled throughout Africa and Canaan",
  "",
  "📖 Many important biblical nations came from Ham",
  "",
  "➡️ Canaan becomes especially important later in Genesis",
  "",
  "**👨‍👦 The Sons Of Cush**",
  "",
  "**Cush**, one of Ham’s sons and Noah’s grandson, had five sons:",
  "",
  "**Seba** — Connected with people in the upper Nile region.",
  "",
  "**Havilah** — Likely settled in parts of Arabia or northeast Africa.",
  "",
  "**Sabtah** — Connected with southern Arabia.",
  "",
  "**Raamah** — Ancestor of trading peoples in Arabia.",
  "",
  "**Sabtechah** — Also connected with southern Arabia.",
  "",
  "Moses is continuing the family tree, showing how Cush’s descendants spread into different regions.",
  "",
  "👨‍👦 Cush was Ham’s son and Noah’s grandson",
  "",
  "🌍 His descendants spread through Arabia and northeast Africa",
  "",
  "📖 More nations begin forming",
  "",
  "➡️ The family tree continues",
  "",
  "**👨‍👦 The Sons Of Raamah**",
  "",
  "**Raamah**, one of Cush’s sons and Noah’s great grandson, had two sons:",
  "",
  "**Sheba** — Known later for the rich kingdom of Sheba. The Queen of Sheba would eventually visit King Solomon.",
  "",
  "**Dedan** — Became a well known trading people in Arabia and is mentioned several times by the prophets.",
  "",
  "Although these men are only briefly mentioned here, their descendants become important later in the Old Testament.",
  "",
  "👨‍👦 Raamah was Cush’s son and Noah’s great grandson",
  "",
  "👑 Sheba became a famous kingdom",
  "",
  "🐪 Dedan became known for trade",
  "",
  "📖 Their descendants appear later in Scripture",
  "",
  "**👑 Cush Begat Nimrod**",
  "",
  "Unlike the other names in this chapter, Moses pauses to tell us more about **Nimrod**, another son of Cush and Noah’s grandson.",
  "",
  "That tells us Nimrod became an especially important person.",
  "",
  "The name **Nimrod** did **not** originally mean “stupid.”",
  "",
  "The modern insult came much later and is not what the Bible means.",
  "",
  "Nimrod became one of the first great rulers after the flood.",
  "",
  "👑 Moses pauses to focus on Nimrod",
  "",
  "📖 He becomes an important figure",
  "",
  "🌍 One of the first great rulers",
  "",
  "➡️ His story continues",
  "",
  "**💪 He Began To Be A Mighty One In The Earth**",
  "",
  "A **mighty one** means a powerful man.",
  "",
  "Nimrod became known for his strength, influence, leadership, and growing kingdom.",
  "",
  "This does not necessarily mean he was a godly man.",
  "",
  "It simply means he became one of the most powerful people of his day.",
  "",
  "💪 Mighty means powerful",
  "",
  "👑 Nimrod became a great ruler",
  "",
  "🌍 His influence spread widely",
  "",
  "📖 Power does not always mean godliness",
  "",
  "**🏹 He Was A Mighty Hunter Before The Lord**",
  "",
  "Nimrod became famous as a hunter.",
  "",
  "The phrase **“before the Lord”** means God saw everything Nimrod accomplished.",
  "",
  "Some people understand this as praise for his skill.",
  "",
  "Others believe it means Nimrod became powerful in defiance of God, especially since Babel is introduced next.",
  "",
  "The Bible doesn’t fully explain the phrase here, so both views are discussed.",
  "",
  "🏹 Nimrod became famous as a hunter",
  "",
  "👀 God saw everything he did",
  "",
  "📖 Different interpretations exist",
  "",
  "➡️ His growing kingdom becomes the focus",
  "",
  "**🗣️ Even As Nimrod The Mighty Hunter Before The Lord**",
  "",
  "This became a well known saying in the ancient world.",
  "",
  "People used Nimrod’s name as a comparison for someone who was an exceptionally powerful hunter or ruler.",
  "",
  "His reputation became widely known.",
  "",
  "🗣️ Nimrod became famous",
  "",
  "🏹 His name became a comparison",
  "",
  "📖 His reputation spread",
  "",
  "➡️ He became well known",
  "",
  "**🏙️ The Beginning Of His Kingdom Was Babel**",
  "",
  "This is the first time the Bible mentions **Babel**.",
  "",
  "Babel became the center of Nimrod’s kingdom.",
  "",
  "In the very next chapter, Babel becomes the location of the Tower of Babel, where mankind united in pride against God.",
  "",
  "🏙️ Babel becomes Nimrod’s capital",
  "",
  "👑 His kingdom begins here",
  "",
  "📖 Babel becomes important in Genesis 11",
  "",
  "➡️ The story is setting up the Tower of Babel",
  "",
  "**🏛️ Erech, Accad, And Calneh, In The Land Of Shinar**",
  "",
  "These were cities ruled by Nimrod.",
  "",
  "**Shinar** is the region later known as Babylon in southern Mesopotamia (modern day Iraq).",
  "",
  "Instead of ruling only one city, Nimrod was building one of the world’s first kingdoms made up of multiple cities.",
  "",
  "🏛️ These were cities in Nimrod’s kingdom",
  "",
  "🌍 Shinar became ancient Babylon",
  "",
  "👑 Nimrod ruled multiple cities",
  "",
  "📖 One of the first kingdoms begins",
  "",
  "**🏗️ Out Of That Land Went Forth Asshur**",
  "",
  "There are two common understandings of this verse.",
  "",
  "Some believe **Asshur**, a descendant of Shem, left Shinar and established his own cities.",
  "",
  "Others believe the verse is still talking about Nimrod, saying **he** expanded into the land of Asshur.",
  "",
  "Most modern translations understand the verse to mean that Nimrod expanded his kingdom into Assyria.",
  "",
  "The Hebrew can be understood either way.",
  "",
  "🏗️ Two interpretations exist",
  "",
  "🌍 Asshur became the land of Assyria",
  "",
  "📖 The Hebrew allows both readings",
  "",
  "➡️ Either way, new cities were established",
  "",
  "**🏙️ And Builded Nineveh, And The City Rehoboth, And Calah**",
  "",
  "These became major cities in the region of Assyria.",
  "",
  "**Nineveh** later became the capital of the Assyrian Empire and is the city where God sent Jonah to preach many centuries later.",
  "",
  "Even though these cities seem unimportant now, they become major locations throughout the rest of the Bible.",
  "",
  "🏙️ New cities are established",
  "",
  "📖 Nineveh becomes important later",
  "",
  "🌍 Assyria grows into a great empire",
  "",
  "➡️ These cities return throughout Scripture",
  "",
  "# **🌍 Genesis 10:12–20**",
  "",
  "**The Sons of Ham Continued**",
  "",
  "**🏙️ Resen, Between Nineveh And Calah**",
  "",
  "Resen was another city built in the region of Assyria.",
  "",
  "Moses says it was located **between Nineveh and Calah**, showing it was part of this growing civilization.",
  "",
  "The phrase **“the same is a great city”** means Resen, or possibly the group of cities together, was known as an important and influential city in the ancient world.",
  "",
  "🏙️ Resen was an important city",
  "",
  "📍 Located between Nineveh and Calah",
  "",
  "📖 Assyria continued growing",
  "",
  "➡️ Great cities were beginning to form",
  "",
  "**👨‍👦 The Sons Of Mizraim**",
  "",
  "**Mizraim**, Ham’s son and Noah’s grandson, became the ancestor of Egypt.",
  "",
  "His descendants included:",
  "",
  "**Ludim**",
  "",
  "**Anamim**",
  "",
  "**Lehabim**",
  "",
  "**Naphtuhim**",
  "",
  "**Pathrusim**",
  "",
  "**Casluhim** — From this family came the **Philistines**, one of Israel’s greatest enemies throughout the Old Testament.",
  "",
  "**Caphtorim** — Connected with the island of Caphtor, which many scholars identify with Crete. The Philistines are later said to have come from this region.",
  "",
  "Most of these names represent early people groups that settled in and around Egypt.",
  "",
  "👨‍👦 Mizraim became the father of many nations",
  "",
  "🇪🇬 His descendants settled around Egypt",
  "",
  "⚔️ The Philistines came from this family line",
  "",
  "📖 Many important nations came through Mizraim",
  "",
  "**🌍 Canaan Begat**",
  "",
  "**Canaan**, Ham’s son and Noah’s grandson, became the father of many tribes that settled in the land of Canaan.",
  "",
  "His descendants included:",
  "",
  "**Sidon** — Founder of the famous city of Sidon.",
  "",
  "**Heth** — Ancestor of the Hittites.",
  "",
  "**Jebusites**",
  "",
  "**Amorites**",
  "",
  "**Girgashites**",
  "",
  "**Hivites**",
  "",
  "**Arkites**",
  "",
  "**Sinites**",
  "",
  "**Arvadites**",
  "",
  "**Zemarites**",
  "",
  "**Hamathites**",
  "",
  "These were not just individual people.",
  "",
  "As Canaan’s family grew, each branch became its own tribe or nation.",
  "",
  "Think of it like Jacob later having twelve sons.",
  "",
  "Those sons became the twelve tribes of Israel.",
  "",
  "In the same way, Canaan’s descendants became many different Canaanite tribes.",
  "",
  "Throughout the rest of the Old Testament, you’ll read about the Amorites, Hittites, Jebusites, Hivites, and other Canaanite peoples.",
  "",
  "They’re all descendants of one man: **Canaan.**",
  "",
  "🌍 Canaan became the father of many tribes",
  "",
  "🏡 Each family grew into its own nation",
  "",
  "📖 These became the Canaanite peoples",
  "",
  "➡️ Israel later encountered these tribes in the Promised Land",
  "",
  "**🏘️ Afterwards Were The Families Of The Canaanites Spread Abroad**",
  "",
  "As Canaan’s descendants multiplied, they spread throughout the land of Canaan.",
  "",
  "Moses is summarizing what happened to the families he just listed.",
  "",
  "Over time, they became established tribes and nations throughout the region.",
  "",
  "🏘️ The Canaanites spread across the land",
  "",
  "🌍 Families became tribes and nations",
  "",
  "📖 The land filled with Canaanite peoples",
  "",
  "➡️ Canaan’s descendants continued multiplying",
  "",
  "**🗺️ The Border Of The Canaanites Was From Sidon**",
  "",
  "Moses now describes the borders of the land where the Canaanites settled.",
  "",
  "**Sidon** was a major city north of Israel, near the Mediterranean Sea.",
  "",
  "This shows the northern side of the Canaanite territory.",
  "",
  "The land of Canaan was not just one small village.",
  "",
  "It was a large region filled with different cities, tribes, and people groups.",
  "",
  "🗺️ Moses describes Canaan’s borders",
  "",
  "📍 Sidon marks the northern area",
  "",
  "🌊 Sidon was near the Mediterranean coast",
  "",
  "📖 Canaan was a large region",
  "",
  "**📍 As Thou Comest To Gerar, Unto Gaza**",
  "",
  "**Gerar** was a city in the southern part of Canaan.",
  "",
  "**Gaza** was an important city near the coast.",
  "",
  "This shows the border moving southward from Sidon toward the coastal and southern areas of Canaan.",
  "",
  "Gaza later becomes an important Philistine city in the Old Testament.",
  "",
  "📍 Gerar was in southern Canaan",
  "",
  "🌊 Gaza was a coastal city",
  "",
  "🗺️ The border moves south",
  "",
  "📖 Gaza becomes important later",
  "",
  "**🔥 As Thou Goest Unto Sodom And Gomorrah**",
  "",
  "This is the first time the Bible mentions **Sodom and Gomorrah**.",
  "",
  "At this point, Moses only names them as part of Canaan’s border region.",
  "",
  "Later in Genesis, these cities become famous for their wickedness and God’s judgment.",
  "",
  "Abraham will plead with God for these cities, and Lot will be rescued before their destruction.",
  "",
  "🔥 Sodom and Gomorrah appear for the first time",
  "",
  "📖 Their story comes later in Genesis",
  "",
  "⚖️ They become known for judgment",
  "",
  "➡️ Moses is introducing important places early",
  "",
  "**🏙️ Admah And Zeboim, Even Unto Lasha**",
  "",
  "**Admah** and **Zeboim** were cities connected with the same region as Sodom and Gomorrah.",
  "",
  "They are later mentioned together with Sodom and Gomorrah as cities involved in judgment.",
  "",
  "**Lasha** likely marked another point on the border, though its exact location is uncertain.",
  "",
  "Moses is giving a boundary line so the reader understands where the Canaanites lived.",
  "",
  "🏙️ Admah and Zeboim were nearby cities",
  "",
  "🔥 They are connected with Sodom and Gomorrah",
  "",
  "📍 Lasha marked part of the border",
  "",
  "🗺️ Moses is mapping Canaanite territory",
  "",
  "**🌍 These Are The Sons Of Ham**",
  "",
  "Moses finishes Ham’s genealogy the same way he finished Japheth’s.",
  "",
  "Ham’s descendants became many different families.",
  "",
  "Those families developed different languages, settled in different lands, and eventually became separate nations.",
  "",
  "The next section will move to Noah’s final son, **Shem**, whose family line eventually leads to Abraham, Isaac, Jacob, the nation of Israel, and ultimately Jesus Christ.",
  "",
  "🌍 Ham’s descendants became many nations",
  "",
  "🗣️ They developed different languages",
  "",
  "🏡 They settled in different lands",
  "",
  "➡️ The story now prepares to follow Shem’s family line",
  "",
  "**👨‍👩‍👧 After Their Families**",
  "",
  "This means Ham’s descendants were grouped by family lines.",
  "",
  "Each branch came from a father, grandfather, or ancestor already listed in the genealogy.",
  "",
  "Moses is showing that these were not random nations.",
  "",
  "They came from connected family groups.",
  "",
  "👨‍👩‍👧 Families means family lines",
  "",
  "🌳 Each group came from an ancestor",
  "",
  "📖 The nations are connected by bloodline",
  "",
  "➡️ Ham’s family kept spreading",
  "",
  "**🗣️ After Their Tongues**",
  "",
  "**Tongues** means languages.",
  "",
  "By the time these families became nations, they had different languages.",
  "",
  "Genesis 11 will explain how the languages were divided at the Tower of Babel.",
  "",
  "Here, Moses is summarizing the result before telling that story.",
  "",
  "🗣️ Tongues means languages",
  "",
  "🌍 Different groups spoke different languages",
  "",
  "📖 Genesis 11 explains how this happened",
  "",
  "➡️ The nations became separated by speech",
  "",
  "**🏡 In Their Countries And In Their Nations**",
  "",
  "**Countries** means the lands or territories where these families settled.",
  "",
  "**Nations** means the larger people groups that formed from those families.",
  "",
  "So Genesis 10 is showing the full development:",
  "",
  "families became tribes…",
  "",
  "tribes settled in lands…",
  "",
  "and those people groups became nations.",
  "",
  "🏡 Countries means lands or territories",
  "",
  "🌍 Nations means people groups",
  "",
  "📖 Families grew into nations",
  "",
  "➡️ Ham’s descendants spread across the earth",
  "",
  "# **🌍 Genesis 10:21–32**",
  "",
  "**The Sons of Shem**",
  "",
  "**👨 Unto Shem Also, The Father Of All The Children Of Eber**",
  "",
  "Moses now turns to **Shem**, Noah’s third son.",
  "",
  "Shem’s family is given special attention because this is the family line that eventually leads to **Abraham, Isaac, Jacob (Israel), King David, and ultimately Jesus Christ**.",
  "",
  "The phrase **“the father of all the children of Eber”** points to Eber, one of Shem’s descendants.",
  "",
  "Many scholars believe the word **Hebrew** comes from the name **Eber**.",
  "",
  "Although Israel does not exist yet, this is the family line God will later choose to bring His covenant people into the world.",
  "",
  "👨 Shem was one of Noah’s three sons",
  "",
  "📖 His family line leads to Abraham and Israel",
  "",
  "✝️ Jesus eventually comes through this family",
  "",
  "➡️ Moses begins tracing God’s chosen line",
  "",
  "**👬 The Brother Of Japheth The Elder**",
  "",
  "This simply reminds the reader how Shem fits into Noah’s family.",
  "",
  "Some translations understand this phrase to mean Japheth was the older brother.",
  "",
  "Others understand it to mean Shem himself was the elder.",
  "",
  "The main point is simply identifying Shem within Noah’s family.",
  "",
  "👬 Shem and Japheth were brothers",
  "",
  "👨‍👦 Moses identifies Noah’s family",
  "",
  "📖 Different translations word this differently",
  "",
  "➡️ The genealogy continues",
  "",
  "**👶 Even To Him Were Children Born**",
  "",
  "Like Japheth and Ham, Shem also had children after the flood.",
  "",
  "Moses is preparing to trace the family line that eventually leads to Abraham.",
  "",
  "This does not mean these were Shem’s only children.",
  "",
  "It simply introduces the descendants that are important to the biblical story.",
  "",
  "👶 Shem had children after the flood",
  "",
  "📖 Moses follows the important family line",
  "",
  "🌳 The genealogy continues",
  "",
  "➡️ God’s plan moves through Shem",
  "",
  "**👨‍👦 The Children Of Shem**",
  "",
  "Shem had five sons:",
  "",
  "**Elam** — Ancestor of the Elamites, who settled east of Babylon.",
  "",
  "**Asshur** — Ancestor of the Assyrians, one of the greatest empires in the Old Testament.",
  "",
  "**Arphaxad** — Most important in Genesis because Abraham eventually comes through this family line.",
  "",
  "**Lud** — Connected with people in western Asia Minor.",
  "",
  "**Aram** — Ancestor of the Arameans (Syrians), who appear often throughout the Old Testament.",
  "",
  "👨‍👦 Shem had five sons",
  "",
  "🌍 His descendants formed major nations",
  "",
  "📖 Abraham comes through Arphaxad",
  "",
  "➡️ God’s chosen family line continues",
  "",
  "**👨‍👦 The Children Of Aram**",
  "",
  "**Aram**, Shem’s son and Noah’s grandson, had four sons:",
  "",
  "**Uz** — Later associated with the land where Job lived.",
  "",
  "**Hul**",
  "",
  "**Gether**",
  "",
  "**Mash**",
  "",
  "The Bible gives little information about the last three, but Moses records them because they became the ancestors of later families and nations.",
  "",
  "👨‍👦 Aram had four sons",
  "",
  "📍 Uz later becomes associated with Job",
  "",
  "🌍 More families and nations develop",
  "",
  "➡️ The family tree keeps growing",
  "",
  "**🌳 Arphaxad Begat Salah**",
  "",
  "Moses now follows **Arphaxad’s** family instead of his brothers.",
  "",
  "This is the branch that eventually leads to Abraham.",
  "",
  "Whenever Moses pauses to continue one family instead of another, it usually means that family will become especially important later.",
  "",
  "🌳 Moses follows Arphaxad’s family",
  "",
  "📖 This becomes Abraham’s family line",
  "",
  "👨‍👩‍👦 One branch becomes the focus",
  "",
  "➡️ God’s plan continues through this family",
  "",
  "**🌳 Salah Begat Eber**",
  "",
  "Eber becomes one of the most important names in Shem’s genealogy.",
  "",
  "Many scholars believe the word **Hebrew** comes from Eber’s name.",
  "",
  "Although Abraham has not been born yet, Moses is bringing us closer to the family through whom God will later make His covenant.",
  "",
  "🌳 Eber is an important ancestor",
  "",
  "📖 The name Hebrew likely comes from Eber",
  "",
  "👨‍👩‍👦 Abraham’s family line continues",
  "",
  "➡️ The story is moving toward Genesis 12",
  "",
  "**👶 Unto Eber Were Born Two Sons**",
  "",
  "The genealogy now moves another generation forward.",
  "",
  "Noah → Shem → Arphaxad → Salah → Eber.",
  "",
  "Eber had two sons, and Moses briefly explains both before continuing through one family line.",
  "",
  "👶 Another generation is introduced",
  "",
  "🌳 The family tree continues",
  "",
  "📖 Moses moves one step closer to Abraham",
  "",
  "➡️ The genealogy keeps narrowing",
  "",
  "**🌍 The Name Of One Was Peleg; For In His Days Was The Earth Divided**",
  "",
  "**Peleg** means **division**.",
  "",
  "The phrase **“the earth was divided”** has two common interpretations.",
  "",
  "Many believe it refers to the **Tower of Babel**, when God divided mankind by confusing their languages and scattering them across the earth.",
  "",
  "Others believe it refers to the nations becoming divided into different lands after Babel.",
  "",
  "Either way, Peleg lived during a time when humanity became separated into different nations and languages.",
  "",
  "🌍 Peleg means division",
  "",
  "🗣️ Many connect this to the Tower of Babel",
  "",
  "🗺️ Nations spread across the earth",
  "",
  "➡️ Humanity became divided",
  "",
  "**👨 His Brother’s Name Was Joktan**",
  "",
  "Although Moses briefly mentions Joktan here, he immediately lists his descendants before returning to the family line that leads to Abraham.",
  "",
  "Joktan becomes the father of many families, but God’s covenant line will continue through Peleg instead.",
  "",
  "👨 Joktan was Peleg’s brother",
  "",
  "🌳 His family also became many nations",
  "",
  "📖 Moses lists his descendants first",
  "",
  "➡️ The covenant line continues through Peleg later",
  "",
  "# ",
  "",
  "**The Sons of Shem (Continued)**",
  "",
  "**👨‍👦 Joktan Begat**",
  "",
  "**Joktan**, the son of Eber and brother of Peleg, had thirteen sons:",
  "",
  "**Almodad**",
  "",
  "**Sheleph**",
  "",
  "**Hazarmaveth**",
  "",
  "**Jerah**",
  "",
  "**Hadoram**",
  "",
  "**Uzal**",
  "",
  "**Diklah**",
  "",
  "**Obal**",
  "",
  "**Abimael**",
  "",
  "**Sheba**",
  "",
  "**Ophir** — Later known for its great wealth and fine gold, especially during King Solomon’s reign.",
  "",
  "**Havilah** — Connected with regions in Arabia. This is likely a different Havilah than the one mentioned earlier in Genesis.",
  "",
  "**Jobab**",
  "",
  "The Bible gives very little information about most of these men because Moses’ purpose is simply to show how the nations spread after the flood.",
  "",
  "👨‍👦 Joktan had thirteen sons",
  "",
  "🌍 His family became many nations",
  "",
  "📖 Most are listed only in this genealogy",
  "",
  "➡️ Moses continues tracing the spread of mankind",
  "",
  "**🏡 Their Dwelling Was From Mesha**",
  "",
  "The word **dwelling** means where they settled or lived.",
  "",
  "Moses now describes the region where Joktan’s descendants established their homes.",
  "",
  "Unlike earlier genealogies that focused on people, Moses now points to the land they occupied.",
  "",
  "🏡 Dwelling means where they settled",
  "",
  "📍 Moses begins describing their territory",
  "",
  "🌍 Families spread into different lands",
  "",
  "➡️ Nations continued growing",
  "",
  "**🏔️ As Thou Goest Unto Sephar, A Mount Of The East**",
  "",
  "**Sephar** was a place located in the eastern regions, though its exact location is uncertain today.",
  "",
  "The phrase **“a mount of the east”** tells us Joktan’s descendants settled in the mountainous areas of the East, probably in parts of southern Arabia.",
  "",
  "Moses is marking the boundaries of where this family eventually lived.",
  "",
  "🏔️ Sephar was in the eastern region",
  "",
  "📍 Their territory extended into the mountains",
  "",
  "🌍 Moses marks their borders",
  "",
  "➡️ Another nation finds its home",
  "",
  "**🌳 These Are The Sons Of Shem**",
  "",
  "Moses finishes Shem’s genealogy just as he finished Japheth’s and Ham’s.",
  "",
  "Shem’s descendants became many different families, tribes, and nations.",
  "",
  "Unlike the other two genealogies, however, Shem’s family receives special attention because this is the line that will eventually lead to Abraham.",
  "",
  "🌳 Shem’s family became many nations",
  "",
  "📖 His line leads to Abraham",
  "",
  "✝️ God’s plan continues through Shem",
  "",
  "➡️ The story prepares for Genesis 11",
  "",
  "**👨‍👩‍👧 After Their Families**",
  "",
  "The descendants of Shem remained connected through family lines.",
  "",
  "Each nation began with a family that continued growing over many generations.",
  "",
  "Moses reminds us that every nation started with real people and real families.",
  "",
  "👨‍👩‍👧 Families became larger",
  "",
  "🌳 Nations began with one family",
  "",
  "📖 The genealogy remains connected",
  "",
  "➡️ The family tree continues",
  "",
  "**🗣️ After Their Tongues**",
  "",
  "**Tongues** means languages.",
  "",
  "By the time these families became nations, each had developed its own language.",
  "",
  "Genesis 11 will immediately explain how those different languages came into existence at the Tower of Babel.",
  "",
  "🗣️ Tongues means languages",
  "",
  "🌍 Different peoples spoke different languages",
  "",
  "📖 Babel explains how this happened",
  "",
  "➡️ Moses is preparing the next chapter",
  "",
  "**🏡 In Their Lands, After Their Nations**",
  "",
  "As Shem’s descendants multiplied, they settled in different regions.",
  "",
  "Those settlements became tribes, kingdoms, and eventually nations.",
  "",
  "This pattern has now been shown for all three of Noah’s sons.",
  "",
  "🏡 Families settled in different lands",
  "",
  "🌍 Tribes became nations",
  "",
  "📖 The world continued spreading",
  "",
  "➡️ Humanity filled the earth",
  "",
  "**🌍 These Are The Families Of The Sons Of Noah**",
  "",
  "Moses now concludes the entire chapter.",
  "",
  "Everything from Genesis 10 has been answering one question:",
  "",
  "**How did the world become populated again after the flood?**",
  "",
  "The answer is through the descendants of Noah’s three sons: **Shem, Ham, and Japheth.**",
  "",
  "Every nation listed in this chapter traces its beginning back to one of those three family lines.",
  "",
  "🌍 The genealogy is complete",
  "",
  "👨 Noah’s three sons became the ancestors of the nations",
  "",
  "📖 Genesis explains where the nations came from",
  "",
  "➡️ The story now moves to Babel",
  "",
  "**🌎 By These Were The Nations Divided In The Earth After The Flood**",
  "",
  "This verse summarizes the entire chapter.",
  "",
  "After the flood, Noah’s family obeyed God’s command to **be fruitful and multiply**.",
  "",
  "Their children had children…",
  "",
  "Families became tribes…",
  "",
  "Tribes became nations…",
  "",
  "Nations spread across the earth.",
  "",
  "Genesis 10 serves as the bridge between the Flood and the Tower of Babel.",
  "",
  "Chapter 10 tells us **where the nations ended up.**",
  "",
  "Genesis 11 will explain **how they became separated into different languages and scattered across the earth.**",
  "",
  "🌎 Noah’s descendants repopulated the earth",
  "",
  "👨‍👩‍👧 Families became tribes",
  "",
  "🌍 Tribes became nations",
  "",
  "📖 Genesis 11 explains how the nations were divided"
].join("\n");

export const GENESIS_TEN_PERSONAL_SECTIONS: GenesisTenPersonalSection[] = parseGenesisTenRawNotes(
  GENESIS_TEN_RAW_NOTES,
);
