export type PersonalGenesisPhraseSectionInput = {
  chapter: number;
  startVerse: number;
  endVerse: number;
  reference: string;
  title: string;
  icon: string;
  phrases: Array<[string, string]>;
};

const note = (lines: string[]) => lines.join("\n\n");

type PersonalSectionSplit = {
  startVerse: number;
  endVerse: number;
  reference: string;
  title: string;
  phraseIndexes: number[];
};

const SECTION_SPLITS: Record<string, PersonalSectionSplit[]> = {
  "Genesis 11:10-26": [
    { startVerse: 10, endVerse: 17, reference: "Genesis 11:10-17", title: "Shem's Line Continues", phraseIndexes: [0, 1] },
    { startVerse: 18, endVerse: 26, reference: "Genesis 11:18-26", title: "The Line Reaches Abram", phraseIndexes: [1, 2] },
  ],
  "Genesis 12:10-20": [
    { startVerse: 10, endVerse: 13, reference: "Genesis 12:10-13", title: "Abram Acts Out Of Fear", phraseIndexes: [0, 1] },
    { startVerse: 14, endVerse: 20, reference: "Genesis 12:14-20", title: "God Protects Sarai In Egypt", phraseIndexes: [2] },
  ],
  "Genesis 13:8-18": [
    { startVerse: 8, endVerse: 13, reference: "Genesis 13:8-13", title: "Lot Chooses The Plain", phraseIndexes: [0, 1] },
    { startVerse: 14, endVerse: 18, reference: "Genesis 13:14-18", title: "God Repeats The Land Promise", phraseIndexes: [2] },
  ],
  "Genesis 14:1-12": [
    { startVerse: 1, endVerse: 9, reference: "Genesis 14:1-9", title: "Kings Go To War", phraseIndexes: [0] },
    { startVerse: 10, endVerse: 12, reference: "Genesis 14:10-12", title: "Lot Is Taken Captive", phraseIndexes: [1, 2] },
  ],
  "Genesis 14:13-24": [
    { startVerse: 13, endVerse: 16, reference: "Genesis 14:13-16", title: "Abram Rescues Lot", phraseIndexes: [0] },
    { startVerse: 17, endVerse: 24, reference: "Genesis 14:17-24", title: "Melchizedek Blesses Abram", phraseIndexes: [1, 2] },
  ],
  "Genesis 15:7-21": [
    { startVerse: 7, endVerse: 11, reference: "Genesis 15:7-11", title: "Abram Asks For Assurance", phraseIndexes: [0] },
    { startVerse: 12, endVerse: 21, reference: "Genesis 15:12-21", title: "God Cuts The Covenant", phraseIndexes: [1, 2] },
  ],
  "Genesis 17:15-27": [
    { startVerse: 15, endVerse: 22, reference: "Genesis 17:15-22", title: "Sarah And Isaac Are Promised", phraseIndexes: [0, 1, 2] },
    { startVerse: 23, endVerse: 27, reference: "Genesis 17:23-27", title: "Abraham Obeys The Covenant Sign", phraseIndexes: [2] },
  ],
  "Genesis 18:1-15": [
    { startVerse: 1, endVerse: 8, reference: "Genesis 18:1-8", title: "Abraham Welcomes The Visitors", phraseIndexes: [0] },
    { startVerse: 9, endVerse: 15, reference: "Genesis 18:9-15", title: "Sarah Laughs At The Promise", phraseIndexes: [1, 2] },
  ],
  "Genesis 18:16-33": [
    { startVerse: 16, endVerse: 22, reference: "Genesis 18:16-22", title: "The Lord Reveals Sodom's Judgment", phraseIndexes: [0] },
    { startVerse: 23, endVerse: 28, reference: "Genesis 18:23-28", title: "Abraham Begins Pleading For Sodom", phraseIndexes: [0, 1] },
    { startVerse: 29, endVerse: 33, reference: "Genesis 18:29-33", title: "Abraham Pleads Down To Ten", phraseIndexes: [2] },
  ],
  "Genesis 19:1-11": [
    { startVerse: 1, endVerse: 3, reference: "Genesis 19:1-3", title: "Lot Welcomes The Angels", phraseIndexes: [0] },
    { startVerse: 4, endVerse: 11, reference: "Genesis 19:4-11", title: "Sodom Shows Its Wickedness", phraseIndexes: [1, 2] },
  ],
  "Genesis 19:12-22": [
    { startVerse: 12, endVerse: 16, reference: "Genesis 19:12-16", title: "Lot Lingers As Judgment Comes", phraseIndexes: [1, 2] },
    { startVerse: 17, endVerse: 22, reference: "Genesis 19:17-22", title: "Lot Is Told To Escape", phraseIndexes: [0] },
  ],
  "Genesis 19:23-38": [
    { startVerse: 23, endVerse: 29, reference: "Genesis 19:23-29", title: "Sodom Falls", phraseIndexes: [0, 1] },
    { startVerse: 30, endVerse: 38, reference: "Genesis 19:30-38", title: "Lot's Family Breaks", phraseIndexes: [2] },
  ],
  "Genesis 20:8-18": [
    { startVerse: 8, endVerse: 13, reference: "Genesis 20:8-13", title: "Abimelech Confronts Abraham", phraseIndexes: [0, 1] },
    { startVerse: 14, endVerse: 18, reference: "Genesis 20:14-18", title: "Sarah Is Restored", phraseIndexes: [2] },
  ],
};

function expandSplitSections(sections: PersonalGenesisPhraseSectionInput[]) {
  return sections.flatMap((section) => {
    const splits = SECTION_SPLITS[section.reference];
    if (!splits) {
      return [section];
    }

    return splits.map((split) => ({
      ...section,
      startVerse: split.startVerse,
      endVerse: split.endVerse,
      reference: split.reference,
      title: split.title,
      phrases: split.phraseIndexes.map((index) => section.phrases[index]).filter(Boolean),
    }));
  });
}

const RAW_GENESIS_11_20_PERSONAL_SECTIONS: PersonalGenesisPhraseSectionInput[] = [
  {
    chapter: 11,
    startVerse: 1,
    endVerse: 4,
    reference: "Genesis 11:1-4",
    title: "The Tower Of Babel Begins",
    icon: "🏙️",
    phrases: [
      [
        "🗣️ The Whole Earth Was Of One Language",
        note([
          "Before Babel, humanity is described as having one language and one speech.",
          "That means people could communicate easily and work together quickly.",
          "Unity itself was not the problem.",
          "The problem was what they decided to do with that unity.",
          "Instead of spreading over the earth as God had commanded, they gathered around their own project.",
          "Genesis is showing that people can be united and still be moving in the wrong direction.",
        ]),
      ],
      [
        "🧱 Let Us Make Brick",
        note([
          "The builders make bricks because they are settling in a flat land without natural stone for building.",
          "This detail shows human skill and planning.",
          "They know how to organize materials, labor, and a city project.",
          "The Bible is not saying technology is evil.",
          "It is showing that human ability becomes dangerous when it is used for pride and independence from God.",
          "The bricks become part of a project built around human greatness.",
        ]),
      ],
      [
        "🏷️ Let Us Make Us A Name",
        note([
          "This is the heart of Babel.",
          "The people want a name for themselves.",
          "In plain terms, they want identity, security, and greatness without receiving it from God.",
          "That matters because Genesis 12 will immediately show God promising to make Abram's name great.",
          "Babel grasps for a name; Abram receives one from God.",
          "Genesis is teaching that lasting significance is not seized by pride, but given by God.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 5,
    endVerse: 9,
    reference: "Genesis 11:5-9",
    title: "God Scatters Babel",
    icon: "🔀",
    phrases: [
      [
        "⬇️ The Lord Came Down",
        note([
          "The people build a tower they think reaches toward heaven, but Genesis says God came down to see it.",
          "That line has a little irony in it.",
          "The tower looked huge to people, but it was not impressive from God's view.",
          "Human pride often feels massive to us and small before God.",
          "The Lord is not threatened by Babel.",
          "He comes down as the true authority over human plans.",
        ]),
      ],
      [
        "🗣️ Confound Their Language",
        note([
          "God confuses their language so they cannot keep building together.",
          "This judgment directly touches the thing that made their project possible: shared speech.",
          "The confusion stops their pride from growing into something worse.",
          "God is not being random.",
          "He is breaking the unity they were using for rebellion.",
          "The scattered languages explain why the nations of Genesis 10 are divided by tongues.",
        ]),
      ],
      [
        "🏙️ Babel",
        note([
          "Babel is connected with confusion.",
          "The name becomes a memory of human pride and God's scattering.",
          "Later in the Bible, Babylon grows from this same idea into a symbol of human empire against God.",
          "That makes Babel more than an old building story.",
          "It becomes a pattern.",
          "Whenever people build their lives around their own name instead of God's glory, Babel is still alive in the human heart.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 10,
    endVerse: 26,
    reference: "Genesis 11:10-26",
    title: "The Story Narrows Toward Abram",
    icon: "📜",
    phrases: [
      [
        "📜 These Are The Generations Of Shem",
        note([
          "Genesis now narrows from all the nations back to Shem's family line.",
          "This matters because Abram will come from this line.",
          "After Babel scatters humanity, God begins preparing one family through whom blessing will come.",
          "The genealogy may look slow, but it is moving the story toward the call of Abram.",
          "God's plan does not appear out of nowhere in Genesis 12.",
          "It is being carried quietly through generations.",
        ]),
      ],
      [
        "👶 Begat Sons And Daughters",
        note([
          "This repeated phrase reminds us that the promise story moves through ordinary family life.",
          "Most of these people do not get dramatic stories.",
          "They live, have children, and pass the line forward.",
          "That may feel small, but it matters deeply.",
          "God often works through generations that look ordinary from the outside.",
          "The future of Abram is being preserved through names many readers skip.",
        ]),
      ],
      [
        "👨‍👦 Terah Begat Abram",
        note([
          "Abram is introduced before God speaks to him in Genesis 12.",
          "He is part of a real family with a father, brothers, a wife, and a homeland.",
          "That matters because God's call will ask him to leave much of that behind.",
          "Abram does not float into the story as a religious idea.",
          "He comes from a household with history, grief, and attachments.",
          "Genesis 11 gives us the ground under Abram's obedience.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 27,
    endVerse: 32,
    reference: "Genesis 11:27-32",
    title: "Abram's Family Stops In Haran",
    icon: "🧳",
    phrases: [
      [
        "💔 Haran Died Before His Father",
        note([
          "Abram's brother Haran dies before Terah.",
          "This detail matters because Lot is Haran's son.",
          "When Abram later travels with Lot, he is traveling with a nephew who has already lost his father.",
          "Genesis is quietly giving emotional background.",
          "Abram's family story includes grief before it includes calling.",
          "God's call often comes into families that already carry wounds.",
        ]),
      ],
      [
        "🚫 Sarai Was Barren",
        note([
          "Sarai's barrenness is one of the most important details in Abram's story.",
          "God will promise Abram descendants, but his wife cannot have children.",
          "That means the promise begins in an impossible situation.",
          "Genesis wants the reader to feel the tension early.",
          "The family line God chooses cannot continue by human strength alone.",
          "From the start, Abram's future will depend on God's power.",
        ]),
      ],
      [
        "⏸️ They Came Unto Haran, And Dwelt There",
        note([
          "Terah's family begins moving toward Canaan but stops in Haran.",
          "That unfinished journey matters because Genesis 12 will begin with God calling Abram to keep going.",
          "The story pauses in an in-between place.",
          "They have left Ur, but they have not reached Canaan.",
          "Abram's call will meet him in the middle of an unfinished road.",
          "Sometimes God's next word comes where a family journey has stalled.",
        ]),
      ],
    ],
  },
  {
    chapter: 12,
    startVerse: 1,
    endVerse: 9,
    reference: "Genesis 12:1-9",
    title: "God Calls Abram",
    icon: "🚶",
    phrases: [
      [
        "🚶 Get Thee Out",
        note([
          "God calls Abram to leave country, family, and father's house.",
          "That is not a small request in the ancient world.",
          "Family and land were security, identity, and future.",
          "Abram is being called away from what is familiar into a future God will show him.",
          "The call requires trust before Abram knows the whole map.",
          "Faith begins with God's word, not with full information.",
        ]),
      ],
      [
        "🌍 In Thee Shall All Families Of The Earth Be Blessed",
        note([
          "God's promise to Abram is bigger than Abram's private life.",
          "After Babel scattered the nations, God chooses one man through whom blessing will reach all families.",
          "That means election has a mission.",
          "God is not choosing Abram so everyone else is forgotten.",
          "He is choosing Abram as the channel of blessing for the world.",
          "The rest of the Bible keeps moving toward this promise.",
        ]),
      ],
      [
        "⛪ There Builded He An Altar",
        note([
          "Abram responds to God's promise by building an altar.",
          "An altar marks worship, gratitude, and meeting with God.",
          "Abram is not only traveling through the land; he is worshiping in it.",
          "This matters because Canaan is still occupied by others, but Abram is already calling on the Lord there.",
          "The altar becomes a witness that Abram belongs to God.",
          "Where God speaks, Abram worships.",
        ]),
      ],
    ],
  },
  {
    chapter: 12,
    startVerse: 10,
    endVerse: 20,
    reference: "Genesis 12:10-20",
    title: "Abram Goes Down To Egypt",
    icon: "😨",
    phrases: [
      [
        "🌾 There Was A Famine",
        note([
          "Abram reaches the land of promise and immediately faces famine.",
          "That is important because obedience does not mean life becomes easy.",
          "The promised land can still have pressure.",
          "Abram goes down to Egypt to survive, but fear begins shaping his choices.",
          "Genesis is showing that Abram is a man of faith, but still a man learning faith.",
          "The promise is real even when the land is hard.",
        ]),
      ],
      [
        "👩 Say, I Pray Thee, Thou Art My Sister",
        note([
          "Abram asks Sarai to say she is his sister because he fears being killed.",
          "Genesis 20 later explains there is a family connection, but the point here is still deception.",
          "Abram uses a half-truth to protect himself.",
          "That choice puts Sarai in danger.",
          "Fear can make people protect themselves while exposing someone else.",
          "Genesis does not hide Abram's failure.",
        ]),
      ],
      [
        "🛡️ The Lord Plagued Pharaoh",
        note([
          "God intervenes to protect Sarai and the promise.",
          "Abram's fear created danger, but God did not let Pharaoh keep Sarai.",
          "This matters because the promise depends on the family God is forming.",
          "God is faithful even when Abram acts foolishly.",
          "The rescue does not excuse Abram's deception.",
          "It shows that God's promise is stronger than Abram's weakness.",
        ]),
      ],
    ],
  },
  {
    chapter: 13,
    startVerse: 1,
    endVerse: 7,
    reference: "Genesis 13:1-7",
    title: "Abram And Lot Outgrow The Land",
    icon: "🐑",
    phrases: [
      [
        "🔙 Abram Went Up Out Of Egypt",
        note([
          "Abram returns from Egypt to the land where he had built an altar.",
          "This feels like a recovery moment after his fearful choices in Egypt.",
          "He comes back to the place of worship.",
          "That matters because failure does not have to be the end of the journey.",
          "Abram returns to the land and calls on the Lord again.",
          "The story moves him back toward promise.",
        ]),
      ],
      [
        "📈 Abram Was Very Rich",
        note([
          "Abram has grown wealthy in animals, silver, and gold.",
          "Wealth in Genesis is often shown through flocks, herds, servants, and metals.",
          "But blessing also creates new challenges.",
          "Abram and Lot have so many possessions that the land cannot support them together.",
          "This phrase teaches that increase can bring pressure too.",
          "The next test is not poverty, but conflict in abundance.",
        ]),
      ],
      [
        "⚔️ There Was A Strife",
        note([
          "The herdsmen of Abram and Lot begin fighting.",
          "The conflict is practical: too many animals need water and grazing land.",
          "But the spiritual test is how Abram will handle it.",
          "He could demand first choice because he is the older and greater figure.",
          "Instead, he will choose peace.",
          "Genesis is showing Abram grow in trust after the fear of Egypt.",
        ]),
      ],
    ],
  },
  {
    chapter: 13,
    startVerse: 8,
    endVerse: 18,
    reference: "Genesis 13:8-18",
    title: "Lot Chooses The Plain",
    icon: "👀",
    phrases: [
      [
        "🤝 Let There Be No Strife",
        note([
          "Abram seeks peace with Lot before the conflict grows.",
          "This matters because family conflict can become destructive if no one steps down.",
          "Abram does not cling to control.",
          "He gives Lot the choice of land.",
          "That is a major act of trust because land is tied to survival and future.",
          "Abram can be generous because he believes God is his provider.",
        ]),
      ],
      [
        "👀 Lot Lifted Up His Eyes",
        note([
          "Lot chooses by what looks good to his eyes.",
          "The plain is well-watered and attractive.",
          "But Genesis also tells us Sodom is nearby and morally wicked.",
          "That tension matters.",
          "Lot sees opportunity, but does not seem to weigh the spiritual danger.",
          "The choice that looks best on the surface will pull him toward trouble.",
        ]),
      ],
      [
        "🌍 All The Land Which Thou Seest",
        note([
          "After Lot separates, God repeats the land promise to Abram.",
          "That timing matters.",
          "Abram gave Lot first choice, but he did not lose God's promise.",
          "God tells Abram to look in every direction because the land will belong to his offspring.",
          "Abram's future does not depend on grabbing the best-looking option.",
          "It depends on God's word.",
        ]),
      ],
    ],
  },
  {
    chapter: 14,
    startVerse: 1,
    endVerse: 12,
    reference: "Genesis 14:1-12",
    title: "Lot Is Taken Captive",
    icon: "⚔️",
    phrases: [
      [
        "⚔️ Four Kings With Five",
        note([
          "Genesis 14 opens with regional conflict between kings.",
          "This can feel like a sudden war report, but it shows the dangerous world around Abram.",
          "The promised land is not peaceful empty space.",
          "It is full of politics, alliances, rebellion, and violence.",
          "Abram's family is living inside real ancient power struggles.",
          "The covenant promise is unfolding in a messy world.",
        ]),
      ],
      [
        "🏙️ Sodom And Gomorrah",
        note([
          "Sodom and Gomorrah appear here before their judgment in Genesis 19.",
          "Lot has moved near Sodom, and now he is caught in Sodom's trouble.",
          "This is important because Lot's earlier choice is beginning to have consequences.",
          "The place that looked prosperous also places him in danger.",
          "Genesis is not random in naming Sodom here.",
          "It is showing the cost of drifting toward a wicked city.",
        ]),
      ],
      [
        "⛓️ They Took Lot",
        note([
          "Lot is captured because he is living in Sodom.",
          "This is the first major danger connected to his choice of location.",
          "Abram's nephew is now pulled into a war he did not start.",
          "The phrase reminds us that where we settle can shape what we get caught in.",
          "Lot's trouble becomes Abram's rescue mission.",
          "Family ties still matter even after separation.",
        ]),
      ],
    ],
  },
  {
    chapter: 14,
    startVerse: 13,
    endVerse: 24,
    reference: "Genesis 14:13-24",
    title: "Abram Rescues Lot",
    icon: "🛡️",
    phrases: [
      [
        "🏃 Abram The Hebrew",
        note([
          "This is the first time Abram is called the Hebrew.",
          "It marks him as distinct among the peoples around him.",
          "Abram is not a king like the others in the chapter, but he acts with courage and loyalty.",
          "He hears Lot is captured and moves to rescue him.",
          "The title reminds us that Abram is a stranger in the land, yet God is with him.",
          "His identity is tied to the promise, not to local power.",
        ]),
      ],
      [
        "🍞 Melchizedek King Of Salem",
        note([
          "Melchizedek appears suddenly as king of Salem and priest of the Most High God.",
          "His name is connected with righteousness, and Salem is connected with peace.",
          "He blesses Abram after the rescue.",
          "This is important because Abram meets a priest-king who honors the same Most High God.",
          "Later Scripture, especially Psalm 110 and Hebrews, looks back to Melchizedek as deeply significant.",
          "Genesis gives us a mysterious glimpse of priestly kingship before Israel exists.",
        ]),
      ],
      [
        "🙌 I Have Lift Up Mine Hand Unto The Lord",
        note([
          "Abram refuses to take wealth from the king of Sodom.",
          "He does not want Sodom's king to claim he made Abram rich.",
          "This is a strong contrast with Egypt, where Abram received gifts in a messy situation.",
          "Here Abram is careful about where his increase comes from.",
          "He wants the Lord alone to be seen as his provider.",
          "Faith is growing in Abram's choices.",
        ]),
      ],
    ],
  },
  {
    chapter: 15,
    startVerse: 1,
    endVerse: 6,
    reference: "Genesis 15:1-6",
    title: "Abram Believes God",
    icon: "⭐",
    phrases: [
      [
        "🛡️ I Am Thy Shield",
        note([
          "God speaks to Abram after the battle and tells him not to fear.",
          "A shield protects a person in danger.",
          "Abram has just faced kings, rescued Lot, and refused Sodom's reward.",
          "God Himself promises to be Abram's protection and reward.",
          "This matters because Abram's security is not in armies or wealth.",
          "His safety rests in the Lord.",
        ]),
      ],
      [
        "👶 I Go Childless",
        note([
          "Abram honestly tells God the problem he still feels.",
          "God has promised descendants, but Abram has no child.",
          "This is not unbelief pretending to be prayer.",
          "It is honest faith bringing the tension to God.",
          "Abram's life is blessed in many ways, but the central promise still seems impossible.",
          "Genesis lets us hear the ache under his faith.",
        ]),
      ],
      [
        "⭐ Tell The Stars",
        note([
          "God takes Abram outside and tells him to look at the stars.",
          "The stars become a picture of descendants too many to count.",
          "God does not answer Abram with a child immediately.",
          "He answers with a renewed promise.",
          "Abram believes the Lord, and God counts it to him as righteousness.",
          "This becomes one of the most important faith texts in the whole Bible.",
        ]),
      ],
    ],
  },
  {
    chapter: 15,
    startVerse: 7,
    endVerse: 21,
    reference: "Genesis 15:7-21",
    title: "God Makes A Covenant With Abram",
    icon: "🔥",
    phrases: [
      [
        "📍 To Give Thee This Land",
        note([
          "God connects Abram's faith to the land promise again.",
          "Abram asks how he will know he will inherit it.",
          "This question matters because Abram believes God, but still needs assurance.",
          "Faith can ask for help understanding the promise.",
          "God does not shame Abram for asking.",
          "He gives him a covenant ceremony.",
        ]),
      ],
      [
        "🔥 A Smoking Furnace, And A Burning Lamp",
        note([
          "The smoking furnace and burning lamp pass between the pieces of the sacrifice.",
          "This is covenant imagery.",
          "In that world, passing between cut animals could symbolize a serious oath.",
          "What is stunning is that God alone passes through.",
          "Abram is asleep while God binds Himself to the promise.",
          "The covenant rests on God's faithfulness before it rests on Abram's strength.",
        ]),
      ],
      [
        "🧳 Thy Seed Shall Be A Stranger",
        note([
          "God tells Abram his descendants will be strangers and afflicted before receiving the land.",
          "This points forward to Israel in Egypt.",
          "The promise includes delay, suffering, and deliverance.",
          "That matters because God's plan is not shallow or instant.",
          "Abram is being told that the road to fulfillment will be long.",
          "But God also promises judgment on the oppressor and return to the land.",
        ]),
      ],
    ],
  },
  {
    chapter: 16,
    startVerse: 1,
    endVerse: 6,
    reference: "Genesis 16:1-6",
    title: "Sarai And Abram Try To Force The Promise",
    icon: "😔",
    phrases: [
      [
        "🚫 Sarai Bare Him No Children",
        note([
          "The chapter begins by repeating Sarai's barrenness.",
          "This is the pressure under the whole story.",
          "God promised descendants, but years have passed with no child through Sarai.",
          "Waiting has become painful.",
          "The problem is real, but the solution Sarai proposes will wound the household.",
          "Genesis is showing what happens when people try to force God's promise through fear.",
        ]),
      ],
      [
        "👩 Hagar The Egyptian",
        note([
          "Hagar is an Egyptian servant in Sarai's household.",
          "She is vulnerable because she does not have the same power Abram and Sarai have.",
          "Sarai gives her to Abram to produce a child.",
          "This may have been a known ancient custom, but Genesis shows the pain it creates.",
          "Hagar is not just a tool in the story.",
          "She is a real person who will be seen by God.",
        ]),
      ],
      [
        "💔 Sarai Dealt Hardly With Her",
        note([
          "After Hagar becomes pregnant, tension erupts in the household.",
          "Sarai feels dishonored, Abram avoids responsibility, and Hagar suffers.",
          "The plan that was supposed to solve the problem creates a new wound.",
          "This matters because human shortcuts often produce pain people did not expect.",
          "Genesis does not romanticize the decision.",
          "It shows the brokenness that grows from trying to control the promise.",
        ]),
      ],
    ],
  },
  {
    chapter: 16,
    startVerse: 7,
    endVerse: 16,
    reference: "Genesis 16:7-16",
    title: "God Sees Hagar",
    icon: "👁️",
    phrases: [
      [
        "🌵 The Angel Of The Lord Found Her",
        note([
          "Hagar runs into the wilderness, but the Lord finds her there.",
          "That word found matters because Hagar is not forgotten or invisible.",
          "She is away from Abram's household, but not away from God's sight.",
          "The wilderness becomes the place where God meets a mistreated servant.",
          "This is one of the most tender scenes in Genesis.",
          "God sees the person the household failed to protect.",
        ]),
      ],
      [
        "👶 Thou Shalt Call His Name Ishmael",
        note([
          "Ishmael means God hears.",
          "The name is connected to Hagar's affliction.",
          "Every time the name is spoken, it testifies that God heard her pain.",
          "This matters because Hagar has very little power in the human story.",
          "But God gives her child a name rooted in divine attention.",
          "Her suffering has reached God's ears.",
        ]),
      ],
      [
        "👁️ Thou God Seest Me",
        note([
          "Hagar names God as the God who sees her.",
          "This is remarkable because she is not the central covenant figure like Abram.",
          "Yet she has a direct encounter with God's care.",
          "The phrase teaches something deeply personal about the Lord.",
          "He sees people in places where others may ignore them.",
          "Hagar's testimony becomes one of the clearest statements of God's compassion in Genesis.",
        ]),
      ],
    ],
  },
  {
    chapter: 17,
    startVerse: 1,
    endVerse: 8,
    reference: "Genesis 17:1-8",
    title: "God Renames Abram",
    icon: "🆕",
    phrases: [
      [
        "🙌 I Am The Almighty God",
        note([
          "God introduces Himself to Abram as Almighty God.",
          "That title matters because Abram's situation still looks impossible.",
          "He is old, Sarai is barren, and the promised son has not come.",
          "God's power is the foundation for the command and promise that follow.",
          "Abram's hope is not in human possibility.",
          "It is in the Almighty God who can do what people cannot.",
        ]),
      ],
      [
        "🚶 Walk Before Me, And Be Thou Perfect",
        note([
          "God calls Abram to live before Him faithfully.",
          "Perfect here carries the idea of wholeness, integrity, or blamelessness.",
          "God is not asking Abram to pretend he has no weakness.",
          "He is calling him to wholehearted covenant life.",
          "The promise does not remove obedience.",
          "Grace and calling belong together in Abram's story.",
        ]),
      ],
      [
        "🆕 Abraham",
        note([
          "Abram's name is changed to Abraham, connected with being father of many nations.",
          "This is powerful because he still does not have the promised son through Sarah.",
          "God names him according to the promise before the promise is visible.",
          "The new name asks Abraham to live under what God has said.",
          "Every time the name is spoken, it points to God's future.",
          "Identity is being shaped by promise.",
        ]),
      ],
    ],
  },
  {
    chapter: 17,
    startVerse: 9,
    endVerse: 14,
    reference: "Genesis 17:9-14",
    title: "The Sign Of Circumcision",
    icon: "✂️",
    phrases: [
      [
        "✂️ Every Man Child Among You Shall Be Circumcised",
        note([
          "Circumcision becomes the covenant sign for Abraham's household.",
          "It marks the males of the family as belonging to the covenant God made with Abraham.",
          "The sign is physical because the promise involves real descendants, real bodies, and real generations.",
          "It is not a private feeling only.",
          "The covenant is marked into the family line.",
          "This sign will later become a major identity marker for Israel.",
        ]),
      ],
      [
        "🏠 Born In The House, Or Bought With Money",
        note([
          "The sign includes more than Abraham's biological children.",
          "Servants and those attached to his household are included too.",
          "That matters because the covenant household is wider than one nuclear family.",
          "Everyone under Abraham's house is brought under the sign.",
          "Genesis is showing a whole household being marked by God's covenant.",
          "The promise begins with Abraham but reaches through his community.",
        ]),
      ],
      [
        "⚠️ That Soul Shall Be Cut Off",
        note([
          "Rejecting the covenant sign is treated seriously.",
          "To be cut off means to be removed from covenant belonging.",
          "This shows that God's covenant is not casual.",
          "The sign does not save by itself, but rejecting it rejects the covenant command God gave.",
          "The relationship with God includes both promise and responsibility.",
          "Genesis wants the reader to feel the weight of belonging to the Lord.",
        ]),
      ],
    ],
  },
  {
    chapter: 17,
    startVerse: 15,
    endVerse: 27,
    reference: "Genesis 17:15-27",
    title: "Sarah Is Named And Isaac Is Promised",
    icon: "👶",
    phrases: [
      [
        "🆕 Sarah",
        note([
          "Sarai's name is changed to Sarah.",
          "God does not only rename Abraham.",
          "He also marks Sarah as central to the promise.",
          "That matters because the promised son will not come through Hagar or another woman.",
          "He will come through Sarah.",
          "Her new name stands beside Abraham's as part of the covenant future.",
        ]),
      ],
      [
        "😂 Abraham Fell Upon His Face, And Laughed",
        note([
          "Abraham laughs because the promise sounds impossible.",
          "He is nearly one hundred, and Sarah is ninety.",
          "The laughter is not ignored by the story.",
          "It shows the human shock of hearing God promise something beyond natural possibility.",
          "God does not change the promise because Abraham laughs.",
          "Instead, He names the child Isaac, a name connected with laughter.",
        ]),
      ],
      [
        "👶 Sarah Shall Bear Unto Thee Isaac",
        note([
          "God names the promised child before he is born.",
          "Isaac will be the son of covenant promise.",
          "Ishmael will be blessed, but Isaac is the line through whom the covenant continues.",
          "This distinction matters for the rest of Genesis.",
          "God is not rejecting compassion for Ishmael.",
          "He is clarifying the specific promise line through Sarah's son.",
        ]),
      ],
    ],
  },
  {
    chapter: 18,
    startVerse: 1,
    endVerse: 15,
    reference: "Genesis 18:1-15",
    title: "The Lord Visits Abraham And Sarah",
    icon: "⛺",
    phrases: [
      [
        "⛺ The Lord Appeared Unto Him",
        note([
          "Genesis says the Lord appeared to Abraham by the oaks of Mamre.",
          "The scene begins like a visit from travelers, but the text tells us something deeper is happening.",
          "Abraham responds with urgent hospitality.",
          "In the ancient world, hospitality was a serious act of honor and care.",
          "This visit becomes the setting for another promise about Sarah's son.",
          "God comes near to Abraham's tent before the promise is fulfilled.",
        ]),
      ],
      [
        "📅 At The Time Appointed",
        note([
          "God gives a specific time for Sarah to have a son.",
          "The promise is no longer distant and vague.",
          "It is moving toward fulfillment.",
          "This matters because Abraham and Sarah have waited for years.",
          "God's promise has timing, even when the waiting feels long.",
          "The appointed time belongs to the Lord.",
        ]),
      ],
      [
        "😂 Sarah Laughed Within Herself",
        note([
          "Sarah laughs quietly because the promise sounds impossible to her body and age.",
          "The Bible does not flatten her into a simple villain of unbelief.",
          "It lets us see how hard the promise is to receive after years of barrenness.",
          "God answers her hidden laughter with a question: Is anything too hard for the Lord?",
          "That question is the point of the scene.",
          "The promise depends on God's power, not Sarah's ability.",
        ]),
      ],
    ],
  },
  {
    chapter: 18,
    startVerse: 16,
    endVerse: 33,
    reference: "Genesis 18:16-33",
    title: "Abraham Intercedes For Sodom",
    icon: "🙏",
    phrases: [
      [
        "⚖️ Shall Not The Judge Of All The Earth Do Right?",
        note([
          "Abraham asks one of the most important justice questions in Genesis.",
          "He knows the Lord is judge over the whole earth.",
          "His concern is whether the righteous will be swept away with the wicked.",
          "This matters because biblical justice is not random anger.",
          "Abraham appeals to God's own character.",
          "He believes God's judgment must be righteous.",
        ]),
      ],
      [
        "🙏 Peradventure There Be Fifty Righteous",
        note([
          "Abraham begins interceding for Sodom by asking about fifty righteous people.",
          "He is not defending Sodom's wickedness.",
          "He is pleading for mercy if righteous people are present there.",
          "The conversation shows Abraham acting like a mediator.",
          "He stands before God and asks for mercy on behalf of others.",
          "This is a major growth moment after Abraham's earlier fear-driven failures.",
        ]),
      ],
      [
        "🔟 For Ten's Sake",
        note([
          "Abraham's intercession moves from fifty down to ten.",
          "The Lord agrees not to destroy the city if ten righteous are found.",
          "That shows God's patience and willingness to hear Abraham's plea.",
          "But it also prepares the reader for how corrupt Sodom really is.",
          "The problem is not that God is unwilling to spare.",
          "The tragedy is that the city does not even have ten righteous people.",
        ]),
      ],
    ],
  },
  {
    chapter: 19,
    startVerse: 1,
    endVerse: 11,
    reference: "Genesis 19:1-11",
    title: "Sodom Shows Its Wickedness",
    icon: "🏙️",
    phrases: [
      [
        "🏙️ Lot Sat In The Gate Of Sodom",
        note([
          "The city gate was a place of public life, leadership, and decisions.",
          "Lot is no longer just near Sodom; he is sitting in its gate.",
          "That suggests he has become part of the city's life.",
          "This matters because his earlier choice to move toward Sodom has gone deeper over time.",
          "Small steps toward a place can become deep entanglement.",
          "Lot is righteous, but he is living in a dangerous environment.",
        ]),
      ],
      [
        "🚪 Bring Them Out Unto Us",
        note([
          "The men of Sodom surround Lot's house and demand the visitors.",
          "The scene exposes the violence and corruption of the city.",
          "This is not only private sin; it is public, aggressive wickedness.",
          "The whole crowd participates in the threat.",
          "Genesis wants us to see why judgment is coming.",
          "Sodom's evil is not hidden anymore.",
        ]),
      ],
      [
        "👁️ They Smote The Men With Blindness",
        note([
          "The angels strike the men with blindness to protect the household.",
          "Even then, the men keep wearing themselves out trying to find the door.",
          "That detail shows how hardened they are.",
          "Judgment has begun, but their desire is still violent.",
          "The blindness is both protection and warning.",
          "Sodom is spiritually blind before it is physically struck blind.",
        ]),
      ],
    ],
  },
  {
    chapter: 19,
    startVerse: 12,
    endVerse: 22,
    reference: "Genesis 19:12-22",
    title: "Lot Is Pulled Out Of Sodom",
    icon: "🏃",
    phrases: [
      [
        "🏃 Escape For Thy Life",
        note([
          "The angels command Lot to flee because judgment is coming.",
          "This is urgent language.",
          "Lot cannot negotiate a comfortable exit from a condemned city.",
          "He must leave quickly and not look back.",
          "The phrase matters because rescue sometimes requires separation.",
          "God's mercy pulls Lot out, but Lot still has to leave Sodom behind.",
        ]),
      ],
      [
        "⏳ While He Lingered",
        note([
          "Lot delays even after being warned.",
          "That is one of the saddest details in the chapter.",
          "He knows danger is coming, but he still struggles to leave.",
          "Sodom has a hold on him and his family.",
          "The angels seize their hands because the Lord is merciful.",
          "Lot's rescue is not because he moves quickly, but because God shows compassion.",
        ]),
      ],
      [
        "🖐️ The Lord Being Merciful Unto Him",
        note([
          "This phrase explains why Lot survives.",
          "The angels pull him, his wife, and his daughters out because of God's mercy.",
          "Lot is not presented as heroic in this moment.",
          "He is hesitant and afraid.",
          "God's mercy is stronger than Lot's hesitation.",
          "The rescue shows that deliverance can be deeply gracious even when people are slow to obey.",
        ]),
      ],
    ],
  },
  {
    chapter: 19,
    startVerse: 23,
    endVerse: 38,
    reference: "Genesis 19:23-38",
    title: "Sodom Falls And Lot's Family Breaks",
    icon: "🔥",
    phrases: [
      [
        "🔥 Brimstone And Fire",
        note([
          "The Lord rains judgment on Sodom and Gomorrah.",
          "This is the answer to the outcry against the city.",
          "Genesis shows judgment as serious and terrifying.",
          "God is patient in the conversation with Abraham, but Sodom's evil is real.",
          "The destruction becomes one of the Bible's major examples of judgment.",
          "It warns that wickedness does not continue forever unchecked.",
        ]),
      ],
      [
        "🧂 His Wife Looked Back",
        note([
          "Lot's wife looks back and becomes a pillar of salt.",
          "The look is more than a glance over the shoulder.",
          "It shows attachment to the city God was judging.",
          "She was brought out of Sodom, but her heart still turned back toward it.",
          "This detail becomes a warning later in Scripture.",
          "Being physically removed from danger is not the same as fully letting go.",
        ]),
      ],
      [
        "💔 Moab And Ammon",
        note([
          "The chapter ends with the disturbing origin of Moab and Ammon.",
          "Lot's daughters act out of fear and desperation after the destruction.",
          "The scene is morally broken and painful.",
          "Moab and Ammon will later become important neighbors and enemies of Israel.",
          "Genesis is showing how damaged choices can echo into future nations.",
          "Lot escapes Sodom, but his family story remains deeply wounded.",
        ]),
      ],
    ],
  },
  {
    chapter: 20,
    startVerse: 1,
    endVerse: 7,
    reference: "Genesis 20:1-7",
    title: "Abraham Repeats The Lie",
    icon: "🔁",
    phrases: [
      [
        "👩 She Is My Sister",
        note([
          "Abraham repeats the same fear-driven plan he used in Egypt.",
          "This is painful because he has walked with God for years by now.",
          "Old fear can return even after real growth.",
          "The statement has some family truth behind it, but it is used deceptively.",
          "Abraham is again protecting himself while putting Sarah at risk.",
          "Genesis is honest that people of faith can repeat old failures.",
        ]),
      ],
      [
        "🌙 God Came To Abimelech In A Dream",
        note([
          "God intervenes before Abimelech touches Sarah.",
          "This protects Sarah, Abimelech, and the promised child who will soon come.",
          "The dream shows that God is guarding the promise even when Abraham is acting out of fear.",
          "Abimelech is not part of Abraham's covenant line, but God still speaks to him.",
          "The Lord is working beyond Abraham's household.",
          "God's protection is wider than Abraham's wisdom.",
        ]),
      ],
      [
        "🙏 He Is A Prophet",
        note([
          "God calls Abraham a prophet even in a chapter where Abraham fails.",
          "That is surprising.",
          "It does not excuse Abraham's deception, but it shows his calling remains real.",
          "Abraham will pray for Abimelech, and God will heal his household.",
          "This matters because God's gifts and callings are not based on people being flawless.",
          "Abraham still needs correction, but he also still carries a role before God.",
        ]),
      ],
    ],
  },
  {
    chapter: 20,
    startVerse: 8,
    endVerse: 18,
    reference: "Genesis 20:8-18",
    title: "Sarah Is Restored",
    icon: "🛡️",
    phrases: [
      [
        "😳 What Hast Thou Done Unto Us?",
        note([
          "Abimelech confronts Abraham directly.",
          "The question exposes how Abraham's fear endangered other people.",
          "Abraham may have thought he was only managing his own survival.",
          "But his deception nearly brought guilt on an entire household.",
          "This matters because fear often feels private, but its choices can hurt others.",
          "Abraham has to face the damage his half-truth caused.",
        ]),
      ],
      [
        "😨 I Thought, Surely The Fear Of God Is Not In This Place",
        note([
          "Abraham explains that he lied because he assumed the people of Gerar did not fear God.",
          "That assumption was wrong.",
          "Abimelech acts with more integrity in this chapter than Abraham does.",
          "Genesis is challenging Abraham's fear and prejudice.",
          "He judged the place before he knew the people.",
          "Fear made him see danger everywhere and act deceptively.",
        ]),
      ],
      [
        "🙏 Abraham Prayed Unto God",
        note([
          "Abraham prays, and God heals Abimelech's household.",
          "This closes the chapter with mercy after correction.",
          "Sarah is restored, Abimelech is protected, and Abraham intercedes.",
          "The promise is preserved again by God's faithfulness.",
          "This matters because Isaac's birth is about to happen in Genesis 21.",
          "Before the promised son arrives, God protects the promised mother.",
        ]),
      ],
    ],
  },
];

const GENESIS_11_PERSONAL_REWRITE_SECTIONS: PersonalGenesisPhraseSectionInput[] = [
  {
    chapter: 11,
    startVerse: 1,
    endVerse: 4,
    reference: "Genesis 11:1-4",
    title: "The Tower Of Babel Begins",
    icon: "🏙️",
    phrases: [
      [
        "🗣️ The Whole Earth Was Of One Language",
        note([
          "Before Babel, humanity is described as having one language and one speech.",
          "This means the people shared the same words and could understand each other without translation.",
          "That made communication fast and cooperation easy.",
          "Unity itself was not evil.",
          "God had already blessed humanity and told them to fill the earth.",
          "The problem is what they chose to do with their unity.",
          "They used a shared language to gather around pride, control, and self-protection.",
          "Genesis is showing that people can be united and still be moving in the wrong direction.",
        ]),
      ],
      [
        "🧭 As They Journeyed From The East",
        note([
          "This phrase tells us the people are moving after the flood and after the nations begin spreading.",
          "The direction matters because Genesis often uses movement to show where people are going physically and spiritually.",
          "They are not simply taking a walk; they are relocating and settling together.",
          "Instead of continuing to spread over the earth, they find a place where they can stop and build.",
          "A brand-new reader might wonder why Genesis mentions the direction at all.",
          "It helps place the story in real geography and real movement.",
          "The people are on the move, but their hearts are about to move toward pride.",
          "Genesis is setting up the tension between God's command to fill the earth and humanity's desire to gather in one place.",
        ]),
      ],
      [
        "🌅 From The East",
        note([
          "The words from the east are a location marker.",
          "Genesis is not telling a floating story with no place attached to it.",
          "It is describing people moving across real land after the flood.",
          "In Genesis, directions often help us follow movement, separation, exile, return, and settlement.",
          "Here the main point is that humanity is gathering into a region where the Babel project can begin.",
          "The phrase also reminds us that the nations are still in motion after Noah's family leaves the ark.",
          "God wanted humanity to fill the earth, but this group chooses to stop and centralize their life.",
          "That decision prepares the reader for the rebellion that follows.",
        ]),
      ],
      [
        "🏜️ A Plain",
        note([
          "A plain is a wide, flat stretch of land.",
          "That matters because flat land is easier for settling, farming, organizing people, and building a city.",
          "The people are not choosing a random spot.",
          "They find a place that can support a large shared project.",
          "For a new reader, this explains why a city and tower can be imagined here.",
          "The geography helps the story make sense.",
          "A plain gives them room to build outward and upward.",
          "The problem is not the plain itself; the problem is the pride that shapes what they build there.",
        ]),
      ],
      [
        "🗺️ The Land Of Shinar",
        note([
          "Shinar is the region connected with ancient Mesopotamia, the area around the great river systems of the ancient world.",
          "This matters because Mesopotamia was known for early cities, organized building, and large temple-tower structures.",
          "Later in the Bible, Shinar is also connected with Babylon.",
          "That means this location is not just background scenery.",
          "It becomes part of a larger Bible theme: human empire trying to organize life apart from God.",
          "Babel begins here, and Babylon later becomes a major symbol of proud human power.",
          "Genesis is planting a seed that the rest of Scripture will keep developing.",
          "When readers see Shinar, they should think of a real place and a spiritual pattern beginning to form.",
        ]),
      ],
      [
        "🏠 They Dwelt There",
        note([
          "To dwell means to settle, remain, or make a home.",
          "This matters because God's blessing after creation and after the flood was connected to filling the earth.",
          "The people are not merely resting for a moment.",
          "They are choosing to settle together in one place.",
          "That decision explains why they soon build a city.",
          "They want permanence, safety, and control.",
          "Settling is not always wrong, but here it becomes part of resisting God's purpose.",
          "Genesis shows that the problem begins before the tower reaches upward; it begins when the people choose security over obedience.",
        ]),
      ],
      [
        "🧱 Let Us Make Brick",
        note([
          "The builders make bricks because they are settling in a flat land where natural stone was not the normal building material.",
          "In Mesopotamia, baked brick was common because good stone was harder to find.",
          "This detail shows human skill, planning, and technology.",
          "They know how to organize labor, gather materials, and build something large.",
          "Genesis is not saying technology is evil.",
          "The problem is not that they know how to make bricks.",
          "The problem is the purpose their skill is serving.",
          "Human ability becomes dangerous when it is used for pride and independence from God.",
        ]),
      ],
      [
        "🔥 Burn Them Thoroughly",
        note([
          "Burning the bricks thoroughly means they baked them hard so they would be stronger and more durable.",
          "Sun-dried bricks were common, but fired bricks could last longer and support bigger projects.",
          "This tells the reader the builders are serious and organized.",
          "They are not throwing together a small shelter.",
          "They are preparing materials for a lasting city and tower.",
          "The phrase helps us see the ambition behind Babel.",
          "They want something permanent enough to protect their name and hold their people together.",
          "The stronger the brick, the clearer the desire for lasting human glory.",
        ]),
      ],
      [
        "🧱 Brick For Stone",
        note([
          "This phrase explains the building materials in a place where stone was not the normal resource.",
          "The people substitute brick where others might have used stone.",
          "A new reader might wonder why Genesis pauses to explain this.",
          "It shows that the project is tied to the land of Shinar and its culture.",
          "The builders are adapting to their environment with real skill.",
          "Again, the Bible is not mocking their intelligence.",
          "It is showing that smart people can still build foolishly when pride leads the way.",
          "The material is strong, but the spiritual foundation is weak.",
        ]),
      ],
      [
        "🛢️ Slime Had They For Mortar",
        note([
          "The word slime in the KJV refers to bitumen, a tar-like substance used as mortar.",
          "Mortar is what holds bricks together.",
          "In ancient Mesopotamia, bitumen was used in building because it helped seal and bind materials.",
          "This detail gives cultural and historical texture to the story.",
          "Genesis is showing a real kind of ancient construction.",
          "The people have bricks and binding material, so they have everything needed for a major project.",
          "But the deeper issue is that strong mortar cannot hold together a rebellious heart.",
          "Babel may be well-built physically, but spiritually it is already cracking.",
        ]),
      ],
      [
        "🏙️ Let Us Build Us A City",
        note([
          "A city in the ancient world meant more than buildings.",
          "It meant protection, identity, economy, leadership, and a shared center of life.",
          "The people want a place that can hold them together.",
          "That desire makes sense on one level because scattering can feel unsafe.",
          "But Genesis has already shown that God wanted humanity to fill the earth.",
          "The city becomes a way to resist that calling.",
          "They are building a center around themselves instead of trusting God's rule over the whole earth.",
          "Babel is not just construction; it is a community organized around self-made security.",
        ]),
      ],
      [
        "🗼 A Tower Whose Top May Reach Unto Heaven",
        note([
          "This phrase does not mean the people could literally build into God's throne room.",
          "It means they wanted a tower that reached upward and looked spiritually impressive.",
          "In Mesopotamia, large temple-towers called ziggurats were built as religious and civic centers.",
          "They were connected with worship, power, and the idea of linking earth and heaven.",
          "That background helps explain why Babel is such a serious story.",
          "The people are not only building tall; they are trying to establish access, greatness, and security on human terms.",
          "Genesis answers their pride with irony: God still has to come down to see it.",
          "No human tower can force its way into heaven.",
        ]),
      ],
      [
        "🏷️ Let Us Make Us A Name",
        note([
          "This is the heart of Babel.",
          "The people want a name for themselves.",
          "In the Bible, a name is connected to identity, reputation, legacy, and significance.",
          "They want to secure their own greatness instead of receiving their identity from God.",
          "This is why Babel connects so strongly to Genesis 12.",
          "Right after Babel, God will tell Abram, I will make thy name great.",
          "Babel grasps for a name; Abram receives one by promise.",
          "Lasting significance is not seized by pride; it is given by God.",
        ]),
      ],
      [
        "🌍 Lest We Be Scattered Abroad",
        note([
          "This phrase tells us what the builders fear.",
          "They do not want to be scattered across the earth.",
          "But spreading across the earth was part of God's command to humanity after creation and after the flood.",
          "That means their fear is pulling them away from obedience.",
          "They build to keep control, stay together, and protect their own future.",
          "A new reader might think the city sounds wise, but Genesis shows the deeper problem.",
          "Safety can become disobedience when it keeps us from what God has said.",
          "Babel is what happens when fear and pride work together.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 5,
    endVerse: 9,
    reference: "Genesis 11:5-9",
    title: "God Scatters Babel",
    icon: "🔀",
    phrases: [
      [
        "⬇️ The Lord Came Down",
        note([
          "This phrase is one of the most important lines in the Babel story.",
          "The people build a tower they think reaches toward heaven, but Genesis says the Lord came down to see it.",
          "That is intentional irony.",
          "From the ground, the tower may have looked massive and impressive.",
          "From God's view, it is so small that He must come down to inspect it.",
          "The phrase humbles human pride without needing a long argument.",
          "God is not threatened by Babel.",
          "He stands above every human project, city, empire, and tower.",
        ]),
      ],
      [
        "👥 The Children Of Men",
        note([
          "Genesis calls the builders the children of men.",
          "That phrase reminds us that Babel is a human project, not a God-commanded one.",
          "It also links the story to humanity as a whole after the flood.",
          "This is not only one family's private mistake.",
          "It represents the wider human tendency to organize life around pride and independence.",
          "The phrase helps the reader see Babel as a mirror.",
          "The issue is not only ancient builders in Shinar.",
          "It is the human heart trying to build identity without surrendering to God.",
        ]),
      ],
      [
        "🗣️ One People And One Language",
        note([
          "God notices that the people are united in speech and purpose.",
          "Again, unity by itself is not the problem.",
          "The problem is that unity is being used to resist God's command and magnify human pride.",
          "Shared language makes the project possible because everyone can plan, command, and cooperate easily.",
          "This explains why God's judgment touches their language.",
          "He disrupts the tool they are using for rebellion.",
          "The phrase teaches that power becomes dangerous when many people share one sinful purpose.",
          "Unity needs truth and humility, not just agreement.",
        ]),
      ],
      [
        "🚧 Nothing Will Be Restrained From Them",
        note([
          "This does not mean humans can overpower God.",
          "It means their united rebellion will keep growing if God does not intervene.",
          "The phrase shows God's concern over what sinful humanity can become when pride is organized and unchecked.",
          "After the flood, the human heart is still bent toward evil.",
          "Babel proves that judgment has not removed the sin problem.",
          "God sees that the project is only the beginning of a deeper direction.",
          "Stopping Babel is judgment, but it is also restraint.",
          "God limits evil before it spreads even further.",
        ]),
      ],
      [
        "🔽 Go To, Let Us Go Down",
        note([
          "Go to is an older way of saying come, let us act now.",
          "The phrase echoes the builders' own words, because they said, let us make brick and let us build.",
          "Humanity says, let us build upward.",
          "God says, let us go down.",
          "That contrast is powerful.",
          "The builders organize themselves in pride, but God answers as the true ruler.",
          "Many Christians also notice the plural language here and connect it with the fullness of God's counsel.",
          "The main point is clear: God responds directly to the proud plan.",
        ]),
      ],
      [
        "🗣️ Confound Their Language",
        note([
          "To confound means to confuse or mix up.",
          "God confuses their language so they can no longer understand one another.",
          "This judgment fits the sin exactly.",
          "They used one speech to build a proud center, so God breaks the shared speech that made the project possible.",
          "A new reader might wonder why God does not simply knock the tower down.",
          "Instead, He touches the deeper system holding the rebellion together.",
          "The project stops because communication breaks.",
          "Language confusion becomes the way God scatters pride.",
        ]),
      ],
      [
        "🌍 The Lord Scattered Them Abroad",
        note([
          "This is the result the builders were trying to avoid.",
          "They built the city because they did not want to be scattered, but God scatters them anyway.",
          "This shows that resisting God's purpose cannot finally succeed.",
          "God's command to fill the earth still stands.",
          "The scattering is judgment because their proud project is broken.",
          "But it also moves humanity back toward the purpose they were avoiding.",
          "Sometimes God's mercy comes through disruption.",
          "He tears down what would keep people trapped in rebellion.",
        ]),
      ],
      [
        "🏙️ Babel",
        note([
          "Babel is connected with confusion.",
          "The name becomes a memory of human pride, confused language, and scattering.",
          "Later in Scripture, Babylon grows from this same idea into a symbol of proud human empire against God.",
          "That makes Babel more than an old tower story.",
          "It becomes a pattern that runs through the Bible.",
          "Whenever people build life around their own name instead of God's glory, Babel is still alive in the human heart.",
          "Genesis 11 prepares us for the next answer: God will call Abram and promise blessing for all families of the earth.",
          "Human pride scatters, but God's promise will begin a rescue plan.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 10,
    endVerse: 17,
    reference: "Genesis 11:10-17",
    title: "Shem's Line Continues",
    icon: "📜",
    phrases: [
      [
        "📜 These Are The Generations Of Shem",
        note([
          "This phrase introduces the family line Genesis wants us to follow.",
          "After Babel scatters humanity, the story narrows back to Shem's descendants.",
          "That narrowing is important because Abram will come from this line.",
          "The genealogy may look slow, but it is moving the Bible story toward the next major promise.",
          "Genesis often gives family lines to show how God's plan is being preserved.",
          "This is not filler.",
          "It is the bridge from the scattered nations to the call of Abram.",
          "God is preparing blessing through one family for the sake of many families.",
        ]),
      ],
      [
        "👨 Shem Was An Hundred Years Old",
        note([
          "This detail connects the genealogy back to Noah's family after the flood.",
          "Shem is not a random name in a list.",
          "He is one of Noah's sons, and Genesis is showing how the post-flood world continues through him.",
          "The ages remind readers that the story is moving across generations.",
          "God's plan is not rushed.",
          "It passes through births, years, families, and ordinary life.",
          "A new reader may want to skip the numbers, but the numbers show continuity.",
          "The promise story has a real family timeline behind it.",
        ]),
      ],
      [
        "👶 Begat Arphaxad",
        note([
          "Begat means became the father of.",
          "The repeated word can feel boring, but it is how Genesis traces the promise line.",
          "Arphaxad matters because his line will keep moving toward Abram.",
          "Most of these names do not get long stories, but they still carry the line forward.",
          "That teaches something important about how God works.",
          "Not every faithful generation gets a dramatic chapter.",
          "Some people matter because they preserve the road for what God will do later.",
          "The quiet names are part of the promise story too.",
        ]),
      ],
      [
        "👪 Sons And Daughters",
        note([
          "This repeated phrase reminds us that these families were larger than the one named son in the promise line.",
          "Genesis names the person needed to trace the story, but it also acknowledges broader family life.",
          "These were real households with many people, not just names on a chart.",
          "The phrase helps readers avoid thinking the Bible only cares about one individual at a time.",
          "God is guiding a line, but that line exists inside real families and communities.",
          "The repetition also shows life continuing after Babel.",
          "Human pride was judged, but human life was not erased.",
          "God's mercy keeps generations moving.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 18,
    endVerse: 26,
    reference: "Genesis 11:18-26",
    title: "The Line Reaches Abram",
    icon: "🧬",
    phrases: [
      [
        "🧵 Peleg",
        note([
          "Peleg was already mentioned in Genesis 10, where his name is connected with division.",
          "That matters because Genesis 10 and 11 work together.",
          "Genesis 10 gives the spread of nations, and Genesis 11 explains the Babel event behind the scattering.",
          "Peleg's place in the family line keeps that connection in view.",
          "A reader may wonder why the Bible repeats names from earlier lists.",
          "It is helping us connect the map of nations with the story of Babel and the line to Abram.",
          "The world is divided, but God's promise line is still being preserved.",
          "Division does not stop God's plan.",
        ]),
      ],
      [
        "👴 Lived After He Begat",
        note([
          "This repeated phrase shows life continuing after each named son is born.",
          "The father does not disappear from the story the moment the next generation arrives.",
          "Genesis is showing overlapping generations, family continuity, and the slow passing of time.",
          "For a new Bible reader, this helps explain why the genealogy feels repetitive.",
          "The repetition is part of the rhythm.",
          "It shows that God's plan is moving through normal human life.",
          "Birth, age, family, and death all sit under God's larger purpose.",
          "The promise line is being carried forward one generation at a time.",
        ]),
      ],
      [
        "👨‍👦 Terah Lived Seventy Years",
        note([
          "Terah is Abram's father, so his name marks the final step before Abram appears.",
          "The genealogy is now almost at the person Genesis has been preparing us to meet.",
          "Terah's age and family details show that Abram's call has a real family setting.",
          "God does not call Abram out of nowhere.",
          "He calls a man with a father, brothers, a wife, a nephew, and a homeland.",
          "That matters because Genesis 12 will ask Abram to leave his father's house.",
          "Genesis 11 lets us feel what Abram will be called to trust God beyond.",
          "The call of faith begins inside real family history.",
        ]),
      ],
      [
        "👤 Abram",
        note([
          "Abram appears at the end of the genealogy because the whole section has been moving toward him.",
          "He is not yet called Abraham here.",
          "His name will be changed later when God confirms the covenant and gives him a new identity.",
          "At this point, he is introduced before the major promise is spoken.",
          "That helps the reader see that Abram's story has a background.",
          "He comes from a line, a father, a place, and a family.",
          "The Bible is preparing us to see God's call enter an ordinary human story.",
          "Genesis 12 will turn Abram's life into one of the most important stories in Scripture.",
        ]),
      ],
    ],
  },
  {
    chapter: 11,
    startVerse: 27,
    endVerse: 32,
    reference: "Genesis 11:27-32",
    title: "Abram's Family Stops In Haran",
    icon: "🧳",
    phrases: [
      [
        "🧾 These Are The Generations Of Terah",
        note([
          "This phrase opens a new focus in Genesis.",
          "The story is now moving from Shem's broad line to Terah's household.",
          "That matters because Abram is Terah's son.",
          "Genesis is zooming in closer and closer until Abram stands in the center of the story.",
          "The phrase generations does not only mean children.",
          "It means the family history or account that follows.",
          "Genesis uses this phrase to introduce major sections of the book.",
          "Here it prepares us for the family background behind Abram's call.",
        ]),
      ],
      [
        "👨‍👦 Abram, Nahor, And Haran",
        note([
          "These are Terah's sons and Abram's immediate family circle.",
          "The names matter because the next chapters will keep referring to this household.",
          "Nahor's family will later matter when Isaac and Jacob's wives come from the wider family line.",
          "Haran matters because he is Lot's father.",
          "Abram is not being introduced as a lonely spiritual hero.",
          "He stands inside a family with relationships, grief, and history.",
          "When God calls Abram to leave, the reader now knows there are real ties involved.",
          "Obedience will touch the people and places that shaped him.",
        ]),
      ],
      [
        "💔 Haran Died Before His Father",
        note([
          "Abram's brother Haran dies before Terah.",
          "This means Terah outlives his own son, which is a deep family grief.",
          "It also matters because Lot is Haran's son.",
          "When Abram later travels with Lot, he is traveling with a nephew who has already lost his father.",
          "Genesis is quietly giving emotional background.",
          "Abram's family story includes loss before it includes calling.",
          "That helps us read the next chapters with more tenderness.",
          "God's call often comes into families that already carry wounds.",
        ]),
      ],
      [
        "🏙️ Ur Of The Chaldees",
        note([
          "Ur of the Chaldees was a major city in ancient Mesopotamia.",
          "It was known for wealth, trade, organized city life, and pagan worship.",
          "This tells us Abram came from a real cultural world, not an empty background.",
          "He had a homeland, a family identity, and a settled place.",
          "Later Scripture connects Abram's family background with life among other gods.",
          "That makes God's call in Genesis 12 even more powerful.",
          "Abram will be called away from familiar security into a promise he cannot yet see.",
          "Faith begins in a real place before it walks into the unknown.",
        ]),
      ],
      [
        "👩 Sarai",
        note([
          "Sarai is introduced before God gives Abram the promise of descendants.",
          "That matters because she is not a side character in Abram's story.",
          "The promise of offspring will involve her body, her waiting, her pain, and eventually God's miracle.",
          "Genesis names her here so the reader knows Abram's family situation before the call begins.",
          "Sarai will later be renamed Sarah, just as Abram will become Abraham.",
          "Her story is tied to covenant promise, not just marriage background.",
          "A new reader should notice her early because the whole promise story will soon press against her barrenness.",
          "God's plan will move through this woman the text has just introduced.",
        ]),
      ],
      [
        "🚫 Sarai Was Barren",
        note([
          "This is one of the most important details in Abram's story.",
          "Barren means Sarai could not have children.",
          "That detail appears before God promises Abram descendants.",
          "So the promise begins in a situation that looks humanly impossible.",
          "Genesis wants the reader to feel that tension from the start.",
          "The chosen family line cannot continue by human strength alone.",
          "Abram's future will depend on God's power and God's word.",
          "This phrase sets up years of waiting, testing, faith, failure, and miracle.",
        ]),
      ],
      [
        "🛣️ To Go Into The Land Of Canaan",
        note([
          "Terah takes his family out of Ur with Canaan named as the destination.",
          "That matters because Canaan will become the land of promise.",
          "The family is already moving toward the place that will dominate Abram's story.",
          "A new reader might wonder why Canaan is named before Genesis 12.",
          "It shows that the journey toward the promised land has already begun in some way.",
          "But the family does not complete the journey yet.",
          "Genesis is building tension between direction and completion.",
          "They are moving toward Canaan, but they will stop short.",
        ]),
      ],
      [
        "⏸️ They Came Unto Haran, And Dwelt There",
        note([
          "Terah's family begins moving toward Canaan but stops in Haran.",
          "Haran becomes an in-between place.",
          "They have left Ur, but they have not reached Canaan.",
          "This unfinished journey matters because Genesis 12 will begin with God calling Abram to keep going.",
          "The story pauses before the next act of obedience.",
          "Abram's call will meet him in the middle of an unfinished road.",
          "Sometimes God's next word comes where a family journey has stalled.",
          "Haran is not the final destination, but it becomes the place right before the call.",
        ]),
      ],
      [
        "⚰️ Terah Died In Haran",
        note([
          "Genesis 11 ends with Terah's death in Haran.",
          "That means Abram's next chapter begins after family loss and an unfinished journey.",
          "The death of Terah closes one part of the family story.",
          "Genesis 12 will open with God's call to Abram.",
          "This order matters because calling often begins after an ending.",
          "Abram does not start with a clean, simple life.",
          "He starts with family history, grief, barrenness, movement, and delay.",
          "God's promise enters that real and unfinished place.",
        ]),
      ],
    ],
  },
];

export const GENESIS_11_20_PERSONAL_SECTIONS = [
  ...GENESIS_11_PERSONAL_REWRITE_SECTIONS,
  ...expandSplitSections(RAW_GENESIS_11_20_PERSONAL_SECTIONS).filter((section) => section.chapter !== 11),
];
