import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 17 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsSeventeenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_SEVENTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Better Is A Dry Morsel, And Quietness Therewith",
    icon: "🍞",
    underline: "Better is a dry morsel, and quietness therewith,",
    preview: "\"Morsel\" means a small plain piece of food.",
  },
  {
    verse: 1,
    noteTitle: "Than An House Full Of Sacrifices With Strife",
    icon: "🏠",
    underline: "than an house full of sacrifices with strife.",
    preview: "This does not mean the sacrifices caused the problem.",
  },
  {
    verse: 2,
    noteTitle: "A Wise Servant Shall Have Rule Over A Son That Causeth Shame",
    icon: "👤",
    underline: "A wise servant shall have rule over a son that causeth shame,",
    preview: "In this culture a servant normally ranked below a son.",
  },
  {
    verse: 2,
    noteTitle: "And Shall Have Part Of The Inheritance Among The Brethren",
    icon: "📜",
    underline: "and shall have part of the inheritance among the brethren.",
    preview: "\"Inheritance\" means a real legal share of the family estate.",
  },
  {
    verse: 3,
    noteTitle: "The Fining Pot Is For Silver, And The Furnace For Gold",
    icon: "🔥",
    underline: "The fining pot is for silver, and the furnace for gold:",
    preview: "A \"fining pot\" was a small clay vessel used to purify silver.",
  },
  {
    verse: 3,
    noteTitle: "But The LORD Trieth The Hearts",
    icon: "🔍",
    underline: "but the LORD trieth the hearts.",
    preview: "\"Trieth\" means tests closely, the same way fire tests metal.",
  },
  {
    verse: 4,
    noteTitle: "A Wicked Doer Giveth Heed To False Lips",
    icon: "👂",
    underline: "A wicked doer giveth heed to false lips;",
    preview: "\"Giveth heed\" means listens closely and pays real attention.",
  },
  {
    verse: 4,
    noteTitle: "And A Liar Giveth Ear To A Naughty Tongue",
    icon: "📛",
    underline: "and a liar giveth ear to a naughty tongue.",
    preview: "\"Naughty\" in this older English means wicked, not mischievous.",
  },
  {
    verse: 5,
    noteTitle: "Whoso Mocketh The Poor Reproacheth His Maker",
    icon: "😏",
    underline: "Whoso mocketh the poor reproacheth his Maker:",
    preview: "\"Mocketh\" means makes fun of with real contempt.",
  },
  {
    verse: 5,
    noteTitle: "And He That Is Glad At Calamities Shall Not Be Unpunished",
    icon: "💥",
    underline: "and he that is glad at calamities shall not be unpunished.",
    preview: "\"Calamities\" means disasters or serious misfortunes that fall on someone.",
  },
  {
    verse: 6,
    noteTitle: "Children's Children Are The Crown Of Old Men",
    icon: "👑",
    underline: "Children’s children are the crown of old men;",
    preview: "A \"crown\" here pictures something worn with pride and honor.",
  },
  {
    verse: 6,
    noteTitle: "And The Glory Of Children Are Their Fathers",
    icon: "🔄",
    underline: "and the glory of children are their fathers.",
    preview: "This half turns the honor in the opposite direction.",
  },
  {
    verse: 7,
    noteTitle: "Excellent Speech Becometh Not A Fool",
    icon: "👔",
    underline: "Excellent speech becometh not a fool:",
    preview: "\"Becometh\" means fits or suits, like clothing matching its wearer.",
  },
  {
    verse: 7,
    noteTitle: "Much Less Do Lying Lips A Prince",
    icon: "👑",
    underline: "much less do lying lips a prince.",
    preview: "A \"prince\" here means a ruler or someone in authority.",
  },
  {
    verse: 8,
    noteTitle: "A Gift Is As A Precious Stone In The Eyes Of Him That Hath It",
    icon: "💎",
    underline: "A gift is as a precious stone in the eyes of him that hath it:",
    preview: "\"Gift\" in Proverbs often describes a payment given to gain favor.",
  },
  {
    verse: 8,
    noteTitle: "Whithersoever It Turneth, It Prospereth",
    icon: "🧭",
    underline: "whithersoever it turneth, it prospereth.",
    preview: "This line describes how bribery often seems to work.",
  },
  {
    verse: 9,
    noteTitle: "He That Covereth A Transgression Seeketh Love",
    icon: "🤲",
    underline: "He that covereth a transgression seeketh love;",
    preview: "\"Covereth\" means chooses to overlook a wrong instead of exposing it.",
  },
  {
    verse: 9,
    noteTitle: "But He That Repeateth A Matter Separateth Very Friends",
    icon: "🔁",
    underline: "but he that repeateth a matter separateth very friends.",
    preview: "\"Repeateth a matter\" means bringing up an old offense again.",
  },
  {
    verse: 10,
    noteTitle: "A Reproof Entereth More Into A Wise Man",
    icon: "🗣️",
    underline: "A reproof entereth more into a wise man",
    preview: "\"Reproof\" means correction, a spoken warning about wrong behavior.",
  },
  {
    verse: 10,
    noteTitle: "Than An Hundred Stripes Into A Fool",
    icon: "⛓️",
    underline: "than an hundred stripes into a fool.",
    preview: "\"Stripes\" means physical blows, a harsh ancient punishment.",
  },
  {
    verse: 11,
    noteTitle: "An Evil Man Seeketh Only Rebellion",
    icon: "🎯",
    underline: "An evil man seeketh only rebellion:",
    preview: "\"Seeketh only\" means this is his main pursuit, not a lapse.",
  },
  {
    verse: 11,
    noteTitle: "Therefore A Cruel Messenger Shall Be Sent Against Him",
    icon: "📨",
    underline: "therefore a cruel messenger shall be sent against him.",
    preview: "\"Cruel messenger\" likely pictures a harsh agent of punishment.",
  },
  {
    verse: 12,
    noteTitle: "Let A Bear Robbed Of Her Whelps Meet A Man",
    icon: "🐻",
    underline: "Let a bear robbed of her whelps meet a man,",
    preview: "A bear robbed of her cubs was a known picture of raw danger.",
  },
  {
    verse: 12,
    noteTitle: "Rather Than A Fool In His Folly",
    icon: "🃏",
    underline: "rather than a fool in his folly.",
    preview: "\"Folly\" means foolish, reckless behavior acted out in the moment.",
  },
  {
    verse: 13,
    noteTitle: "Whoso Rewardeth Evil For Good",
    icon: "🔄",
    underline: "Whoso rewardeth evil for good,",
    preview: "\"Rewardeth evil for good\" means answering kindness with harm on purpose.",
  },
  {
    verse: 13,
    noteTitle: "Evil Shall Not Depart From His House",
    icon: "🏠",
    underline: "evil shall not depart from his house.",
    preview: "This warns that such betrayal invites lasting trouble in return.",
  },
  {
    verse: 14,
    noteTitle: "The Beginning Of Strife Is As When One Letteth Out Water",
    icon: "💧",
    underline: "The beginning of strife is as when one letteth out water:",
    preview: "\"Letteth out water\" pictures breaking a small hole in a dam.",
  },
  {
    verse: 14,
    noteTitle: "Therefore Leave Off Contention, Before It Be Meddled With",
    icon: "🚪",
    underline: "therefore leave off contention, before it be meddled with.",
    preview: "\"Meddled with\" means stirred up further or gotten deeply involved in.",
  },
  {
    verse: 15,
    noteTitle: "He That Justifieth The Wicked, And He That Condemneth The Just",
    icon: "⚖️",
    underline: "He that justifieth the wicked, and he that condemneth the just,",
    preview: "\"Justifieth\" means declares innocent, a term from the courtroom.",
  },
  {
    verse: 15,
    noteTitle: "Even They Both Are Abomination To The LORD",
    icon: "💔",
    underline: "even they both are abomination to the LORD.",
    preview: "\"Abomination\" means something God finds deeply offensive.",
  },
  {
    verse: 16,
    noteTitle: "Wherefore Is There A Price In The Hand Of A Fool To Get Wisdom",
    icon: "💰",
    underline: "Wherefore is there a price in the hand of a fool to get wisdom,",
    preview: "\"Price\" here likely means money set aside to pay a teacher.",
  },
  {
    verse: 16,
    noteTitle: "Seeing He Hath No Heart To It",
    icon: "🫀",
    underline: "seeing he hath no heart to it?",
    preview: "\"No heart to it\" means no real desire to learn.",
  },
  {
    verse: 17,
    noteTitle: "A Friend Loveth At All Times",
    icon: "⏳",
    underline: "A friend loveth at all times,",
    preview: "\"At all times\" rules out love that comes and goes.",
  },
  {
    verse: 17,
    noteTitle: "And A Brother Is Born For Adversity",
    icon: "🌧️",
    underline: "and a brother is born for adversity.",
    preview: "\"Adversity\" means hardship, trouble, or difficult circumstances.",
  },
  {
    verse: 18,
    noteTitle: "A Man Void Of Understanding Striketh Hands",
    icon: "🤝",
    underline: "A man void of understanding striketh hands,",
    preview: "\"Striketh hands\" was an ancient gesture sealing a financial agreement.",
  },
  {
    verse: 18,
    noteTitle: "And Becometh Surety In The Presence Of His Friend",
    icon: "📜",
    underline: "and becometh surety in the presence of his friend.",
    preview: "\"Surety\" means becoming legally responsible for another person's debt.",
  },
  {
    verse: 19,
    noteTitle: "He Loveth Transgression That Loveth Strife",
    icon: "⚖️",
    underline: "He loveth transgression that loveth strife:",
    preview: "\"Transgression\" means sin, a real crossing of a moral line.",
  },
  {
    verse: 19,
    noteTitle: "And He That Exalteth His Gate Seeketh Destruction",
    icon: "🚪",
    underline: "and he that exalteth his gate seeketh destruction.",
    preview: "\"Gate\" likely pictures a grand entrance built to display wealth.",
  },
  {
    verse: 20,
    noteTitle: "He That Hath A Froward Heart Findeth No Good",
    icon: "😠",
    underline: "He that hath a froward heart findeth no good:",
    preview: "\"Froward\" means stubbornly contrary, twisted away from what is right.",
  },
  {
    verse: 20,
    noteTitle: "And He That Hath A Perverse Tongue Falleth Into Mischief",
    icon: "🌀",
    underline: "and he that hath a perverse tongue falleth into mischief.",
    preview: "\"Perverse\" means twisted away from truth and honesty.",
  },
  {
    verse: 21,
    noteTitle: "He That Begetteth A Fool Doeth It To His Sorrow",
    icon: "👶",
    underline: "He that begetteth a fool doeth it to his sorrow:",
    preview: "\"Begetteth\" means fathers or brings a child into the world.",
  },
  {
    verse: 21,
    noteTitle: "And The Father Of A Fool Hath No Joy",
    icon: "🔁",
    underline: "and the father of a fool hath no joy.",
    preview: "This half restates the same idea from a different angle.",
  },
  {
    verse: 22,
    noteTitle: "A Merry Heart Doeth Good Like A Medicine",
    icon: "💊",
    underline: "A merry heart doeth good like a medicine:",
    preview: "This verse compares real joy directly to a healing medicine.",
  },
  {
    verse: 22,
    noteTitle: "But A Broken Spirit Drieth The Bones",
    icon: "💔",
    underline: "but a broken spirit drieth the bones.",
    preview: "\"Broken spirit\" means deep discouragement or crushed hope.",
  },
  {
    verse: 23,
    noteTitle: "A Wicked Man Taketh A Gift Out Of The Bosom",
    icon: "👘",
    underline: "A wicked man taketh a gift out of the bosom",
    preview: "\"Bosom\" here means the fold of a garment used as a pocket.",
  },
  {
    verse: 23,
    noteTitle: "To Pervert The Ways Of Judgment",
    icon: "🌀",
    underline: "to pervert the ways of judgment.",
    preview: "\"Pervert\" means twist or bend away from what is fair.",
  },
  {
    verse: 24,
    noteTitle: "Wisdom Is Before Him That Hath Understanding",
    icon: "👀",
    underline: "Wisdom is before him that hath understanding;",
    preview: "\"Before him\" pictures wisdom staying in clear, close view.",
  },
  {
    verse: 24,
    noteTitle: "But The Eyes Of A Fool Are In The Ends Of The Earth",
    icon: "🌍",
    underline: "but the eyes of a fool are in the ends of the earth.",
    preview: "\"Ends of the earth\" pictures attention scattered on faraway things.",
  },
  {
    verse: 25,
    noteTitle: "A Foolish Son Is A Grief To His Father",
    icon: "😢",
    underline: "A foolish son is a grief to his father,",
    preview: "\"Grief\" means deep, lasting sorrow, not a passing annoyance.",
  },
  {
    verse: 25,
    noteTitle: "And Bitterness To Her That Bare Him",
    icon: "👶",
    underline: "and bitterness to her that bare him.",
    preview: "\"Bare him\" means gave birth to him, naming the mother.",
  },
  {
    verse: 26,
    noteTitle: "Also To Punish The Just Is Not Good",
    icon: "⚖️",
    underline: "Also to punish the just is not good,",
    preview: "\"The just\" means people who have actually done what is right.",
  },
  {
    verse: 26,
    noteTitle: "Nor To Strike Princes For Equity",
    icon: "⚖️",
    underline: "nor to strike princes for equity.",
    preview: "\"Equity\" here means fairness, doing what is right and just.",
  },
  {
    verse: 27,
    noteTitle: "He That Hath Knowledge Spareth His Words",
    icon: "🤐",
    underline: "He that hath knowledge spareth his words:",
    preview: "\"Spareth his words\" means holds back from speaking more than necessary.",
  },
  {
    verse: 27,
    noteTitle: "And A Man Of Understanding Is Of An Excellent Spirit",
    icon: "🕊️",
    underline: "and a man of understanding is of an excellent spirit.",
    preview: "\"Excellent spirit\" means a calm, steady, well governed disposition.",
  },
  {
    verse: 28,
    noteTitle: "Even A Fool, When He Holdeth His Peace, Is Counted Wise",
    icon: "🤫",
    underline: "Even a fool, when he holdeth his peace, is counted wise:",
    preview: "\"Holdeth his peace\" means stays silent instead of speaking.",
  },
  {
    verse: 28,
    noteTitle: "And He That Shutteth His Lips Is Esteemed A Man Of Understanding",
    icon: "🔒",
    underline: "and he that shutteth his lips is esteemed a man of understanding.",
    preview: "\"Shutteth his lips\" repeats the same picture of chosen silence.",
  },
];
