type Verse = {
  number: number;
  text: string;
};

type NotesSection = {
  range: string;
  heading: string;
  verses: Verse[];
  body: string[];
};

type ChapterNotes = {
  title: string;
  intro: string[];
  flow: string[];
  sections: NotesSection[];
  takeaway: string[];
};

function renderVerseBlock(verses: Verse[]) {
  return verses.map((verse) => `> **${verse.number}** ${verse.text}`).join("\n>\n");
}

function renderNotes(chapter: number, notes: ChapterNotes) {
  return `# ${notes.title}

${notes.intro.join("\n\n")}

## 📍 The Chapter Flow

${notes.flow.map((item) => `- ${item}`).join("\n")}

${notes.sections
  .map(
    (section) => `## 📖 Proverbs ${chapter}:${section.range}

${renderVerseBlock(section.verses)}

## ${section.heading}

${section.body.join("\n\n")}`,
  )
  .join("\n\n")}

## 💡 The Bigger Takeaway

${notes.takeaway.join("\n\n")}
`;
}

const PROVERBS_FOUR: ChapterNotes = {
  title: "🔥 Wisdom Handed Down",
  intro: [
    "Proverbs 4 feels like a family moment.",
    "Solomon is not only speaking as a king. He is speaking as a son who remembers being taught, and as a father who now has to pass that wisdom forward.",
    "That gives this chapter a different weight.",
    "Wisdom is not treated like a private opinion Solomon invented. It is an inheritance. It moved from father to son, from one generation to the next, and now Solomon is trying to place it into the heart of his own child.",
    "The chapter keeps circling around one big idea: wisdom must be received, guarded, and walked out.",
    "It is not enough to admire wisdom. You have to hold it. You have to keep it in front of your eyes. You have to guard your heart before your feet carry you somewhere destructive.",
  ],
  flow: [
    "👨‍👦 Verses 1-4: A father remembers being taught",
    "💎 Verses 5-9: Get wisdom and do not let her go",
    "🛣️ Verses 10-13: Wisdom leads in right paths",
    "⚠️ Verses 14-19: Avoid the path of the wicked",
    "❤️ Verses 20-23: Guard the heart because life flows from it",
    "👀 Verses 24-27: Watch your mouth, eyes, and steps",
  ],
  sections: [
    {
      range: "1-4",
      heading: "👨‍👦 A Father Who Was Once A Son",
      verses: [
        { number: 1, text: "Hear, ye children, the instruction of a father, and attend to know understanding." },
        { number: 2, text: "For I give you good doctrine, forsake ye not my law." },
        { number: 3, text: "For I was my father's son, tender and only beloved in the sight of my mother." },
        { number: 4, text: "He taught me also, and said unto me, Let thine heart retain my words: keep my commandments, and live." },
      ],
      body: [
        "Solomon begins by calling children to listen.",
        "This is not casual advice. This is a father gathering the next generation and saying, Pay attention, because what I am giving you can shape your life.",
        "Then Solomon does something important. He remembers that he was once a son too.",
        "Before Solomon became king, before he became famous for wisdom, before people traveled to hear him speak, he was a child receiving instruction.",
        "That means wisdom did not begin with him.",
        "He received it before he taught it.",
        "This matters because one of the marks of wisdom is humility. A wise person knows they did not start as the expert.",
        "Solomon is showing his son that wisdom is an inheritance, but it still has to be personally retained.",
        "David could teach Solomon. Solomon could teach his son. But the son still had to let his heart retain the words.",
        "Wisdom can be handed to you, but it cannot be kept for you.",
      ],
    },
    {
      range: "5-9",
      heading: "💎 Get Wisdom",
      verses: [
        { number: 5, text: "Get wisdom, get understanding: forget it not; neither decline from the words of my mouth." },
        { number: 6, text: "Forsake her not, and she shall preserve thee: love her, and she shall keep thee." },
        { number: 7, text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding." },
        { number: 8, text: "Exalt her, and she shall promote thee: she shall bring thee to honour, when thou dost embrace her." },
        { number: 9, text: "She shall give to thine head an ornament of grace: a crown of glory shall she deliver to thee." },
      ],
      body: [
        "The command is repeated because the point is urgent: get wisdom.",
        "Solomon does not say, Get attention. Get power. Get comfort. Get applause.",
        "He says wisdom is the principal thing.",
        "Principal means first, chief, central, the thing that gives shape to everything else.",
        "This is important because a person can get many things and still not know how to live.",
        "You can get money and mishandle it. You can get influence and abuse it. You can get opportunity and waste it.",
        "Wisdom teaches you how to carry the things you get.",
        "Solomon also speaks of wisdom like a woman who protects, keeps, promotes, and honors the one who embraces her.",
        "That picture matters. Wisdom is not cold information sitting on a shelf. Wisdom is something to love, hold, and refuse to forsake.",
        "The son is being taught to value wisdom before life teaches him the cost of foolishness.",
      ],
    },
    {
      range: "10-13",
      heading: "🛣️ Wisdom Gives You A Path",
      verses: [
        { number: 10, text: "Hear, O my son, and receive my sayings; and the years of thy life shall be many." },
        { number: 11, text: "I have taught thee in the way of wisdom; I have led thee in right paths." },
        { number: 12, text: "When thou goest, thy steps shall not be straitened; and when thou runnest, thou shalt not stumble." },
        { number: 13, text: "Take fast hold of instruction; let her not go: keep her; for she is thy life." },
      ],
      body: [
        "Wisdom is not only something you think about.",
        "Wisdom becomes a way.",
        "Solomon says he has taught his son in the way of wisdom and led him in right paths.",
        "That means wisdom gives direction. It does not merely tell you what is true. It shows you where to walk.",
        "Verse 12 pictures movement without being trapped or stumbling.",
        "This does not mean wise people never face difficulty. It means wisdom keeps a person from many self-made traps.",
        "There is a difference between suffering because life is broken and stumbling because you ignored instruction.",
        "Solomon wants his son to hold instruction tightly because instruction is life.",
        "The warning is gentle but serious: if you let go of wisdom, you are not letting go of a small thing.",
        "You are letting go of something that protects your life.",
      ],
    },
    {
      range: "14-19",
      heading: "⚠️ Do Not Even Enter That Path",
      verses: [
        { number: 14, text: "Enter not into the path of the wicked, and go not in the way of evil men." },
        { number: 15, text: "Avoid it, pass not by it, turn from it, and pass away." },
        { number: 16, text: "For they sleep not, except they have done mischief; and their sleep is taken away, unless they cause some to fall." },
        { number: 17, text: "For they eat the bread of wickedness, and drink the wine of violence." },
        { number: 18, text: "But the path of the just is as the shining light, that shineth more and more unto the perfect day." },
        { number: 19, text: "The way of the wicked is as darkness: they know not at what they stumble." },
      ],
      body: [
        "Solomon does not tell his son to test the path of the wicked.",
        "He says avoid it.",
        "Pass not by it.",
        "Turn from it.",
        "Pass away.",
        "The repetition is the lesson. Some paths are not meant to be explored. They are meant to be avoided.",
        "The wicked are described as people so committed to evil that mischief becomes their food and violence becomes their drink.",
        "That is a picture of appetite. They are not merely slipping. They are feeding on what destroys.",
        "Then Solomon contrasts two roads.",
        "The path of the just is like shining light. It grows clearer as it goes.",
        "The way of the wicked is darkness. They stumble and do not even know what tripped them.",
        "Wisdom teaches you to ask not only where a path begins, but where it gets darker as it goes.",
      ],
    },
    {
      range: "20-23",
      heading: "❤️ Guard The Source",
      verses: [
        { number: 20, text: "My son, attend to my words; incline thine ear unto my sayings." },
        { number: 21, text: "Let them not depart from thine eyes; keep them in the midst of thine heart." },
        { number: 22, text: "For they are life unto those that find them, and health to all their flesh." },
        { number: 23, text: "Keep thy heart with all diligence; for out of it are the issues of life." },
      ],
      body: [
        "This is one of the most important sections in Proverbs.",
        "Solomon moves from ears to eyes to heart.",
        "Listen to wisdom. Keep it in sight. Store it in the heart.",
        "Then he says to guard the heart with all diligence.",
        "The heart is not just feelings. In Proverbs, the heart is the control center of a person.",
        "Desires, thoughts, decisions, motives, and direction flow from it.",
        "That is why the heart must be guarded.",
        "If the spring is polluted, the stream will be polluted.",
        "If the heart is unguarded, the life flowing out of it becomes unstable.",
        "Solomon is teaching his son to protect the source before the damage shows up downstream.",
      ],
    },
    {
      range: "24-27",
      heading: "👀 Mouth, Eyes, And Feet",
      verses: [
        { number: 24, text: "Put away from thee a froward mouth, and perverse lips put far from thee." },
        { number: 25, text: "Let thine eyes look right on, and let thine eyelids look straight before thee." },
        { number: 26, text: "Ponder the path of thy feet, and let all thy ways be established." },
        { number: 27, text: "Turn not to the right hand nor to the left: remove thy foot from evil." },
      ],
      body: [
        "After telling his son to guard the heart, Solomon immediately talks about the body.",
        "The mouth, eyes, and feet reveal what is happening inside.",
        "Crooked speech shows a crooked inner direction.",
        "Wandering eyes show an unfocused heart.",
        "Careless feet show an unexamined path.",
        "Wisdom is practical. It does not stay vague.",
        "Solomon says put away perverse speech, look straight ahead, ponder the path, and remove your foot from evil.",
        "This is how guarding the heart becomes visible.",
        "You guard the heart by watching what you say, what you look toward, and where you are walking.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 4 teaches that wisdom is an inheritance, but it must become personal.",
    "You can be taught wisdom and still fail to keep it.",
    "You can hear the right words and still walk the wrong path.",
    "So Solomon says to get wisdom, hold instruction, avoid wicked paths, guard the heart, and watch the direction of your life.",
    "The chapter is a father pleading with his son to protect the source early, before the stream of life gets polluted.",
  ],
};

const PROVERBS_FIVE: ChapterNotes = {
  title: "⚠️ The Sweet Voice That Turns Bitter",
  intro: [
    "Proverbs 5 moves into a dangerous room.",
    "Solomon is still speaking as a father, but now the warning is about desire, temptation, and sexual sin.",
    "The chapter is honest. Temptation does not always look ugly at first. It can sound sweet. It can feel smooth. It can offer escape, attention, secrecy, and pleasure without showing the cost up front.",
    "That is why Solomon teaches his son to see the end before he takes the first step.",
    "This chapter is not trying to make desire evil. It is trying to put desire under wisdom.",
    "It warns against the destructive path of adultery and calls the son toward covenant faithfulness, delight, and the fear of the Lord.",
  ],
  flow: [
    "👂 Verses 1-2: Listen so discretion can guard you",
    "🍯 Verses 3-6: Temptation sounds sweet but ends bitter",
    "🚪 Verses 7-14: Stay far from the door before regret comes",
    "💧 Verses 15-20: Rejoice in covenant love",
    "👀 Verses 21-23: God sees every path and sin becomes a trap",
  ],
  sections: [
    {
      range: "1-2",
      heading: "👂 Wisdom Before Desire Speaks",
      verses: [
        { number: 1, text: "My son, attend unto my wisdom, and bow thine ear to my understanding:" },
        { number: 2, text: "That thou mayest regard discretion, and that thy lips may keep knowledge." },
      ],
      body: [
        "Solomon begins by calling his son to listen before temptation starts talking.",
        "That timing matters.",
        "If wisdom only enters after desire is already loud, the heart is already in danger.",
        "Discretion is the ability to recognize what is happening and choose carefully.",
        "Knowledge kept on the lips means the son is able to speak from truth instead of being carried by impulse.",
        "Temptation often wins when a person has no prepared wisdom.",
        "Solomon wants his son trained before the moment arrives.",
      ],
    },
    {
      range: "3-6",
      heading: "🍯 Sweet At First, Bitter At The End",
      verses: [
        { number: 3, text: "For the lips of a strange woman drop as an honeycomb, and her mouth is smoother than oil:" },
        { number: 4, text: "But her end is bitter as wormwood, sharp as a twoedged sword." },
        { number: 5, text: "Her feet go down to death; her steps take hold on hell." },
        { number: 6, text: "Lest thou shouldest ponder the path of life, her ways are moveable, that thou canst not know them." },
      ],
      body: [
        "The warning begins with sweetness.",
        "The lips drop like honey. The mouth is smoother than oil.",
        "Solomon is honest about the appeal. Sin rarely introduces itself as death.",
        "It usually introduces itself as pleasure, comfort, attention, or excitement.",
        "But verse 4 turns the picture.",
        "The end is bitter as wormwood and sharp as a twoedged sword.",
        "This is the wisdom of seeing the ending before trusting the beginning.",
        "Temptation wants the son to focus on the honey and ignore the blade.",
        "Her ways are moveable, unstable, hard to track. That means this path is not clear, steady, or safe.",
        "The person who follows it loses the ability to ponder the path of life clearly.",
      ],
    },
    {
      range: "7-14",
      heading: "🚪 Stay Far From The Door",
      verses: [
        { number: 7, text: "Hear me now therefore, O ye children, and depart not from the words of my mouth." },
        { number: 8, text: "Remove thy way far from her, and come not nigh the door of her house:" },
        { number: 9, text: "Lest thou give thine honour unto others, and thy years unto the cruel:" },
        { number: 10, text: "Lest strangers be filled with thy wealth; and thy labours be in the house of a stranger;" },
        { number: 11, text: "And thou mourn at the last, when thy flesh and thy body are consumed," },
        { number: 12, text: "And say, How have I hated instruction, and my heart despised reproof;" },
        { number: 13, text: "And have not obeyed the voice of my teachers, nor inclined mine ear to them that instructed me!" },
        { number: 14, text: "I was almost in all evil in the midst of the congregation and assembly." },
      ],
      body: [
        "Solomon does not tell his son to manage the temptation from close range.",
        "He says remove your way far from her.",
        "Do not come near the door.",
        "That is practical wisdom. Some doors are dangerous before they open.",
        "The warning is not only about one sinful act. It is about what the path costs.",
        "Honor is given away. Years are handed to the cruel. Wealth and labor are consumed by strangers.",
        "Then comes the most painful part: regret.",
        "The person says, How have I hated instruction?",
        "That is the sound of someone finally seeing what wisdom had been saying all along.",
        "Solomon wants his son to listen before the mourning, not after it.",
      ],
    },
    {
      range: "15-20",
      heading: "💧 Desire Within Covenant",
      verses: [
        { number: 15, text: "Drink waters out of thine own cistern, and running waters out of thine own well." },
        { number: 16, text: "Let thy fountains be dispersed abroad, and rivers of waters in the streets." },
        { number: 17, text: "Let them be only thine own, and not strangers' with thee." },
        { number: 18, text: "Let thy fountain be blessed: and rejoice with the wife of thy youth." },
        { number: 19, text: "Let her be as the loving hind and pleasant roe; let her breasts satisfy thee at all times; and be thou ravished always with her love." },
        { number: 20, text: "And why wilt thou, my son, be ravished with a strange woman, and embrace the bosom of a stranger?" },
      ],
      body: [
        "This section shows that Proverbs is not anti-desire.",
        "Solomon does not only say no to adultery. He says yes to faithfulness.",
        "The image of water points to satisfaction, refreshment, and rightful delight.",
        "Drink from your own cistern. Rejoice with the wife of your youth.",
        "This is covenant language.",
        "Desire is meant to be protected, not scattered into the streets.",
        "Solomon is teaching that faithfulness is not a dry prison. It is a protected fountain.",
        "Sin promises more, but it actually steals the ability to enjoy what is good rightly.",
        "The question in verse 20 is meant to wake the son up: why be captivated by a stranger when God has given a faithful path for love?",
      ],
    },
    {
      range: "21-23",
      heading: "👀 God Sees The Path",
      verses: [
        { number: 21, text: "For the ways of man are before the eyes of the LORD, and he pondereth all his goings." },
        { number: 22, text: "His own iniquities shall take the wicked himself, and he shall be holden with the cords of his sins." },
        { number: 23, text: "He shall die without instruction; and in the greatness of his folly he shall go astray." },
      ],
      body: [
        "The chapter ends by bringing God into the hidden places.",
        "The ways of man are before the eyes of the Lord.",
        "Secret sin is not secret to God.",
        "He ponders all a person's goings.",
        "Then Solomon shows how sin traps the sinner. His own iniquities take him. He is held by the cords of his sins.",
        "That is a powerful image because sin often begins by promising freedom.",
        "But unrepented sin becomes a rope.",
        "It tightens. It holds. It leads a person astray.",
        "The answer is not less instruction. The answer is receiving wisdom before folly grows strong.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 5 teaches the wisdom of seeing the end before the beginning seduces you.",
    "Temptation can sound sweet and still end bitter.",
    "Solomon calls his son to stay far from destructive doors, rejoice in covenant faithfulness, and remember that God sees every path.",
    "The chapter does not kill desire. It teaches desire where life is found.",
  ],
};

const PROVERBS_SIX: ChapterNotes = {
  title: "🧯 Wisdom For Everyday Danger",
  intro: [
    "Proverbs 6 gathers several dangers that can quietly damage a life.",
    "This chapter is practical and direct. It warns about careless promises, laziness, wicked schemes, things the Lord hates, and sexual sin.",
    "At first, these topics may feel separate.",
    "But they belong together because all of them show what happens when a person refuses disciplined wisdom.",
    "Words can trap you. Sleep can waste a season. A crooked heart can sow harm. Desire can burn down a life.",
    "Solomon is teaching his son to take ordinary decisions seriously before they become extraordinary consequences.",
  ],
  flow: [
    "🤝 Verses 1-5: Do not stay trapped by reckless surety",
    "🐜 Verses 6-11: Learn diligence from the ant",
    "🕵️ Verses 12-15: A wicked person spreads corruption",
    "🚫 Verses 16-19: Seven things the Lord hates",
    "💡 Verses 20-24: Commandment is a lamp and law is light",
    "🔥 Verses 25-35: Adultery is fire that burns",
  ],
  sections: [
    {
      range: "1-5",
      heading: "🤝 When Your Words Trap You",
      verses: [
        { number: 1, text: "My son, if thou be surety for thy friend, if thou hast stricken thy hand with a stranger," },
        { number: 2, text: "Thou art snared with the words of thy mouth, thou art taken with the words of thy mouth." },
        { number: 3, text: "Do this now, my son, and deliver thyself, when thou art come into the hand of thy friend; go, humble thyself, and make sure thy friend." },
        { number: 4, text: "Give not sleep to thine eyes, nor slumber to thine eyelids." },
        { number: 5, text: "Deliver thyself as a roe from the hand of the hunter, and as a bird from the hand of the fowler." },
      ],
      body: [
        "Solomon begins with surety, a financial pledge that makes you responsible for someone else's debt.",
        "The point is not that generosity is bad.",
        "The warning is against reckless obligation.",
        "A person can be trapped by their own words.",
        "That is why Solomon says to move quickly, humble yourself, and get free.",
        "This is wisdom for anyone who has agreed to something without thinking through the cost.",
        "Do not let pride keep you trapped.",
        "If your mouth has created danger, humility may be the first step toward deliverance.",
      ],
    },
    {
      range: "6-11",
      heading: "🐜 Consider The Ant",
      verses: [
        { number: 6, text: "Go to the ant, thou sluggard; consider her ways, and be wise:" },
        { number: 7, text: "Which having no guide, overseer, or ruler," },
        { number: 8, text: "Provideth her meat in the summer, and gathereth her food in the harvest." },
        { number: 9, text: "How long wilt thou sleep, O sluggard? when wilt thou arise out of thy sleep?" },
        { number: 10, text: "Yet a little sleep, a little slumber, a little folding of the hands to sleep:" },
        { number: 11, text: "So shall thy poverty come as one that travelleth, and thy want as an armed man." },
      ],
      body: [
        "The ant becomes a teacher.",
        "That is humbling.",
        "Solomon tells the lazy person to learn from a small creature that works without needing constant supervision.",
        "The ant understands seasons.",
        "It gathers in harvest because harvest does not last forever.",
        "Laziness often feels small in the moment: a little sleep, a little slumber, a little folding of the hands.",
        "But small delay can become large loss.",
        "Poverty is pictured like a traveler arriving, then like an armed man overpowering.",
        "Wisdom learns to act in the right season before need becomes a crisis.",
      ],
    },
    {
      range: "12-19",
      heading: "🚫 A Crooked Life God Hates",
      verses: [
        { number: 12, text: "A naughty person, a wicked man, walketh with a froward mouth." },
        { number: 13, text: "He winketh with his eyes, he speaketh with his feet, he teacheth with his fingers;" },
        { number: 14, text: "Frowardness is in his heart, he deviseth mischief continually; he soweth discord." },
        { number: 15, text: "Therefore shall his calamity come suddenly; suddenly shall he be broken without remedy." },
        { number: 16, text: "These six things doth the LORD hate: yea, seven are an abomination unto him:" },
        { number: 17, text: "A proud look, a lying tongue, and hands that shed innocent blood," },
        { number: 18, text: "An heart that deviseth wicked imaginations, feet that be swift in running to mischief," },
        { number: 19, text: "A false witness that speaketh lies, and he that soweth discord among brethren." },
      ],
      body: [
        "This section describes a person whose whole life has become crooked.",
        "The mouth, eyes, feet, fingers, and heart are all involved.",
        "Sin is not only in one action. It has become a pattern.",
        "The person devises mischief and sows discord.",
        "Then Solomon lists seven things the Lord hates.",
        "This list shows that God is not only concerned with private spirituality.",
        "He hates pride, lies, violence, wicked planning, eager participation in evil, false witness, and division among brothers.",
        "The final item matters deeply: sowing discord.",
        "God cares about how people damage community.",
        "Wisdom does not merely avoid scandal. Wisdom refuses to become a person who spreads corruption.",
      ],
    },
    {
      range: "20-24",
      heading: "💡 A Lamp For The Dark",
      verses: [
        { number: 20, text: "My son, keep thy father's commandment, and forsake not the law of thy mother:" },
        { number: 21, text: "Bind them continually upon thine heart, and tie them about thy neck." },
        { number: 22, text: "When thou goest, it shall lead thee; when thou sleepest, it shall keep thee; and when thou awakest, it shall talk with thee." },
        { number: 23, text: "For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life:" },
        { number: 24, text: "To keep thee from the evil woman, from the flattery of the tongue of a strange woman." },
      ],
      body: [
        "Solomon returns to parental instruction.",
        "The father's commandment and mother's law are to be bound to the heart and neck.",
        "That means wisdom should be internal and visible.",
        "Verse 22 shows wisdom as a companion.",
        "It leads when you go. It keeps when you sleep. It talks when you awake.",
        "This is why instruction matters. It stays with you when the teacher is not physically present.",
        "The commandment is a lamp and the law is light.",
        "Reproofs of instruction are the way of life.",
        "Correction may feel uncomfortable, but it keeps a person from darker roads.",
      ],
    },
    {
      range: "25-35",
      heading: "🔥 You Cannot Carry Fire And Stay Unburned",
      verses: [
        { number: 25, text: "Lust not after her beauty in thine heart; neither let her take thee with her eyelids." },
        { number: 26, text: "For by means of a whorish woman a man is brought to a piece of bread: and the adulteress will hunt for the precious life." },
        { number: 27, text: "Can a man take fire in his bosom, and his clothes not be burned?" },
        { number: 28, text: "Can one go upon hot coals, and his feet not be burned?" },
        { number: 29, text: "So he that goeth in to his neighbour's wife; whosoever toucheth her shall not be innocent." },
        { number: 30, text: "Men do not despise a thief, if he steal to satisfy his soul when he is hungry;" },
        { number: 31, text: "But if he be found, he shall restore sevenfold; he shall give all the substance of his house." },
        { number: 32, text: "But whoso committeth adultery with a woman lacketh understanding: he that doeth it destroyeth his own soul." },
        { number: 33, text: "A wound and dishonour shall he get; and his reproach shall not be wiped away." },
        { number: 34, text: "For jealousy is the rage of a man: therefore he will not spare in the day of vengeance." },
        { number: 35, text: "He will not regard any ransom; neither will he rest content, though thou givest many gifts." },
      ],
      body: [
        "Solomon returns to sexual temptation, but now he uses the image of fire.",
        "Can a man carry fire against his chest and not be burned?",
        "Can a person walk on hot coals and not burn his feet?",
        "The answer is obvious.",
        "Some sins cannot be touched safely.",
        "Adultery is not treated as a small private mistake. It destroys the soul, wounds honor, and creates consequences that money cannot easily repair.",
        "Solomon also compares adultery with theft.",
        "Even theft from hunger still requires repayment. But adultery brings a deeper devastation because it betrays covenant, trust, and another household.",
        "Wisdom tells the truth: fire burns, even when it looks beautiful.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 6 teaches that danger can enter through ordinary doors: careless promises, laziness, crooked speech, hidden pride, and unguarded desire.",
    "The wise person pays attention before consequences become loud.",
    "Solomon is forming a son who acts quickly when trapped, works diligently in season, refuses crookedness, keeps instruction close, and will not play with fire.",
  ],
};

const PROVERBS_SEVEN: ChapterNotes = {
  title: "🌙 The Night Walk Toward A Trap",
  intro: [
    "Proverbs 7 reads almost like a scene from a story.",
    "Solomon looks through a window and sees a young man moving through the street at night.",
    "The young man is not forced. He is walking near danger. He is in the wrong place, at the wrong time, with an unguarded heart.",
    "Then temptation meets him.",
    "This chapter is cinematic because Solomon wants the reader to see the path before the fall.",
    "The tragedy begins long before the final decision. It begins with being simple, drifting near the corner, and walking into darkness without wisdom close.",
  ],
  flow: [
    "📜 Verses 1-5: Keep wisdom close like family",
    "🪟 Verses 6-9: Solomon sees a young man without understanding",
    "🎭 Verses 10-20: Temptation dresses itself, speaks religiously, and promises secrecy",
    "🪤 Verses 21-23: Flattery leads him like an animal to slaughter",
    "📣 Verses 24-27: Listen now, because her house goes down to death",
  ],
  sections: [
    {
      range: "1-5",
      heading: "📜 Wisdom Close Enough To Protect",
      verses: [
        { number: 1, text: "My son, keep my words, and lay up my commandments with thee." },
        { number: 2, text: "Keep my commandments, and live; and my law as the apple of thine eye." },
        { number: 3, text: "Bind them upon thy fingers, write them upon the table of thine heart." },
        { number: 4, text: "Say unto wisdom, Thou art my sister; and call understanding thy kinswoman:" },
        { number: 5, text: "That they may keep thee from the strange woman, from the stranger which flattereth with her words." },
      ],
      body: [
        "The chapter opens with protection.",
        "Keep my words. Lay up my commandments. Guard the law like the apple of your eye.",
        "The apple of the eye refers to something precious and protected.",
        "Solomon wants wisdom that close.",
        "He says to bind wisdom on the fingers and write it on the heart.",
        "Then he uses family language: call wisdom your sister and understanding your kinswoman.",
        "That means wisdom should not be a stranger.",
        "It should feel close, familiar, trusted, and present.",
        "Why? Because flattery is coming.",
        "If wisdom is distant, temptation will sound like the nearest voice.",
      ],
    },
    {
      range: "6-9",
      heading: "🪟 The Young Man Without Understanding",
      verses: [
        { number: 6, text: "For at the window of my house I looked through my casement," },
        { number: 7, text: "And beheld among the simple ones, I discerned among the youths, a young man void of understanding," },
        { number: 8, text: "Passing through the street near her corner; and he went the way to her house," },
        { number: 9, text: "In the twilight, in the evening, in the black and dark night:" },
      ],
      body: [
        "Solomon now tells what he saw.",
        "A young man void of understanding is walking near her corner.",
        "That phrase matters.",
        "He is not yet inside the house. He is near the corner.",
        "Many falls begin with nearness.",
        "The young man is moving in the direction of danger before the temptation speaks.",
        "The time also matters: twilight, evening, black and dark night.",
        "Darkness is not only the setting. It pictures the moral atmosphere.",
        "He is walking where wisdom has already told him not to go.",
      ],
    },
    {
      range: "10-20",
      heading: "🎭 Temptation Knows How To Talk",
      verses: [
        { number: 10, text: "And, behold, there met him a woman with the attire of an harlot, and subtil of heart." },
        { number: 11, text: "(She is loud and stubborn; her feet abide not in her house:" },
        { number: 12, text: "Now is she without, now in the streets, and lieth in wait at every corner.)" },
        { number: 13, text: "So she caught him, and kissed him, and with an impudent face said unto him," },
        { number: 14, text: "I have peace offerings with me; this day have I payed my vows." },
        { number: 15, text: "Therefore came I forth to meet thee, diligently to seek thy face, and I have found thee." },
        { number: 16, text: "I have decked my bed with coverings of tapestry, with carved works, with fine linen of Egypt." },
        { number: 17, text: "I have perfumed my bed with myrrh, aloes, and cinnamon." },
        { number: 18, text: "Come, let us take our fill of love until the morning: let us solace ourselves with loves." },
        { number: 19, text: "For the goodman is not at home, he is gone a long journey:" },
        { number: 20, text: "He hath taken a bag of money with him, and will come home at the day appointed." },
      ],
      body: [
        "Temptation is not presented as random.",
        "It is prepared.",
        "She has attire, timing, words, confidence, religion, beauty, fragrance, and a promise of secrecy.",
        "She even mentions peace offerings and vows.",
        "That is chilling because sin can borrow religious language to make itself feel safe.",
        "Then she personalizes the temptation: I came to meet thee. I sought thy face. I found thee.",
        "Temptation often makes a person feel chosen.",
        "She describes the bed, the coverings, the perfume, the night, and the absent husband.",
        "Everything is designed to make the moment feel irresistible and consequence-free.",
        "But wisdom sees what the young man does not see.",
      ],
    },
    {
      range: "21-23",
      heading: "🪤 The Trap Springs",
      verses: [
        { number: 21, text: "With her much fair speech she caused him to yield, with the flattering of her lips she forced him." },
        { number: 22, text: "He goeth after her straightway, as an ox goeth to the slaughter, or as a fool to the correction of the stocks;" },
        { number: 23, text: "Till a dart strike through his liver; as a bird hasteth to the snare, and knoweth not that it is for his life." },
      ],
      body: [
        "The young man yields through fair speech and flattery.",
        "Words move him before the act destroys him.",
        "Solomon compares him to an ox going to slaughter, a fool to punishment, and a bird rushing into a snare.",
        "These images show ignorance.",
        "The animal does not understand the ending.",
        "The young man thinks he is walking into pleasure, but he is walking into death.",
        "That is the tragedy of temptation.",
        "It narrows your vision until you only see the moment and not the cost.",
      ],
    },
    {
      range: "24-27",
      heading: "📣 Listen Before You Walk",
      verses: [
        { number: 24, text: "Hearken unto me now therefore, O ye children, and attend to the words of my mouth." },
        { number: 25, text: "Let not thine heart decline to her ways, go not astray in her paths." },
        { number: 26, text: "For she hath cast down many wounded: yea, many strong men have been slain by her." },
        { number: 27, text: "Her house is the way to hell, going down to the chambers of death." },
      ],
      body: [
        "Solomon ends by speaking directly again.",
        "Do not let your heart decline to her ways.",
        "That is important because the heart often declines before the body follows.",
        "The warning is not only for weak men. Many strong men have been slain.",
        "Strength without wisdom is not enough.",
        "Confidence without holiness is not enough.",
        "The house that looked inviting is the way to hell, going down to death.",
        "Solomon wants his son to see the ending while he is still outside the door.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 7 teaches that temptation is often a story with steps.",
    "The young man drifts near the wrong corner, at the wrong time, without wisdom close to his heart.",
    "Temptation flatters, decorates, spiritualizes, and promises secrecy.",
    "But wisdom sees the trap behind the invitation.",
    "The lesson is simple and serious: listen before you walk.",
  ],
};

const PROVERBS_EIGHT: ChapterNotes = {
  title: "📣 Wisdom Calls In Public",
  intro: [
    "Proverbs 8 returns to wisdom as a woman calling out.",
    "But this time the tone is grand and cosmic.",
    "Wisdom is not hiding in a secret room. She is calling in public places, speaking truth, offering treasure better than gold, and showing that she was with the Lord before creation was formed.",
    "This chapter lifts wisdom higher than practical advice.",
    "Wisdom is tied to God's order, God's righteousness, God's creation, and the life that comes from listening.",
    "The point is clear: wisdom is not rare because she is silent. Wisdom is missed because people refuse to hear.",
  ],
  flow: [
    "📣 Verses 1-5: Wisdom calls where people can hear",
    "🗣️ Verses 6-11: Wisdom speaks truth better than riches",
    "👑 Verses 12-21: Wisdom belongs with prudence, justice, rulers, and true wealth",
    "🌍 Verses 22-31: Wisdom was with the Lord before creation",
    "🚪 Verses 32-36: Blessed are those who listen at wisdom's doors",
  ],
  sections: [
    {
      range: "1-5",
      heading: "📣 Wisdom Is Not Hiding",
      verses: [
        { number: 1, text: "Doth not wisdom cry? and understanding put forth her voice?" },
        { number: 2, text: "She standeth in the top of high places, by the way in the places of the paths." },
        { number: 3, text: "She crieth at the gates, at the entry of the city, at the coming in at the doors." },
        { number: 4, text: "Unto you, O men, I call; and my voice is to the sons of man." },
        { number: 5, text: "O ye simple, understand wisdom: and, ye fools, be ye of an understanding heart." },
      ],
      body: [
        "Wisdom is pictured as calling out in visible places.",
        "High places, paths, gates, city entrances, doors.",
        "These are public spaces where people pass by.",
        "The point is that wisdom is available.",
        "She is not hiding from people.",
        "She calls to the sons of man, to the simple, and even to fools.",
        "This means the problem is not that wisdom cannot be found.",
        "The problem is whether people will listen when wisdom speaks.",
      ],
    },
    {
      range: "6-11",
      heading: "🗣️ Truth Better Than Treasure",
      verses: [
        { number: 6, text: "Hear; for I will speak of excellent things; and the opening of my lips shall be right things." },
        { number: 7, text: "For my mouth shall speak truth; and wickedness is an abomination to my lips." },
        { number: 8, text: "All the words of my mouth are in righteousness; there is nothing froward or perverse in them." },
        { number: 9, text: "They are all plain to him that understandeth, and right to them that find knowledge." },
        { number: 10, text: "Receive my instruction, and not silver; and knowledge rather than choice gold." },
        { number: 11, text: "For wisdom is better than rubies; and all the things that may be desired are not to be compared to it." },
      ],
      body: [
        "Wisdom speaks excellent, right, true, and righteous things.",
        "There is nothing crooked in her words.",
        "This contrasts with flattery in the previous chapters.",
        "Temptation uses smooth words to hide danger.",
        "Wisdom uses true words to reveal life.",
        "Solomon again compares wisdom to silver, gold, and rubies.",
        "The lesson keeps returning because human hearts keep overvaluing visible treasure.",
        "Wisdom is better because wisdom teaches you how to live before God with every treasure you receive.",
      ],
    },
    {
      range: "12-21",
      heading: "👑 Wisdom For Rulers And Real Life",
      verses: [
        { number: 12, text: "I wisdom dwell with prudence, and find out knowledge of witty inventions." },
        { number: 13, text: "The fear of the LORD is to hate evil: pride, and arrogancy, and the evil way, and the froward mouth, do I hate." },
        { number: 14, text: "Counsel is mine, and sound wisdom: I am understanding; I have strength." },
        { number: 15, text: "By me kings reign, and princes decree justice." },
        { number: 16, text: "By me princes rule, and nobles, even all the judges of the earth." },
        { number: 17, text: "I love them that love me; and those that seek me early shall find me." },
        { number: 18, text: "Riches and honour are with me; yea, durable riches and righteousness." },
        { number: 19, text: "My fruit is better than gold, yea, than fine gold; and my revenue than choice silver." },
        { number: 20, text: "I lead in the way of righteousness, in the midst of the paths of judgment:" },
        { number: 21, text: "That I may cause those that love me to inherit substance; and I will fill their treasures." },
      ],
      body: [
        "Wisdom is not weak.",
        "She belongs with prudence, counsel, understanding, strength, righteousness, and judgment.",
        "This is why kings and princes need wisdom.",
        "Power without wisdom becomes dangerous.",
        "Authority without righteousness becomes oppression.",
        "Wisdom also defines the fear of the Lord as hating evil.",
        "That means reverence for God is not only a feeling. It creates moral rejection.",
        "Pride, arrogance, the evil way, and the froward mouth are hated by wisdom.",
        "The treasure wisdom gives is durable. It lasts longer than gold because it is rooted in righteousness.",
      ],
    },
    {
      range: "22-31",
      heading: "🌍 Wisdom Before The World",
      verses: [
        { number: 22, text: "The LORD possessed me in the beginning of his way, before his works of old." },
        { number: 23, text: "I was set up from everlasting, from the beginning, or ever the earth was." },
        { number: 24, text: "When there were no depths, I was brought forth; when there were no fountains abounding with water." },
        { number: 25, text: "Before the mountains were settled, before the hills was I brought forth:" },
        { number: 26, text: "While as yet he had not made the earth, nor the fields, nor the highest part of the dust of the world." },
        { number: 27, text: "When he prepared the heavens, I was there: when he set a compass upon the face of the depth:" },
        { number: 28, text: "When he established the clouds above: when he strengthened the fountains of the deep:" },
        { number: 29, text: "When he gave to the sea his decree, that the waters should not pass his commandment: when he appointed the foundations of the earth:" },
        { number: 30, text: "Then I was by him, as one brought up with him: and I was daily his delight, rejoicing always before him;" },
        { number: 31, text: "Rejoicing in the habitable part of his earth; and my delights were with the sons of men." },
      ],
      body: [
        "This section lifts wisdom into creation itself.",
        "Before depths, fountains, mountains, fields, heavens, clouds, seas, and foundations, wisdom was with the Lord.",
        "Solomon is not treating wisdom as a human life hack.",
        "Wisdom is woven into the order of God's world.",
        "This means when a person rejects wisdom, they are not merely rejecting advice.",
        "They are pushing against the grain of creation.",
        "The same God who ordered the sea and set boundaries for the waters has wisdom for human life.",
        "Wisdom rejoices before God and delights in the sons of men.",
        "This is a beautiful picture: wisdom is not trying to rob people of joy.",
        "Wisdom delights in life rightly ordered under God.",
      ],
    },
    {
      range: "32-36",
      heading: "🚪 Waiting At Wisdom's Door",
      verses: [
        { number: 32, text: "Now therefore hearken unto me, O ye children: for blessed are they that keep my ways." },
        { number: 33, text: "Hear instruction, and be wise, and refuse it not." },
        { number: 34, text: "Blessed is the man that heareth me, watching daily at my gates, waiting at the posts of my doors." },
        { number: 35, text: "For whoso findeth me findeth life, and shall obtain favour of the LORD." },
        { number: 36, text: "But he that sinneth against me wrongeth his own soul: all they that hate me love death." },
      ],
      body: [
        "The chapter ends with a choice.",
        "Hear instruction and be wise, or refuse it.",
        "The blessed person watches daily at wisdom's gates.",
        "That means wisdom is not a one-time curiosity.",
        "It is a daily posture.",
        "The one who finds wisdom finds life and favor from the Lord.",
        "The one who sins against wisdom wrongs his own soul.",
        "That phrase is serious because rejecting wisdom is self-harm.",
        "To hate wisdom is to love death, even if the person does not call it that.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 8 shows wisdom calling publicly, speaking truthfully, ruling righteously, standing before creation, and offering life.",
    "Wisdom is not hidden. Wisdom is calling.",
    "The question is whether a person will wait at her doors or walk past her voice.",
  ],
};

const PROVERBS_NINE: ChapterNotes = {
  title: "🍽️ Two Invitations, Two Endings",
  intro: [
    "Proverbs 9 closes the opening section of Proverbs with two invitations.",
    "Wisdom prepares a house, sets a table, sends messengers, and invites the simple to come and live.",
    "Folly also calls.",
    "She sits loudly in public and invites the simple into secret pleasure, but her house is full of death.",
    "This chapter makes the choice clear.",
    "Two voices call. Two tables appear. Two paths open. But only one leads to life.",
  ],
  flow: [
    "🏠 Verses 1-6: Wisdom builds, prepares, invites, and gives life",
    "🧠 Verses 7-12: How a person responds to correction reveals their heart",
    "☠️ Verses 13-18: Folly copies the invitation but hides the death inside",
  ],
  sections: [
    {
      range: "1-6",
      heading: "🏠 Wisdom's House And Table",
      verses: [
        { number: 1, text: "Wisdom hath builded her house, she hath hewn out her seven pillars:" },
        { number: 2, text: "She hath killed her beasts; she hath mingled her wine; she hath also furnished her table." },
        { number: 3, text: "She hath sent forth her maidens: she crieth upon the highest places of the city," },
        { number: 4, text: "Whoso is simple, let him turn in hither: as for him that wanteth understanding, she saith to him," },
        { number: 5, text: "Come, eat of my bread, and drink of the wine which I have mingled." },
        { number: 6, text: "Forsake the foolish, and live; and go in the way of understanding." },
      ],
      body: [
        "Wisdom is pictured as a woman who has built a strong house.",
        "Seven pillars suggest fullness, stability, and strength.",
        "She prepares a feast and sends out servants.",
        "This is not a desperate invitation. It is generous and prepared.",
        "Wisdom calls to the simple, the person who lacks understanding and can still be shaped.",
        "The invitation is not merely to learn a fact.",
        "It is to leave foolishness and live.",
        "The table of wisdom requires a turn.",
        "You cannot keep clinging to folly and fully feast on wisdom.",
      ],
    },
    {
      range: "7-12",
      heading: "🧠 Correction Reveals The Heart",
      verses: [
        { number: 7, text: "He that reproveth a scorner getteth to himself shame: and he that rebuketh a wicked man getteth himself a blot." },
        { number: 8, text: "Reprove not a scorner, lest he hate thee: rebuke a wise man, and he will love thee." },
        { number: 9, text: "Give instruction to a wise man, and he will be yet wiser: teach a just man, and he will increase in learning." },
        { number: 10, text: "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding." },
        { number: 11, text: "For by me thy days shall be multiplied, and the years of thy life shall be increased." },
        { number: 12, text: "If thou be wise, thou shalt be wise for thyself: but if thou scornest, thou alone shalt bear it." },
      ],
      body: [
        "This section shows the difference between a scorner and a wise person.",
        "The scorner hates correction.",
        "The wise person loves the one who rebukes him because he values growth more than ego.",
        "That is one of the clearest tests of wisdom.",
        "How do you respond when corrected?",
        "A wise person becomes wiser through instruction.",
        "A just person increases in learning.",
        "Then verse 10 restates the foundation: the fear of the Lord is the beginning of wisdom.",
        "Wisdom does not begin with pride. It begins with reverence.",
        "Verse 12 also makes responsibility personal. If you are wise, you benefit. If you scorn, you bear it.",
      ],
    },
    {
      range: "13-18",
      heading: "☠️ Folly's Imitation Feast",
      verses: [
        { number: 13, text: "A foolish woman is clamorous: she is simple, and knoweth nothing." },
        { number: 14, text: "For she sitteth at the door of her house, on a seat in the high places of the city," },
        { number: 15, text: "To call passengers who go right on their ways:" },
        { number: 16, text: "Whoso is simple, let him turn in hither: and as for him that wanteth understanding, she saith to him," },
        { number: 17, text: "Stolen waters are sweet, and bread eaten in secret is pleasant." },
        { number: 18, text: "But he knoweth not that the dead are there; and that her guests are in the depths of hell." },
      ],
      body: [
        "Folly also has a house and a voice.",
        "This is important because folly often imitates wisdom's invitation.",
        "She calls to the same kind of person: the simple and the one who lacks understanding.",
        "But her message is different.",
        "Stolen waters are sweet. Secret bread is pleasant.",
        "Folly sells secrecy and forbidden pleasure.",
        "She does not talk about the ending.",
        "Verse 18 reveals what she hides: the dead are there.",
        "Her guests are in the depths of hell.",
        "The table looked exciting, but it was set in a graveyard.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 9 brings the opening lessons of Proverbs to a decision.",
    "Wisdom calls and folly calls.",
    "Wisdom offers life with understanding. Folly offers secret pleasure with hidden death.",
    "The difference is not whether a voice is calling. The difference is which voice you answer.",
  ],
};

const PROVERBS_TEN: ChapterNotes = {
  title: "⚖️ The Proverbs Begin In Full",
  intro: [
    "Proverbs 10 marks a shift.",
    "The opening chapters had longer father-to-son speeches. Now the book begins moving into shorter sayings placed side by side.",
    "Each proverb is compact, but not shallow.",
    "The chapter compares the wise and foolish, righteous and wicked, diligent and lazy, truthful and corrupt, loving and hateful.",
    "This is where Proverbs starts to feel like a collection of wisdom sayings.",
    "The goal is not to rush through them. The goal is to let each saying train how you see life.",
  ],
  flow: [
    "👨‍👩‍👦 Verses 1-5: Wisdom affects family, work, provision, and seasons",
    "🗣️ Verses 6-14: The mouth reveals righteousness or foolishness",
    "💰 Verses 15-17: Wealth, labor, and instruction show different paths",
    "👄 Verses 18-21: Words can hide hatred or feed many",
    "🏠 Verses 22-26: The Lord's blessing is different from foolish sport",
    "🌱 Verses 27-32: The righteous have hope, stability, and fitting speech",
  ],
  sections: [
    {
      range: "1-5",
      heading: "👨‍👩‍👦 Wisdom In The House And Harvest",
      verses: [
        { number: 1, text: "The proverbs of Solomon. A wise son maketh a glad father: but a foolish son is the heaviness of his mother." },
        { number: 2, text: "Treasures of wickedness profit nothing: but righteousness delivereth from death." },
        { number: 3, text: "The LORD will not suffer the soul of the righteous to famish: but he casteth away the substance of the wicked." },
        { number: 4, text: "He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich." },
        { number: 5, text: "He that gathereth in summer is a wise son: but he that sleepeth in harvest is a son that causeth shame." },
      ],
      body: [
        "The first proverb begins in the family.",
        "A wise son brings gladness, while a foolish son brings heaviness.",
        "Wisdom is not private. It affects the people closest to you.",
        "Then Solomon moves to wealth and righteousness.",
        "Treasures gained through wickedness do not profit in the deepest sense.",
        "Righteousness delivers from death because it aligns life with God instead of corruption.",
        "Verses 4 and 5 speak about diligence and seasons.",
        "A slack hand leads toward poverty, while diligence tends toward provision.",
        "The harvest must be gathered when it is harvest time.",
        "Wisdom knows when it is time to work.",
      ],
    },
    {
      range: "6-14",
      heading: "🗣️ The Mouth Shows The Heart",
      verses: [
        { number: 6, text: "Blessings are upon the head of the just: but violence covereth the mouth of the wicked." },
        { number: 7, text: "The memory of the just is blessed: but the name of the wicked shall rot." },
        { number: 8, text: "The wise in heart will receive commandments: but a prating fool shall fall." },
        { number: 9, text: "He that walketh uprightly walketh surely: but he that perverteth his ways shall be known." },
        { number: 10, text: "He that winketh with the eye causeth sorrow: but a prating fool shall fall." },
        { number: 11, text: "The mouth of a righteous man is a well of life: but violence covereth the mouth of the wicked." },
        { number: 12, text: "Hatred stirreth up strifes: but love covereth all sins." },
        { number: 13, text: "In the lips of him that hath understanding wisdom is found: but a rod is for the back of him that is void of understanding." },
        { number: 14, text: "Wise men lay up knowledge: but the mouth of the foolish is near destruction." },
      ],
      body: [
        "This section returns again and again to the mouth.",
        "The wicked mouth is covered with violence. The foolish mouth talks toward destruction. The righteous mouth is a well of life.",
        "Words are not small in Proverbs.",
        "Speech reveals the direction of the heart.",
        "A wise heart receives commandments, but a prating fool falls.",
        "A prating fool is someone whose mouth keeps running without wisdom.",
        "Verse 12 is especially important: hatred stirs up strife, but love covers sins.",
        "That does not mean love hides injustice.",
        "It means love does not delight in stirring conflict. Love seeks restoration where hatred wants fire.",
        "Wise people store knowledge. Fools pour out words that bring them near destruction.",
      ],
    },
    {
      range: "15-17",
      heading: "💰 Wealth, Labor, And Correction",
      verses: [
        { number: 15, text: "The rich man's wealth is his strong city: the destruction of the poor is their poverty." },
        { number: 16, text: "The labour of the righteous tendeth to life: the fruit of the wicked to sin." },
        { number: 17, text: "He is in the way of life that keepeth instruction: but he that refuseth reproof erreth." },
      ],
      body: [
        "These sayings are realistic about money.",
        "Wealth can feel like a strong city because it creates protection and options.",
        "Poverty can be destructive because it creates vulnerability.",
        "But Solomon does not stop at economics.",
        "He moves to moral direction.",
        "The labor of the righteous tends to life, while the fruit of the wicked tends to sin.",
        "Then he returns to instruction.",
        "The person who keeps instruction is in the way of life.",
        "The person who refuses reproof goes astray.",
        "Correction is not an interruption to wisdom. It is part of the path.",
      ],
    },
    {
      range: "18-21",
      heading: "👄 Words That Heal Or Harm",
      verses: [
        { number: 18, text: "He that hideth hatred with lying lips, and he that uttereth a slander, is a fool." },
        { number: 19, text: "In the multitude of words there wanteth not sin: but he that refraineth his lips is wise." },
        { number: 20, text: "The tongue of the just is as choice silver: the heart of the wicked is little worth." },
        { number: 21, text: "The lips of the righteous feed many: but fools die for want of wisdom." },
      ],
      body: [
        "Solomon gives several warnings about speech.",
        "Lying lips can hide hatred, and slander spreads harm openly.",
        "Both are foolish.",
        "Verse 19 teaches restraint. Where there are too many words, sin is not lacking.",
        "That does not mean silence is always wisdom.",
        "It means wise speech is measured.",
        "The tongue of the just is like choice silver because righteous speech has value.",
        "The lips of the righteous feed many.",
        "That is a beautiful picture. Words can nourish people when they are truthful, timely, and wise.",
      ],
    },
    {
      range: "22-26",
      heading: "🏠 Blessing, Fear, And Laziness",
      verses: [
        { number: 22, text: "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it." },
        { number: 23, text: "It is as sport to a fool to do mischief: but a man of understanding hath wisdom." },
        { number: 24, text: "The fear of the wicked, it shall come upon him: but the desire of the righteous shall be granted." },
        { number: 25, text: "As the whirlwind passeth, so is the wicked no more: but the righteous is an everlasting foundation." },
        { number: 26, text: "As vinegar to the teeth, and as smoke to the eyes, so is the sluggard to them that send him." },
      ],
      body: [
        "The blessing of the Lord is different from gain grabbed through wickedness.",
        "It makes rich without the same sorrow that comes from crooked gain.",
        "Verse 23 shows the fool's twisted enjoyment. Mischief is sport to him.",
        "A wise person does not treat harm like entertainment.",
        "The wicked fear what eventually comes upon them, while the righteous have a different foundation.",
        "The whirlwind passes and the wicked are gone.",
        "The righteous are described as an everlasting foundation.",
        "Then Solomon gives a vivid picture of laziness: vinegar to the teeth and smoke to the eyes.",
        "A sluggard frustrates those who depend on him.",
        "Laziness is not only personal weakness. It affects others.",
      ],
    },
    {
      range: "27-32",
      heading: "🌱 The End Of The Two Paths",
      verses: [
        { number: 27, text: "The fear of the LORD prolongeth days: but the years of the wicked shall be shortened." },
        { number: 28, text: "The hope of the righteous shall be gladness: but the expectation of the wicked shall perish." },
        { number: 29, text: "The way of the LORD is strength to the upright: but destruction shall be to the workers of iniquity." },
        { number: 30, text: "The righteous shall never be removed: but the wicked shall not inhabit the earth." },
        { number: 31, text: "The mouth of the just bringeth forth wisdom: but the froward tongue shall be cut out." },
        { number: 32, text: "The lips of the righteous know what is acceptable: but the mouth of the wicked speaketh frowardness." },
      ],
      body: [
        "The chapter ends by contrasting the long-term outcomes of righteousness and wickedness.",
        "The fear of the Lord prolongs days, while wickedness shortens them.",
        "The righteous have hope that leads toward gladness.",
        "The expectation of the wicked perishes.",
        "The way of the Lord is strength to the upright, but destruction to workers of iniquity.",
        "The same Lord who strengthens the upright also opposes evil.",
        "Then Solomon returns once more to the mouth.",
        "The mouth of the just brings wisdom, while the wicked mouth speaks frowardness.",
        "This chapter began with the wise and foolish son, and it ends by showing that wisdom eventually becomes visible in speech, hope, stability, and life.",
      ],
    },
  ],
  takeaway: [
    "Proverbs 10 begins the short-saying section of the book, but the themes are deep.",
    "Wisdom affects family, money, work, speech, correction, desire, hope, and legacy.",
    "The chapter trains you to compare paths, not moments.",
    "The wicked may have quick gain, loud words, and temporary confidence, but the righteous path has life, stability, and hope in the Lord.",
  ],
};

export const PROVERBS_FOUR_TO_TEN_NOTES: Record<number, string> = {
  4: renderNotes(4, PROVERBS_FOUR),
  5: renderNotes(5, PROVERBS_FIVE),
  6: renderNotes(6, PROVERBS_SIX),
  7: renderNotes(7, PROVERBS_SEVEN),
  8: renderNotes(8, PROVERBS_EIGHT),
  9: renderNotes(9, PROVERBS_NINE),
  10: renderNotes(10, PROVERBS_TEN),
};
