import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 12 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsTwelveSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_TWELVE_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Whoso Loveth Instruction Loveth Knowledge",
    icon: "🎓",
    underline: "Whoso loveth instruction loveth knowledge",
    preview: "\"Instruction\" here means correction, being told plainly where you went wrong.",
  },
  {
    verse: 1,
    noteTitle: "He That Hateth Reproof Is Brutish",
    icon: "🐴",
    underline: "he that hateth reproof is brutish",
    preview: "\"Reproof\" is the same idea as instruction, being shown a fault.",
  },
  {
    verse: 2,
    noteTitle: "A Good Man Obtaineth Favour Of The LORD",
    icon: "🙏",
    underline: "A good man obtaineth favour of the LORD",
    preview: "This proverb states plainly that God notices and responds to a good life.",
  },
  {
    verse: 2,
    noteTitle: "A Man Of Wicked Devices Will He Condemn",
    icon: "⚖️",
    underline: "a man of wicked devices will he condemn",
    preview: "\"Devices\" means schemes, plans made on purpose to do harm.",
  },
  {
    verse: 3,
    noteTitle: "A Man Shall Not Be Established By Wickedness",
    icon: "🏛️",
    underline: "A man shall not be established by wickedness",
    preview: "\"Established\" means built to last, firmly set in place.",
  },
  {
    verse: 3,
    noteTitle: "The Root Of The Righteous Shall Not Be Moved",
    icon: "🌳",
    underline: "the root of the righteous shall not be moved",
    preview: "\"Root\" pictures a tree anchored deep in the ground.",
  },
  {
    verse: 4,
    noteTitle: "A Virtuous Woman Is A Crown To Her Husband",
    icon: "👑",
    underline: "A virtuous woman is a crown to her husband",
    preview: "\"Virtuous\" means strong, capable, and of excellent character, not simply nice.",
  },
  {
    verse: 4,
    noteTitle: "She That Maketh Ashamed Is As Rottenness In His Bones",
    icon: "🦴",
    underline: "she that maketh ashamed is as rottenness in his bones",
    preview: "\"Maketh ashamed\" means bringing public disgrace onto someone through bad behavior.",
  },
  {
    verse: 5,
    noteTitle: "The Thoughts Of The Righteous Are Right",
    icon: "⚖️",
    underline: "The thoughts of the righteous are right",
    preview: "\"Thoughts\" here means a person's inner plans and intentions, not stray ideas.",
  },
  {
    verse: 5,
    noteTitle: "The Counsels Of The Wicked Are Deceit",
    icon: "🎭",
    underline: "the counsels of the wicked are deceit",
    preview: "\"Counsels\" means the advice and plans a person forms, the same idea as thoughts.",
  },
  {
    verse: 6,
    noteTitle: "The Words Of The Wicked Are To Lie In Wait For Blood",
    icon: "🗡️",
    underline: "The words of the wicked are to lie in wait for blood",
    preview: "\"Lie in wait\" pictures an ambush, waiting hidden to attack someone unaware.",
  },
  {
    verse: 6,
    noteTitle: "The Mouth Of The Upright Shall Deliver Them",
    icon: "🛟",
    underline: "the mouth of the upright shall deliver them",
    preview: "\"Deliver\" means to rescue from real danger.",
  },
  {
    verse: 7,
    noteTitle: "The Wicked Are Overthrown, And Are Not",
    icon: "💥",
    underline: "The wicked are overthrown, and are not",
    preview: "\"Overthrown\" means violently brought down, not a quiet fall.",
  },
  {
    verse: 7,
    noteTitle: "The House Of The Righteous Shall Stand",
    icon: "🏠",
    underline: "the house of the righteous shall stand",
    preview: "\"House\" here means a family's whole household, not just a building.",
  },
  {
    verse: 8,
    noteTitle: "A Man Shall Be Commended According To His Wisdom",
    icon: "🏅",
    underline: "A man shall be commended according to his wisdom",
    preview: "\"Commended\" means publicly praised or approved by others.",
  },
  {
    verse: 8,
    noteTitle: "He That Is Of A Perverse Heart Shall Be Despised",
    icon: "👎",
    underline: "he that is of a perverse heart shall be despised",
    preview: "\"Perverse heart\" means a will twisted toward wrong on purpose.",
  },
  {
    verse: 9,
    noteTitle: "He That Is Despised, And Hath A Servant",
    icon: "🤷",
    underline: "He that is despised, and hath a servant",
    preview: "This does not mean status alone makes a person valuable.",
  },
  {
    verse: 9,
    noteTitle: "Is Better Than He That Honoureth Himself, And Lacketh Bread",
    icon: "🍞",
    underline: "is better than he that honoureth himself, and lacketh bread",
    preview: "\"Honoureth himself\" means someone who thinks highly of his own status.",
  },
  {
    verse: 10,
    noteTitle: "A Righteous Man Regardeth The Life Of His Beast",
    icon: "🐴",
    underline: "A righteous man regardeth the life of his beast",
    preview: "\"Regardeth\" means to care about and pay real attention to something.",
  },
  {
    verse: 10,
    noteTitle: "The Tender Mercies Of The Wicked Are Cruel",
    icon: "💔",
    underline: "the tender mercies of the wicked are cruel",
    preview: "This does not describe the wicked as having no mercy at all.",
  },
  {
    verse: 11,
    noteTitle: "He That Tilleth His Land Shall Be Satisfied With Bread",
    icon: "🌾",
    underline: "He that tilleth his land shall be satisfied with bread",
    preview: "\"Tilleth\" means working the ground, plowing and planting by hand.",
  },
  {
    verse: 11,
    noteTitle: "He That Followeth Vain Persons Is Void Of Understanding",
    icon: "🚫",
    underline: "he that followeth vain persons is void of understanding",
    preview: "\"Vain persons\" means people who chase empty, worthless pursuits with no real substance.",
  },
  {
    verse: 12,
    noteTitle: "The Wicked Desireth The Net Of Evil Men",
    icon: "🪤",
    underline: "The wicked desireth the net of evil men",
    preview: "\"Net\" here pictures a trap used to catch prey, often by deceit.",
  },
  {
    verse: 12,
    noteTitle: "The Root Of The Righteous Yieldeth Fruit",
    icon: "🌳",
    underline: "the root of the righteous yieldeth fruit",
    preview: "\"Root\" repeats the same picture from verse three, something anchored and alive.",
  },
  {
    verse: 13,
    noteTitle: "The Wicked Is Snared By The Transgression Of His Lips",
    icon: "🪤",
    underline: "The wicked is snared by the transgression of his lips",
    preview: "\"Transgression of his lips\" means sinful speech, lies or careless talk.",
  },
  {
    verse: 13,
    noteTitle: "The Just Shall Come Out Of Trouble",
    icon: "🛟",
    underline: "the just shall come out of trouble",
    preview: "\"Come out of trouble\" means an actual escape, not staying stuck in it.",
  },
  {
    verse: 14,
    noteTitle: "A Man Shall Be Satisfied With Good By The Fruit Of His Mouth",
    icon: "🍞",
    underline: "A man shall be satisfied with good by the fruit of his mouth",
    preview: "\"Fruit of his mouth\" means the results that come from what someone says.",
  },
  {
    verse: 14,
    noteTitle: "The Recompence Of A Man's Hands Shall Be Rendered Unto Him",
    icon: "✋",
    underline: "the recompence of a man’s hands shall be rendered unto him",
    preview: "\"Recompence\" means payment, whatever a person actually earns through their actions.",
  },
  {
    verse: 15,
    noteTitle: "The Way Of A Fool Is Right In His Own Eyes",
    icon: "👁️",
    underline: "The way of a fool is right in his own eyes",
    preview: "\"Right in his own eyes\" is an idiom meaning a person is fully convinced by their own judgment.",
  },
  {
    verse: 15,
    noteTitle: "He That Hearkeneth Unto Counsel Is Wise",
    icon: "👂",
    underline: "he that hearkeneth unto counsel is wise",
    preview: "\"Hearkeneth\" means to listen closely and actually take advice to heart.",
  },
  {
    verse: 16,
    noteTitle: "A Fool's Wrath Is Presently Known",
    icon: "😠",
    underline: "A fool’s wrath is presently known",
    preview: "\"Wrath\" here means anger, a strong emotional reaction.",
  },
  {
    verse: 16,
    noteTitle: "A Prudent Man Covereth Shame",
    icon: "🤐",
    underline: "a prudent man covereth shame",
    preview: "\"Prudent\" means someone who thinks carefully before reacting.",
  },
  {
    verse: 17,
    noteTitle: "He That Speaketh Truth Sheweth Forth Righteousness",
    icon: "✅",
    underline: "He that speaketh truth sheweth forth righteousness",
    preview: "\"Sheweth forth\" is an old way of saying displays or reveals openly.",
  },
  {
    verse: 17,
    noteTitle: "A False Witness Deceit",
    icon: "🎭",
    underline: "a false witness deceit",
    preview: "This short phrase completes the contrast started in the first half of the verse.",
  },
  {
    verse: 18,
    noteTitle: "There Is That Speaketh Like The Piercings Of A Sword",
    icon: "🗡️",
    underline: "There is that speaketh like the piercings of a sword",
    preview: "\"Piercings of a sword\" pictures words that wound as sharply as a blade.",
  },
  {
    verse: 18,
    noteTitle: "The Tongue Of The Wise Is Health",
    icon: "🩹",
    underline: "the tongue of the wise is health",
    preview: "\"Health\" here means healing, restoring what was hurt or broken.",
  },
  {
    verse: 19,
    noteTitle: "The Lip Of Truth Shall Be Established For Ever",
    icon: "⏳",
    underline: "The lip of truth shall be established for ever",
    preview: "\"Established for ever\" means lasting permanently, never being overturned.",
  },
  {
    verse: 19,
    noteTitle: "A Lying Tongue Is But For A Moment",
    icon: "💨",
    underline: "a lying tongue is but for a moment",
    preview: "\"But for a moment\" means it lasts only briefly before it fails.",
  },
  {
    verse: 20,
    noteTitle: "Deceit Is In The Heart Of Them That Imagine Evil",
    icon: "🎭",
    underline: "Deceit is in the heart of them that imagine evil",
    preview: "\"Imagine evil\" means actively planning harm in one's mind, not a passing thought.",
  },
  {
    verse: 20,
    noteTitle: "To The Counsellors Of Peace Is Joy",
    icon: "😊",
    underline: "to the counsellors of peace is joy",
    preview: "\"Counsellors of peace\" means people who work to bring calm and resolve conflict.",
  },
  {
    verse: 21,
    noteTitle: "There Shall No Evil Happen To The Just",
    icon: "🛡️",
    underline: "There shall no evil happen to the just",
    preview: "This does not promise the just will never suffer hardship at all.",
  },
  {
    verse: 21,
    noteTitle: "The Wicked Shall Be Filled With Mischief",
    icon: "😈",
    underline: "the wicked shall be filled with mischief",
    preview: "\"Mischief\" here is a strong old word for real harm and trouble, not childish pranks.",
  },
  {
    verse: 22,
    noteTitle: "Lying Lips Are Abomination To The LORD",
    icon: "🤢",
    underline: "Lying lips are abomination to the LORD",
    preview: "\"Abomination\" repeats the strongest word this book uses for something God finds truly disgusting.",
  },
  {
    verse: 22,
    noteTitle: "They That Deal Truly Are His Delight",
    icon: "🤝",
    underline: "they that deal truly are his delight",
    preview: "\"Deal truly\" means acting honestly in everyday dealings with other people.",
  },
  {
    verse: 23,
    noteTitle: "A Prudent Man Concealeth Knowledge",
    icon: "🤫",
    underline: "A prudent man concealeth knowledge",
    preview: "This does not mean hiding truth or refusing to help someone.",
  },
  {
    verse: 23,
    noteTitle: "The Heart Of Fools Proclaimeth Foolishness",
    icon: "📢",
    underline: "the heart of fools proclaimeth foolishness",
    preview: "\"Proclaimeth\" means announcing loudly and openly, the opposite of concealing.",
  },
  {
    verse: 24,
    noteTitle: "The Hand Of The Diligent Shall Bear Rule",
    icon: "✋",
    underline: "The hand of the diligent shall bear rule",
    preview: "\"Diligent\" means hardworking and consistent in effort over time.",
  },
  {
    verse: 24,
    noteTitle: "The Slothful Shall Be Under Tribute",
    icon: "⛓️",
    underline: "the slothful shall be under tribute",
    preview: "\"Slothful\" means lazy, unwilling to put in consistent effort.",
  },
  {
    verse: 25,
    noteTitle: "Heaviness In The Heart Of Man Maketh It Stoop",
    icon: "😔",
    underline: "Heaviness in the heart of man maketh it stoop",
    preview: "\"Heaviness\" means real emotional weight, grief, worry, or anxiety.",
  },
  {
    verse: 25,
    noteTitle: "A Good Word Maketh It Glad",
    icon: "😊",
    underline: "a good word maketh it glad",
    preview: "\"Good word\" means kind, encouraging speech offered to someone.",
  },
  {
    verse: 26,
    noteTitle: "The Righteous Is More Excellent Than His Neighbour",
    icon: "👑",
    underline: "The righteous is more excellent than his neighbour",
    preview: "\"More excellent\" means genuinely better in character, not just luckier or richer.",
  },
  {
    verse: 26,
    noteTitle: "The Way Of The Wicked Seduceth Them",
    icon: "🌀",
    underline: "the way of the wicked seduceth them",
    preview: "\"Seduceth\" means leads astray, gently at first, until it is too late to notice.",
  },
  {
    verse: 27,
    noteTitle: "The Slothful Man Roasteth Not That Which He Took In Hunting",
    icon: "🏹",
    underline: "The slothful man roasteth not that which he took in hunting",
    preview: "This pictures a hunter who caught real game but never finished the job.",
  },
  {
    verse: 27,
    noteTitle: "The Substance Of A Diligent Man Is Precious",
    icon: "💎",
    underline: "the substance of a diligent man is precious",
    preview: "\"Substance\" here means real wealth, possessions actually gained through labor.",
  },
  {
    verse: 28,
    noteTitle: "In The Way Of Righteousness Is Life",
    icon: "🛤️",
    underline: "In the way of righteousness is life",
    preview: "\"Way of righteousness\" means a whole life lived rightly before God, not one good deed.",
  },
  {
    verse: 28,
    noteTitle: "In The Pathway Thereof There Is No Death",
    icon: "⚰️",
    underline: "in the pathway thereof there is no death",
    preview: "\"Pathway thereof\" means that same road of righteousness just named.",
  },
];
