import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 10 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsTenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_TEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "The Proverbs Of Solomon",
    icon: "📜",
    underline: "The proverbs of Solomon",
    preview: "A proverb is a short saying built to be remembered and repeated.",
  },
  {
    verse: 1,
    noteTitle: "A Wise Son Maketh A Glad Father",
    icon: "👨",
    underline: "A wise son maketh a glad father",
    preview: "A child's daily choices reach far beyond that child alone.",
  },
  {
    verse: 1,
    noteTitle: "A Foolish Son Is The Heaviness Of His Mother",
    icon: "😢",
    underline: "a foolish son is the heaviness of his mother",
    preview: "Heaviness here means grief, a weight that presses down on someone.",
  },
  {
    verse: 2,
    noteTitle: "Treasures Of Wickedness Profit Nothing",
    icon: "💰",
    underline: "Treasures of wickedness profit nothing",
    preview: "Wickedness here means gaining wealth through dishonest or sinful means.",
  },
  {
    verse: 2,
    noteTitle: "Righteousness Delivereth From Death",
    icon: "🛟",
    underline: "righteousness delivereth from death",
    preview: "This does not promise that righteous people never die.",
  },
  {
    verse: 3,
    noteTitle: "The LORD Will Not Suffer The Soul Of The Righteous To Famish",
    icon: "🍞",
    underline: "The LORD will not suffer the soul of the righteous to famish",
    preview: "Suffer here means allow, not endure.",
  },
  {
    verse: 3,
    noteTitle: "He Casteth Away The Substance Of The Wicked",
    icon: "💨",
    underline: "he casteth away the substance of the wicked",
    preview: "Substance here means a person's wealth, property, and resources.",
  },
  {
    verse: 4,
    noteTitle: "He Becometh Poor That Dealeth With A Slack Hand",
    icon: "😴",
    underline: "He becometh poor that dealeth with a slack hand",
    preview: "A slack hand pictures a hand that works loosely, without effort or care.",
  },
  {
    verse: 4,
    noteTitle: "The Hand Of The Diligent Maketh Rich",
    icon: "💪",
    underline: "the hand of the diligent maketh rich",
    preview: "Diligent means steady, careful, and hardworking over time.",
  },
  {
    verse: 5,
    noteTitle: "He That Gathereth In Summer Is A Wise Son",
    icon: "☀️",
    underline: "He that gathereth in summer is a wise son",
    preview: "In this farming culture, summer was the short window to gather the harvest.",
  },
  {
    verse: 5,
    noteTitle: "He That Sleepeth In Harvest Is A Son That Causeth Shame",
    icon: "😴",
    underline: "he that sleepeth in harvest is a son that causeth shame",
    preview: "Harvest was the busiest, most urgent season on a farm.",
  },
  {
    verse: 6,
    noteTitle: "Blessings Are Upon The Head Of The Just",
    icon: "🙌",
    underline: "Blessings are upon the head of the just",
    preview: "In this culture, blessing was often pictured as oil poured out on the head.",
  },
  {
    verse: 6,
    noteTitle: "Violence Covereth The Mouth Of The Wicked",
    icon: "⚔️",
    underline: "violence covereth the mouth of the wicked",
    preview: "Covereth here pictures violence filling up someone's speech, almost like a mask.",
  },
  {
    verse: 7,
    noteTitle: "The Memory Of The Just Is Blessed",
    icon: "🌟",
    underline: "The memory of the just is blessed",
    preview: "In a culture without photographs or written records for most people, being remembered mattered deeply.",
  },
  {
    verse: 7,
    noteTitle: "The Name Of The Wicked Shall Rot",
    icon: "🪦",
    underline: "the name of the wicked shall rot",
    preview: "Rot pictures something once solid slowly decaying into nothing.",
  },
  {
    verse: 8,
    noteTitle: "The Wise In Heart Will Receive Commandments",
    icon: "📚",
    underline: "The wise in heart will receive commandments",
    preview: "Heart in this book usually means the center of a person's will and choices, not just emotion.",
  },
  {
    verse: 8,
    noteTitle: "A Prating Fool Shall Fall",
    icon: "🗯️",
    underline: "a prating fool shall fall",
    preview: "Prating means talking constantly and carelessly, often without real content.",
  },
  {
    verse: 9,
    noteTitle: "He That Walketh Uprightly Walketh Surely",
    icon: "🛤️",
    underline: "He that walketh uprightly walketh surely",
    preview: "Walking is a common picture in this book for how a person lives day to day.",
  },
  {
    verse: 9,
    noteTitle: "He That Perverteth His Ways Shall Be Known",
    icon: "🎭",
    underline: "he that perverteth his ways shall be known",
    preview: "Perverteth means to twist or distort something away from what is right.",
  },
  {
    verse: 10,
    noteTitle: "He That Winketh With The Eye Causeth Sorrow",
    icon: "😉",
    underline: "He that winketh with the eye causeth sorrow",
    preview: "A wink in this culture, as in ours, often signals a secret or dishonest message.",
  },
  {
    verse: 11,
    noteTitle: "The Mouth Of A Righteous Man Is A Well Of Life",
    icon: "💧",
    underline: "The mouth of a righteous man is a well of life",
    preview: "In this dry region, a well was one of the most valuable things a community could have.",
  },
  {
    verse: 12,
    noteTitle: "Hatred Stirreth Up Strifes",
    icon: "💥",
    underline: "Hatred stirreth up strifes",
    preview: "Strifes means ongoing quarrels and conflicts, not a single argument.",
  },
  {
    verse: 12,
    noteTitle: "Love Covereth All Sins",
    icon: "❤️",
    underline: "love covereth all sins",
    preview: "Covereth here does not mean pretending sin never happened.",
  },
  {
    verse: 13,
    noteTitle: "In The Lips Of Him That Hath Understanding Wisdom Is Found",
    icon: "💡",
    underline: "In the lips of him that hath understanding wisdom is found",
    preview: "Understanding here means real insight into how life and God actually work.",
  },
  {
    verse: 13,
    noteTitle: "A Rod Is For The Back Of Him That Is Void Of Understanding",
    icon: "🪵",
    underline: "a rod is for the back of him that is void of understanding",
    preview: "Void of understanding means genuinely lacking sense, not simply young or inexperienced.",
  },
  {
    verse: 14,
    noteTitle: "Wise Men Lay Up Knowledge",
    icon: "📦",
    underline: "Wise men lay up knowledge",
    preview: "Lay up pictures storing something valuable for later use, like grain in a barn.",
  },
  {
    verse: 14,
    noteTitle: "The Mouth Of The Foolish Is Near Destruction",
    icon: "💣",
    underline: "the mouth of the foolish is near destruction",
    preview: "Near destruction means close to real danger, not just embarrassment.",
  },
  {
    verse: 15,
    noteTitle: "The Rich Man's Wealth Is His Strong City",
    icon: "🏰",
    underline: "The rich man’s wealth\nis his strong city",
    preview: "A strong city in this world meant thick walls and real protection from attack.",
  },
  {
    verse: 15,
    noteTitle: "The Destruction Of The Poor Is Their Poverty",
    icon: "🕳️",
    underline: "the destruction of the poor\nis their poverty",
    preview: "This line is not calling poverty a sin or a personal failure.",
  },
  {
    verse: 16,
    noteTitle: "The Labour Of The Righteous Tendeth To Life",
    icon: "🌱",
    underline: "The labour of the righteous tendeth to life",
    preview: "Tendeth means leads toward or moves in a direction over time.",
  },
  {
    verse: 16,
    noteTitle: "The Fruit Of The Wicked Tendeth To Sin",
    icon: "🍂",
    underline: "the fruit of the wicked to sin",
    preview: "Fruit here pictures the natural result that grows out of a person's actions.",
  },
  {
    verse: 17,
    noteTitle: "He Is In The Way Of Life That Keepeth Instruction",
    icon: "🛤️",
    underline: "He is in the way of life that keepeth instruction",
    preview: "The way of life is another picture of a path leading somewhere good.",
  },
  {
    verse: 17,
    noteTitle: "He That Refuseth Reproof Erreth",
    icon: "🌀",
    underline: "he that refuseth reproof erreth",
    preview: "Reproof means direct correction, pointing out exactly where someone went wrong.",
  },
  {
    verse: 18,
    noteTitle: "He That Hideth Hatred With Lying Lips",
    icon: "🎭",
    underline: "He that hideth hatred with lying lips",
    preview: "Hiding hatred behind lying lips means acting friendly while secretly holding a grudge.",
  },
  {
    verse: 18,
    noteTitle: "He That Uttereth A Slander Is A Fool",
    icon: "🗣️",
    underline: "he that uttereth a slander, is a fool",
    preview: "Uttereth simply means speaks out loud, puts into words.",
  },
  {
    verse: 19,
    noteTitle: "In The Multitude Of Words There Wanteth Not Sin",
    icon: "💬",
    underline: "In the multitude of words there wanteth not sin",
    preview: "Multitude means a large number, more than is necessary.",
  },
  {
    verse: 19,
    noteTitle: "He That Refraineth His Lips Is Wise",
    icon: "🤐",
    underline: "he that refraineth his lips is wise",
    preview: "Refraineth means to hold back or restrain something on purpose.",
  },
  {
    verse: 20,
    noteTitle: "The Tongue Of The Just Is As Choice Silver",
    icon: "🥈",
    underline: "The tongue of the just is as choice silver",
    preview: "Choice silver means silver that has been refined, purified of impurities.",
  },
  {
    verse: 20,
    noteTitle: "The Heart Of The Wicked Is Little Worth",
    icon: "🪨",
    underline: "the heart of the wicked is little worth",
    preview: "Heart again means the center of a person's will and choices.",
  },
  {
    verse: 21,
    noteTitle: "The Lips Of The Righteous Feed Many",
    icon: "🍽️",
    underline: "The lips of the righteous feed many",
    preview: "Feed many pictures someone providing real nourishment through their words, like a shepherd providing for a flock.",
  },
  {
    verse: 21,
    noteTitle: "Fools Die For Want Of Wisdom",
    icon: "🕳️",
    underline: "fools die for want of wisdom",
    preview: "Want of wisdom means lacking it, being without it.",
  },
  {
    verse: 22,
    noteTitle: "The Blessing Of The LORD, It Maketh Rich",
    icon: "💰",
    underline: "The blessing of the LORD, it maketh rich",
    preview: "This verse names God directly as the true source behind real riches.",
  },
  {
    verse: 22,
    noteTitle: "He Addeth No Sorrow With It",
    icon: "🕊️",
    underline: "he addeth no sorrow with it",
    preview: "Sorrow here means the regret, guilt, or grief that often follows how wealth was gained.",
  },
  {
    verse: 23,
    noteTitle: "It Is As Sport To A Fool To Do Mischief",
    icon: "🎲",
    underline: "It is as sport to a fool to do mischief",
    preview: "Sport here means a game, something done purely for entertainment.",
  },
  {
    verse: 23,
    noteTitle: "A Man Of Understanding Hath Wisdom",
    icon: "🧠",
    underline: "a man of understanding hath wisdom",
    preview: "This line stands directly opposite the fool who treats mischief as sport.",
  },
  {
    verse: 24,
    noteTitle: "The Fear Of The Wicked, It Shall Come Upon Him",
    icon: "😨",
    underline: "The fear of the wicked, it shall come upon him",
    preview: "Fear here means the wicked person's own dread, the thing they are secretly afraid of.",
  },
  {
    verse: 24,
    noteTitle: "The Desire Of The Righteous Shall Be Granted",
    icon: "🎁",
    underline: "the desire of the righteous shall be granted",
    preview: "Desire here means what a righteous person genuinely longs for.",
  },
  {
    verse: 25,
    noteTitle: "As The Whirlwind Passeth, So Is The Wicked No More",
    icon: "🌪️",
    underline: "As the whirlwind passeth, so is the wicked no more",
    preview: "A whirlwind was a familiar, terrifying storm in this region, capable of destroying everything in its path.",
  },
  {
    verse: 25,
    noteTitle: "The Righteous Is An Everlasting Foundation",
    icon: "🏛️",
    underline: "the righteous is an everlasting foundation",
    preview: "A foundation is the part of a building that does not move, the part everything else rests on.",
  },
  {
    verse: 26,
    noteTitle: "As Vinegar To The Teeth, And As Smoke To The Eyes",
    icon: "🍋",
    underline: "As vinegar to the teeth, and as smoke to the eyes",
    preview: "Vinegar touching the teeth causes a sharp, unpleasant sting.",
  },
  {
    verse: 26,
    noteTitle: "So Is The Sluggard To Them That Send Him",
    icon: "🐌",
    underline: "so is the sluggard to them that send him",
    preview: "A sluggard means a lazy person who resists doing what needs to be done.",
  },
  {
    verse: 27,
    noteTitle: "The Fear Of The LORD Prolongeth Days",
    icon: "⏳",
    underline: "The fear of the LORD prolongeth days",
    preview: "Fear of the LORD means taking God seriously enough to actually live differently because of him.",
  },
  {
    verse: 27,
    noteTitle: "The Years Of The Wicked Shall Be Shortened",
    icon: "✂️",
    underline: "the years of the wicked shall be shortened",
    preview: "Shortened here does not mean every wicked person dies young.",
  },
  {
    verse: 28,
    noteTitle: "The Hope Of The Righteous Shall Be Gladness",
    icon: "😊",
    underline: "The hope of the righteous shall be gladness",
    preview: "Hope here means a confident expectation, not just a wish.",
  },
  {
    verse: 28,
    noteTitle: "The Expectation Of The Wicked Shall Perish",
    icon: "💨",
    underline: "the expectation of the wicked shall perish",
    preview: "Expectation here means whatever the wicked person is counting on for the future.",
  },
  {
    verse: 29,
    noteTitle: "The Way Of The LORD Is Strength To The Upright",
    icon: "🏔️",
    underline: "The way of the LORD is strength to the upright",
    preview: "The way of the LORD means living according to how God has instructed his people to live.",
  },
  {
    verse: 29,
    noteTitle: "Destruction Shall Be To The Workers Of Iniquity",
    icon: "💥",
    underline: "destruction shall be to the workers of iniquity",
    preview: "Workers of iniquity means people who practice sin as an ongoing pattern, not a single mistake.",
  },
  {
    verse: 30,
    noteTitle: "The Righteous Shall Never Be Removed",
    icon: "🌳",
    underline: "The righteous shall never be removed",
    preview: "Removed pictures being uprooted, like a tree torn out of the ground.",
  },
  {
    verse: 30,
    noteTitle: "The Wicked Shall Not Inhabit The Earth",
    icon: "🏜️",
    underline: "the wicked shall not inhabit the earth",
    preview: "Inhabit means to live in and possess a place long term, not just visit it.",
  },
  {
    verse: 31,
    noteTitle: "The Mouth Of The Just Bringeth Forth Wisdom",
    icon: "🍯",
    underline: "The mouth of the just bringeth forth wisdom",
    preview: "Bringeth forth pictures wisdom growing and emerging naturally, the way fruit grows from a healthy tree.",
  },
  {
    verse: 31,
    noteTitle: "The Froward Tongue Shall Be Cut Out",
    icon: "✂️",
    underline: "the froward tongue shall be cut out",
    preview: "Froward means stubborn, twisted, and deliberately contrary to what is right.",
  },
  {
    verse: 32,
    noteTitle: "The Lips Of The Righteous Know What Is Acceptable",
    icon: "✅",
    underline: "The lips of the righteous know what is acceptable",
    preview: "Acceptable here means what is fitting, pleasing, and appropriate to say in a given moment.",
  },
  {
    verse: 32,
    noteTitle: "The Mouth Of The Wicked Speaketh Frowardness",
    icon: "🌀",
    underline: "the mouth of the wicked speaketh frowardness",
    preview: "Frowardness is the noun form of froward, meaning stubborn and twisted speech.",
  },
];
