import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 13 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsThirteenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_THIRTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "A Wise Son Heareth His Father's Instruction",
    icon: "👂",
    underline: "A wise son heareth his father’s instruction",
    preview: "\"Instruction\" here means correction from a parent, not just any lesson.",
  },
  {
    verse: 1,
    noteTitle: "A Scorner Heareth Not Rebuke",
    icon: "🙄",
    underline: "a scorner heareth not rebuke",
    preview: "\"Scorner\" means someone who mocks correction instead of considering it.",
  },
  {
    verse: 2,
    noteTitle: "A Man Shall Eat Good By The Fruit Of His Mouth",
    icon: "🗣️",
    underline: "A man shall eat good by the fruit of his mouth",
    preview: "\"Fruit of his mouth\" means the results that come from what a person says.",
  },
  {
    verse: 2,
    noteTitle: "The Soul Of The Transgressors Shall Eat Violence",
    icon: "⚖️",
    underline: "the soul of the transgressors shall eat violence",
    preview: "\"Transgressors\" means those who break God's commands on purpose.",
  },
  {
    verse: 3,
    noteTitle: "He That Keepeth His Mouth Keepeth His Life",
    icon: "🛡️",
    underline: "He that keepeth his mouth keepeth his life",
    preview: "\"Keepeth\" means guards carefully, the way someone guards something valuable.",
  },
  {
    verse: 3,
    noteTitle: "He That Openeth Wide His Lips Shall Have Destruction",
    icon: "👄",
    underline: "he that openeth wide his lips shall have destruction",
    preview: "\"Openeth wide his lips\" pictures speaking without any restraint at all.",
  },
  {
    verse: 4,
    noteTitle: "The Soul Of The Sluggard Desireth, And Hath Nothing",
    icon: "😴",
    underline: "The soul of the sluggard desireth, and hath nothing",
    preview: "\"Sluggard\" means a lazy person, someone unwilling to put in effort.",
  },
  {
    verse: 4,
    noteTitle: "The Soul Of The Diligent Shall Be Made Fat",
    icon: "💪",
    underline: "the soul of the diligent shall be made fat",
    preview: "\"Diligent\" means hardworking and consistent, the opposite of the sluggard.",
  },
  {
    verse: 5,
    noteTitle: "A Righteous Man Hateth Lying",
    icon: "😠",
    underline: "A righteous man hateth lying",
    preview: "\"Hateth\" here means a strong, settled opposition, not a passing dislike.",
  },
  {
    verse: 5,
    noteTitle: "A Wicked Man Is Loathsome, And Cometh To Shame",
    icon: "🤢",
    underline: "a wicked man is loathsome, and cometh to shame",
    preview: "\"Loathsome\" means disgusting, something people want to keep their distance from.",
  },
  {
    verse: 6,
    noteTitle: "Righteousness Keepeth Him That Is Upright In The Way",
    icon: "🛡️",
    underline: "Righteousness keepeth him that is upright in the way",
    preview: "\"Keepeth\" here means guards and protects over time.",
  },
  {
    verse: 6,
    noteTitle: "Wickedness Overthroweth The Sinner",
    icon: "💥",
    underline: "wickedness overthroweth the sinner",
    preview: "\"Overthroweth\" means violently brings down, the same strong word used elsewhere in this book.",
  },
  {
    verse: 7,
    noteTitle: "There Is That Maketh Himself Rich, Yet Hath Nothing",
    icon: "🎭",
    underline: "There is that maketh himself rich, yet hath nothing",
    preview: "This describes someone who appears wealthy but actually owns very little.",
  },
  {
    verse: 7,
    noteTitle: "There Is That Maketh Himself Poor, Yet Hath Great Riches",
    icon: "🙇",
    underline: "there is that maketh himself poor, yet hath great riches",
    preview: "This describes the exact opposite situation, someone who appears poor but truly has much.",
  },
  {
    verse: 8,
    noteTitle: "The Ransom Of A Man's Life Are His Riches",
    icon: "💰",
    underline: "The ransom of a man’s life are his riches",
    preview: "\"Ransom\" means the price paid to free someone from danger or captivity.",
  },
  {
    verse: 8,
    noteTitle: "The Poor Heareth Not Rebuke",
    icon: "🤷",
    underline: "the poor heareth not rebuke",
    preview: "This likely means a poor man draws little threat from those who prey on wealth.",
  },
  {
    verse: 9,
    noteTitle: "The Light Of The Righteous Rejoiceth",
    icon: "💡",
    underline: "The light of the righteous rejoiceth",
    preview: "\"Light\" is a common picture in this book for a good, flourishing life.",
  },
  {
    verse: 9,
    noteTitle: "The Lamp Of The Wicked Shall Be Put Out",
    icon: "🪔",
    underline: "the lamp of the wicked shall be put out",
    preview: "\"Lamp\" pictures a smaller, more fragile light than the sun, something that must be tended.",
  },
  {
    verse: 10,
    noteTitle: "Only By Pride Cometh Contention",
    icon: "⚔️",
    underline: "Only by pride cometh contention",
    preview: "\"Contention\" means quarreling and conflict between people.",
  },
  {
    verse: 10,
    noteTitle: "With The Well Advised Is Wisdom",
    icon: "👂",
    underline: "with the well advised is wisdom",
    preview: "\"Well advised\" describes someone who actually takes counsel from others seriously.",
  },
  {
    verse: 11,
    noteTitle: "Wealth Gotten By Vanity Shall Be Diminished",
    icon: "💨",
    underline: "Wealth gotten by vanity shall be diminished",
    preview: "\"Vanity\" here means emptiness, quick or dishonest schemes with no real substance.",
  },
  {
    verse: 11,
    noteTitle: "He That Gathereth By Labour Shall Increase",
    icon: "💪",
    underline: "he that gathereth by labour shall increase",
    preview: "\"Labour\" means real, steady work over time.",
  },
  {
    verse: 12,
    noteTitle: "Hope Deferred Maketh The Heart Sick",
    icon: "⏳",
    underline: "Hope deferred maketh the heart sick",
    preview: "\"Deferred\" means delayed, pushed off again and again without resolution.",
  },
  {
    verse: 12,
    noteTitle: "When The Desire Cometh, It Is A Tree Of Life",
    icon: "🌳",
    underline: "when the desire cometh, it is a tree of life",
    preview: "\"Tree of life\" is a picture used elsewhere in this book for something that brings real flourishing.",
  },
  {
    verse: 13,
    noteTitle: "Whoso Despiseth The Word Shall Be Destroyed",
    icon: "🙄",
    underline: "Whoso despiseth the word shall be destroyed",
    preview: "\"Despiseth\" means treats with contempt, refuses to take seriously.",
  },
  {
    verse: 13,
    noteTitle: "He That Feareth The Commandment Shall Be Rewarded",
    icon: "🙏",
    underline: "he that feareth the commandment shall be rewarded",
    preview: "\"Feareth\" here means takes seriously with real respect, not terror.",
  },
  {
    verse: 14,
    noteTitle: "The Law Of The Wise Is A Fountain Of Life",
    icon: "⛲",
    underline: "The law of the wise is a fountain of life",
    preview: "\"Fountain of life\" pictures a spring of fresh, flowing water in a dry land.",
  },
  {
    verse: 14,
    noteTitle: "To Depart From The Snares Of Death",
    icon: "🪤",
    underline: "to depart from the snares of death",
    preview: "\"Snares\" pictures hidden traps set to catch something unaware.",
  },
  {
    verse: 15,
    noteTitle: "Good Understanding Giveth Favour",
    icon: "🧠",
    underline: "Good understanding giveth favour",
    preview: "\"Understanding\" here means sound judgment, seeing situations clearly.",
  },
  {
    verse: 15,
    noteTitle: "The Way Of Transgressors Is Hard",
    icon: "🪨",
    underline: "the way of transgressors is hard",
    preview: "\"Hard\" here means rough and difficult to travel, like a rocky, wearing path.",
  },
  {
    verse: 16,
    noteTitle: "Every Prudent Man Dealeth With Knowledge",
    icon: "🧠",
    underline: "Every prudent man dealeth with knowledge",
    preview: "\"Prudent\" means careful and thoughtful before acting.",
  },
  {
    verse: 16,
    noteTitle: "A Fool Layeth Open His Folly",
    icon: "📢",
    underline: "a fool layeth open his folly",
    preview: "\"Layeth open\" means displays plainly, without meaning to hide it.",
  },
  {
    verse: 17,
    noteTitle: "A Wicked Messenger Falleth Into Mischief",
    icon: "📨",
    underline: "A wicked messenger falleth into mischief",
    preview: "\"Messenger\" here means someone entrusted to carry news or instructions for another person.",
  },
  {
    verse: 17,
    noteTitle: "A Faithful Ambassador Is Health",
    icon: "🕊️",
    underline: "a faithful ambassador is health",
    preview: "\"Ambassador\" here means a trusted representative sent on another's behalf.",
  },
  {
    verse: 18,
    noteTitle: "Poverty And Shame Shall Be To Him That Refuseth Instruction",
    icon: "🙅",
    underline: "Poverty and shame shall be to him that refuseth instruction",
    preview: "\"Refuseth instruction\" means outright rejecting correction, not simply forgetting it.",
  },
  {
    verse: 18,
    noteTitle: "He That Regardeth Reproof Shall Be Honoured",
    icon: "👂",
    underline: "he that regardeth reproof shall be honoured",
    preview: "\"Regardeth\" means pays real attention to and takes to heart.",
  },
  {
    verse: 19,
    noteTitle: "The Desire Accomplished Is Sweet To The Soul",
    icon: "🎯",
    underline: "The desire accomplished is sweet to the soul",
    preview: "\"Desire accomplished\" means a genuine longing that finally gets fulfilled.",
  },
  {
    verse: 19,
    noteTitle: "It Is Abomination To Fools To Depart From Evil",
    icon: "🤢",
    underline: "it is abomination to fools to depart from evil",
    preview: "\"Abomination\" repeats the strongest word this book uses for something truly disgusting to someone.",
  },
  {
    verse: 20,
    noteTitle: "He That Walketh With Wise Men Shall Be Wise",
    icon: "🚶",
    underline: "He that walketh with wise men shall be wise",
    preview: "\"Walketh with\" pictures ongoing companionship, not a single conversation.",
  },
  {
    verse: 20,
    noteTitle: "A Companion Of Fools Shall Be Destroyed",
    icon: "👥",
    underline: "a companion of fools shall be destroyed",
    preview: "\"Companion\" repeats the same idea of close, ongoing relationship from the first half of the verse.",
  },
  {
    verse: 21,
    noteTitle: "Evil Pursueth Sinners",
    icon: "🏃",
    underline: "Evil pursueth sinners",
    preview: "\"Pursueth\" pictures active chasing, not evil simply waiting nearby.",
  },
  {
    verse: 21,
    noteTitle: "To The Righteous Good Shall Be Repayed",
    icon: "💰",
    underline: "to the righteous good shall be repayed",
    preview: "\"Repayed\" means paid back, as though goodness were an actual debt owed.",
  },
  {
    verse: 22,
    noteTitle: "A Good Man Leaveth An Inheritance To His Children's Children",
    icon: "🏡",
    underline: "A good man leaveth an inheritance to his children’s children",
    preview: "\"Inheritance\" here means what a family passes down across generations.",
  },
  {
    verse: 22,
    noteTitle: "The Wealth Of The Sinner Is Laid Up For The Just",
    icon: "📦",
    underline: "the wealth of the sinner is laid up for the just",
    preview: "\"Laid up\" means stored away, kept in reserve for someone else to eventually receive.",
  },
  {
    verse: 23,
    noteTitle: "Much Food Is In The Tillage Of The Poor",
    icon: "🌾",
    underline: "Much food is in the tillage of the poor",
    preview: "\"Tillage\" means land that has been worked and planted by hand.",
  },
  {
    verse: 23,
    noteTitle: "There Is That Is Destroyed For Want Of Judgment",
    icon: "🧠",
    underline: "there is that is destroyed for want of judgment",
    preview: "\"Want of judgment\" means a real lack of wisdom, not bad luck.",
  },
  {
    verse: 24,
    noteTitle: "He That Spareth His Rod Hateth His Son",
    icon: "🪵",
    underline: "He that spareth his rod hateth his son",
    preview: "\"Rod\" here means physical discipline, a real corrective tool used in this culture.",
  },
  {
    verse: 24,
    noteTitle: "He That Loveth Him Chasteneth Him Betimes",
    icon: "✋",
    underline: "he that loveth him chasteneth him betimes",
    preview: "\"Chasteneth\" means disciplines, corrects with real consequence.",
  },
  {
    verse: 25,
    noteTitle: "The Righteous Eateth To The Satisfying Of His Soul",
    icon: "🍽️",
    underline: "The righteous eateth to the satisfying of his soul",
    preview: "\"Satisfying of his soul\" means real, deep contentment, not just a full stomach.",
  },
  {
    verse: 25,
    noteTitle: "The Belly Of The Wicked Shall Want",
    icon: "🕳️",
    underline: "the belly of the wicked shall want",
    preview: "\"Want\" here means to genuinely lack, to go without what is needed.",
  },
];
