import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 7 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsSevenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_SEVEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "My Son",
    icon: "👂",
    underline: "My son",
    preview: "My son is how a teacher spoke to a student in this kind of writing.",
  },
  {
    verse: 1,
    noteTitle: "Keep My Words",
    icon: "🛡️",
    underline: "keep my words",
    preview: "Keep means much more than simply remembering something for later.",
  },
  {
    verse: 1,
    noteTitle: "Lay Up My Commandments With Thee",
    icon: "📦",
    underline: "lay up my commandments with thee",
    preview: "Lay up pictures storing something away safely for future use.",
  },
  {
    verse: 2,
    noteTitle: "Keep My Commandments, And Live",
    icon: "⚖️",
    underline: "Keep my commandments, and live",
    preview: "This line ties obedience directly to life itself.",
  },
  {
    verse: 2,
    noteTitle: "As The Apple Of Thine Eye",
    icon: "👁️",
    underline: "as the apple of thine eye",
    preview: "The apple of the eye is an old way of naming the pupil.",
  },
  {
    verse: 3,
    noteTitle: "Bind Them Upon Thy Fingers",
    icon: "💍",
    underline: "Bind them upon thy fingers",
    preview: "Binding something on the fingers pictures wearing it like a ring.",
  },
  {
    verse: 3,
    noteTitle: "Write Them Upon The Table Of Thine Heart",
    icon: "❤️",
    underline: "write them upon the table of thine heart",
    preview: "A table here means a flat writing surface, like a tablet.",
  },
  {
    verse: 4,
    noteTitle: "Say Unto Wisdom, Thou Art My Sister",
    icon: "👭",
    underline: "Say unto wisdom, Thou art my sister",
    preview: "Calling wisdom a sister uses family language on purpose.",
  },
  {
    verse: 4,
    noteTitle: "Call Understanding Thy Kinswoman",
    icon: "👵",
    underline: "call understanding thy kinswoman",
    preview: "Kinswoman names a close relative bound to a family by blood.",
  },
  {
    verse: 5,
    noteTitle: "The Strange Woman",
    icon: "🚫",
    underline: "the strange woman",
    preview: "A strange woman in Proverbs means a woman outside the bounds of marriage.",
  },
  {
    verse: 5,
    noteTitle: "Which Flattereth With Her Words",
    icon: "🍯",
    underline: "which flattereth with her words",
    preview: "Flattery means false praise designed to lower someone's guard.",
  },
  {
    verse: 6,
    noteTitle: "At The Window Of My House",
    icon: "🪟",
    underline: "at the window of my house",
    preview: "The speaker here is the father telling his son a story he witnessed.",
  },
  {
    verse: 6,
    noteTitle: "Through My Casement",
    icon: "🔲",
    underline: "through my casement",
    preview: "A casement was a lattice or screened opening built into a window.",
  },
  {
    verse: 7,
    noteTitle: "Among The Simple Ones",
    icon: "🙈",
    underline: "among the simple ones",
    preview: "Simple in Proverbs does not mean stupid, it means untrained and easily led.",
  },
  {
    verse: 7,
    noteTitle: "Void Of Understanding",
    icon: "🕳️",
    underline: "void of understanding",
    preview: "Void here means completely empty, missing the thing entirely.",
  },
  {
    verse: 8,
    noteTitle: "Passing Through The Street Near Her Corner",
    icon: "🚶",
    underline: "Passing through the street near her corner",
    preview: "He is not lost, he chose this exact route.",
  },
  {
    verse: 8,
    noteTitle: "He Went The Way To Her House",
    icon: "🏠",
    underline: "he went the way to her house",
    preview: "This line removes any doubt about where his path was heading.",
  },
  {
    verse: 9,
    noteTitle: "In The Twilight",
    icon: "🌆",
    underline: "In the twilight",
    preview: "Twilight was the first stretch of fading daylight after the sun went down.",
  },
  {
    verse: 9,
    noteTitle: "In The Evening",
    icon: "🌃",
    underline: "in the evening",
    preview: "Evening deepens the same picture named just a moment before.",
  },
  {
    verse: 9,
    noteTitle: "In The Black And Dark Night",
    icon: "🌑",
    underline: "in the black and dark night",
    preview: "This is the third and final named hour, and the darkest by far.",
  },
  {
    verse: 10,
    noteTitle: "The Attire Of An Harlot",
    icon: "👗",
    underline: "the attire of an harlot",
    preview: "Clothing in this culture openly signaled a person's trade or intention.",
  },
  {
    verse: 10,
    noteTitle: "Subtil Of Heart",
    icon: "🦊",
    underline: "subtil of heart",
    preview: "Subtil is an old word meaning crafty, cunning, and calculating.",
  },
  {
    verse: 11,
    noteTitle: "Loud And Stubborn",
    icon: "📢",
    underline: "loud and stubborn",
    preview: "Loud describes brash, attention seeking public behavior.",
  },
  {
    verse: 11,
    noteTitle: "Her Feet Abide Not In Her House",
    icon: "🏃",
    underline: "her feet abide not in her house",
    preview: "Abide means to stay put or remain settled somewhere.",
  },
  {
    verse: 12,
    noteTitle: "Now Is She Without, Now In The Streets",
    icon: "🌇",
    underline: "Now is she without, now in the streets",
    preview: "Without here means outside, away from home.",
  },
  {
    verse: 12,
    noteTitle: "Lieth In Wait At Every Corner",
    icon: "🕸️",
    underline: "lieth in wait at every corner",
    preview: "Lieth in wait describes an ambush, not a chance encounter.",
  },
  {
    verse: 13,
    noteTitle: "So She Caught Him, And Kissed Him",
    icon: "💋",
    underline: "So she caught him, and kissed him",
    preview: "Caught pictures a quick, decisive seizing, not a gentle greeting.",
  },
  {
    verse: 13,
    noteTitle: "With An Impudent Face",
    icon: "😏",
    underline: "with an impudent face",
    preview: "Impudent means shameless, showing no embarrassment at all.",
  },
  {
    verse: 14,
    noteTitle: "I Have Peace Offerings With Me",
    icon: "🐑",
    underline: "I have peace offerings with me",
    preview: "A peace offering was a sacrifice where the worshipper ate part of the meat.",
  },
  {
    verse: 14,
    noteTitle: "This Day Have I Payed My Vows",
    icon: "🙏",
    underline: "this day have I payed my vows",
    preview: "A vow was a conditional promise made to God, often in exchange for help.",
  },
  {
    verse: 15,
    noteTitle: "Therefore Came I Forth To Meet Thee",
    icon: "🚪",
    underline: "Therefore came I forth to meet thee",
    preview: "Therefore ties her actions directly back to the vow she just claimed.",
  },
  {
    verse: 15,
    noteTitle: "Diligently To Seek Thy Face",
    icon: "👀",
    underline: "diligently to seek thy face",
    preview: "Diligently means with real, focused effort, not a casual glance around.",
  },
  {
    verse: 15,
    noteTitle: "I Have Found Thee",
    icon: "🎯",
    underline: "I have found thee",
    preview: "Found treats him like something she was searching for, not someone she met.",
  },
  {
    verse: 16,
    noteTitle: "Decked My Bed With Coverings Of Tapestry",
    icon: "🛏️",
    underline: "decked my bed with coverings of tapestry",
    preview: "Decked means dressed up or decorated in an elaborate way.",
  },
  {
    verse: 16,
    noteTitle: "Fine Linen Of Egypt",
    icon: "🏺",
    underline: "fine linen of Egypt",
    preview: "Egypt was famous across the ancient world for producing the finest linen.",
  },
  {
    verse: 17,
    noteTitle: "Perfumed My Bed With Myrrh, Aloes, And Cinnamon",
    icon: "🌿",
    underline: "perfumed my bed with myrrh, aloes, and cinnamon",
    preview: "These three spices were rare, imported, and extremely expensive in that world.",
  },
  {
    verse: 18,
    noteTitle: "Come, Let Us Take Our Fill Of Love Until The Morning",
    icon: "🌙",
    underline: "Come, let us take our fill of love until the morning",
    preview: "This is the true point of everything staged before it.",
  },
  {
    verse: 18,
    noteTitle: "Solace Ourselves With Loves",
    icon: "🔁",
    underline: "solace ourselves with loves",
    preview: "Solace means to comfort or soothe oneself.",
  },
  {
    verse: 19,
    noteTitle: "The Goodman Is Not At Home",
    icon: "🏡",
    underline: "the goodman is not at home",
    preview: "Goodman is an old English word for the master of the house, her husband.",
  },
  {
    verse: 19,
    noteTitle: "He Is Gone A Long Journey",
    icon: "🧳",
    underline: "he is gone a long journey",
    preview: "A long journey suggested days or weeks, not a quick errand.",
  },
  {
    verse: 20,
    noteTitle: "A Bag Of Money With Him",
    icon: "💰",
    underline: "a bag of money with him",
    preview: "Mentioning money adds a believable, practical reason for the trip.",
  },
  {
    verse: 20,
    noteTitle: "Will Come Home At The Day Appointed",
    icon: "📅",
    underline: "will come home at the day appointed",
    preview: "Appointed means a fixed, agreed upon date, not a rough guess.",
  },
  {
    verse: 21,
    noteTitle: "With Her Much Fair Speech She Caused Him To Yield",
    icon: "🗣️",
    underline: "With her much fair speech she caused him to yield",
    preview: "Much fair speech means a steady flood of pleasant, persuasive words.",
  },
  {
    verse: 21,
    noteTitle: "With The Flattering Of Her Lips She Forced Him",
    icon: "🍯",
    underline: "with the flattering of her lips she forced him",
    preview: "Forced here does not mean physical force at all.",
  },
  {
    verse: 22,
    noteTitle: "He Goeth After Her Straightway",
    icon: "🚶",
    underline: "He goeth after her straightway",
    preview: "Straightway means immediately, without any pause to think.",
  },
  {
    verse: 22,
    noteTitle: "As An Ox Goeth To The Slaughter",
    icon: "🐂",
    underline: "as an ox goeth to the slaughter",
    preview: "An ox walking to slaughter has no idea what is about to happen.",
  },
  {
    verse: 22,
    noteTitle: "Or As A Fool To The Correction Of The Stocks",
    icon: "⛓️",
    underline: "or as a fool to the correction of the stocks",
    preview: "The stocks were a wooden device used to publicly restrain and punish someone.",
  },
  {
    verse: 23,
    noteTitle: "Till A Dart Strike Through His Liver",
    icon: "🏹",
    underline: "Till a dart strike through his liver",
    preview: "A dart was an old word for a small, thrown spear or arrow.",
  },
  {
    verse: 23,
    noteTitle: "As A Bird Hasteth To The Snare",
    icon: "🐦",
    underline: "as a bird hasteth to the snare",
    preview: "A snare was a hidden trap built to catch birds by surprise.",
  },
  {
    verse: 23,
    noteTitle: "And Knoweth Not That It Is For His Life",
    icon: "🕳️",
    underline: "and knoweth not that it is for his life",
    preview: "Knoweth not means total, complete ignorance of the true stakes.",
  },
  {
    verse: 24,
    noteTitle: "Hearken Unto Me Now Therefore",
    icon: "📢",
    underline: "Hearken unto me now therefore",
    preview: "Hearken means listen closely, more urgent than a simple ask to pay attention.",
  },
  {
    verse: 24,
    noteTitle: "O Ye Children",
    icon: "👶",
    underline: "O ye children",
    preview: "Children here is plural, widening the audience beyond the one son from verse one.",
  },
  {
    verse: 25,
    noteTitle: "Let Not Thine Heart Decline To Her Ways",
    icon: "💔",
    underline: "Let not thine heart decline to her ways",
    preview: "Decline means to gradually turn aside, not to suddenly leap.",
  },
  {
    verse: 25,
    noteTitle: "Go Not Astray In Her Paths",
    icon: "🛤️",
    underline: "go not astray in her paths",
    preview: "Astray means wandering off a path that was already marked and known.",
  },
  {
    verse: 26,
    noteTitle: "For She Hath Cast Down Many Wounded",
    icon: "⚔️",
    underline: "For she hath cast down many wounded",
    preview: "Cast down pictures defeat, the language of a battlefield, not a metaphor alone.",
  },
  {
    verse: 26,
    noteTitle: "Yea, Many Strong Men Have Been Slain By Her",
    icon: "💪",
    underline: "yea, many strong men have been slain by her",
    preview: "Strong men specifically means physical strength offered no protection here at all.",
  },
  {
    verse: 27,
    noteTitle: "Her House Is The Way To Hell",
    icon: "🚪",
    underline: "Her house is the way to hell",
    preview: "Hell here translates a word better understood as the grave, the realm of the dead.",
  },
  {
    verse: 27,
    noteTitle: "Going Down To The Chambers Of Death",
    icon: "🕳️",
    underline: "going down to the chambers of death",
    preview: "Chambers echoes the very bed she decked out earlier in the chapter.",
  },
];
