import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 14 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsFourteenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_FOURTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Every Wise Woman Buildeth Her House",
    icon: "🏠",
    underline: "Every wise woman buildeth her house",
    preview: "\"House\" here means more than a building.",
  },
  {
    verse: 1,
    noteTitle: "The Foolish Plucketh It Down With Her Hands",
    icon: "🔨",
    underline: "the foolish plucketh it down with her hands",
    preview: "\"Plucketh down\" means tears apart, the opposite of building.",
  },
  {
    verse: 2,
    noteTitle: "He That Walketh In His Uprightness Feareth The LORD",
    icon: "🧭",
    underline: "He that walketh in his uprightness feareth the LORD",
    preview: "\"Uprightness\" means living an honest, straight path.",
  },
  {
    verse: 2,
    noteTitle: "He That Is Perverse In His Ways Despiseth Him",
    icon: "🌀",
    underline: "he that is perverse in his ways despiseth him",
    preview: "\"Perverse\" means twisted, choosing to bend away from what is right.",
  },
  {
    verse: 3,
    noteTitle: "In The Mouth Of The Foolish Is A Rod Of Pride",
    icon: "🪵",
    underline: "In the mouth of the foolish is a rod of pride",
    preview: "\"Rod of pride\" pictures proud, arrogant speech used like a weapon.",
  },
  {
    verse: 3,
    noteTitle: "The Lips Of The Wise Shall Preserve Them",
    icon: "🛡️",
    underline: "the lips of the wise shall preserve them",
    preview: "\"Preserve\" means keep safe, protect from harm over time.",
  },
  {
    verse: 4,
    noteTitle: "Where No Oxen Are, The Crib Is Clean",
    icon: "🐂",
    underline: "Where no oxen are, the crib is clean",
    preview: "\"Crib\" means a feeding trough or stall for animals.",
  },
  {
    verse: 4,
    noteTitle: "Much Increase Is By The Strength Of The Ox",
    icon: "📈",
    underline: "much increase is by the strength of the ox",
    preview: "\"Increase\" means growth, more crops or more wealth over time.",
  },
  {
    verse: 5,
    noteTitle: "A Faithful Witness Will Not Lie",
    icon: "⚖️",
    underline: "A faithful witness will not lie",
    preview: "\"Witness\" means someone giving testimony, often in a legal case.",
  },
  {
    verse: 5,
    noteTitle: "A False Witness Will Utter Lies",
    icon: "⚠️",
    underline: "a false witness will utter lies",
    preview: "\"Utter\" means speaks out loud, states as if it were true.",
  },
  {
    verse: 6,
    noteTitle: "A Scorner Seeketh Wisdom, And Findeth It Not",
    icon: "🙄",
    underline: "A scorner seeketh wisdom, and findeth it not",
    preview: "\"Scorner\" means someone who mocks wisdom instead of respecting it.",
  },
  {
    verse: 6,
    noteTitle: "Knowledge Is Easy Unto Him That Understandeth",
    icon: "🧠",
    underline: "knowledge is easy unto him that understandeth",
    preview: "\"Understandeth\" means someone with real insight, not just information.",
  },
  {
    verse: 7,
    noteTitle: "Go From The Presence Of A Foolish Man",
    icon: "🚶",
    underline: "Go from the presence of a foolish man",
    preview: "This is a direct command, not just friendly advice.",
  },
  {
    verse: 7,
    noteTitle: "When Thou Perceivest Not In Him The Lips Of Knowledge",
    icon: "🗣️",
    underline: "when thou perceivest not in him the lips of knowledge",
    preview: "\"Perceivest\" means notice or recognize by paying attention.",
  },
  {
    verse: 8,
    noteTitle: "The Wisdom Of The Prudent Is To Understand His Way",
    icon: "🧠",
    underline: "The wisdom of the prudent is to understand his way",
    preview: "\"Prudent\" means careful and thoughtful about the direction of a life.",
  },
  {
    verse: 8,
    noteTitle: "The Folly Of Fools Is Deceit",
    icon: "🎭",
    underline: "the folly of fools is deceit",
    preview: "\"Deceit\" means dishonesty, tricking others or even tricking themselves.",
  },
  {
    verse: 9,
    noteTitle: "Fools Make A Mock At Sin",
    icon: "😂",
    underline: "Fools make a mock at sin",
    preview: "\"Make a mock\" means treat something as a joke, not serious at all.",
  },
  {
    verse: 9,
    noteTitle: "Among The Righteous There Is Favour",
    icon: "🤝",
    underline: "among the righteous there is favour",
    preview: "\"Favour\" here means goodwill, both from other people and from God.",
  },
  {
    verse: 10,
    noteTitle: "The Heart Knoweth His Own Bitterness",
    icon: "💔",
    underline: "The heart knoweth his own bitterness",
    preview: "\"Bitterness\" here means deep, private pain or grief.",
  },
  {
    verse: 10,
    noteTitle: "A Stranger Doth Not Intermeddle With His Joy",
    icon: "🎉",
    underline: "a stranger doth not intermeddle with his joy",
    preview: "\"Intermeddle\" means to fully share in or take part in something.",
  },
  {
    verse: 11,
    noteTitle: "The House Of The Wicked Shall Be Overthrown",
    icon: "💥",
    underline: "The house of the wicked shall be overthrown",
    preview: "\"Overthrown\" means violently torn down, not simply fading away.",
  },
  {
    verse: 11,
    noteTitle: "The Tabernacle Of The Upright Shall Flourish",
    icon: "⛺",
    underline: "the tabernacle of the upright shall flourish",
    preview: "\"Tabernacle\" here means a tent, a much simpler dwelling than a house.",
  },
  {
    verse: 12,
    noteTitle: "There Is A Way Which Seemeth Right Unto A Man",
    icon: "🤔",
    underline: "There is a way which seemeth right unto a man",
    preview: "\"Seemeth right\" means it genuinely feels correct from the inside.",
  },
  {
    verse: 12,
    noteTitle: "The End Thereof Are The Ways Of Death",
    icon: "🏁",
    underline: "the end thereof are the ways of death",
    preview: "\"The end thereof\" means where that confident path actually leads.",
  },
  {
    verse: 13,
    noteTitle: "Even In Laughter The Heart Is Sorrowful",
    icon: "😢",
    underline: "Even in laughter the heart is sorrowful",
    preview: "A smile can sit right on top of real, hidden grief.",
  },
  {
    verse: 13,
    noteTitle: "The End Of That Mirth Is Heaviness",
    icon: "😄",
    underline: "the end of that mirth is heaviness",
    preview: "\"Mirth\" means cheerfulness, laughter and lighthearted fun.",
  },
  {
    verse: 14,
    noteTitle: "The Backslider In Heart Shall Be Filled With His Own Ways",
    icon: "🔙",
    underline: "The backslider in heart shall be filled with his own ways",
    preview: "\"Backslider\" means someone who has turned away from following God.",
  },
  {
    verse: 14,
    noteTitle: "A Good Man Shall Be Satisfied From Himself",
    icon: "😌",
    underline: "a good man shall be satisfied from himself",
    preview: "\"Satisfied from himself\" means his contentment comes from within, not from outside praise.",
  },
  {
    verse: 15,
    noteTitle: "The Simple Believeth Every Word",
    icon: "🙋",
    underline: "The simple believeth every word",
    preview: "\"Simple\" in Proverbs means naive, not stupid, someone who has not yet learned discernment.",
  },
  {
    verse: 15,
    noteTitle: "The Prudent Man Looketh Well To His Going",
    icon: "🔍",
    underline: "the prudent man looketh well to his going",
    preview: "\"Looketh well\" means examines carefully before acting.",
  },
  {
    verse: 16,
    noteTitle: "A Wise Man Feareth, And Departeth From Evil",
    icon: "👀",
    underline: "A wise man feareth, and departeth from evil",
    preview: "\"Feareth\" here means takes danger seriously, stays alert and cautious.",
  },
  {
    verse: 16,
    noteTitle: "The Fool Rageth, And Is Confident",
    icon: "🔥",
    underline: "the fool rageth, and is confident",
    preview: "\"Rageth\" means acts recklessly, without self control.",
  },
  {
    verse: 17,
    noteTitle: "He That Is Soon Angry Dealeth Foolishly",
    icon: "🌡️",
    underline: "He that is soon angry dealeth foolishly",
    preview: "\"Soon angry\" means quick tempered, reacting before thinking.",
  },
  {
    verse: 17,
    noteTitle: "A Man Of Wicked Devices Is Hated",
    icon: "🗡️",
    underline: "a man of wicked devices is hated",
    preview: "\"Devices\" means schemes, plans made on purpose to harm someone.",
  },
  {
    verse: 18,
    noteTitle: "The Simple Inherit Folly",
    icon: "👪",
    underline: "The simple inherit folly",
    preview: "\"Inherit\" means receive automatically, the way property passes down in a family.",
  },
  {
    verse: 18,
    noteTitle: "The Prudent Are Crowned With Knowledge",
    icon: "👑",
    underline: "the prudent are crowned with knowledge",
    preview: "\"Crowned\" means honored publicly, given something valuable to wear or display.",
  },
  {
    verse: 19,
    noteTitle: "The Evil Bow Before The Good",
    icon: "🙇",
    underline: "The evil bow before the good",
    preview: "\"Bow\" pictures a posture of submission, like a servant before a master.",
  },
  {
    verse: 19,
    noteTitle: "The Wicked At The Gates Of The Righteous",
    icon: "🚪",
    underline: "the wicked at the gates of the righteous",
    preview: "\"Gates\" in an ancient city were where elders judged disputes and business was done.",
  },
  {
    verse: 20,
    noteTitle: "The Poor Is Hated Even Of His Own Neighbour",
    icon: "🏘️",
    underline: "The poor is hated even of his own neighbour",
    preview: "The word \"neighbour\" here points to someone living right nearby, not a stranger.",
  },
  {
    verse: 20,
    noteTitle: "The Rich Hath Many Friends",
    icon: "💰",
    underline: "the rich hath many friends",
    preview: "\"Many friends\" here likely includes people drawn by what wealth can offer.",
  },
  {
    verse: 21,
    noteTitle: "He That Despiseth His Neighbour Sinneth",
    icon: "🙄",
    underline: "He that despiseth his neighbour sinneth",
    preview: "\"Despiseth\" means looks down on with contempt, treats as less valuable.",
  },
  {
    verse: 21,
    noteTitle: "He That Hath Mercy On The Poor, Happy Is He",
    icon: "🤲",
    underline: "he that hath mercy on the poor, happy is he",
    preview: "\"Mercy\" here means active kindness, not just feeling bad for someone.",
  },
  {
    verse: 22,
    noteTitle: "Do They Not Err That Devise Evil?",
    icon: "🚫",
    underline: "Do they not err that devise evil?",
    preview: "\"Err\" means go astray, miss the right path entirely.",
  },
  {
    verse: 22,
    noteTitle: "Mercy And Truth Shall Be To Them That Devise Good",
    icon: "🌱",
    underline: "mercy and truth shall be to them that devise good",
    preview: "\"Devise good\" mirrors the evil scheming just named, but aimed the opposite way.",
  },
  {
    verse: 23,
    noteTitle: "In All Labour There Is Profit",
    icon: "💪",
    underline: "In all labour there is profit",
    preview: "\"Labour\" means real, sustained work, not a single burst of effort.",
  },
  {
    verse: 23,
    noteTitle: "The Talk Of The Lips Tendeth Only To Penury",
    icon: "🗣️",
    underline: "the talk of the lips tendeth only to penury",
    preview: "\"Tendeth\" means leads toward, moves in that direction over time.",
  },
  {
    verse: 24,
    noteTitle: "The Crown Of The Wise Is Their Riches",
    icon: "👑",
    underline: "The crown of the wise is their riches",
    preview: "\"Crown\" means the visible mark of honor a person wears or carries.",
  },
  {
    verse: 24,
    noteTitle: "The Foolishness Of Fools Is Folly",
    icon: "🔁",
    underline: "the foolishness of fools is folly",
    preview: "This line is repetitive on purpose, foolishness produces nothing but more foolishness.",
  },
  {
    verse: 25,
    noteTitle: "A True Witness Delivereth Souls",
    icon: "⚖️",
    underline: "A true witness delivereth souls",
    preview: "\"Delivereth\" means rescues or saves from real danger.",
  },
  {
    verse: 25,
    noteTitle: "A Deceitful Witness Speaketh Lies",
    icon: "🎭",
    underline: "a deceitful witness speaketh lies",
    preview: "\"Deceitful\" means intentionally dishonest, not simply mistaken.",
  },
  {
    verse: 26,
    noteTitle: "In The Fear Of The LORD Is Strong Confidence",
    icon: "🙏",
    underline: "In the fear of the LORD is strong confidence",
    preview: "\"Fear of the LORD\" means taking God seriously, with real reverence and awe.",
  },
  {
    verse: 26,
    noteTitle: "His Children Shall Have A Place Of Refuge",
    icon: "🏠",
    underline: "his children shall have a place of refuge",
    preview: "\"Refuge\" means a safe place to run to when danger comes.",
  },
  {
    verse: 27,
    noteTitle: "The Fear Of The LORD Is A Fountain Of Life",
    icon: "⛲",
    underline: "The fear of the LORD is a fountain of life",
    preview: "\"Fountain of life\" pictures a spring of fresh water in a dry, thirsty land.",
  },
  {
    verse: 27,
    noteTitle: "To Depart From The Snares Of Death",
    icon: "🪤",
    underline: "to depart from the snares of death",
    preview: "\"Snares\" pictures hidden traps set to catch something unaware.",
  },
  {
    verse: 28,
    noteTitle: "In The Multitude Of People Is The King's Honour",
    icon: "👥",
    underline: "In the multitude of people is the king’s honour",
    preview: "\"Multitude\" means a large number, a nation full of people.",
  },
  {
    verse: 28,
    noteTitle: "In The Want Of People Is The Destruction Of The Prince",
    icon: "📉",
    underline: "in the want of people is the destruction of the prince",
    preview: "\"Want\" here means lack, a shortage instead of an abundance.",
  },
  {
    verse: 29,
    noteTitle: "He That Is Slow To Wrath Is Of Great Understanding",
    icon: "⏳",
    underline: "He that is slow to wrath is of great understanding",
    preview: "\"Slow to wrath\" means someone who takes real time before reacting in anger.",
  },
  {
    verse: 29,
    noteTitle: "He That Is Hasty Of Spirit Exalteth Folly",
    icon: "⚡",
    underline: "he that is hasty of spirit exalteth folly",
    preview: "\"Hasty of spirit\" means quick to react without thinking first.",
  },
  {
    verse: 30,
    noteTitle: "A Sound Heart Is The Life Of The Flesh",
    icon: "❤️",
    underline: "A sound heart is the life of the flesh",
    preview: "\"Sound heart\" means a calm, healthy inner life, free from constant turmoil.",
  },
  {
    verse: 30,
    noteTitle: "Envy The Rottenness Of The Bones",
    icon: "💔",
    underline: "envy the rottenness of the bones",
    preview: "\"Envy\" means resentment toward what someone else has.",
  },
  {
    verse: 31,
    noteTitle: "He That Oppresseth The Poor Reproacheth His Maker",
    icon: "⚠️",
    underline: "He that oppresseth the poor reproacheth his Maker",
    preview: "\"Oppresseth\" means treats unjustly, takes advantage of someone with less power.",
  },
  {
    verse: 31,
    noteTitle: "He That Honoureth Him Hath Mercy On The Poor",
    icon: "🙏",
    underline: "he that honoureth him hath mercy on the poor",
    preview: "The word \"him\" here refers back to God, the Maker just named.",
  },
  {
    verse: 32,
    noteTitle: "The Wicked Is Driven Away In His Wickedness",
    icon: "💨",
    underline: "The wicked is driven away in his wickedness",
    preview: "\"Driven away\" pictures a forceful, sudden removal, not a slow fade.",
  },
  {
    verse: 32,
    noteTitle: "The Righteous Hath Hope In His Death",
    icon: "🌅",
    underline: "the righteous hath hope in his death",
    preview: "\"Hope\" here means real confidence about what comes after this life.",
  },
  {
    verse: 33,
    noteTitle: "Wisdom Resteth In The Heart Of Him That Hath Understanding",
    icon: "🏠",
    underline: "Wisdom resteth in the heart of him that hath understanding",
    preview: "\"Resteth\" means settles in and stays, not a passing visit.",
  },
  {
    verse: 33,
    noteTitle: "That Which Is In The Midst Of Fools Is Made Known",
    icon: "📢",
    underline: "that which is in the midst of fools is made known",
    preview: "\"Made known\" means eventually comes out into the open for everyone to see.",
  },
  {
    verse: 34,
    noteTitle: "Righteousness Exalteth A Nation",
    icon: "⬆️",
    underline: "Righteousness exalteth a nation",
    preview: "\"Exalteth\" means lifts up, raises to a place of honor.",
  },
  {
    verse: 34,
    noteTitle: "Sin Is A Reproach To Any People",
    icon: "😳",
    underline: "sin is a reproach to any people",
    preview: "\"Reproach\" means public shame, disgrace in front of others.",
  },
  {
    verse: 35,
    noteTitle: "The King's Favour Is Toward A Wise Servant",
    icon: "🤝",
    underline: "The king’s favour is toward a wise servant",
    preview: "\"Favour\" means goodwill and approval from someone in power.",
  },
  {
    verse: 35,
    noteTitle: "His Wrath Is Against Him That Causeth Shame",
    icon: "🔥",
    underline: "his wrath is against him that causeth shame",
    preview: "\"Wrath\" here means real anger, backed by real power to punish.",
  },
];
