import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 11 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsElevenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_ELEVEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "A False Balance Is Abomination To The LORD",
    icon: "⚖️",
    underline: "A false balance is abomination to the LORD",
    preview: "\"Balance\" here means a merchant's scale, used to weigh goods in the marketplace.",
  },
  {
    verse: 1,
    noteTitle: "A Just Weight Is His Delight",
    icon: "❤️",
    underline: "a just weight is his delight",
    preview: "A \"just weight\" is an honest, accurate measure, the opposite of the rigged scale.",
  },
  {
    verse: 2,
    noteTitle: "When Pride Cometh, Then Cometh Shame",
    icon: "👑",
    underline: "When pride cometh, then cometh shame",
    preview: "\"Pride\" means an inflated view of oneself that refuses correction.",
  },
  {
    verse: 2,
    noteTitle: "With The Lowly Is Wisdom",
    icon: "🙇",
    underline: "with the lowly is wisdom",
    preview: "The \"lowly\" are people who do not overrate themselves and stay willing to be taught.",
  },
  {
    verse: 3,
    noteTitle: "The Integrity Of The Upright Shall Guide Them",
    icon: "🧩",
    underline: "The integrity of the upright shall guide them",
    preview: "\"Integrity\" means being whole, the same person in private as in public.",
  },
  {
    verse: 3,
    noteTitle: "The Perverseness Of Transgressors Shall Destroy Them",
    icon: "🌀",
    underline: "the perverseness of transgressors shall destroy them",
    preview: "\"Perverseness\" means a twisted, crooked way of living, chosen on purpose.",
  },
  {
    verse: 4,
    noteTitle: "Riches Profit Not In The Day Of Wrath",
    icon: "💰",
    underline: "Riches profit not in the day of wrath",
    preview: "The \"day of wrath\" refers to a moment of God's judgment, not simply a hard day.",
  },
  {
    verse: 4,
    noteTitle: "Righteousness Delivereth From Death",
    icon: "🛟",
    underline: "righteousness delivereth from death",
    preview: "\"Death\" here often pictures ruin or being cut off from God, not only physical dying.",
  },
  {
    verse: 5,
    noteTitle: "The Righteousness Of The Perfect Shall Direct His Way",
    icon: "🛤️",
    underline: "The righteousness of the perfect shall direct his way",
    preview: "\"Perfect\" here does not mean flawless, it means blameless or fully devoted to God.",
  },
  {
    verse: 5,
    noteTitle: "The Wicked Shall Fall By His Own Wickedness",
    icon: "🪤",
    underline: "the wicked shall fall by his own wickedness",
    preview: "\"Fall by his own wickedness\" means the wicked person's downfall grows out of their own choices.",
  },
  {
    verse: 6,
    noteTitle: "The Righteousness Of The Upright Shall Deliver Them",
    icon: "🛟",
    underline: "The righteousness of the upright shall deliver them",
    preview: "\"Deliver\" means to rescue someone out of real danger.",
  },
  {
    verse: 6,
    noteTitle: "Transgressors Shall Be Taken In Their Own Naughtiness",
    icon: "🪤",
    underline: "transgressors shall be taken in their own naughtiness",
    preview: "\"Naughtiness\" is a strong old word for wickedness, not childish mischief.",
  },
  {
    verse: 7,
    noteTitle: "When A Wicked Man Dieth, His Expectation Shall Perish",
    icon: "🎯",
    underline: "When a wicked man dieth, his expectation shall perish",
    preview: "\"Expectation\" means whatever the wicked person was counting on for the future.",
  },
  {
    verse: 7,
    noteTitle: "The Hope Of Unjust Men Perisheth",
    icon: "🔁",
    underline: "the hope of unjust men perisheth",
    preview: "\"Unjust men\" repeats the same idea as \"wicked man\" from the first half of the verse.",
  },
  {
    verse: 8,
    noteTitle: "The Righteous Is Delivered Out Of Trouble",
    icon: "🛟",
    underline: "The righteous is delivered out of trouble",
    preview: "\"Delivered out of trouble\" means rescued from a difficulty already in progress.",
  },
  {
    verse: 8,
    noteTitle: "The Wicked Cometh In His Stead",
    icon: "🔄",
    underline: "the wicked cometh in his stead",
    preview: "\"In his stead\" means taking that very place, stepping into the trouble instead.",
  },
  {
    verse: 9,
    noteTitle: "An Hypocrite With His Mouth Destroyeth His Neighbour",
    icon: "🗣️",
    underline: "An hypocrite with his mouth destroyeth his neighbour",
    preview: "A \"hypocrite\" here is someone who says one thing while meaning another.",
  },
  {
    verse: 9,
    noteTitle: "Through Knowledge Shall The Just Be Delivered",
    icon: "📚",
    underline: "through knowledge shall the just be delivered",
    preview: "\"Knowledge\" here means real, godly understanding, not simply information.",
  },
  {
    verse: 10,
    noteTitle: "When It Goeth Well With The Righteous, The City Rejoiceth",
    icon: "🏙️",
    underline: "When it goeth well with the righteous, the city rejoiceth",
    preview: "This describes a whole community's reaction, not just one family's own joy.",
  },
  {
    verse: 10,
    noteTitle: "When The Wicked Perish, There Is Shouting",
    icon: "📢",
    underline: "when the wicked perish, there is shouting",
    preview: "\"Shouting\" pictures open, public celebration, not quiet relief.",
  },
  {
    verse: 11,
    noteTitle: "By The Blessing Of The Upright The City Is Exalted",
    icon: "🙌",
    underline: "By the blessing of the upright the city is exalted",
    preview: "\"Blessing\" here means the good influence and favor an upright person brings with them.",
  },
  {
    verse: 11,
    noteTitle: "It Is Overthrown By The Mouth Of The Wicked",
    icon: "💥",
    underline: "it is overthrown by the mouth of the wicked",
    preview: "\"Overthrown\" means torn down, brought to ruin.",
  },
  {
    verse: 12,
    noteTitle: "He That Is Void Of Wisdom Despiseth His Neighbour",
    icon: "👎",
    underline: "He that is void of wisdom despiseth his neighbour",
    preview: "\"Void of wisdom\" means genuinely lacking it, not simply young or untrained.",
  },
  {
    verse: 12,
    noteTitle: "A Man Of Understanding Holdeth His Peace",
    icon: "🤐",
    underline: "a man of understanding holdeth his peace",
    preview: "\"Holdeth his peace\" means choosing to stay quiet rather than speak carelessly.",
  },
  {
    verse: 13,
    noteTitle: "A Talebearer Revealeth Secrets",
    icon: "🗣️",
    underline: "A talebearer revealeth secrets",
    preview: "A \"talebearer\" is someone who spreads private information for their own gain or entertainment.",
  },
  {
    verse: 13,
    noteTitle: "He That Is Of A Faithful Spirit Concealeth The Matter",
    icon: "🤝",
    underline: "he that is of a faithful spirit concealeth the matter",
    preview: "A \"faithful spirit\" means someone who is trustworthy and reliable at their core.",
  },
  {
    verse: 14,
    noteTitle: "Where No Counsel Is, The People Fall",
    icon: "🗺️",
    underline: "Where no counsel is, the people fall",
    preview: "\"Counsel\" here means wise guidance, especially from leaders making decisions for a group.",
  },
  {
    verse: 14,
    noteTitle: "In The Multitude Of Counsellors There Is Safety",
    icon: "👥",
    underline: "in the multitude of counsellors there is safety",
    preview: "\"Multitude of counsellors\" means gathering advice from more than one wise source.",
  },
  {
    verse: 15,
    noteTitle: "He That Is Surety For A Stranger Shall Smart For It",
    icon: "📜",
    underline: "He that is surety for a stranger shall smart for it",
    preview: "\"Surety\" means legally promising to pay someone else's debt if they cannot.",
  },
  {
    verse: 15,
    noteTitle: "He That Hateth Suretiship Is Sure",
    icon: "🔒",
    underline: "he that hateth suretiship is sure",
    preview: "\"Hateth suretiship\" means strongly avoiding this kind of risky guarantee altogether.",
  },
  {
    verse: 16,
    noteTitle: "A Gracious Woman Retaineth Honour",
    icon: "🕊️",
    underline: "A gracious woman retaineth honour",
    preview: "\"Gracious\" here means kind, dignified, and marked by good character.",
  },
  {
    verse: 16,
    noteTitle: "Strong Men Retain Riches",
    icon: "💪",
    underline: "strong men retain riches",
    preview: "\"Strong\" here likely points to diligence and effort, not simply physical strength.",
  },
  {
    verse: 17,
    noteTitle: "The Merciful Man Doeth Good To His Own Soul",
    icon: "🔁",
    underline: "The merciful man doeth good to his own soul",
    preview: "\"Merciful\" means showing kindness to people who could not force it or repay it.",
  },
  {
    verse: 17,
    noteTitle: "He That Is Cruel Troubleth His Own Flesh",
    icon: "🔪",
    underline: "he that is cruel troubleth his own flesh",
    preview: "\"Cruel\" means someone who deliberately causes pain or harm to others.",
  },
  {
    verse: 18,
    noteTitle: "The Wicked Worketh A Deceitful Work",
    icon: "🎭",
    underline: "The wicked worketh a deceitful work",
    preview: "\"Deceitful work\" means effort built on lies or dishonest gain.",
  },
  {
    verse: 18,
    noteTitle: "To Him That Soweth Righteousness Shall Be A Sure Reward",
    icon: "🌱",
    underline: "to him that soweth righteousness shall be a sure reward",
    preview: "\"Soweth\" pictures planting seed, an image for actions that grow into a result later.",
  },
  {
    verse: 19,
    noteTitle: "As Righteousness Tendeth To Life",
    icon: "🛤️",
    underline: "As righteousness tendeth to life",
    preview: "\"Tendeth\" means moves steadily toward, already seen earlier in chapter ten.",
  },
  {
    verse: 19,
    noteTitle: "He That Pursueth Evil Pursueth It To His Own Death",
    icon: "🏃",
    underline: "he that pursueth evil pursueth it to his own death",
    preview: "\"Pursueth\" means actively chasing after something, not simply stumbling into it.",
  },
  {
    verse: 20,
    noteTitle: "They That Are Of A Froward Heart Are Abomination To The LORD",
    icon: "🌀",
    underline: "They that are of a froward heart are abomination to the LORD",
    preview: "\"Froward\" means stubborn and deliberately twisted, already seen back in chapter ten.",
  },
  {
    verse: 20,
    noteTitle: "Such As Are Upright In Their Way Are His Delight",
    icon: "🙌",
    underline: "such as are upright in their way are his delight",
    preview: "\"Upright in their way\" means honest and consistent across a whole pattern of living.",
  },
  {
    verse: 21,
    noteTitle: "Though Hand Join In Hand, The Wicked Shall Not Be Unpunished",
    icon: "🤝",
    underline: "Though hand join in hand, the wicked shall not be unpunished",
    preview: "\"Hand join in hand\" was likely an idiom for making an alliance or a solemn agreement.",
  },
  {
    verse: 21,
    noteTitle: "The Seed Of The Righteous Shall Be Delivered",
    icon: "🌱",
    underline: "the seed of the righteous shall be delivered",
    preview: "\"Seed\" here means descendants, a person's children and family line.",
  },
  {
    verse: 22,
    noteTitle: "As A Jewel Of Gold In A Swine's Snout",
    icon: "💍",
    underline: "As a jewel of gold in a swine’s snout",
    preview: "A \"jewel of gold\" was a genuinely valuable ornament in this culture.",
  },
  {
    verse: 22,
    noteTitle: "So Is A Fair Woman Which Is Without Discretion",
    icon: "🧠",
    underline: "so is a fair woman which is without discretion",
    preview: "\"Fair\" here means physically beautiful, an outward quality.",
  },
  {
    verse: 23,
    noteTitle: "The Desire Of The Righteous Is Only Good",
    icon: "❤️",
    underline: "The desire of the righteous is only good",
    preview: "\"Desire\" here means what a righteous person actually wants deep down.",
  },
  {
    verse: 23,
    noteTitle: "The Expectation Of The Wicked Is Wrath",
    icon: "⚖️",
    underline: "the expectation of the wicked is wrath",
    preview: "\"Expectation\" here means what the wicked person is ultimately heading toward.",
  },
  {
    verse: 24,
    noteTitle: "There Is That Scattereth, And Yet Increaseth",
    icon: "🌾",
    underline: "There is that scattereth, and yet increaseth",
    preview: "\"Scattereth\" pictures generous giving, like a farmer scattering seed widely.",
  },
  {
    verse: 24,
    noteTitle: "There Is That Withholdeth More Than Is Meet, But It Tendeth To Poverty",
    icon: "📉",
    underline: "there is that withholdeth more than is meet, but it tendeth to poverty",
    preview: "\"Withholdeth more than is meet\" means holding back more than is right or fair.",
  },
  {
    verse: 25,
    noteTitle: "The Liberal Soul Shall Be Made Fat",
    icon: "🍞",
    underline: "The liberal soul shall be made fat",
    preview: "\"Liberal\" here means generous, freely giving to others.",
  },
  {
    verse: 25,
    noteTitle: "He That Watereth Shall Be Watered Also Himself",
    icon: "💧",
    underline: "he that watereth shall be watered also himself",
    preview: "\"Watereth\" pictures someone pouring out for another person's growth, like watering a plant.",
  },
  {
    verse: 26,
    noteTitle: "He That Withholdeth Corn, The People Shall Curse Him",
    icon: "🌾",
    underline: "He that withholdeth corn, the people shall curse him",
    preview: "\"Corn\" here means grain in general, the basic food supply of the region.",
  },
  {
    verse: 26,
    noteTitle: "Blessing Shall Be Upon The Head Of Him That Selleth It",
    icon: "🙌",
    underline: "blessing shall be upon the head of him that selleth it",
    preview: "\"Selleth it\" means releasing grain into the market at a fair time instead of hoarding it.",
  },
  {
    verse: 27,
    noteTitle: "He That Diligently Seeketh Good Procureth Favour",
    icon: "🔍",
    underline: "He that diligently seeketh good procureth favour",
    preview: "\"Diligently seeketh\" means actively pursuing something, not passively hoping for it.",
  },
  {
    verse: 27,
    noteTitle: "He That Seeketh Mischief, It Shall Come Unto Him",
    icon: "😈",
    underline: "he that seeketh mischief, it shall come unto him",
    preview: "\"Mischief\" here means deliberate harm or wrongdoing, the same word seen back in chapter ten.",
  },
  {
    verse: 28,
    noteTitle: "He That Trusteth In His Riches Shall Fall",
    icon: "💰",
    underline: "He that trusteth in his riches shall fall",
    preview: "\"Trusteth in his riches\" means treating wealth as the real source of security.",
  },
  {
    verse: 28,
    noteTitle: "The Righteous Shall Flourish As A Branch",
    icon: "🌿",
    underline: "the righteous shall flourish as a branch",
    preview: "\"Flourish as a branch\" pictures healthy, visible, ongoing growth, like a living tree.",
  },
  {
    verse: 29,
    noteTitle: "He That Troubleth His Own House Shall Inherit The Wind",
    icon: "🏠",
    underline: "He that troubleth his own house shall inherit the wind",
    preview: "\"Troubleth his own house\" means bringing conflict or ruin onto one's own family.",
  },
  {
    verse: 29,
    noteTitle: "The Fool Shall Be Servant To The Wise Of Heart",
    icon: "🧑‍🤝‍🧑",
    underline: "the fool shall be servant to the wise of heart",
    preview: "\"Servant\" here pictures being placed under someone else's authority and direction.",
  },
  {
    verse: 30,
    noteTitle: "The Fruit Of The Righteous Is A Tree Of Life",
    icon: "🌳",
    underline: "The fruit of the righteous is a tree of life",
    preview: "\"Fruit\" here means the visible results a righteous life produces, echoing the tree imagery from chapter ten.",
  },
  {
    verse: 30,
    noteTitle: "He That Winneth Souls Is Wise",
    icon: "🧑‍🤝‍🧑",
    underline: "he that winneth souls is wise",
    preview: "\"Winneth souls\" means helping guide other people toward wisdom and God.",
  },
  {
    verse: 31,
    noteTitle: "Behold, The Righteous Shall Be Recompensed In The Earth",
    icon: "👀",
    underline: "Behold, the righteous shall be recompensed in the earth",
    preview: "\"Behold\" signals that something important and worth pausing on is about to be said.",
  },
  {
    verse: 31,
    noteTitle: "Much More The Wicked And The Sinner",
    icon: "📈",
    underline: "much more the wicked and the sinner",
    preview: "\"Much more\" makes an argument from the lesser case to the greater one.",
  },
];
