import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 18 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsEighteenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_EIGHTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Through Desire A Man, Having Separated Himself",
    icon: "🚪",
    underline: "Through desire a man, having separated himself,",
    preview: "\"Desire\" here means a man's own selfish want.",
  },
  {
    verse: 1,
    noteTitle: "Seeketh And Intermeddleth With All Wisdom",
    icon: "⚔️",
    underline: "seeketh and intermeddleth with all wisdom.",
    preview: "\"Intermeddleth\" means picks a fight with something.",
  },
  {
    verse: 2,
    noteTitle: "A Fool Hath No Delight In Understanding",
    icon: "🙄",
    underline: "A fool hath no delight in understanding,",
    preview: "A \"fool\" in Proverbs means someone who rejects wisdom on purpose.",
  },
  {
    verse: 2,
    noteTitle: "But That His Heart May Discover Itself",
    icon: "🗣️",
    underline: "but that his heart may discover itself.",
    preview: "\"Discover\" here is an old word for reveal or expose.",
  },
  {
    verse: 3,
    noteTitle: "When The Wicked Cometh, Then Cometh Also Contempt",
    icon: "😤",
    underline: "When the wicked cometh, then cometh also contempt,",
    preview: "\"Contempt\" means open scorn toward someone.",
  },
  {
    verse: 3,
    noteTitle: "And With Ignominy Reproach",
    icon: "😳",
    underline: "and with ignominy reproach.",
    preview: "\"Ignominy\" means public shame and disgrace.",
  },
  {
    verse: 4,
    noteTitle: "The Words Of A Man's Mouth Are As Deep Waters",
    icon: "🌊",
    underline: "The words of a man’s mouth are as deep waters,",
    preview: "\"Deep waters\" pictures something with a hidden bottom.",
  },
  {
    verse: 4,
    noteTitle: "And The Wellspring Of Wisdom As A Flowing Brook",
    icon: "💧",
    underline: "and the wellspring of wisdom as a flowing brook.",
    preview: "A wellspring is a natural spring where water rises from the ground.",
  },
  {
    verse: 5,
    noteTitle: "To Accept The Person Of The Wicked",
    icon: "⚖️",
    underline: "It is not good to accept the person of the wicked,",
    preview: "\"Accept the person\" is an old idiom for favoritism.",
  },
  {
    verse: 5,
    noteTitle: "To Overthrow The Righteous In Judgment",
    icon: "🧑‍⚖️",
    underline: "to overthrow the righteous in judgment.",
    preview: "\"Overthrow\" here means to wrongly defeat someone in court.",
  },
  {
    verse: 6,
    noteTitle: "A Fool's Lips Enter Into Contention",
    icon: "🗣️",
    underline: "A fool’s lips enter into contention,",
    preview: "\"Contention\" means an ongoing argument or quarrel.",
  },
  {
    verse: 6,
    noteTitle: "And His Mouth Calleth For Strokes",
    icon: "👊",
    underline: "and his mouth calleth for strokes.",
    preview: "\"Strokes\" here means physical blows or a beating.",
  },
  {
    verse: 7,
    noteTitle: "A Fool's Mouth Is His Destruction",
    icon: "💥",
    underline: "A fool’s mouth is his destruction,",
    preview: "A fool does not need an outside enemy to ruin him.",
  },
  {
    verse: 7,
    noteTitle: "And His Lips Are The Snare Of His Soul",
    icon: "🪤",
    underline: "and his lips are the snare of his soul.",
    preview: "A \"snare\" is a trap used to catch an animal by surprise.",
  },
  {
    verse: 8,
    noteTitle: "The Words Of A Talebearer Are As Wounds",
    icon: "🗣️",
    underline: "The words of a talebearer are as wounds,",
    preview: "A \"talebearer\" is someone who spreads gossip and rumors.",
  },
  {
    verse: 8,
    noteTitle: "And They Go Down Into The Innermost Parts Of The Belly",
    icon: "🍽️",
    underline: "and they go down into the innermost parts of the belly.",
    preview: "\"Innermost parts of the belly\" is a Hebrew way of saying deep inside a person.",
  },
  {
    verse: 9,
    noteTitle: "He Also That Is Slothful In His Work",
    icon: "🐌",
    underline: "He also that is slothful in his work",
    preview: "\"Slothful\" means lazy and unwilling to work.",
  },
  {
    verse: 9,
    noteTitle: "Is Brother To Him That Is A Great Waster",
    icon: "💣",
    underline: "is brother to him that is a great waster.",
    preview: "A \"waster\" actively destroys or ruins what he has.",
  },
  {
    verse: 10,
    noteTitle: "The Name Of The LORD Is A Strong Tower",
    icon: "🗼",
    underline: "The name of the LORD is a strong tower:",
    preview: "A \"strong tower\" was a fortified place people ran to for safety.",
  },
  {
    verse: 10,
    noteTitle: "The Righteous Runneth Into It, And Is Safe",
    icon: "🏃",
    underline: "the righteous runneth into it, and is safe.",
    preview: "\"Runneth\" means moving fast and with real purpose.",
  },
  {
    verse: 11,
    noteTitle: "The Rich Man's Wealth Is His Strong City",
    icon: "🏙️",
    underline: "The rich man’s wealth is his strong city,",
    preview: "A \"strong city\" here echoes the strong tower from verse ten.",
  },
  {
    verse: 11,
    noteTitle: "And As An High Wall In His Own Conceit",
    icon: "🧠",
    underline: "and as an high wall in his own conceit.",
    preview: "\"Conceit\" here is an old word for his own imagination or opinion.",
  },
  {
    verse: 12,
    noteTitle: "Before Destruction The Heart Of Man Is Haughty",
    icon: "🙄",
    underline: "Before destruction the heart of man is haughty,",
    preview: "\"Haughty\" means proud and looking down on other people.",
  },
  {
    verse: 12,
    noteTitle: "And Before Honour Is Humility",
    icon: "🙇",
    underline: "and before honour is humility.",
    preview: "Humility means putting yourself lower than you have to.",
  },
  {
    verse: 13,
    noteTitle: "He That Answereth A Matter Before He Heareth It",
    icon: "✋",
    underline: "He that answereth a matter before he heareth it,",
    preview: "Answering early means forming a verdict too soon.",
  },
  {
    verse: 13,
    noteTitle: "It Is Folly And Shame Unto Him",
    icon: "🙈",
    underline: "it is folly and shame unto him.",
    preview: "\"Folly\" means a failure in judgment.",
  },
  {
    verse: 14,
    noteTitle: "The Spirit Of A Man Will Sustain His Infirmity",
    icon: "🤒",
    underline: "The spirit of a man will sustain his infirmity;",
    preview: "\"Infirmity\" means physical sickness or weakness.",
  },
  {
    verse: 14,
    noteTitle: "But A Wounded Spirit Who Can Bear",
    icon: "💔",
    underline: "but a wounded spirit who can bear?",
    preview: "A \"wounded spirit\" means being crushed emotionally or mentally.",
  },
  {
    verse: 15,
    noteTitle: "The Heart Of The Prudent Getteth Knowledge",
    icon: "🧠",
    underline: "The heart of the prudent getteth knowledge;",
    preview: "\"Prudent\" means careful and sensible in making decisions.",
  },
  {
    verse: 15,
    noteTitle: "And The Ear Of The Wise Seeketh Knowledge",
    icon: "👂",
    underline: "and the ear of the wise seeketh knowledge.",
    preview: "\"Seeketh\" means actively searches, not just happens to hear.",
  },
  {
    verse: 16,
    noteTitle: "A Man's Gift Maketh Room For Him",
    icon: "🎁",
    underline: "A man’s gift maketh room for him,",
    preview: "In this culture a gift was often given before a request.",
  },
  {
    verse: 16,
    noteTitle: "And Bringeth Him Before Great Men",
    icon: "👑",
    underline: "and bringeth him before great men.",
    preview: "\"Great men\" means people with real power or authority.",
  },
  {
    verse: 17,
    noteTitle: "He That Is First In His Own Cause Seemeth Just",
    icon: "🗣️",
    underline: "He that is first in his own cause seemeth just;",
    preview: "One story, told alone, almost always sounds convincing.",
  },
  {
    verse: 17,
    noteTitle: "But His Neighbour Cometh And Searcheth Him",
    icon: "🔎",
    underline: "but his neighbour cometh and searcheth him.",
    preview: "\"Searcheth\" means examines closely.",
  },
  {
    verse: 18,
    noteTitle: "The Lot Causeth Contentions To Cease",
    icon: "🎲",
    underline: "The lot causeth contentions to cease,",
    preview: "Casting the lot meant using an object like a stone to make a decision by chance.",
  },
  {
    verse: 18,
    noteTitle: "And Parteth Between The Mighty",
    icon: "💪",
    underline: "and parteth between the mighty.",
    preview: "\"The mighty\" means powerful and strong willed people.",
  },
  {
    verse: 19,
    noteTitle: "A Brother Offended Is Harder To Be Won Than A Strong City",
    icon: "🏰",
    underline: "A brother offended is harder to be won than a strong city:",
    preview: "A \"strong city\" was protected by thick walls built to survive a siege.",
  },
  {
    verse: 19,
    noteTitle: "And Their Contentions Are Like The Bars Of A Castle",
    icon: "🔒",
    underline: "and their contentions are like the bars of a castle.",
    preview: "\"Bars\" here means the iron bars that locked a gate shut.",
  },
  {
    verse: 20,
    noteTitle: "A Man's Belly Shall Be Satisfied With The Fruit Of His Mouth",
    icon: "🍽️",
    underline: "A man’s belly shall be satisfied with the fruit of his mouth;",
    preview: "\"Fruit of his mouth\" pictures words as something a person eats.",
  },
  {
    verse: 20,
    noteTitle: "And With The Increase Of His Lips Shall He Be Filled",
    icon: "📈",
    underline: "and with the increase of his lips shall he be filled.",
    preview: "\"Increase\" here means whatever a person's words produce over time.",
  },
  {
    verse: 21,
    noteTitle: "Death And Life Are In The Power Of The Tongue",
    icon: "💚",
    underline: "Death and life are in the power of the tongue:",
    preview: "Words can genuinely heal, encourage, or build someone up.",
  },
  {
    verse: 21,
    noteTitle: "And They That Love It Shall Eat The Fruit Thereof",
    icon: "🗣️",
    underline: "and they that love it shall eat the fruit thereof.",
    preview: "\"Love it\" here means loving the tongue's power to speak freely.",
  },
  {
    verse: 22,
    noteTitle: "Whoso Findeth A Wife Findeth A Good Thing",
    icon: "🔍",
    underline: "Whoso findeth a wife findeth a good thing,",
    preview: "\"Findeth\" pictures active searching, not something accidental.",
  },
  {
    verse: 22,
    noteTitle: "And Obtaineth Favour Of The LORD",
    icon: "🙏",
    underline: "and obtaineth favour of the LORD.",
    preview: "\"Favour\" here means God's kindness or approval.",
  },
  {
    verse: 23,
    noteTitle: "The Poor Useth Intreaties",
    icon: "🙏",
    underline: "The poor useth intreaties;",
    preview: "\"Intreaties\" means humble pleading requests.",
  },
  {
    verse: 23,
    noteTitle: "But The Rich Answereth",
    icon: "😠",
    underline: "but the rich answereth roughly.",
    preview: "Wealth here can sound hard and impatient.",
  },
  {
    verse: 24,
    noteTitle: "A Man That Hath Friends Must Shew Himself Friendly",
    icon: "🤝",
    underline: "A man that hath friends must shew himself friendly:",
    preview: "\"Shew himself friendly\" means acting like a real friend.",
  },
  {
    verse: 24,
    noteTitle: "And There Is A Friend That Sticketh Closer Than A Brother",
    icon: "💎",
    underline: "and there is a friend that sticketh closer than a brother.",
    preview: "In this culture a brother carried the strongest possible family loyalty.",
  },
];
