import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 8 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsEightSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_EIGHT_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Doth Not Wisdom Cry",
    icon: "🌅",
    underline: "Doth not wisdom cry",
    preview: "This opens with a question that expects the answer yes.",
  },
  {
    verse: 1,
    noteTitle: "Understanding Put Forth Her Voice",
    icon: "🗣️",
    underline: "understanding put forth her voice",
    preview: "Understanding here stands beside wisdom as a second figure given a voice.",
  },
  {
    verse: 2,
    noteTitle: "In The Top Of High Places",
    icon: "🏔️",
    underline: "in the top of high places",
    preview: "High places in this culture were the most visible, most traveled spots in a town.",
  },
  {
    verse: 2,
    noteTitle: "By The Way In The Places Of The Paths",
    icon: "🛤️",
    underline: "by the way in the places of the paths",
    preview: "This names the exact spot where multiple roads crossed.",
  },
  {
    verse: 3,
    noteTitle: "At The Gates, At The Entry Of The City",
    icon: "🚪",
    underline: "at the gates, at the entry of the city",
    preview: "The city gate was the ancient world's courtroom, marketplace, and news center.",
  },
  {
    verse: 3,
    noteTitle: "At The Coming In At The Doors",
    icon: "🏙️",
    underline: "at the coming in at the doors",
    preview: "This repeats the gate image once more using a different word.",
  },
  {
    verse: 4,
    noteTitle: "Unto You, O Men, I Call",
    icon: "📣",
    underline: "Unto you, O men, I call",
    preview: "Wisdom addresses her call directly rather than sending a messenger.",
  },
  {
    verse: 4,
    noteTitle: "My Voice Is To The Sons Of Man",
    icon: "👥",
    underline: "my voice is to the sons of man",
    preview: "Sons of man is simply an old way of saying humanity in general.",
  },
  {
    verse: 5,
    noteTitle: "O Ye Simple, Understand Wisdom",
    icon: "🙈",
    underline: "O ye simple, understand wisdom",
    preview: "Simple again means untrained and easily led, not stupid.",
  },
  {
    verse: 5,
    noteTitle: "Ye Fools, Be Ye Of An Understanding Heart",
    icon: "🙅",
    underline: "ye fools, be ye of an understanding heart",
    preview: "A fool in Proverbs rejects wisdom on purpose, not someone who lacks intelligence.",
  },
  {
    verse: 6,
    noteTitle: "I Will Speak Of Excellent Things",
    icon: "💎",
    underline: "I will speak of excellent things",
    preview: "Excellent here means things of real weight and worth, not merely pleasant sounding words.",
  },
  {
    verse: 6,
    noteTitle: "The Opening Of My Lips Shall Be Right Things",
    icon: "👄",
    underline: "the opening of my lips shall be right things",
    preview: "Right things means straightforward and honest, without any hidden angle.",
  },
  {
    verse: 7,
    noteTitle: "My Mouth Shall Speak Truth",
    icon: "✅",
    underline: "my mouth shall speak truth",
    preview: "Truth here stands in direct contrast to the flattering speech of chapter seven.",
  },
  {
    verse: 7,
    noteTitle: "Wickedness Is An Abomination To My Lips",
    icon: "🤢",
    underline: "wickedness is an abomination to my lips",
    preview: "Abomination is strong language, describing something that causes deep disgust.",
  },
  {
    verse: 8,
    noteTitle: "All The Words Of My Mouth Are In Righteousness",
    icon: "⚖️",
    underline: "All the words of my mouth are in righteousness",
    preview: "Righteousness describes speech that fully matches what is right and true.",
  },
  {
    verse: 8,
    noteTitle: "Nothing Froward Or Perverse In Them",
    icon: "🌀",
    underline: "nothing froward or perverse in them",
    preview: "Froward means willfully crooked, twisting away from what is straight.",
  },
  {
    verse: 9,
    noteTitle: "Plain To Him That Understandeth",
    icon: "🔍",
    underline: "plain to him that understandeth",
    preview: "Plain here means clear and easy to follow, not hidden in riddles.",
  },
  {
    verse: 9,
    noteTitle: "Right To Them That Find Knowledge",
    icon: "✅",
    underline: "right to them that find knowledge",
    preview: "Right here means correct and fitting, matching exactly what is needed.",
  },
  {
    verse: 10,
    noteTitle: "Receive My Instruction, And Not Silver",
    icon: "💰",
    underline: "Receive my instruction, and not silver",
    preview: "This is not a literal command to reject money outright.",
  },
  {
    verse: 10,
    noteTitle: "Knowledge Rather Than Choice Gold",
    icon: "🥇",
    underline: "knowledge rather than choice gold",
    preview: "Choice gold means the finest, most refined gold available.",
  },
  {
    verse: 11,
    noteTitle: "Wisdom Is Better Than Rubies",
    icon: "💎",
    underline: "wisdom is better than rubies",
    preview: "Rubies here likely names a rare and costly gem, though scholars debate the exact stone.",
  },
  {
    verse: 11,
    noteTitle: "All The Things That May Be Desired",
    icon: "🌍",
    underline: "all the things that may be desired",
    preview: "This phrase widens the comparison to include everything a person could want.",
  },
  {
    verse: 12,
    noteTitle: "I Wisdom Dwell With Prudence",
    icon: "👩",
    underline: "I wisdom dwell with prudence",
    preview: "Wisdom now speaks in the first person, naming herself directly for the first time.",
  },
  {
    verse: 12,
    noteTitle: "Find Out Knowledge Of Witty Inventions",
    icon: "🛠️",
    underline: "find out knowledge of witty inventions",
    preview: "Witty inventions is an old phrase meaning careful, skillful planning.",
  },
  {
    verse: 13,
    noteTitle: "The Fear Of The LORD Is To Hate Evil",
    icon: "📖",
    underline: "The fear of the LORD is to hate evil",
    preview: "This gives a working definition of the fear of the LORD introduced back in Proverbs 1:7.",
  },
  {
    verse: 13,
    noteTitle: "Pride, And Arrogancy, And The Evil Way",
    icon: "💔",
    underline: "pride, and arrogancy, and the evil way",
    preview: "Pride and arrogancy are named together because their meanings overlap closely.",
  },
  {
    verse: 13,
    noteTitle: "The Froward Mouth, Do I Hate",
    icon: "🌀",
    underline: "the froward mouth, do I hate",
    preview: "Froward mouth repeats a word already defined earlier in this chapter, willfully crooked speech.",
  },
  {
    verse: 14,
    noteTitle: "Counsel Is Mine, And Sound Wisdom",
    icon: "🧭",
    underline: "Counsel is mine, and sound wisdom",
    preview: "Counsel here means the practical advice a person needs to make a hard decision.",
  },
  {
    verse: 14,
    noteTitle: "I Am Understanding",
    icon: "🎯",
    underline: "I am understanding",
    preview: "This is one of several bold, direct claims wisdom makes about her own identity.",
  },
  {
    verse: 14,
    noteTitle: "I Have Strength",
    icon: "💪",
    underline: "I have strength",
    preview: "Strength here means real capability, not physical power in the ordinary sense.",
  },
  {
    verse: 15,
    noteTitle: "By Me Kings Reign",
    icon: "👑",
    underline: "By me kings reign",
    preview: "This claims wisdom stands behind the success of the highest human authority.",
  },
  {
    verse: 15,
    noteTitle: "Princes Decree Justice",
    icon: "⚖️",
    underline: "princes decree justice",
    preview: "Princes here refers to rulers and officials below the level of a king.",
  },
  {
    verse: 16,
    noteTitle: "By Me Princes Rule, And Nobles",
    icon: "🔁",
    underline: "By me princes rule, and nobles",
    preview: "This repeats and widens the claim from verse fifteen to a broader group of leaders.",
  },
  {
    verse: 16,
    noteTitle: "All The Judges Of The Earth",
    icon: "🌍",
    underline: "all the judges of the earth",
    preview: "This closes the list with the widest possible scope, every judge everywhere.",
  },
  {
    verse: 17,
    noteTitle: "I Love Them That Love Me",
    icon: "❤️",
    underline: "I love them that love me",
    preview: "Wisdom is described here as capable of loving in return, not simply available to be used.",
  },
  {
    verse: 17,
    noteTitle: "Those That Seek Me Early Shall Find Me",
    icon: "🌅",
    underline: "those that seek me early shall find me",
    preview: "Seek me early can mean seeking earnestly, and can also carry the sense of seeking from youth.",
  },
  {
    verse: 18,
    noteTitle: "Riches And Honour Are With Me",
    icon: "💰",
    underline: "Riches and honour are with me",
    preview: "Riches names material wealth, and honour names the respect a person earns from others.",
  },
  {
    verse: 18,
    noteTitle: "Durable Riches And Righteousness",
    icon: "⏳",
    underline: "durable riches and righteousness",
    preview: "Durable means lasting, built to survive over a long stretch of time.",
  },
  {
    verse: 19,
    noteTitle: "My Fruit Is Better Than Gold",
    icon: "🌳",
    underline: "My fruit is better than gold",
    preview: "Fruit here pictures the actual results wisdom produces in a person's life.",
  },
  {
    verse: 19,
    noteTitle: "My Revenue Than Choice Silver",
    icon: "💵",
    underline: "my revenue than choice silver",
    preview: "Revenue is an old word for steady income, not a single one time payment.",
  },
  {
    verse: 20,
    noteTitle: "I Lead In The Way Of Righteousness",
    icon: "🧭",
    underline: "I lead in the way of righteousness",
    preview: "Lead pictures wisdom as an active guide, walking ahead rather than simply pointing.",
  },
  {
    verse: 20,
    noteTitle: "In The Midst Of The Paths Of Judgment",
    icon: "⚖️",
    underline: "in the midst of the paths of judgment",
    preview: "Paths of judgment means the road of fair, right decision making.",
  },
  {
    verse: 21,
    noteTitle: "Cause Those That Love Me To Inherit Substance",
    icon: "🎁",
    underline: "cause those that love me to inherit substance",
    preview: "Inherit pictures receiving something as a lasting possession, passed down rather than won by luck.",
  },
  {
    verse: 21,
    noteTitle: "I Will Fill Their Treasures",
    icon: "🏆",
    underline: "I will fill their treasures",
    preview: "Fill pictures abundance, not a bare minimum handed out reluctantly.",
  },
  {
    verse: 22,
    noteTitle: "The LORD Possessed Me In The Beginning Of His Way",
    icon: "🌅",
    underline: "The LORD possessed me in the beginning of his way",
    preview: "Possessed here can also be translated as brought forth or acquired, and scholars have long debated the exact sense.",
  },
  {
    verse: 22,
    noteTitle: "Before His Works Of Old",
    icon: "🏛️",
    underline: "before his works of old",
    preview: "Works of old means everything God has made throughout history.",
  },
  {
    verse: 23,
    noteTitle: "I Was Set Up From Everlasting",
    icon: "♾️",
    underline: "I was set up from everlasting",
    preview: "Set up pictures being established or installed in a position, not simply born.",
  },
  {
    verse: 23,
    noteTitle: "From The Beginning, Or Ever The Earth Was",
    icon: "⏳",
    underline: "from the beginning, or ever the earth was",
    preview: "Or ever is an old phrase meaning before, already used twice in this passage.",
  },
  {
    verse: 24,
    noteTitle: "When There Were No Depths",
    icon: "🌊",
    underline: "When there were no depths",
    preview: "Depths refers to the deep waters that covered the earth before it was formed, named in Genesis 1:2.",
  },
  {
    verse: 24,
    noteTitle: "I Was Brought Forth",
    icon: "👶",
    underline: "I was brought forth",
    preview: "Brought forth pictures something like birth, a specific moment of coming into being.",
  },
  {
    verse: 24,
    noteTitle: "No Fountains Abounding With Water",
    icon: "💧",
    underline: "no fountains abounding with water",
    preview: "Fountains here means natural springs, a basic source of fresh water for any ancient community.",
  },
  {
    verse: 25,
    noteTitle: "Before The Mountains Were Settled",
    icon: "🏔️",
    underline: "Before the mountains were settled",
    preview: "Settled here means fixed firmly in place, given a permanent position.",
  },
  {
    verse: 25,
    noteTitle: "Before The Hills Was I Brought Forth",
    icon: "⛰️",
    underline: "before the hills was I brought forth",
    preview: "Hills repeats the mountain image using a slightly smaller, related landform.",
  },
  {
    verse: 26,
    noteTitle: "The Earth, Nor The Fields, Nor The Highest Part Of The Dust",
    icon: "🌾",
    underline: "nor the fields, nor the highest part of the dust",
    preview: "Fields names cultivated, usable farmland, the land people actually lived on and worked.",
  },
  {
    verse: 27,
    noteTitle: "When He Prepared The Heavens",
    icon: "🛠️",
    underline: "When he prepared the heavens",
    preview: "Prepared here means carefully set in place, not thrown together at random.",
  },
  {
    verse: 27,
    noteTitle: "I Was There",
    icon: "👀",
    underline: "I was there",
    preview: "This is one of the most direct claims in the entire chapter.",
  },
  {
    verse: 27,
    noteTitle: "He Set A Compass Upon The Face Of The Depth",
    icon: "⭕",
    underline: "he set a compass upon the face of the depth",
    preview: "Compass here is an old word for a circle, not the navigation tool used today.",
  },
  {
    verse: 28,
    noteTitle: "He Established The Clouds Above",
    icon: "🏛️",
    underline: "he established the clouds above",
    preview: "Established means fixed securely in place, the same word used earlier for the mountains.",
  },
  {
    verse: 28,
    noteTitle: "He Strengthened The Fountains Of The Deep",
    icon: "💪",
    underline: "he strengthened the fountains of the deep",
    preview: "Strengthened means given lasting stability and force.",
  },
  {
    verse: 29,
    noteTitle: "He Gave To The Sea His Decree",
    icon: "📜",
    underline: "he gave to the sea his decree",
    preview: "Decree means a binding, authoritative command that must be obeyed.",
  },
  {
    verse: 29,
    noteTitle: "The Waters Should Not Pass His Commandment",
    icon: "🛡️",
    underline: "the waters should not pass his commandment",
    preview: "This restates the sea's boundary using the word commandment instead of decree.",
  },
  {
    verse: 29,
    noteTitle: "He Appointed The Foundations Of The Earth",
    icon: "🏗️",
    underline: "he appointed the foundations of the earth",
    preview: "Appointed means deliberately fixed and assigned, not left to chance.",
  },
  {
    verse: 30,
    noteTitle: "As One Brought Up With Him",
    icon: "👨‍👧",
    underline: "as one brought up with him",
    preview: "Brought up with him pictures a child raised closely alongside a parent.",
  },
  {
    verse: 30,
    noteTitle: "Daily His Delight, Rejoicing Always Before Him",
    icon: "😊",
    underline: "I was daily his delight, rejoicing always before him",
    preview: "Delight means a source of real joy and pleasure, not simple usefulness.",
  },
  {
    verse: 31,
    noteTitle: "Rejoicing In The Habitable Part Of His Earth",
    icon: "🏠",
    underline: "Rejoicing in the habitable part of his earth",
    preview: "Habitable part means specifically the parts of the world made for people to live on.",
  },
  {
    verse: 31,
    noteTitle: "My Delights Were With The Sons Of Men",
    icon: "👥",
    underline: "my delights were with the sons of men",
    preview: "Sons of men repeats the same phrase used back in verse four, closing a loop across the chapter.",
  },
  {
    verse: 32,
    noteTitle: "Now Therefore Hearken Unto Me",
    icon: "🔄",
    underline: "Now therefore hearken unto me",
    preview: "Now therefore signals a shift from description back to direct appeal.",
  },
  {
    verse: 32,
    noteTitle: "O Ye Children",
    icon: "👶",
    underline: "O ye children",
    preview: "Children here repeats the same wide address used in chapter seven's closing appeal.",
  },
  {
    verse: 32,
    noteTitle: "Blessed Are They That Keep My Ways",
    icon: "🙏",
    underline: "blessed are they that keep my ways",
    preview: "Blessed here means genuinely favored and fortunate, not simply happy in the moment.",
  },
  {
    verse: 33,
    noteTitle: "Hear Instruction, And Be Wise",
    icon: "👂",
    underline: "Hear instruction, and be wise",
    preview: "Hear here means more than physically listening, it means actually taking the words in.",
  },
  {
    verse: 33,
    noteTitle: "Refuse It Not",
    icon: "🙅",
    underline: "refuse it not",
    preview: "Refuse means actively turning something away, not simply forgetting to act on it.",
  },
  {
    verse: 34,
    noteTitle: "Watching Daily At My Gates",
    icon: "👀",
    underline: "watching daily at my gates",
    preview: "Watching daily pictures consistent, repeated effort rather than a single visit.",
  },
  {
    verse: 34,
    noteTitle: "Waiting At The Posts Of My Doors",
    icon: "⏳",
    underline: "waiting at the posts of my doors",
    preview: "Posts of my doors names the door frame itself, the closest possible spot to entering.",
  },
  {
    verse: 35,
    noteTitle: "Whoso Findeth Me Findeth Life",
    icon: "🌱",
    underline: "whoso findeth me findeth life",
    preview: "Findeth repeats a word used earlier in the chapter, back in verse seventeen.",
  },
  {
    verse: 35,
    noteTitle: "Shall Obtain Favour Of The LORD",
    icon: "🙏",
    underline: "shall obtain favour of the LORD",
    preview: "Favour means being looked on with approval and goodwill.",
  },
  {
    verse: 36,
    noteTitle: "He That Sinneth Against Me Wrongeth His Own Soul",
    icon: "🪞",
    underline: "he that sinneth against me wrongeth his own soul",
    preview: "Sinneth against me treats rejecting wisdom as a genuine offense, not a neutral choice.",
  },
  {
    verse: 36,
    noteTitle: "All They That Hate Me Love Death",
    icon: "💔",
    underline: "all they that hate me love death",
    preview: "Hate here means the same settled, deliberate opposition described earlier for fools.",
  },
];
