import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 9 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsNineSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_NINE_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "Wisdom Hath Builded Her House",
    icon: "🏠",
    underline: "Wisdom hath builded her house",
    preview: "Wisdom is pictured here as a woman building her own house.",
  },
  {
    verse: 1,
    noteTitle: "Hewn Out Her Seven Pillars",
    icon: "🪓",
    underline: "hewn out her seven pillars",
    preview: "Hewn means cut and shaped by hand, usually from stone.",
  },
  {
    verse: 2,
    noteTitle: "She Hath Killed Her Beasts",
    icon: "🐐",
    underline: "She hath killed her beasts",
    preview: "Killing an animal for meat was not a daily event in this culture.",
  },
  {
    verse: 2,
    noteTitle: "She Hath Mingled Her Wine",
    icon: "🍷",
    underline: "she hath mingled her wine",
    preview: "Mingled means she added spices into the wine.",
  },
  {
    verse: 2,
    noteTitle: "She Hath Furnished Her Table",
    icon: "🍽️",
    underline: "she hath also furnished her table",
    preview: "Furnished means the table was already fully set.",
  },
  {
    verse: 3,
    noteTitle: "She Hath Sent Forth Her Maidens",
    icon: "📯",
    underline: "She hath sent forth her maidens",
    preview: "Wisdom does not wait quietly for people to find her.",
  },
  {
    verse: 3,
    noteTitle: "She Crieth Upon The Highest Places Of The City",
    icon: "📢",
    underline: "she crieth upon the highest places of the city",
    preview: "Crieth means she calls out loudly, in public, for anyone to hear.",
  },
  {
    verse: 4,
    noteTitle: "Whoso Is Simple, Let Him Turn In Hither",
    icon: "🙋",
    underline: "Whoso is simple, let him turn in hither",
    preview: "Simple here does not mean stupid or slow.",
  },
  {
    verse: 4,
    noteTitle: "Wanteth Understanding, She Saith To Him",
    icon: "🗣️",
    underline: "as for him that wanteth understanding, she saith to him",
    preview: "Wanteth here means lacks, not desires.",
  },
  {
    verse: 5,
    noteTitle: "Come, Eat Of My Bread",
    icon: "🍞",
    underline: "Come, eat of my bread",
    preview: "Wisdom offers her bread as something to be personally received.",
  },
  {
    verse: 5,
    noteTitle: "Drink Of The Wine Which I Have Mingled",
    icon: "🍷",
    underline: "drink of the wine which I have mingled",
    preview: "This is the same mingled wine already prepared back in verse two.",
  },
  {
    verse: 6,
    noteTitle: "Forsake The Foolish, And Live",
    icon: "🚶",
    underline: "Forsake the foolish, and live",
    preview: "Forsake means to leave behind completely, not just to disagree with.",
  },
  {
    verse: 6,
    noteTitle: "Go In The Way Of Understanding",
    icon: "🛤️",
    underline: "go in the way of understanding",
    preview: "The Bible often pictures a life choice as a road or a path.",
  },
  {
    verse: 7,
    noteTitle: "He That Reproveth A Scorner Getteth To Himself Shame",
    icon: "😤",
    underline: "He that reproveth a scorner getteth to himself shame",
    preview: "Reproveth means to correct someone or point out their fault.",
  },
  {
    verse: 7,
    noteTitle: "He That Rebuketh A Wicked Man Getteth Himself A Blot",
    icon: "💢",
    underline: "he that rebuketh a wicked man getteth himself a blot",
    preview: "Rebuketh is a stronger word than reproveth, closer to a sharp warning.",
  },
  {
    verse: 8,
    noteTitle: "Reprove Not A Scorner, Lest He Hate Thee",
    icon: "🙅",
    underline: "Reprove not a scorner, lest he hate thee",
    preview: "This is practical advice, not permission to ignore all wrongdoing.",
  },
  {
    verse: 8,
    noteTitle: "Rebuke A Wise Man, And He Will Love Thee",
    icon: "🤝",
    underline: "rebuke a wise man, and he will love thee",
    preview: "A wise man responds to correction the opposite way a scorner does.",
  },
  {
    verse: 9,
    noteTitle: "Give Instruction To A Wise Man, And He Will Be Yet Wiser",
    icon: "📚",
    underline: "Give instruction to a wise man, and he will be yet wiser",
    preview: "Wisdom is never finished growing, no matter how far along someone is.",
  },
  {
    verse: 10,
    noteTitle: "The Fear Of The LORD Is The Beginning Of Wisdom",
    icon: "👑",
    underline: "The fear of the LORD is the beginning of wisdom",
    preview: "Fear here does not mean being scared of God.",
  },
  {
    verse: 10,
    noteTitle: "The Knowledge Of The Holy Is Understanding",
    icon: "🙏",
    underline: "the knowledge of the holy is understanding",
    preview: "The Holy here refers to God himself.",
  },
  {
    verse: 11,
    noteTitle: "By Me Thy Days Shall Be Multiplied",
    icon: "📆",
    underline: "by me thy days shall be multiplied",
    preview: "Wisdom is still speaking here, in her own voice.",
  },
  {
    verse: 12,
    noteTitle: "If Thou Be Wise, Thou Shalt Be Wise For Thyself",
    icon: "🪞",
    underline: "If thou be wise, thou shalt be wise for thyself",
    preview: "The benefit of wisdom belongs first to the person who has it.",
  },
  {
    verse: 12,
    noteTitle: "If Thou Scornest, Thou Alone Shalt Bear It",
    icon: "⚖️",
    underline: "if thou scornest, thou alone shalt bear it",
    preview: "The same rule works in the opposite direction too.",
  },
  {
    verse: 13,
    noteTitle: "A Foolish Woman Is Clamorous",
    icon: "📣",
    underline: "A foolish woman is clamorous",
    preview: "Folly is now pictured the same way Wisdom was, as a woman.",
  },
  {
    verse: 13,
    noteTitle: "She Is Simple, And Knoweth Nothing",
    icon: "🤷",
    underline: "she is simple, and knoweth nothing",
    preview: "This is the same word simple used back in verse four.",
  },
  {
    verse: 14,
    noteTitle: "She Sitteth At The Door Of Her House",
    icon: "🪑",
    underline: "she sitteth at the door of her house",
    preview: "Wisdom built an entire house and prepared a full feast.",
  },
  {
    verse: 14,
    noteTitle: "On A Seat In The High Places Of The City",
    icon: "🏙️",
    underline: "on a seat in the high places of the city",
    preview: "Folly copies the exact location Wisdom already used in verse three.",
  },
  {
    verse: 15,
    noteTitle: "To Call Passengers Who Go Right On Their Ways",
    icon: "🚶",
    underline: "To call passengers who go right on their ways",
    preview: "These passengers were not lost or searching for anything.",
  },
  {
    verse: 16,
    noteTitle: "Whoso Is Simple, Let Him Turn In Hither Too",
    icon: "🗣️",
    underline: "Whoso is simple, let him turn in hither",
    preview: "Folly uses the very same words Wisdom used back in verse four.",
  },
  {
    verse: 17,
    noteTitle: "Stolen Waters Are Sweet",
    icon: "💧",
    underline: "Stolen waters are sweet",
    preview: "Folly's whole pitch is that secrecy makes things taste better.",
  },
  {
    verse: 17,
    noteTitle: "Bread Eaten In Secret Is Pleasant",
    icon: "🍞",
    underline: "bread eaten in secret is pleasant",
    preview: "This line directly echoes Wisdom's own invitation to bread in verse five.",
  },
  {
    verse: 18,
    noteTitle: "He Knoweth Not That The Dead Are There",
    icon: "💀",
    underline: "he knoweth not that the dead are there",
    preview: "The guest walking in only sees the pleasure Folly is offering.",
  },
  {
    verse: 18,
    noteTitle: "Her Guests Are In The Depths Of Hell",
    icon: "⚰️",
    underline: "her guests are in the depths of hell",
    preview: "Hell here means Sheol, the ancient Hebrew word for the realm of the dead.",
  },
];
