import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 16 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsSixteenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_SIXTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "The Preparations Of The Heart In Man",
    icon: "🧠",
    underline: "The preparations of the heart in man",
    preview: "\"Preparations\" means the planning and arranging a person does before acting.",
  },
  {
    verse: 1,
    noteTitle: "The Answer Of The Tongue, Is From The LORD",
    icon: "👄",
    underline: "the answer of the tongue, is from the LORD",
    preview: "This verse pairs the silent plan with the spoken word that follows it.",
  },
  {
    verse: 2,
    noteTitle: "All The Ways Of A Man Are Clean In His Own Eyes",
    icon: "👀",
    underline: "All the ways of a man are clean in his own eyes",
    preview: "This means people naturally believe their own choices are justified.",
  },
  {
    verse: 2,
    noteTitle: "But The LORD Weigheth The Spirits",
    icon: "⚖️",
    underline: "but the LORD weigheth the spirits",
    preview: "\"Weigheth\" means examines closely and measures true value or motive.",
  },
  {
    verse: 3,
    noteTitle: "Commit Thy Works Unto The LORD",
    icon: "🙏",
    underline: "Commit thy works unto the LORD",
    preview: "\"Commit\" means to hand something over fully, not just ask for help.",
  },
  {
    verse: 3,
    noteTitle: "Thy Thoughts Shall Be Established",
    icon: "🏗️",
    underline: "thy thoughts shall be established",
    preview: "\"Established\" means made firm and lasting, not likely to collapse.",
  },
  {
    verse: 4,
    noteTitle: "The LORD Hath Made All Things For Himself",
    icon: "🌍",
    underline: "The LORD hath made all things for himself",
    preview: "This means every created thing ultimately serves God's own purposes.",
  },
  {
    verse: 4,
    noteTitle: "Yea, Even The Wicked For The Day Of Evil",
    icon: "⚠️",
    underline: "yea, even the wicked for the day of evil",
    preview: "This is one of the harder lines in Proverbs to read plainly.",
  },
  {
    verse: 5,
    noteTitle: "Every One That Is Proud In Heart Is An Abomination To The LORD",
    icon: "💔",
    underline: "Every one that is proud in heart is an abomination to the LORD",
    preview: "\"Abomination\" means something God finds deeply offensive, not merely disliked.",
  },
  {
    verse: 5,
    noteTitle: "Though Hand Join In Hand, He Shall Not Be Unpunished",
    icon: "🤝",
    underline: "though hand join in hand, he shall not be unpunished",
    preview: "\"Hand join in hand\" is an old idiom for people banding together.",
  },
  {
    verse: 6,
    noteTitle: "By Mercy And Truth Iniquity Is Purged",
    icon: "💞",
    underline: "By mercy and truth iniquity is purged",
    preview: "\"Purged\" means cleansed or removed, like impurity being burned away.",
  },
  {
    verse: 6,
    noteTitle: "By The Fear Of The LORD Men Depart From Evil",
    icon: "🚶",
    underline: "by the fear of the LORD men depart from evil",
    preview: "\"Fear of the LORD\" means real reverence, taking God seriously.",
  },
  {
    verse: 7,
    noteTitle: "When A Man's Ways Please The LORD",
    icon: "🕊️",
    underline: "When a man’s ways please the LORD",
    preview: "\"Please\" here means genuinely pleasing to God, not merely acceptable.",
  },
  {
    verse: 7,
    noteTitle: "He Maketh Even His Enemies To Be At Peace With Him",
    icon: "🤝",
    underline: "he maketh even his enemies to be at peace with him",
    preview: "This is a surprising promise most readers would not expect.",
  },
  {
    verse: 8,
    noteTitle: "Better Is A Little With Righteousness",
    icon: "💰",
    underline: "Better is a little with righteousness",
    preview: "\"Better is\" proverbs weigh two things to teach what actually matters.",
  },
  {
    verse: 8,
    noteTitle: "Than Great Revenues Without Right",
    icon: "😰",
    underline: "than great revenues without right",
    preview: "\"Revenues\" means income or gain, however it was obtained.",
  },
  {
    verse: 9,
    noteTitle: "A Man's Heart Deviseth His Way",
    icon: "🗺️",
    underline: "A man’s heart deviseth his way",
    preview: "\"Deviseth\" means plans out carefully, working out the details in advance.",
  },
  {
    verse: 9,
    noteTitle: "But The LORD Directeth His Steps",
    icon: "🧭",
    underline: "but the LORD directeth his steps",
    preview: "\"Directeth\" means actively guides the actual outcome of each step.",
  },
  {
    verse: 10,
    noteTitle: "A Divine Sentence Is In The Lips Of The King",
    icon: "👑",
    underline: "A divine sentence is in the lips of the king",
    preview: "\"Divine sentence\" pictures royal speech carrying an almost prophetic weight.",
  },
  {
    verse: 10,
    noteTitle: "His Mouth Transgresseth Not In Judgment",
    icon: "⚖️",
    underline: "his mouth transgresseth not in judgment",
    preview: "\"Transgresseth\" means crosses a line it should not cross.",
  },
  {
    verse: 11,
    noteTitle: "A Just Weight And Balance Are The LORD's",
    icon: "⚖️",
    underline: "A just weight and balance are the LORD’s",
    preview: "\"Weight and balance\" were the tools ancient merchants used to measure goods honestly.",
  },
  {
    verse: 11,
    noteTitle: "All The Weights Of The Bag Are His Work",
    icon: "💰",
    underline: "all the weights of the bag are his work",
    preview: "Merchants carried small stone weights in a bag to measure out goods.",
  },
  {
    verse: 12,
    noteTitle: "It Is An Abomination To Kings To Commit Wickedness",
    icon: "🚫",
    underline: "It is an abomination to kings to commit wickedness",
    preview: "This states an ideal every good king was expected to hold.",
  },
  {
    verse: 12,
    noteTitle: "For The Throne Is Established By Righteousness",
    icon: "🏛️",
    underline: "for the throne is established by righteousness",
    preview: "\"Established\" means made secure and lasting over time.",
  },
  {
    verse: 13,
    noteTitle: "Righteous Lips Are The Delight Of Kings",
    icon: "💋",
    underline: "Righteous lips are the delight of kings",
    preview: "\"Delight\" here means something a king genuinely enjoyed hearing.",
  },
  {
    verse: 13,
    noteTitle: "They Love Him That Speaketh Right",
    icon: "🙌",
    underline: "they love him that speaketh right",
    preview: "\"Speaketh right\" means tells the truth, even when it is hard to hear.",
  },
  {
    verse: 14,
    noteTitle: "The Wrath Of A King Is As Messengers Of Death",
    icon: "💀",
    underline: "The wrath of a king is as messengers of death",
    preview: "\"Messengers of death\" was a vivid ancient image for an unstoppable threat.",
  },
  {
    verse: 14,
    noteTitle: "But A Wise Man Will Pacify It",
    icon: "🕊️",
    underline: "but a wise man will pacify it",
    preview: "\"Pacify\" means calm down, turning anger away before it does harm.",
  },
  {
    verse: 15,
    noteTitle: "In The Light Of The King's Countenance Is Life",
    icon: "☀️",
    underline: "In the light of the king’s countenance is life",
    preview: "\"Countenance\" means the face, someone's outward expression.",
  },
  {
    verse: 15,
    noteTitle: "His Favour Is As A Cloud Of The Latter Rain",
    icon: "🌧️",
    underline: "his favour is as a cloud of the latter rain",
    preview: "The \"latter rain\" fell in spring, right when crops needed it most to ripen.",
  },
  {
    verse: 16,
    noteTitle: "How Much Better Is It To Get Wisdom Than Gold",
    icon: "💎",
    underline: "How much better is it to get wisdom than gold",
    preview: "\"How much better\" is a common Proverbs comparison moving from lesser to greater value.",
  },
  {
    verse: 16,
    noteTitle: "To Get Understanding Rather To Be Chosen Than Silver",
    icon: "🥈",
    underline: "to get understanding rather to be chosen than silver",
    preview: "Silver was the second most valuable metal in everyday ancient trade.",
  },
  {
    verse: 17,
    noteTitle: "The Highway Of The Upright Is To Depart From Evil",
    icon: "🛣️",
    underline: "The highway of the upright is to depart from evil",
    preview: "\"Highway\" pictures a clear, well used road, not a hidden side path.",
  },
  {
    verse: 17,
    noteTitle: "He That Keepeth His Way Preserveth His Soul",
    icon: "🛡️",
    underline: "he that keepeth his way preserveth his soul",
    preview: "\"Keepeth his way\" means stays carefully on the right path over time.",
  },
  {
    verse: 18,
    noteTitle: "Pride Goeth Before Destruction",
    icon: "💥",
    underline: "Pride goeth before destruction",
    preview: "This is one of the most quoted lines in the whole book.",
  },
  {
    verse: 18,
    noteTitle: "And An Haughty Spirit Before A Fall",
    icon: "😤",
    underline: "and an haughty spirit before a fall",
    preview: "\"Haughty\" means arrogant, looking down on others as beneath oneself.",
  },
  {
    verse: 19,
    noteTitle: "Better It Is To Be Of An Humble Spirit With The Lowly",
    icon: "🙏",
    underline: "Better it is to be of an humble spirit with the lowly",
    preview: "\"Lowly\" here means people of modest means or low social standing.",
  },
  {
    verse: 19,
    noteTitle: "Than To Divide The Spoil With The Proud",
    icon: "🏆",
    underline: "than to divide the spoil with the proud",
    preview: "\"Spoil\" means plunder or loot taken after a victory or a raid.",
  },
  {
    verse: 20,
    noteTitle: "He That Handleth A Matter Wisely Shall Find Good",
    icon: "🧠",
    underline: "He that handleth a matter wisely shall find good",
    preview: "\"Handleth wisely\" means approaches a situation with real skill and care.",
  },
  {
    verse: 20,
    noteTitle: "And Whoso Trusteth In The LORD, Happy Is He",
    icon: "🙌",
    underline: "and whoso trusteth in the LORD, happy is he",
    preview: "\"Trusteth\" means relies on, leaning full weight on someone else.",
  },
  {
    verse: 21,
    noteTitle: "The Wise In Heart Shall Be Called Prudent",
    icon: "🧠",
    underline: "The wise in heart shall be called prudent",
    preview: "\"Prudent\" means practically skilled at making good decisions.",
  },
  {
    verse: 21,
    noteTitle: "And The Sweetness Of The Lips Increaseth Learning",
    icon: "🍯",
    underline: "and the sweetness of the lips increaseth learning",
    preview: "\"Sweetness of the lips\" means speech that is pleasant and easy to receive.",
  },
  {
    verse: 22,
    noteTitle: "Understanding Is A Wellspring Of Life Unto Him That Hath It",
    icon: "💧",
    underline: "Understanding is a wellspring of life unto him that hath it",
    preview: "A \"wellspring\" is a natural spring, a constant source of fresh water in a dry land.",
  },
  {
    verse: 22,
    noteTitle: "But The Instruction Of Fools Is Folly",
    icon: "🙄",
    underline: "but the instruction of fools is folly",
    preview: "This verse draws a sharp contrast with the wellspring just described.",
  },
  {
    verse: 23,
    noteTitle: "The Heart Of The Wise Teacheth His Mouth",
    icon: "🫀",
    underline: "The heart of the wise teacheth his mouth",
    preview: "This pictures wisdom starting inside and then shaping outward speech.",
  },
  {
    verse: 23,
    noteTitle: "And Addeth Learning To His Lips",
    icon: "📈",
    underline: "and addeth learning to his lips",
    preview: "\"Addeth\" means increases or builds up over time, not a single event.",
  },
  {
    verse: 24,
    noteTitle: "Pleasant Words Are As An Honeycomb",
    icon: "🍯",
    underline: "Pleasant words are as an honeycomb",
    preview: "Honey straight from the comb was one of the sweetest foods available in this culture.",
  },
  {
    verse: 24,
    noteTitle: "Sweet To The Soul, And Health To The Bones",
    icon: "💊",
    underline: "sweet to the soul, and health to the bones",
    preview: "Ancient people connected deep emotional states directly to physical bodily health.",
  },
  {
    verse: 25,
    noteTitle: "There Is A Way That Seemeth Right Unto A Man",
    icon: "🌀",
    underline: "There is a way that seemeth right unto a man",
    preview: "This verse warns that a path can feel completely correct and still be wrong.",
  },
  {
    verse: 25,
    noteTitle: "But The End Thereof Are The Ways Of Death",
    icon: "☠️",
    underline: "but the end thereof are the ways of death",
    preview: "\"End thereof\" means where that confident path actually leads in the end.",
  },
  {
    verse: 26,
    noteTitle: "He That Laboureth Laboureth For Himself",
    icon: "💪",
    underline: "He that laboureth laboureth for himself",
    preview: "The repeated word \"laboureth\" emphasizes ongoing, hard physical work.",
  },
  {
    verse: 26,
    noteTitle: "For His Mouth Craveth It Of Him",
    icon: "👄",
    underline: "for his mouth craveth it of him",
    preview: "\"Craveth\" means demands strongly, like real hunger driving action.",
  },
  {
    verse: 27,
    noteTitle: "An Ungodly Man Diggeth Up Evil",
    icon: "🕳️",
    underline: "An ungodly man diggeth up evil",
    preview: "\"Diggeth up\" pictures someone actively digging for trouble, not stumbling into it.",
  },
  {
    verse: 27,
    noteTitle: "And In His Lips There Is As A Burning Fire",
    icon: "🔥",
    underline: "and in his lips there is as a burning fire",
    preview: "Fire spreads quickly and destroys far more than its starting point.",
  },
  {
    verse: 28,
    noteTitle: "A Froward Man Soweth Strife",
    icon: "😈",
    underline: "A froward man soweth strife",
    preview: "\"Froward\" means stubbornly contrary, twisting things away from what is right.",
  },
  {
    verse: 28,
    noteTitle: "And A Whisperer Separateth Chief Friends",
    icon: "🤫",
    underline: "and a whisperer separateth chief friends",
    preview: "\"Whisperer\" means someone who spreads gossip in secret, quiet conversations.",
  },
  {
    verse: 29,
    noteTitle: "A Violent Man Enticeth His Neighbour",
    icon: "😈",
    underline: "A violent man enticeth his neighbour",
    preview: "\"Enticeth\" means lures or persuades someone toward something harmful.",
  },
  {
    verse: 29,
    noteTitle: "And Leadeth Him Into The Way That Is Not Good",
    icon: "🛣️",
    underline: "and leadeth him into the way that is not good",
    preview: "\"Leadeth\" pictures someone actually guiding another person, step by step.",
  },
  {
    verse: 30,
    noteTitle: "He Shutteth His Eyes To Devise Froward Things",
    icon: "👁️",
    underline: "He shutteth his eyes to devise froward things",
    preview: "Ancient readers associated shut or narrowed eyes with hidden scheming.",
  },
  {
    verse: 30,
    noteTitle: "Moving His Lips He Bringeth Evil To Pass",
    icon: "👄",
    underline: "moving his lips he bringeth evil to pass",
    preview: "Silently moving lips pictured someone quietly working out a plan's final details.",
  },
  {
    verse: 31,
    noteTitle: "The Hoary Head Is A Crown Of Glory",
    icon: "👴",
    underline: "The hoary head is a crown of glory",
    preview: "\"Hoary\" means gray or white, describing the hair of someone elderly.",
  },
  {
    verse: 31,
    noteTitle: "If It Be Found In The Way Of Righteousness",
    icon: "✝️",
    underline: "if it be found in the way of righteousness",
    preview: "This second half quietly narrows the promise made in the first half.",
  },
  {
    verse: 32,
    noteTitle: "He That Is Slow To Anger Is Better Than The Mighty",
    icon: "🕊️",
    underline: "He that is slow to anger is better than the mighty",
    preview: "\"The mighty\" means a powerful warrior admired for physical strength and conquest.",
  },
  {
    verse: 32,
    noteTitle: "And He That Ruleth His Spirit Than He That Taketh A City",
    icon: "🏙️",
    underline: "and he that ruleth his spirit than he that taketh a city",
    preview: "\"Taketh a city\" pictured a major military conquest, a huge public achievement.",
  },
  {
    verse: 33,
    noteTitle: "The Lot Is Cast Into The Lap",
    icon: "🎲",
    underline: "The lot is cast into the lap",
    preview: "Casting lots was an ancient method like rolling dice to decide something.",
  },
  {
    verse: 33,
    noteTitle: "But The Whole Disposing Thereof Is Of The LORD",
    icon: "🙌",
    underline: "but the whole disposing thereof is of the LORD",
    preview: "\"Disposing\" means the actual deciding of how something turns out.",
  },
];
