import type { GenesisOnePhrase } from "./genesisOneStudyMode";

/**
 * Proverbs 15 Insight Cards phrase map.
 *
 * Mirrors lib/genesisOneStudyMode.ts. The notes themselves live in
 * lib/proverbsFifteenSource.ts (read server side via /api/study-notes); this
 * file only supplies which verse each phrase sits under, the exact KJV
 * words to underline, and a one line preview.
 */
export const PROVERBS_FIFTEEN_PHRASES: GenesisOnePhrase[] = [
  {
    verse: 1,
    noteTitle: "A Soft Answer Turneth Away Wrath",
    icon: "🕊️",
    underline: "A soft answer turneth away wrath",
    preview: "A soft answer means a calm, gentle reply, not a weak one.",
  },
  {
    verse: 1,
    noteTitle: "Grievous Words Stir Up Anger",
    icon: "🔥",
    underline: "grievous words stir up anger",
    preview: "\"Grievous\" means harsh and cutting, words meant to wound.",
  },
  {
    verse: 2,
    noteTitle: "The Tongue Of The Wise Useth Knowledge Aright",
    icon: "🧠",
    underline: "The tongue of the wise useth knowledge aright",
    preview: "\"Aright\" means correctly, in the right way and the right time.",
  },
  {
    verse: 2,
    noteTitle: "The Mouth Of Fools Poureth Out Foolishness",
    icon: "🗑️",
    underline: "the mouth of fools poureth out foolishness",
    preview: "\"Poureth out\" means an uncontrolled gush, not a careful gift.",
  },
  {
    verse: 3,
    noteTitle: "The Eyes Of The LORD Are In Every Place",
    icon: "👁️",
    underline: "The eyes of the LORD are in every place",
    preview: "This means God is actively watching, not merely present everywhere.",
  },
  {
    verse: 3,
    noteTitle: "Beholding The Evil And The Good",
    icon: "⚖️",
    underline: "beholding the evil and the good",
    preview: "\"Beholding\" means watching closely, taking full notice.",
  },
  {
    verse: 4,
    noteTitle: "A Wholesome Tongue Is A Tree Of Life",
    icon: "🌳",
    underline: "A wholesome tongue is a tree of life",
    preview: "\"Wholesome\" here means healing, speech that restores rather than harms.",
  },
  {
    verse: 4,
    noteTitle: "Perverseness Therein Is A Breach In The Spirit",
    icon: "💔",
    underline: "perverseness therein is a breach in the spirit",
    preview: "\"Perverseness\" means twisted speech, words bent away from what is true.",
  },
  {
    verse: 5,
    noteTitle: "A Fool Despiseth His Father's Instruction",
    icon: "🙄",
    underline: "A fool despiseth his father’s instruction",
    preview: "\"Despiseth\" means treats with contempt, not simple disagreement.",
  },
  {
    verse: 5,
    noteTitle: "He That Regardeth Reproof Is Prudent",
    icon: "🎯",
    underline: "he that regardeth reproof is prudent",
    preview: "\"Regardeth\" means takes seriously and actually acts on what is said.",
  },
  {
    verse: 6,
    noteTitle: "In The House Of The Righteous Is Much Treasure",
    icon: "💰",
    underline: "In the house of the righteous is much treasure",
    preview: "\"House\" here means a family's whole estate, not one room.",
  },
  {
    verse: 6,
    noteTitle: "In The Revenues Of The Wicked Is Trouble",
    icon: "🌀",
    underline: "in the revenues of the wicked is trouble",
    preview: "\"Revenues\" means income or gain, however it was obtained.",
  },
  {
    verse: 7,
    noteTitle: "The Lips Of The Wise Disperse Knowledge",
    icon: "🌾",
    underline: "The lips of the wise disperse knowledge",
    preview: "\"Disperse\" means scatter widely, like a farmer sowing seed.",
  },
  {
    verse: 7,
    noteTitle: "The Heart Of The Foolish Doeth Not So",
    icon: "🕳️",
    underline: "the heart of the foolish doeth not so",
    preview: "\"Doeth not so\" means the fool simply does not do this at all.",
  },
  {
    verse: 8,
    noteTitle: "The Sacrifice Of The Wicked Is An Abomination To The LORD",
    icon: "🙅",
    underline: "The sacrifice of the wicked is an abomination to the LORD",
    preview: "\"Abomination\" means something God finds deeply offensive.",
  },
  {
    verse: 8,
    noteTitle: "The Prayer Of The Upright Is His Delight",
    icon: "💖",
    underline: "the prayer of the upright is his delight",
    preview: "\"Delight\" means something God genuinely takes pleasure in.",
  },
  {
    verse: 9,
    noteTitle: "The Way Of The Wicked Is An Abomination Unto The LORD",
    icon: "🚫",
    underline: "The way of the wicked is an abomination unto the LORD",
    preview: "\"Way\" here means an entire lifestyle, not one action.",
  },
  {
    verse: 9,
    noteTitle: "He Loveth Him That Followeth After Righteousness",
    icon: "❤️",
    underline: "he loveth him that followeth after righteousness",
    preview: "\"Followeth after\" means actively pursuing, running toward something.",
  },
  {
    verse: 10,
    noteTitle: "Correction Is Grievous Unto Him That Forsaketh The Way",
    icon: "😖",
    underline: "Correction is grievous unto him that forsaketh the way",
    preview: "\"Forsaketh\" means has actually abandoned the right path already.",
  },
  {
    verse: 10,
    noteTitle: "He That Hateth Reproof Shall Die",
    icon: "⚰️",
    underline: "he that hateth reproof shall die",
    preview: "\"Hateth reproof\" means rejecting correction completely, not just disliking it.",
  },
  {
    verse: 11,
    noteTitle: "Hell And Destruction Are Before The LORD",
    icon: "💀",
    underline: "Hell and destruction are before the LORD",
    preview: "\"Hell\" here translates Sheol, the ancient Hebrew word for the realm of the dead.",
  },
  {
    verse: 11,
    noteTitle: "How Much More Then The Hearts Of The Children Of Men",
    icon: "🫀",
    underline: "how much more then the hearts of the children of men",
    preview: "\"How much more\" is a common Proverbs argument moving from greater to lesser.",
  },
  {
    verse: 12,
    noteTitle: "A Scorner Loveth Not One That Reproveth Him",
    icon: "😤",
    underline: "A scorner loveth not one that reproveth him",
    preview: "\"Scorner\" means someone who mocks correction, worse than simply being foolish.",
  },
  {
    verse: 12,
    noteTitle: "Neither Will He Go Unto The Wise",
    icon: "🚪",
    underline: "neither will he go unto the wise",
    preview: "This shows the scorner's problem is not accidental, it is a pattern of avoidance.",
  },
  {
    verse: 13,
    noteTitle: "A Merry Heart Maketh A Cheerful Countenance",
    icon: "😊",
    underline: "A merry heart maketh a cheerful countenance",
    preview: "\"Countenance\" means the face, someone's outward expression.",
  },
  {
    verse: 13,
    noteTitle: "By Sorrow Of The Heart The Spirit Is Broken",
    icon: "😔",
    underline: "by sorrow of the heart the spirit is broken",
    preview: "\"Spirit is broken\" means more than sadness, it means crushed inner strength.",
  },
  {
    verse: 14,
    noteTitle: "The Heart Of Him That Hath Understanding Seeketh Knowledge",
    icon: "🔍",
    underline: "The heart of him that hath understanding seeketh knowledge",
    preview: "\"Seeketh\" means an ongoing search, not a single completed task.",
  },
  {
    verse: 14,
    noteTitle: "The Mouth Of Fools Feedeth On Foolishness",
    icon: "🍔",
    underline: "the mouth of fools feedeth on foolishness",
    preview: "\"Feedeth on\" means consumes as a steady diet, not an occasional snack.",
  },
  {
    verse: 15,
    noteTitle: "All The Days Of The Afflicted Are Evil",
    icon: "☁️",
    underline: "All the days of the afflicted are evil",
    preview: "\"Afflicted\" means someone under real, ongoing hardship or oppression.",
  },
  {
    verse: 15,
    noteTitle: "He That Is Of A Merry Heart Hath A Continual Feast",
    icon: "🎉",
    underline: "he that is of a merry heart hath a continual feast",
    preview: "\"Continual feast\" pictures ongoing celebration, not one special meal.",
  },
  {
    verse: 16,
    noteTitle: "Better Is Little With The Fear Of The LORD",
    icon: "🙏",
    underline: "Better is little with the fear of the LORD",
    preview: "\"Better is\" proverbs compare two things to teach what actually matters.",
  },
  {
    verse: 16,
    noteTitle: "Than Great Treasure And Trouble Therewith",
    icon: "😰",
    underline: "than great treasure and trouble therewith",
    preview: "\"Trouble therewith\" means anxiety and conflict that come bundled with wealth.",
  },
  {
    verse: 17,
    noteTitle: "Better Is A Dinner Of Herbs Where Love Is",
    icon: "🥗",
    underline: "Better is a dinner of herbs where love is",
    preview: "\"Dinner of herbs\" pictures the simplest, humblest possible meal.",
  },
  {
    verse: 17,
    noteTitle: "Than A Stalled Ox And Hatred Therewith",
    icon: "🐂",
    underline: "than a stalled ox and hatred therewith",
    preview: "\"Stalled ox\" means a fattened animal, the richest possible feast.",
  },
  {
    verse: 18,
    noteTitle: "A Wrathful Man Stirreth Up Strife",
    icon: "🔥",
    underline: "A wrathful man stirreth up strife",
    preview: "\"Wrathful\" describes someone with a quick, hot temper as a pattern.",
  },
  {
    verse: 18,
    noteTitle: "He That Is Slow To Anger Appeaseth Strife",
    icon: "🕊️",
    underline: "he that is slow to anger appeaseth strife",
    preview: "\"Slow to anger\" means taking real time before reacting, not staying passive.",
  },
  {
    verse: 19,
    noteTitle: "The Way Of The Slothful Man Is As An Hedge Of Thorns",
    icon: "🌵",
    underline: "The way of the slothful man is as an hedge of thorns",
    preview: "\"Slothful\" means habitually lazy, avoiding needed effort.",
  },
  {
    verse: 19,
    noteTitle: "The Way Of The Righteous Is Made Plain",
    icon: "🛣️",
    underline: "the way of the righteous is made plain",
    preview: "\"Made plain\" pictures a clear, level road, easy to walk.",
  },
  {
    verse: 20,
    noteTitle: "A Wise Son Maketh A Glad Father",
    icon: "😄",
    underline: "A wise son maketh a glad father",
    preview: "This is a recurring theme across the book of Proverbs.",
  },
  {
    verse: 20,
    noteTitle: "A Foolish Man Despiseth His Mother",
    icon: "😞",
    underline: "a foolish man despiseth his mother",
    preview: "Notice the shift here from a young \"son\" to a grown \"man.\"",
  },
  {
    verse: 21,
    noteTitle: "Folly Is Joy To Him That Is Destitute Of Wisdom",
    icon: "🎈",
    underline: "Folly is joy to him that is destitute of wisdom",
    preview: "\"Destitute of wisdom\" means someone utterly lacking any real understanding.",
  },
  {
    verse: 21,
    noteTitle: "A Man Of Understanding Walketh Uprightly",
    icon: "🚶",
    underline: "a man of understanding walketh uprightly",
    preview: "\"Walketh uprightly\" pictures a steady, deliberate direction over time.",
  },
  {
    verse: 22,
    noteTitle: "Without Counsel Purposes Are Disappointed",
    icon: "🌀",
    underline: "Without counsel purposes are disappointed",
    preview: "\"Purposes\" here means plans a person has made for themselves.",
  },
  {
    verse: 22,
    noteTitle: "In The Multitude Of Counsellors They Are Established",
    icon: "👥",
    underline: "in the multitude of counsellors they are established",
    preview: "\"Multitude of counsellors\" means several wise advisors, not just one opinion.",
  },
  {
    verse: 23,
    noteTitle: "A Man Hath Joy By The Answer Of His Mouth",
    icon: "😊",
    underline: "A man hath joy by the answer of his mouth",
    preview: "This describes the real satisfaction of giving a genuinely fitting reply.",
  },
  {
    verse: 23,
    noteTitle: "A Word Spoken In Due Season, How Good Is It",
    icon: "⏰",
    underline: "a word spoken in due season, how good is it",
    preview: "\"Due season\" means the right moment, not simply the right content.",
  },
  {
    verse: 24,
    noteTitle: "The Way Of Life Is Above To The Wise",
    icon: "⬆️",
    underline: "The way of life is above to the wise",
    preview: "\"Above\" and \"beneath\" later in this verse form a spatial picture.",
  },
  {
    verse: 24,
    noteTitle: "That He May Depart From Hell Beneath",
    icon: "⬇️",
    underline: "that he may depart from hell beneath",
    preview: "\"Hell\" here again translates Sheol, pictured here as the downward pull.",
  },
  {
    verse: 25,
    noteTitle: "The LORD Will Destroy The House Of The Proud",
    icon: "🏚️",
    underline: "The LORD will destroy the house of the proud",
    preview: "\"House\" here again means a whole family's estate and legacy.",
  },
  {
    verse: 25,
    noteTitle: "He Will Establish The Border Of The Widow",
    icon: "🛡️",
    underline: "he will establish the border of the widow",
    preview: "\"Border\" here means a property line, a widow's small remaining land.",
  },
  {
    verse: 26,
    noteTitle: "The Thoughts Of The Wicked Are An Abomination To The LORD",
    icon: "🧠",
    underline: "The thoughts of the wicked are an abomination to the LORD",
    preview: "This verse judges thoughts themselves, not only actions taken.",
  },
  {
    verse: 26,
    noteTitle: "The Words Of The Pure Are Pleasant Words",
    icon: "🕊️",
    underline: "the words of the pure are pleasant words",
    preview: "\"Pure\" describes a heart free from hidden, twisted motives.",
  },
  {
    verse: 27,
    noteTitle: "He That Is Greedy Of Gain Troubleth His Own House",
    icon: "💰",
    underline: "He that is greedy of gain troubleth his own house",
    preview: "\"Greedy of gain\" means grasping for profit without regard for how it is gotten.",
  },
  {
    verse: 27,
    noteTitle: "He That Hateth Gifts Shall Live",
    icon: "🙌",
    underline: "he that hateth gifts shall live",
    preview: "\"Gifts\" here means bribes, payments meant to twist someone's judgment.",
  },
  {
    verse: 28,
    noteTitle: "The Heart Of The Righteous Studieth To Answer",
    icon: "🤔",
    underline: "The heart of the righteous studieth to answer",
    preview: "\"Studieth\" means deliberately thinks before speaking, not merely reacting.",
  },
  {
    verse: 28,
    noteTitle: "The Mouth Of The Wicked Poureth Out Evil Things",
    icon: "💥",
    underline: "the mouth of the wicked poureth out evil things",
    preview: "\"Poureth out\" repeats the same image used earlier in this chapter.",
  },
  {
    verse: 29,
    noteTitle: "The LORD Is Far From The Wicked",
    icon: "🚧",
    underline: "The LORD is far from the wicked",
    preview: "This distance is relational, not physical, since God sees every place.",
  },
  {
    verse: 29,
    noteTitle: "He Heareth The Prayer Of The Righteous",
    icon: "👂",
    underline: "he heareth the prayer of the righteous",
    preview: "\"Heareth\" means actively listens and responds, not simply detects sound.",
  },
  {
    verse: 30,
    noteTitle: "The Light Of The Eyes Rejoiceth The Heart",
    icon: "✨",
    underline: "The light of the eyes rejoiceth the heart",
    preview: "\"Light of the eyes\" pictures a bright, joyful look on someone's face.",
  },
  {
    verse: 30,
    noteTitle: "A Good Report Maketh The Bones Fat",
    icon: "💪",
    underline: "a good report maketh the bones fat",
    preview: "\"Bones fat\" was an ancient way of describing physical health and vigor.",
  },
  {
    verse: 31,
    noteTitle: "The Ear That Heareth The Reproof Of Life",
    icon: "👂",
    underline: "The ear that heareth the reproof of life",
    preview: "\"Reproof of life\" means correction that actually leads toward life.",
  },
  {
    verse: 31,
    noteTitle: "Abideth Among The Wise",
    icon: "🏡",
    underline: "abideth among the wise",
    preview: "\"Abideth\" means settles in permanently, not a brief passing visit.",
  },
  {
    verse: 32,
    noteTitle: "He That Refuseth Instruction Despiseth His Own Soul",
    icon: "🙈",
    underline: "He that refuseth instruction despiseth his own soul",
    preview: "\"Refuseth\" means actively rejects, closing the door on purpose.",
  },
  {
    verse: 32,
    noteTitle: "He That Heareth Reproof Getteth Understanding",
    icon: "📈",
    underline: "he that heareth reproof getteth understanding",
    preview: "\"Getteth\" means actively gains, treating correction as something acquired.",
  },
  {
    verse: 33,
    noteTitle: "The Fear Of The LORD Is The Instruction Of Wisdom",
    icon: "🙏",
    underline: "The fear of the LORD is the instruction of wisdom",
    preview: "This closing verse echoes the opening claim made back in Proverbs one.",
  },
  {
    verse: 33,
    noteTitle: "Before Honour Is Humility",
    icon: "🌱",
    underline: "before honour is humility",
    preview: "\"Honour\" means being genuinely valued and respected by others.",
  },
];
