import { getScrambledBook } from "@/lib/scrambledGameData";
import {
  CHAPTER_BASED_TRIVIA_BOOK_CONFIG,
  getChapterBasedTriviaBookByKey,
  getTriviaProgressBookKey,
} from "@/lib/triviaCatalog";

export type TriviaOption = {
  label: string;
  text: string;
};

export type TriviaQuestion = {
  id: string;
  question: string;
  options: TriviaOption[];
  correctAnswer: string;
  verse: string;
  explanation: string;
};

export type TriviaChapterPack = {
  chapter: number;
  title: string;
  description: string;
  progressKey: string;
  questions: TriviaQuestion[];
};

export type TriviaBookPack = {
  key: string;
  routeSlug: string;
  name: string;
  chapters: TriviaChapterPack[];
};

const OPTION_LABELS = ["A", "B", "C", "D"] as const;

function createQuestion(
  id: string,
  question: string,
  options: [string, string, string, string],
  correctAnswer: "A" | "B" | "C" | "D",
  verse: string,
  explanation: string,
): TriviaQuestion {
  return {
    id,
    question,
    options: options.map((text, index) => ({
      label: OPTION_LABELS[index],
      text,
    })),
    correctAnswer,
    verse,
    explanation,
  };
}

function createChapter(bookKey: string, chapter: number, description: string, questions: TriviaQuestion[]): TriviaChapterPack {
  return {
    chapter,
    title: `Chapter ${chapter}`,
    description,
    progressKey: getTriviaProgressBookKey(bookKey, chapter),
    questions,
  };
}

const MANUAL_TRIVIA_BOOKS: Record<string, TriviaBookPack> = {
  genesis: {
    key: "genesis",
    routeSlug: "genesis",
    name: "Genesis",
    chapters: [
      createChapter("genesis", 1, "Creation unfolds in order as God speaks light, sky, land, life, and humanity into place.", [
        createQuestion(
          "genesis-1-1",
          "What did God create on the first day?",
          ["The sun and moon", "Light", "Dry land", "Animals"],
          "B",
          "Genesis 1:3",
          "God said, 'Let there be light,' before the sun and moon were created later in the chapter.",
        ),
        createQuestion(
          "genesis-1-2",
          "On which day did God create the greater and lesser lights?",
          ["Day two", "Day three", "Day four", "Day six"],
          "C",
          "Genesis 1:14-19",
          "The sun, moon, and stars were placed in the heavens on the fourth day.",
        ),
        createQuestion(
          "genesis-1-3",
          "What did God create on the sixth day?",
          ["Birds and fish only", "Land animals and mankind", "Trees and plants", "The heavens"],
          "B",
          "Genesis 1:24-27",
          "Day six includes land animals and humanity made in the image of God.",
        ),
        createQuestion(
          "genesis-1-4",
          "In whose image were human beings created?",
          ["The angels", "The earth", "God", "Adam"],
          "C",
          "Genesis 1:26-27",
          "Genesis 1 says mankind was created in God's image, giving human life unique dignity.",
        ),
        createQuestion(
          "genesis-1-5",
          "What did God give humanity to rule over in Genesis 1?",
          ["Only the Garden of Eden", "Only the animals", "The fish, birds, and living things on earth", "Only the stars"],
          "C",
          "Genesis 1:28",
          "God blessed mankind and gave them dominion over the creatures of the earth.",
        ),
      ]),
      createChapter("genesis", 2, "God forms Adam, plants Eden, gives one command, and creates Eve as a fitting helper.", [
        createQuestion(
          "genesis-2-1",
          "What did God form man from in Genesis 2?",
          ["Water", "Dust of the ground", "Stone", "Light"],
          "B",
          "Genesis 2:7",
          "Adam was formed from the dust, and then God breathed into him the breath of life.",
        ),
        createQuestion(
          "genesis-2-2",
          "Where did God place the man after forming him?",
          ["Mount Ararat", "The land of Nod", "The garden in Eden", "Egypt"],
          "C",
          "Genesis 2:8, 15",
          "God placed Adam in the Garden of Eden to work it and keep it.",
        ),
        createQuestion(
          "genesis-2-3",
          "Which tree were Adam and Eve forbidden to eat from?",
          ["The tree of life", "The cedar of Lebanon", "The tree of the knowledge of good and evil", "The fig tree"],
          "C",
          "Genesis 2:16-17",
          "God gave one boundary in the garden: they were not to eat from the tree of the knowledge of good and evil.",
        ),
        createQuestion(
          "genesis-2-4",
          "Why did God say it was not good for man to be alone?",
          ["Because the garden was too large", "Because Adam needed a helper fit for him", "Because animals were dangerous", "Because Adam needed more work"],
          "B",
          "Genesis 2:18",
          "God said He would make a helper suitable for Adam.",
        ),
        createQuestion(
          "genesis-2-5",
          "How did God make the woman?",
          ["From clay", "From one of Adam's ribs", "From a tree", "From water"],
          "B",
          "Genesis 2:21-22",
          "God caused Adam to sleep and made Eve from his rib.",
        ),
      ]),
      createChapter("genesis", 3, "The serpent deceives, Adam and Eve sin, and God announces judgment along with the first promise of victory.", [
        createQuestion(
          "genesis-3-1",
          "Who tempted Eve in the garden?",
          ["Adam", "A serpent", "An angel", "Cain"],
          "B",
          "Genesis 3:1",
          "The serpent questioned God's word and tempted Eve.",
        ),
        createQuestion(
          "genesis-3-2",
          "What happened to Adam and Eve after they ate the fruit?",
          ["They immediately left Eden", "Their eyes were opened and they knew they were naked", "They became kings", "They forgot God's command"],
          "B",
          "Genesis 3:7",
          "Their eyes were opened, and shame entered the story.",
        ),
        createQuestion(
          "genesis-3-3",
          "What did Adam and Eve use to make coverings for themselves?",
          ["Animal skins", "Branches", "Fig leaves", "Grass"],
          "C",
          "Genesis 3:7",
          "They sewed fig leaves together after realizing they were naked.",
        ),
        createQuestion(
          "genesis-3-4",
          "What did God say the serpent would do to the seed of the woman?",
          ["Serve him forever", "Bruise his heel", "Build a city", "Guard the garden"],
          "B",
          "Genesis 3:15",
          "Genesis 3:15 points forward to conflict and ultimate victory over the serpent.",
        ),
        createQuestion(
          "genesis-3-5",
          "Why were Adam and Eve driven out of the garden?",
          ["They wanted more land", "They disobeyed God and were cut off from the tree of life", "They feared the animals", "They asked to leave"],
          "B",
          "Genesis 3:22-24",
          "God drove them out after sin so they would not eat from the tree of life in that fallen state.",
        ),
      ]),
      createChapter("genesis", 4, "Cain and Abel bring offerings, jealousy turns to murder, and violence begins spreading through the human family.", [
        createQuestion(
          "genesis-4-1",
          "What were the names of Adam and Eve's two sons in Genesis 4?",
          ["Seth and Enosh", "Cain and Abel", "Noah and Shem", "Esau and Jacob"],
          "B",
          "Genesis 4:1-2",
          "Genesis 4 introduces Cain and Abel as the first brothers.",
        ),
        createQuestion(
          "genesis-4-2",
          "Why was Abel's offering accepted by God?",
          ["Because it was offered in faith from the firstborn of his flock", "Because it was larger than Cain's", "Because Cain arrived late", "Because it came from the ground"],
          "A",
          "Genesis 4:4",
          "Abel brought the firstborn of his flock, and Hebrews later highlights his faith.",
        ),
        createQuestion(
          "genesis-4-3",
          "What sin did Cain commit against Abel?",
          ["He lied to him", "He stole from him", "He murdered him", "He banished him"],
          "C",
          "Genesis 4:8",
          "Cain rose up against his brother Abel and killed him.",
        ),
        createQuestion(
          "genesis-4-4",
          "How did Cain answer God when asked where Abel was?",
          ["I do not know; am I my brother's keeper?", "He went into the field", "He is with our father", "I buried him"],
          "A",
          "Genesis 4:9",
          "Cain answered with defiance after murdering his brother.",
        ),
        createQuestion(
          "genesis-4-5",
          "What kind of life did God say Cain would live after his judgment?",
          ["A king's life", "A quiet life in Eden", "A fugitive and wanderer", "A priest's life"],
          "C",
          "Genesis 4:12",
          "Cain's punishment was restless wandering away from the ground he had worked.",
        ),
      ]),
      createChapter("genesis", 5, "A long family line from Adam to Noah highlights the spread of death and the remarkable walk of Enoch with God.", [
        createQuestion(
          "genesis-5-1",
          "Whose family line is recorded in Genesis 5?",
          ["Cain's descendants", "Adam's descendants through Seth", "Noah's sons", "Abraham's household"],
          "B",
          "Genesis 5:1-3",
          "Genesis 5 traces the line from Adam through Seth down to Noah.",
        ),
        createQuestion(
          "genesis-5-2",
          "Who is specifically said to have walked with God?",
          ["Lamech", "Methuselah", "Enoch", "Jared"],
          "C",
          "Genesis 5:24",
          "Enoch stands out because he walked with God and was taken by Him.",
        ),
        createQuestion(
          "genesis-5-3",
          "What happened to Enoch at the end of his life?",
          ["He died in the flood", "God took him", "He moved to Egypt", "He built an ark"],
          "B",
          "Genesis 5:24",
          "Unlike the repeated phrase 'and he died,' Enoch was taken by God.",
        ),
        createQuestion(
          "genesis-5-4",
          "Who was the father of Noah?",
          ["Methuselah", "Lamech", "Jared", "Enosh"],
          "B",
          "Genesis 5:28-29",
          "Lamech named his son Noah and spoke of comfort from the cursed ground.",
        ),
        createQuestion(
          "genesis-5-5",
          "What pattern is repeated again and again throughout Genesis 5?",
          ["And he built a city", "And he reigned", "And he died", "And he offered a sacrifice"],
          "C",
          "Genesis 5",
          "The repeated refrain 'and he died' shows the reality of the curse after the fall.",
        ),
      ]),
      createChapter("genesis", 6, "Human wickedness fills the earth, but Noah finds grace and receives God's instructions to build the ark.", [
        createQuestion(
          "genesis-6-1",
          "How did God describe the wickedness of mankind in Genesis 6?",
          ["Occasional and minor", "Great in the earth, with evil thoughts continually", "Limited to one city", "Only among kings"],
          "B",
          "Genesis 6:5",
          "God saw that human wickedness was great and every intent of the heart was continually evil.",
        ),
        createQuestion(
          "genesis-6-2",
          "Who found grace in the eyes of the Lord?",
          ["Enoch", "Noah", "Lamech", "Shem"],
          "B",
          "Genesis 6:8",
          "Noah is singled out as the man who found grace before God.",
        ),
        createQuestion(
          "genesis-6-3",
          "How is Noah described in Genesis 6:9?",
          ["Perfect in his generations and walking with God", "A mighty hunter", "King over the earth", "The oldest man alive"],
          "A",
          "Genesis 6:9",
          "Noah is described as righteous and blameless among his contemporaries.",
        ),
        createQuestion(
          "genesis-6-4",
          "What did God command Noah to build?",
          ["A temple", "A tower", "An ark", "A city wall"],
          "C",
          "Genesis 6:14",
          "God told Noah to make an ark of gopher wood.",
        ),
        createQuestion(
          "genesis-6-5",
          "Why was God bringing a flood on the earth?",
          ["To water the crops", "Because the earth was filled with violence and corruption", "To help Noah travel", "To reveal a new land"],
          "B",
          "Genesis 6:11-13",
          "God announced judgment because the earth had become corrupt and full of violence.",
        ),
      ]),
      createChapter("genesis", 7, "Noah enters the ark, the flood begins, and the waters of judgment cover the earth.", [
        createQuestion(
          "genesis-7-1",
          "How old was Noah when the flood began?",
          ["500", "550", "600", "700"],
          "C",
          "Genesis 7:6",
          "Genesis 7 states that Noah was 600 years old when the floodwaters came.",
        ),
        createQuestion(
          "genesis-7-2",
          "How many days did it rain on the earth?",
          ["7", "30", "40", "150"],
          "C",
          "Genesis 7:12",
          "Rain fell for forty days and forty nights.",
        ),
        createQuestion(
          "genesis-7-3",
          "Who shut Noah in after he entered the ark?",
          ["Shem", "An angel", "The Lord", "Methuselah"],
          "C",
          "Genesis 7:16",
          "The Lord shut the door of the ark after Noah and his family entered.",
        ),
        createQuestion(
          "genesis-7-4",
          "What happened to every living thing outside the ark?",
          ["They moved to higher ground", "They survived in caves", "They died in the flood", "They became birds"],
          "C",
          "Genesis 7:21-23",
          "Everything on the dry land outside the ark perished in the flood.",
        ),
        createQuestion(
          "genesis-7-5",
          "How high did the waters rise over the mountains?",
          ["A little above them", "Fifteen cubits upward", "Seventy cubits", "Exactly to the peak"],
          "B",
          "Genesis 7:20",
          "The waters prevailed fifteen cubits upward over the mountains.",
        ),
      ]),
      createChapter("genesis", 8, "The floodwaters recede, Noah waits carefully, and the family finally steps out onto dry ground.", [
        createQuestion(
          "genesis-8-1",
          "What did God send over the earth as the floodwaters began to recede?",
          ["Lightning", "A great wind", "An earthquake", "Fire"],
          "B",
          "Genesis 8:1",
          "God caused a wind to pass over the earth, and the waters subsided.",
        ),
        createQuestion(
          "genesis-8-2",
          "What bird did Noah send out first from the ark?",
          ["A dove", "A raven", "An eagle", "A sparrow"],
          "B",
          "Genesis 8:7",
          "Noah first sent out a raven before sending the dove.",
        ),
        createQuestion(
          "genesis-8-3",
          "What did the dove bring back to Noah the second time it returned?",
          ["A stone", "A branch of cedar", "An olive leaf", "A grain of wheat"],
          "C",
          "Genesis 8:11",
          "The olive leaf showed that the waters had receded enough for plant life to appear.",
        ),
        createQuestion(
          "genesis-8-4",
          "On what mountains did the ark come to rest?",
          ["Sinai", "Moriah", "Ararat", "Carmel"],
          "C",
          "Genesis 8:4",
          "The ark rested on the mountains of Ararat.",
        ),
        createQuestion(
          "genesis-8-5",
          "What did Noah do after leaving the ark?",
          ["Built a city", "Offered burnt offerings to the Lord", "Planted a vineyard immediately", "Sent out more birds"],
          "B",
          "Genesis 8:20",
          "Noah built an altar and offered burnt offerings after leaving the ark.",
        ),
      ]),
      createChapter("genesis", 9, "God makes a covenant with Noah, gives the rainbow as a sign, and Noah's vineyard leads to family shame.", [
        createQuestion(
          "genesis-9-1",
          "What sign did God give of His covenant never again to destroy the earth with a flood?",
          ["A star", "A rainbow", "An altar", "A pillar of fire"],
          "B",
          "Genesis 9:13",
          "The rainbow was given as the sign of God's covenant with the earth.",
        ),
        createQuestion(
          "genesis-9-2",
          "What command did God repeat to Noah and his sons after the flood?",
          ["Build another ark", "Be fruitful and multiply", "Return to Eden", "Offer bread daily"],
          "B",
          "Genesis 9:1, 7",
          "God again told humanity to be fruitful and multiply.",
        ),
        createQuestion(
          "genesis-9-3",
          "What did Noah plant after the flood?",
          ["An olive grove", "A vineyard", "A field of wheat", "A cedar forest"],
          "B",
          "Genesis 9:20",
          "Noah became a man of the soil and planted a vineyard.",
        ),
        createQuestion(
          "genesis-9-4",
          "What happened after Noah drank from the fruit of the vineyard?",
          ["He fell asleep outside the ark", "He became drunk", "He sold the vineyard", "He moved to another land"],
          "B",
          "Genesis 9:21",
          "Noah became drunk and lay uncovered in his tent.",
        ),
        createQuestion(
          "genesis-9-5",
          "Which two sons respectfully covered Noah without looking on his nakedness?",
          ["Ham and Japheth", "Shem and Ham", "Shem and Japheth", "Cush and Mizraim"],
          "C",
          "Genesis 9:23",
          "Shem and Japheth walked backward and covered their father respectfully.",
        ),
      ]),
      createChapter("genesis", 10, "The nations spread out through the descendants of Noah after the flood.", [
        createQuestion(
          "genesis-10-1",
          "Whose descendants are listed in Genesis 10?",
          ["Abraham, Isaac, and Jacob", "Noah's sons Shem, Ham, and Japheth", "Adam, Seth, and Enosh", "Moses, Aaron, and Miriam"],
          "B",
          "Genesis 10:1",
          "Genesis 10 is often called the Table of Nations because it traces the families of Noah's sons.",
        ),
        createQuestion(
          "genesis-10-2",
          "Which man is described as a mighty hunter before the Lord?",
          ["Canaan", "Peleg", "Nimrod", "Joktan"],
          "C",
          "Genesis 10:8-9",
          "Nimrod is specifically called a mighty hunter before the Lord.",
        ),
        createQuestion(
          "genesis-10-3",
          "What kingdom is connected with Nimrod at the beginning?",
          ["Israel", "Babylon", "Rome", "Egypt"],
          "B",
          "Genesis 10:10",
          "Babel is named among the first cities of Nimrod's kingdom.",
        ),
        createQuestion(
          "genesis-10-4",
          "From which son of Noah did the line of Shem come?",
          ["The oldest son", "The youngest son", "The middle son only", "Genesis does not say"],
          "A",
          "Genesis 10:21",
          "Genesis 10 introduces Shem as the ancestor of important later lines in Scripture.",
        ),
        createQuestion(
          "genesis-10-5",
          "How does Genesis 10 describe the spread of the families after the flood?",
          ["By clans, languages, lands, and nations", "Only by cities", "Only by kings", "Only by tribes of Israel"],
          "A",
          "Genesis 10:5, 20, 31-32",
          "The chapter repeatedly describes the families spreading by clans, lands, and languages into nations.",
        ),
      ]),
      createChapter("genesis", 11, "Human pride builds Babel, God confuses the languages, and the family line narrows from Shem down to Abram.", [
        createQuestion(
          "genesis-11-1",
          "Why did the people begin building the tower of Babel?",
          ["To worship God", "To make a name for themselves", "To escape a flood", "To store grain"],
          "B",
          "Genesis 11:4",
          "The builders wanted to make a name for themselves instead of humbly obeying God.",
        ),
        createQuestion(
          "genesis-11-2",
          "What did God do to stop the building of Babel?",
          ["Sent a flood", "Destroyed the city with fire", "Confused their language", "Raised up a king"],
          "C",
          "Genesis 11:7-8",
          "God confused their language so they could no longer work together in pride.",
        ),
        createQuestion(
          "genesis-11-3",
          "What is the name of the city where God confused the people's language?",
          ["Ur", "Nineveh", "Babel", "Hebron"],
          "C",
          "Genesis 11:9",
          "The city was called Babel because there the Lord confused the language of all the earth.",
        ),
        createQuestion(
          "genesis-11-4",
          "Who was Abram's father?",
          ["Nahor", "Peleg", "Terah", "Laban"],
          "C",
          "Genesis 11:26",
          "Genesis 11 identifies Terah as the father of Abram, Nahor, and Haran.",
        ),
        createQuestion(
          "genesis-11-5",
          "From what city did Abram's family begin their journey?",
          ["Haran", "Jerusalem", "Ur of the Chaldees", "Gerar"],
          "C",
          "Genesis 11:31",
          "Terah took Abram and the family out of Ur of the Chaldees toward Canaan.",
        ),
      ]),
      createChapter("genesis", 12, "God calls Abram to leave home, promises blessing, and Abram's faith is mixed with fear in Egypt.", [
        createQuestion(
          "genesis-12-1",
          "Where did God tell Abram to go?",
          ["Back to Ur", "To Egypt", "To a land God would show him", "To Babylon"],
          "C",
          "Genesis 12:1",
          "God called Abram to leave his country and go to the land He would reveal.",
        ),
        createQuestion(
          "genesis-12-2",
          "What three major things did God promise Abram in Genesis 12?",
          ["A kingdom, a temple, and a law", "Land, descendants, and blessing", "Gold, armies, and fame", "Rain, crops, and peace"],
          "B",
          "Genesis 12:2-3",
          "God promised to make Abram a great nation and bless all families of the earth through him.",
        ),
        createQuestion(
          "genesis-12-3",
          "How old was Abram when he left Haran?",
          ["60", "75", "86", "100"],
          "B",
          "Genesis 12:4",
          "Abram was 75 years old when he departed from Haran.",
        ),
        createQuestion(
          "genesis-12-4",
          "Why did Abram go down into Egypt?",
          ["To visit family", "Because of war in Canaan", "Because there was a famine", "To build an altar"],
          "C",
          "Genesis 12:10",
          "Abram went to Egypt because the famine in the land was severe.",
        ),
        createQuestion(
          "genesis-12-5",
          "What did Abram tell Sarai to say in Egypt?",
          ["That she was his servant", "That she was his sister", "That she was his daughter", "That she was widowed"],
          "B",
          "Genesis 12:13",
          "Abram asked Sarai to say she was his sister because he feared for his life.",
        ),
      ]),
      createChapter("genesis", 13, "Abram and Lot separate peacefully, and God renews His promise of the land to Abram.", [
        createQuestion(
          "genesis-13-1",
          "Why did Abram and Lot separate?",
          ["They argued about worship", "The land could not support both households together", "Lot wanted Egypt", "God commanded immediate separation"],
          "B",
          "Genesis 13:6",
          "Their flocks and herds had become so large that the land could not support them living together.",
        ),
        createQuestion(
          "genesis-13-2",
          "What region did Lot choose for himself?",
          ["The mountains of Ararat", "The plain of Jordan near Sodom", "The Negev desert", "The land of Goshen"],
          "B",
          "Genesis 13:10-12",
          "Lot chose the well-watered plain of Jordan and moved his tents toward Sodom.",
        ),
        createQuestion(
          "genesis-13-3",
          "How is Sodom described in Genesis 13?",
          ["A city of peace", "A city of wisdom", "Wicked and sinful before the Lord", "A place of refuge"],
          "C",
          "Genesis 13:13",
          "Genesis says the men of Sodom were wicked and sinners before the Lord exceedingly.",
        ),
        createQuestion(
          "genesis-13-4",
          "After Lot separated, what did God tell Abram to do?",
          ["Return to Haran", "Lift up his eyes and look at the land", "Build an ark", "Go immediately to Egypt"],
          "B",
          "Genesis 13:14-15",
          "God told Abram to look north, south, east, and west at the land He was giving him.",
        ),
        createQuestion(
          "genesis-13-5",
          "What image did God use for Abram's descendants in Genesis 13?",
          ["Stars", "Sand", "Dust of the earth", "Waves of the sea"],
          "C",
          "Genesis 13:16",
          "God said Abram's descendants would be like the dust of the earth.",
        ),
      ]),
      createChapter("genesis", 14, "Abram rescues Lot from invading kings and is blessed by Melchizedek after the victory.", [
        createQuestion(
          "genesis-14-1",
          "Who was taken captive when the kings attacked Sodom?",
          ["Abram", "Sarai", "Lot", "Melchizedek"],
          "C",
          "Genesis 14:12",
          "Lot was living in Sodom and was carried away when the city was attacked.",
        ),
        createQuestion(
          "genesis-14-2",
          "How did Abram respond when he heard Lot had been taken?",
          ["He fled to Egypt", "He armed his trained servants and pursued the captors", "He made peace with the kings", "He waited for an army"],
          "B",
          "Genesis 14:14",
          "Abram armed the trained servants born in his house and went after the captors.",
        ),
        createQuestion(
          "genesis-14-3",
          "Who blessed Abram after the rescue?",
          ["The king of Egypt", "Melchizedek king of Salem", "Lot", "Noah"],
          "B",
          "Genesis 14:18-19",
          "Melchizedek, king of Salem and priest of the Most High God, blessed Abram.",
        ),
        createQuestion(
          "genesis-14-4",
          "What did Abram give Melchizedek?",
          ["A sheep", "A tenth of everything", "His sword", "The land of Sodom"],
          "B",
          "Genesis 14:20",
          "Abram gave Melchizedek a tenth of all the spoils.",
        ),
        createQuestion(
          "genesis-14-5",
          "Why did Abram refuse the goods offered by the king of Sodom?",
          ["He had already lost them", "He did not want the king of Sodom to say he made Abram rich", "He was required to tithe them", "Lot asked him not to take them"],
          "B",
          "Genesis 14:22-23",
          "Abram refused so that no one but God would get credit for blessing him.",
        ),
      ]),
      createChapter("genesis", 15, "God reassures Abram, promises descendants like the stars, and formally cuts a covenant with him.", [
        createQuestion(
          "genesis-15-1",
          "What did God tell Abram not to fear?",
          ["The famine", "The kings of the east", "Because God was his shield and great reward", "His old age"],
          "C",
          "Genesis 15:1",
          "God reassured Abram by saying He Himself would be Abram's shield and exceeding great reward.",
        ),
        createQuestion(
          "genesis-15-2",
          "Whom did Abram say would inherit his house if he remained childless?",
          ["Lot", "Ishmael", "Eliezer of Damascus", "Isaac"],
          "C",
          "Genesis 15:2",
          "Abram thought Eliezer of Damascus would become his heir.",
        ),
        createQuestion(
          "genesis-15-3",
          "What did God compare Abram's descendants to?",
          ["The dust of the ground", "The fish of the sea", "The stars of heaven", "The cedars of Lebanon"],
          "C",
          "Genesis 15:5",
          "God brought Abram outside and told him to count the stars if he could.",
        ),
        createQuestion(
          "genesis-15-4",
          "How does Genesis 15 describe Abram's response to God's promise?",
          ["He doubted and left", "He believed the Lord", "He demanded a sign first", "He told Sarai to wait"],
          "B",
          "Genesis 15:6",
          "Abram believed the Lord, and it was counted to him for righteousness.",
        ),
        createQuestion(
          "genesis-15-5",
          "What passed between the divided pieces in Abram's covenant vision?",
          ["A mighty angel", "A smoking furnace and a burning lamp", "A river of fire", "A cloud of locusts"],
          "B",
          "Genesis 15:17",
          "The smoking furnace and burning lamp symbolized God's presence sealing the covenant.",
        ),
      ]),
      createChapter("genesis", 16, "Sarai gives Hagar to Abram, conflict follows, and the angel of the Lord promises a son named Ishmael.", [
        createQuestion(
          "genesis-16-1",
          "Why did Sarai give Hagar to Abram?",
          ["Because Hagar was widowed", "Because Sarai had no children and tried to obtain a family through her", "Because God commanded it", "Because Abram asked for another wife"],
          "B",
          "Genesis 16:1-2",
          "Sarai tried to solve her barrenness by giving Hagar to Abram.",
        ),
        createQuestion(
          "genesis-16-2",
          "What happened after Hagar conceived?",
          ["She returned to Egypt", "She despised Sarai in her eyes", "Abram sent her away immediately", "She had twins"],
          "B",
          "Genesis 16:4",
          "Tension grew when Hagar looked down on Sarai after becoming pregnant.",
        ),
        createQuestion(
          "genesis-16-3",
          "Where did the angel of the Lord find Hagar?",
          ["By a well in the wilderness", "At Abram's altar", "Inside the tent", "In Sodom"],
          "A",
          "Genesis 16:7",
          "The angel found Hagar by a spring of water in the wilderness.",
        ),
        createQuestion(
          "genesis-16-4",
          "What name was Hagar told to give her son?",
          ["Isaac", "Eliezer", "Ishmael", "Midian"],
          "C",
          "Genesis 16:11",
          "The angel told Hagar to call the child Ishmael because the Lord had heard her affliction.",
        ),
        createQuestion(
          "genesis-16-5",
          "How old was Abram when Ishmael was born?",
          ["75", "86", "99", "100"],
          "B",
          "Genesis 16:16",
          "Abram was 86 years old when Hagar bore Ishmael.",
        ),
      ]),
      createChapter("genesis", 17, "God renews His covenant, changes Abram and Sarai's names, and gives circumcision as the sign.", [
        createQuestion(
          "genesis-17-1",
          "What new name did God give Abram?",
          ["Israel", "Abraham", "Abimelech", "Isaac"],
          "B",
          "Genesis 17:5",
          "God changed Abram's name to Abraham, meaning father of many nations.",
        ),
        createQuestion(
          "genesis-17-2",
          "What covenant sign did God command Abraham and his household to keep?",
          ["Passover", "Circumcision", "Sabbath", "Tithing"],
          "B",
          "Genesis 17:10-11",
          "Circumcision was given as the sign of God's covenant with Abraham.",
        ),
        createQuestion(
          "genesis-17-3",
          "What new name did God give Sarai?",
          ["Rachel", "Sarah", "Rebekah", "Miriam"],
          "B",
          "Genesis 17:15",
          "God changed Sarai's name to Sarah.",
        ),
        createQuestion(
          "genesis-17-4",
          "What son did God promise would be born to Sarah?",
          ["Ishmael", "Esau", "Isaac", "Jacob"],
          "C",
          "Genesis 17:19",
          "God said Sarah would bear a son and Abraham would call his name Isaac.",
        ),
        createQuestion(
          "genesis-17-5",
          "How old was Abraham when he was circumcised?",
          ["86", "90", "99", "100"],
          "C",
          "Genesis 17:24",
          "Abraham was 99 years old when he was circumcised.",
        ),
      ]),
      createChapter("genesis", 18, "Three visitors come to Abraham, Isaac is promised, and Abraham intercedes for Sodom.", [
        createQuestion(
          "genesis-18-1",
          "How many visitors appeared to Abraham by the oaks of Mamre?",
          ["One", "Two", "Three", "Twelve"],
          "C",
          "Genesis 18:2",
          "Abraham saw three men standing near him.",
        ),
        createQuestion(
          "genesis-18-2",
          "What did the visitors promise Sarah would have within a year?",
          ["A daughter", "A son", "A new homeland", "A great flock"],
          "B",
          "Genesis 18:10",
          "The visitors announced that Sarah would have a son at the appointed time.",
        ),
        createQuestion(
          "genesis-18-3",
          "How did Sarah respond when she heard the promise?",
          ["She sang", "She laughed", "She bowed silently", "She left the tent"],
          "B",
          "Genesis 18:12",
          "Sarah laughed within herself because she thought the promise was impossible.",
        ),
        createQuestion(
          "genesis-18-4",
          "What question did the Lord ask after Sarah laughed?",
          ["Why did Abraham build this altar?", "Is anything too hard for the Lord?", "Who shall inherit the land?", "Will the city stand forever?"],
          "B",
          "Genesis 18:14",
          "The Lord asked, 'Is anything too hard for the Lord?'",
        ),
        createQuestion(
          "genesis-18-5",
          "To what number did Abraham finally plead the Lord down for the sake of Sodom's righteous?",
          ["50", "25", "10", "1"],
          "C",
          "Genesis 18:32",
          "Abraham kept interceding until he asked whether the city would be spared for ten righteous people.",
        ),
      ]),
      createChapter("genesis", 19, "Angels rescue Lot, Sodom is destroyed, and Lot's family is divided by disobedience and fear.", [
        createQuestion(
          "genesis-19-1",
          "Who came to Sodom and stayed with Lot?",
          ["Three kings", "Two angels", "Abram's servants", "The sons of Noah"],
          "B",
          "Genesis 19:1",
          "The two angels arrived at Sodom in the evening and Lot welcomed them.",
        ),
        createQuestion(
          "genesis-19-2",
          "What did the men of Sodom demand regarding Lot's visitors?",
          ["That they join the feast", "That Lot send them out", "That they reveal their names", "That they bless the city"],
          "B",
          "Genesis 19:5",
          "The men of Sodom surrounded the house and demanded the visitors be brought out.",
        ),
        createQuestion(
          "genesis-19-3",
          "What happened to Lot's wife as they fled?",
          ["She became blind", "She became a pillar of salt", "She ran back to the city", "She disappeared in the storm"],
          "B",
          "Genesis 19:26",
          "Lot's wife looked back and became a pillar of salt.",
        ),
        createQuestion(
          "genesis-19-4",
          "What destroyed Sodom and Gomorrah?",
          ["A flood", "An earthquake", "Brimstone and fire from the Lord", "A foreign army"],
          "C",
          "Genesis 19:24",
          "The Lord rained brimstone and fire on Sodom and Gomorrah.",
        ),
        createQuestion(
          "genesis-19-5",
          "Who was rescued from Sodom because God remembered Abraham?",
          ["Abimelech", "Lot", "Ishmael", "Laban"],
          "B",
          "Genesis 19:29",
          "Lot was delivered when God overthrew the cities of the plain.",
        ),
      ]),
      createChapter("genesis", 20, "Abraham repeats his fear-driven lie, but God protects Sarah and warns Abimelech in a dream.", [
        createQuestion(
          "genesis-20-1",
          "To which king did Abraham say Sarah was his sister in Genesis 20?",
          ["Pharaoh", "Abimelech", "Melchizedek", "Chedorlaomer"],
          "B",
          "Genesis 20:2",
          "Abraham told Abimelech king of Gerar that Sarah was his sister.",
        ),
        createQuestion(
          "genesis-20-2",
          "How did God warn Abimelech about Sarah?",
          ["By an angel with a sword", "Through a prophet in the city", "In a dream by night", "By plague first"],
          "C",
          "Genesis 20:3",
          "God came to Abimelech in a dream and warned him that Sarah was Abraham's wife.",
        ),
        createQuestion(
          "genesis-20-3",
          "How does God describe Abraham to Abimelech?",
          ["A priest", "A king", "A prophet", "A judge"],
          "C",
          "Genesis 20:7",
          "God said Abraham was a prophet and would pray for Abimelech.",
        ),
        createQuestion(
          "genesis-20-4",
          "What had God done to Abimelech's household because of Sarah?",
          ["Taken their wealth", "Closed the wombs of the women", "Destroyed their crops", "Sent them into exile"],
          "B",
          "Genesis 20:18",
          "The Lord had fast closed all the wombs of Abimelech's household because of Sarah.",
        ),
        createQuestion(
          "genesis-20-5",
          "What happened after Abraham prayed for Abimelech?",
          ["His kingdom fell", "God healed Abimelech's household", "Sarah left Abraham", "Abraham moved away immediately"],
          "B",
          "Genesis 20:17",
          "God healed Abimelech, his wife, and his female servants after Abraham prayed.",
        ),
      ]),
      createChapter("genesis", 21, "Isaac is born, Hagar and Ishmael are sent away, and Abraham makes a covenant at Beersheba.", [
        createQuestion(
          "genesis-21-1",
          "What son was born to Abraham and Sarah in Genesis 21?",
          ["Ishmael", "Isaac", "Esau", "Joseph"],
          "B",
          "Genesis 21:1-3",
          "The promised son Isaac was born to Abraham and Sarah.",
        ),
        createQuestion(
          "genesis-21-2",
          "How old was Abraham when Isaac was born?",
          ["86", "90", "99", "100"],
          "D",
          "Genesis 21:5",
          "Abraham was 100 years old when Isaac was born.",
        ),
        createQuestion(
          "genesis-21-3",
          "Why did Sarah ask Abraham to send Hagar and Ishmael away?",
          ["They wanted to return to Egypt", "Ishmael mocked Isaac", "God told her to first", "There was not enough food"],
          "B",
          "Genesis 21:9-10",
          "Sarah saw Ishmael mocking and asked that Hagar and her son be sent away.",
        ),
        createQuestion(
          "genesis-21-4",
          "What did God provide for Hagar and Ishmael in the wilderness?",
          ["A city", "A well of water", "A flock of sheep", "An altar"],
          "B",
          "Genesis 21:19",
          "God opened Hagar's eyes and she saw a well of water.",
        ),
        createQuestion(
          "genesis-21-5",
          "What place was named because of the oath between Abraham and Abimelech?",
          ["Hebron", "Bethel", "Beersheba", "Gerar"],
          "C",
          "Genesis 21:31",
          "The place was called Beersheba because there the two made an oath.",
        ),
      ]),
      createChapter("genesis", 22, "God tests Abraham by commanding Isaac's sacrifice, but provides a ram in Isaac's place.", [
        createQuestion(
          "genesis-22-1",
          "Whom did God tell Abraham to offer as a burnt offering?",
          ["Ishmael", "Isaac", "Eliezer", "Lot"],
          "B",
          "Genesis 22:2",
          "God told Abraham to take Isaac, his beloved son, to the land of Moriah.",
        ),
        createQuestion(
          "genesis-22-2",
          "What question did Isaac ask Abraham on the way to the sacrifice?",
          ["Where are we going?", "Where is the lamb for the burnt offering?", "Why are the servants staying behind?", "Will mother come too?"],
          "B",
          "Genesis 22:7",
          "Isaac noticed the wood and fire and asked where the lamb was.",
        ),
        createQuestion(
          "genesis-22-3",
          "What did Abraham say God would provide?",
          ["Another altar", "A city", "A lamb for the burnt offering", "A priest"],
          "C",
          "Genesis 22:8",
          "Abraham answered that God Himself would provide a lamb.",
        ),
        createQuestion(
          "genesis-22-4",
          "What did Abraham offer instead of Isaac?",
          ["A bull", "A dove", "A ram caught in a thicket", "A goat from his flock"],
          "C",
          "Genesis 22:13",
          "God provided a ram caught in a thicket as the substitute.",
        ),
        createQuestion(
          "genesis-22-5",
          "What name did Abraham give the place of the sacrifice?",
          ["Jehovah-jireh", "Beersheba", "Bethel", "Peniel"],
          "A",
          "Genesis 22:14",
          "Abraham called the place 'The Lord will provide.'",
        ),
      ]),
      createChapter("genesis", 23, "Sarah dies, and Abraham purchases a burial cave in Canaan for his family.", [
        createQuestion(
          "genesis-23-1",
          "Who died in Genesis 23?",
          ["Rebekah", "Sarah", "Hagar", "Leah"],
          "B",
          "Genesis 23:1-2",
          "Genesis 23 opens with the death of Sarah.",
        ),
        createQuestion(
          "genesis-23-2",
          "From whom did Abraham seek to buy a burial place?",
          ["The Egyptians", "The Philistines", "The sons of Heth", "The Midianites"],
          "C",
          "Genesis 23:3-4",
          "Abraham asked the sons of Heth for a burial possession.",
        ),
        createQuestion(
          "genesis-23-3",
          "What specific field and cave did Abraham purchase?",
          ["The field of Gerar and cave of Zoar", "The field of Ephron with the cave of Machpelah", "The valley of Siddim and cave of Adullam", "The field of Salem and cave of Horeb"],
          "B",
          "Genesis 23:17-18",
          "Abraham bought the field of Ephron, including the cave of Machpelah.",
        ),
        createQuestion(
          "genesis-23-4",
          "How much silver did Abraham weigh out for the field?",
          ["100 shekels", "200 shekels", "400 shekels", "600 shekels"],
          "C",
          "Genesis 23:16",
          "Abraham weighed out 400 shekels of silver to Ephron.",
        ),
        createQuestion(
          "genesis-23-5",
          "Where was Sarah buried?",
          ["Near Beersheba", "In the cave of Machpelah near Hebron", "In Egypt", "On Mount Moriah"],
          "B",
          "Genesis 23:19",
          "Sarah was buried in the cave of Machpelah before Mamre, which is Hebron.",
        ),
      ]),
      createChapter("genesis", 24, "Abraham sends his servant to find a wife for Isaac, and Rebekah is brought into the covenant family.", [
        createQuestion(
          "genesis-24-1",
          "Why did Abraham send his servant to his own relatives?",
          ["To find more servants", "To find a wife for Isaac", "To buy land", "To escape famine"],
          "B",
          "Genesis 24:2-4",
          "Abraham wanted Isaac's wife to come from his own kindred rather than the Canaanites.",
        ),
        createQuestion(
          "genesis-24-2",
          "What sign did the servant ask God to show him at the well?",
          ["The woman would sing", "The woman would offer water to him and his camels", "The woman would bring gold", "The woman would know Isaac's name"],
          "B",
          "Genesis 24:14",
          "The servant asked that the chosen woman would offer water to him and his camels.",
        ),
        createQuestion(
          "genesis-24-3",
          "Who came to the well and fulfilled the servant's prayer?",
          ["Rachel", "Leah", "Rebekah", "Milcah"],
          "C",
          "Genesis 24:15-20",
          "Rebekah arrived and did exactly what the servant had asked God to show.",
        ),
        createQuestion(
          "genesis-24-4",
          "What relation was Rebekah to Abraham's family?",
          ["She was Lot's daughter", "She was Bethuel's daughter and Nahor's granddaughter", "She was Sarah's sister", "She was Melchizedek's daughter"],
          "B",
          "Genesis 24:24",
          "Rebekah was from Abraham's extended family through Nahor.",
        ),
        createQuestion(
          "genesis-24-5",
          "How did Isaac respond when Rebekah became his wife?",
          ["He feared her", "He sent her away", "He loved her and was comforted after his mother's death", "He built her a city"],
          "C",
          "Genesis 24:67",
          "Isaac loved Rebekah and was comforted after Sarah's death.",
        ),
      ]),
      createChapter("genesis", 25, "Abraham dies, Ishmael's line is noted, and Jacob and Esau are born with very different desires.", [
        createQuestion(
          "genesis-25-1",
          "Whom did Abraham marry after Sarah's death?",
          ["Hagar", "Keturah", "Rebekah", "Milcah"],
          "B",
          "Genesis 25:1",
          "Genesis 25 says Abraham took another wife named Keturah.",
        ),
        createQuestion(
          "genesis-25-2",
          "Who buried Abraham after he died?",
          ["Jacob and Esau", "Isaac and Ishmael", "Noah and Shem", "Eliezer and Lot"],
          "B",
          "Genesis 25:9",
          "Isaac and Ishmael buried Abraham in the cave of Machpelah.",
        ),
        createQuestion(
          "genesis-25-3",
          "What struggle happened before Jacob and Esau were born?",
          ["A famine in the land", "The children struggled within Rebekah", "Isaac became blind", "Abraham left Canaan"],
          "B",
          "Genesis 25:22",
          "Rebekah felt the twins struggling within her and asked the Lord about it.",
        ),
        createQuestion(
          "genesis-25-4",
          "Which twin was born first?",
          ["Jacob", "Esau", "They were born at the same moment", "Benjamin"],
          "B",
          "Genesis 25:25",
          "Esau came out first, and Jacob followed holding his heel.",
        ),
        createQuestion(
          "genesis-25-5",
          "What did Esau sell to Jacob for stew?",
          ["His inheritance", "His flocks", "His birthright", "His blessing"],
          "C",
          "Genesis 25:33",
          "Esau sold his birthright to Jacob for bread and red stew.",
        ),
      ]),
      createChapter("genesis", 26, "God blesses Isaac in Gerar, conflict rises over wells, and peace is made with Abimelech.", [
        createQuestion(
          "genesis-26-1",
          "Why did Isaac go to Gerar in Genesis 26?",
          ["To visit Abraham's grave", "Because there was a famine in the land", "To find a wife", "To escape war"],
          "B",
          "Genesis 26:1",
          "A famine drove Isaac toward Gerar in the land of the Philistines.",
        ),
        createQuestion(
          "genesis-26-2",
          "What did Isaac say about Rebekah because he was afraid?",
          ["That she was his servant", "That she was his sister", "That she was barren", "That she was from Egypt"],
          "B",
          "Genesis 26:7",
          "Like Abraham before him, Isaac said Rebekah was his sister out of fear.",
        ),
        createQuestion(
          "genesis-26-3",
          "Why did the Philistines envy Isaac?",
          ["He ruled over them", "He had become very prosperous", "He married Rebekah", "He built an altar"],
          "B",
          "Genesis 26:13-14",
          "Isaac became very great, and the Philistines envied his prosperity.",
        ),
        createQuestion(
          "genesis-26-4",
          "What name did Isaac give the well that meant 'room' because the Lord made space for him?",
          ["Esek", "Sitnah", "Rehoboth", "Beer-lahai-roi"],
          "C",
          "Genesis 26:22",
          "Isaac named the well Rehoboth, saying the Lord had made room for them.",
        ),
        createQuestion(
          "genesis-26-5",
          "Who made a covenant of peace with Isaac?",
          ["Laban", "Abimelech", "Esau", "Melchizedek"],
          "B",
          "Genesis 26:26-31",
          "Abimelech came to Isaac, and they swore an oath of peace together.",
        ),
      ]),
      createChapter("genesis", 27, "Jacob deceives Isaac, receives Esau's blessing, and Esau's hatred begins to grow.", [
        createQuestion(
          "genesis-27-1",
          "Which son did Isaac intend to bless first?",
          ["Jacob", "Esau", "Ishmael", "Joseph"],
          "B",
          "Genesis 27:1-4",
          "Isaac called Esau to prepare food so he could bless him.",
        ),
        createQuestion(
          "genesis-27-2",
          "Who helped Jacob deceive Isaac?",
          ["Leah", "Sarah", "Rebekah", "Rachel"],
          "C",
          "Genesis 27:5-17",
          "Rebekah guided Jacob in the plan to obtain Isaac's blessing.",
        ),
        createQuestion(
          "genesis-27-3",
          "How did Jacob make himself feel like Esau?",
          ["He changed clothes only", "He used goat skins on his hands and neck", "He put on armor", "He anointed himself with oil"],
          "B",
          "Genesis 27:16",
          "Goat skins made Jacob's skin feel like Esau's hairy skin.",
        ),
        createQuestion(
          "genesis-27-4",
          "What did Esau plan to do after learning Jacob had taken the blessing?",
          ["Leave the land forever", "Kill Jacob", "Serve Jacob faithfully", "Ask Isaac for another wife"],
          "B",
          "Genesis 27:41",
          "Esau resolved to kill Jacob after the days of mourning for Isaac.",
        ),
        createQuestion(
          "genesis-27-5",
          "Where did Rebekah send Jacob to escape Esau's anger?",
          ["Egypt", "Haran to Laban", "Sodom", "Bethel"],
          "B",
          "Genesis 27:43",
          "Rebekah told Jacob to flee to her brother Laban in Haran.",
        ),
      ]),
      createChapter("genesis", 28, "Jacob flees, dreams of a ladder to heaven, and God renews the covenant promises at Bethel.", [
        createQuestion(
          "genesis-28-1",
          "Where was Jacob sent to find a wife?",
          ["Egypt", "Canaan", "Padan-aram", "Gerar"],
          "C",
          "Genesis 28:2",
          "Isaac sent Jacob to Padan-aram to the house of Laban.",
        ),
        createQuestion(
          "genesis-28-2",
          "What did Jacob see in his dream at Bethel?",
          ["A burning bush", "A ladder reaching to heaven with angels ascending and descending", "A rainbow over the city", "A river of fire"],
          "B",
          "Genesis 28:12",
          "Jacob saw a ladder set up on the earth reaching to heaven.",
        ),
        createQuestion(
          "genesis-28-3",
          "What promise did God repeat to Jacob in the dream?",
          ["That he would never leave Canaan", "That the land would belong to him and his descendants", "That Esau would serve him immediately", "That he would have no troubles"],
          "B",
          "Genesis 28:13-14",
          "God repeated the land and descendants promises made to Abraham and Isaac.",
        ),
        createQuestion(
          "genesis-28-4",
          "What name did Jacob give the place where he had the dream?",
          ["Machpelah", "Beersheba", "Bethel", "Peniel"],
          "C",
          "Genesis 28:19",
          "Jacob called the place Bethel, meaning house of God.",
        ),
        createQuestion(
          "genesis-28-5",
          "What did Jacob set up as a pillar after the dream?",
          ["A branch", "A stone from under his head", "An altar of gold", "A wooden post"],
          "B",
          "Genesis 28:18",
          "Jacob took the stone he had used for his pillow and set it up as a pillar.",
        ),
      ]),
      createChapter("genesis", 29, "Jacob meets Rachel, is tricked by Laban, and ends up married to both Leah and Rachel.", [
        createQuestion(
          "genesis-29-1",
          "Whom did Jacob first meet by the well in Haran?",
          ["Leah", "Rachel", "Rebekah", "Dinah"],
          "B",
          "Genesis 29:9-10",
          "Rachel came with her father's sheep, and Jacob met her at the well.",
        ),
        createQuestion(
          "genesis-29-2",
          "How many years did Jacob agree to serve for Rachel?",
          ["3", "5", "7", "14"],
          "C",
          "Genesis 29:18",
          "Jacob agreed to serve Laban seven years for Rachel.",
        ),
        createQuestion(
          "genesis-29-3",
          "Whom did Laban give Jacob on the wedding night instead of Rachel?",
          ["Dinah", "Leah", "Bilhah", "Zilpah"],
          "B",
          "Genesis 29:23",
          "Laban substituted Leah for Rachel on the wedding night.",
        ),
        createQuestion(
          "genesis-29-4",
          "How much longer did Jacob serve in order to marry Rachel?",
          ["1 year", "3 years", "7 more years", "20 more years"],
          "C",
          "Genesis 29:27-30",
          "Jacob served another seven years for Rachel.",
        ),
        createQuestion(
          "genesis-29-5",
          "Which four sons did Leah bear in Genesis 29?",
          ["Reuben, Simeon, Levi, Judah", "Dan, Naphtali, Gad, Asher", "Issachar, Zebulun, Joseph, Benjamin", "Esau, Jacob, Judah, Levi"],
          "A",
          "Genesis 29:32-35",
          "Leah gave birth to Reuben, Simeon, Levi, and Judah in this chapter.",
        ),
      ]),
      createChapter("genesis", 30, "Jacob's household grows rapidly, and God prospers him even while tension remains in Laban's house.", [
        createQuestion(
          "genesis-30-1",
          "What did Rachel say when she saw she had no children?",
          ["Give me a new home", "Give me children, or else I die", "Send me back to my father", "Bless my flocks"],
          "B",
          "Genesis 30:1",
          "Rachel cried out to Jacob because she was barren.",
        ),
        createQuestion(
          "genesis-30-2",
          "Which maid did Rachel give to Jacob to bear children?",
          ["Zilpah", "Bilhah", "Hagar", "Leah"],
          "B",
          "Genesis 30:3",
          "Rachel gave Bilhah to Jacob as her maid.",
        ),
        createQuestion(
          "genesis-30-3",
          "What son did Rachel finally bear after God remembered her?",
          ["Judah", "Joseph", "Benjamin", "Isaac"],
          "B",
          "Genesis 30:22-24",
          "God remembered Rachel, and she gave birth to Joseph.",
        ),
        createQuestion(
          "genesis-30-4",
          "What arrangement did Jacob make with Laban about the flocks?",
          ["He would keep only white sheep", "The speckled and spotted animals would be his wages", "He would take half the silver", "He would leave empty-handed"],
          "B",
          "Genesis 30:32",
          "Jacob agreed that the speckled and spotted animals would be his wages.",
        ),
        createQuestion(
          "genesis-30-5",
          "How does Genesis 30 describe Jacob's prosperity?",
          ["He stayed poor", "He became exceedingly prosperous", "He lost all his animals", "He moved back to Canaan immediately"],
          "B",
          "Genesis 30:43",
          "Jacob increased greatly and had many flocks, servants, camels, and donkeys.",
        ),
      ]),
      createChapter("genesis", 31, "Jacob secretly leaves Laban, God protects him, and the two men make a covenant of separation.", [
        createQuestion(
          "genesis-31-1",
          "Why did Jacob decide to leave Laban?",
          ["Because of famine", "Because Laban's attitude had changed and God told him to return", "Because Rachel demanded it", "Because Esau invited him home"],
          "B",
          "Genesis 31:2-3",
          "Jacob noticed Laban's changed attitude, and God told him to return to his own land.",
        ),
        createQuestion(
          "genesis-31-2",
          "What did Rachel steal from her father when the family left?",
          ["Gold and silver", "The household idols", "Laban's staff", "His sheep"],
          "B",
          "Genesis 31:19",
          "Rachel stole her father's household idols.",
        ),
        createQuestion(
          "genesis-31-3",
          "How did God warn Laban before he confronted Jacob?",
          ["By a prophet", "In a dream", "By a pillar of fire", "Through Rebekah"],
          "B",
          "Genesis 31:24",
          "God came to Laban in a dream and told him not to speak either good or bad to Jacob.",
        ),
        createQuestion(
          "genesis-31-4",
          "Where did Rachel hide the household idols when Laban searched?",
          ["In a well", "Under the tent curtain", "In the camel's furniture", "In Jacob's bag"],
          "C",
          "Genesis 31:34",
          "Rachel hid the idols in the camel's furniture and sat on them.",
        ),
        createQuestion(
          "genesis-31-5",
          "What memorial did Jacob and Laban set up after making peace?",
          ["A well", "A heap of stones", "A golden altar", "A cedar tree"],
          "B",
          "Genesis 31:46-48",
          "They set up a heap of stones as a witness between them.",
        ),
      ]),
      createChapter("genesis", 32, "Jacob fears Esau, prays for help, and is renamed Israel after wrestling through the night.", [
        createQuestion(
          "genesis-32-1",
          "Why was Jacob afraid in Genesis 32?",
          ["Laban was chasing him", "Esau was coming with 400 men", "A famine had begun", "Rachel was missing"],
          "B",
          "Genesis 32:6-7",
          "Jacob feared because Esau was coming to meet him with 400 men.",
        ),
        createQuestion(
          "genesis-32-2",
          "How did Jacob prepare to meet Esau?",
          ["He hid alone in the hills", "He sent gifts ahead in droves", "He returned to Laban", "He built a city wall"],
          "B",
          "Genesis 32:13-20",
          "Jacob sent a generous gift ahead to appease Esau.",
        ),
        createQuestion(
          "genesis-32-3",
          "With whom did Jacob wrestle through the night?",
          ["Esau", "An angelic man", "Laban", "Isaac"],
          "B",
          "Genesis 32:24",
          "Jacob wrestled with a man through the night in a mysterious encounter with God.",
        ),
        createQuestion(
          "genesis-32-4",
          "What new name was Jacob given after the wrestling?",
          ["Judah", "Israel", "Joseph", "Bethel"],
          "B",
          "Genesis 32:28",
          "Jacob was renamed Israel because he had striven with God and men.",
        ),
        createQuestion(
          "genesis-32-5",
          "What name did Jacob give the place where he said he had seen God face to face?",
          ["Bethel", "Peniel", "Hebron", "Beersheba"],
          "B",
          "Genesis 32:30",
          "Jacob called the place Peniel because he believed he had seen God face to face.",
        ),
      ]),
      createChapter("genesis", 33, "Jacob and Esau meet in peace, and Jacob settles safely in the land.", [
        createQuestion(
          "genesis-33-1",
          "How did Jacob greet Esau when they met?",
          ["He hid behind the servants", "He bowed himself to the ground seven times", "He argued with him", "He sent Joseph first"],
          "B",
          "Genesis 33:3",
          "Jacob humbly bowed seven times as he approached Esau.",
        ),
        createQuestion(
          "genesis-33-2",
          "How did Esau respond when he saw Jacob?",
          ["He attacked him", "He ran to meet him and embraced him", "He ignored him", "He demanded payment"],
          "B",
          "Genesis 33:4",
          "Esau ran to Jacob, embraced him, and they both wept.",
        ),
        createQuestion(
          "genesis-33-3",
          "What did Jacob urge Esau to accept?",
          ["His tents", "His daughters", "His gift", "His birthright"],
          "C",
          "Genesis 33:10-11",
          "Jacob urged Esau to accept the present he had sent.",
        ),
        createQuestion(
          "genesis-33-4",
          "Where did Jacob first travel after parting from Esau?",
          ["Egypt", "Succoth", "Ur", "Babel"],
          "B",
          "Genesis 33:17",
          "Jacob journeyed to Succoth and built booths there.",
        ),
        createQuestion(
          "genesis-33-5",
          "What did Jacob do when he came safely to Shechem?",
          ["Built an altar called El-Elohe-Israel", "Married again", "Became king", "Buried Rachel"],
          "A",
          "Genesis 33:20",
          "Jacob erected an altar and called it El-Elohe-Israel.",
        ),
      ]),
      createChapter("genesis", 34, "Dinah is violated in Shechem, and Jacob's sons respond with violent deceit.", [
        createQuestion(
          "genesis-34-1",
          "Whose daughter is at the center of Genesis 34?",
          ["Rachel's daughter Dinah", "Leah's daughter Dinah", "Sarah's daughter", "Rebekah's daughter"],
          "B",
          "Genesis 34:1",
          "Dinah is identified as the daughter Leah bore to Jacob.",
        ),
        createQuestion(
          "genesis-34-2",
          "Who defiled Dinah?",
          ["Laban", "Esau", "Shechem son of Hamor", "Abimelech"],
          "C",
          "Genesis 34:2",
          "Shechem, the son of Hamor the Hivite, violated Dinah.",
        ),
        createQuestion(
          "genesis-34-3",
          "What condition did Jacob's sons require before agreeing to marriage with the men of the city?",
          ["They had to leave the land", "They had to pay silver only", "All the males had to be circumcised", "They had to serve Jacob for seven years"],
          "C",
          "Genesis 34:15",
          "Jacob's sons deceitfully required circumcision of all the males.",
        ),
        createQuestion(
          "genesis-34-4",
          "Which two sons of Jacob killed the men of the city?",
          ["Reuben and Judah", "Simeon and Levi", "Dan and Naphtali", "Joseph and Benjamin"],
          "B",
          "Genesis 34:25",
          "Simeon and Levi attacked the city and killed the males.",
        ),
        createQuestion(
          "genesis-34-5",
          "How did Jacob react to Simeon and Levi's violence?",
          ["He praised them", "He feared they had made him stink among the inhabitants of the land", "He moved to Egypt immediately", "He crowned them as leaders"],
          "B",
          "Genesis 34:30",
          "Jacob was troubled by the danger their violence had brought on the family.",
        ),
      ]),
      createChapter("genesis", 35, "Jacob returns to Bethel, idols are buried, and sorrow comes with Rachel's death.", [
        createQuestion(
          "genesis-35-1",
          "Where did God tell Jacob to return and dwell?",
          ["Hebron", "Bethel", "Gerar", "Egypt"],
          "B",
          "Genesis 35:1",
          "God told Jacob to go up to Bethel and dwell there.",
        ),
        createQuestion(
          "genesis-35-2",
          "What did Jacob command his household to do before going to Bethel?",
          ["Count the flocks", "Put away foreign gods and be clean", "Gather food for the road", "Send gifts to Esau"],
          "B",
          "Genesis 35:2",
          "Jacob told his household to put away foreign gods and purify themselves.",
        ),
        createQuestion(
          "genesis-35-3",
          "What happened to Rachel as Benjamin was born?",
          ["She was healed immediately", "She died in childbirth", "She moved back to Laban", "She had twins"],
          "B",
          "Genesis 35:18-19",
          "Rachel died while giving birth to Benjamin.",
        ),
        createQuestion(
          "genesis-35-4",
          "What name did Rachel call Benjamin before Jacob renamed him?",
          ["Ben-oni", "Manasseh", "Joseph", "Ephraim"],
          "A",
          "Genesis 35:18",
          "Rachel called him Ben-oni, but Jacob named him Benjamin.",
        ),
        createQuestion(
          "genesis-35-5",
          "Who buried Isaac at the end of Genesis 35?",
          ["Jacob only", "Esau only", "Jacob and Esau together", "Joseph and Benjamin"],
          "C",
          "Genesis 35:29",
          "Jacob and Esau buried Isaac together.",
        ),
      ]),
      createChapter("genesis", 36, "Esau's descendants are listed as the fathers and chiefs of Edom.", [
        createQuestion(
          "genesis-36-1",
          "What other name is used for Esau in Genesis 36?",
          ["Israel", "Edom", "Moab", "Midian"],
          "B",
          "Genesis 36:1",
          "Genesis 36 begins by saying, 'Now these are the generations of Esau, who is Edom.'",
        ),
        createQuestion(
          "genesis-36-2",
          "Why did Jacob and Esau's households separate permanently?",
          ["They were fighting again", "Their possessions were too great to dwell together", "God divided the land equally", "Esau was exiled"],
          "B",
          "Genesis 36:6-7",
          "Their riches and possessions were too great for them to live together.",
        ),
        createQuestion(
          "genesis-36-3",
          "Where did Esau settle?",
          ["The plains of Jordan", "Mount Seir", "Goshen", "Hebron"],
          "B",
          "Genesis 36:8",
          "Esau dwelt in Mount Seir.",
        ),
        createQuestion(
          "genesis-36-4",
          "What nation came from Esau's descendants?",
          ["Israel", "Egypt", "Edom", "Assyria"],
          "C",
          "Genesis 36:9",
          "Esau became the father of the Edomites in Mount Seir.",
        ),
        createQuestion(
          "genesis-36-5",
          "How does Genesis 36 mainly read?",
          ["As a story of war", "As a genealogy of Esau's line", "As a song of praise", "As a covenant renewal"],
          "B",
          "Genesis 36",
          "The chapter mainly records the genealogy, chiefs, and kings connected to Esau's line.",
        ),
      ]),
      createChapter("genesis", 37, "Joseph's dreams provoke jealousy, and his brothers sell him into slavery.", [
        createQuestion(
          "genesis-37-1",
          "Which son did Jacob especially love?",
          ["Judah", "Benjamin", "Joseph", "Reuben"],
          "C",
          "Genesis 37:3",
          "Joseph was Jacob's beloved son, born to him in old age.",
        ),
        createQuestion(
          "genesis-37-2",
          "What special gift did Jacob give Joseph?",
          ["A sword", "A coat of many colors", "A birthright document", "A ring"],
          "B",
          "Genesis 37:3",
          "Jacob gave Joseph a special coat that marked him out.",
        ),
        createQuestion(
          "genesis-37-3",
          "What did Joseph's dreams suggest about his future?",
          ["He would leave the family", "His family would bow down to him", "He would die young", "He would become a priest"],
          "B",
          "Genesis 37:7-10",
          "Joseph's dreams pointed to his family bowing before him.",
        ),
        createQuestion(
          "genesis-37-4",
          "What did Joseph's brothers do with him after throwing him into a pit?",
          ["They brought him home", "They sold him to Ishmaelite traders", "They made him king", "They sent him to Esau"],
          "B",
          "Genesis 37:28",
          "The brothers sold Joseph for twenty pieces of silver.",
        ),
        createQuestion(
          "genesis-37-5",
          "How did the brothers convince Jacob that Joseph was dead?",
          ["They buried an empty coffin", "They sent his coat dipped in blood", "They said he drowned", "They blamed wild men"],
          "B",
          "Genesis 37:31-33",
          "They stained Joseph's coat with blood so Jacob would think a wild beast had killed him.",
        ),
      ]),
      createChapter("genesis", 38, "Judah's family line is preserved through Tamar after deep failure and hidden sin.", [
        createQuestion(
          "genesis-38-1",
          "Whom did Judah marry in Genesis 38?",
          ["A daughter of the Canaanites", "Rebekah's sister", "An Egyptian woman", "Tamar"],
          "A",
          "Genesis 38:2",
          "Judah took a wife from the Canaanites named the daughter of Shua.",
        ),
        createQuestion(
          "genesis-38-2",
          "Why did Tamar remain childless after marrying Judah's sons?",
          ["There was a famine", "Er and Onan both died", "She returned home immediately", "Judah forbade children"],
          "B",
          "Genesis 38:7-10",
          "Er died for wickedness, and Onan also died after refusing to raise up offspring.",
        ),
        createQuestion(
          "genesis-38-3",
          "How did Tamar disguise herself when Judah came by the road?",
          ["As a servant", "As a widow in mourning", "As a prostitute", "As a foreign queen"],
          "C",
          "Genesis 38:14-15",
          "Tamar veiled herself so Judah thought she was a prostitute.",
        ),
        createQuestion(
          "genesis-38-4",
          "What pledge did Judah leave with Tamar?",
          ["His tent and staff only", "His signet, bracelets, and staff", "A flock of sheep", "A written promise"],
          "B",
          "Genesis 38:18",
          "Judah left his signet, cord, and staff as a pledge.",
        ),
        createQuestion(
          "genesis-38-5",
          "What did Judah say when Tamar's identity was revealed?",
          ["She has deceived me", "She has been more righteous than I", "She must leave the land", "I do not know her"],
          "B",
          "Genesis 38:26",
          "Judah admitted Tamar had been more righteous than he was.",
        ),
      ]),
      createChapter("genesis", 39, "Joseph prospers in Potiphar's house, resists temptation, and is imprisoned unjustly.", [
        createQuestion(
          "genesis-39-1",
          "To whom was Joseph sold in Egypt?",
          ["Pharaoh", "Potiphar", "The cupbearer", "The baker"],
          "B",
          "Genesis 39:1",
          "Joseph was sold to Potiphar, an officer of Pharaoh.",
        ),
        createQuestion(
          "genesis-39-2",
          "Why did Potiphar trust Joseph with all that he had?",
          ["Joseph was the oldest servant", "The Lord was with Joseph and he prospered", "Joseph was Egyptian", "Joseph had money"],
          "B",
          "Genesis 39:2-4",
          "Potiphar saw that the Lord was with Joseph and made him overseer of his house.",
        ),
        createQuestion(
          "genesis-39-3",
          "What temptation did Joseph resist repeatedly?",
          ["Stealing from Potiphar", "Bow to Egyptian gods", "Potiphar's wife asking him to lie with her", "Running away from prison"],
          "C",
          "Genesis 39:7-10",
          "Joseph refused the advances of Potiphar's wife.",
        ),
        createQuestion(
          "genesis-39-4",
          "What did Joseph leave behind when he fled from Potiphar's wife?",
          ["His ring", "His cloak", "His sandals", "His staff"],
          "B",
          "Genesis 39:12",
          "Joseph fled, leaving his garment in her hand.",
        ),
        createQuestion(
          "genesis-39-5",
          "Where was Joseph sent after Potiphar's wife accused him?",
          ["Back to Canaan", "Pharaoh's palace", "Prison", "A desert camp"],
          "C",
          "Genesis 39:20",
          "Joseph was cast into the prison where the king's prisoners were kept.",
        ),
      ]),
      createChapter("genesis", 40, "Joseph interprets the dreams of Pharaoh's cupbearer and baker while still in prison.", [
        createQuestion(
          "genesis-40-1",
          "Which two officials of Pharaoh were put in prison with Joseph?",
          ["The captain and the scribe", "The cupbearer and the baker", "The charioteer and the treasurer", "The chief shepherd and the butler"],
          "B",
          "Genesis 40:1-3",
          "Pharaoh's chief cupbearer and chief baker were imprisoned.",
        ),
        createQuestion(
          "genesis-40-2",
          "Who said that interpretations belong to God?",
          ["The cupbearer", "Joseph", "Potiphar", "Pharaoh"],
          "B",
          "Genesis 40:8",
          "Joseph told the prisoners that interpretations belong to God.",
        ),
        createQuestion(
          "genesis-40-3",
          "What did Joseph say would happen to the cupbearer in three days?",
          ["He would die", "He would escape to Canaan", "He would be restored to Pharaoh", "He would become a guard"],
          "C",
          "Genesis 40:13",
          "Joseph said Pharaoh would restore the cupbearer to his position.",
        ),
        createQuestion(
          "genesis-40-4",
          "What did Joseph say would happen to the baker in three days?",
          ["He would return home", "He would be executed", "He would be promoted", "He would escape prison"],
          "B",
          "Genesis 40:19",
          "Joseph told the baker that Pharaoh would lift up his head from off him.",
        ),
        createQuestion(
          "genesis-40-5",
          "What did the restored cupbearer do after leaving prison?",
          ["He immediately remembered Joseph", "He forgot Joseph", "He rescued Joseph", "He sent Joseph money"],
          "B",
          "Genesis 40:23",
          "The chief cupbearer did not remember Joseph, but forgot him.",
        ),
      ]),
      createChapter("genesis", 41, "Joseph interprets Pharaoh's dreams, is exalted in Egypt, and begins preparing for the famine.", [
        createQuestion(
          "genesis-41-1",
          "What did Pharaoh see in his first dream?",
          ["A ladder to heaven", "Seven fat cows and seven thin cows", "A great flood", "Stars bowing down"],
          "B",
          "Genesis 41:1-4",
          "Pharaoh dreamed of seven healthy cows and seven gaunt cows from the river.",
        ),
        createQuestion(
          "genesis-41-2",
          "What did Pharaoh see in his second dream?",
          ["A burning bush", "Seven good ears of grain and seven thin ears", "A ram in a thicket", "An angel with a sword"],
          "B",
          "Genesis 41:5-7",
          "The second dream featured good ears of grain swallowed by thin ears.",
        ),
        createQuestion(
          "genesis-41-3",
          "How did Joseph interpret the seven good years and seven bad years?",
          ["Seven years of war, then seven of peace", "Seven years of plenty, then seven years of famine", "Seven years of flood, then seven of drought", "Seven kings, then seven prophets"],
          "B",
          "Genesis 41:29-30",
          "Joseph said Egypt would have seven years of abundance followed by seven years of famine.",
        ),
        createQuestion(
          "genesis-41-4",
          "What position did Pharaoh give Joseph?",
          ["Captain of the guard", "Ruler over all Egypt under Pharaoh", "Chief priest", "Commander of the army only"],
          "B",
          "Genesis 41:40-41",
          "Pharaoh set Joseph over all the land of Egypt.",
        ),
        createQuestion(
          "genesis-41-5",
          "What were the names of Joseph's two sons born in Egypt?",
          ["Ephraim and Manasseh", "Perez and Zerah", "Shem and Ham", "Reuben and Simeon"],
          "A",
          "Genesis 41:50-52",
          "Joseph's sons were Manasseh and Ephraim.",
        ),
      ]),
      createChapter("genesis", 42, "Joseph's brothers come to Egypt for grain, and Joseph begins testing their hearts.", [
        createQuestion(
          "genesis-42-1",
          "Why did Jacob send his sons to Egypt?",
          ["To visit Joseph", "To buy grain", "To find wives", "To make peace with Pharaoh"],
          "B",
          "Genesis 42:1-2",
          "Jacob sent his sons to Egypt because there was grain there during the famine.",
        ),
        createQuestion(
          "genesis-42-2",
          "Which brother stayed behind with Jacob on the first trip?",
          ["Joseph", "Benjamin", "Reuben", "Judah"],
          "B",
          "Genesis 42:4",
          "Jacob did not send Benjamin with his brothers on the first trip.",
        ),
        createQuestion(
          "genesis-42-3",
          "How did Joseph treat his brothers when they arrived?",
          ["He immediately revealed himself", "He accused them of being spies", "He turned them away hungry", "He bowed before them"],
          "B",
          "Genesis 42:9",
          "Joseph recognized his brothers and accused them of being spies.",
        ),
        createQuestion(
          "genesis-42-4",
          "Which brother did Joseph keep in prison until they returned?",
          ["Reuben", "Judah", "Simeon", "Levi"],
          "C",
          "Genesis 42:24",
          "Joseph bound Simeon before their eyes.",
        ),
        createQuestion(
          "genesis-42-5",
          "What did the brothers find in their sacks on the way home?",
          ["Extra grain", "Their money returned", "Jewels from Egypt", "A letter from Pharaoh"],
          "B",
          "Genesis 42:27-28",
          "They found their money returned in their sacks and became afraid.",
        ),
      ]),
      createChapter("genesis", 43, "Judah offers himself as surety, and the brothers return to Egypt with Benjamin.", [
        createQuestion(
          "genesis-43-1",
          "Why did Jacob finally agree to send Benjamin to Egypt?",
          ["The famine was severe and they needed food", "Benjamin wanted to go", "Pharaoh demanded it in a letter", "Esau forced the decision"],
          "A",
          "Genesis 43:1-2, 11-14",
          "The famine grew so severe that Jacob had to let Benjamin go for the family to survive.",
        ),
        createQuestion(
          "genesis-43-2",
          "Who became surety for Benjamin before Jacob?",
          ["Reuben", "Simeon", "Judah", "Levi"],
          "C",
          "Genesis 43:8-9",
          "Judah personally pledged himself for Benjamin's safety.",
        ),
        createQuestion(
          "genesis-43-3",
          "What gifts did Jacob send with his sons to Egypt?",
          ["Horses and chariots", "Balm, honey, spices, myrrh, nuts, and almonds", "Silver trumpets", "A coat of many colors"],
          "B",
          "Genesis 43:11",
          "Jacob sent choice gifts from the land along with double money.",
        ),
        createQuestion(
          "genesis-43-4",
          "What happened when Joseph saw Benjamin?",
          ["He sent him away", "He was deeply moved and went to weep", "He accused him of theft", "He crowned him"],
          "B",
          "Genesis 43:29-30",
          "Joseph's compassion stirred for Benjamin, and he went aside to weep.",
        ),
        createQuestion(
          "genesis-43-5",
          "How much larger was Benjamin's portion at Joseph's table?",
          ["Twice as much", "Three times as much", "Five times as much", "Ten times as much"],
          "C",
          "Genesis 43:34",
          "Benjamin's portion was five times as much as the others'.",
        ),
      ]),
      createChapter("genesis", 44, "Joseph's silver cup is planted in Benjamin's sack, and Judah pleads to take Benjamin's place.", [
        createQuestion(
          "genesis-44-1",
          "What special item did Joseph hide in Benjamin's sack?",
          ["A gold ring", "A silver cup", "A royal scroll", "His signet"],
          "B",
          "Genesis 44:2",
          "Joseph commanded that his silver cup be placed in Benjamin's sack.",
        ),
        createQuestion(
          "genesis-44-2",
          "What was the brothers' first reaction when they were accused of stealing the cup?",
          ["They ran away", "They defended their innocence and offered death for the thief", "They blamed Benjamin", "They attacked the steward"],
          "B",
          "Genesis 44:7-9",
          "They strongly denied the accusation and said the guilty one should die.",
        ),
        createQuestion(
          "genesis-44-3",
          "In whose sack was the cup found?",
          ["Reuben's", "Judah's", "Benjamin's", "Simeon's"],
          "C",
          "Genesis 44:12",
          "The cup was found in Benjamin's sack as Joseph had arranged.",
        ),
        createQuestion(
          "genesis-44-4",
          "How did the brothers respond when the cup was found?",
          ["They abandoned Benjamin", "They tore their clothes and returned to the city", "They laughed", "They attacked the steward"],
          "B",
          "Genesis 44:13",
          "The brothers tore their clothes in grief and returned together.",
        ),
        createQuestion(
          "genesis-44-5",
          "Who offered to remain as a slave in Benjamin's place?",
          ["Reuben", "Joseph", "Judah", "Levi"],
          "C",
          "Genesis 44:33",
          "Judah pleaded to stay behind as a slave instead of Benjamin.",
        ),
      ]),
      createChapter("genesis", 45, "Joseph reveals himself to his brothers and declares that God sent him ahead to preserve life.", [
        createQuestion(
          "genesis-45-1",
          "What did Joseph finally tell his brothers in Genesis 45?",
          ["I am your ruler", "I am Joseph", "I forgive you later", "Return to Canaan alone"],
          "B",
          "Genesis 45:3",
          "Joseph revealed his identity by saying, 'I am Joseph.'",
        ),
        createQuestion(
          "genesis-45-2",
          "How did Joseph explain God's purpose in sending him to Egypt?",
          ["To make him wealthy", "To preserve life", "To punish the brothers immediately", "To start a war"],
          "B",
          "Genesis 45:5-7",
          "Joseph said God sent him before them to preserve life and save many people.",
        ),
        createQuestion(
          "genesis-45-3",
          "Where did Joseph tell his family to come live?",
          ["Jerusalem", "Goshen", "Babel", "Mount Seir"],
          "B",
          "Genesis 45:10",
          "Joseph instructed them to dwell in the land of Goshen.",
        ),
        createQuestion(
          "genesis-45-4",
          "How did Pharaoh respond when he heard Joseph's family was coming?",
          ["He was angry", "He approved and offered the best of the land", "He imprisoned the brothers", "He demanded silver"],
          "B",
          "Genesis 45:16-18",
          "Pharaoh was pleased and invited Joseph's family to take the best of Egypt.",
        ),
        createQuestion(
          "genesis-45-5",
          "What did Joseph tell his brothers not to do on the journey home?",
          ["Do not stop to rest", "Do not quarrel on the way", "Do not tell Jacob the truth", "Do not bring Benjamin back"],
          "B",
          "Genesis 45:24",
          "Joseph sent them away with the instruction not to fall out along the way.",
        ),
      ]),
      createChapter("genesis", 46, "Jacob journeys to Egypt, God reassures him, and the family line is listed as it enters the land.", [
        createQuestion(
          "genesis-46-1",
          "Where did God speak to Jacob before he went down to Egypt?",
          ["Bethel", "Hebron", "Beersheba", "Gerar"],
          "C",
          "Genesis 46:1-2",
          "Jacob offered sacrifices at Beersheba, and God spoke to him in visions of the night.",
        ),
        createQuestion(
          "genesis-46-2",
          "What did God tell Jacob about going to Egypt?",
          ["Do not go there", "Go down there, for I will make of you a great nation", "Go only for a few days", "Return immediately after seeing Joseph"],
          "B",
          "Genesis 46:3",
          "God told Jacob not to fear going to Egypt because He would make him a great nation there.",
        ),
        createQuestion(
          "genesis-46-3",
          "Which son did Jacob send ahead to Joseph to show the way to Goshen?",
          ["Reuben", "Judah", "Benjamin", "Levi"],
          "B",
          "Genesis 46:28",
          "Jacob sent Judah ahead to Joseph to direct the family to Goshen.",
        ),
        createQuestion(
          "genesis-46-4",
          "How did Joseph react when he met Jacob again?",
          ["He bowed silently", "He fell on his neck and wept", "He accused him of waiting too long", "He sent him to Pharaoh first"],
          "B",
          "Genesis 46:29",
          "Joseph embraced his father and wept on his neck for a good while.",
        ),
        createQuestion(
          "genesis-46-5",
          "What occupation did Joseph tell his brothers to mention to Pharaoh?",
          ["Builders", "Soldiers", "Shepherds", "Merchants"],
          "C",
          "Genesis 46:33-34",
          "Joseph told them to say they were shepherds so they could live in Goshen.",
        ),
      ]),
      createChapter("genesis", 47, "Jacob's family settles in Goshen while Joseph administers Egypt through the years of famine.", [
        createQuestion(
          "genesis-47-1",
          "Where were Joseph's family allowed to settle in Egypt?",
          ["Memphis", "Goshen", "The Nile Delta only", "Pharaoh's palace"],
          "B",
          "Genesis 47:6",
          "Pharaoh allowed Joseph's family to dwell in the best of the land, in Goshen.",
        ),
        createQuestion(
          "genesis-47-2",
          "How old did Jacob say he was when he stood before Pharaoh?",
          ["100", "110", "130", "147"],
          "C",
          "Genesis 47:9",
          "Jacob told Pharaoh the days of his pilgrimage were 130 years.",
        ),
        createQuestion(
          "genesis-47-3",
          "What did the Egyptians eventually give Joseph in exchange for food after their money was gone?",
          ["Only their gold", "Their livestock and then their land", "Their children", "Their temples"],
          "B",
          "Genesis 47:16-20",
          "Joseph accepted livestock first and later bought the land for Pharaoh during the famine.",
        ),
        createQuestion(
          "genesis-47-4",
          "What ongoing portion did Joseph establish for Pharaoh from the people's harvest?",
          ["A tenth", "A fifth", "A half", "Two thirds"],
          "B",
          "Genesis 47:24-26",
          "Joseph established that a fifth of the produce would belong to Pharaoh.",
        ),
        createQuestion(
          "genesis-47-5",
          "What request did Jacob make of Joseph before he died?",
          ["Make Benjamin ruler", "Bury me in Egypt", "Do not bury me in Egypt", "Return the family to Canaan immediately"],
          "C",
          "Genesis 47:29-30",
          "Jacob made Joseph swear to bury him with his fathers, not in Egypt.",
        ),
      ]),
      createChapter("genesis", 48, "Jacob blesses Joseph's sons and intentionally places the greater blessing on Ephraim.", [
        createQuestion(
          "genesis-48-1",
          "Whose two sons did Jacob bless in Genesis 48?",
          ["Judah's sons", "Joseph's sons", "Benjamin's sons", "Esau's sons"],
          "B",
          "Genesis 48:1-5",
          "Jacob blessed Joseph's two sons, Manasseh and Ephraim.",
        ),
        createQuestion(
          "genesis-48-2",
          "What were the names of Joseph's two sons?",
          ["Perez and Zerah", "Ephraim and Manasseh", "Reuben and Simeon", "Dan and Naphtali"],
          "B",
          "Genesis 48:1",
          "Joseph brought Manasseh and Ephraim to Jacob for blessing.",
        ),
        createQuestion(
          "genesis-48-3",
          "Which son was the firstborn, standing at Jacob's right hand?",
          ["Ephraim", "Manasseh", "Benjamin", "Asher"],
          "B",
          "Genesis 48:13-14",
          "Manasseh was the firstborn and was positioned at Jacob's right hand.",
        ),
        createQuestion(
          "genesis-48-4",
          "What did Jacob do with his hands when blessing the boys?",
          ["He kept them straight", "He crossed his hands", "He laid both on Manasseh", "He refused to bless them"],
          "B",
          "Genesis 48:14",
          "Jacob crossed his hands, placing his right hand on Ephraim.",
        ),
        createQuestion(
          "genesis-48-5",
          "Which grandson received the greater blessing?",
          ["Manasseh", "Ephraim", "They were blessed equally", "Benjamin"],
          "B",
          "Genesis 48:19",
          "Jacob said Ephraim, though younger, would become greater.",
        ),
      ]),
      createChapter("genesis", 49, "Jacob blesses and prophesies over his sons before dying in Egypt.", [
        createQuestion(
          "genesis-49-1",
          "Which son did Jacob say would have the scepter not depart from him?",
          ["Joseph", "Levi", "Judah", "Benjamin"],
          "C",
          "Genesis 49:10",
          "Jacob's blessing on Judah includes the promise of kingship.",
        ),
        createQuestion(
          "genesis-49-2",
          "Which two sons are rebuked for violence at Shechem?",
          ["Reuben and Judah", "Dan and Gad", "Simeon and Levi", "Joseph and Benjamin"],
          "C",
          "Genesis 49:5-7",
          "Jacob speaks sharply to Simeon and Levi because of their violence.",
        ),
        createQuestion(
          "genesis-49-3",
          "How is Joseph described in Jacob's blessing?",
          ["A barren branch", "A fruitful bough", "A ravening wolf", "A royal lion"],
          "B",
          "Genesis 49:22",
          "Jacob calls Joseph a fruitful bough by a well.",
        ),
        createQuestion(
          "genesis-49-4",
          "What animal is Judah compared to in Jacob's blessing?",
          ["An eagle", "A lion's whelp", "A serpent", "A deer"],
          "B",
          "Genesis 49:9",
          "Judah is compared to a lion's whelp.",
        ),
        createQuestion(
          "genesis-49-5",
          "Where did Jacob instruct his sons to bury him?",
          ["In Egypt", "At Bethel", "In the cave of Machpelah", "At Beersheba"],
          "C",
          "Genesis 49:29-30",
          "Jacob instructed his sons to bury him in the cave of Machpelah with his fathers.",
        ),
      ]),
      createChapter("genesis", 50, "Jacob is buried in Canaan, Joseph forgives his brothers, and Genesis closes with hope in God's providence.", [
        createQuestion(
          "genesis-50-1",
          "How long did the Egyptians mourn for Jacob?",
          ["7 days", "30 days", "40 days", "70 days"],
          "D",
          "Genesis 50:3",
          "The Egyptians mourned for Jacob seventy days.",
        ),
        createQuestion(
          "genesis-50-2",
          "Where was Jacob buried?",
          ["At Bethel", "In the cave of Machpelah", "In Goshen", "By the Nile"],
          "B",
          "Genesis 50:13",
          "Jacob was buried in the cave of Machpelah in the land of Canaan.",
        ),
        createQuestion(
          "genesis-50-3",
          "Why were Joseph's brothers afraid after Jacob died?",
          ["They feared famine", "They feared Joseph would repay them for selling him", "They feared Pharaoh", "They feared Esau"],
          "B",
          "Genesis 50:15",
          "The brothers worried Joseph would finally avenge himself after their father's death.",
        ),
        createQuestion(
          "genesis-50-4",
          "What famous words did Joseph say about the evil his brothers had done?",
          ["You meant it for good", "You meant evil against me, but God meant it for good", "The Lord has forgotten it", "Justice has been delayed"],
          "B",
          "Genesis 50:20",
          "Joseph declared that God had overruled their evil for good.",
        ),
        createQuestion(
          "genesis-50-5",
          "What did Joseph ask to be done with his bones when God visited Israel?",
          ["Bury them in Egypt", "Burn them on an altar", "Carry them up out of Egypt", "Place them by Pharaoh"],
          "C",
          "Genesis 50:25",
          "Joseph made the children of Israel swear to carry his bones out of Egypt.",
        ),
      ]),
    ],
  },
};

function formatAnswer(answer: string) {
  return answer
    .split(/[\s-]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(" ");
}

function buildOptions(correctAnswer: string, answers: string[]) {
  const distractors: string[] = [];

  for (const candidate of answers) {
    if (candidate === correctAnswer || distractors.includes(candidate)) {
      continue;
    }

    distractors.push(candidate);
    if (distractors.length === 3) {
      break;
    }
  }

  while (distractors.length < 3) {
    distractors.push(`Choice ${distractors.length + 2}`);
  }

  const optionTexts = [correctAnswer, ...distractors].sort((left, right) => left.localeCompare(right));
  return optionTexts.map((text, index) => ({
    label: OPTION_LABELS[index],
    text,
  }));
}

function createGeneratedQuestionId(bookKey: string, chapterNumber: number, questionNumber: number) {
  return `${bookKey}-chapter-${chapterNumber}-question-${questionNumber}`;
}

function buildGeneratedTriviaBook(bookKey: string): TriviaBookPack | null {
  const config = getChapterBasedTriviaBookByKey(bookKey);
  const scrambledBook = getScrambledBook(bookKey);

  if (!config || !scrambledBook) {
    return null;
  }

  return {
    key: config.key,
    routeSlug: config.routeSlug,
    name: config.title,
    chapters: scrambledBook.chapters.map((chapter) => {
      const formattedAnswers = chapter.questions.map((question) => formatAnswer(question.answer));

      return {
        chapter: chapter.chapter,
        title: `Chapter ${chapter.chapter}`,
        description: chapter.description,
        progressKey: getTriviaProgressBookKey(bookKey, chapter.chapter),
        questions: chapter.questions.slice(0, 5).map((question, index) => {
          const correctText = formatAnswer(question.answer);
          const options = buildOptions(correctText, formattedAnswers);

          return {
            id: createGeneratedQuestionId(bookKey, chapter.chapter, index + 1),
            question: `Which Bible word best matches this clue from ${config.title} ${chapter.chapter}?`,
            options,
            correctAnswer: options.find((option) => option.text === correctText)?.label ?? "A",
            verse: question.reference,
            explanation: question.clue,
          };
        }),
      };
    }),
  };
}

const TRIVIA_BOOKS = new Map(
  CHAPTER_BASED_TRIVIA_BOOK_CONFIG.map((book) => [book.key, MANUAL_TRIVIA_BOOKS[book.key] ?? buildGeneratedTriviaBook(book.key)]),
);

export function getTriviaBook(bookKey: string) {
  return TRIVIA_BOOKS.get(bookKey) ?? null;
}

export function getTriviaChapter(bookKey: string, chapterNumber: number) {
  return getTriviaBook(bookKey)?.chapters.find((chapter) => chapter.chapter === chapterNumber) ?? null;
}
