/**
 * Build step: write every chapter's study sections as static JSON under
 * public/study-notes/<book-slug>/<chapter>.json, and the index of chapters
 * that have notes to lib/chaptersWithNotes.generated.ts.
 *
 * Why: the Insight Card reader needs a chapter's notes to draw its underlines.
 * Fetching them from /api/study-notes means a server function that first
 * loads the whole-Bible aggregator (~33 MB) on a cold start, which is the
 * slowest part of opening any chapter other than Genesis 1. As static files
 * the notes come from the CDN like any image, and the chapter route can
 * decide which reader to show without any request at all.
 *
 * Runs automatically before `next build` (see "prebuild" in package.json),
 * so the files are always in step with the note sources in lib/. Run by hand
 * after adding notes locally:
 *   npx tsx scripts/generate-study-notes-static.ts
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BIBLE_READER_STUDY_SECTIONS } from "../lib/bibleReaderStudyNotes";

const slugOf = (book: string) => book.toLowerCase().trim().replace(/\s+/g, "-");
const OUT = join(process.cwd(), "public", "study-notes");

function main() {
  const byChapter = new Map<string, typeof BIBLE_READER_STUDY_SECTIONS>();
  for (const section of BIBLE_READER_STUDY_SECTIONS) {
    const key = `${section.book}:${section.chapter}`;
    const list = byChapter.get(key) || [];
    list.push(section);
    byChapter.set(key, list);
  }

  rmSync(OUT, { recursive: true, force: true });
  const index: Record<string, number[]> = {};
  for (const [key, sections] of byChapter) {
    const [book, chapterText] = key.split(":");
    const chapter = Number(chapterText);
    const dir = join(OUT, slugOf(book));
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, `${chapter}.json`), JSON.stringify({ sections }));
    (index[book] ||= []).push(chapter);
  }
  for (const chapters of Object.values(index)) chapters.sort((a, b) => a - b);

  const books = Object.keys(index).sort();
  const lines = [
    "// GENERATED by scripts/generate-study-notes-static.ts. Do not edit by hand.",
    "// Chapters that have study notes, by lower-case book name. Regenerated on",
    "// every build (prebuild), so it is always in step with lib/bibleReaderStudyNotes.",
    "",
    "export const CHAPTERS_WITH_NOTES: Record<string, number[]> = {",
    ...books.map((book) => `  ${JSON.stringify(book)}: [${index[book].join(", ")}],`),
    "};",
    "",
    "export function hasStudyNotes(book: string | null | undefined, chapter: number | null | undefined) {",
    "  const key = String(book || \"\").trim().toLowerCase().replace(/\\s+/g, \" \");",
    "  return (CHAPTERS_WITH_NOTES[key] || []).includes(Number(chapter));",
    "}",
    "",
  ];
  writeFileSync(join(process.cwd(), "lib", "chaptersWithNotes.generated.ts"), lines.join("\n"));
  console.log(`study-notes static: ${byChapter.size} chapters across ${books.length} books`);
}

main();
