-- The Testing of Joseph is no longer maintained as a 21-day story-fragment devotional.
--
-- Bible Buddy's daily habit system now uses:
-- ONE CHAPTER = ONE DAILY JOURNEY
--
-- Use this script instead:
--   npx tsx scripts/restructure-testing-of-joseph-chapter-journey.ts
--
-- That script updates The Testing of Joseph into a 14-day chapter-based journey:
--   Day 1  Genesis 37
--   Day 2  Genesis 38
--   Day 3  Genesis 39
--   Day 4  Genesis 40
--   Day 5  Genesis 41
--   Day 6  Genesis 42
--   Day 7  Genesis 43
--   Day 8  Genesis 44
--   Day 9  Genesis 45
--   Day 10 Genesis 46
--   Day 11 Genesis 47
--   Day 12 Genesis 48
--   Day 13 Genesis 49
--   Day 14 Genesis 50
--
-- This file intentionally performs no database writes.
SELECT 'Use scripts/restructure-testing-of-joseph-chapter-journey.ts for the current chapter-based Joseph devotional.' AS notice;
